dcos/dcos

- gen/installer/bash/Dockerfile.in
Fixes issue with installer failing to build with the following:
```
wget: error getting response: Connection reset by peer
The command '/bin/sh -c wget
https://github.com/andyshinn/alpine-pkg-glibc/releases/download/2.22-r5/glibc-2.22-r5.apk
&& apk --allow-untrusted add glibc-2.22-r5.apk && rm glibc-2.22-r5.apk
&& rm -rf /var/cache/apk/*' returned a non-zero code: 1
```
This is due to busybox wget in Alpine not supporting https. Use the installed curl instead.
> Use curl instead of wget

- pkgpanda/build/__init__.py
- pkgpanda/build/tests/test_build.py
Also makes it so
- the .json file can be empty impling an empty json dictionary
- A default / empty name variant doesn't need to exist
> Make buildinfo and treeinfo files mandatory (but allow them to be empty)

- pkgpanda/build/__init__.py
- pytest/test_release.py
- release/__init__.py
This removes the `--skip-build` option and gets `release create` to use the result of `pkgpanda.build.build_tree` directly rather than calling a helper which scrapes up artifacts.
General shape of the upstream work for pkgpanda:
1. Return structured information about the packages built and place that in the metadata.json
1. this PR
1. Returning more dictionaries of exactly what was built from build_tree (all the packages, what variants, what those package ids were, what the bootstrap variants are, what those bootstrap ids are). Broken into a separate step so that we have testing over the return structure change.
2. Add the notion of a "backing" / "upstream" repository. `pkgpanda` can refer to pre-built packages in this "upstream" repository just like it can local filesystem packages. It …
> Remove `--skip-build` and simplify `do_build_packages` to help prepare for "upstreams"

- packages/boost-system/build
- packages/boost-system/buildinfo.json
- packages/dcos-signal/extra/dcos-signal-ee.timer
- packages/dnspython/build
- packages/dnspython/buildinfo.json
Reverts dcos/dcos#19
Turns out the DNS is actually used
> Revert "Remove unused dnspython and boost-system packages"

- pkgpanda/build/__init__.py
Simplifies the code a bit, removes a bunch of `.get()` which all had to be consistent
Also fix a bug found while doing this: If a non-default build script was specified it wasn't included in the package id while the default build script still was.
> pkgpanda: Move loading defaults for buildinfo files to a single place

- pkgpanda/build/__init__.py
- pkgpanda/build/cli.py
- pkgpanda/build/tests/test_build.py
This is part of the groundwork to enable having a "variant" / "spin" of DC/OS which lives in a separate repository.
The end goal is that we can have a upstream source (which is specified the same as a "source" in a buildinfo) which will get cloned / checked out so that all the "build" and "buildinfo.json" files are available. The local "packages" directory will look like it is "overlaid" on top of that repository, allowing treeinfo.json and dependencies to cross the boundary. The local repository will also be able to replace at will packages in the upstream repository.
This consists of three main parts so far
- Adding the "package store" abstraction
- Increasing reliance on the abstraction for getting details rather manually traversing the filesystem
- Teaching `mkpanda tree` to be a …
> Teach pkgpanda to refer to a "package store" to get packages rather than filesystem assumptions

- pkgpanda/build/__init__.py
- pkgpanda/build/cli.py
- pkgpanda/build/src_fetchers.py
- pkgpanda/build/tests/test_build.py
- pkgpanda/util.py
- release/__init__.py
- release/storage/local.py
- Fix some code style nits
- Add a download_atomic to remove redundant code
- Always use PackageStore to get / ask about a package, whether that is from cache or local disk
- pass PackageStore to `build_tree()` and `make_bootstrap_tarball()` as an argument, simplifying the call signatures and making them in line with `build()`
- pass PackageStore to build_tree, make_bootstrap like it is
> Various cleanups allowing straightforward implementation for multiple packages dirs later

- gen/aws/templates/advanced/advanced-master.json
- gen/aws/templates/advanced/advanced-pub-agent.json
- gen/aws/templates/cloudformation.json
> Switch ELB port 80 from HTTP to TCP mode.

- gen/aws/templates/advanced/infra.json
- gen/aws/templates/cloudformation.json
AWS public agents were previously allowing traffic to ports up to 65535.
This change adjusts the public agent security group to only allow
traffic to ports controlled by the Mesos agent (ports below 32000).
This fixes a potential security issue, where internal DC/OS services
which listen these high range ports (including minuteman) could be
exposed to the outside world on the public agents.
> Restrict AWS public agents to mesos port ranges

- pkgpanda/build/__init__.py
- pkgpanda/util.py
These are pulled out of #52, are generally applicable even without those code changes. Pulling out so they can land before the rest.
> Better error messaging, correctness around accessing package tarballs

- packages/.gitignore
- pkgpanda/build/__init__.py
- pkgpanda/build/cli.py
- pkgpanda/build/src_fetchers.py
- pkgpanda/build/tests/test_build.py
- pytest/test_release.py
- release/__init__.py
This is useful for being able to have a distributon of DC/OS derived from the
open source DC/OS.
The distribution of DC/OS could do things like
- Add new DC/OS system packages which should be installed on every host
- Replace DC/OS components with alternate implementations
In another patch set the ability to have gen spit out more configuration files
will be added.
TODO:
> Teach packaging about "upstream" packages

- pytest/test_ssh_integration.py
- ssh/ssh_tunnel.py
Allows for simple, synchronous, persistent coordination
The purpose of this PR is to provide the utility for cleaner test implementation. Specifically:
-replacing parallel ssh implementation in test_util/installer_api_test.py
-replacing ssh async code thats executed synchronously in test_util/test_installer_ccm.py
-allowing the for the creation of a test_runner utility that runs test coordination commands on an arbitrary remote host with network visibility of a DCOS cluster
> Add ssh_tunnel.py to ssh module

- pkgpanda/build/cli.py
This moves around the logic to check not for a buildinfo.json file, but instead
whether or not the PackageStore found the package as having 1+ buildable
variants.
> Allow building packages that only have variants defined

- gen/__init__.py
- release/__init__.py
- Allow changing defaults which were set in gen/calc.py with a gen_extra/calc.py
- Allow adding additional content to `gen/{dcos-config.yaml,cloud-config.yaml}` by placing an identically named file in a `gen_extra` folder.
TODO:
> Allow downstream "variants" of DC/OS to include extra bits in gen

- ext/dcos-installer/dcos_installer/__init__.py
- ext/dcos-installer/dcos_installer/cli.py
- ext/dcos-installer/dcos_installer/installer_analytics.py
- ext/dcos-installer/setup.py
- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
@cmaloney @spahl @darkonie
Add analytics tracking to installer CLI (GUI will be next). 
Refactored the CLI a bit to use a dispatcher for the action arguments. This way we can call the tracker once in a clean method. I also moved the dispatcher to a new file cli.py as the groundwork to refactor the __init__.py (future work).
> Adding analytics tracking to installer

- ext/dcos-installer/dcos_installer/action_lib/__init__.py
Solution here is to statically assign the path for CentOS and RHEL servers that are version 7. I have also tested if this will break CentOS and It works well.
Docker explicitly mentions this as well in their installation instructions for RHEL here: https://docs.docker.com/engine/installation/linux/rhel/.
Second confirmation. $releasever is equal to '7' on CentOS and $releasever is equal to '7Server' on RHEL. Our fixes solves this problem during this point in time.
```
[centos@ip-172-31-4-230 ~]$ python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'
Loaded plugins: fastestmirror
{'arch': 'ia32e',
'basearch': 'x86_64',
'infra': 'genclo',
'releasever': '7',
'uuid': 'c6243c4d-d2b4-4ff0-9f6f-2ad3caa48c27'}
[centos@ip-172-31-4-230 ~]$ 
```
``` …
```
> Fixing RHEL7 --install-prereqs

- build_teamcity
- prep_teamcity
This makes it so the same script can be used to build downstream variants.
Also make TEAMCITY_BRANCH not being set be a hard error.
> make it so build_teamcity always uses the directory of the script.

- gen/installer/bash.py
- packages/.gitignore
- pkgpanda/build/__init__.py
- pkgpanda/build/tests/test_build.py
- pytest/test_release.py
- release/__init__.py
Results in cleaner build directories, less .gitignore being necessary.
> Move bootstrap to be cached in the cache/ directory

- packages/3dt/buildinfo.json
Use history service to retrieve a list of agents if leader.mesos dns record
is not available.
https://github.com/dcos/3dt/pull/14
DCOS-6435
> use latest 3dt

- pkgpanda/build/__init__.py
The work dir should be the packages directory so relative path file fetches work how a user might expect.
The output filename is in the cache directory.
PR #93 fixed part of the problem but not all of it, as can be seen in the build:  https://teamcity.mesosphere.io/viewLog.html?buildId=260177&tab=buildResultsDiv&buildTypeId=DcosIo_Dcos_Master
> Do a better job fixing cached bootstrap download

- ext/dcos-installer/dcos_installer/cli.py
- pytest/test_ssh_integration.py
- ssh/ssh_runner.py
- ssh/utils.py
- test_util/installer_api_test.py
Add a function to run before any command from a chain start executing. This
allows to prepare status json. For JsonDelegate we want to list all nodes
from a config right away. The status for a node will be changed as installer
proceeds.
> add prepare status json

- pkgpanda/build/__init__.py
- pkgpanda/util.py
Increases cross-platform compatibility, speeds things up by reducing the amount of forking and execing
> Remove all usage of `sha1sum` command

- ext/dcos-installer/dcos_installer/config/__init__.py
isinstance(True, int) returns true
isinstance(5, bool) returns false
> Move bool test above int test, because bool is a subclass of int

- pytest/test_ssh_integration.py
- ssh/ssh_tunnel.py
- test_util/installer_api_test.py
- test_util/test_installer_ccm.py
- test_util/test_runner.py
-transfers generic test-orchestration code from test_installer_ccm
-switches from awkward synchronous async ssh usage to sync ssh
-configures agents via single control node for easy compatibility
with clusters behind load balancers
> Create test_runner module

- pkgpanda/build/__init__.py
- pkgpanda/build/cli.py
This allows developers to run `mkpanda --recursive` to build a single package and all of it's dependencies which don't currently have builds.
Pulled out of #106
> Teach mkpanda to be able to recursively build packages

- gen/aws/templates/advanced/zen.json
AdminLocation is a parameter to the underlying infra template, but not configurable in the base template. This passes the value down through the CF stack.
> AdminLocation should be user configurable

- packages/adminrouter/build
- packages/dcos-oauth/extra/dcos-oauth.service
- packages/keepalived/build
- packages/logrotate/build
- packages/mesos-dns/extra/dcos-mesos-dns.service
- packages/spartan/extra/dcos-gen-resolvconf.service
- packages/spartan/extra/dcos-spartan-watchdog.service
It doesn't exist in many on-prem environments.
Internal JIRA: DCOS-6641
> Remove `/etc/environment` from all software

- build_local.sh
Without this there is no chance of it working. Note that the docker version must be the same as CI for the package builds to be cached still. With docker 1.11+ that should stop being an issue (the docker image ID format stabilized).
> Make cache work for build_local.sh

- pkgpanda/__init__.py
- pkgpanda/build/__init__.py
- pkgpanda/cli.py
- pkgpanda/tests/test_util.py
- By default we'll use systemd-sysusers to add users to the host (You can opt to manually add users instead). RPM, Deb, and Arch packaging all automatically have packages add users
- All DC/OS software users begin with `dcos_` to make them easy to find / distinguish.
> Work on making it so pkgpanda packages can have their software run as non-root

- gen/aws/templates/advanced/infra.json
It would be nice to have the route table IDs output from the CF template for use in VPN configurations.
Use Case:
- I have a VPC configured with all of the necessary VPNGateway/CustomerGateway/etc
- After creating DC/OS subnets and route tables, they are outputted from the CF template
- I then attach my VPNGateway to these route tables for VPN Route propagation
> Output route table ID's from infra.json

- NEWS
It is intended to document breaking changes / things which should be taken into account upgrading from the previous release. Actual release Errata should live in the DC/OS Documentation, this is for keeping track of things as we dev, then use it when we release to write up end user release notes
> Add a NEWS file

- build_local.sh
Adjust the build_local.sh script to create the venv outside of the
source dir so that tox syntax tests will continue to work after a build.
Alternatively, we could add an ignore/exclude rule for this build dir,
but moving it seems cleaner.
> Move build venv outside of source dir

- gen/calc.py
- gen/dcos-config.yaml
- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
This removes some assumptions relating to custom hook and isolator modules, which aren't currently being used in Open DC/OS. With this change, a separate config file* is designated for use by downstream builds. This allows keeping unused configuration logic out of Open DC/OS while making downstream changes a bit more flexible.
* `/opt/mesosphere/etc/mesos-slave-common-extras`
> Move extra module configuration into a separate EnvironmentFile

- gen/aws/templates/cloudformation.json
By adding its resource ID to the outputs of the CloudFormation stack.
The bucket is created with a "Retain" deletion policy, which means that destroying the stack won't delete the bucket. This change makes it possible to still delete the bucket in an automated way (figuring out the bucket name without the stack output [is much more complicated](https://github.com/dcos-labs/dcos-bootstrap/blob/1ec418ca52590199576a7d5999fad6e3d0545747/destroy.yml#L5-L9)).
> Allow to delete Exhibitor S3 bucket after the fact

- gen/installer/bash.py
Makes build output a little cleaner / more uniform
> Make dcos_generate_config.sh get put in the package cache directory

- packages/exhibitor/buildinfo.json
See: https://github.com/dcos/exhibitor/pull/2
Biggest things are
- some tooling fixes
- Update AWS SDK
> Update exhibitor to include the latest netflix/exhibitor changes.

- packages/exhibitor/extra/exhibitor_wait.py
There was a 60+ line traceback looking something like:
```
Jun 08 03:21:40 ip-10-10-0-126 exhibitor_wait.py[2928]: Traceback (most recent call last):
Jun 08 03:21:40 ip-10-10-0-126 exhibitor_wait.py[2928]: File "/opt/mesosphere/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
Jun 08 03:21:40 ip-10-10-0-126 exhibitor_wait.py[2928]: (self.host, self.port), self.timeout, **extra_kw)
Jun 08 03:21:40 ip-10-10-0-126 exhibitor_wait.py[2928]: File "/opt/mesosphere/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 91, in create_connection
Jun 08 03:21:40 ip-10-10-0-126 exhibitor_wait.py[2928]: raise err
Jun 08 03:21:40 ip-10-10-0-126 exhibitor_wait.py[2928]: File "/opt/mesosphere/lib/python3.4/site-packages/requests/packages/ …
```
> Update exhibitor_wait to not print an error on connection failure in requests

- gen/aws/calc.py
- gen/calc.py
- gen/dcos-config.yaml
- gen/ip-detect/aws_public.sh
- packages/adminrouter/buildinfo.json
- setup.py
In AWS, add an alternate implementation to get the instance Public IP from the metadata service.
- Update adminrouter to run `/opt/mesosphere/bin/detect_ip_public` still
cc @sargun
> Add detect_ip_public script, default to detect_ip script.

- ext/dcos-installer/dcos_installer/action_lib/utils.py
- pytest/test_ssh_unittest.py
- ssh/validate.py
DCOS-7596
- add optional `ssh_parallelism` option to a config file. The value must be
integer within 1..100 range.
- use default ssh_parallelism of 20 for DC/OS installer.
> bump concurrent ssh sessions for DC/OS installer

- test_util/test_runner.py
@cmaloney I think this should stop the spurious failures of VPC integration tests
> Forward ports to both public and private agents

- .gitignore
- gen/dcos-config.yaml
- packages/dcos-signal/buildinfo.json
- test_util/integration_test.py
- Updates to tests to POST from signal to test cache server
- Updates for security enhancements 
- Updates to reporters to do asynchronous report queries and multiple, generic reporter types
- Hard fails if cluster-id is not present
> Signal Service 1.1.5

- release/__init__.py
Otherwise the BuildError is stuck in the middle of a big exception which is a
bit harder to parse.
cc: @mellenburg
> Make it so when we get a pkgpanda build error before re-throwing

- test_util/test_installer_ccm.py
- test_util/test_runner.py
Exiting non-zero causes TeamCity to hard fail, even if the test which failed is muted.
This makes CI_FLAGS interpreted as a sign that we're running in a CI environment which understands
structured test results, and that the CI system will interpret failed test as a failed run.
So the new method is either "basic" environment where a non-zero exit indicates error, or
"everything ran successfully but some tests failed" indicated by test results being reported out and
the process exiting zero.
> if CI_FLAGS is set, exit with code 0, since the CI should pick up the results and fail that way

- gen/__init__.py
- release/__init__.py
- tox.ini
https://github.com/JetBrains/teamcity-messages/issues/103
Hopefully short term. It's nice to have these propogate up to the UI
> Remove teamcity-messages from code quality check

- ssh/ssh_tunnel.py
- test_util/docker/py.test/Dockerfile
- test_util/run-all
- test_util/test_runner.py
Refactors how VPC intgration tests are run
-creates pluggable python module for setting up and running
tests on bare remote hosts (or mesos masters)
-Adds CLI for running on arbitrary clusters as a tool
-bakes arguments and integration test into docker image
before every test => custom depdencies can be used in integration +
huge string of arguments does not need to be copied to rerun test
> Build docker images locally

- ssh/ssh_tunnel.py
Otherwise path name will be too long for a unix socket
> Use hash instead of r_user@host:port for ctrl path

- test_util/integration_test.py
- test_util/run-all
- test_util/test_installer_ccm.py
- test_util/test_runner.py
Required for activating AWS and Azure integration testing
> Allow setting provider in integration_test.py

- gen/installer/bash.py
Set the output back to normal after the invalid role, rather than printing the literal string `"{NORMAL}"`
> Fixing output format on invalid roles

- build_local.sh
Details of the bug are given here: DCOS-7837
The binary `pyvenv` is deprecated and  Python3.5 does not ship pyvenv. The correct way to use the module seems to be like `python -m venv`.
I installed Ubuntu 16.04, and it came with python3.5 by default, and it did not have the pyvenv command installed.
```
skumaran@hamming:~/workspace/dcos/dcos$ sudo ./build_local.sh 
+ set -o errexit -o pipefail
+ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
+ rm -rf /tmp/dcos_build_venv
+ export PYTHONUNBUFFERED=notemtpy
+ PYTHONUNBUFFERED=notemtpy
+ '[' '!' -f dcos-release.config.yaml ']'
+ cat
+ pyvenv /tmp/dcos_build_venv
./build_local.sh: line 33: pyvenv: command not found
skumaran@hamming:~/workspace/dcos/dcos$ …
```
> Instead of pyvenv command, invoke it as a module.

- gen/azure/cloud-config.yaml
* Fixes Docker issue with latest Azure Ubuntu 16.04 LTS image
(16.04.201606100) where the Docker daemon does not successfully start
during DC/OS boot up, causing Mesos Agents to also fail to start
* Update to Docker 1.11.2 and add new docker dependency: libltdl7
* Various Docker bug fixes, see:
https://github.com/docker/docker/releases
* Improve install times and protect against edge case of another process
locking the package database by adding exponential backoff to dpkg
install wrapper
* Restart docker.socket once docker.service is successfully started (a work around for Docker bug https://github.com/docker/docker/issues/18444)
> Update from Docker 1.11.0 to 1.11.2

- NEWS
- packages/exhibitor/build
- packages/exhibitor/buildinfo.json
- packages/exhibitor/extra/dcos-exhibitor.service
- packages/exhibitor/extra/start_exhibitor.py
- packages/marathon/buildinfo.json
- Remove resolv.conf mount, RuntimeDir workaround. Shouldn't be needed with the spartan approach
- make exhibitor configure ZK use a different config folder than where it's .jar lives
- Add creating the dir for zoo.cfg to start_exhibitor
- Update NEWS file
- Set java preferences di
- zookeeper is now configured to log to journald
- Remove marathon's dependency on the exhibitor package. It just needs it at runtime, and we did this recently for the mesos package as well in #239 
TODO before landing:
- Merge exhibitor patches.
> Make exhibitor non-root

- packages/dcos-oauth/extra/dcos-oauth.service
Cosmos service already uses `/var/lib/dcos/environment.proxy` for proxy settings. It would be good to use that for OAuth service as well instead of users having to edit other environment files
> Get proxy settings for OAuth service

- ext/dcos-installer/dcos_installer/action_lib/__init__.py
- ext/dcos-installer/dcos_installer/cli.py
- ext/dcos-installer/dcos_installer/cli_dispatcher.py
- pytest/test_installer_backend.py
- pytest/test_installer_init.py
Rather than do getattr() to see if the particular flag we want was set, followed by a dispatch into the local scope whatever has that name, instead add the argparse arguments, having them all set a '.action' ot the name of the option.
This fixes a couple things
- Remove unimplemented `--test` flag
- Remove default=False from store_true arguments
`store_true` and `store_false` both default appropriately.
See: https://docs.python.org/3/library/argparse.html
- Write a single dispatch which does a simple dictionary lookup to figure out which to run.
- Make it so that argparse building and dispatch can't get out of sync
- Add a `--version` mode / flag
> Make argument parsing be more direct / rely less on python run-time introspection

- packages/3dt/buildinfo.json
- test_util/integration_test.py
API should return snapshot file name along with its size. This will allow
to warn a user if snapshot file is too big.
https://github.com/dcos/3dt/pull/42
> add snapshot size

- gen/installer/aws.py
These got lost in #132, making it only into the AWS Advanced.
Fixes https://dcosjira.atlassian.net/browse/DCOS-200
> Add missing CoreOS units

- tox.ini
This reverts commit 1db7c13d56be01031dae7ed5cfff320165841cb3.
Should work now that https://github.com/JetBrains/teamcity-messages/pull/104 has landed.
> Revert "Remove teamcity-messages from code quality check"

- packages/octarine/build
- packages/octarine/buildinfo.json
- test_util/integration_test.py
octarine is a HTTP proxy that is additionally capable of resolving SRV records as if they were URLs. It can function both as a standard and transparent proxy. It was made for usage by the DC/OS CLI.
> octarine: Add octarine package

- test_util/integration_test.py
Last time this was closed. Vagrant runs the test without waiting long enough for the backend routing to be setup. We can alternatively sleep 5 seconds.
> Retry ensure routable

- gen/azure/templates/acs.json
Per discussions with Azure, we've agreed to pin to the LTS image
version. Historically these images stick around until Ubuntu EOL's the
release and if we continue to pin to 'latest' there will be a chance
that a new Ubuntu LTS build will break ACS.
> Pin to latest Ubuntu 16.04 LTS image

- packages/dcos-integration-test/extra/integration_test.py
- ssh/ssh_tunnel.py
- test_util/installer_api_test.py
-tests that use base_marathon_app need to be apart of registry_cluster fixture
-timeout must be settable in environment for installer API
-Suppressing error codes in test make it very hard to distinguish if the test failed or if the setup of the test failed. Rather, do the suppression  in TC (there is a specific option just for this case)
> Test fixes

- packages/3dt/buildinfo.json
- packages/dcos-integration-test/extra/integration_test.py
- pkgpanda/__init__.py
- pkgpanda/build/__init__.py
- pkgpanda/tests/test_util.py
3dt needs to read the journal. In order to do that it needs to be in
systemd-journal group. The issue is that coreos uses several backends for
users and groups. One is a regular /etc/passwd, /etc/groups and the other is
located under /usr/share/baselayout. If we try to append dcos_3dt user with
flag -G this will not work. (Tested on CoreOS beta (1068.3.0))
This seems to be a long running issue with CoreOS
https://github.com/coreos/bugs/issues/312
However if we try to change a user's primary group with -g flag all works
as expected.
> add group to make 3dt read journal

- README.md
README mentions the CI system but doesn't actually link to it even though it's public.
> Add link for "the CI system"

- packages/dvdcli/build
- packages/dvdcli/buildinfo.json
The Mesos volume isolator requires dvdcli 0.1.0. See
https://github.com/apache/mesos/blob/master/docs/docker-volume.md#pre-conditions.
> Downgrade dvdcli 0.2.0 -> 0.1.0

- gen/calc.py
- gen/dcos-config.yaml
Move mesos_isolation into a gen/calc variable so downstreams can extend it.
Also dropped the deprecated isolator name 'posix/disk' in favor of the new 'disk/du'.
> Move mesos_isolation into a gen/calc variable.

- README.md
A local build will end up shelling out with `git -C ...`.
This option is introduced in Git 1.8.5:
https://github.com/git/git/commit/44e1e4d67d5148c245db362cc48c3cc6c2ec82ca
Note: This is relevant because the default git package on CentOS 7 is version 1.8.3.
> Add minimum version to the local build git requirement.

- README.md
Additional information on how to build on Ubuntu 16.04 using Pyenv and
Python 3.4.4. FIXES: DCOS-254
> Add docs for Ubuntu 16.04 build dependencies

- packages/dcos-integration-test/extra/integration_test.py
The marathon ports API is weird, when you don't say  requirePors, the port being specified is the apps "servicePort", and the app gets launched / assigned a random port on the host. The tests ended up assigning multiple apps the same service port (Which gets caught by newer versions of marathon).
This switches all of the ports to always be dynamic from Marathon so we don't have to keep track of any interference. Another option would have been to use `requirePorts` and change the ports to be unique by hand.
> Move to dynamic ports for Minuteman and Octarine test apps

- packages/mesos-overlay-modules/buildinfo.json
* Added unit-test cases for `mesos-overlay-modules`. We can run `make
check`.
* Re-factored Agent and Master modules for the unit-test.
* Fixed a discrepancy in the information exposed in the
overlay-master/state` endpoint and the `overlay-agent/overlay` endpoint.
* Ensuring that `DOCKER-ISOLATION` bypass iptable rules are installed
only if the `docker-bridge` is enabled in the Agent module.
> Bumped `mesos-overlay-modules`

- packages/dcos-integration-test/extra/integration_test.py
- packages/dcos-signal/buildinfo.json
- test_util/run-all
Leverages new test flag which dumps to STDOUT so we can remove the usage of caching server.
> Remove Caching Test Server from Signal Test

- gen/calc.py
[REX-Ray will fail with an empty config file](https://teamcity.mesosphere.io/viewLog.html?buildId=341742&buildTypeId=DcosIo_Dcos_VagrantIntegrationTests_ProvisioningTestGenconfBashPr&tab=buildLog#_focus=1615). This PR adds a new config that [disables the default Docker module](http://rexray.readthedocs.io/en/v0.3.3/user-guide/config/#disabling-modules). This config will allow REX-Ray to start, and cause dvdcli to fail with `Unable to locate plugin: rexray`.
> Fix REX-Ray default config

- packages/dcos-integration-test/extra/conftest.py
after splitting out the test into multiple modules,
this should be session scoped as to share apps
between tests
> change scope of cluster fixture to session

- ext/dcos-installer/dcos_installer/config/__init__.py
- pytest/test_installer_init.py
Makes it easier to use from other places, easy to unit test.
cc: @lingmann (for the AWS CFN outputting), @malnick as original author
> Make stringify_config a helper function in the installer

- gen/calc.py
According to this NANOG post, it is unused: https://www.nanog.org/mailinglist/mailarchives/old_archive/2003-04/msg00762.html We're using 9/8 because with the way the overlay works, each agent  takes a fixed sized subnet. We want to be able to run at least 100 Docker container on each machine. The agent takes the aforementioned subnet and splits it in half between Docker and Mesos containes. There is a product requirement to support 100+ containers per machine using this feature. We also want to support 1000+ agents.
Therefore, a reasonable approach is to give the DC/OS cluster a /8 (9/8) that's unlikely to conflict. The middle two octects are per agent, so we can support ~2**16-Masters agents
This is the default, and those doing business in a 9/8 environment can modify the defaults for …
> Switch to using 9/8 for the subnet to assign agent subnets

- packages/logrotate/build
The default log rotation is way to small by mistake. This bumps it from 7*2000k to 7*256M
> Increase log rotation threshold for /var/log/mesos

- gen/dcos-config.yaml
- packages/bootstrap/extra/dcos_internal_utils/bootstrap/cli.py
- packages/marathon/build
- packages/spartan/buildinfo.json
Replaces #419. This one is from a repository where others can contribute / work on the patch.
Things that are left
- Agents need fixing (they don't boot currently)
- Bootstrap needs to be switched to use the zk addresses per https://github.com/dcos/dcos/pull/419#issuecomment-235978364
> Switch to zk addresses

- packages/bootstrap/extra/dcos_internal_utils/cli.py
- packages/boto/extra/cfn-signal
- packages/pkgpanda-role/build
This makes it so we have a state of what is currently running, instead of the state of what might be running.
cc: @alberts @orsenthil @lingmann @spahl
> Add a pkgpanda package that will say what roles are active

- gen/dcos-config.yaml
This limitation improves performance and memory consumption on hosts with large number of cores.
Schedulers running custom executors can still override this value by providing it in their executor definition.
> [Mesos] Limit the default number of libprocess worker threads for executors to 8.

- gen/dcos-config.yaml
- packages/marathon/build
Marathon/Metronome are now run by the dcos_marathon and dcos_metronome linux users. Their schedulers default to setting FrameworkInfo.user to the user that launched the scheduler process. Since this used to be 'root', many users may be accustomed to just having access to things. Let's set the default FrameworkInfo.user to 'root' for now, since that's more sane than 'dcos_marathon', which is supposed to be just for root Marathon itself. In the future, I'd recommend we default this to 'nobody' or a generic 'dcos' user.
Note that this user can always be overridden on a per-task basis.
> Run Marathon/Metronome tasks as 'root' by default.

- packages/3dt/buildinfo.json
- increase exhibitor response timeout to 11sec.
If a master node goes down, a get request to exhibitor may take up to 10 sec.
(http://127.0.0.1:8181/exhibitor/v1/cluster/status).
https://github.com/dcos/3dt/pull/50
- fix typo
https://github.com/dcos/3dt/pull/51
> 3dt bug fixes

- tox.ini
Reverts #411 
Flake8 3.0 and teamcity-messages are now compatible. See: https://github.com/JetBrains/teamcity-messages/releases/tag/v1.20
This reverts commit 0a39e4b4098ebf4928ee200388243277ce21c78d.
> Revert "Pin flake8==2.6.2 in tox"

- test_util/run-all
Allows vagrant integration tests to have tests muted.
> Exit 0 when under teamcity and tests fail

- gen/installer/aws.py
Fix issue introduced with 75985bf554754babd17ba11987d6d3b1f6794f1c  The
InternalMasterLoadBalancer and ElasticLoadBalancer attributes are not
available on the private and public agent templates. Resolve by only
rendering aws_dnsnames on the advanced master templates.
> Only render aws_dnsnames for master templates

- packages/dcos-image-deps/buildinfo.json
- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_applications.py
- packages/flask/build
- packages/flask/buildinfo.json
This adds `flask` as a dependency of `dcos-image-deps` and updates it to [version 0.11.1](http://flask.pocoo.org/docs/0.11/changelog/) to include this fix:
> Added support to serializing top-level arrays to flask.jsonify(). This introduces a security risk in ancient browsers. See [JSON Security](http://flask.pocoo.org/docs/0.11/security/#json-security) for details.
> Fix Pkgpanda API JSON response serialization

- tox.ini
Show in test summary reasons for any tests which were 'skipped'. For
example:
```
============================================================================= short test summary info =============================================================================
SKIP [2] /dcos/pytest/test_release.py:17: Skipping because there is no configuration in dcos-release.config.yaml
============================================================ 75 passed, 2 skipped, 1 pytest-warnings in 20.41 seconds =============================================================
_____________________________________________________________________________________ summary _____________________________________________________________________________________
```
> Report on py.test skip reasons

- pkgpanda/http/config.py
Review Request: @branden  
I noticed this while merging to master today. This change provides a reliable way point to the tempdir.
Linux
```
>>> WORK_DIR = os.path.join(tempfile.gettempdir(), 'pkgpanda_api')
>>> WORK_DIR
'/tmp/pkgpanda_api
```
Mac
```
>>> WORK_DIR = os.path.join(tempfile.gettempdir(), 'pkgpanda_api')
>>> WORK_DIR
'/var/folders/yx/tn9fxy1s4qz1vf2cbb5fwlw00000gn/T/pkgpanda_api'
```
> [minor] Use tempfile.tempdir in http.config instead of hardcoding to /tmp.

- setup.py
Azure broke recently with an exception in internal API calls
> Pin requests to 2.10.0 for mrest compatibility

- gen/template.py
You modified the config template and template.py throws a ValueError in your face? This adds an error message that hopefully helps you understand what went wrong.
> gen/template.py: add error message for unhandled switch/case value

- cloud_images/CHANGELOG.md
- cloud_images/README.md
- cloud_images/centos7/create_base_ami.sh
- cloud_images/centos7/create_dcos_ami.sh
- cloud_images/centos7/dcos_vol_setup.sh
- cloud_images/centos7/install_prereqs.sh
- cloud_images/centos7/packer.json
- gen/aws/templates/advanced/advanced-master.json
- gen/aws/templates/advanced/advanced-priv-agent.json
- gen/aws/templates/advanced/advanced-pub-agent.json
* Original work and reviews in #205 and #311.
* Now uses Overlay + XFS with the EL7 base image for Docker storage, so that problematic containers like `rastasheep/ubuntu-sshd` work properly.
* Updates AWS Advanced Templates default EL7 base image to use new AMI's.
* Automated builds are now available at https://teamcity.mesosphere.io/project.html?projectId=DcosIo_Dcos_BuildCloudBaseImages&tab=projectOverview
> Scripts to create DC/OS compatible cloud images

- packages/3dt/buildinfo.json
- packages/dcos-integration-test/extra/test_3dt.py
- add timeout to `detect_ip` script execution
https://github.com/dcos/3dt/pull/53
- add no cache functionality. This feature allows to get most recent health
status by getting endpoint with ?cache=0 parameter.
https://github.com/dcos/3dt/pull/52
- add `-pull-timeout` flag. Allows user to specify the get health status
timeout.
https://github.com/dcos/3dt/pull/54
- add a new 3dt test to make sure all units are healthy.
> use latest 3dt; update test

- NEWS
- gen/aws/templates/advanced/advanced-master.json
- gen/aws/templates/advanced/advanced-priv-agent.json
- gen/aws/templates/advanced/advanced-pub-agent.json
- gen/aws/templates/cloudformation.json
CoreOS 1068.9.0 includes:
* kernel: 4.6.3
* rkt: 1.7.0
* docker: 1.10.3
* etcd: 0.4.9, 2.3.2
* fleet: 0.11.7
* systemd: 229
See: https://coreos.com/releases/#1068.9.0 for full release notes.
> Update AWS templates to CoreOS Stable 1068.9.0

- gen/calc.py
Currently, we raise the wrong error:
```
except json.JSONDecodeError:
assert False, ...
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```
This exception is from simplejson module. We use json
> Replace simplejson exception

- packages/spartan/extra/gen_resolvconf.py
Should resolve https://dcosjira.atlassian.net/browse/DCOS-305
Basically: Systemd by default makes `/etc/resolv.conf` a symlink to `/run/systemd/resolve/resolv.conf` which is owned by systemd-resolved / systemd-networkd. Just writing directly to that file, there ends up being some "contested" / racy ownership.
By writing to a temp file next to that, and moving into place we do two things
1. The symlink gets replaced by a file so there isn't a race anymore
2. Changing resolv.conf is "atomic" / can't have partial writes and the like show up in the file things use.
> Do a rename to move our resolv.conf into place to wipe out symlinks

- gen/installer/bash.py
if the preflight gets executed on agent or public agent node, do not check
for master services.
https://dcosjira.atlassian.net/browse/DCOS-278
https://mesosphere.atlassian.net/browse/DCOS-9045
> exclude service check from preflight on agent node

- packages/mesos/extra/slave_logrotate_module.json
This change depends on https://reviews.apache.org/r/50766/
> [Mesos] Limit logrotate module libprocess worker threads to 2.

- packages/adminrouter/build
- packages/adminrouter/extra/dcos-adminrouter-agent-reload.service
- packages/dcos-integration-test/extra/test_composition.py
Previously it was failing every run because the `nginx reload` pointed to a
non-existent configuration file. This makes it point to the master configuration
on masters, and agent configuration on agents.
Should unblock #551
cc: @branden @jgehrcke @darkonie
> Split dcos-adminrouter-reload.service between masters and agents

- ssh/ssh_tunnel.py
[11:44:28]Traceback (most recent call last):
[11:44:28]  File "/teamcity/work/4b75044667254774/env/bin/ccm-deploy-test", line 11, in <module>
[11:44:28]    sys.exit(main())
[11:44:28]  File "/teamcity/work/4b75044667254774/env/lib/python3.4/site-packages/test_util/test_installer_ccm.py", line 318, in main
[11:44:28]    installer.postflight()
[11:44:28]  File "/teamcity/work/4b75044667254774/env/lib/python3.4/site-packages/test_util/installer_api_test.py", line 330, in postflight
[11:44:28]    self.run_cli_cmd('--postflight', expect_errors=expect_errors)
[11:44:28]  File "/teamcity/work/4b75044667254774/env/lib/python3.4/site-packages/test_util/installer_api_test.py", line 254, in run_cli_cmd
[11:44:28]    print(self.ssh(cmd))
[11:44:28]  File …
> ssh_tunnel: Fix byte / str type mismatch in logging

- gen/dcos-config.yaml
- packages/bootstrap/extra/dcos_internal_utils/cli.py
- packages/bootstrap/extra/dcos_internal_utils/exhibitor.py
In tests we can point it to a file which does exist. It is a parameter.
> Hard fail if master count file doesn't exist.

- gen/template.py
- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-integration-test/extra/test_endpoints.py
- packages/dcos-integration-test/extra/test_server.py
- test_util/ccm.py
- tox.ini
- Move flake8 excludes to the config line rather than command line arg (Easier to read / deal with)
- Add pep8-naming check
On my roadmap is enabling McCabe complexity checking, but that is more involved.
cc: @orsenthil @mellenburg 
The biggest thing this changes is a bunch of names in tests.
> Tweak flake8

- packages/marathon/build
- packages/metronome/build
- packages/metronome/buildinfo.json
> Make metronome, marathon run as non-root

- packages/bootstrap/extra/dcos_internal_utils/cli.py
- packages/minuteman/build
- packages/minuteman/buildinfo.json
- pkgpanda/__init__.py
- pkgpanda/actions.py
- pkgpanda/build/__init__.py
- pkgpanda/build/tests/test_build.py
- pkgpanda/cli.py
- pkgpanda/constants.py
- pkgpanda/docs/activating.md
- pkgpanda/docs/package_concepts.md
- pkgpanda/tests/integration_tests/test_setup.py
- pkgpanda/tests/resources/packages/mesos--0.22.0/pkginfo.json
**sysctl support in pkgpanda**
a) Each package will have it's sysctl setting in buildinfo.json
b) pkgpanda activate will gather that information and write it to a json file, at a known location:
`/opt/mesosphere/dcos-service-configuration.json`
c) When each package calls the bootstrap is invoked via it's systemd unit configuration, the boostrap utility will look for the service configuration requirements in `/opt/mesosphere/etc/dcos-service-configuration.json` and will do the required action before starting the service.
Please review @cmaloney , @spahl and @lingmann
> sysctl support in pkgpanda

- gen/dcos-config.yaml
- packages/mesos-overlay-modules/buildinfo.json
Removed any references to ZK URL from overlay module JSON config. 
The ZK URL for master and agent overlay module can now be learned from
'MESOS_ZK' on the master and 'MESOS_MASTER' on the agent. So
specifying these URLs in the JSON should not be necessary.
> Modified overlay modules to learn ZK URL from environment variables.

- ext/dcos-installer/dcos_installer/action_lib/__init__.py
CoreOS at least has /etc/lsb-release and /etc/oem-release which both have different info.
Should fix https://dcosjira.atlassian.net/browse/DCOS-105
> Detect CoreOS properly, limit to /etc/os-release which is the base standard

- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
Over time working on removing the "slave" terminology. See https://issues.apache.org/jira/browse/MESOS-1478 for some history
Fixes internal bug DCOS-6556
> Launch mesos-agent binary rather than mesos-slave binary

- gen/calc.py
- gen/dcos-config.yaml
- packages/mesos-overlay-modules/buildinfo.json
* The mesos-overlay-module on the agent will try to re-register with the master in case of a configuration failure, forcing it to reattempt the configuration of the overlay network. On failing more than four times (default value) it will bail.
> Updated mesos-overlay-modules with fix for configuration failure.

- ext/dcos-installer/dcos_installer/async_server.py
- ext/dcos-installer/dcos_installer/cli.py
- ext/dcos-installer/setup.py
- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- setup.py
- tests/test_installer_async_api.py
- tox.ini
This makes it so importing async_server doesn't cause a bunch of code to run, which helps separate concerns.
The aiohttp updates fix some issues that certain version mixes had with the tests resulting in a "has no method is_closing" error.
> Move app building into a function, upgrade to aiohttp 0.22.5

- packages/navstar/buildinfo.json
Navstar changes include changing the default for Navstar's HTTP API listener from `0.0.0.0` to `127.0.0.1` and updating Navstar's lashup version.
> Update Navstar Reference

- packages/dcos-oauth/build
- packages/dcos-oauth/extra/dcos_add_user.py
- tox.ini
`sudo -i /opt/mesosphere/bin/dcos_add_user.py`
TODO:
> Add a dcos_add_user.py script to add oauth users from the command line while in a shell on the masters

- test_util/azure_test_driver.py
- test_util/run-all
- test_util/test_installer_ccm.py
- test_util/test_runner.py
Now that some tests may be skipped when testing ACS deployments,
explicitly print out details on skipped tests just like we do with our
tox configuration for py.test.
Update every single invocation of py.test in the project to do `-rs -vv`
Pulled out of #591, with some missing cases fixed
> Details skip test

- packages/dcos-image/build
- packages/dcos-installer/build
- packages/dcos-installer/buildinfo.json
- packages/installer.treeinfo.json
- packages/treeinfo.json
No point in having it separate from dcos-image, both always get rebuilt in the same circumstances
> Remove dcos-installer package

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_composition.py
Cuts a minute off our integration testing time.
> Cleanup test_signal_service / move it to the non-caching 3dt endpoint

- gen/installer/aws.py
- gen/installer/azure.py
- release/__init__.py
This is work in making it so that on each of the artifacts we can attach some "metadata" which will make a nice page for people to sort through all the various template variations.
> Teach AWS, Azure templates to yield the templates directly

- packages/dcos-integration-test/extra/test_composition.py
- test_util/azure_test_driver.py
Update Azure integration tests to support ACS
* Determine the cluster IP configuration based on the detected Azure
resource types for the deployed cluster. This is required for testing
ACS templates which use VM Scale Sets which depend on a different API
for extracting IP configuration.
* Fail if required environment variables are not set correctly.
* Ensure template parameters are explicitly defined for those which we
depend on in the tests.
* Update tests to be correct, given the initial cluster configuration
(e.g. do not test for auth if oauth is disabled via template
parameters, skip the telemetry test if it was not enabled)
* Do not use the `master_lb` with the integration test, since this is
not a reachable address inside an ACS cluster.
> Update Azure integration tests to support ACS templates

- gen/installer/bash/dcos_generate_config.sh.in
There are no other uses of BUILD_DIR in the entire codebase
> Remove BUILD_DIR printing, doesn't particularly add a lot of value

- gen/azure/templates/acs.json
- gen/installer/azure.py
This adds a dedicated storage account for Exhibitor coordination state, also making it possible to use Premium LRS for the Agent OS disks. Previously, when a VM with Premium LRS storage was selected, Exhibitor would also be configured to use a Premium LRS account for storing coordination state via block blobs. However, this is not supported use of the Premium LRS service (see [Azure Premium Storage](https://azure.microsoft.com/en-us/documentation/articles/storage-premium-storage/)):
> Currently, Premium Storage does not support Azure Block Blobs, Azure Append Blobs, Azure Files, Azure Tables, or Azure Queues. Any other object placed in a Premium Storage account will be a Page Blob, and it will snap to one of the the supported provisioned sizes. Heance Premium Storage account is not meant …
> Use dedicated storage account for Exhibitor storage

- packages/cni/buildinfo.json
Fixed the namespace path check in `pkg/ns` package in the upstream `containernetworking/cni` repo:
https://github.com/containernetworking/cni/pull/290
Updating the CNI plugins package to reflect this PR.
Fixes https://dcosjira.atlassian.net/browse/DCOS-300
> Fixed namespace check in CNI package.

- cloud_images/CHANGELOG.md
- cloud_images/centos7/install_prereqs.sh
- ext/dcos-installer/dcos_installer/action_lib.py
- gen/aws/templates/advanced/advanced-master.json
- gen/aws/templates/advanced/advanced-priv-agent.json
- gen/aws/templates/advanced/advanced-pub-agent.json
- gen/aws/templates/cloudformation.json
- gen/azure/cloud-config.yaml
On a percentage of DC/OS agents (~5%) with Docker 1.11.2, the Daemon
will fail to start up with the following error:
> Error starting daemon: Error initializing network controller: Error
> creating default "bridge" network: failed to allocate gateway
> (172.17.0.1): Address already in use
This seems to be related to a Docker bug around the network controller
initialization, where the controller has allocated an ip pool and
persisted some state but not all of it. See:
* https://github.com/docker/docker/issues/22834
* https://github.com/docker/docker/issues/23078
This fix simply removes the docker0 interface if it exists before
starting the Docker daemon. This fix will need to be re-evaluated if we
want to enable the 1.12+ containerd live-restore like Docker options as
discussed in:
* …
> Fix for Docker 1.11.2 startup issue

- gen/installer/azure.py
- tests/test_release.py
Update the azure.html page to render links using the configured Azure
release location (dcosio.azureedge.net). FIXES: https://mesosphere.atlassian.net/browse/DCOS-9357
> Fix template links in azure.html

- packages/mesos-dns/buildinfo.json
Changes in this update:
* Rename IAM `secret` to `private_key`: https://github.com/mesosphere/mesos-dns/pull/465
* Stability improvements: https://github.com/mesosphere/mesos-dns/pull/461
* Fix crashes related to `labels.trimCut` problems: https://github.com/mesosphere/mesos-dns/pull/460
> Updating mesos-dns ref

- gen/aws/templates/cloudformation.json
This was inadvertently changed in 28e52bd6ffe8af5e49fcd2d12499ccc92476f2f9
That was supposed to just update the custom CentOS AMI, but caught the CoreOS
AMI as well
cc: @lingmann
> Change AWS Simple template AMI back to CoreOS

- release/__init__.py
This fixes failures when older versions of Docker are used. The format is pretty different, here's an example of the output from older versions:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```
And here's what it looks like from newer versions:
```
Client:
Version:      1.12.0
API version:  1.24
Go version:   go1.6.3
Git commit:   8eab29e
Built:        Thu Jul 28 23:54:00 2016
OS/Arch:      darwin/amd64
Server:
Version:      1.12.1
API version:  1.24
Go version:   go1.6.3
Git commit:   23cf638
Built:        Thu Aug 18 17:52:38 2016
OS/Arch:      linux/amd64
``` …
> Support getting the docker client version for older versions of docker

- .isort.cfg
- ext/dcos-installer/dcos_installer/action_lib.py
- ext/dcos-installer/dcos_installer/async_server.py
- ext/dcos-installer/dcos_installer/backend.py
- ext/dcos-installer/dcos_installer/cli.py
- ext/dcos-installer/dcos_installer/config.py
- ext/dcos-installer/dcos_installer/config_util.py
- ext/dcos-installer/dcos_installer/installer_analytics.py
- gen/test_template.py
- packages/bootstrap/extra/dcos_internal_utils/exhibitor.py
- packages/bootstrap/extra/tests/test_bootstrap.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/exhibitor/extra/start_exhibitor.py
- packages/spartan/extra/gen_resolvconf.py
- pkgpanda/build/cli.py
- pkgpanda/cli.py
- pkgpanda/http/__init__.py
- pkgpanda/tests/integration_tests/test_pkgpanga_check.py
- ssh/ssh_tunnel.py
- test_util/installer_api_test.py
- tests/test_installer_async_api.py
- tests/test_ssh_integration.py
- tox.ini
This replaces isort which is painful to use / maintain with the
flake8-import-order plugin which means we don't have do things like manually
maintain a whitelist for isort and a blacklist for flake8. Don't have to remember
to add things to isort. Don't have to manually set known_first_party and known_third_party
Style wise the biggest difference from current the "smarkets" style which is set
now is that from `x import a, B, c` cares about sorting alphabetically without
caring about case now
Based on the code changes, this catches a bunch of basic sorting was off which says the tool config
for isort was too complicated and the new plugin is a lot easier in that respect.
I think the improvement in CI usability (They show up on the teamcity base page) and catching
programmer mistakes / …
> Replace isort with flake8-import-order

- ext/dcos-installer/dcos_installer/action_lib.py
- ext/dcos-installer/dcos_installer/backend.py
- ext/dcos-installer/dcos_installer/cli.py
- ext/dcos-installer/dcos_installer/config.py
- ext/dcos-installer/dcos_installer/config_util.py
- gen/__init__.py
- gen/calc.py
- ssh/validate.py
- tests/test_gen_validation.py
- tests/test_installer_async_api.py
- tests/test_installer_backend.py
- tests/test_ssh_unittest.py
The ConfigTarget will also get used for AWS Key validation and allow using one config.yaml which doesn't have all of it's parameters go into the cluster: AWS keys, SSH keys, etc in config.yaml shouldn't end up on every host.
This includes:
#627 (although can land independently)
Replaces
#620 (Adds fixes, integration test by way of ssh validation test)
- Make it so gen knows all parameters that are ever available and makes sure the user doesn't have random unknown parameters
- Make ConfigTarget get the full computed arguments for that one config target and stash them on the ConfigTarget. This is critical so that with the AWS Advanced templates from dcos_generate_config.sh the AWS keys for uploading templates don't end up on every host in the cluster / in the cluster at all
> Pull out a "Config Target" from gen.calculate, use it for ssh configuration

- gen/aws/templates/advanced/zen.json
- gen/aws/templates/aws.html
- gen/azure/templates/azure.html
- gen/installer/aws.py
- gen/installer/azure.py
- gen/installer/bash.py
- release/__init__.py
- tests/test_release.py
This makes some code when we try making dcos_generate_config.sh call aws
do_create make a lot more sense to write. In that context the release tooling
internal channel_commit_path and friends don't make a lot of sense.
cc: @lingmann: This should help make the calling do_create from the AWS advanced templates much cleaner looking.
> Change do_create interface to make more sense when reused from other places

- ext/dcos-installer/dcos_installer/backend.py
- ext/dcos-installer/dcos_installer/cli.py
- ext/dcos-installer/dcos_installer/config_util.py
- gen/__init__.py
- gen/aws/templates/advanced/zen.json
- gen/installer/aws.py
- gen/installer/bash.py
- gen/installer/bash/Dockerfile.in
- release/__init__.py
- release/storage/aws.py
- tests/test_installer_backend.py
- tests/test_release.py
Initial support for creating AWS templates with `dcos_generate_config.sh` using the argument `--aws-cloudformation` and a limited subset of `config.yaml` options.
Known bugs:
Sample config.yaml:
```
---
aws_template_storage_bucket: cody-test-advanced
aws_template_storage_bucket_path: some/path
aws_template_storage_region_name: us-west-2
aws_template_upload: true
aws_template_storage_access_key_id: <your_access_key_id>
aws_template_storage_secret_access_key: <your_secret_access_key>
```
Includes: #656
> Generate AWS Advanced Templates directly with gen library

- release/__init__.py
This works because we know the exact set of things which will show up, and adjust
those as needed. Long term should do something cleaner.
For now this should be good enough
> Hacky fix for `release promote`, broken with the aws advanced templates changes

- packages/cosmos/build
- packages/mesos-dns/extra/dcos-mesos-dns.service
- packages/metronome/build
- Make Mesos-DNS wait for spartan
- Teach metronome to wait for leader.mesos (marathon does already)
- Teach cosmos to wait for leader.mesos
cc: @sargun @aquamatthias @BenWhitehead
> Fix some things I noticed in a cluster startup

- prep_local
- prep_teamcity
This seems to be recommended way to upgrade pip. (https://pip.pypa.io/en/stable/installing/) 
The reason being, pip we use is being shipped with python 3.4 and we have to upgrade pip as soon as we encounter it first time.
The two ways to upgrade are 
1. Download and install
```
curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py
```
2. Or the current way.
Since this 2. way delegates the download to pip itself, this is better than explicit download and run.
--- 
**Testing**
Upgrade happens like this:
```
+ ./prep_local
Collecting pip
Using cached pip-8.1.2-py2.py3-none-any.whl
Installing collected packages: pip
Found existing installation: pip 8.1.1
Uninstalling pip-8.1.1:
Successfully uninstalled pip-8.1.1
Successfully installed pip-8.1.2
```
> Proper way to upgrade pip.

- docs/admin-ports.md
- packages/minuteman/buildinfo.json
- packages/navstar/buildinfo.json
- packages/spartan/buildinfo.json
This PR limits disterl to using the ports that are mentioned in the PR doc.
> Lock down distributed Erlang port usage

- packages/adminrouter/extra/dcos-adminrouter-agent.service
- packages/adminrouter/extra/dcos-adminrouter.service
- packages/cosmos/build
- packages/dcos-history/extra/dcos-history.service
- packages/dcos-signal/extra/dcos-signal.service
- packages/exhibitor/extra/dcos-exhibitor.service
- packages/mesos-dns/extra/dcos-mesos-dns.service
- packages/minuteman/build
- packages/navstar/build
- packages/spartan/extra/dcos-gen-resolvconf.service
- packages/spartan/extra/dcos-spartan-watchdog.service
- packages/spartan/extra/dcos-spartan.service
see [Systemd Rules](https://github.com/dcos/dcos/blob/master/docs/systemd-rules.md)
When we have restarting services, Before= and After= don't really mean anything.
That these don't match expectations can be seen by the needing to add `ping` checks for the various services / DNS resolutions because the services came up before what they were `After`
> Remove `After=` lines that don't do what people want / expect.

- gen/calc.py
- gen/dcos-services.yaml
Fixes: https://mesosphere.atlassian.net/browse/DCOS-6484 ('/tmp' is sometimes too small to contain the bootstrap tarball by allowing people to use a custom folder.
> Allow changing the bootstrap download folder from `/tmp`

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_networking.py
Based on ~1k test runs, all of these finish in 20-40 seconds if they're going to succeed. This makes it so they fail a bit faster when they're going to.
cc: @mellenburg
> Move timeouts from 5 minutes to 2 minutes

- gen/installer/azure.py
The fake url explains how to put in a legitimate url by configuring some azure storage.
Reported by a community member, should resolve:
```
WARNING:root:Skipping  AWS CloudFormation validation because couldn't get a test session: No testing section in configuration
Validating CloudFormation: advanced-priv-agent.json
WARNING:root:Skipping  AWS CloudFormation validation because couldn't get a test session: No testing section in configuration
Validating CloudFormation: advanced-pub-agent.json
WARNING:root:Skipping  AWS CloudFormation validation because couldn't get a test session: No testing section in configuration
Validating CloudFormation: aws/templates/advanced/infra.json
WARNING:root:Skipping  AWS CloudFormation validation because couldn't get a test session: No testing section in …
```
> Make it so if no azure storage backend is provided we use a fake / borked url to the azure templates

- packages/dcos-integration-test/extra/conftest.py
Right now we get double the messages:
[2016-09-09 23:56:24,681|root|INFO]: Response from marathon: {'portDefinitions': [{'port': 0, 'protocol
[2016-09-09 23:56:24,681] INFO: Response from marathon: {'portDefinitions': [{'port': 0, 'protocol': 'tcp',
> De-duplicate test logging

- gen/dcos-services.yaml
Many stacks fail to create in AWS because of
curl: (18) transfer closed with ___ bytes remaining to read
curl's default keepalive interval is 60s
From what I can tell, this error is generated when the server side cuts off the transfer so it would make sense to bump up keepalive-time. And it helped at least one person http://stackoverflow.com/questions/33522615/curl-transfer-closed-with-outstanding-read-data-remaining
> Stabilize dcos-setup.service

- gen/cloud-config.yaml
Changing this setting globally, since most customers don't seem to touch it, and we have some issues currently in customer logs with things getting dropped fairly frequently.
cc: @bernadinm
> Up the systemd-journald burst rate

- gen/calc.py
- gen/dcos-config.yaml
- packages/cosmos/build
- packages/dcos-oauth/extra/dcos-oauth.service
- packages/mesos/extra/dcos-mesos-master.service
- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
Sample config.yaml snippet:
```
use_proxy: true
http_proxy: <your_http_proxy>
https_proxy: <your_https_proxy>
```
All but .mesos domains will be proxied
Users can add more domains to the `no_proxy` list by setting `no_proxy` to a list of things to exclude in their config.yaml
TODO:
Fixes: https://mesosphere.atlassian.net/browse/DCOS-6619
Makes progress towards: https://dcosjira.atlassian.net/browse/DCOS-34
> Add support for configuring a proxy via config.yaml

- packages/minuteman/build
- packages/minuteman/buildinfo.json
- packages/navstar/build
- packages/navstar/buildinfo.json
- packages/spartan/buildinfo.json
- packages/spartan/extra/dcos-spartan.service
This changes the location of where the disterl port is set from the
env file to the systemd unit. The reason for this is it should only
apply when launched from systemd, and not debug scripts, such as
remote_console.
> Set the Environment for the disterl port lockdown in the systemd unit

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_composition.py
Allows having a test that just establishes a cluster
is up. So, if the cluster fails to come up, the user
will see waiting for the test_cluster_is_up and not
some arbitrarily chosen test
> Add pytest ordering plugin

- packages/dcos-integration-test/extra/test_applications.py
- packages/octarine/buildinfo.json
Octarine tests were hitting the wrong url, this was causing tests to pass even though it was misbehaving. Also updated Octarine to fix this.
> Octarine bugfix

- tox.ini
- The teamcity messages weren't showing up because TEAMCITY_VERSION wasn't getting through
- The AWS var we moved off of a while ago
Noticed the first one in #623 where they weren't showing as nice structured errors
> Cleanup env vars a bit

- packages/exhibitor/extra/dcos-exhibitor.service
- packages/exhibitor/extra/start_exhibitor.py
- start_exhibitor.py: check existance of realm file in /opt instead of in /run
- run ExecStartPre as root and chown realm file to user dcos_exhibitor
Note that /usr/bin/chown is a standardized location that should exist on all target platforms, and that it dereferences symlinks by default.
> exhibitor: check existance of realm file in /opt instead of in /run

- packages/dcos-integration-test/extra/test_applications.py
If Mesos containerizer shall be used, 'ContainerInfo.mesos' field should be set instead of 'ContainerInfo.docker'.
> test: Updated Marathon app definition for Mesos containerizer

- tox.ini
- Use TEAMCITY_VERSION to trigger teamcity messages rather than explicit flag
- move `-rs -vv` to `addopts` for py.test
> Misc. tox flags cleanup

- packages/dcos-integration-test/extra/test_applications.py
This reverts commit de9842a766582355079ba4dab1032f832ff76485.
See comments on #717 
cc: @rukletsov
> Revert "test: Updated Marathon app definition for Mesos containerizer"

- docs/systemd-rules.md
- gen/dcos-config.yaml
- packages/minuteman/build
- packages/navstar/build
- packages/spartan/extra/dcos-spartan.service
This seems to be the only thing that works reliably across CoreOS / Ubuntu / CentOS
> Move all of the ERL_FLAGS statements to EnvironmentFiles

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_composition.py
wait_for_dcos needs to be in the fixture or else
running tests in arbitrary order will not work
> Always authenticate before any test

- README.md
- packages/bootstrap/build
- packages/bootstrap/extra/setup.py
- packages/boto/build
- packages/curl/build
- packages/dcos-history/build
- packages/dcos-image-deps/build
- packages/dcos-image/build
- packages/dnspython/build
- packages/flask/build
- packages/pytest/build
- packages/python-azure-mgmt-resource/build
- packages/python-dateutil/build
- packages/python-docopt/build
- packages/python-gunicorn/build
- packages/python-isodate/build
- packages/python-jinja2/build
- packages/python-kazoo/build
- packages/python-markupsafe/build
- packages/python-passlib/build
- packages/python-pyyaml/build
- packages/python-requests/build
- packages/python-retrying/build
- packages/python-tox/build
- packages/python/build
- packages/python/buildinfo.json
- packages/six/build
- setup.py
> Bump to Python 3.5

- packages/openssl/buildinfo.json
OpenSSL 1.0.2i was released yesterday, 22 Sep 2016:
https://www.openssl.org/news/cl102.txt
https://www.openssl.org/news/secadv/20160922.txt
> openssl package: update to 1.0.2i

- packages/dcos-history/build
- packages/dcos-history/buildinfo.json
- packages/dcos-history/extra/dcos-history.service
- packages/dcos-history/extra/history/dcos_history_conf.py
- packages/dcos-history/extra/history/server.py
- packages/dcos-history/extra/setup.py
- packages/dcos-integration-test/extra/test_endpoints.py
When running dcos-history, if the flask app cannot bind to the port assigned it does not fail and keeps retrying. Using gunicorn ensures that the app fails and master is marked unhealthy.
https://mesosphere.atlassian.net/browse/DCOS-5334 
Unit tests passed
Syntax test passed
> Handle connection error on dcos-history

- packages/dcos-integration-test/extra/test_3dt.py
test_3dt_bundle_download_and_extract is a flaky test. Sometimes the 3dt health
report for public agent is not in zip archive. Diagnostics bundle has its own
log files: actions log and error log. Let's print out their content if the
required file is not in the archive.
https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=419334#_focus=1830
> make flaky test verbose

- test_util/cluster_api.py
A marathon app is considered deployed when all instances are running
and healthy. To simplify debugging, we should check those cases
separately and print different debug messages.
Adopted from #715, code quality problems fixed.
> test: Tweaked output for deploy_marathon_app

- packages/openssl/buildinfo.json
https://www.openssl.org/news/cl102.txt
> As a result any attempt to use
CRLs in OpenSSL 1.0.2i will crash with a null pointer exception.
@cmaloney this should go in 1.8.5.
> openssl package: update to 1.0.2j

- packages/mesos-overlay-modules/buildinfo.json
Removing an unused namespace from the overlay-module, that was causing compilation failure with Mesos HEAD (since that namespace has been removed in the newer version of the API).
> Fixed compilation error of mesos-overlay-module.

- packages/dcos-signal/buildinfo.json
Brings OSS in line with other variants of DC/OS.
> Bump signal from 1.1.9 to 1.2.1

- test_util/aws.py
Addresses this failure: https://teamcity.mesosphere.io/viewLog.html?buildId=425058
> Fix syntax error preventing S3 cleanup

- dcos_installer/backend.py
- gen/aws/templates/advanced/advanced-master.json
- gen/aws/templates/advanced/advanced-priv-agent.json
- gen/aws/templates/advanced/advanced-pub-agent.json
- gen/aws/templates/cloudformation.json
* Fix missing NATAmi mapping in the Simple Template for the govcloud region
* Set the S3 Exhibitor ARN to the correct values required for us-gov-west-1
* Add CentOS7 base AMI images in the govcloud region for Advanced Templates
> Improvements to support AWS govcloud

- gen/calc.py
- gen/cloud-config.yaml
- gen/dcos-config.yaml
- tests/test_gen_validation.py
The cluster_docker_credentials can either be owned by DC/OS or a sysadmin's
configuration management system (ansible, chef, puppet, salt, etc.).
Core config options:
```
cluster_docker_credentials:
Dictionary of credentials to pass.
If unset / left the default, this will cause an empty credentials file to be placed in
/etc/mesosphere/docker_credentials on DC/OS install. Sysadmin scripts can then edit that file
and do a `systemctl restart dcos-mesos-slave` / `systemctl restart dcos-mesos-slave-public`.
It can also be set as: http://mesos.apache.org/documentation/latest/configuration/
'--docker_config' json format. Note that in config.yaml just write yaml and it will be mapped to
the JSON format for you. This will cause the docker credentials configuration to be part of the
DC/OS internal …
```
> Add cluster_docker_credentials configuration

- gen/aws/templates/advanced/advanced-master.json
- gen/aws/templates/cloudformation.json
If DC/OS is configured for HTTPS, these loadbalancers become useless
See: https://mesosphere.atlassian.net/browse/DCOS-10219
> Use TCP for AWS CF LB Health Checks

- packages/navstar/buildinfo.json
This patch enables internal exposure of the generated zone id
> Bump navstar package

- packages/mesos/buildinfo.json
You can view the branch here:
https://github.com/mesosphere/mesos/commits/dcos-mesos-1.0.x-837bb4e
> Bump Mesos to the latest 1.0.x with existing cherry-picks.

- gen/installer/aws.py
The Zen Advanced AWS template contained duplicate `config_id` sections
in the TemplateURL path. This removes the reproducible_artifact_path
from the URL since it is already calculated by the installer backend.
> Fix duplicate config_id in Zen templates

- dcos_installer/action_lib.py
Our prereq installation was failing because we were on RHEL 7.2
It would be nice if instead of a 700MB shell script you created a compressed file containing scripts separated from binaries, so that people can fix errors on the fly.
> Handle version number with decimals

- packages/adminrouter/buildinfo.json
Validate jwt for 3dt and pkgpanda API on master nodes.
https://github.com/dcos/adminrouter/pull/18
> bump adminrouter

- packages/dcos-ui/buildinfo.json
Includes:
* Fixes to services modal deleting networking configuration options
* Handling CLI-only package error better
> bump dcos-ui package for 1.8.5

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/resiliency/test_aws_cf.py
- test_util/test_aws_cf.py
-resiliency mark makes it impossible to run just open_source_tests in downstream; simple env is better
-if logging is declared in cluster fixutre, -s option will not work when selecting specific tests
> Fix conftest bugs

- packages/adminrouter/extra/dcos-adminrouter-agent.service
- packages/adminrouter/extra/dcos-adminrouter.service
Cuttent one doesn't work when a `systemctl reload dcos-adminrouter` is run (same fix applies to dcos-adminrouter-agent)
Internal JIRA: https://mesosphere.atlassian.net/browse/DCOS-10580
> Change adminrouter ExecReload to work

- packages/dcos-ui/buildinfo.json
> 1.8.5: dcos-ui: Fixes table caching for logs link.

- NEWS
- gen/dcos-services.yaml
- packages/dcos-image/build
- packages/dcos-image/extra/dcos-shell
- packages/dcos-integration-test/extra/test_ec2.py
- test_util/cluster_api.py
The goal is this is the only thing that gets added to $PATH (Rather than the
python environment and everything else)
People can then use:
`dcos-shell` -- get a shell with all DC/OS bits in your environment
`dcos-shell pkgpanda --uninstall` -- run a pkgpanda command with all the right environment variables.
> Add a `dcos-shell` program so dcos doesn't have to be added to the default `$PATH`

- packages/octarine/buildinfo.json
Update to golang 1.7 and move parsing from general HTTP handler to just SRV records. Also updated the project to use godep, a golang dependency tracking tool.
> Octarine: Golang 1.7, godep, and parsing changes

- gen/calc.py
- packages/marathon/build
This patch creates a new config.yaml parameter called `enable_gpu_isolation` that enables (cluster-wide) GPU isolation from mesos. This means that *all* machines in your cluster must have GPUs installed on them in order to enable this feature. Otherwise starting the mesos-agent on non-GPU capable machines will fail.
For now, this support is considered experimental, so requiring all machines in a cluster to have GPUs is acceptable for testing out the feature. In future releases we will proide support for having a mixed cluster of GPU and non GPU machines, where only the GPU-capable machines have this feature enabled.
> Add enable_gpu_isolation flag

- setup.py
- test_util/azure_test_driver.py
Carrying on work from https://github.com/dcos/dcos/pull/716 (which is on a branch I cannot edit)
> Adding testing options passthrough like the CF templates

- tox.ini
Bug was introduced with: https://github.com/PyCQA/
flake8-import-order/commit/863f4597ab4e0879ee6058fab3f5e5b1df1f3463
> Pin flake8-import-ordering to 0.9.2

- gen/aws/calc.py
- gen/azure/calc.py
- gen/calc.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_composition.py
- packages/docker-gc/build
- packages/docker-gc/buildinfo.json
- packages/docker-gc/extra/dcos-docker-gc.service
- packages/docker-gc/extra/dcos-docker-gc.timer
To Enable/Disable in config.yaml:
```
enable_docker_gc: true
```
Disabled by default (landing late, no integration test). See https://github.com/spotify/docker-gc for documentation on configuration, the `/etc/` configuration folders mentioned should work. It is
run hourly in DC/OS.
Fixes internal bug: https://mesosphere.atlassian.net/browse/DCOS-7618
> Add spotify/docker-gc to help cleanup left around dockers on agents

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_auth.py
- packages/dcos-integration-test/extra/test_ec2.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_service_discovery.py
- test_util/cluster_api.py
- test_util/helpers.py
- test_util/marathon.py
-Adds generic get_client to cluster_api by which one may set an API base, user auth,  and default headers to make requests
-Adds marathon api client with marathon helpers for extended functionality
> Add Cluster Marathon Client

- build_dcos_launch.sh
- gen/installer/bash.py
- gen/installer/bash/dcos-launch.spec
- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- release/storage/http.py
- setup.py
- test_util/launch.py
First steps towards making the "launch cluster" stuff in test_util be usable via a simple / sane API via a binary (dcos-launch).
Fixes: https://mesosphere.atlassian.net/browse/DCOS-10196
TODO:
cc: @mellenburg
> Add tooling to make `dcos-launch` binary

- dcos_installer/backend.py
- dcos_installer/config.py
- gen/__init__.py
- gen/exceptions.py
- gen/internals.py
- gen/template.py
- gen/test_template.py
- pkgpanda/util.py
- ssh/validate.py
This reworks the gen a bit to make the library more understandable in terms of what it is doing. It introduces four main primitives:
`Source` is a source of configuration variables. A `Target` is a set of configuration variables which
need to be set to have a complete configuration. The `Resolver` figures out how to use a collection of
sources to fill in a collection of targets and check for conflicts.
`Source`s can be user-provided (a dictionary loaded out of a config file). They can also be provided
by different contexts (AWS templates have a source of AWS which implies things likes resolvers). A
third common provider is deriving from other already given values (master count is derived from a
master list if a master list is given).
`Target`s are a set of variables which need to be set, …
> Rework gen/ to be made of three primitives: Source, Target, Scope and Resolver

- gen/__init__.py
- gen/installer/azure.py
- tests/test_release.py
- tests/test_ssh_integration.py
- Lower ssh process timeout in test so we don't spend 2 seconds waiting
- Use builtin system call rather than a subprocess
- Remove unnecessary regex
- Mock pkgpanda.util.make_tar in test_make_channel_artifacts (We didn't do anything with the produced tar).
cc: @darkonie @lingmann
> Misc cleanup and speedup fixes extracted from #854

- dcos_installer/cli.py
Main changes:
- HASH_PASSWORD, SET_SUPERUSER_PASSWORD placeholders become `password`
- The help for `--preflight` and the like shows the intended help string rather than the all-caps used in the display output when running.
Old:
```
usage: dcos_installer [-h] [--hash-password [HASH_PASSWORD]]
[--set-superuser-password [SET_SUPERUSER_PASSWORD]] [-v]
[--offline] [--cli-telemetry-disabled] [--version]
[--validate-config] [--genconf] [--web]
[--aws-cloudformation] [--preflight] [--postflight]
[--uninstall] [--install-prereqs] [--deploy]
DC/OS Install and Configuration Utility
optional arguments:
-h, --help            show this help message and exit
--hash-password [HASH_PASSWORD]
Hash a password and print the results to copy into a
config.yaml.
--set-superuser-password …
```
> Update dcos_generate_config.sh --help to display the right help messages

- gen/aws/calc.py
- gen/aws/dcos-config.yaml
- gen/calc.py
- gen/dcos-config.yaml
- gen/installer/aws.py
- gen/internals.py
This makes it possible to do things like issue certs properly inside the cluster
for all the addresses of a master. Previously that was only possible for AWS
clusters because the integration was AWS only.
Builds on #883, Train 91 (fixes a bug that existed before and after that train, but in a piece of code #868 reworks some)
https://mesosphere.atlassian.net/browse/DCOS-10934
> Teach configuration to pass through internal load balancer DNS for certificate generation

- dcos_installer/backend.py
The aws s3 api will return an empty value when the buckets region is `us-east-1` [1]. calculate_aws_template_storage_region_name has been updated to return the value `us-east-1` when this happens.
[1] http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html#RESTBucketGETlocation-responses-response-elements
> Update dcos_installer/backend.py::calculate_aws_template_storage_region_name to handle empty value for `us-east-1`

- packages/spartan/extra/dcos-spartan-watchdog.service
- packages/spartan/extra/dcos-spartan-watchdog.timer
This reverts commit ecfe9a57ac9e61e84ad84161c8854f51aa12f417.
There still isn't a good explanation _why_ sleep is better than a delay. The behavior hasn't
really been explained.
That said, this fixes the issue for one customer at present, although we still need to come up with
a reasonable reason for that and _proper_ fixes. `sleep` is rarely the correct solution to software
problems, just a band-aid...
I'm really not a fan of this, only doing it because we need a fix today.
[DCOS-10809](https://mesosphere.atlassian.net/browse/DCOS-10809)
> Revert "Make dcos-spartan-watchdog start later rather than have a random 60 second sleep"

- packages/curl/buildinfo.json
- packages/ncurses/buildinfo.json
- packages/strace/buildinfo.json
- packages/toybox/buildinfo.json
Five packages were fetched over HTTP instead of HTTPS. The SHA still gets checked, but this is a bit better. Confirmed all of these were served over HTTPS as well.
[DCOS-<number>](https://dcosjira.atlassian.net/browse/DCOS-<number)
...
> Changed some package urls to https instead of http.

- packages/cosmos/build
- packages/libevent/build
- packages/marathon/build
- packages/python/build
- pkgpanda/docker/dcos-builder/Dockerfile
This PR does:
- Alphabetizes the list of dependencies in the Dockerfile
- Bumps the base image from `ubuntu:14.04.4` to `ubuntu:16.04`
- Changes `gcc` to `gcc-4.8` and `g++-4.8` (the same version that is currently being used) and set `CC` and `CXX` environment variables appropriately.
- Bumps the package for `linux-headers` to match the updated kernel
- Add `libpcre++-dev` dependency for adminrouter/nginx (the installed library is placed in the same location as before)
- Add `xutils-dev` dependency for the `makedepend` utility
- `s/CXXFLAGS/CPPFLAGS/` in the main Python build, needed to find and build the `_ssl` module
- Removed extraneous `sudo`s from the Cosmos and Marathon build scripts
> Change the default build image to Ubuntu 16

- test_util/aws.py
logging.exception should never be called outside of an except loop, as it will not have an exception to pass and will make a terribly ugly stack trace as seen here:
https://teamcity.mesosphere.io/viewLog.html?buildId=458191&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_ProvisioningTestAwsDe_4&tab=buildLog#_focus=4228
> Do not call logging.exception out of except clause

- build_local.sh
- build_teamcity
We are supposed to be using 3.4 everywhere, but some things still end up being run on 3.5 and then are confused by the artifacts. This commit will enforce explicit use of python 3.4 for the build environment
(disregard branch name)
> Enforce python 3.4 in builds

- packages/dcos-installer-ui/buildinfo.json
- packages/dcos-ui/buildinfo.json
- tests/test_installer_backend.py
* Removes timeout for /login endpoint
* Removes security dropdown from installer UI.
> bump dcos-ui and dcos-installer-ui packages.

- packages/minuteman/buildinfo.json
- packages/navstar/buildinfo.json
- packages/spartan/buildinfo.json
This patch is to upgrade navstar, spartan and minuteman to point to patches to upgrade rebar3 with the fix for relx issue#523
DCOS-11180
> Bug DCOS-11180: upgrades navstar, spartan, minuteman

- packages/dcos-oauth/extra/dcos_add_user.py
Improve error/success message for dcos-oauth dcos_add_user.py
* A success message will be printed to stderr and exit code 0 when adding user is successful
* An error message will be printed to stderr and exit code 1 when connection to zk times out
* An error message will be printed to stderr and exit code 1 if unable to create the `/dcos/users/` base node
* An error message will be printed to stderr and exit code 1 when attempting to add a user that already exists
[DCOS-11241](https://mesosphere.atlassian.net/browse/DCOS-11241)
```
.../dcos/packages/dcos-oauth/extra> python3 dcos_add_user.py blob@mesosphere.io
Connection dropped: socket connection error: Connection refused
Connection dropped: socket connection error: Connection refused
Connection dropped: socket connection error: …
```
> Improve error/success message for dcos-oauth dcos_add_user.py

- pkgpanda/docker/dcos-builder/Dockerfile
Make GCC 4.8 the default in dcos-builder to avoid downstream issues.
Could consider using update-alternatives here, but Ubuntu doesn't do that by default.
Can do http://askubuntu.com/questions/26498/choose-gcc-and-g-version if we feel strongly.
> make GCC 4.8 the default in dcos-builder to avoid downstream issues

- gen/azure/cloud-config.yaml
- gen/azure/templates/acs.json
- gen/installer/azure.py
Moving large .deb files onto the ephemeral disk for faster read write
times on setup. Making about a 2 min speed up in standing up a cluster.(Not exhaustively tested, but speed up was noticeable in ad-hoc testing.
- Now stored in the  new folder /var/lib/mesos/dcos/
Making ssh work on port 22 on the master load balancer. Achieved by:
- opening port 2222 for ssh on the master vms by modifiy sshd_config
- NATing port 22 on LB to port 2222 on master 0
- updating rest of networking resources to make that work.
this is none ideal in a few ways:
- the arm template isn't perfectly optimized, all masters NICs depend on the new NAT rule but only one uses it, minor since the rule comes up very quickly. Didn't just drop the old NAT rule as that would be a breaking change, and wanted to do this in a …
> integrating changes made in acs codebase back into dcos

- gen/aws/calc.py
fix master_external_loadbalancer typo in aws/calc.py
> fix master_external_loadbalancer typo in aws/calc.py

- packages/marathon/buildinfo.json
- When a runtime exit is requested, if the exit does not complete in less than the requested amount of time (10 seconds by default),
now will actually kill the JVM. Previously, the timeout code did not actually work at all.
- Marathon will now terminate upon loss of leadership instead of becoming a non-master. This prevents a lot of potentially unsafe
behavior and a watchdog will instead bring marathon back up in a clean state.
> Use Marathon 1.3.6

- packages/dcos-integration-test/extra/resiliency/test_aws_cf.py
- test_util/aws.py
- test_util/helpers.py
Using tags for finding instances in groups resulted in failures as tagging is not guaranteed at deployment time, but resources are guaranteed to be created. See: https://mesosphere.atlassian.net/browse/DCOS-11009
> Use resources to find instances in AWS util

- dcos_installer/cli.py
- gen/installer/bash/installer_internal_wrapper.in
- tests/test_installer_backend.py
- tests/test_installer_init.py
dcos_generate_config.sh --help goes from:
```
dcos_installer <...>
```
to:
```
dcos_generate_config.sh <...>
```
Should help reduce customer confusion (dcos_installer sounds a lot like dcos_install.sh)
In order to change that, how the "password" arguments are handled was also changed to use a custom argparse action which makes a simpler to understand API for which mode they should go into (Hash the given password vs. no password given prompt for one).
https://mesosphere.slack.com/archives/documentation/p1477923100001079
> making argparse use sys.argv so it auto picks up argv[0]

- packages/python-pyyaml/buildinfo.json
PyYAML 3.12 was released earlier the year (more than two years after 3.11), addressing three small issues (http://pyyaml.org/wiki/PyYAML#History):
```
* Adding an implicit resolver to a derived loader should not affect the base loader (fixes issue #57).
* Uniform representation for OrderedDict across different versions of Python (fixes issue #61).
* Fixed comparison to None warning (closes issue #64).
```
> python-pyyaml: bump to 3.12

- packages/dcos-integration-test/extra/test_applications.py
- test_util/cluster_api.py
- test_util/helpers.py
- test_util/marathon.py
-Circular dependencies are bad. This only worked because python doesnt evaluate until runtime
-Allows ApiClient to be generic
-Adds a convenience constructor to make the Api from a cluster object
> Remove cluster from ApiClient

- build_local.sh
- build_teamcity
- tox.ini
Switches build and unit tests to run in python 3.5 rather than python 3.4, unifying all dc/os internals and build to always be python 3.5.
This PR should help flush out remaining things that break.
> Switch remaining pieces to Python 3.5

- pkgpanda/build/__init__.py
- pkgpanda/build/test_util.py
- release/__init__.py
Add test for hash_files_in_folder, fix several usages with absolute paths in codebase
Absolute paths with hash_folder resulted in a non-reproducible hash since the absolute path changes from host to host (where the checkout is changes). This makes hash_folder assertion fail if it's given an absolute path, and gives a helper function which can be used to make absolute paths into relative paths by changing into the directory before running hash_folder
[DCOS-275](https://dcosjira.atlassian.net/browse/DCOS-275)
> Add test for hash_files_in_folder, fix several usages with absolute paths in codebase

- dcos_installer/action_lib.py
- dcos_installer/async_server.py
- dcos_installer/prettyprint.py
- ssh/README.md
- ssh/runner.py
- ssh/test_integration.py
- ssh/tunnel.py
- test_util/azure_test_driver.py
- test_util/cluster.py
- test_util/installer_api_test.py
They were already living in the "ssh" namespace, having them named SSH as well
is redundant (ssh.ssh_tunnel.SSHTunnel -> ssh.tunnel.Tunnel).
This also makes their parameters "user" and "key_path" rather than "ssh_user"
and "ssh_key_path" since the context of "this is an ssh thing" is implicit in
the fact it came from the ssh library.
> Remove redundant SSH name / prefix from ssh modules

- test_util/azure_test_driver.py
- test_util/run-all
- test_util/test_aws_cf.py
- test_util/test_aws_vpc.py
- test_util/test_runner.py
- test_util/test_upgrade_vpc.py
- Many of our builds logs are extremely hard to parse
- Test logs should pump out status logging info continuously so sudden failure causes can be diagnosed
> Cleanup logging

- dcos_installer/action_lib.py
- Disable SElinux on CentOS7 when executing `sudo bash dcos_generate_config.sh --install-prereqs`
- It can disable SElinux correctly on CentOS7
- sed -i will break hard or symbolic links when -i is used on such a file, should add --follow-symlinks option. (https://www.gnu.org/software/sed/manual/sed.html)
[DCOS-524](https://dcosjira.atlassian.net/browse/DCOS-524)
...
sed -i will break the link between /etc/sysconfig/selinux and /etc/selinux/config.
> DCOS-524:install-prereqs actually doesn't disable SElinux on CentOS

- cloud_images/centos7/dcos_vol_setup.sh
- cloud_images/centos7/install_prereqs.sh
- cloud_images/centos7/packer.json
This modifies default packer settings and supporting scripts for the CentOS 7 AMI.
The current CentOS 7 AMI uses 8GB on / of which 4GB is in use by the OS and DC/OS. On our prod cluster's leader the remaining 4GB were filled with /var/log data within a day.
This PR:
- fixes a race in `dcos_vol_setup.sh` where the Kernel could sometimes take longer to pick up the newly created partition than it takes the script to proceed with `mkfs.xfs` (`dcos_vol_setup.sh[689]: /dev/xvdf1: No such file or directory`).
- makes the `partprobe` call optional. The script sometimes fails right now because the new partition is being picked up before the partprobe call and make the device busy (`Error: Error informing the kernel about modifications to partition /dev/xvde1 -- Device or resource busy.`). Since …
> Various CentOS 7 AMI fixes and improvements.

- dcos_installer/backend.py
- dcos_installer/config.py
- gen/__init__.py
- gen/calc.py
- gen/internals.py
- gen/test_internals.py
- ssh/validate.py
- Targets now get finalized with results. This also means they need to be constructued per-use.
- validate_configuration() no longer exists, as resolve_configuration does exactly the same thing,
users of validate_configuration() are migrated to just use resolve_configuration() once.
- The per-target results aren't yet plugged into various places, that will come in a later pr
- Introduce a notion of variables "visited" to calculate a particular variable.
- Introduce a concept of a "Resolvable". A resolvable tracks the resolution state of a particular configuration value. (Unresolved, being resolved, error). It will eventually also include a "late resolution" (late binding) state. The introduction centralizes the logic for tracking that, and makes it harder to get wrong. Resolvables also …
> gen: Add the concept of a Resolvable, Resolve config per-Target

- ssh/test_integration.py
- ssh/tunnel.py
- test_util/azure_test_driver.py
- test_util/cluster.py
- test_util/installer_api_test.py
- TunnelCollection is replaced with a contextlib.ExitStack, so it has less code while keeping the same behavior, uses more standard code.
- Tunnel class is replaced with a "contextmanager" function that yields a Tunneled object.
the Tunnel contextmanager function makes it harder to use the tunnels
incorrectly as the tunnel is only accessible inside the contextmanager / when
the contextmanager has been entered. The "Tunneled" class only has the simple
API / behavior people expect to work on things which are tunneled to.
> Update / rewrite Tunnel, TunnelCollection

- packages/exhibitor/buildinfo.json
None
Fixes a critical bug in the exhibitor UI that can result in zookeeper never being able to restart after updating configuration.
Fixed bug in UI
[DCOS-9782](https://dcosjira.atlassian.net/browse/DCOS-9782)
Upstream PR: https://github.com/dcos/exhibitor/pull/4
> Bump exhibitor SHA to 7d39834f55988e21f2d7ce2c0b67847cb4a55dab

- test_util/cluster_api.py
- test_util/helpers.py
- test_util/marathon.py
assert r.ok is a very uninformative check to make. Rather just use
r.raise_for_status()
additionally, this utility requires app names to start with '/' so just they can be queried, which makes for confusing errors if you successfully launch an app with a name that doesn't start with '/'
> Cleanup request checking

- dcos_installer/action_lib.py
- gen/calc.py
- gen/internals.py
- gen/template.py
- packages/dcos-history/extra/history/statebuffer.py
- pkgpanda/__init__.py
- pkgpanda/actions.py
- pkgpanda/build/__init__.py
- release/__init__.py
- release/storage/__init__.py
- release/storage/aws.py
- release/storage/azure.py
- release/storage/local.py
- ssh/runner.py
- ssh/tunnel.py
- ssh/utils.py
The set of things to replace was found with:
`git grep 'assert isinstance'`
The python 3.5 type hints are now expressive enough for the all of these,
through the new "typing" module. The hints will effectively do the same thing
the asserts used to.
Some type assertions still exist, particularly in cases where there are circular
references (referring to a not-defined-yet class), as well as inside gen
validation where we're explicitly trying to walk through the type.
There is a second commit here which converts two error messages which didn't actually error / abort.
> Replace isinstance type assertions with python 3.5 type annotations

- packages/python-passlib/buildinfo.json
This is backwards-compatible, but brings along changes required downstream.
> packages/python-passlib: bump to 1.7.0

- packages/boto/build
- packages/boto/buildinfo.json
- test_util/aws.py
- test_util/helpers.py
- calls to boto resources need wrapping for rate limiting
- test_util.helpers.wait_for_len now has a less aggressive interval
> Adjust rate limiting

- release/__init__.py
- release/test_release.py
- if do_build_packages fail, we get the real exception in the log stream, but it is buried under an UnboundError exception that occurs because the code tries to go forward after failing when it should have simply stopped 
- Just raise the error as was originally the case
> Raise error to exit nicely

- packages/3dt/build
- packages/3dt/buildinfo.json
- packages/dcos-oauth/build
- packages/dcos-oauth/buildinfo.json
- packages/dcos-signal/build
- packages/dcos-signal/buildinfo.json
- pkgpanda/docker/dcos-builder/Dockerfile
This PR adds golang 1.7.3 to the DC/OS base build image. This supports consolidating to a single container for building (faster builds) and allowing pkgpanda packages which build many components can use a single container (see dcos-metrics service and module consolidation).
> Add golang 1.7.3 to dcos base build image and use it in our golang projects

- gen/internals.py
- gen/template.py
- gen/test_internals.py
- Add missing `from` to raise
- If there are unset variables, then that means the resolver is in an "Error" state. This wasn't happening, which resulted in weird `is_resolved` assertion failures when variables were unset rather than a ValidationError being raised.
Found working towards late binding
> Add missing from to re-raise, fix unset variables leading to an assertion

- dcos_installer/exhibitor_migrate.py
- setup.py
New package contains two new scripts 1) dcos-exhibitor-migrate-perform
2) dcos-exhibitor-migrate-status that will help operators update their
exhibitor config to the new post 1.8 values if they are running an
earlier version of dcos.
See the included readme for details of each script.
[DCOS-9782](https://dcosjira.atlassian.net/browse/DCOS-9782)
> Add dcos-exhibitor-migrate scripts

- dcos_installer/config.py
- gen/__init__.py
- gen/build_deploy/aws.py
- gen/build_deploy/azure.py
- packages/dcos-integration-test/extra/test_misc.py
- pkgpanda/util.py
- release/__init__.py
- test_util/installer_api_test.py
Changes from calling yaml.load() directly to using a wrapper `load_yaml` which does a couple things
1. Makes syntax errors include the filename (re-wrap the exception with more context)
2. Make it so not everyone has to do a `with open() as f; yaml.load(f)`
3. Switch from yaml.load -> yaml.safe_load so that we're always keeping to basic yaml types / not arbitrary code.
Found during / relates to Late Binding #1009
> yaml.load -> load_yaml for better error messages, simpler code

- packages/dcos-ui/build
Add `unsafe-perm` flag to run DC/OS UI install scripts with proper privileges. Without those privileges the installation will fail to write some of the dependencies (e.g. the Marathon RAML files) with the correct user/permissions.
> Adjust DC/OS UI build to properly install dependencies

- gen/azure/templates/acs.json
- Update the available set of Azure agent VM sizes available to only
those which meet the minimum DC/OS requirements of >= 2 cores.
- Add support for recently added Azure VM types.
- Update the validation VM size from Standard_A0 to Standard_A2.
> Update Azure VM options

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_endpoints.py
Description:
Removed the configuration of the docker bridge on the agent overlay module on the Master. This reduces the dependency on the docker daemon for the Master. The docker bridge being configured was redundant, since there were no docker containers on the overlay on the Master.
[DCOS-539](https://dcosjira.atlassian.net/browse/DCOS-539)
...
> Removed docker bridge configuration for agent overlay module on Master

- dcos_installer/backend.py
- dcos_installer/config.py
- gen/__init__.py
- gen/aws/templates/advanced/zen.json
- gen/build_deploy/aws.py
- gen/build_deploy/azure.py
- gen/calc.py
- gen/internals.py
- gen/test_internals.py
- release/__init__.py
- release/test_release.py
- ssh/validate.py
Cleans up two of the interfaces inside of the codebase. This is work that was done as part of getting to #1009 / late binding, pulled out of that PR so it can be reviewed / land independently.
1. Make resolve_configuration operate purely on sources and targets
This makes it have a more straightforward API and moves the responsibility for
building a source out of user arguments (if that is even needed) to the various
callsites (just two of them)
2. Remove magic global passing of azure and aws storage urls
Previously these were passed by globals when we were doing a release and as arguments when we did a advanced / custom configuration template generation. Now they are always passed as arguments which are injected by release/__init__.py in the case of release for the configuration, and via …
> Cleanup interfaces for passing template urls as well as resolve_configuration

- test_util/cluster.py
With 1.9 we're removing our recommendation to upgrade the ZK leader last. Passing upgrade test [here](https://teamcity.mesosphere.io/viewLog.html?buildId=502005&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_DcosOssUpgradeTestOnPre).
> Upgrade masters in a random order during test

- gen/internals.py
This restores a default value removed in de76c26a844c4f11e4794861f59bb177f32479e7.
[DCOS-11894](https://mesosphere.atlassian.net/browse/DCOS-11894)
> Make CalculatorError.__init__() chain arg optional

- test_util/marathon.py
I'd accidentally had people use r.body instead of r.content for getting the body
of the http request for debug info. Since this isn't normally executed code it
snuck through. A recent other PR though hit one of these asserts and got the bad
output.
response.content: http://docs.python-requests.org/en/master/user/quickstart/#binary-response-content
Sample old behavior / assertion
```
def deploy_pod(self, pod_definition):
"""Deploy a pod to marathon
This function deploys an a pod and then waits for marathon to
aknowledge it's successfull creation or fails the test.
It waits until all the instances reach tasksRunning and then tasksHealthy state.
Args:
pod_definition: a dict with pod definition as specified in
Marathon API
check_health: wait until Marathon reports tasks as healthy before …
```
> response.body -> response.content. Response.body never existed

- gen/calc.py
- gen/test_validation.py
Having static master_discovery but non-static exhibitor_storage_backend is legal,
although doesn't provide a lot of value. There isn't a particular reason to outlaw it however.
Having master_discovery master_http_loadbalancer but exhibitor_storage_backend isn't legal since it
results in configuration conflicts.
[DCOS-11827](https://mesosphere.atlassian.net/browse/DCOS-11827)
> Validate that if master_discovery is non-static exhibitor_storage_backend is non-static

- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/util/python_test_server.py
- packages/erlang/build
- packages/minuteman/build
- packages/minuteman/buildinfo.json
- packages/minuteman/extra/dcos-minuteman.service
- packages/minuteman/extra/setup_iptables.sh
- packages/navstar/build
- packages/navstar/buildinfo.json
- packages/toybox/build
- This change fixes quite a few issues with Minuteman and Navstar
- It fixes the performance and scalability issues with Minuteman and Navstar
- It fixes the DNS polling issues
- It switches to the IPVS-based datapath for Minuteman
https://mesosphere.atlassian.net/browse/DCOS-10256
https://mesosphere.atlassian.net/browse/DCOS-11667
https://mesosphere.atlassian.net/browse/DCOS-9754
https://mesosphere.atlassian.net/browse/DCOS-11024
https://mesosphere.atlassian.net/browse/DCOS-11300
- This doesn't change any functionality, but merely changes the implementation of it. The existing tests are valid
* https://github.com/dcos/navstar/pull/31
* https://github.com/dcos/minuteman/pull/61
* …
> Upgrade Navstar & Minuteman

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
This Mesos bump includes all the commits in the official Mesos 1.1.0 tag, the fixes for [MESOS-6465](https://issues.apache.org/jira/browse/MESOS-6465) (task_id -> container_id mapping in state.json), as well as "code-complete" for Debugging (I/O switchboard, AttachContainerInput/Output and LNCSession, authz, etc.).
- OSS Mesos: https://teamcity.mesosphere.io/viewLog.html?buildId=502519&tab=report_project134_Results
```
30d6edb Fixed container-logger subprocess environment setup.
8dcef9c Added Mesos logo to the list of files installed for the web UI.
a567345 Made the IO Switchboard wait for the reader to signal before exiting.
57d986c Used agent environment variables for I/O switchboard.
77b16d8 Added authorization support when attaching to container input/output.
be45c94 Added support for …
```
> Bump Mesos SHA to recent master

- gen/build_deploy/aws.py
- gen/build_deploy/azure.py
- gen/calc.py
- gen/internals.py
This allows downstreams to overwrite the value for oauth_available if they would like for the cloud templates. They used to be able to do this because of how dictionary overwriting worked, but with the use of "Sources" it stopped being possible. This changes the functionality back to how it was originally designed to work.
[DCOS-11894](https://dcosjira.atlassian.net/browse/DCOS-11894)
> Make oauth_available always derived, even for cloud templates, optionally from oauth_enabled

- packages/dcos-metrics/extra/metrics.json
- fixed the state directory of the mesos volume to go to the standard path
n/a
> Use /var/lib/dcos/mesos for metrics module state path

- packages/dcos-integration-test/extra/test_mesos.py
- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
- test_util/recordio.py
This change bumps Mesos (and mesos-modules to match) to include debugging fixes.
Also bumping AdminRouter to pickup some debugging support.
But most significant is a dcos-integration test of the new Mesos Debug API calls.
[DCOS-9574](https://mesosphere.atlassian.net/browse/DCOS-9574)
Mesos
https://github.com/mesosphere/mesos/compare/dcos-mesos-master-30d6edb...mesosphere:dcos-mesos-master-e99ea9c
(mostly tests/fixes for debugging)
(3 known cmake build errors, 1 consistently failing test soon-to-be-fixed, and several known flaky tests)
Mesos-modules
(fix build for Mesos interface changes; log-sink module for #1000 and upgrade-fix slipped in too)
Adminrouter
("Disable buffering to mesos agent API and use HTTP/1.1" for debugging support)
> Debugging API changes in Mesos

- gen/calc.py
- packages/dcos-integration-test/extra/test_rlimit.py
Added 'posix/rlimits' to default Mesos isolator list.
This isolator enables the POSIX rlimits support in Mesos. It allows
frameworks to change the default resource limits (both hard and soft)
for their containers, similar to Docker --ulimit flag.
Some data services like Elastic Search or Cassandra typically require
a higher than normal resource limit for their containers, and will do
a check during startup to see if those limits are set properly. This
support in Mesos will unblock them running on DC/OS.
This isolator only affects the launch path of the container. If no
framework is using this feature, adding this isolator to the isolator
list will be a no-op.
[MESOS-6402](https://issues.apache.org/jira/browse/MESOS-6402)
> Added POSIX rlimits support to Mesos

- packages/dcos-integration-test/extra/cluster_fixture.py
- packages/dcos-integration-test/extra/resiliency/test_aws_cf.py
- packages/dcos-integration-test/extra/test_auth.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_service_discovery.py
- test_util/azure_test_driver.py
- test_util/cluster.py
- test_util/cluster_api.py
- test_util/run-all
- test_util/runner.py
- test_util/test_aws_cf.py
- test_util/test_aws_vpc.py
- test_util/test_upgrade_vpc.py
We want to minimize the amount of input needed to run a test and these member variables serve no purpose other than passing through information that can be readily pulled from the config on the host where the test is running:
-provider
-auth_enabled
-dns_search_set
https://mesosphere.atlassian.net/browse/DCOS-11977
> Remove variable pass through for items found locally

- packages/dcos-metrics/buildinfo.json
Bump dcos-metrics to 1.0.0-rc4 to resolve an issue fetching the framework principal.
N/A
> Bump dcos-metrics to 1.0.0-rc4

- flake8_dcos_lint/__version__.py
- flake8_dcos_lint/check_rules.py
- flake8_dcos_lint/checker.py
- flake8_dcos_lint/setup.py
- packages/dcos-integration-test/extra/test_3dt.py
- tox.ini
* Provides ability to add custom rule checks.
[DCOS-12408](https://mesosphere.atlassian.net/browse/DCOS-12408)
...
* The code style test will fail with the introduction of this plugin. Proof that the checking with rules works.
```
./packages/dcos-integration-test/extra/test_3dt.py:27:9: D001 Invalid assertion of type assert <symbol>.ok found.
```
* https://teamcity.mesosphere.io/viewLog.html?buildId=517381
> flake8 plugin for dcos.

- packages/bootstrap/extra/dcos_internal_utils/cli.py
- packages/dcos-log/buildinfo.json
- packages/dcos-log/extra/dcos-log-agent.service
- packages/dcos-log/extra/dcos-log-master.service
no bootstrap required anymore for dcos-logs in upstream
- Bump dcos-log
- Remove the bootstrap from dcos-log
> dcos-log: remove bootstrap

- packages/spartan/buildinfo.json
- packages/spartan/extra/dcos-spartan.service
There were two issues that are cleaned up in this PR
1. Every time we had a TCP connection idle out (and not close cleanly), we printed a warning to the console
2. It bumps the FD limit for Spartan
Component change:
https://github.com/dcos/spartan/commit/baefef9e613ed489d208bf273f8bdfdf8efef7b5
> Upgrade Spartan to have cleaner logging

- packages/cosmos/buildinfo.json
[DCOS-12411](https://mesosphere.atlassian.net/browse/DCOS-12411)
1. https://github.com/dcos/cosmos/commit/da39604cdacbc4f79c84f397ec7fc0d14b83c47c#diff-c51a7c12e1cf4f27093f6f1caf7b54b4
1. https://teamcity.mesosphere.io/viewQueued.html?itemId=520272
-  Return postInstallNotes instead of uninstall notes ([#560](https://github.com/dcos/cosmos/pull/560)) 
- Make sure that we set None to false for selected and framework ([#559](https://github.com/dcos/cosmos/pull/559))
- Add ServiceAlreadyStarted error ([#557](https://github.com/dcos/cosmos/pull/557))
- Fix package ordering …
> Grab latest fix to package describe and install

- ssh/test_integration.py
- ssh/tunnel.py
- test_util/aws.py
- test_util/azure_test_driver.py
- test_util/cluster.py
- test_util/installer_api_test.py
- test_util/runner.py
- test_util/test_aws_cf.py
- test_util/test_aws_vpc.py
- test_util/test_upgrade_vpc.py
- no longer pass ssh_key_path, but rather the key contents
ssh/tunnel.py now handles creating a temp key file with the
correct permissions (and cleans it up)
- safer passing of AWS parameters by casting to str
- no longer need to write to remote host in order to test;
now, everything is injected as a command
- removes unused code in ssh/tunnel.py
- removes unused code in test_util/installer_api_test.py
- no longer pass add_env separately in internals
>  Launch prereqs

- gen/calc.py
- gen/dcos-config.yaml
- gen/test_validation.py
- packages/marathon/build
Bug fix: Marathon should be configured with the name of the default dcos overlay network when overlay networking has been configured at install time.
> set MARATHON_DEFAULT_NETWORK_NAME to the name of the default dcos overlay network

- test_util/run-all
This change upgrades the dcos-vagrant version to a most recent update on Dec 16, 2016.
* [dcos-vagrant-Changes](https://github.com/dcos/dcos-vagrant/compare/7b0b56bde93b8f2b65bb9ec50cd8a0ca932033b2...2b323c4c1942e3f6d484a7375e749929356a4417)
Since that update is backwards compatible no config changes in the repo were required.
Furthermore,  this was tested with
```
root@agent1:~# vagrant --version
Vagrant 1.9.1
root@agent1:~# vbox-img --version
5.1.12r112440
```
And some of the flakiness that we observe with vagrant integration tests were not observed under this configuration.
> Upgrade dcos-vagrant SHA for the Vagrant Integration Tests.

- test_util/runner.py
- currently just adds overhead as it doesnt catch all cases.
- Will be rectified with dcos-launch and fine-grained testing controls
https://mesosphere.atlassian.net/browse/DCOS-12772
> Remove preflight from test runner

- tox.ini
Need to pin the webtest-aiohttp as it is using a different features from a higher version aiohttp than us.
The reasons are explained here: [DCOS-13081](https://mesosphere.atlassian.net/browse/DCOS-13081)
*Tested Change locally*
```
GLOB sdist-make: /dcos/setup.py
py35-unittests create: /dcos/.tox/py35-unittests
py35-unittests installdeps: dnspython, pytest, webtest, webtest-aiohttp==1.1.0
py35-unittests inst: /dcos/.tox/dist/dcos_image-0.1.zip
py35-unittests installed: aiohttp==0.22.5,analytics-python==1.2.6,azure-common==1.1.4,azure-mgmt-network==0.30.0rc4,azure-mgmt-nspkg==1.0.0,azure-mgmt-resource==0.30.0rc4,azure-nspkg==1.0.0,azure-storage==0.32.0,beautifulsoup4==4.5.3,boto3==1.4.3,botocore==1.4.93,certifi==2016.9.26,chardet==2.3.0,click==6.7,coloredlogs==5.2,dcos-image==0.1,dnspython= …
```
> Pinning the version for webtest-aiohttp

- packages/exhibitor/build
`zkCli.sh` expects `zkEnv.sh` to be in the same directory.
```
$ dcos-shell /opt/mesosphere/packages/exhibitor--9b89c1f1654d9f2addfb8dfaa138053d6c6a5eb7/usr/zookeeper/bin/zkCli.sh ls >/dev/null
$ echo $?
0
$ dcos-shell /opt/mesosphere/bin/zkCli.sh ls >/dev/null
/opt/mesosphere/bin/zkCli.sh: line 36: /opt/mesosphere/bin/zkEnv.sh: No
such file or directory
/opt/mesosphere/bin/zkCli.sh: line 39: : command not found
$ echo $?
127
$
```
https://mesosphere.atlassian.net/browse/DCOS-9775
> Add zkEnv.sh to /bin

- dcos_installer/action_lib.py
- dcos_installer/cli.py
- dcos_installer/test_cli.py
* [DCOS-12968](https://mesosphere.atlassian.net/browse/DCOS-12968)
```
$ wget https://s3-us-west-2.amazonaws.com/downloads.dcos.io/dcos/testing/pull/1123/commit/48cb7792006fc47aaf43ab66f8245be659fa4036/dcos_generate_config.sh
$ chmod +x dcos_generate_config.sh
$ ./dcos_generate_config.sh --help
DC/OS Install and Configuration Utility
optional arguments:
-h, --help            show this help message and exit
--hash-password [password]
Hash a password and print the results to copy into a
config.yaml.
--set-superuser-password [password]
Hash the given password and store it as the superuser
password in config.yaml
-v, --verbose         Verbose log output (DEBUG).
--offline             Do not install preflight prerequisites on CentOS7,
RHEL7 in web mode
--cli-telemetry-disabled
Disable the CLI …
```
> Don't expose --uninstall flag when the operation is not complete.

- packages/dcos-history/extra/history/server.py
- packages/dcos-integration-test/extra/test_misc.py
- packages/dcos-oauth/extra/dcos_add_user.py
- packages/exhibitor/build
- packages/exhibitor/extra/start_exhibitor.py
- pkgpanda/build/cli.py
- release/__init__.py
- release/storage/aws.py
- release/storage/azure.py
- release/storage/http.py
- release/storage/local.py
- test_util/azure_test_driver.py
- test_util/run-all
- test_util/test_aws_cf.py
- tox.ini
Bumps dcos-vagrant, pins webtest-aiohttp, and sets exhibitor's JAVA_HOME to get the 1.8.x CI green again.
> Fix CI for 1.8.8

- packages/mesos/buildinfo.json
Bumps Mesos to a recent master SHA (Mesos 1.2 rc not ready yet). Highlights include:
```
d09a6eb Fixed docker runtime isolator argv issue for nested container.
bea98b9 Fixed wrong float serialization in JSON in locales different from C.
3efcd33 Fixed a bug in the default executor around not committing suicide.
be127e6 Fixed memory leak in implementation of Future<T>::after().
3e2e018 Added initial random delay to agent (re)registration.
9408651 Fixed spurious registration bug in framework and agent.
8954735 Modified isolator for dynamic addition/deletion of CNI networks.
f076bb8 Cleaned up Master::markUnreachableAfterFailover.
e5fe811 Simplified `State::recover` interface in the agent.
789e9f7 Kept the listening socket while accept is in flight.
a3a6550 Used process::loop in infinitely …
```
> Bump Mesos to recent master.

- packages/navstar/buildinfo.json
Merges sys.config from minuteman into navstar.  This change was missing from https://github.com/dcos/dcos/pull/1010
Due to the missing config minuteman doesn't submit network metrics.  Fails networking_api integration tests in EE
[DCOS-11299](https://mesosphere.atlassian.net/browse/DCOS-11299)
...
dcos enterprise test_network_api_service.py
https://github.com/dcos/navstar/compare/52d6c144b334e23faa6237c1e06dbd125272f6c3...4ef753e175a93adc597827aa28a836e43b8ccf3d
https://circleci.com/gh/dcos/navstar/260
https://codecov.io/gh/dcos/navstar/tree/4ef753e175a93adc597827aa28a836e43b8ccf3d
> merged minuteman sys.config into navstar sys.config

- gen/calc.py
- gen/dcos-config.yaml
- packages/mesos-modules/buildinfo.json
This commit adds a configuration option to pipe container logs to one of 3 destinations:
* Journald
* The sandbox, with logrotation
* Or both
This change is meant to ease the upgrade process as we transition away from logging to the sandbox, in favor of journald.
NOTE: This component bump also contains changes to the overlay agent module, which now no longer blocks the Mesos agent from starting up if the module cannot start.  See the changelog for more details.
* Changelog: https://github.com/dcos/dcos-mesos-modules/compare/6660b90fbbf69a15ef46d0184e36755881d6a5ae...36ce01e6cf869b4bb2bfe9e91766f984f333f742
* Unit tests: Parameterized existing tests for the three cases.  No CI for this repository yet.
* Coverage: Not available.
* [DCOS-12797](https://mesosphere.atlassian.net/browse/DCOS-127 …
> Add compatibility option for container logs (journald, sandbox, or both).

- packages/dcos-integration-test/extra/util/python_test_server.py
- test_util/marathon.py
- The username being picked up earlier was wrong and caused the test to fail. This change enable the test to get the uid from the environment and use that to compare the user. 
https://mesosphere.atlassian.net/browse/DCOS-10327
https://teamcity.mesosphere.io/viewLog.html?buildId=532479&buildTypeId=ClosedSource_Dcos_DcOsEnterpriseCcmDeployTestSecurityStrict&tab=buildLog
> Fixing the test_if_marathon_app_can_be_deployed_with_mesos_containerizer

- packages/mesos/README.md
This patch updates the Mesos package readme to include the latest versions of the cherry-pick commits that must be applied to open source Mesos before building in DC/OS.
This is a non-functional change.
> Updated the Mesos package readme.

- packages/exhibitor/build
Fixes a bug where exhibitor was building with the jdk present in the base docker container, rather than the defined java pkgpanda package.
> Explicitly set JAVA_HOME for exhibitor gradle build

- build_dcos_launch.sh
- gen/build_deploy/bash.py
- gen/build_deploy/bash/dcos-launch.spec
- test_util/aws.py
- test_util/launch.py
- test_util/test_launch.py
- tox.ini
Initial implementation of DC/OS Launch Utility
-only covers launching generic AWS CF simple templates. Can technically launch any generic cloudformation template, but it all features will only work for a simple deployment
-Covers create, wait, describe, test, and delete
-test optionally takes command line args for interactively working on tests
> Add dcos-launch

- packages/dcos-integration-test/extra/cluster_fixture.py
- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_3dt.py
- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_auth.py
- packages/dcos-integration-test/extra/test_composition.py
- test_util/dcos_api_session.py
- test_util/helpers.py
- test_util/marathon.py
- test_util/test_upgrade_vpc.py
- test_util/test_usage.py
- ApiClient was added with the intention of making it easier to handle common requests by extending all requests with some default. However, this is exactly what requests.session does (and it does it much better with less cruft)
- Also adds a Url abstration to that allows easy URL composing
- By using session, a simple BaseAuth object can be bound
- With these improvements, ApiClient only takes a Url and an optional get_node_port which is a call back for determining ports for an API that has different ports on different nodes
- ApiClient.api_request still takes the same arguments (HTTP verb, something to add to path, node=) but also accepts arbitrary default url substitutions like scheme='http' or query='last_cache=0'
> Use requests paradigms

- packages/dcos-integration-test/extra/api_session_fixture.py
- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/resiliency/test_aws_cf.py
- packages/dcos-integration-test/extra/test_3dt.py
- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_auth.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-integration-test/extra/test_dcos_log.py
- packages/dcos-integration-test/extra/test_ec2.py
- packages/dcos-integration-test/extra/test_endpoints.py
- packages/dcos-integration-test/extra/test_mesos.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_rlimit.py
- packages/dcos-integration-test/extra/test_service_discovery.py
In integration tests, all tests rely upon a fixture called 'cluster'. This is extremely confusing and uninformative. Rather, it should be called what it really is a session object that wraps the DCOS/Adminrouter API
Note: This PR is only for renaming the test fixture. A functional refactor (which gives the harness a well-defined purpose) is here: https://github.com/dcos/dcos/pull/1016
> Rename cluster -> dcos_api_session

- PULL_REQUEST_TEMPLATE.md
Improve the PR template by making it more clear which items are required and which are not.
- [DCOS-12106](https://mesosphere.atlassian.net/browse/DCOS-12106) Update dcos/dcos PR template with contributing rules and train details
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include: 
___
* Developers responsible for code …
> Improve PR template

- test_util/dcos_api_session.py
- test_util/helpers.py
- test_util/test_helpers.py
- test_util/test_upgrade_vpc.py
Adds an app to the upgrade test workload that continuously resolves a Marathon app's DNS name and checks for failure after the upgrade.
This PR also modifies the healthcheck app to ensure a single failed healthcheck causes Marathon to kill the task, and then generically verifies all test apps after the upgrade test by checking whether their running tasks have changed.
https://mesosphere.atlassian.net/browse/DCOS-4414
> Test DNS during upgrade

- packages/marathon/buildinfo.json
- BugFix Release. See https://github.com/mesosphere/marathon/releases/tag/v1.4.0-RC5
- Fixes [#4876](https://github.com/mesosphere/marathon/issues/4876) - Use 'openjdk:8-jdk' container image instead of 'java:8-jdk'.
- Fixes [#4874](https://github.com/mesosphere/marathon/issues/4874) - Document feature flag requirement for TASK_KILLING state.
- Fixes [#4900](https://github.com/mesosphere/marathon/issues/4900) - Do not restart already started task during leader abdication.
- Fixes [#4788](https://github.com/mesosphere/marathon/issues/4788) - Use async InstanceTracker in DeploymentActor.
- Fixes [#4897](https://github.com/mesosphere/marathon/issues/4897) - Fix kill and scale to never scale below 0.
- Fixes …
> Use Marathon 1.4.0-RC5

- test_util/azure_test_driver.py
- test_util/run-all
- test_util/test_aws_cf.py
- test_util/test_aws_vpc.py
- test_util/test_upgrade_vpc.py
Streaming, when combined with the teamcity plugin
causes some output to be randomly unparseable, thus
leading to some tests being ignored and unreported
> Disable streaming for pytest

- test_util/runner.py
Currently, azure fails to run and is not counted as a failure like so:
https://teamcity.mesosphere.io/viewLog.html?buildId=538219&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_DcosOssAzureIntegrati_2&tab=buildLog#_state=271&focus=1655
This is because we need to exit nonzero in order for TeamCity to be able to mute tests. However, if no tests are run, then there is nothing for TeamCity to interpret and the test is considered passing. See https://mesosphere.atlassian.net/browse/DCOS-12772 for fixing this.
This PR will simply correct the syntax error, but extra care will need to be taken when merging until 12772 is fixed
> Fix test runner

- packages/dcos-integration-test/extra/util/python_test_server.py
The test is failing when getpass.getuser tries to get the username. getpass.getuser uses /etc/passwd . The failure occurred when the uid could not be translated to the username. We should rely on only the uid and not the username going forward. 
[DCOS-10327] https://mesosphere.atlassian.net/browse/DCOS-10327
___
* …
> Removing username from operating environment

- packages/mesos/README.md
- packages/mesos/buildinfo.json
Includes various fixes deemed worthy enough to backport to Apache Mesos 1.0.2 and 1.0.3.
Puts DC/OS 1.8.x on an official Mesos tag (more or less).
[DCOS-11525](https://mesosphere.atlassian.net/browse/DCOS-11525) Include Mesos 1.0.3 in dcos-mesos
[DCOS-12412](https://mesosphere.atlassian.net/browse/DCOS-12412) Agents disconnected from the cluster after installing kafka service
https://github.com/mesosphere/mesos/compare/dcos-mesos-1.0.x-837bb4e...mesosphere:dcos-mesos-1.0.3-rc1
> Bump dcos-mesos to Apache Mesos 1.0.3-rc1

- packages/marathon/buildinfo.json
- Bug fix release for Marathon. We discovered a serious migration issue in migration to 1.1.5.
- Fixes [Issue 4854](https://github.com/mesosphere/marathon/issues/4854) Cannot start marathon (1.4.0-RC3) with `default_accepted_resource_roles = *`
- Fixes [Issue 4637](https://github.com/mesosphere/marathon/issues/4637) Fixes #4637 Allow filtering SSE events by types
- Fixes [Pull 4927](https://github.com/mesosphere/marathon/pull/4927) Parse JSON event only once before broadcast
- Fixes [Pull 4711](https://github.com/mesosphere/marathon/pull/4711) Added a MigrationTo1_1 class to handle broken app groups
- Fixes [Issue 4968](https://github.com/mesosphere/marathon/pull/4968) Prevent Migration if the StorageVersion is too new (#4968) (Jason Gilanfarr)
If this is …
> update marathon to 1.3.8 for dc/os 1.8.8

- packages/exhibitor/buildinfo.json
Allows exhibitor to function under high load.
This fixes an issue where exhibitor leaked / opened too many file descriptors under load.
Configure the Jetty Server to use non-blocking I/O for accepting new connections and limit the number of pending requests.
[DCOS-558](https://dcosjira.atlassian.net/browse/DCOS-558)
...
This behaviour emerges from an exhibitor node under load and would be very tricky to build a reliable test for. The effect can be checked by running 
```
while true; do sudo bash -c 'ulimit -n 10000; ab -n 100000 -c 4096 -s 1 http://172.17.0.2:8181/exhibitor/v1/cluster/status'; done
```
Bumps …
> bump exhibitor SHA to fc44d4fe0e612381646a4738a1a898867b2086d8t

- flake8_dcos_lint/setup.py
* 2.3.0 broke our builds: https://github.com/PyCQA/pycodestyle/issues/617
- [DCOS-13518](https://mesosphere.atlassian.net/browse/DCOS-13518) Pin pycodestyle, because it breaks our CI too often
- **NA** Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
> Pin pycodestyle version to 2.2.0

- dcos_installer/installer_analytics.py
- gen/build_deploy/aws.py
- gen/build_deploy/azure.py
- gen/build_deploy/bash.py
- gen/dcos-config.yaml
- gen/test_validation.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-signal/buildinfo.json
- test_util/cluster.py
- test_util/installer_api_test.py
- test_util/run-all
Feed `platform` gen config to dcos-signal as `gen_platform`.
`platform` is the WHAT, while `provider` is the HOW. For example, `onprem` (provider) is used by "advanced install" onto `aws` (platform) using VPC rather than cloud formation templates.
Depends on https://github.com/dcos/dcos-signal/pull/31
> Add platform field to config.yaml

- packages/openssl/buildinfo.json
This bumps OpenSSL to version 1.0.2k (released on January 26th).
https://www.openssl.org/news/cl102.txt
https://mta.openssl.org/pipermail/openssl-announce/2017-January/000091.html
> openssl: bump to 1.0.2k

- gen/calc.py
- tests/test_installer_backend.py
This bumps the version of the branch to 1.8.8
___
> Bump version to 1.8.8

- docs/admin-ports.md
- gen/dcos-config.yaml
Set LIBPROCESS_PORT for marathon (15101) and metronome (15102) in the dcos-config.yaml explicitly. Update the admin-port documentation.
Backport of https://github.com/dcos/dcos/pull/1121
https://mesosphere.atlassian.net/browse/DCOS-12706
___ …
> Set LIBPROCESS_PORT for marathon and metronome

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-oauth/extra/dcos_add_user.py
- test_util/dcos_api_session.py
Spartan supports resolving `zk-1.zk, zk-2.zk, ..., zk-5.zk` to the IPs of the running zookeeper instances. When there are fewer instances than 5, the extra hostnames resolve to those servers that are present.
This allows services to run even if their local zookeeper instance is down.
This is nothing new. This patch just does some house cleaning by replacing one or two places where the old style was still used.
- [DCOS-626](https://dcosjira.atlassian.net/browse/DCOS-626) Standardize zookeeper address string
___
> standardize on zookeeper connection string

- gen/dcos-config.yaml
- packages/mesos-dns/build
- packages/mesos-dns/buildinfo.json
Update mesos-dns to build instead of downloading a binary.
Fix race between mesos-dns serving empty data (NXDOMAINs) and polling state.json at startup.
Updates mesos-dns to HEAD, bringing in a couple of commits from the last few months.
Also included code that disables setting the truncate bit and config change to activate it.
- [DCOS-10809](https://mesosphere.atlassian.net/browse/DCOS-10809): DNS unavailable during DC/OS 1.8.5 upgrade
- [DCOS-13193](https://mesosphere.atlassian.net/browse/DCOS-13193): Review EDNS fixes, merge to master if needed
- [DCOS-13507](https://mesosphere.atlassian.net/browse/DCOS-13507): build mesos-dns in DC/OS build instead of pulling from CI …
> mesos-dns bugfixes and truncate bit disable

- gen/dcos-config.yaml
- packages/cosmos/build
- packages/dcos-integration-test/extra/test_endpoints.py
The Cosmos service currently runs with default options for its admin port (`0.0.0.0:9990`) and its http port (`0.0.0.0:7070`.) We should restrict Cosmos to listen on the loopback interface only.
This change prevents bypassing Admin Router via direct access to Cosmos.
[DCOS-613](https://dcosjira.atlassian.net/browse/DCOS-613)
Supercedes https://github.com/dcos/dcos/pull/1134
> cosmos: restrict admin and http ports to localhost + test fix

- packages/dcos-integration-test/extra/util/delete_ec2_volume.py
It is an on going battle with AWS to find every part of code that fails due to API rate limiting and then patching with this decorator duct tape
> Make delete volumes resilient to rate limiting

- packages/dcos-integration-test/extra/test_sysctl.py
- packages/mesos/buildinfo.json
Set default vm.max_map_count and vm.swappiness for frameworks like elasticsearch
- [DCOS-10611](https://mesosphere.atlassian.net/browse/DCOS-10611) Swappiness and MMap Settings
___
> Set default vm.max_map_count and vm.swappiness for frameworks

- gen/azure/cloud-config.yaml
- packages/3dt/build
- packages/adminrouter/extra/dcos-adminrouter-agent.service
- packages/adminrouter/extra/dcos-adminrouter.service
- packages/cosmos/build
- packages/dcos-history/extra/dcos-history.service
- packages/dcos-log/extra/dcos-log-agent.service
- packages/dcos-log/extra/dcos-log-master.service
- packages/dcos-metrics/extra/dcos-metrics-agent.service
- packages/dcos-metrics/extra/dcos-metrics-master.service
- packages/dcos-oauth/extra/dcos-oauth.service
- packages/dcos-signal/extra/dcos-signal.service
- packages/docker-gc/extra/dcos-docker-gc.service
- packages/erlang/build
- packages/exhibitor/extra/dcos-exhibitor.service
- packages/logrotate/extra/dcos-logrotate-agent.service
- packages/logrotate/extra/dcos-logrotate-master.service
- packages/marathon/build
- packages/mesos-dns/extra/dcos-mesos-dns.service
- packages/metronome/build
- packages/navstar/extra/dcos-navstar.service
- packages/pkgpanda-api/extra/dcos-pkgpanda-api.service
- packages/rexray/extra/dcos-rexray.service
Of all the DC/OS services, only spartan and mesos-{master,slave,public-slave}
set file limits. In all other cases the limit defaults to whatever is the default
for the distribution. In the case of CoreOS the default soft limit is 1024.
This PR sets the default file limit of all other dcos-* services to 16384.
Ideally this kind of change should inspect a very large, very busy cluster
and set the limits accordingly.
In future, as our monitoring improves, we will collect peak usage from large
clusters and adjust the limits accordingly.
Ideally all services should run with a predictable maximum number of open files
to support far tighter limits.
- [DCOS-625](https://dcosjira.atlassian.net/browse/DCOS-625) Explicit file descriptor limits for all DC/OS services …
> packages: set open file limits in systemd config files

- packages/dcos-integration-test/extra/resiliency/test_aws_cf.py
- test_util/aws.py
- test_util/cluster.py
- test_util/helpers.py
- test_util/launch.py
- test_util/test_aws_cf.py
- test_util/test_aws_vpc.py
- test_util/test_launch.py
- test_util/test_upgrade_vpc.py
In order to support launching Advanced (aka Zen) AWS templates, DC/OS Launch needed to be aware of which class representation from test_util.aws. Also, the Zen templates do not natively support turnkey deployment, so this PR also adds a helper to support exactly this case
- Clusters are determined to be either simple or zen when they are fetched via checking for the presence of resources that are exclusive between the two
- The only interface difference for a user deploying a zen stack will be in the case where the user did not follow the docs and create network resources in setup, in which case, (s)he can add a field to the config called ```zen_helper: true```
- Cleans up existing AWS test code to have more sensible classes, generators, and properties
- Simplifies key handling by …
> Add dcos-launch support for AWS advanced clusters

- packages/exhibitor/extra/start_exhibitor.py
Currently Zookeeper writes its logs to the `/var/lib/dcos/exhibitor/zookeeper/zookeeper.out` file and also to the `journald` service. Since the file isn't managed by any logrotation service it grows unbounded and can fill up disk. This patch links `/var/lib/dcos/exhibitor/zookeeper/zookeeper.out` to a `/dev/null` to prevent filling up disk. Users should use `journald` service to examine `zookeeper` and `exhibitor` logs. Part of the patch is also setting explicitly where the log file exists so it won't happen that location will change in future releases without controlling it.
- [DCOS-595](https://dcosjira.atlassian.net/browse/DCOS-595) DC/OS Zookeeper does not log manage. …
> DCOS-595: Stop writing zookeeper log to a file

- packages/dcos-integration-test/extra/resiliency/test_aws_cf.py
- test_util/aws.py
- test_util/cluster.py
- test_util/helpers.py
- test_util/launch.py
- test_util/test_aws_cf.py
- test_util/test_aws_vpc.py
- test_util/test_launch.py
- test_util/test_upgrade_vpc.py
- Adds fetch stack helper that can automatically return the correct AWS Stack representation
- Remove most boto/aws - level logic and concentrate it entirely inside test_util/aws.py
- Refactors AwsCfAdvanced into AwsZenCfStack and turn each of the resource stacks within zen into its own class
- Note: all of the @classmethod create's in this file are essentially bits of dcos-launch and will be removed when we switch infrastructure to use dcos-launch
https://mesosphere.atlassian.net/browse/DCOS-13298
> Refactor AWS Zen stack resource model

- gen/build_deploy/bash/dcos-launch.spec
- setup.py
- ssh/tunnel.py
- test_util/aws.py
- test_util/launch.py
- test_util/launch_cli.py
- test_util/runner.py
- test_util/test_launch.py
- suppresses select libraries to prevent obfuscation
- adds truncated options for existing long-name options
- moves CLI code to its own module
> Add log-level control for dcos-launch

- test_util/test_upgrade_vpc.py
Refactor test_upgrade_vpc.py by moving all test logic into a class
* The new class VpcClusterUpdateTest now provides an abstraction from running the test and configuring the test. This will allow the test to be instantiated with a different cluster api when ran against and enterprise cluster.
* Add teamcity logging messages for each of the major scopes run in this test
> Refactor test_upgrade_vpc.py by moving all test logic into a class

- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-metrics/buildinfo.json
- Adds tagging 
- Adds unit values to metrics
- Adds better metric gathering for node collector
Merged PR: https://github.com/dcos/dcos-metrics/pull/61
[DCOS-12410](https://jira.mesophere.com/browse/DCOS-12410) Add unit values and arbitrary tag support
```
ok      github.com/dcos/dcos-metrics/util/http/helpers  0.006s
?       github.com/dcos/dcos-metrics/util/http/profiler [no test files]
github.com/dcos/dcos-metrics/collectors/framework/framework.go:67:      New                             100.0%
github.com/dcos/dcos-metrics/collectors/framework/framework.go:77:      RunFrameworkTCPListener         75.0%
github.com/dcos/dcos-metrics/collectors/framework/framework.go:102:     handleConnection                60.5%
github.com/dcos/dcos-metrics/collectors/framework/framework.go:180: …
```
> Bump metrics to test new build

- packages/dcos-integration-test/extra/test_mesos.py
- packages/mesos/README.md
- packages/mesos/buildinfo.json
This PR:
* Updates the Mesos cherry-picks which we routinely apply before incorporating Mesos into DC/OS. These needed to be rebased to accommodate recent changes to the Mesos UI.
* Bumps the Mesos package SHA
* Updates a Mesos/Marathon integration test to accommodate changes to the Mesos HTTP API.
https://github.com/mesosphere/dcos-enterprise/pull/563
https://mesosphere.atlassian.net/browse/DCOS-13203
https://issues.apache.org/jira/browse/MESOS-6917
https://mesosphere.atlassian.net/browse/DCOS-13116
https://issues.apache.org/jira/browse/MESOS-6866
https://mesosphere.atlassian.net/browse/DCOS-13655
https://issues.apache.org/jira/browse/MESOS-5931
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to …
> Updated Mesos package README, bumped Mesos, updated tests.

- packages/exhibitor/build
This PR fixes the issue of missing `JNA` library for Zookeeper purging subprocess launched by `exhibitor`.
Exhibitor periodically launches purging process that makes sure that only relevant data stay on a disk. The process is launched as a subprocess launching new `java` process. The exhibitor searches for libraries that should be included in a `classpath` for the subprocess. By predefined rules the exhibitor includes every library from `[zookeeper-home]/libs` that include `log4j` or `sfl4j` in a file name. As a result it included `log4j-systemd-journal-appender-1.3.2.jar` but not `jna-4.2.2` which is a dependency for the first library.
This patch renames final `jna-4.2.2.jar` file to `log4j-jna-4.2.2.jar` to make sure it will get included in the purging subprocess classpath.
- …
> exhibitor: make sure that JNA library is included for ZK subprocesses

- packages/marathon/buildinfo.json
* bump Marathon from 1.4.0-RC7 to 1.4.0-RC8
- [MARATHON-1378](https://jira.mesosphere.com/browse/MARATHON-1378) pod tasks are missing DiscoveryInfo; broken for minuteman
- [MARATHON-1383](https://jira.mesosphere.com/browse/MARATHON-1383) Marathon is not setting `network-scope` flag for mesocontainerizer
* dcos-networking team is providing tests for MARATHON-1378 and MARATHON-1383
___ …
> bump marathon to v1.4.0-RC8

- test_util/test_aws_cf.py
- test_util/test_aws_vpc.py
- test_util/test_upgrade_vpc.py
Emergency CI Fix
- removes usage of default key in favor of generating a new key each time
- extra keys will be garbage colected by cloud cleaner
- user can no longer specify pre-existing clusters (to aid simplicity)
- standardizes tests to start with the string 'dcos-ci-test' to allow easier resource cleanup
> Use generated SSH keys

- packages/mesos/README.md
- packages/mesos/buildinfo.json
Elastic Search fails fetching its artifacts. This patch adds a new cherry-pick on top of the usual suspects for Mesos, to unblock framework developers while we wait for the fix to land in Apache Mesos (1.2.0).
In Review: https://reviews.apache.org/r/56711/
- [DCOS-13965](https://dcosjira.atlassian.net/browse/DCOS-13965) Fetcher breaks down on attempting to access SSL cert.
https://github.com/dcos/dcos/compare/5af46904b59956af67b3f82284e0cbc859665128...786771f09e160e19014ac347b66c9bdca08672f1
package Mesos:
[https://github.com/apache/mesos/compare/04085c80c2c84ea6b8375042d61797f7f46138fd...abe6e6390612f523a3106192d719 …
> Bumped mesos to include a potential fix for the fetcher.

- packages/marathon/buildinfo.json
This reverts commit cafe34aa046789469795cb15c5c7709828f861ed.
This reverts marathon back to RC7
- https://jira.mesosphere.com/browse/DCOS-13975
___
It is best to proactively ask …
> Revert "bump marathon to v1.4.0-RC8"

- packages/rexray/buildinfo.json
Bumps rexray to support govcloud regions
- https://jira.mesosphere.com/browse/DCOS-11335
___
It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in …
> Grab rex ray with updated aws-go-sdk

- gen/dcos-config.yaml
- test_util/test_upgrade_vpc.py
Currently, all command tasks will become "over-committed" by 0.1 CPUs
and 32 MB of memory, per task, after an upgrade.  This is because the
agent generates the ExecutorInfo for command tasks with this slight
over-committment of resources.
The agent determines whether an executor is a command executor by
comparing the executor's path with its own `--launcher_dir`.  Because
the `--launcher_dir` changes (by a SHA in the path) during every upgrade,
all command executors will be considered "custom" executors after an
upgrade.  The agent will report executor resources to the master for
non-command executors only.
- [DCOS-13672](https://jira.mesosphere.com/browse/DCOS-13672) Mesos Reports Over allocated CPU during Upgrade
> Add a static value for the agent `--launcher_dir` flag.

- test_util/azure.py
- test_util/test_azure.py
- test_util/test_dcos_api_session.py
- test_util/test_helpers.py
The current tooling only allows deploying a specific template and does a lot of custom logic. This PR breaks that logical into sensible chunks that are independent of DC/OS environment
Included in this PR is a helper function that will pull down a Azure template, parse the parameters, and then type cast the user parameters as indicated. The motivation for this is that Azure parameters are naturally JSON, so a user should be able to pass a JSON or YAML parameter specification to the azure wrapper and launch. The YAML or JSON parsers have to way to tell if a string should be a string or an integer or a boolean, and as such the user would have to explicitly detail the types for no benefit what so ever.
Edit:
PR also includes a small shuffling of unit tests relevant to the code being modified …
> Convert acs deploy to generic utilities

- gen/calc.py
- packages/mesos/README.md
- packages/mesos/buildinfo.json
This PR enables GPU support in DC/OS by default.
This means that if your agents have Nvidia GPUs installed on them as well as the proper Nvidia NVML library (> 340.29) installed on them, GPUs will be offered to your frameworks as a resource by those agents.
Previously, GPU support was an install-time parameter that required *all* agents in your cluster to have the proper NVML libraries installed on them. This PR removes this restriction and turns on GPU support by default. Operators should not have to perform any extra configuration to take advantage of this feature.
One caveat to be aware of, however, is that mesos will only offer GPU resources to frameworks that *opt-in* to receive these resources. If your framework has not opted-in, it will receive *no* offers from agents that have …
> Bump Mesos, Turn on GPU support by default.

- packages/dcos-signal/buildinfo.json
Bumps signal service requests timeout to 15 seconds to compensate for services that might be requesting data from API's not native to a DC/OS cluster (in example, Cosmos reaches out to S3, which is prone to variable lag). 
https://jira.mesosphere.com/browse/DCOS-12267
```
➜  dcos-signal malnick/DCOS-12267 ✓ make test
+test
go test github.com/dcos/dcos-signal github.com/dcos/dcos-signal/config github.com/dcos/dcos-signal/signal -v -cover
?       github.com/dcos/dcos-signal     [no test files]
time="2017-02-14T17:13:30-08:00" level=warning msg="Service account not detected, continuing with out secure requests." 
=== …
```
> Bump signal service timeout to 15 seconds

- gen/dcos-config.yaml
- packages/adminrouter/buildinfo.json
- packages/dcos-log/buildinfo.json
This PR changes in AR:
* refactors cache, introduces CACHE_MAX_AGE_(HARD|SOFT)_LIMIT variables
* removes a couple of bugs:
* `/agent` endpoint where the Nginx was incorrectly interpreting URLs that only contained `/agent/<agent-id>` endpoint and nothing else. Agent, in this case, was receiving original path component.
* increase logging verbosity by changing log level from notice to info
* add (marathon|mesos)-leader redirecting feature for system API (`marathon-leader.lua`)
* add `/system/v1/leader/mesos` and `/system/v1/leader/marathon` endpoints
* make all timing variables for cache configurable using ENV vars
* switch history service to `leader.mesos` upstream as per DCOS-13598
* refactor Server-Sent-Events configuration:
* for endpoints we own (logging, metrics), we switch to …
> Adminrouter: refactor cache, system API leader endpoints, history service's upstream uses leader.mesos

- packages/dcos-metrics/buildinfo.json
Updates metrics service to query only agent state per changes shipped in Mesos 1.2
- [DCOS-13688](https://dcosjira.atlassian.net/browse/DCOS-13688) Metrics service causes excessive master load
- [DCOS-13936](https://mesosphere.atlassian.net/browse/DCOS-13936) Metrics service should use agent not master state. 
___
* …
> Ensure metrics service uses agent state

- packages/marathon/buildinfo.json
Move to marathon 1.4.0 GA which is more or less identical to 1.4.0 RC9 (#1254) except for the changelog.
- [x ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [1.4.0](https://github.com/mesosphere/marathon/releases/tag/v1.4.0)
___
* Developers who understand …
> Upgrade marathon to 1.4.0

- packages/mesos/README.md
- packages/mesos/buildinfo.json
Any custom executors using checkpointed resources will fail without this
patch. We only include it here as a quick fix until we bump mesos to
1.2.0-rc2 next week.
- [MESOS-7137](https://issues.apache.org/jira/browse/MESOS-7137) Custom executors cannot use any reserved resources.
Custom executors (specifically Cassandra) are failing without this fix. The test will be to make sure these frameworks now work again.
> Add mesos patch to fix regression with custom executors failing.

- test_util/test_upgrade_vpc.py
Fixes error running integration suite for upgrade tests
> Add space between env args and py.test

- gen/dcos-config.yaml
This PR adds the logging configuration to the UI config so they can easily switch between the two logging back ends. 
- [DCOS_OSS-645](https://jira.mesosphere.com/browse/DCOS_OSS-645)
___
* Developers responsible for code that interacts with or depends on the code being …
> Add logging type to UI config

- packages/marathon/buildinfo.json
marathon 1.4.0 broke `PUT` on `/v2/apps`, this is fixed within 1.4.1.
- https://github.com/mesosphere/marathon/issues/5211
- https://github.com/mesosphere/marathon/pull/5217
___ …
> update marathon to version 1.4.1

- gen/build_deploy/bash.py
When installing dcos by cli, I got following error while running `bash dcos_install.sh master` 
```
Starting DC/OS Install Process
Running preflight checks
Checking if DC/OS is already installed: PASS (Not installed)
PASS Is SELinux disabled?
awk: line 32: illegal reference to array cv
awk: line 32: illegal reference to array sv
awk: line 32: illegal reference to array cv
awk: line 32: illegal reference to array sv
Checking if docker is installed and in PATH: PASS
dcos_install.sh: line 232: $3: unbound variable
```
related code:
```
y = length(cv) > length(sv) ? length(cv) : length(sv)
```
I found it's because that debian default installed mawk doesn't support length(ARRAY).
Then I changed like this pull request and it works.
It supports both mawk and gawk.
> make the awk script compatible with both mawk and gawk

- packages/dcos-integration-test/extra/test_mesos.py
In Enterprise `security:strict` mode the `mesos-master` and `mesos-agent` processes check the `Authorization` header and forbids unauthorized requests. They also supports only `https`. 
This PR fixes a test by replacing direct use of the `requests` library with the recently added `dcos_api_session` fixture that provides a similar API. Requests made using this fixture have a valid `Authorization` header injected. It also chooses the scheme (ie., `http` / `https`) appropriate to the cluster's security mode.
The initial `Connection Refused` failure was due to use of `http://` instead of `https://`. Fixing that revealed what we already knew: the `mesos-master` and `mesos-agent` processes would forbid unauthorized requests.
- [DCOS-14161](https://jira.mesosphere.com/browse/DCOS-14161) Fix …
> dcos-integration-test: use dcos_api_session in test_mesos.py

- packages/dcos-metrics/buildinfo.json
This PR fixes CPU times being pushed to 0
https://github.com/dcos/dcos-metrics/pull/67
https://jira.mesosphere.com/browse/DCOS-14035
___ …
> Bump metrics service to fix 0 CPU results

- packages/mesos/README.md
- packages/mesos/buildinfo.json
Bumps dcos-mesos to the official Apache Meso 1.2.0-rc2 tag to include such critical fixes as:
```
e1c11f0 Fixed fetcher to not pick up environment variables it should not see.
4683320 Fixed nested container agent flapping issue after reboot.
056978a Modified the executor driver to always relink on agent failover.
12e99f7 Fixed a bug around executor not able to use reserved resources.
d80af6c Fixed a crash on the default executor due to a failed invariant check.
7e5439d Fixed a crash on the agent when handling the SIGUSR1 signal.
e53fcaf Fixed a crash on the master upon receiving an invalid inverse offer.
```
- [CORE-864](https://jira.mesosphere.com/browse/CORE-864) Mesos masters crashing after receiving inverse offers
- [CORE-779](https://jira.mesosphere.com/browse/CORE-779) Bump …
> Bump dcos-mesos to 1.2.0-rc2

- gen/build_deploy/bash.py
I think its a minor bug. We would never run into this in currently supported distros. But I happened to stumble upon the logic which seems incorrect.
I believe there is a bug in the code block : 
```
$( echo '1' | sort -V >/dev/null 2>&1 || exit 1 )
RC=$?
if [[ "$RC" -eq "2" ]]; then
```
Bash is confusing in that 0 is true(success) non-zero is false(failure) 
Current logic
If `sort -V` is valid, its retncode will be 0, `||` will short circuit and `$?`=0
If  `sort -V` is invalid its retncode will be 2, `||` will not short circuit and exit 1 will be executed  and `$?`=1
I think && is what was intended to be used.
New logic 
If `sort -V` is valid, its retncode will be 0, `&&` will not short circuit and exit 1 will be executed  and `$?`=1
If  `sort -V` is invalid its retncode will be 2, `&&` …
> Fix the sort -V capability check

- packages/adminrouter/extra/src/test-harness/modules/generic_test_code.py
- packages/adminrouter/extra/src/test-harness/tests/test_agent.py
- packages/adminrouter/extra/src/test-harness/tests/test_master.py
AdminRouter regression test that checks passing `X-Accel-Buffering` header upstream.
Original PR: https://github.com/dcos/adminrouter/pull/54
- [DCOS-14147](https://jira.mesosphere.com/browse/DCOS-14147) Add regression tests for X-Accel-Buff header bug
> AdminRouter: Add regression tests for X-Accel-Buffering passing

- packages/adminrouter/extra/src/master/cache.lua
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/marathon.py
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
Adds new AR unit test that exercises Marathon apps caching
Original PR: https://github.com/dcos/adminrouter/pull/55
- [DCOS-14066](https://jira.mesosphere.com/browse/DCOS-14066) Admin Router: add tests for Marathon svcapps caching
> AdminRouter: Add tests for Marathon svcapps caching

- packages/adminrouter/extra/src/master/cache.lua
AdminRouter cache update occurs every 20-45 seconds instead of desired 25s interval. This is due to Nginx reloads interfering with update coroutines and is going to be fixed in DCOS-5809, but for now, we need to eliminate "stale cache" warning messages. They appear way too frequently in the logs even though the cache was eventually updated. 
With CACHE_MAX_AGE_SOFT_LIMIT set to 75s, there have to be at least two failed attempts to update the cache for the warning to appear.
More details can be found in the Jira issue itself.
- [DCOS_OSS-693](https://dcosjira.atlassian.net/browse/DCOS_OSS-693) Adminrouter: set CACHE_MAX_AGE_SOFT_LIMIT to 75s
https://github.com/mesosphere/dcos-enterprise/pull/657
> Adminrouter: Increase CACHE_MAX_AGE_SOFT_LIMIT as per DCOS_OSS-693

- PULL_REQUEST_TEMPLATE.md
We recently moved to new on-prem servers, so the old URLs:
https://dcosjira.atlassian.net/browse/DCOS
https://mesosphere.atlassian.net/browse/DCOS
won't work anymore, and instead we'll need to use
https://jira.dcos.io/browse/DCOS_OSS
https://jira.mesosphere.com/browse/DCOS
More recently, the public dcosjira projects were imported into the same JIRA instance, which means all the tickets from https://jira.dcos.io/browse/DCOS were renamed to https://jira.dcos.io/browse/DCOS_OSS (also accessible via https://jira.mesosphere.com/browse/DCOS_OSS )
> Update JIRA links in PR template.

- packages/3dt/extra/dcos-3dt-agent.service
- packages/3dt/extra/dcos-3dt-master.service
- packages/3dt/extra/dcos-3dt.socket
- packages/adminrouter/buildinfo.json
- packages/adminrouter/docker/Dockerfile
- packages/adminrouter/docker/requirements-tests.txt
- packages/adminrouter/extra/src/common/main.conf
- packages/adminrouter/extra/src/test-harness/modules/runner/common.py
- packages/adminrouter/extra/src/test-harness/tests/conftest.py
- packages/adminrouter/extra/src/test-harness/tests/test_common.py
- packages/dcos-integration-test/extra/test_units.py
- packages/dcos-log/extra/dcos-log-agent.service
- packages/dcos-log/extra/dcos-log-master.service
- packages/dcos-log/extra/dcos-log.socket
- packages/dcos-metrics/extra/dcos-metrics-agent.service
- packages/dcos-metrics/extra/dcos-metrics-agent.socket
- packages/dcos-metrics/extra/dcos-metrics-master.service
- packages/dcos-metrics/extra/dcos-metrics-master.socket
- packages/pkgpanda-api/extra/dcos-pkgpanda-api.service
- packages/pkgpanda-api/extra/dcos-pkgpanda-api.socket
- packages/pkgpanda-api/extra/pkgpanda-api.sh
- pkgpanda/__init__.py
Unix sockets that are managed by systemd default to having mode 0666. This is a hole in our security. 
This PR
- restricts access to socket files to the `root` user and members of the `dcos_adminrouter` group.
- patches pkgpanda so it doesn't complain if the group specified in the `buildinfo.json` doesn't exist already on condition that it matches the username of the user being created. That group would be created as part of creating the user anyway, but now we can be explicit about the fact in our `buildinfo.json` files.
- adds the `dcos_adminrouter` supplementary group to the service systemd units.
- sets the group adminrouter worker processes run as to `dcos_adminrouter`.
- [DCOS-14113](https://jira.mesosphere.com/browse/DCOS-14113) adminrouter: run worker processes with groups …
> Restrict access to /run/dcos unix socket files

- packages/adminrouter/extra/src/test-harness/modules/mocker/common.py
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/marathon.py
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/recording.py
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
* Adds new method to send arbitrary encoded response from Recording mock endpoint
* Improves startup and teardown times for mock servers
- [DCOS-14067](https://jira.mesosphere.com/browse/DCOS-14067) add tests for EE auth AR
> AdminRouter: Test library improvements

- packages/curl/build
This addresses https://jira.mesosphere.com/browse/DCOS_OSS-721.
A copy of the commit msg:
```
This adds a second default trust database that affects all
standard invocations and usage of curl and libcurl within
DC/OS. DC/OS operators can now place custom trusted root CA
certificates (in the OpenSSL PEM format in single files) in
the directory /var/lib/dcos/pki/tls/certs (must be created
if not yet existing, must be re-hashed if contents change).
This for example affects the Mesos agent fetcher mechanisms
for pulling Docker images or remote resources via HTTPS.
```
- [DCOS_OSS-721](https://jira.mesosphere.com/browse/DCOS_OSS-721) Curl: add location where operators can place additional trusted root CA certificates
If you are changing components or packages in DC/OS (e.g. you are bumping the …
> curl: add --with-ca-path configure option

- test_util/azure.py
- test_util/test_azure.py
CI supporting builds now has the ability to
garbage collect Azure, like our AWS CF deploys
> Allow Azure clusters to persist

- Jenkinsfile
Adds Slack notifications for failed builds on the master branch.
- [DCOS-14159](https://jira.mesosphere.com/browse/DCOS-14159) Notifications for failed master-branch builds
> Jenkinsfile: Add slack notifications for master branch build failures

- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-metrics/buildinfo.json
Adds container metric tags, removes abusive reflect usage to derive metric names from struct JSON tags, add container unit values, fixes a bug where many container ID datapoints come up in a request to /container/<container_id>. 
- https://jira.mesosphere.com/browse/DCOS_OSS-736
- https://jira.mesosphere.com/browse/DCOS_OSS-729
- https://jira.mesosphere.com/browse/DCOS-14383
- https://jira.mesosphere.com/browse/DCOS-14429
___
All PRs require 2 approvals using github's …
> Container metric tags, better container metric transformations

- dcos_installer/backend.py
- pkgpanda/__init__.py
- pkgpanda/actions.py
- pkgpanda/util.py
This includes packages in the artifacts that get uploaded along with generated AWS templates.
This also fixes an issue where failed downloads to tempfile locations during node setup cause an incidental error that hides the original download error.
- [DCOS-14381](https://jira.mesosphere.com/browse/DCOS-14381) Various reports of failure when using templates generated by --aws-cloudformation
> Upload packages along with AWS advanced templates

- packages/mesos/buildinfo.json
Bumps Mesos to be based off the official 1.2.0 tag instead of the rc2 tag (same SHA).
Also includes a sandbox permissions fix cherry-picked for CORE-900.
- [CORE-779](https://jira.mesosphere.com/browse/CORE-779) Bump dcos-mesos to Mesos 1.2
- [CORE-900](https://jira.mesosphere.com/browse/CORE-900) Command task with image specified should not set dir/files under sandbox owned by root.
- [MESOS-7208](https://issues.apache.org/jira/browse/MESOS-7208) Persistent volume ownership is set to root when task is running with non-root user
- [DCOS-14292](https://jira.mesosphere.com/browse/DCOS-14292) SSL module should change the ownership of the `.ssl` directory in sandbox.
> Bump mesos to 1.2.0 official.

- gen/calc.py
This PR is currently blocked the following tickets and should not be merged until these land:
https://jira.mesosphere.com/browse/DCOS_OSS-645
https://jira.mesosphere.com/browse/DCOS-14010
We discovered a bug in journald which spikes CPU usage to 100% even under moderate load with rate-limiting turned on.
This is a known performance bug.
https://github.com/systemd/systemd/issues/5102
If we are intent on using journald in the future (which I think we are), the only way to deal with this problem is to get a patched version of journald in place that fixes the bug.
There are only 2 options for that:
(1) wait for it to get patched upstream
(2) patch it ourselves
If we wait for it to get patched upstream, there are two complications:
(1) we don't when / if this would ever happen
(2) it would …
> Turn task-level journald logging off by default.

- packages/adminrouter/extra/src/Makefile
Make AdminRouter `make test` work on Mac (docker-machine).
The `ip` command isn't present on Mac and even if it were, when using docker-machine the bridge interface is not present on the host machine, only inside the docker-machine VM. So to get that IP, you can run the IP detection inside a docker container (using alpine). This should work on both Mac and any variety of Linux.
Since `make test` already runs the tests in a docker container, it's no bid deal to use docker to look up the IP to use for docker dns.
> Make AdminRouter `make test` work on Mac (docker-machine)

- packages/erlang/buildinfo.json
I tried building locally and failed because this ref is not in the repo.
Looks like this was pinned against a merge commit that is no longer in the branch?
> Fix erlang ref

- gen/dcos-config.yaml
While investigating failures in https://github.com/dcos/dcos/pull/1091 we discovered that sometime early in 1.9, we injected dcos-log config files in the middle of the `/etc/mesos-slave-common` definition, which renders the (conditional) setting of MESOS_DOCKER_REGISTRY, MESOS_DOCKER_CONFIG, and MESOS_HOOKS futile, since they are now set in `/etc_slave_public/dcos-log-config.json` instead of becoming Mesos flags. This patch moves the dcos-log configs out, and reunites the conditional parts of mesos-slave-common with the rest.
- [DCOS-14473](https://jira.mesosphere.com/browse/DCOS-14473) MESOS_DOCKER_REGISTRY, MESOS_DOCKER_CONFIG, and MESOS_HOOKS ignored in OSS dcos
> Move dcos-log configs out of the middle of mesos-slave-common.

- packages/navstar/buildinfo.json
- packages/navstar/extra/dcos-navstar.service
Fixes the issue of high memory usage by navstar due to file fd leak in ip_vs_conn module.
- [DCOS-14438](https://jira.mesosphere.com/browse/DCOS-14438) Investigate high memory usage of Navstar
https://github.com/dcos/minuteman/pull/91
https://github.com/mesosphere/ip_vs_conn/pull/15
https://github.com/dcos/navstar/pull/54
___ …
> upgrade navstar

- test_util/aws.py
- test_util/test_upgrade_vpc.py
Since Upgrade Integration Tests are inherited and used in Enterprise tests too, it will be good to know the stacks that were launched for enterprise vs the cloudformation stacks that were launched for open.
- https://jira.mesosphere.com/browse/DCOS-13979
> Provide an Ability to give AWS Stack name prefix.

- gen/internals.py
- gen/template.py
Fix the class definition statements used in code.
Stumbled upon these while reviewing gen/ code.
-  No Issue.
- [x ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
- [ x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)
___
> Fix style: python class definition statements.

- packages/logrotate/buildinfo.json
fedorahosted.org was retired on March 1st, 2017.
> Fix logrotate URL and sha1

- pkgpanda/docs/http-swagger.yaml
Add tags to pkgpanda swagger. This makes the endpoints show as grouped in Swagger UI.
> Add tags to pkgpanda swagger

- test_util/test_upgrade_vpc.py
Muted tests still show up as a failure. 
DCOS-14580
https://jira.mesosphere.com/browse/DCOS-14580
___
It is best to proactively ask for 2 reviews by @mentioning the candidate …
> Check CI flags in upgrade tests

- packages/dcos-integration-test/extra/test_composition.py
went unnoticed because logging exceptions wont interrupt
the main thread so you actually have to view the logs to notice
> Fix logging statements

- packages/mesos-dns/buildinfo.json
The DNS library that is used in mesos-dns has a bug where certain record types are being compressed when they should not be. This has been fixed in that library and this PR updates mesos-dns to a version that includes the fix. 
- [DCOS-13590](https://jira.mesosphere.com/browse/DCOS-13590) mesos-dns compresses SRV records
___
> packages/mesos-dns: bump to bf08ab7

- dcos_installer/action_lib.py
This causes `dcos_generate_config.sh --install-prereqs` to install Docker 1.13, and not break existing Docker 1.13 installs. This also matches the documentation at https://github.com/dcos/dcos-docs/blob/master/1.9/administration/installing/custom/system-requirements/install-docker-centos.md.
- [DCOS_OSS-743](https://jira.mesosphere.com/browse/DCOS_OSS-743) `--install-prereqs` breaks Docker 1.13 on CentOS 7.3
> Install Docker 1.13 with --install-prereqs

- cloud_images/centos7/install_prereqs.sh
Several Frameworks rely on the local FQDN being present in /etc/hosts. This is currently not the case in CentOS 7 on EC2. This PR adds a script that, if necessary, updates /etc/hosts with metadata retrieved from the AWS API upon boot.
We generally recommend for frameworks not to rely on working DNS resolution. However according to Julien Eid Zeppelin, Elasticsearch, Kafka and Chronos do.
- [DCOS-14302](https://jira.mesosphere.com/browse/DCOS-14302) Chronos requires the hostname inside /etc/hosts.
- [OPS-578](https://jira.mesosphere.com/browse/OPS-578) DC/OS CentOS 7 AMI has broken hostname config.
> Add script that fixes /etc/hosts in CentOS 7 on EC2 upon boot

- packages/dcos-integration-test/extra/test_applications.py
- packages/octarine/buildinfo.json
@mellenburg discovered that the octarine tests were muted. Upon fixing the test code itself and turning them back on, we discovered that they are now failing due to a bug in octarine. This fixes octarine, the existing octarine tests, and expands the test coverage.
- [DCOS_OSS-780](https://jira.mesosphere.com/browse/DCOS_OSS-780) octarine's history of why it was broken.
___ …
> Fix octarine, tests, and increase coverage

- gen/calc.py
- packages/dcos-integration-test/extra/test_mesos.py
This change enables the pid isolator for all containers launched by the UCR.
- [DCOS_OSS-790](https://jira.mesosphere.com/browse/DCOS_OSS-790) Always enable the pid isolator for the UCR in Mesos.
> Enable PID namespace isolator in mesos for the UCR.

- dcos_installer/async_server.py
Fix a bug where logs would be unavailable to download from installer UI.
- [DCOS-14750](https://jira.mesosphere.com/browse/DCOS-14750)
___ …
> dcos_installer: fix logs download

- gen/azure/templates/acs.json
- Quite often templates will fail to deploy because a resource that is required by zero-th master NIC is not available. That is because the current master NIC resource template only waits for the 2200+ indexed SSH port rules to be established. Rather, all of them should wait for the rules that are consistently named regardless of master count
- Also hard codes the rule names that are not indexed across the masters given that there can only be one anyway.
- Azure PR checks fail with errors like this: https://teamcity.mesosphere.io/viewLog.html?buildId=602849&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_DcosOssAzureIntegrati_2&tab=buildLog#_focus=435 …
> Fill out dependencies in Azure deployment

- packages/mesos-dns/buildinfo.json
When using the mesos http rest api to query service information, if the client includes an Accept header of `application/json`, the request is rejected with a `406 Not-Acceptable` error.
- [DCOS_OSS-611](https://jira.mesosphere.com/browse/DCOS_OSS-611) Mesos DNS HTTP API returns 406 Not Acceptable for valid requests.
___
> mesos-dns: Allow application/json Accept header

- packages/adminrouter/docker/adminrouter-upstreams.conf
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/marathon.py
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/mesos.py
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/open/iam.py
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/recording.py
This PR:
* refactors the way endpoints are reset in order to keep things DRY
* makes IAM `/foo/bar` test-path more concise 
* renames Bouncer to IAM in AR configuration
- [DCOS-14238](https://jira.mesosphere.com/browse/DCOS-14238) Admin Router: Create a single way to reset endpoint configuration without code duplication
- [DCOS-14585](https://jira.mesosphere.com/browse/DCOS-14585) Admin Router: Add reflecting path to Recording endpoints
- [DCOS-14836](https://jira.mesosphere.com/browse/DCOS-DCOS-14836) Admin Router: Standardize on IAM/get rid of `bouncer` term in AR configuration files
EE counterpart: https://github.com/mesosphere/dcos-enterprise/pull/743
> Admin Router: Test harness improvements

- gen/azure/cloud-config.yaml
Bumps Docker to 1.13.1 on Azure
Also reverts `LimitNOFILE` #1181 for the Docker execstart unit file as the Docker package already ships with a higher limit (1M) than the one we set (16k).
> Bump Azure Docker to 1.13.1

- gen/azure/templates/acs.json
- gen/build_deploy/azure.py
- test_util/test_azure.py
Currently, the acs template does not provide the user with a route to the master for DC/OS UI usage. This was due to security requirements and previous issues with oauth. Now that we can oauth in the acs templates without issue, this patch will add routes for http/https when oauth is *available* and then will only add extra network security rules when oauthEnabled=true at deploy time.
Thus, with this PR, when someone deploys a oauthEnabled=false cluster, the traffic will not be routed to the master, but it can easily be turned on by opening the Network Security Group rule. Additionally, if a downstream DC/OS variant is built and if it uses `custom_auth`  the routes will be enabled.
> Add HTTP routing to master for Azure

- cloud_images/centos7/dcos_vol_setup.sh
This turns on an XFS filesystem function where the inode type is stored in the directory structure. This is vital to the use of Overlay and a bug it wasn't there before.
Without it the Filesystem in containers can corrupt.
This setting is default beginning with EL 7.3.
- [DCOS-14872](https://jira.mesosphere.com/browse/DCOS-14872) Filesystem corruption in dcos-ui container.
> AMI: XFS - store inode type in directory structure by default

- packages/dcos-integration-test/extra/resiliency/test_aws_cf.py
- packages/dcos-launch/extra/launch/aws.py
- setup.py
- test_util/aws.py
- test_util/cluster.py
- test_util/templates/vpc-cluster-template.json
- test_util/templates/vpc-ebs-only-cluster-template.json
- test_util/test_aws_vpc.py
- test_util/test_upgrade_vpc.py
These templates are currently pulled from a magic bucket on S3. There is no reason why these should not just live in the repo where they can be updated in sync with DC/OS.
Additionally, the arbitrary names in the template are switched from CentOS to Bare as the intention of this template is to provide homogenous AMIs without DC/OS for use with the onprem installer.
https://jira.mesosphere.com/browse/DCOS-11534
> Add AWS bare cluster template

- test_util/marathon.py
- test_util/test_upgrade_vpc.py
Although the necessary VIP should have been ensured to exist
by polling marathon deployments for the app to be healthy (which
requires the VIP to be established), the viptalk app still fails
due to inability to connect to the VIP. This is a relatively minor
error if the VIP eventually works within the app deployment timeout.
Networking latency relating to app deployment should not cause
upgrade tests to fail out.
https://jira.mesosphere.com/browse/DCOS-14660
> Ignore task failures for viplisten in upgrade test

- test_util/helpers.py
- test_util/marathon.py
Modifies the Marathon API client in test_util to ignore Connection and Timeout errors
https://jira.mesosphere.com/browse/DCOS-14969
> Add ConnectionError retrying Mixin

- packages/dcos-integration-test/extra/test_ucr.py
This patch included new DC/OS UCR integration test for app and pods:
1) Tested image default entrypoint.
2) Tested scratch image support.
3) Tested image with whiteout files.
4) Tested image by digest.
- [CORE-869](https://jira.mesosphere.com/browse/CORE-869) Add DC/OS integration tests for UCR.
___ …
> Added DC/OS integration tests for UCR.

- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-integration-test/extra/test_endpoints.py
- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_misc.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_rexray.py
- packages/dcos-integration-test/extra/test_service_discovery.py
- test_util/run-all
- test_util/test_azure.py
Right now, people need to declare `-m 'not ccm'` when running tests that are outside of AWS. This is wrong for two reasons:
- we shouldnt assume that we are in an AWS environment
- we shouldnt have anything with the label "ccm" as it does not really add any description other than it might be involved with CI
This PR also cleans up the expanded config helper by consolidating it across the codebase
> Only run rexray tests when config shows aws env

- packages/dcos-integration-test/extra/test_applications.py
- test_util/marathon.py
This test is failing due to simple timeouts on an extremely regular basis. The two minute deploy timeout for apps is not a hard limit, but rather an optimization used because few apps ever succeeded after 120 seconds of waiting. We currently have no such data for pods and as such should bump this timeout
https://jira.mesosphere.com/browse/DCOS_OSS-912
> Deflake pods test

- setup.py
Builds have been broken for a while because pip's default azure-common lib moved to 1.1.5. E.G.:
https://teamcity.mesosphere.io/viewLog.html?buildId=616254&tab=buildResultsDiv&buildTypeId=DcosIo_Dcos_Master
All builds broken
> Pin azure common 1.1.4

- docs/admin-ports.md
Not sure if these are missing ports or weren't documented because they don't need to be exposed or aren't actually used...
This list, dcos.io, and docs.mesosphere.com all say different things. So it's hard to tell which is correct.
2888 & 3888 are used here:
https://github.com/dcos/dcos/blob/master/packages/exhibitor/extra/start_exhibitor.py
Feel free to correct me...
> Document missing exhibitor ports

- gen/calc.py
Previously, the calculate_ip_detect_public_contents() function would
throw away the value of calculate_ip_detect_contents() in the case where
ip_detect_public_filename is passed in. Now it doesn't.
- [DCOS_OSS-847](https://jira.mesosphere.com/browse/DCOS_OSS-847) Cannot customize ip_detect_public_filename in config.yaml as expected.
> Fixed bug in `calculate_ip_detect_public_contents()`.

- packages/dcos-integration-test/extra/test_composition.py
- packages/pkgpanda-api/build
- packages/pkgpanda-api/extra/dcos-pkgpanda-api.service
- packages/pkgpanda-api/extra/dcos-pkgpanda-api.socket
- packages/pkgpanda-api/extra/pkgpanda-api.sh
The `dcos-pkgpanda-api` service runs as a gunicorn web server. This service listens on a unix socket `/run/dcos/pkgpanda-api.sock`. This socket used to be managed by systemd as the `dcos-pkgpanda-api.socket` unit. However, gunicorn removes the socket file when it exits and creates it on start if it doesn't already exist. In short, it is not intended for use with systemd managed sockets.
This PR removes the systemd socket unit and relies on gunicorn's command-line flags to correctly set the permissions and ownership of its socket file.
This fixes an issue where upgrading a master from 1.8.8 to 1.9.0 would sometimes require a manual `systemctl restart dcos-pkgpanda-api.socket` as a final step so the `dcos-pkgpanda-api` service could start.
- …
> pkgpanda-api: don't use systemd socket

- packages/dcos-launch/extra/conftest.py
- packages/dcos-launch/extra/launch/__init__.py
- packages/dcos-launch/extra/launch/aws.py
- packages/dcos-launch/extra/launch/azure.py
- packages/dcos-launch/extra/launch/cli.py
- packages/dcos-launch/extra/test_aws.py
When dcos-launch was first implemented there was some difference in the internal data structures 'config' and 'info' and as such, only the create function took the config, which created the info, and all other functions took the info. However, the info has simply become a superset of the config, so these remain identical. Additionally, all of these values can just be set at instantiation for simplification and to avoid needless argument passing, e.g. `get_launcher(info).wait(info)`
marginal refactor
> Simplify parameter input in dcos-launch

- packages/dcos-integration-test/extra/test_3dt.py
Azure tests have failed because check-time seems to reach consistency a little slower on the default azure OS image (ubuntu). Specifically, I have seen this test fail and then checked logs to see that check-time started working only seconds later
https://jira.mesosphere.com/browse/DCOS-15228
https://jira.mesosphere.com/browse/DCOS_OSS-987
https://jira.mesosphere.com/browse/DCOS_OSS-988
> Increase 3dt test latency to two minutes

- test_util/aws.py
- test_util/test_aws_cf.py
- test_util/test_aws_vpc.py
- test_util/test_upgrade_vpc.py
Rate limit has been cropping up in CI so this polling
limit can be reduced to increase stability with very minimal
impact. Also decouples fixed waiting code from polling code
https://jira.mesosphere.com/browse/DCOS_OSS-933
https://jira.mesosphere.com/browse/DCOS_OSS-945
> Increase AWS polling interval

- test_util/helpers.py
- test_util/marathon.py
Our testing logs are becoming so large that it takes considerable amount of time to download the logs into the browser, not to mention how cumbersome they become to scroll through. Most of this information is overly verbose and should be accessed on demand by changing the logging level.
This PR does the following:
- Reduce a few loggers from info to debug to reduce clutter
- Increase polling interval to cut down on repeated, uninformative information
> Reduce dcos-integration-test logging

- test_util/dcos_api_session.py
Changes the test harness to not fail if more agents than expected appear in the history service agent
list. This is expected to happen if a agent is replaced as in the case of the aws resiliency test
https://jira.mesosphere.com/browse/QUALITY-1424
> Allow extra nodes to be reported in test harness

- test_util/dcos_api_session.py
Sporadic RemoteDisconnected / ConnectionError test failures do not illuminate any wider issues not happen at a high enough frequency to warrant dedicated investigation. This change will add a retrying mixin for this specific failure case to the DcosApiSession object used in the integration tests. This is the same treatment applied to marathon polling to reduce test flakiness
https://jira.mesosphere.com/browse/QUALITY-1426
> Add ConnectionError Retrying Mixin to test harness

- test_util/aws.py
- test_util/templates/vpc-cluster-template.json
- test_util/templates/vpc-ebs-only-cluster-template.json
- All of the other templates use the term KeyName
- KeyName is AWS native and more intuitive
- dcos-launch has a utility that injects KeyName into template parameters after generating a key, so this change will enable seamless integration
https://jira.mesosphere.com/browse/DCOS-13299
> Change KeyPair->KeyName for consistency

- packages/3dt/buildinfo.json
Journald uses structured log format. When 3dt tries to read logs from journald for a specific systemd unit, it will only include logs which have `UNIT` field set to a given systemd unit name. We also want logs that have another field `_SYSTEMD_UNIT` set to a gived systemd unit name.
This change makes 3dt to read log entries that have either UNIT or _SYSTEMD_UNIT field set to the required unit name.
- [DCOS_OSS-987](https://jira.mesosphere.com/browse/DCOS_OSS-987)
the test is added to `dcos-log` since 3dt reuses the code.
- [dcos-log](https://github.com/dcos/dcos-log/pull/39)
- [jenkins#113](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-log-pulls/113/) …
> bump 3dt sha

- packages/adminrouter/extra/src/common/auth/open.lua
The DC/OS `oauth_enabled` configuration parameter value determines whether Admin Router's authentication module is activated or not. This patch ensures that the auth module is deactivated only if a literal `'false'` (YAML string type) is provided and that it is enabled in _all_ other cases.
As of now, the auth module is enabled only if a literal `'true'` (YAML string type) is provided and it is disabled in all other cases. This implies an unnecessarily large risk for unintentionally deactivating the authentication module and therefore is a security risk.
Kudos to @lordnynex for the report via Slack and via [DCOS_OSS-1003](https://jira.mesosphere.com/browse/DCOS_OSS-1003).
- [DCOS_OSS-1003](https://jira.mesosphere.com/browse/DCOS_OSS-1003) `oauth_enabled` cfg param: only the literal …
> [DCOS_OSS-1003] Admin Router auth module: require a literal 'false' for disabling the module

- packages/openssl/build
Disable support for the insecure RC4 stream cipher (cf. RFC [7465](https://tools.ietf.org/html/rfc7465)). Assume AMD64 architecture and enable the usage of machine code optimized for certain curves.
For more background information see https://jira.mesosphere.com/browse/DCOS_OSS-1010 and https://jira.mesosphere.com/browse/DCOS_OSS-1009.
- [DCOS_OSS-1010](https://jira.mesosphere.com/browse/DCOS_OSS-1010) OpenSSL: build with no-rc4 option (also set no-ssl2 and no-ssl3)
- [DCOS_OSS-1009](https://jira.mesosphere.com/browse/DCOS_OSS-1009) OpenSSL: build with enable-ec_nistp_64_gcc_128 option
> openssl: add no-rc4 no-ssl2(3) enable-ec_nistp_64_gcc_128 build opts

- packages/dcos-signal/buildinfo.json
When dcos-signal is invoked it will report a list of installed packages. The list comes from cosmos. Current implementation provides unreadable output
```level=warning msg="REPORT:\n&{Packages:[{AppID:/jenkins} {AppID:/kafka}]}"```
This change makes the output easier to read and includes the version of the package.
```Installed cosmos packages: flink 3.0, hello-world 3.0, jenkins 3.0```
- [DCOS-15379](https://jira.mesosphere.com/browse/DCOS-15379)
The unittest has been added to dcos-signal.
___
**What is the review process and …
> bump dcos-signal sha

- packages/adminrouter/extra/dcos-adminrouter.service
- packages/cosmos/buildinfo.json
- packages/dcos-integration-test/extra/python_test_server.py
- packages/mesos/buildinfo.json
- test_util/cluster_api.py
Train 159 targeting 1.8.9 branch
#1494 Backporting https://jira.mesosphere.com/browse/DCOS-10327 to 1.8.9
#1458 Update cosmos to version 0.2.1
#1456 Backporting the fix for DCOS_OSS-683 to 1.8
#1445 Bumped Mesos to include fixes for leakage of sensitive data - Mesos 1.0.4
> Train 159 (targeting 1.8.9)

- packages/mesos/buildinfo.json
Generally fixes sensitive data leakage to task sandbox. 
Updates Mesos package to be based on Apache/Mesos 1.0.4 (WIP). 
- [DCOS-11709](https://jira.mesosphere.com/browse/DCOS-11709) Secrets printed directly to the logs.
-  [MESOS-2537] - AC_ARG_ENABLED checks are broken
-  [MESOS-6606] - Reject optimized builds with libcxx before 3.9
-  [MESOS-7008] - Quota not recovered from registry in empty cluster.
-  [MESOS-7265] - Containerizer startup may cause sensitive data to leak into sandbox logs.
-  [MESOS-7366] - Agent sandbox gc could accidentally delete the entire persistent volume content.
-  [MESOS-7383] - Docker executor logs possibly sensitive parameters.
-  [MESOS-7422] - Docker containerizer should not leak possibly sensitive data to agent log.
If you are changing components or …
> Bumped Mesos to include fixes for leakage of sensitive data - Mesos 1.0.4

- packages/adminrouter/extra/dcos-adminrouter.service
In newer versions of CoreOS, libcurl shipped with DC/OS is incompatible(old) with system curl, leading to `curl: (48) An unknown option was passed in to libcurl` error. This has laready been fixed in 1.9 but 1.8.8 had already been released before the fix so backporting the fix to 1.8.9
- [DCOS_OSS-683](https://jira.dcos.io/browse/DCOS_OSS-683) Latest Stable version of CoreOS break dcos-adminrouter
- [X ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
- [ X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)
If you are changing components or packages in DC/OS (e.g. …
> Backporting the fix for DCOS_OSS-683 to 1.8

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_mesos.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_service_discovery.py
- test_util/marathon.py
- test_util/test_upgrade_vpc.py
Testing all network VIP configuration permutations at once is not a viable test. When it fails, it is near impossible to de-tangle what is broken and the logs are returned in a totally unorganized manner. This PR will:
- consolidate the code for generating consistent test server applications to make the tests calling it far more readable
- serialize the test so that pytest can report results in an organized manner, thereby allowing others to debug from CI or to simply just focus on problem areas (rather than python threading issues). Unfortunately, this serialization will add ~30 minutes to tests
https://jira.mesosphere.com/browse/DCOS-14950
https://jira.mesosphere.com/browse/DCOS_OSS-909
https://jira.mesosphere.com/browse/DCOS_OSS-910
> Serialize test_vip

- packages/dcos-metrics/buildinfo.json
This PR addresses https://jira.mesosphere.com/browse/DCOS_OSS-925.
Once it gets merged in I think the idea will be to tag dcos-metrics
and then change the ref/origin in buildinfo.json.
This change brings in a bugfix in dcos-metrics.  The bug is described in
https://jira.mesosphere.com/browse/DCOS_OSS-925.
Effectively it avoids `NaN` and `encoding/json` incompatibilities by special
casing the `NaN` value in an avro record.
- [DCOS_OSS-925](https://jira.mesosphere.com/browse/DCOS_OSS-925) Metrics app endpoint can produce 'null' as a value for datapoints.
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY …
> Integrate DCOS_OSS-925 fix in dcos-metrics.

- packages/adminrouter/build
- packages/adminrouter/buildinfo.json
- packages/adminrouter/extra/adminrouter.sh
- packages/adminrouter/extra/dcos-adminrouter-agent-reload.service
- packages/adminrouter/extra/dcos-adminrouter-agent.service
- packages/adminrouter/extra/dcos-adminrouter-reload.service
- packages/adminrouter/extra/dcos-adminrouter.service
- packages/dcos-history/extra/history/server.py
This is just a backport of https://github.com/dcos/dcos/pull/1521 into 1.8 Please check https://github.com/dcos/dcos/pull/1521 description for details.
As 1.8 did not have ANY AR testing infra, it's omitted here.
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/891
> Admin Router: Make AR route to history-service backend, conditionally

- packages/3dt/buildinfo.json
- packages/dcos-integration-test/extra/test_3dt.py
Backporting #1219 in attempt to get some more debugging information into diagnostic bundles.
Corresponding enterprise PR https://github.com/mesosphere/dcos-enterprise/pull/874
The following JIRA is associated with #1219 not really relevant to this PR
- [DCOS-13706](https://jira.mesosphere.com/browse/DCOS-13706) Add Zookeeper.out to DC/OS Diagnostic Bundle
___
@darkonie and @adam-mesos  please review
> Backport PR #1219 to 1.8.9

- packages/metronome/buildinfo.json
Security fix for Cross-Site Scripting Vulnerabilities
- [DCOS-14866](https://jira.mesosphere.com/browse/DCOS-14866) Cross-Site Scripting Vulnerabilities
___
It is best to …
> [DCOS 1.9.1] Use metronome 0.2.3

- packages/cosmos/build
See https://bugs.openjdk.java.net/browse/JDK-8168839
Fixes [DCOS-15542](https://jira.mesosphere.com/browse/DCOS-15542). In release 8u111 of the JDK, basic auth was disabled for HTTPS tunneling. Since DC/OS 1.9 shipped with a more recent JDK, it prevented some customers from accessing the package Universe from their cluster. This change removes basic auth from the disabled list.
- [DCOS-15542](https://jira.mesosphere.com/browse/DCOS-15542). Cosmos fails any request that queries Universe through a proxy with authentication
___ …
> Enable Cosmos HTTPS tunneling through a proxy secured by basic auth (for 1.9.1)

- gen/dcos-config.yaml
- packages/dcos-cni/build
- packages/dcos-cni/buildinfo.json
- packages/navstar/buildinfo.json
- pkgpanda/docker/dcos-builder/Dockerfile
This PR adds DC/OS CNI plugins for minuteman and spartan. Currently minuteman and spartan cannot work with any CNI network that completely isolates container's traffic from the host network (except for agent/executor communication). The DC/OS CNI plugins plumb routes, interfaces and IPVS entries into the container's netns that allow the container to use spartan and minuteman for service discovery and load balancing respectively.
- [DCOS_OSS-854](https://jira.mesosphere.com/browse/DCOS_OSS-854) 
We have unit tests in the `github.com/dcos/dcos-cni` repo. The unit-tests test the basic semantics of the `dcos-l4lb` CNI plugins. Writing integration tests for the plugins is a bit involved. It requires an installation of a CNI network that emulates the isolation semantics of CNI networks that …
> Added the DC/OS CNI plugins.

- gen/dcos-config.yaml
Given a logrotate config with neither a time-based rotation criteria, nor a `size` option, logrotate will default to rotating files once they hit 1 MB.  The `maxsize` option apparently only takes effect if there is a time-based rotation option (i.e. daily or weekly).
Given the current logrotate config, log retention is 256 times smaller than intended.
- None at the moment.
- N/A
___
> Fixed log rotation for Mesos master/agent logs.

- gen/calc.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/api_session_fixture.py
- packages/dcos-integration-test/extra/test_endpoints.py
- test_util/dcos_api_session.py
This adds an optional config param `exhibitor_admin_password`. If provided, requests to Exhibitor must be authenticated with the userid `admin` and the password.
- [DCOS_OSS-1064](https://jira.mesosphere.com/browse/DCOS_OSS-1064) Add config param for Exhibitor basic HTTP auth 
> Add HTTP basic auth for Exhibitor

- packages/cosmos/build
See https://bugs.openjdk.java.net/browse/JDK-8168839
Fixes [DCOS-15542](https://jira.mesosphere.com/browse/DCOS-15542). In release 8u111 of the JDK, basic auth was disabled for HTTPS tunneling. Since DC/OS 1.9 shipped with a more recent JDK, it prevented some customers from accessing the package Universe from their cluster. This change removes basic auth from the disabled list.
- [DCOS-15542](https://jira.mesosphere.com/browse/DCOS-15542). Cosmos fails any request that queries Universe through a proxy with authentication
___ …
> Enable Cosmos HTTPS tunneling through a proxy secured by basic auth (for master)

- packages/dcos-signal/buildinfo.json
send package version of installed package instead of packaging version to segment. We updated signal to parse /package/list to get out packaging version in https://github.com/dcos/dcos-signal/commit/67ce8b98c0d7cbc58cf921951f3d52ef0286ef5b, but turns out we actually wanted package version. this updates to package version. 
- [DCOS_OSS-1102](https://jira.dcos.io/browse/DCOS_OSS-1102) Foo the Bar so it stops Bazzing.
___
> dcos-signal: bugfix update

- ssh/ssher.py
This gets rid of this annoying error message: ```Warning: Permanently added '52.59.62.9' (ECDSA) to the list of known hosts.```
This is worthless because we set the known hosts list to /dev/null
area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).
> Remove useless known hosts warnings

- packages/mesos/README.md
- packages/mesos/buildinfo.json
This PR bumps the Mesos package to include one additional cherry-pick which fixes an issue in the executor driver.
- [DCOS-15809](https://jira.mesosphere.com/browse/DCOS-15809) Backport the fix for MESOS-7057 to DCOS 1.8.9
- [MESOS-7057](https://issues.apache.org/jira/browse/MESOS-7057) Consider using the relink functionality of libprocess in the executor driver.
> Bumped Mesos to include a fix for the executor driver.

- packages/dcos-launch/build
- packages/dcos-launch/buildinfo.json
- packages/dcos-launch/extra/dcos-launch.spec
- packages/dcos-launch/extra/launch/aws.py
- packages/dcos-launch/extra/launch/azure.py
- packages/dcos-launch/extra/launch/config.py
- packages/dcos-launch/extra/launch/ip-detect/aws.sh
- packages/dcos-launch/extra/launch/ip-detect/aws_public.sh
- packages/dcos-launch/extra/launch/onprem.py
- packages/dcos-launch/extra/launch/util.py
- packages/dcos-launch/extra/setup.py
- packages/dcos-launch/extra/test_aws.py
- packages/dcos-launch/extra/test_config.py
- packages/dcos-launch/extra/test_onprem.py
gen required many hacks to integrate in at all. The only reason it was used was the convenience of the shared code-base. However, given that the shared code-base has now crippled dcos-launch with its custom-SSL, dcos-launch must be split off.
gen and the rest of the "DC/OS Image" library is a long ways away from being converted into a legitimately importable library, so it must be removed to make the dcos-launch packaging feasible.
https://jira.mesosphere.com/browse/DCOS_OSS-1060
https://jira.mesosphere.com/browse/DCOS_OSS-1041
https://jira.mesosphere.com/browse/DCOS_OSS-1084
> Remove gen from dcos launch

- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_networking.py
apps usually take less than 120 seconds to deploy
and achieve a healthy status, but in test_vip there
is no blocking on the previous test cleaning up state.
This speeds up execution to allow marathon to optimize
the deployments, but also adds a small increase to the
time any given app spends deploying
Timeouts occurring on random test cases such as https://teamcity.mesosphere.io/viewLog.html?buildId=653598&
> Increase timeout for apps to be healthy

- test_util/cluster.py
Many CI-driven integration tests time-out due to this overly conservative timeout, so increase the period to 300 seconds (5 minutes) from 120 seconds
https://jira.mesosphere.com/browse/DCOS-15839
> Increase wait time for SSH capability

- test_util/dcos_api_session.py
#1508 and #1528 conflicted but this case silently slipped by because it was a new usage of the variable being removed. This was not caught during testing as the code was not exercised until a specific setting was enabled in CI
- https://jira.mesosphere.com/browse/DCOS_OSS-1125
> Fix broken reference to public_master

- gen/build_deploy/bash/dcos_generate_config.sh.in
My goal was to make DC/OS Docker runnable from my Mac as a development convenience.
This - `sed` syntax which does not work on macOS - was the one blocker in DC/OS.
https://jira.mesosphere.com/browse/DCOS-15645 - Run DC/OS Docker on macOS without Vagrant
I originally wrote a way of overwriting `sed` with GNU sed on macOS (see https://github.com/dcos/dcos-docker/pull/36/files#diff-04c6e90faac2675aa89e2176d2eec7d8R33). This would require no changes to DC/OS but may have unintended consequences for the user.
I was asked by @karlkfi in review to create a cross-platform compatible change and to add to DC/OS a test which runs on a macOS builder. The suggested test would potentially spin up a DC/OS Docker cluster on macOS. My preference is to not do that because:
* That adds a support burden if …
> [DCOS-15645] Change `sed` in installer to not be GNU specific

- docs/admin-ports.md
- gen/calc.py
- gen/dcos-config.yaml
- packages/dvdcli/build
- packages/dvdcli/buildinfo.json
- packages/rexray/build
- packages/rexray/buildinfo.json
- packages/rexray/extra/dcos-rexray.service
Upgrades rex-ray to v0.9.0. Also upgrades `dvdcli` to `v0.2.0`.
This rebases https://github.com/dcos/dcos/pull/1196 against master.
- [DCOS-13137](https://jira.mesosphere.com/browse/DCOS-13137) RexRay (libstorage) on DC/OS to be upgraded to latest in order to support Ceph/NBD driver
___
> upgrade rex-ray to v0.9.0

- packages/dcos-checks/build
- packages/dcos-checks/buildinfo.json
- packages/dcos-integration-test/extra/test_dcos_checks.py
[dcos-enterprise PR ](https://github.com/mesosphere/dcos-enterprise/pull/944)
Add a new pkgpanda package `dcos-checks`. The `dcos-checks` provides node and cluster checks implementation.
- [DCOS-14989](https://jira.mesosphere.com/browse/DCOS-14989) Create `dcos-checks` package
___ …
> Add dcos checks

- packages/navstar/buildinfo.json
- packages/navstar/extra/setup_iptables.sh
This patch avoids adding same iptable rule multiple times
- [DCOS_OSS-1045](https://jira.mesosphere.com/browse/DCOS_OSS-1045) Same ip table rule is added multiple times
- [DCOS_OSS-1040](https://jira.mesosphere.com/browse/DCOS_OSS-1040) Same ip rule is added multiple times
https://github.com/dcos/navstar/pull/70
___
* …
> fixes duplicate iptable rule

- gen/calc.py
- gen/dcos-services.yaml
- packages/dcos-integration-test/extra/test_misc.py
This adds a test which verifies that the DC/OS profile script is symlinked from the correct source file.
- [DCOS_OSS-947](https://jira.mesosphere.com/browse/DCOS_OSS-947) On 1.8->1.9 upgrade, /etc/profile.d/dcos.sh symlink is not updated.
> Add test verifying profile symlink

- packages/navstar/buildinfo.json
- packages/navstar/extra/setup_iptables.sh
This patch fixes two issues:
1. upgrade issue from 1.8.x to 1.9.x with minuteman
2. Tcp metrics
- [DCOS_OSS-871](https://jira.mesosphere.com/browse/DCOS_OSS-871) upgrade failure
- [DCOS-15036](https://jira.mesosphere.com/browse/DCOS-15036) Navstar unhealthy after 1.8.8 to 1.9 upgrade
- [DCOS-14818](https://jira.mesosphere.com/browse/DCOS-14818) tcp metrics
- [DCOS_OSS-1040](https://jira.mesosphere.com/browse/DCOS_OSS-1040) same ip rule added multiple times on navstar restart
- [DCOS_OSS-992](https://jira.mesosphere.com/browse/DCOS_OSS-992) docker 1.12+ breaks dcos overlay network
- [DCOS-15576](https://jira.mesosphere.com/browse/DCOS-15576) More Navstar failures after 1.8.8 to 1.9.0 upgrade …
> Bump networking components for 1.9.1

- dcos_installer/exhibitor_migrate.py
- dcos_installer/upgrade.py
- gen/calc.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/api_session_fixture.py
- packages/dcos-integration-test/extra/test_endpoints.py
- test_util/dcos_api_session.py
This teaches the upgrade script to authenticate Exhibitor requests if Exhibitor requires it.
This is a 1.9 backport of #1541.
- [DCOS-15495](https://jira.mesosphere.com/browse/DCOS-15495) DC/OS upgrade script does not support exhibitor HTTP auth
> (1.9) Authenticate requests to Exhibitor during upgrade

- packages/adminrouter/extra/src/nginx.master.conf
(**DCOS-13976**) Adds X-Frame-Options to prevent Clickjacking attack through iframe.
To test this create a index.html page and use iframe markup pointing to a cluster that contain this changes. You should see this in the console `Refused to display 'https://52.41.194.202/' in a frame because it set 'X-Frame-Options' to 'deny'.`
https://jira.mesosphere.com/browse/DCOS-13976 - Application is vulnerable to Clickjacking attack
> feat(DCOS-13976): Disable opening the UI in iframe

- packages/docker-gc/extra/dcos-docker-gc.service
When enable_docker_gc is set to false, the file docker_gc_enabled does not exist, which is supposed to stop the unit file from starting. The ConditionPathExists was in the wrong place, however, and needs to be in the Unit section instead of Service. 
Tested manually on my cluster. How does 3dt mark Condition failed systemd units as in the UI? On my cluster, docker-gc still shows as healthy even though it can't be executing. Could be very confusing if people are expecting docker-gc to be disabled, but still see it show up in the DC/OS UI.
https://jira.mesosphere.com/browse/DCOS_OSS-999
> Set ConditionalPathExists in correct area so docker-gc-enabled works.

- gen/build_deploy/bash/dcos_generate_config.sh.in
Currently if `dcos_generate_config.sh` is truncated or otherwise corrupted and run it'll extract a corrupted tarball that can't be loaded into Docker.
Then when `dcos_generate_config.sh` is redownloaded it'll fail to run as it'll find a tarball with matching name which causes it to not extract the image tarball and load it into Docker.
Resulting in:
```
Unable to find image 'mesosphere/dcos-genconf:0ce03387884523f026-58fd0833ce81b6244f' locally
Trying to pull repository docker.io/mesosphere/dcos-genconf ...
/usr/bin/docker-current: unauthorized: authentication required.
See '/usr/bin/docker-current run --help'.
```
This PR adds an additional check that, if a tarball of the same name already exists it confirms that the image was actually loaded into Docker. If not it removes the tarball …
> Fixed: Partial download of dcos_generate_config.sh results in unrecoverable error that requires manual intervention.

- packages/cosmos/build
See https://bugs.openjdk.java.net/browse/JDK-8168839
Addresses [DCOS_OSS-519](https://jira.mesosphere.com/browse/DCOS_OSS-519). In release 8u111 of the JDK, basic auth was disabled for HTTPS tunneling. Since DC/OS 1.8.7 shipped with a more recent JDK, it prevented some customers from accessing the package Universe from their cluster. This change removes basic auth from the disabled list.
Corresponding EE PR: https://github.com/mesosphere/dcos-enterprise/pull/950
- [DCOS_OSS-519](https://jira.mesosphere.com/browse/DCOS_OSS-519). Universe package listing (default one) fails to list packages behind corporate web proxy
- [DCOS-15542](https://jira.mesosphere.com/browse/DCOS-15542) Cosmos fails any request that queries Universe through a proxy with authentication …
> Enable Cosmos HTTPS tunneling through a proxy secured by basic auth (for 1.8.9)

- packages/marathon/buildinfo.json
- [MARATHON-7397](https://jira.mesosphere.com/browse/MARATHON-7397) Include USER networked docker containers in /v2/tasks text/plain output. If no host port is specified, specify address as `{containerIp}:{containerPort}`. If host port is specified, `{agentIp}:{hostPort}`
- [MARATHON-7397](https://jira.mesosphere.com/browse/MARATHON-7397) Foo the Bar so it stops Bazzing.
- Extensive unit tests were written, and extensive manual integration testing was performed.
> bump to Marathon 1.3.12

- packages/mesos/README.md
- packages/mesos/buildinfo.json
This PR updates the Mesos package to include backported fixes which enable retries of executor reconnect requests from the agent.
- [MESOS-7540](https://issues.apache.org/jira/browse/MESOS-7540) Add an agent flag for executor re-register timeout
- [MESOS-7569](https://issues.apache.org/jira/browse/MESOS-7569) Allow "old" executors with half-open connections to be preserved during agent upgrade / restart.
> Bumped Mesos package to include executor reconnect retries.

- packages/exhibitor/extra/start_exhibitor.py
Adds back `[myid:{}]` to `journald` messages output which was removed in one of the previous patches. This is a backport of patch that is going to the `master`.
- [DCOS-15317](https://jira.mesosphere.com/browse/DCOS-15317) ZooKeeper log: ensure that `myid` is in the log
> exhibitor: Add back  to journald log messages (1.9.1 backport)

- packages/mesos/buildinfo.json
Bumps Apache Mesos to 1.2.1-rc1 with the addition of
https://github.com/mesosphere/mesos/commit/d39453dd32a91ec21098e10c3ae445363a7bf7e8 
https://github.com/mesosphere/mesos/commit/db85099218ebc1e97bc54f730a2292c2b34a7597
https://github.com/mesosphere/mesos/commit/d562795d5fed1628e8bf56dede7ef2ea93b838c5
https://github.com/mesosphere/mesos/commit/f5ba5b06ebf80353991cf65e413cd3045ea52d22
https://github.com/mesosphere/mesos/commit/5189618e10ae8492c7d6f6f17d3e74b398fb3cba
https://github.com/mesosphere/mesos/commit/417be416d832225db67af0b96694a0ab13d95e81
> Bumped Apache Mesos to latest 1.2.1-rc1.

- dcos_installer/upgrade.py
- gen/calc.py
- gen/dcos-services.yaml
- packages/dcos-integration-test/extra/test_misc.py
This makes the 1.9 upgrade script recreate the symlink at `/etc/profile.d/dcos.sh` and point it to the correct source for 1.9.
- [DCOS_OSS-947](https://jira.mesosphere.com/browse/DCOS_OSS-947) On 1.8->1.9 upgrade, /etc/profile.d/dcos.sh symlink is not updated.
> (1.9) Fix profile symlink during upgrade

- gen/dcos-config.yaml
- packages/mesos-modules/buildinfo.json
This includes two cherry-picks:
- https://github.com/dcos/dcos/pull/1565 - A CHECK failure in a logger module when running tasks with a `:` in the TaskID or ExecutorID.
- https://github.com/dcos/dcos/pull/1499 - A logrotation config error, which leads to rotating files when they are 1 MB instead of 256 MB.
- [CORE-1062](https://jira.mesosphere.com/browse/CORE-1062) Chronos launching Docker container causes Mesos agent to crash
- [DCOS-15653](https://jira.mesosphere.com/browse/DCOS-15653) Log rotation happens 256 times more often than intended
> [1.9.1] Cherry-picks for logger modules crash + log rotation size.

- packages/dcos-metrics/buildinfo.json
This change brings dcos-metrics up to date, resolving the last known issues affecting the ability of the package to work with external metrics storage providers. 
Specifically, it improves error handling and avoids transmitting very long labels. 
- [Handle errors gracefully](https://github.com/dcos/dcos-metrics/pull/96/commits/7b84b5e01d3d1cdcb3a11c0c31390a27a40b3b70)
- [Drop long labels in mesos agent](https://github.com/dcos/dcos-metrics/pull/96/commits/cca85f336eee440c2468d4b4c9d1c3b246654188)
https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-metrics/job/public-dcos-metrics-pulls/374/
https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-metrics/job/public-dcos-metrics-pulls/374/cobertura/
- [DCOS-15224](https://jira.mesosphere.com/browse/DCOS-15224) Improve error …
> [1.9.1] Bump dcos-metrics for 1.9.1

- gen/calc.py
- packages/mesos/buildinfo.json
Updates Mesos to 4faca73e9608664a5fcf46cc95951c318a64861f. This change contains file-based secrets and image pull secrets. 
Also enables the volume/secret isolator.
https://jira.mesosphere.com/browse/DCOS-10236 File-Based Secrets
https://jira.mesosphere.com/browse/CORE-810 Image pull secrets
This PR relies upon Mesos test suite.
> Bump Mesos to 4faca73 and enable volume/secret isolator.

- gen/calc.py
- gen/dcos-config.yaml
This adds a default BRIDGE mode networking for UCR.
Supersedes #1481 
- [DCOS_OSS-954](https://jira.dcos.io/browse/DCOS_OSS-954) Add default bridge network for UCR.
___
It is …
> Added a default bridge for UCR.

- gen/dcos-config.yaml
- packages/marathon/build
- packages/marathon/buildinfo.json
- packages/metronome/build
- Pkgpanda doesn't let marathon and metronome share files, so make marathon package-private
- Add some docs and fix MARATHON_CMD => MARATHON_
- Set Hostname is set via the environment
We now publish more normalized packages that attempt to follow Linux Standard Base Guidelines and use sbt-native-packager to achieve this.
As a result of this and the many historic ways of passing options into marathon, we will only read `/etc/default/marathon` when starting up.
This file, like `/etc/sysconfig/marathon`, has all marathon command line options as "MARATHON_XXX=YYY" which will translate to `--xx=yyy`.
We no longer support /etc/marathon/conf which was a set of files that would get translated into command line arguments. In addition,
we no longer assume that if there is no zk/master argument …
> Use the new marathon packaging (testing with a snapshot build)

- gen/calc.py
- gen/dcos-config.yaml
- packages/mesos/README.md
- packages/mesos/buildinfo.json
- introduce a new config.yaml option `gpus_are_scarce` with default values `true`
- bump mesos to include `--filter-gpu-resources` master flag.
- [DCOS_OSS-876](https://jira.mesosphere.com/browse/DCOS_OSS-876)
- [CORE-1107](https://jira.mesosphere.com/browse/CORE-1107)
The PR does not include any integration test, since we do not have an infrastructure for integration tests with GPUs. @klueska has performed manual tests to make sure this change works as expected.
> add a new config.yaml option gpus_are_scarce

- packages/mesos/README.md
- packages/mesos/buildinfo.json
Updates Mesos to a branch based on 4faca73e9608664a5fcf46cc95951c318a64861f with 55e7ea5ed788acb0e4f810dd4575a5a4479520d1 cherry-picked. This version of Mesos contains support for the Mesos Master `--filter_gpu_resources` flag and a fix for MESOS-7546.
- [MESOS-7546](https://issues.apache.org/jira/browse/MESOS-7546) WAIT_NESTED_CONTAINER sometimes returns 404.
> Bump Mesos version to include fix for MESOS-7546.

- packages/adminrouter/extra/src/README.md
- packages/adminrouter/extra/src/docs/api/nginx.master.yaml
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/test-harness/modules/generic_test_code/common.py
- packages/adminrouter/extra/src/test-harness/modules/generic_test_code/generalised_tests.py
- packages/adminrouter/extra/src/test-harness/tests/test_generic.config.yml
- packages/dcos-integration-test/extra/test_endpoints.py
This PR:
* fixes `/marathon` endpoint redirect (see the discussion in the issue for more details)
* piggybacks removing some redundant information from README.md
* make `is_endpoint_redirecting_properly` test more flexible - now it is possible to verify the code of the redirect sent by the backend
- https://jira.mesosphere.com/browse/DCOS_OSS-1163 - "mycluster.com/marathon" routes to "mycluster.com/ui" => 404
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/1023
> Admin Router: /marathon endpoint fix

- packages/marathon/buildinfo.json
- [MARATHON-7411](https://jira.mesosphere.com/browse/MARATHON-7411) Include USER networked docker containers in /v2/tasks text/plain output. If no host port is specified, specify address as `{containerIp}:{containerPort}`. If host port is specified, `{agentIp}:{hostPort}`.
- [MARATHON-7396](https://jira.mesosphere.com/browse/MARATHON-7396) Marathon leader would become a zombie process in certain Zookeper failure scenarios.
- Marathon would not load authentication plugins in certain situations. This has been addressed.
- [MARATHON-7322](https://jira.mesosphere.com/browse/MARATHON-7322) /ping endpoint returns the correct content type
- [MARATHON-7320](https://jira.mesosphere.com/browse/MARATHON-7320) Fix MAX_PER constraint for attributes.
- Fix issue related to Marathon plugins and …
> bumping Marathon to 1.4.4

- packages/cosmos/build
- packages/cosmos/buildinfo.json
- packages/dcos-integration-test/extra/test_mesos.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/mesos-modules/buildinfo.json
Fixed CHECK failure in logger module due to Docker workaround.
https://github.com/dcos/dcos/pull/1565
Fixed bug in 'test_mesos.test_if_ucr_app_runs_in_new_pid_namespace'.
https://github.com/dcos/dcos/pull/1617
Disable NTLM proxy auth for cosmos
https://github.com/dcos/dcos/pull/1632
Increase timeout in test_vip
https://github.com/dcos/dcos/pull/1641
Update cosmos to latest version
https://github.com/dcos/dcos/pull/1646
> Master train 174

- packages/mesos-modules/buildinfo.json
This bumps the logger module to include a fix for a CHECK failure when a Docker task is started with a colon (`:`) in the ID.
- [CORE-1062](https://jira.mesosphere.com/browse/CORE-1062) Chronos launching Docker container causes Mesos agent to crash
- https://github.com/dcos/dcos/pull/1592
> Fixed CHECK failure in logger module due to Docker workaround.

- packages/dcos-integration-test/extra/test_mesos.py
Previously, there was a race between the `app_task` starting and it
writing its output to the `ps_output_file`. We now wait up to 10 seconds
for this file to appear before giving up and throwing an exception.
- [DCOS_OSS-862](https://jira.mesosphere.com/browse/DCOS_OSS-862) Vagrant integration test test_mesos.test_if_ucr_app_runs_in_new_pid_namespace is flaky.
___
> Fixed bug in 'test_mesos.test_if_ucr_app_runs_in_new_pid_namespace'.

- packages/dcos-integration-test/extra/test_networking.py
test_networking tests have been failing by timing out while waiting for apps to remain healthy. So far, this has not been indicative of any actual failure
https://jira.mesosphere.com/browse/DCOS-14108
https://jira.mesosphere.com/browse/DCOS-15989
a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).
> Increase timeout in test_vip

- gen/build_deploy/aws.py
AWS templates launched in the govcloud region were failing with the error:
```
CREATE_FAILED AWS::EC2::Instance NATInstance The request must contain the parameter ImageId 
```
The NAT mapping in the template appears to have been accidentally removed with commit
95b7dbccd.
FIXES: https://jira.mesosphere.com/browse/DCOS-15295
- [DCOS-15295](https://jira.mesosphere.com/browse/DCOS-15295>) DC/OS 1.9 not working in govcloud
> Restore NATAmi mapping for govcloud regions

- packages/marathon/buildinfo.json
- [MARATHON-7479](https://jira.mesosphere.com/browse/MARATHON-7479) Fixes major deployment plan computation performance regression for Marathon instances containing a large number of apps (500+).
> Target Marathon 1.4.5

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_networking.py
- packages/navstar/buildinfo.json
- packages/spartan/buildinfo.json
* Overlay could be enable/disable via "dcos_overlay_enable" in config.yaml. Currently, this flag is read by mesos overlay module but not by navstar overlay module. It will be good if navstar overlay module could also read this flag and enable/disable accordingly.
* Several performance improvements for spartan dns server.
* Spartan HTTP API (in there release only for debugging purposes)
* Add VIPs Debug HTTP API
* Currently it is possible for spartan to start it's own epmd if dcos-epmd is not yet started or has died for some reason. The systemd services for each of the Erlang based components should be reviewed and modified so that each ensures dcos-epmd is already running before starting.
- [DCOS_OSS-1134](https://jira.dcos.io/browse/DCOS_OSS-1134) Read dcos_overlay_enable to start/stop …
> Bump spartan and navstar

- pkgpanda/__init__.py
- pkgpanda/cli.py
- pkgpanda/constants.py
- pkgpanda/http/__init__.py
- pkgpanda/http/config.py
- pkgpanda/test_http.py
- pkgpanda/test_resources/packages/mesos--0.23.0/pkginfo.json
- pkgpanda/test_setup.py
This causes the Pkgpanda API to create state directories as appropriate for the packages it activates, making it consistent with the CLI's current behavior.
- [DCOS_OSS-1212](https://jira.mesosphere.com/browse/DCOS_OSS-1212) Pkgpanda API does not create package state dirs in /var/lib/dcos/
> Create state directory for packages activated via the Pkgpanda API

- packages/mesos/README.md
- packages/mesos/buildinfo.json
Updates to Apache Mesos master (1.4.0 WIP) beyond the recently introduced and then fixed Docker containerizer issue in strict mode. Backports are not needed.
- [CORE-1134](https://jira.mesosphere.com/browse/CORE-1134) Docker containerized tasks fail with broken pipe in strict mode.
- [DCOS-16115](https://jira.mesosphere.com/browse/DCOS-16115) Bump mesos for 1.10.
> Bumped Mesos to current (1.4.x WIP) master.

- packages/rexray/extra/dcos-rexray.service
REX-Ray does not currently source the proxy configuration in `/opt/mesosphere/etc/proxy.conf`. This means AWS agents behind a proxy can't contact the EBS API. This PR adds the proxy configuration to the `dcos-rexray.service` file to enable this behaviour.
- [DCOS_OSS-1283](https://jira.mesosphere.com/browse/DCOS_OSS-1283) rexray not honouring proxy config
___
> rexray: read proxy.env

- packages/marathon/buildinfo.json
This attempts to address [DCOS_OSS-1289](https://jira.mesosphere.com/browse/DCOS_OSS-1289), assuming that the current state of `https://downloads.mesosphere.io/marathon/snapshots/marathon-1.5.0-SNAPSHOT-582-g1793076.tgz` is sane. The root cause of the current mismatch in the `master` branch is still to be identified and will hopefully be reported to https://jira.mesosphere.com/browse/DCOS_OSS-1289.
> marathon: "fix" checksum of build artifact (DCOS_OSS-1289)

- gen/calc.py
- gen/tests/test_validation.py
- gen/tests/utils.py
- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- setup.py
This PR adds `custom_checks` as a supported parameter in `config.yaml`. This parameter contains custom check definitions which are added to the check config that is read by `dcos-diagnostics`. These custom checks are then executed alongside the builtin checks when `dcos-diagnostics check` is used.
Example custom check config:
```
custom_checks:
cluster_checks:
custom-check-1:
description: Foobar cluster service is healthy
cmd:
- echo
- hello
timeout: 1s
node_checks:
checks:
custom-check-2:
description: Foobar node service is healthy
cmd:
- echo
- hello
timeout: 1s
roles:
- agent
poststart:
- custom-check-2
```
- [DCOS_OSS-1024](https://jira.mesosphere.com/browse/DCOS_OSS-1024) Support adding custom check config during onprem installation
If you are changing components or packages in DC/OS …
> Add custom_checks config parameter

- pkgpanda/docker/dcos-builder/Dockerfile
https://github.com/golang/go/issues/20040 / https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-8932 has raised a bit of discussion recently. Let's use the latest 1.8.x Go distribution to include the corresponding fix.
This is tracked via [DCOS_OSS-1290](https://jira.mesosphere.com/browse/DCOS_OSS-1290).
> dcos-builder: bump Go to version 1.8.3

- packages/rexray/extra/dcos-rexray.service
REX-Ray does not currently source the proxy configuration in `/opt/mesosphere/etc/proxy.conf`. This means AWS agents behind a proxy can't contact the EBS API. This PR adds the proxy configuration to the `dcos-rexray.service` file to enable this behaviour.
- [DCOS_OSS-1283](https://jira.mesosphere.com/browse/DCOS_OSS-1283) rexray not honouring proxy config
___
> rexray: read proxy.env (1.9.1)

- packages/exhibitor/buildinfo.json
This addresses https://jira.mesosphere.com/browse/DCOS_OSS-739 and bumps ZooKeeper in DC/OS from version 3.4.8 to version 3.4.10.
Official changelog:
* http://zookeeper.apache.org/doc/r3.4.9/releasenotes.html
* http://zookeeper.apache.org/doc/r3.4.10/releasenotes.html
Particularly relevant changelog items:
* "Zookeeper service becomes unavailable when leader fails to write transaction log"
* "Back-port ZOOKEEPER-1460 to 3.4 for IPv6 literal address support."
* "CancelledKeyException in zookeeper"
* "Potential memory leak in recordio.c"
* "Large databases take a long time to regain a quorum"
* "Correct DataNode.getChildren() inconsistent behaviour."
> Bump ZooKeeper to release 3.4.10

- packages/dcos-test-utils/buildinfo.json
This updated DC/OS Test Utils to incorporate the changes in https://github.com/mesosphere/dcos-test-utils/pull/36. This is useful for testing WIP.
- [DCOS-16421](https://jira.mesosphere.com/browse/DCOS-16421) Fix broken DC/OS Enterprise End to End Tests
> [DCOS-16421] Bump test utils

- packages/adminrouter/extra/src/lib/service.lua
- packages/adminrouter/extra/src/test-harness/modules/util.py
- packages/adminrouter/extra/src/test-harness/tests/conftest.py
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
- packages/adminrouter/extra/src/test-harness/tests/test_service.py
This PR:
* makes dns mock a dependency for mocker. Without it the tests can
stall for >60s, depending on the order of fixtures in the function signature.
* adds missing tests for `/service` endpoint:
* verify that resolving a service waits for Marathon if the cache is empty
* verify that resolving a service waits for Mesos if the cache is empty
* verify that resolving a service returns 503 in case when Marathon was borked AND make sure that Mesos data is ignored in this case
* verify that resolving a service returns 503 in case when Mesos was borked AND resolving via Marathon did not succed
* verify that resolving a service returns 200 in case when Mesos was borked AND Marathon is OK
- https://jira.mesosphere.com/browse/DCOS-16108 `Inspect integration test failures as of Admin Router's …
> Admin Router: Improve /service endpoint tests

- gen/calc.py
- gen/tests/test_validation.py
- tox.ini
This PR ensures the user cannot pass a `s3_prefix` that ends in a '/' when installing DC/OS. This would have prevented an issue that one of our users ran into. See the jira for more details.
It also fixes the tox.ini to install the 'schema' python package when running tests.
- [DCOS_OSS-1353](https://jira.mesosphere.com/browse/DCOS_OSS-1353) gen: don't allow s3_prefix ending in '/'
___
> gen: validate s3_prefix

- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
This PR fixes a bug introduced in https://github.com/dcos/dcos/pull/1628 where we tested a value in a table against the json app definition encoding a 'null' value, but we never tested for the key not being specified at all.
- [DCOS_OSS-1366](https://jira.mesosphere.com/browse/DCOS_OSS-1366) Admin Router: service isn't resolved properly after some time
___
> adminrouter: check for nil in addition to cjson_safe.null

- packages/libsodium/buildinfo.json
* Existing version mentioned in buildinfo.json is no longer available.
The builds have been working out off our cache.
> Update libsodium dependency.

- packages/mesos/README.md
- packages/mesos/buildinfo.json
This PR updates the Mesos package SHA to the tip of Mesos master branch, which brings in fixes to a couple issues, noted below.
- [CORE-1116](https://jira.mesosphere.com/browse/CORE-1116) An extra Elastic framework appeared during Mesos Master failover in Soak
- [MESOS-7728](https://issues.apache.org/jira/browse/MESOS-7728) Java HTTP adapter crashes JVM when leading master disconnects
- [MESOS-7735](https://issues.apache.org/jira/browse/MESOS-7735) The master crashes when state endpoint is hit during a task authorization
> Bumped Mesos to include some fixes.

- packages/dcos-metrics/buildinfo.json
- This change bumps the commit hash of the dcos-metrics module so that the STATSD_UDP_HOST and STATSD_UDP_PORT envvars are exposed to tasks running on the Mesos default executor (dcos/dcos-metrics#106).
- None
___
* Developers responsible for code that interacts with or …
> Bump dcos-metrics version

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-test-utils/buildinfo.json
Tests often flake-out due to a marathon deployment timing out or some other odd deployment condition. To remedy this, purge all marathon workloads before and running EVERY test.
https://jira.mesosphere.com/browse/DCOS-14108
dcos-test-utils PR: https://github.com/mesosphere/dcos-test-utils/pull/40
> Purge Marathon state before and after tests

- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-metrics/buildinfo.json
This PR updates dcos-metrics to the latest master. This brings in a fix to a bug where app data would be lost if it was not sent as a single batch. Additionally, a stability fix which was already in master is brought back into 1.9.2 in this PR. 
- [DCOS-16350](https://jira.mesosphere.com/browse/DCOS-16350) dcos-metrics drops nearly all app data	
- [DCOS-15939](https://jira.mesosphere.com/browse/DCOS-16350) Long labels can cause errors in datadog plugin for dcos-metrics
> [1.9.2] Bump dcos-metrics hash

- packages/exhibitor/extra/start_exhibitor.py
Adds back `[myid:{}]` to `journald` messages output which was removed in one of the previous patches.
- [DCOS-15317](https://jira.mesosphere.com/browse/DCOS-15317) ZooKeeper log: ensure that `myid` is in the log
> exhibitor: Add back  to journald log messages

- gen/calc.py
- packages/dcos-checks/buildinfo.json
The current zk check uses port 8181, removing the check and moving it to use adminrouter. Unfortunately not supported in open. 
https://jira.mesosphere.com/browse/DCOS-16650
https://github.com/mesosphere/dcos-enterprise/pull/1143
Changelog:
https://github.com/dcos/dcos-checks/commit/422e531a6f180495c2569cf7a9ea407e67de4e3a
___ …
> Remove zk check 

- dcos_installer/backend.py
- dcos_installer/test_backend.py
This allows a user to override `aws_template_storage_region_name` in their `config.yaml` when generating cloud templates.
- https://jira.mesosphere.com/browse/DCOS-16737
> Override storage region

- packages/mesos/buildinfo.json
This PR bumps the Mesos package to the latest HEAD of the 1.2.x branch, to bring in the recent backported bugfix.
- [MESOS-7777](https://issues.apache.org/jira/browse/MESOS-7777) Agent failed to recover due to mount namespace leakage in Docker 1.12/1.13.
> Bumped Mesos package to latest HEAD of the 1.2.x branch.

- gen/dcos-config.yaml
This changes is required for dcos-kubernetes project as kubernetes require cni config files to have .conf extention
- [DCOS-17194](https://jira.mesosphere.com/browse/DCOS-17194) Rename .cni config files to .conf.
___
* Developers responsible for code that interacts with …
> Changes name of CNI conf file from .cni to .conf

- packages/mesos/README.md
- packages/mesos/buildinfo.json
This PR updates the Mesos package to include an additional cherry-picked commit which fixes broken sandbox links in the web UI.
- [CORE-1159](https://jira.mesosphere.com/browse/CORE-1159) Mesos UI sandbox redirection is broken in DC/OS.
> Bumped the Mesos package to fix the Mesos web UI sandbox links.

- packages/mesos/build
This adds RPATH `/opt/mesosphere/lib` to all Mesos binaries. This is important for making the `mesos-cni-port-mapper` work on all platforms.
- [DCOS_OSS-1377](https://jira.dcos.io/browse/DCOS_OSS-1377) Fixed UCR bridge mode for CentOS 7.
We don't have any integration tests for UCR bridge mode. These need to be enabled in `test_vips` once this PR is merged.
___ …
> Added an `--rpath` to Mesos builds.

- packages/erlang/build
- packages/navstar/buildinfo.json
- packages/spartan/buildinfo.json
Spartan exits repeatedly after a network partition test
- [DCOS-17217](https://jira.mesosphere.com/browse/DCOS-17217) Spartan exits repeatedly after a network partition test
https://github.com/dcos/spartan/pull/46
https://github.com/dcos/navstar/pull/84
___
* Developers …
> [1.10] Unregister node in epmd on start

- dcos_installer/test_backend.py
- gen/calc.py
1.9.2 should report its version as 1.9.2 :smile_cat:
> Bump version to 1.9.2

- gen/calc.py
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This PR sets the `PATH` and `LD_LIBRARY_PATH` for check commands in the check runner's config file, rather than inheriting them from the runner's environment.
- [DCOS_OSS-1321](https://jira.mesosphere.com/browse/DCOS_OSS-1321) Configurable search path for checks
> Set PATH and LD_LIBRARY_PATH for check commands

- packages/docker-gc/extra/dcos-docker-gc.service
1.9 backport of #1543.
- [DCOS_OSS-1433](https://jira.mesosphere.com/browse/DCOS_OSS-1433) Bug in /etc/systemd/system/dcos-docker-gc.service script (1.9)
> (1.9) Set ConditionalPathExists in correct area.

- packages/docker-gc/extra/dcos-docker-gc.service
- packages/mesos/buildinfo.json
#1742 (1.9) Set ConditionalPathExists in correct area.
#1757 Bumped Mesos package to latest HEAD of the 1.2.x branch.
> [1.9.3] Train 196

- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/lib/service.lua
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
Improves logging messages related to caching.
- https://jira.mesosphere.com/browse/DCOS-16614 - `Admin Router: "Using stale `svcapps` cache" and "Resolved via Mesos state-summary" for the same request`
EE: https://github.com/mesosphere/dcos-enterprise/pull/1220
> Admin Router: improve logging messages related to caching

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_mesos.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_service_discovery.py
- packages/dcos-integration-test/extra/test_ucr.py
- packages/dcos-integration-test/extra/util/delete_ec2_volume.py
- packages/dcos-test-utils/buildinfo.json
Updates test suite so that the test server marathon app lives with the test server code (in dcos-integration-test). Meanwhile, the methods in dcos-test-utils were untangled
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/1235
> Refactor dcos_test_utils.marathon

- README.md
The current link to JIRA is incorrect. This fixes it.
> Update link to JIRA

- packages/navstar/buildinfo.json
This reverts commit b14e5d04368236720f941ee25799d1dc96f9f4c3 (PR #1778). This
change is causing the overlay network to break for existing Data Agility
services.
> Revert "Bump navstar"

- packages/dcos-metrics/buildinfo.json
- packages/erlang/build
- packages/navstar/buildinfo.json
- packages/spartan/buildinfo.json
This is train 200 targeted for the 1.9.3 release, against the `1.9` branch. It contains the following pull requests:
- #1766 ([1.9.3] Bump dcos-metrics version)
- #1743 ([1.9.3] bump spartan and navstar)
> [1.9.3] Train 200

- packages/erlang/build
- packages/navstar/buildinfo.json
- packages/spartan/buildinfo.json
* Spartan exits repeatedly after a network partition test
* Currently it is possible for spartan to start it's own epmd if dcos-epmd is not yet started or has died for some reason. The systemd services for each of the Erlang based components should be reviewed and modified so that each ensures dcos-epmd is already running before starting.
* Fix inconsistent state error in minuteman
- [DCOS-17271](https://jira.mesosphere.com/browse/DCOS-17271) dcos-epmd failing after host reboot
- [DCOS-17217](https://jira.mesosphere.com/browse/DCOS-17217) Spartan exits repeatedly after a network partition test
- [DCOS_OSS-1128](https://jira.mesosphere.com/browse/DCOS_OSS-1128) Ensure DC/OS Erlang based apps use dcos-epmd.service
- [DCOS_OSS-1472](https://jira.mesosphere.com/browse/DCOS_OSS-1472) …
> [1.9.3] bump spartan and navstar

- packages/dcos-metrics/buildinfo.json
- [DCOS_OSS-1451](https://jira.dcos.io/browse/DCOS_OSS-1451) Stale datapoints can occur in container metrics
- [DCOS_OSS-1486](https://jira.dcos.io/browse/DCOS_OSS-1486) Metrics agent crashes when the mesos containers endpoint is missing fields
> [1.9.3] Bump dcos-metrics version

- packages/dcos-integration-test/extra/api_session_fixture.py
- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-test-utils/buildinfo.json
Log level should be configurable by environment. dcos-test-utils has a method configured for lowering the undersirable loggers a level lower than the current setting.
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/1232
> Configurable log level

- packages/adminrouter/extra/src/includes/server/master.conf
Re-enables request buffering for `/service` endpoint.
https://jira.mesosphere.com/browse/DCOS_OSS-1491 - Admin Router: /service endpoint request buffering was disabled w/o strong technical reason
> Admin Router: Re-enable request buffering for /service endpoint

- packages/mesos/buildinfo.json
Bump Mesos to the latest 1.2.x (in this case, the rc1 for 1.2.2). We were previously on a SHA between 1.2.1 and 1.2.2.
* [CORE-1250](https://jira.mesosphere.com/browse/CORE-1250) - [1.9.x] Bump Mesos to 1.2.2
* [MESOS-5187](https://issues.apache.org/jira/browse/MESOS-5187) - The filesystem/linux isolator does not set the permissions of the host_path.
* [MESOS-7252](https://issues.apache.org/jira/browse/MESOS-7252) - Need to fix resource check in long-lived framework.
* [MESOS-7830](https://issues.apache.org/jira/browse/MESOS-7830) - Sandbox_path volume does not have ownership set correctly.
> [1.9.x] Bump to Mesos 1.2.2-rc1.

- packages/adminrouter/build
- packages/adminrouter/docker/adminrouter-upstreams-ee.conf
- packages/adminrouter/docker/adminrouter-upstreams-open.conf
- packages/adminrouter/extra/src/Makefile.common
- packages/adminrouter/extra/src/README.md
- packages/adminrouter/extra/src/docs/api/nginx.master.html
- packages/adminrouter/extra/src/docs/api/nginx.master.yaml
- packages/adminrouter/extra/src/includes/http/agent.conf
- packages/adminrouter/extra/src/includes/http/master.conf
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/test-harness/conftest.py
- packages/adminrouter/extra/src/test-harness/modules/mocker/dns.py
- packages/adminrouter/extra/src/test-harness/modules/runner/common.py
- packages/adminrouter/extra/src/test-harness/modules/util.py
- packages/adminrouter/extra/src/test-harness/tests/test_dns.py
- packages/adminrouter/extra/systemd/dcos-adminrouter-agent-reload.service
- packages/adminrouter/extra/systemd/dcos-adminrouter-agent-reload.timer
- packages/adminrouter/extra/systemd/dcos-adminrouter-reload.service
- packages/adminrouter/extra/systemd/dcos-adminrouter-reload.timer
- packages/dcos-integration-test/extra/test_composition.py
This PR:
* performs some minor cleanup of docker files - CA bundle location sync
* removes $upstream_marathon variable definition as it is no longer needed - all requests go through /service endpoint and the upstream is determined basing on Mesos' `/state-summary` endpoint
* makes devkit as per-flavour. This enables running both EE and Open devkits side-by-side and permits differences between EE and Open devkits
* exposes test harness logs in a log file, Jenkins should automatically pick it up and treat it as yet another artefact
* removes period reloading of AR in favour of DNS queries, see DCOS_OSS-1446 for details
* removes TTL override for AR DNS resolver. See the comments in the configuration for more details.
- https://jira.mesosphere.com/browse/DCOS_OSS-1446 - Admin Router: Dynamic …
> Admin Router: Remove periodic AR reloading in favour of DNS queries

- packages/exhibitor/extra/start_exhibitor.py
Changes the `journald` logger that Exhibitor uses from the default `PatternLayout` to `PatternLayoutExcaped` which escapes several charactes like (`\n`,` \r`, ...).
- [DCOS_OSS-1470](https://jira.dcos.io/browse/DCOS_OSS-1470) Exhibitor: use PatternLayoutEscaped logger layout for structured journal logger
> [DCOS_OSS-1470] Exhibitor: use PatternLayoutEscaped logger layout for structured journal logger

- packages/dcos-ui/buildinfo.json
**DCOS-UI release**: https://github.com/dcos/dcos-ui/releases/tag/v1.10.0-rc.4
- [DCOS_OSS-940 **HIGH**](https://jira.mesosphere.com/browse/DCOS_OSS-940): Show unreachable tasks in task table
- [DCOS-17205 **BLOCKER**](https://jira.mesosphere.com/browse/DCOS-17205): CLI command for SDK update is only available on Enterprise edition
- [DCOS-16636 **HIGH**](https://jira.mesosphere.com/browse/DCOS-16636): Adjust universe setup/teardown scripts for system tests
- [DCOS-17389 **HIGH**](https://jira.mesosphere.com/browse/DCOS-17389): Update CLI install command for OSX/Linux
- [DCOS-17301 **HIGH**](https://jira.mesosphere.com/browse/DCOS-17301): Show all tasks for a Framework running in a nested folder
- [DCOS-17463 …
> [next-beta] DCOS-UI: Update package for 1.10

- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_service_discovery.py
Vagrant tests are blocking AdminRouter changes in the following cases:
test_octarine
test_service_discovery_docker_bridge
test_service_discovery_docker_overlay
test_service_discovery_docker_overlay_port_mapping
test_ip_per_container
As per the tickets below, these failures are being treated as vagrant specific and therefore are being skipped until a fix can be introduced in dcos-vagrant
https://jira.mesosphere.com/browse/DCOS_OSS-1531
https://jira.mesosphere.com/browse/DCOS_OSS-1532
> skip vagrant tests for DCOS_OSS-1532

- dcos_installer/test_backend.py
- gen/calc.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_3dt.py
- packages/marathon/buildinfo.json
* #1807 - Add cluster-id file to diagnostics bundle
* #1814 - Bump version to 1.9.3
* #1820 -  bumping the marathon to version 1.4.6
> 1.9 train 202

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_3dt.py
This change adds cluster-id file to the diagnostics bundle. This file is useful for support team for issue tracking purposes. (Backporting #1806 to 1.9)
No JIRA filed, just a feature request from support team
___
@darkonie Please review
> Add cluster-id filed to diagnostics bundle (1.9.x)

- packages/marathon/buildinfo.json
The release resolves a large number of bugs and customer issues from version 1.4.5.   Most significantly this includes:  quick response to unreachable strategy, marathon losing tasks on leadership switch, and a race condition bug.   This also resolves a security issue with HTTP TRACE in marathon.
- [MARATHON-7681](https://jira.mesosphere.com/browse/MARATHON-7681) - Fixes an issue in WorkQueue that could cause Marathon to drop exceptions and become unresponsive.
- [MARATHON-7653](https://jira.mesosphere.com/browse/MARATHON-7653) - Fixes an issue in which Marathon could become unresponsive when pod status wasn't available
- [MARATHON-7629](https://jira.mesosphere.com/browse/MARATHON-7629) - Fixes issue in which Marathon could get into an infinite kill loop, in certain situations
- …
> bumping the marathon to version 1.4.6

- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_service_discovery.py
- test_util/run-all
- Upgrade dcos-vagrant
- Enhance mesos-memory to emulate systemd environment of dcos-mesos-slave[-public] by parsing EnvironmentFiles
- Upgrade to dcos-vagrant-box 0.9.2 (Centos 7.3.1611, Docker 1.13.1)
- Don't fail dcos-postflight if STATUS_CMD fails (print error)
- Upgrade dcos-postflight script to use `dcos-diagnostics check node-poststart` and parse its output with `jq`
- Move scripts from /usr/local/sbin -> /usr/sbin so they're in the PATH for vagrant SSH
- Unskip dcos-vagrant tests muted by [DCOS_OSS-1531](https://jira.mesosphere.com/browse/DCOS_OSS-1531)
- [DCOS_OSS-1523](https://jira.mesosphere.com/browse/DCOS_OSS-1523) DC/OS Vagrant: Improve how memory resources are defined for agents
- [DCOS_OSS-1524](https://jira.mesosphere.com/browse/DCOS_OSS-1524) dcos-diagnostics --diag …
> Bump dcos-vagrant

- packages/marathon/buildinfo.json
Upgrade to latest Marathon 1.5 master with latest bug fixes.
___ …
> Update Marathon to 1.5.0-SNAPSHOT-706-g27c2744

- gen/dcos-config.yaml
- packages/mesos/buildinfo.json
This patch updates the Mesos package to use the latest from the Apache Mesos `1.4.x` branch.
- [MESOS-7871](https://issues.apache.org/jira/browse/MESOS-7871) Agent fails assertion during request to '/state'
- [MESOS-6950](https://issues.apache.org/jira/browse/MESOS-6950) Launching two tasks with the same Docker image simultaneously may cause a staging dir never cleaned up
- [CORE-1225](https://jira.mesosphere.com/browse/CORE-1225) Support shared PID namespace in Mesos.
- [CORE-1274](https://jira.mesosphere.com/browse/CORE-1274) Enable the Mesos Agent flag 'disallow_sharing_agent_pid_namespace' in DC/OS for security concern. …
> Bumped the Mesos package to recent 1.4.x.

- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-test-utils/buildinfo.json
Increases the default timeout for marathon app deployment to be 2X mesos default timeout
> Bump dcos-test-utils

- gen/aws/templates/cloudformation.json
Depending on GatewayToInternet alone was not viable
as it could happen that the autoscaling group may come
up before the networking rules that would actually allow
the private agents to download DC/OS
https://jira.mesosphere.com/browse/QUALITY-1516
> Fix slave server autoscaling group dependency

- packages/dcos-metrics/buildinfo.json
This bump allows metrics to attempt to fall back to http after an https call to Mesos state fails (which can happen during disabled->permissive upgrades), and adds task information to the container metrics endpoint in dcos-metrics.
- [DCOS_OSS-1542](https://jira.dcos.io/browse/DCOS_OSS-1542) Fall back to HTTP when polling Mesos state in dcos-metrics
- [DCOS-17813](https://jira.mesosphere.com/browse/DCOS-17813) Include task name as a dimension via dcos-metrics API
> [next beta] Bump dcos-metrics version

- packages/navstar/buildinfo.json
- Fix inconsistent state error in minuteman
- [DCOS_OSS-1472](https://jira.mesosphere.com/browse/DCOS_OSS-1472) Inconsistent state of minuteman
___
It is best to proactively ask …
> bump navstar for 1.10

- packages/mesos-modules/buildinfo.json
This includes a fix for CHECK failing on nested container launch, when:
1. The parent container is launched
2. The agent is restarted
3. A nested container is launched in the same parent
- [CORE-1279](https://jira.mesosphere.com/browse/CORE-1279) Internal tracking ticket which basically says the same thing as this description.
> Bump Mesos modules package.

- packages/marathon/buildinfo.json
* [MARATHON-7715](https://jira.mesosphere.com/browse/MARATHON-7715) - Marathon would not notice an unreachable / lost resident task was gone, or that a reservation should be released, unless if it was idle. This is has been resolved.
* [MARATHON-1703](https://jira.mesosphere.com/browse/MARATHON-1703) - Resident task instance placement now properly respects constraints which rely on the placement state of instance peers (such as hostname:UNIQUE).
* [MARATHON-7707](https://jira.mesosphere.com/browse/MARATHON-7707) - Resident task instance agentId and host name values are now properly updated on re-launch.
* [MARATHON-7654](https://jira.mesosphere.com/browse/MARATHON-7654) - …
> Bump Marathon to 1.4.7.

- packages/adminrouter/extra/src/README.md
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/includes/server/open/master.conf
- packages/adminrouter/extra/src/lib/util.lua
- packages/adminrouter/extra/src/test-harness/modules/generic_test_code/common.py
- packages/adminrouter/extra/src/test-harness/modules/generic_test_code/generalised_tests.py
- packages/adminrouter/extra/src/test-harness/tests/open/test_generic.config.yml
- packages/adminrouter/extra/src/test-harness/tests/test_generic.config.yml
This PR introduces removing `dcos-*` cookies for upstream requests.
For technical motivation - please check the linked Jira issue
For technical implementation details - please check the description of the function `util.clear_dcos_cookies` in `lib/util.lua` file
- https://jira.mesosphere.com/browse/DCOS-12015 `Admin Router: remove auth cookie after translating it into Authorization header`
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/1298
> Admin Router: Prevent forwarding dcos-* cookies to upstreams

- dcos_installer/upgrade.py
Fix error handling for the upgrade script. 
Remove the workaround which we had earlier for trapping error codes, now all the individual statements have the fixes
Add functionality to skip checks
Related changes in the test infra:
https://github.com/dcos/dcos-test-utils/pull/8
https://jira.mesosphere.com/browse/DCOS-17844 
___ …
> Adding skip checks flag to the upgrade script

- gen/calc.py
- packages/dcos-checks/buildinfo.json
EE DC/OS [PR](https://github.com/mesosphere/dcos-enterprise/pull/1322)
Add a new check command to dcos-checks and node-poststart config to verify the journald directory has the right owner / group and the permission bits are set correctly.
- [DCOS_OSS-1362](https://jira.mesosphere.com/browse/DCOS_OSS-1362)
- [DCOS-16568](https://jira.mesosphere.com/browse/DCOS-16568)
- [DCOS_OSS-1240](https://jira.mesosphere.com/browse/DCOS_OSS-1240)
___ …
> add journald directory ownership/permissions check

- packages/mesos/buildinfo.json
Bumping Mesos to 1.4.0-rc1
Replying on Mesos test suite.
___ …
> Bumped Mesos to 1.4.0-rc1.

- packages/mesos/README.md
- packages/mesos/buildinfo.json
This PR is meant to be merged after pull/1855. It incorporates three additional commits into the Mesos package which update the logging of Mesos checks/health checks.
- [MESOS-7861](https://issues.apache.org/jira/browse/MESOS-7861) Include check output in the DefaultExecutor log
> Bumped Mesos to include health check logging improvements.

- dcos_installer/upgrade.py
Make skip-checks a flag instead of an argument
No jira 
___ …
> Make skip checks a flag

- packages/navstar/buildinfo.json
Bump navstar to include a fix for coreOS 1465+
- [DCOS_OSS-1574](https://jira.mesosphere.com/browse/DCOS_OSS-1574) Navstar is unhealthy on Core OS 1465+
___
It is best to …
> Final bump navstar for 1.10

- packages/dcos-metrics/buildinfo.json
This is a metrics bump PR. It includes a workaround for an issue which meant that nested app metrics were not discoverable. 
- [DCOS-18195](https://jira.mesosphere.com/browse/DCOS-18195) Nested container IDs don't appear in dcos-metrics /containers endpoint
> [1.10] Bump dcos-metrics

- packages/mesos/README.md
- packages/mesos/buildinfo.json
This PR bumps the Mesos package to the latest 1.4.0 release candidate, 1.4.0-rc3.
- [MESOS-7714](https://issues.apache.org/jira/browse/MESOS-7714) Fix agent downgrade for reservation refinement
> Bumped Mesos package to 1.4.0-rc3.

- packages/adminrouter/extra/src/docs/api/nginx.agent.html
- packages/adminrouter/extra/src/docs/api/nginx.agent.yaml
- packages/adminrouter/extra/src/docs/api/nginx.master.html
- packages/adminrouter/extra/src/docs/api/nginx.master.yaml
- packages/adminrouter/extra/src/includes/http/agent.conf
- packages/adminrouter/extra/src/includes/http/common.conf
- packages/adminrouter/extra/src/includes/http/master.conf
- packages/adminrouter/extra/src/includes/http/open/master.conf
- packages/dcos-integration-test/extra/test_networking.py
This is train 211. It includes:
- #1875 (Bump 1.9 api links to 1.10)
- #1873 (test_networking.test_vip test is flaky [2])
> [1.10] Train 211

- packages/adminrouter/extra/src/docs/api/nginx.agent.html
- packages/adminrouter/extra/src/docs/api/nginx.agent.yaml
- packages/adminrouter/extra/src/docs/api/nginx.master.html
- packages/adminrouter/extra/src/docs/api/nginx.master.yaml
- packages/adminrouter/extra/src/includes/http/agent.conf
- packages/adminrouter/extra/src/includes/http/common.conf
- packages/adminrouter/extra/src/includes/http/master.conf
- packages/adminrouter/extra/src/includes/http/open/master.conf
API docs need to point to the right place for 1.10.
@vespian who else should review this minor change?
JIRA: https://jira.mesosphere.com/browse/DCOS-18244
> Bump 1.9 api links to 1.10

- packages/dcos-integration-test/extra/test_packaging.py
- packages/dcos-test-utils/buildinfo.json
Here is the analogous PR to 1.10 https://github.com/dcos/dcos/pull/1889
I had the interface wrong on the `dcos_api_session.cosmos` endpoint in `dcos-test-utils`, where install didn't take all of the options, and install and uninstall had some options as required when only the packageName is required. 
Correcting dcos-test-utils https://github.com/dcos/dcos-test-utils/pull/7/commits/bc75f1a46ef173d9bb982f8ae2a75ffbd6b57ce8
Merging that will require this to be merged so the `test_packaging.py` tests don't fail.
This is all ultimately to support the tweeter integration test
https://github.com/mesosphere/dcos-enterprise/pull/1303 …
> Update package/cosmos api usage in integration tests

- cloud_images/centos7/dcos_vol_setup.sh
- cloud_images/centos7/install_prereqs.sh
This PR updates the dcos_vol_setup.service dependencies so that it starts as early as possible in the boot sequence. It also simplifies dcos_vol_setup.sh - the systemd manipulations and /var/log migration are no longer necessary now that dcos_vol_setup.service is running early.
Because dcos_vol_setup.service did not include DefaultDependencies=no, it was implicitly running with After=basic.target which is fairly late in the systemd targets. Many other services are started after basic.target - like dockerd and chrony - which in some cases were left in a bad state because file systems were being formatted while the services were initializing.
Coincidentally, dcos_vol_setup was failing prematurely because it was receiving SIGPIPE when trying to write to stdout/stderr when systemd-journald …
> Prevent dcos_vol_setup from formatting partitions while services are starting

- packages/dcos-ui/buildinfo.json
- packages/mesos/buildinfo.json
This is train 214 with patches that are supposed to land in the 1.10.0 release. It contains the following pull requests:
- #1892 (Update DC/OS UI package to 1.10.0-rc.8 (1.10))
- #1900 (Bumped Mesos package to 1.4.x head 60b8d41)
> [1.10.0] Train 214

- packages/dcos-integration-test/extra/test_packaging.py
- packages/dcos-test-utils/buildinfo.json
This is the same as https://github.com/dcos/dcos/pull/1833 (PR to master)
I had the interface wrong on the `dcos_api_session.cosmos` endpoint in `dcos-test-utils`, where install didn't take all of the options, and install and uninstall had some options as required when only the packageName is required. 
This is all ultimately to support the tweeter integration test
https://github.com/mesosphere/dcos-enterprise/pull/1303
___
All PRs require 2 approvals using github's …
> Update package/cosmos api usage in integration tests 

- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
Since DC/OS 1.8+ agents do not depend on `leader.mesos` (e.g. we can start a dcos-mesos-slave with `--master=zk1:2181`), we should not have this prerequisite as it can result in outages.
> Removed leader.mesos prerequisite for dcos-mesos-slave.

- packages/dcos-test-utils/buildinfo.json
Dcos-test-utils now includes dcos-cli abstraction that was previously included in dcos-enterprise testing suite
___
> Bump dcos-test-utils to dev cli branch

- dcos_installer/check.py
- dcos_installer/test_check.py
This causes the installer to print a descriptive error to the console when checks fail during `--postflight`, instead of a confusing traceback.
- [DCOS_OSS-1661](https://jira.mesosphere.com/browse/DCOS_OSS-1661) Installer prints large traceback when checks fail during --postflight
> Fix method name in installer

- dcos_installer/backend.py
- dcos_installer/config.py
- dcos_installer/config_util.py
- dcos_installer/test_backend.py
- dcos_installer/test_config.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-metrics/buildinfo.json
- packages/mesos/buildinfo.json
- tox.ini
This is train 224. It is comprised of the following pull requests:
* #1902 dcos_installer: Don't run genconf validation twice
* #1910 test_networking.test_vip test is flaky [3]
* #1913 Bump Mesos to 1.4.0 
* #1944 Bump dcos-metrics
> [master] train 224

- dcos_installer/backend.py
- dcos_installer/config.py
- dcos_installer/config_util.py
- dcos_installer/test_backend.py
- dcos_installer/test_config.py
- tox.ini
When a user runs `./dcos_generate_config.sh` they'll get messages produced by gen package twice, i.e.
```
====> EXECUTING CONFIGURATION GENERATION
Generating configuration files...
Generating configuration files...
```
This patch is a minimal change that prevents dupes in the logging output. This PR addresses the issue discovered in https://github.com/mesosphere/dcos-enterprise/pull/1391#issuecomment-327164903
- [DCOS-18206](https://jira.mesosphere.com/browse/DCOS-18206) gen_extra: Add installer warning for private key on node when installing cluster with custom CA cert
> dcos_installer: Don't run genconf validation twice

- packages/dcos-integration-test/extra/test_networking.py
Remove port range from 14849 to 15103 from global port pool. We hope that we will revert this patch in the future when we will support centos 7.4.  
Linux kernel 3.10.0-327 (centos 7.2) and 3.10.0-514 (centos 7.3) drops outgoing lxlan tcp packets if the destination port is in the range from 14849 to 15103. It's 255-port range, from 0x3a01 to 0x3aff. it's not iptables or something like that, it's somewhere in interface driver. ICMP and UPD work fine. If you start another tcp server outside the range 14849-15103 in the same container it will work. We didn't find the exact line where this bug is happening in linux kernel, but we haven't seen this bug on linux kernel 3.10.0-693 (centos 7.4).
- [DCOS_OSS-1463](https://jira.mesosphere.com/browse/DCOS_OSS-1463) test_networking.test_vip test is …
> test_networking.test_vip test is flaky [3]

- packages/dcos-metrics/buildinfo.json
This PR adds `task_id` and `task_name` to the `dimensions` hash in the  `/v0/containers/container-id/app` endpoint. 
- [DCOS-17956](https://jira.mesosphere.com/browse/DCOS-17956) Include task name as a dimension in /container/app endpoint in dcos-metrics
> Bump dcos-metrics

- packages/dcos-ui/buildinfo.json
*Contains a blocker fix for better catalog package deployment.*
- [DCOS-18055](https://jira.mesosphere.com/browse/DCOS-18055): Improve catalog deployment to remove 1-click install.
- [DCOS-18212](https://jira.mesosphere.com/browse/DCOS-18212): Change "mesos runtime" copy to UCR in service create form.
___ …
> chore(dcos-ui): bump dcos-ui for 1.10.1

- dcos_installer/check.py
- dcos_installer/test_check.py
This is a backport of #1936.
This causes the installer to print a descriptive error to the console when checks fail during `--postflight`, instead of a confusing traceback.
- [DCOS_OSS-1661](https://jira.mesosphere.com/browse/DCOS_OSS-1661) Installer prints large traceback when checks fail during --postflight
> (1.10) Fix method name in installer

- packages/dcos-metrics/buildinfo.json
This PR backports a fix which add `task_id` and `task_name` to the `dimensions` hash in the  `/v0/containers/container-id/app` endpoint. 
- [DCOS-17956](https://jira.mesosphere.com/browse/DCOS-17956) Include task name as a dimension in /container/app endpoint in dcos-metrics
> [1.10.1] Bump dcos-metrics

- packages/mesos/README.md
- packages/mesos/buildinfo.json
- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
* #1851 - Bump the Mesos package to include critical backports.
* #1947 - [1.8.10] Removed leader.mesos prerequisite for dcos-mesos-slave(-public)
> 1.8.10 train 222

- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
Since DC/OS 1.8+ agents do not depend on `leader.mesos` (e.g. we can start a dcos-mesos-slave with `--master=zk1:2181`), we should not have this prerequisite for the services dcos-mesos-slave and dcos-mesos-slave-public as it can result in outages.
This PR is a backport of #1921 for DC/OS 1.8.
> [1.8.10] Removed leader.mesos prerequisite for dcos-mesos-slave(-public).

- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
Since DC/OS 1.8+ agents do not depend on `leader.mesos` (e.g. we can start a dcos-mesos-slave with `--master=zk1:2181`), we should not have this prerequisite for the services dcos-mesos-slave and dcos-mesos-slave-public as it can result in outages.
This PR is a backport of #1921 for DC/OS 1.9.
> [1.9.5] Removed leader.mesos prerequisite for dcos-mesos-slave(-public).

- packages/marathon/buildinfo.json
- packages/navstar/buildinfo.json
This is train 227, meant to land before the 1.9.5 release. It contains the following pull requests:
* #1955 (Marathon 1.4.8)
* #1939 (Navstar bump)
> [1.9.5] Train 227

- packages/navstar/buildinfo.json
This patch bumps navstar to include the fix wherein navstar was
crashing on coreOS 1465+
- [DCOS_OSS-1574](https://jira.mesosphere.com/browse/DCOS_OSS-1574) Navstar is unhealthy on Core OS 1465+
-https://github.com/dcos/navstar/compare/bfc09c9eca064cacc275be04bd65c98361f2504a...73a35a8d4642ef7a126a973b6c10eec331745add
-https://github.com/mesosphere/gen_netlink/compare/3dbbc77c3cb9631516e9c2d835b24f83b52f9e13...mesosphere:2b4b657ea03bc839dafb77948fb7908dccf0f91b
___
All …
> Bump navstar.

- packages/cosmos/buildinfo.json
- packages/libsodium/buildinfo.json
- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
This is train 228 intended for 1.10.1 release. It is comprised of the following pull requests:
* #1906 Fetch libsodium binary from github
* #1945 [1.10.1] Removed leader.mesos prerequisite for dcos-mesos-slave(-public)
* #1954 Release cosmos v0.4.2
> [1.10] Train 228

- packages/libsodium/buildinfo.json
Server `download.libsodium.org` has rather strict SSL configuration as with newer SSL libraries build fails with
```
python 3.5 [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)
```
as python requests fail to download the binary. 
The library version stays the same, only fetched from different mirror.
```
$ sha1sum libsodium-1.0.9.tar.gz 
6e886fa6c7b0c0dc8a9039f49e1b04532401a6ae  libsodium-1.0.9.tar.gz
````
- no related issue so far
___
> Fetch libsodium binary from github

- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
Since DC/OS 1.8+ agents do not depend on `leader.mesos` (e.g. we can start a dcos-mesos-slave with `--master=zk1:2181`), we should not have this prerequisite for the services dcos-mesos-slave and dcos-mesos-slave-public as it can result in outages.
This PR is a backport of #1921 for DC/OS 1.10.
> [1.10.1] Removed leader.mesos prerequisite for dcos-mesos-slave(-public).

- gen/dcos-config.yaml
Global modification of the linker's path is confusing, and can result in non-DCOS
binaries being linked against DCOS libraries. This has caused breakage in at
least one instance where a system-provided `curl` linked against an interface-
incompatible older `libcurl` provided by DCOS, causing MESOS_HTTP healthchecks
to fail.
This commit mirrors the path started in dcos/dcos#707, but with the addition of
rpath in 27339e3 that change is no longer necessary. Further, we opt to preserve
the SASL_PATH override, even though it suffers similar concerns, because libsasl2
would require special mesos-only configuration at compilation time in order to
provide for mesos' out-of-the-box authentication, and that library is not
currently part of the mesos build flow.
Fixes DCOS_OSS-1302.
- …
> dcos-mesos-agent: prefer system libraries for exec'd processes

- dcos_installer/backend.py
- dcos_installer/config.py
- dcos_installer/config_util.py
- dcos_installer/test_backend.py
- dcos_installer/test_config.py
- gen/calc.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- tox.ini
This is train 230 meant for the 1.10.1 release. It includes the following pull requests:
- #1908 (Add cluster ID to diagnostics bundle for 1.10)
- #1959 (dcos_installer: Don't run genconf validation twice [1.10 backport])
- #1972 (Bump DC/OS version to 1.10.1)
> [1.10] Train 230

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
https://github.com/dcos/dcos/pull/1806 did not get merged into master before 1.10 was cut. Hence this PR
Edit(JP): https://jira.mesosphere.com/browse/DCOS_OSS-1627
___
@darkonie @jgehrcke  Please review
> Add cluster ID to diagnostics bundle for 1.10

- dcos_installer/backend.py
- dcos_installer/config.py
- dcos_installer/config_util.py
- dcos_installer/test_backend.py
- dcos_installer/test_config.py
- tox.ini
**1.10 backport**
When a user runs `./dcos_generate_config.sh` they'll get messages produced by gen package twice, i.e.
```
====> EXECUTING CONFIGURATION GENERATION
Generating configuration files...
Generating configuration files...
```
This patch is a minimal change that prevents dupes in the logging output. This PR addresses the issue discovered in https://github.com/mesosphere/dcos-enterprise/pull/1391#issuecomment-327164903
Edit(JP):  This is a backport of #1902 (proper review over there).
- [DCOS-18206](https://jira.mesosphere.com/browse/DCOS-18206) gen_extra: Add installer warning for private key on node when installing cluster with custom CA cert …
> dcos_installer: Don't run genconf validation twice [1.10 backport]

- dcos_installer/test_backend.py
- gen/calc.py
The 1.10.1 version bump! Tracked via https://jira.mesosphere.com/browse/DCOS_OSS-1698.
> Bump DC/OS version to 1.10.1

- dcos_installer/config_util.py
- gen/__init__.py
- gen/build_deploy/bash.py
- gen/build_deploy/util.py
- gen/calc.py
- gen/util.py
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- setup.py
This PR allows onprem installations to include a set of custom executables that can be called from custom checks defined in `config.yaml`. Any executables found in `genconf/check_bins/` will be distributed to cluster nodes and added to the check runner's search path.
- [DCOS_OSS-1275](https://jira.mesosphere.com/browse/DCOS_OSS-1275) Support adding custom check executables during onprem installation
> Support adding custom check executables during onprem installation

- packages/dcos-integration-test/extra/test_ec2.py
- test_util/dcos_api_session.py
- test_util/helpers.py
- test_util/marathon.py
* Adds simple disconnections retry decorator for more robust test cases
* makes ec2 tests skip when not applicable
* https://jira.mesosphere.com/browse/DCOS_OSS-1682
* https://jira.mesosphere.com/browse/DCOS_OSS-1683
* https://jira.mesosphere.com/browse/DCOS_OSS-1686
> Fix tests for 1.9 (backports)

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This is a manual port of https://github.com/dcos/dcos/pull/1908 to the master branch.
#1806 did not get merged into master before 1.10 was cut. Hence this PR.
- [DCOS_OSS-1627](https://jira.mesosphere.com/browse/DCOS_OSS-1627) cluster_id not available in diagnotic bundle
___
> gen/dcos-config.yaml: Add cluster ID to diagnostics bundle

- packages/marathon/buildinfo.json
- [MARATHON-7576](https://jira.mesosphere.com/browse/MARATHON-7576) Changed default of UnreachableEnabled to (0,0)
- [D907](https://phabricator.mesosphere.com/D907) TaskLauncherActor doesn't wait for in-flight tasks on stop
- [MARATHON-7765](https://jira.mesosphere.com/browse/MARATHON-7765) Fixes issue in which /v2/info endpoint always returned 1.5.0-snapshot1, regardless of the actual endpoint.
- [PR 5421](https://github.com/mesosphere/marathon/pull/5421) Added SchedulerPlugin to enable the ability to customize the rejection of offers. (see below)
- [MARATHON-2520](https://jira.mesosphere.com/browse/MARATHON-2520) Improved logging around migration
- …
> bump to marathon 1.5.1

- packages/dcos-test-utils/buildinfo.json
This bumps the version of DC/OS Test Utils.
In particular I am doing this to get the value of https://github.com/dcos/dcos-test-utils/pull/10/ which will hopefully reduce flaky tests.
- [DCOS_OSS-1547](https://jira.dcos.io/browse/DCOS_OSS-1547) Upgrade Test Flaky
- [DCOS-18971](https://jira.mesosphere.com/browse/DCOS-18971) _wait_for_dcos_history_data is flaky
> Bump DC/OS Test Utils to the latest version to include a fix for _wait_for_dcos_history_data

- packages/marathon/buildinfo.json
We updated the Scala version and need to bump dcos plugins
It bumps to the latest marathon 1.6.0 snapshot build for DCOS 1.11
- [MARATHON-7223](https://jira.mesosphere.com/browse/MARATHON-7229) Upgrade Scala to 2.12
> Bump Marathon to 1.6.0-pre-19

- gen/calc.py
- gen/dcos-config.yaml
- gen/tests/test_validation.py
With the latest partition awareness changes, we can increase
the recovery timeout to a much higher value to avoid outages
due to the agent being down for whatever reason.
- [CORE-1291](https://jira.mesosphere.com/browse/CORE-1291) Increase the value for `--recovery_timeout` agent flag in DC/OS
> Increase recovery timeout in agent config.

- cloud_images/centos7/install_prereqs.sh
- dcos_installer/action_lib.py
Update the `docker-engine` packages pulled by CentOS to `17.05.0.ce` (latest).
> Update CentOS Docker packages

- gen/calc.py
- gen/dcos-config.yaml
- gen/tests/test_validation.py
This adds two `config.yaml` parameters that can override the location of the work directory for Mesos masters and agents: `mesos_master_work_dir` and `mesos_agent_work_dir`.
- [DCOS_OSS-1586](https://jira.mesosphere.com/browse/DCOS_OSS-1586) Configurable Mesos work dir location
> Add Mesos work dir config params

- packages/adminrouter/extra/src/Makefile.common
- packages/adminrouter/extra/src/docs/api/nginx.master.html
- packages/adminrouter/extra/src/docs/api/nginx.master.yaml
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/lib/auth/open.lua
- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/test-harness/tests/test_auth.py
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
- packages/adminrouter/extra/src/test-harness/tests/test_service.py
All requests originating from the Admin Router must have the User-Agent header properly set. As part of this PR the `/internal/acs/api/v1/` endpoint has been moved into the shared `master.conf` file. This way we deduplicate the code a bit and keep the change DRY without changing the behaviour of AR.
Additionally, a small change to Makefile is introduced - the DNS server used for hostnames resolving inside the container defaults now to Google's servers (`8.8.8.8` and `8.8.4.4`) unless it's overridden by the `LOCAL_DNS` environment variable. The previous auto-detection approach did not work in networks with external gateways/routers as there is no host-local DNS there.
- https://jira.mesosphere.com/browse/DCOS_OSS-1445 `Admin Router: AR should set unique user agent while doing requests to …
> Admin Router: Make AR send proper `User-Agent` header

- packages/mesos-modules/buildinfo.json
- packages/mesos/README.md
- packages/mesos/buildinfo.json
Bumps Mesos and mesos-modules to the HEAD of their `master` branches.
- [MESOS-8014](https://issues.apache.org/jira/browse/MESOS-8014) Provide HTTP authenticatee interface re/usable for the scheduler library.
- ...
> Bumped Mesos and mesos-modules to master.

- mergebot-config.json
```
@mesosphere-megebot merge-it
```
Will enabled automated merging of open `dcos/dcos` and corresponding `mesosphere/dcos-enterprise` PR.  Only [owners](https://github.com/dcos/dcos/blob/master/owners.json) will be able to issue the command, and all status checks **must-be** green in-order for the bot to merge-it.
> Enable @mesosphere-mergebot merge-it

- gen/calc.py
- gen/dcos-config.yaml
- packages/cosmos/build
- packages/cosmos/buildinfo.json
- packages/dcos-integration-test/extra/test_endpoints.py
Enterprise Cosmos doesn't need a object store any more as this functionality is moved to package registry. Remove object store configuration from DC/OS. The current `cosmos` `master` ignores this flags, and this PR removes those unused flags from dcos.
- [DCOS-18769](https://jira.mesosphere.com/browse/DCOS-18769) Remove object store configuration from DC/OS.
https://github.com/dcos/dcos/blob/master/packages/dcos-integration-test/extra/test_endpoints.py#L158
___
All PRs …
> Remove cosmos object storage
