- packages/dcos-oauth/buildinfo.json
This PR bumps dcos-oauth to increase the ZooKeeper connection timeout from 1s to 60s. It also includes a bump from Go 1.6 to Go 1.7.
- [DCOS_OSS-1788](https://jira.mesosphere.com/browse/DCOS_OSS-1788) Flakey Integration Test Failures on dcos-docker: 500 Server Error
___
> dcos-oauth: bump for increased zk connection timeout

- cloud_images/CHANGELOG.md
- cloud_images/centos7/create_base_ami.sh
- cloud_images/centos7/create_dcos_ami.sh
- cloud_images/centos7/install_prereqs.sh
- cloud_images/centos7/packer.json
- gen/build_deploy/aws.py
Screwed up a rebase on the original PR https://github.com/dcos/dcos/pull/1961. See comments over there for what was done to test these. 
Doing this via changing the build scripts in the cloud_images dcos package to read in environment variable for `CENTOS_VERSION`.
- Defaults to 7.4.1708 (initial hard-coded value) in scripts, and is also set to 7.4 in TeamCity.
Manually-kicked-off CI job that created the DC/OS-ready AMIs:
https://teamcity.mesosphere.io/repository/download/DcosIo_Dcos_BuildCloudBaseImages_AwsBuildAndPublishCentOS7baseImage/798303:id/cloud_images/centos7/artifacts.txt
GovCloud DC/OS-ready AMIs generated with https://teamcity.mesosphere.io/viewLog.html?buildId=816581&tab=buildResultsDiv&buildTypeId=DcosIo_Dcos_BuildCloudBaseImages_AwsBuildAndPublishCentOS7baseImagesForGovclou …
> Update CentOS AMIs to version 7.4-1708

- dcos_installer/test_backend.py
- gen/calc.py
This reverts commit 6771ccf3245e58ea8cd188bac8112db0fd6732d6.
* https://jira.mesosphere.com/browse/RELEASE-33 
The version string should be 1.10.1
> 1.10.1 version string should be 1.10.1.

- Jenkinsfile
This PR adjust project's Jenkinsfiles in order to support the new way in which `sec-ci-lib` is called. 
In order to enable other teams to reuse `sec-ci-lib`, both slack channel and slack token ID must be passed as the parameter. This also requires a new approach on versioning `sec-ci-lib` libs - see the discussion in https://github.com/mesosphere/sec-ci-libs/pull/5 for more details.
- [INCIDENT-156](https://jira.dcos.io/browse/INCIDENT-156) Changes to seclibs blocked merges to dcos/dcos, dcos-enterprise, master, 1.10 and 1.9
`sec-ci-libs` PR that introduces the breaking change: https://github.com/mesosphere/sec-ci-libs/pull/5
DC/OS EE PR: https://github.com/mesosphere/dcos-enterprise/pull/1647
> Jenkinsfile: sec-ci-libs version pinning 

- dcos_installer/action_lib.py
Fixes multiple bugs and UX issues with the GUI and CLI installer.
- Enable errexit, nounset, and pipefail (exit when there's a problem)
- Add progress messages for easier debugging
- Validate CentOS/RHEL >= 7.2 (or CoreOS)
- Validate Kernel >= 3.10.x (for minimal overlayfs support)
- Validate overlayfs kernel module (or enable and load)
- Validate Docker >= 1.11 (if installed)
- Validate Docker Data Root (default /var/lib/docker) was provisioned with `ftype=1` if FS is XFS (to avoid known bug with ftype=0)
- Only yum install utilities if not found (print version if already installed)
- Only install Docker (17.05.0.ce) if not found (print version if already installed)
- Validate nogroup linux group (or create)
- Remove obsolete `/opt/dcos-prereqs.installed` file (all steps skipped if …
> Enhance install-prereqs

- owners.json
- DCOS_OSS-1793 - Expand owners. json
**A concept of owners for dcos/dcos**
In dcos/dcos repo, we have owners.json file which gives the members certain privileges equivalent to being a committer of the repo. 
An owner can
* Test Enterprise Update for any PR.  Owner is authorized to do bump-ee on any PR.
* Can add a “ship-it” label manually, thereby including PR to an integration train. This is useful when we to override mergebot automated process.
* Could merge a train or PR to repo with a “merge-it” command.
As we expand mergebot capabilities, owners can delegate many committer-like operations to bot, and concentrate on important work like reviewing PRs and reviewing Integration Tests for DCOS.
If you are tech-lead of the component/team, and you submit or review PRs to dcos/dcos repo, …
> Updating Owners.json

- dcos_installer/backend.py
- gen/__init__.py
- gen/calc.py
- gen/dcos-config.yaml
- gen/internals.py
- gen/tests/test_config.py
- gen/tests/test_internals.py
- packages/dcos-integration-test/extra/test_helpers.py
This adds support for tagging gen config variables as "secret", which removes them from diagnostics bundles and build output.
Secret variables are omitted from `/opt/mesosphere/etc/expanded.config.json`, and their values are masked in `/opt/mesosphere/etc/user.config.yaml` and when they're printed to the console. New files `/opt/mesosphere/etc/user.config.full.yaml` and `/opt/mesosphere/etc/expanded.config.full.json` are added which include secret variables, and these files are only readable by root. 
This also tags some existing config variables as secret:
* `cluster_docker_credentials`
* `exhibitor_admin_password`
* `aws_template_storage_access_key_id`
* `aws_template_storage_secret_access_key`
- [DCOS_OSS-1795](https://jira.mesosphere.com/browse/DCOS_OSS-1795) Sensitive config values …
> Remove sensitive config values from diagnostics bundles and build output

- packages/openssl/build
The TLS compression is vulnerable to MITM attack known as [CRIME](https://en.wikipedia.org/wiki/CRIME). This PR disables support for TLS compression in `openssl` library. None of the components using the `openssl` will be able to run TLS compressed connection.
- [DCOS-19390](https://jira.mesosphere.com/browse/DCOS-19390) Disable TLS compression for mesos TLS interface
> openssl: Disable TLS compression

- packages/openssl/build
This is a backport of https://github.com/dcos/dcos/pull/2073
Backport JIRA: https://jira.mesosphere.com/browse/DCOS-19452
The TLS compression is vulnerable to MITM attack known as [CRIME](https://en.wikipedia.org/wiki/CRIME). This PR disables support for TLS compression in `openssl` library. None of the components using the `openssl` will be able to run TLS compressed connection.
- [DCOS-19390](https://jira.mesosphere.com/browse/DCOS-19390) Disable TLS compression for mesos TLS interface
> openssl: Disable TLS compression [1.10]

- packages/marathon/buildinfo.json
- [MARATHON-7790](https://jira.mesosphere.com/browse/MARATHON-7790) Migrate UnreachableStrategy Saved in Instances
- Change `Int.MaxValue` to 8 for maximum concurrency during migration (#5676) (#5701)
- [MARATHON-7848](https://jira.mesosphere.com/browse/MARATHON-7848) Allow underscore for network names (#5687)
- [MARATHON-7788](https://jira.mesosphere.com/browse/MARATHON-7788) Store a flag node in ZK to indicate that Marathon performs data migration (#5662)
- [MARATHON-7852](https://jira.mesosphere.com/browse/MARATHON-7852) Switch to use Debian Slim base image (#5668)
- Extend the set of command-line flags returned by /v2/info (#5612)
- …
> Marathon 1.5.2 bump

- gen/calc.py
This change enables the `cgroups/blkio` isolator in Mesos agent. For now the `cgroups/blkio` isolator only supports collecting blkio subsystem statistics, see https://issues.apache.org/jira/browse/MESOS-6162 for details.
- [DCOS_OSS-1749](https://jira.mesosphere.com/browse/DCOS_OSS-1749) Enable blkio cgroup subsystem for dcos.
- [MESOS-6162](https://issues.apache.org/jira/browse/MESOS-6162) Add support for cgroups blkio subsystem blkio statistics.
> Enabled the `cgroups/blkio` isolator.

- packages/dcos-integration-test/extra/test_networking.py
- [DCOS-13978](https://jira.mesosphere.com/browse/DCOS-13978) minuteman tests for pods
___
* Developers responsible for code that interacts with or …
> Adds vip test for pods

- packages/openssl/build
This is a backport of https://github.com/dcos/dcos/pull/2073
Backport JIRA: https://jira.mesosphere.com/browse/DCOS-19453
The TLS compression is vulnerable to MITM attack known as [CRIME](https://en.wikipedia.org/wiki/CRIME). This PR disables support for TLS compression in `openssl` library. None of the components using the `openssl` will be able to run TLS compressed connection.
- [DCOS-19390](https://jira.mesosphere.com/browse/DCOS-19390) Disable TLS compression for mesos TLS interface
> openssl: Disable TLS compression [1.9]

- README.md
- packages/adminrouter/extra/src/Makefile.common
- packages/dcos-integration-test/extra/util/run_integration_test.sh
- test_util/run-all
- tox.ini
[pytest project](https://docs.pytest.org/en/latest/changelog.html) recommends `pytest` entry point over `py.test`. (https://github.com/pytest-dev/pytest/issues/1629, https://github.com/pytest-dev/pytest/pull/1633) 
```
Introduce pytest command as recommended entry point. Note that py.test still works and is not scheduled for removal. Closes proposal #1629. Thanks @obestwalter and @davehunt for the complete PR (#1633).
```
> Rename py.test to pytest

- PULL_REQUEST_TEMPLATE.md
This is a follow-up pull request on the discussion that arised in https://github.com/dcos/dcos/pull/2000. This PR intends to supersede #2000.
The `Corresponding DC/OS tickets` section is meant to simplify the work of closing tickets right after merging a PR. The hope is that this section makes it more likely that every pull request has at least one such ticket associated, easily discoverable from the PR description. This paves the pathway towards a workflow in which we are auto-closing tickets upon merge.
>  PR template: add "Corresponding DC/OS tickets" section, cosmetic updates

- packages/marathon/buildinfo.json
Latest build of Marathon 1.6 Dev
- [MARATHON-7916](https://jira.mesosphere.com/browse/MARATHON-7916) Release Latest Marathon to DCOS 1.11
- Simplify LeaderElection 
- Change `Int.MaxValue` to 8 for maximum concurrency
- Introduction of Workload Bursting 
- Allow underscore for network names
- Improved Reliability for Persistence Migration
> Bump marathon to 1.6 dev

- gen/dcos-config.yaml
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/includes/server/open/master.conf
- packages/dcos-integration-test/extra/test_composition.py
- packages/exhibitor/build
- packages/exhibitor/buildinfo.json
- packages/exhibitor/extra/dcos-exhibitor.service
- packages/exhibitor/extra/set_exhibitor_file_permissions.py
- packages/exhibitor/extra/start_exhibitor.py
**This PR revives  https://github.com/dcos/dcos/pull/1984 - please see the original for context and great discussions.**
This PR bumps Exhibitor and adds bootstrap infrastructure for Exhibitor TLS support in DC/OS Enterprise. It also makes the `/exhibitor/exhibitor/v1/cluster/status` an unauthenticated endpoint.
- [DCOS-17894](https://jira.mesosphere.com/browse/DCOS-17894) Encrypt & authenticate cross-Exhibitor communication (1.11)
- [DCOS_OSS-1545](https://jira.mesosphere.com/browse/DCOS_OSS-1545) Admin Router: Investigate whether `/exhibitor/v1/cluster/status` still needs to be unathenticated
___
> Added exhibitor TLS conf

- gen/aws/templates/advanced/advanced-master.json
- gen/aws/templates/advanced/advanced-priv-agent.json
- gen/aws/templates/advanced/advanced-pub-agent.json
- gen/build_deploy/aws.py
- packages/dcos-integration-test/extra/test_packaging.py
Advanced (Zen) CloudFormation instances require that some DC/OS
prerequisites be installed; this PR creates a mapping to `prereq`
images for `el7` and references them in master and agent CF templates.
> `prereq` images for advanced (zen) CF templates

- packages/openssl/buildinfo.json
This bumps OpenSSL from 1.0.2k to 1.0.2m. See https://www.openssl.org/news/cl102.txt.
https://jira.mesosphere.com/browse/DCOS_OSS-1882
> openssl: bump to 1.0.2m

- packages/java/buildinfo.json
This PR bump Java to the latest patchlevel.
- [DCOS-19649](https://jira.mesosphere.com/browse/DCOS-19649)  `Update DC/OS Java JDK 8 to latest version (DC/OS 1.9.6)`
EE Bump: https://github.com/mesosphere/dcos-enterprise/pull/1759
> java: bump java package to the latest patchlevel

- packages/java/buildinfo.json
- packages/mesos/buildinfo.json
- packages/openssl/buildinfo.json
* #2104 - Bumped Mesos to latest 1.2.x (f8706e5).
* #2130 - java: bump java package to the latest patchlevel
* #2122 -  openssl: bump to 1.0.2m
> 1.9 train 265

- packages/adminrouter/docker/requirements-tests.txt
Due to the changes in the latest pytest, there seems to be a conflict in command line arguments. This PR pins pytest to 3.0.4 just like it was pinned for 1.10 and current master.
- https://jira.mesosphere.com/browse/DCOS_OSS-1910 `Admin Router: pin pytest for 3.0.4`
DC/OS EE PR: https://github.com/mesosphere/dcos-enterprise/pull/1777
> Admin Router: Pin pytest

- packages/adminrouter/extra/src/Makefile.common
This PR enables more robust devkit building.
As DCOS-19707 has shown, in some rare cases it is possible that the intermediate devkit container still lingers while the next CI is launched on the Agent. Changes made here should prevent it from happening for both gen_extra and Admin Router devkits.
Even though this PR only touches/changes Admin Router Makefile, I have named both EE and Open PRs the same for clarity. The EE PR adjusts the `gen_extra` devkit, the EE Admin Router's Makefile inherits the changes from the Open Adminrouter's one.
See the Jira and its comments for more details.
* https://jira.mesosphere.com/browse/DCOS-19707 `continuous-integration/jenkins/pr-head fails on seemingly unrelated changes`
EE DC/OS PR: https://github.com/mesosphere/dcos-enterprise/pull/1784
> Admin Router: more robust devkit building

- packages/dcos-integration-test/extra/test_dcos_log.py
Fix a race condition by adding a health check to deployed marathon tasks.
- [DCOS_OSS-1932](https://jira.mesosphere.com/browse/DCOS_OSS-1932)
N/A
___ …
> fix race condition in dcos-log integration test

- packages/dcos-integration-test/extra/test_dcos_log.py
- packages/dcos-net/buildinfo.json
- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
Mesos is now bumped to the latest master (ae08193).
- Bumped Mesos to latest master (apache/mesos@ae08193).
- Bumped dcos-mesos-modules to latest master (dcos/dcos-mesos-modules@6ffea42)
- Bumped dcos-net to handle TASK_STARTING: https://github.com/dcos/dcos-net/pull/21
- [DCOS_OSS-1912](https://jira.mesosphere.com/browse/DCOS_OSS-1912) Bump mesos and mesos-modules packages to latest master
- [DCOS_OSS-1924](https://jira.mesosphere.com/browse/DCOS_OSS-1924) Same set of tests fails reproducibly with current Mesos bump PR
- [DCOS_OSS-1932](https://jira.mesosphere.com/browse/DCOS_OSS-1932) flaky test test_dcos_log.test_log_v2_api
If you are changing components or packages in DC/OS (e.g. you are bumping …
> Bumped Mesos and mesos-modules.

- packages/exhibitor/buildinfo.json
Bump Exhibitor for:
- AWS SDK setting of region, with support for endpoint override.
- Enable specifying the Endpoint Suffix in the azure connection string
- [DCOS_OSS-1940](https://jira.mesosphere.com/browse/DCOS_OSS-1940) exhibitor: bump aws sdk version to support unpublished govcloud regions
- [DCOS_OSS-1941](https://jira.mesosphere.com/browse/DCOS_OSS-1941) exhibitor: enable specifying the Endpoint Suffix in the azure connection string
None that I am aware of at this time.
> Bump exhibitor to update aws sdk version to support unpublished govcloud regions

- LICENSE
- NOTICE
- gen/build_deploy/bash.py
- packages/adminrouter/extra/src/LICENSE
- packages/dcos-image/build
Inclusion of LICENSE, NOTICE file in dcos-image.
JIRA Ticket: https://jira.mesosphere.com/browse/COPS-2050 
Michael Beisiegel is working with Google to include DC/OS in Google Cloud Partership program https://cloud.google.com/partners/join/ and provide a launcher here https://cloud.google.com/launcher/ for DCOS.
As part of the requirement, we need to our LICENSE file and LICENSE information of components that we include should be made available in the installation. 
With this change, we will have the LICENSE and NOTICE file in
/opt/mesosphere/etc/ folder in the installation.
@branden and I discussed and we realized that this is simplest way to ship these files across all our installations (on-prem, aws, azure, etc)
NOTICE file update adheres the style adopted by other projects such as:
* …
> Include LICENSE and NOTICE in dcos-image

- LICENSE
- NOTICE
- gen/build_deploy/bash.py
- packages/adminrouter/extra/src/LICENSE
- packages/dcos-image/build
- packages/exhibitor/buildinfo.json
- packages/marathon/buildinfo.json
#2060 - Bump exhibitor to update aws sdk version to support unpublished govcloud regions
#2128 - Include LICENSE and NOTICE in dcos-image
#2157 - Marathon 1.6 Beta Release
> Train 274 (master)

- packages/mesos/build
- packages/mesos/buildinfo.json
- Bumped Mesos to latest master (apache/mesos@6dfb749).
- Enabled gRPC support to use storage features (i.e. CSI) with Mesos. These features are not enabled by default but compiling with gRPC makes it possible to enable them.
- [DCOS_OSS-1945](https://jira.mesosphere.com/browse/DCOS_OSS-1945) Bump mesos just before Beta freeze and enable gRPC support.
> Bumped Mesos and enabled gRPC support.

- packages/dcos-ui/buildinfo.json
This is train 276 targeted for the 1.11 release. It contains the following pull requests:
- #2170 (chore(dcos-ui): update package to 1.11.0-rc.4)
> Train 276 (master)

- dcos_installer/test_backend.py
- gen/calc.py
This changes the DC/OS version for the upcoming 1.10.3 release.
https://jira.mesosphere.com/browse/DCOS_OSS-1966
> Bump DC/OS version to 1.10.3

- dcos_installer/test_backend.py
- gen/calc.py
This is train 278 for the 1.10.3 release. It contains:
- #2178 (Bump DC/OS version to 1.10.3)
> Train 278 (1.10)

- gen/build_deploy/aws.py
This PR is a cherry-picked commit backport to update AMI IDs which include a fix to a `dcos_vol_setup` bug which is sometimes breaking `cronyd` and `navstar`.  Related JIRA is [DCOS_OSS-1043](https://jira.mesosphere.com/browse/DCOS_OSS-1043).
> (1.10 backport) Update EL7 AMI IDs

- packages/metronome/buildinfo.json
* Upgraded to a released version of Marathon Lib [v1.3.13](https://github.com/mesosphere/marathon/releases/tag/v1.3.13)
* Updates to dependencies (including an Akka update to fix [schedule time wrap around bug](https://github.com/akka/akka/issues/20424))
* Added `/info` end point for metronome version information
* [PR150](https://github.com/dcos/metronome/pull/150) Added `/info` endpoint
* [MARATHON_EE-1717](https://jira.mesosphere.com/browse/MARATHON_EE-1717) 60s min between reschedules
* [MARATHON_EE-1725](https://jira.mesosphere.com/browse/MARATHON_EE-1725) 
* [MARATHON_EE-1726](https://jira.mesosphere.com/browse/MARATHON_EE-1726) Upgrade Marathon libraries and dependencies  …
> bumping metronome to 0.3.1

- gen/dcos-config.yaml
- Enabled UCR auto image gc for dc/os.
- This PR builds on top of [pull/2165](https://github.com/dcos/dcos/pull/2165)([DCOS_OSS-1945](https://jira.mesosphere.com/browse/DCOS_OSS-1945)).
- [DCOS_OSS-1933](https://jira.mesosphere.com/browse/DCOS_OSS-1933) Enable UCR basic auto image GC for DC/OS.
- [DCOS_OSS-1945](https://jira.mesosphere.com/browse/DCOS_OSS-1945) Bump mesos just before Beta freeze.
> Enabled UCR auto image gc for DC/OS.

- LICENSE
- NOTICE
- gen/build_deploy/bash.py
- packages/adminrouter/extra/src/LICENSE
- packages/dcos-image/build
Backport changes from #2128 to 1.9 branch
JIRA Ticket: https://jira.mesosphere.com/browse/COPS-2050
> backport to 1.9 -  Include LICENSE, NOTICE file in dcos-image

- LICENSE
- NOTICE
- gen/build_deploy/bash.py
- packages/adminrouter/extra/src/LICENSE
- packages/dcos-image/build
#2185 backport to 1.9 - Include LICENSE, NOTICE file in dcos-image
> Train 282 (base:1.9)

- gen/build_deploy/bash.py
- gen/dcos-services.yaml
This allows onprem installations on hosts with a premade (and empty) `/opt/mesosphere/`.
- [DCOS_OSS-1587](https://jira.mesosphere.com/browse/DCOS_OSS-1587) Support DC/OS install on non-root LVM volume
> Install to an existing install directory if it's empty

- packages/dcos-integration-test/extra/test_networking.py
We have an 'assertion' in tests which check if the number of slaves > 2.
* https://jira.mesosphere.com/browse/DCOS_OSS-1977
Instead of asserting the requirement, we should skip the tests as not applicable.
> Skip the ip_per_container test when the number of slaves is less than 2.

- packages/metronome/buildinfo.json
* Upgraded to a released version of Marathon Lib [v1.3.13](https://github.com/mesosphere/marathon/releases/tag/v1.3.13)
* Updates to dependencies (including an Akka update to fix [schedule time wrap around bug](https://github.com/akka/akka/issues/20424))
* Added `/info` end point for metronome version information
* [PR150](https://github.com/dcos/metronome/pull/150) Added `/info` endpoint
* [MARATHON_EE-1717](https://jira.mesosphere.com/browse/MARATHON_EE-1717) 60s min between reschedules
* [MARATHON_EE-1725](https://jira.mesosphere.com/browse/MARATHON_EE-1725) 
* [MARATHON_EE-1726](https://jira.mesosphere.com/browse/MARATHON_EE-1726) Upgrade Marathon libraries and dependencies  …
> bump to metronome 0.3.1 on DCOS 1.9

- gen/calc.py
- packages/dcos-checks/build
- packages/dcos-checks/buildinfo.json
- packages/dcos-checks/extra/dcos-checks-poststart.service
- packages/dcos-checks/extra/dcos-checks-poststart.timer
- packages/dcos-integration-test/extra/test_composition.py
Adding node poststart checks as a systemd unit. 
This will be followed by one for prestart and cluster checks. 
Include the checks component update. Diff specified in the checklist below. We had to make a change to the checks component to exclude this systemd unit from the component check. 
https://jira.mesosphere.com/browse/DCOS_OSS-1408
___ …
> Add poststart check as a systemd unit

- packages/mesos/buildinfo.json
Bump Mesos to latest master, to pick up storage-related (CSI/SLRP) changes, and others.
- [DCOS_OSS-1970](https://jira.mesosphere.com/browse/DCOS_OSS-1970) Bump mesos to pre-1.5.0 in preparation for beta3
> Bump Mesos to latest master

- packages/metronome/buildinfo.json
* Upgraded to a released version of Marathon Lib [v1.3.13](https://github.com/mesosphere/marathon/releases/tag/v1.3.13)
* Updates to dependencies (including an Akka update to fix [schedule time wrap around bug](https://github.com/akka/akka/issues/20424))
* Added `/info` end point for metronome version information
* [PR150](https://github.com/dcos/metronome/pull/150) Added `/info` endpoint
* [MARATHON_EE-1717](https://jira.mesosphere.com/browse/MARATHON_EE-1717) 60s min between reschedules
* [MARATHON_EE-1725](https://jira.mesosphere.com/browse/MARATHON_EE-1725) 
* [MARATHON_EE-1726](https://jira.mesosphere.com/browse/MARATHON_EE-1726) Upgrade Marathon libraries and dependencies  …
> bump metronome 0.3.1

- packages/dcos-test-utils/buildinfo.json
It should address this:
*test_composition.test_dcos_cluster_is_up seems to be instable* 
* https://jira.mesosphere.com/browse/DCOS-19925 
Backports this change:
https://github.com/dcos/dcos/pull/2109
Essentially brings dcos-test-utils up to date with the current `master`
https://github.com/dcos/dcos/blob/master/packages/dcos-test-utils/buildinfo.json
> 1.10 backport - Update dcos-test-utils

- packages/mesos/buildinfo.json
Bump Mesos to latest master, to pick up storage-related (CSI/SLRP) changes, and others.
- [DCOS_OSS-1970](https://jira.mesosphere.com/browse/DCOS_OSS-1970) Bump mesos to pre-1.5.0 in preparation for beta3
- [MESOS-7235](https://issues.apache.org/jira/browse/MESOS-7235) Resource Provider and CSI
- [DCOS-13242](https://jira.mesosphere.com/browse/DCOS-13242) Resource Provider (RP) abstraction in Mesos
- [DCOS-13241](https://jira.mesosphere.com/browse/DCOS-13241) Container Storage Interface
> Bump dcos-mesos to latest master a4b1134.

- dcos_installer/action_lib.py
- packages/mesos/buildinfo.json
This is Train 291, against the `master` branch. It contains the following pull requests:
- #2058 (Fixed detection of CoreOS and overlay issues with `systemd-networkd`)
- #2046 (Bump dcos-mesos to latest master a4b1134)
> Train 291 (master)

- packages/python-gunicorn/buildinfo.json
- packages/python-kazoo/buildinfo.json
This bumps gunicorn (a WSGI server) and kazoo (a ZooKeeper client).
Both Python libraries are used by various DC/OS components. The new versions bring along quite a few patches for corner-case production issues. See JIRA tickets for details.
https://jira.mesosphere.com/browse/DCOS_OSS-1896
https://jira.mesosphere.com/browse/DCOS_OSS-2001
> Bump pkgpanda pkgs kazoo and gunicorn

- packages/marathon/buildinfo.json
- Persistent volumes for pods.
- CSI volume profiles for both apps and pods.
- Security fixes.
- A lot of Marathon dependencies are updated.
- Pass killGracePeriodSeconds value to Mesos for pods.
- Performance optimizations.
- Various fixes and improvements.
- [MARATHON-7952](https://jira.mesosphere.com/browse/MARATHON-7952) - killGracePeriodSeconds field does nothing in pods
- [MARATHON-7917](https://jira.mesosphere.com/browse/MARATHON-7917) - Upgrade and Revisit Our Dependencies!
- [MARATHON-7974](https://jira.mesosphere.com/browse/MARATHON-7974) - Covariance Contravariance Confusion (CCC)
- [MARATHON_EE-1735](https://jira.mesosphere.com/browse/MARATHON_EE-1735) - Persistence volumes for pods
- …
> Update Marathon (Persistent volumes, optimizations and more)

- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-metrics/buildinfo.json
This PR brings the version of dcos-metrics in DC/OS up to date with the current dcos-metrics master. The two significant changes here both add new metrics to the </containers/container-id> endpoint in dcos-metrics. 
Note that there is a lot of activity in the changelog linked below, all related to plugins and documentation. 
- [DCOS_OSS-1607](https://jira.mesosphere.com/browse/DCOS_OSS-1607) Add container resource utilisation metrics
- [DCOS_OSS-1489](https://jira.mesosphere.com/browse/DCOS_OSS-1489) Support cgroup blkio statistics in dcos-metrics.
- [DCOS-19920](https://jira.mesosphere.com/browse/DCOS-19920) Update vendored …
> Bump dcos-metrics sha

- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-metrics/buildinfo.json
This PR introduces a Prometheus producer on each node (successor to #2239). 
- [DCOS_OSS-19849](https://jira.mesosphere.com/browse/DCOS_OSS-19849) Add a Prometheus endpoint to dcos-metrics
> Bump DC/OS metrics sha (introduces Prometheus endpoint)

- packages/dcos-test-utils/buildinfo.json
* CLI binary is now configurable
* users must opt-in to having the test fixture assume the cluster composition
https://jira.mesosphere.com/browse/DCOS-17702
___
It is best to …
> Bump dcos-test-utils to point at master

- packages/metronome/buildinfo.json
- taskKillGracePeriod - [METRONOME-151](https://jira.mesosphere.com/browse/METRONOME-151)  Allow for a configurable number of seconds for a task to die before a SIGKILL is sent.
- forcePullImage for Docker images - [METRONOME-148](https://jira.mesosphere.com/browse/METRONOME-148)  Ensures that an image is pulled regardless if it exists locally
-  Security issue - [METRONOME-185](https://jira.mesosphere.com/browse/METRONOME-185) non superuser was not able to retrieve a job run based on runid
-  Security issue - [METRONOME-185](https://jira.mesosphere.com/browse/METRONOME-185) non superuser was not able to retrieve a job run based on runid …
> metronome 0.3.2 bump for DCOS 1.10

- packages/mesos/buildinfo.json
This change bumps Mesos beyond 1.4.1. It includes several critical and important bugfixes in Mesos.
- [DCOS_OSS-2012](https://jira.mesosphere.com/browse/DCOS_OSS-2012) Bump Mesos to post 1.4.1 in DC/OS 1.10.4.
- [MESOS-7873](https://issues.apache.org/jira/browse/MESOS-7873) - Expose `ExecutorInfo.ContainerInfo.NetworkInfo` in Mesos `state` endpoint.
- [MESOS-7921](https://issues.apache.org/jira/browse/MESOS-7921) - ProcessManager::resume sometimes crashes accessing EventQueue.
- [MESOS-7926](https://issues.apache.org/jira/browse/MESOS-7926) Abnormal termination of default executor can cause MesosContainerizer::destroy to fail.
- …
> Bumped Mesos package to 1.4.x head 732c49e.

- packages/marathon/buildinfo.json
- [MARATHON-7974](https://jira.mesosphere.com/browse/MARATHON-7974) Fixes a security concern for a non super user.  It was discovered that permissions for GroupResources was not honored and is now resolved.
- [MARATHON-7919](https://jira.mesosphere.com/browse/MARATHON-7919) Fix byte stream blocking on proxy of non-leader buffers 
> marathon 1.5.5 bump

- dcos_installer/test_backend.py
- gen/calc.py
- packages/bootstrap/extra/dcos_internal_utils/exhibitor.py
- packages/dcos-test-utils/buildinfo.json
- packages/marathon/buildinfo.json
- packages/mesos/buildinfo.json
- packages/metronome/buildinfo.json
Includes:
#2212 - bootstrap: More robust handling of a zk.pid file while waiting for exhibitor 
#2229 - Bump dcos-test-utils to point at master
#2243 - metronome 0.3.2 bump for DCOS 1.10
#2246 - Update version to 1.10.4
#2250 - Bumped Mesos package to 1.4.x head 732c49e
#2253 - marathon 1.5.5 bump
> Train 298 for 1.10.4

- packages/metronome/buildinfo.json
- taskKillGracePeriod - [METRONOME-151](https://jira.mesosphere.com/browse/METRONOME-151)  Allow for a configurable number of seconds for a task to die before a SIGKILL is sent.
- forcePullImage for Docker images - [METRONOME-148](https://jira.mesosphere.com/browse/METRONOME-148)  Ensures that an image is pulled regardless if it exists locally
-  Security issue - [METRONOME-185](https://jira.mesosphere.com/browse/METRONOME-185) non superuser was not able to retrieve a job run based on runid
-  Security issue - [METRONOME-185](https://jira.mesosphere.com/browse/METRONOME-185) non superuser was not able to retrieve a job run based on runid …
> metronome 0.3.2 bump for DCOS 1.9

- packages/metronome/buildinfo.json
- taskKillGracePeriod - [METRONOME-151](https://jira.mesosphere.com/browse/METRONOME-151)  Allow for a configurable number of seconds for a task to die before a SIGKILL is sent.
- forcePullImage for Docker images - [METRONOME-148](https://jira.mesosphere.com/browse/METRONOME-148)  Ensures that an image is pulled regardless if it exists locally
-  Security issue - [METRONOME-185](https://jira.mesosphere.com/browse/METRONOME-185) non superuser was not able to retrieve a job run based on runid
-  Security issue - [METRONOME-185](https://jira.mesosphere.com/browse/METRONOME-185) non superuser was not able to retrieve a job run based on runid …
> metronome 0.3.2 bump for dcos 1.11

- packages/metronome/buildinfo.json
- [DCOS_OSS-2026](https://jira.mesosphere.com/browse/DCOS_OSS-2026) Bump Metronome v0.3.3 Release on DCOS 1.10
- [METRONOME-188](https://jira.mesosphere.com/browse/METRONOME-188) Updated to Protocol Buffers v.3.3.0
- [METRONOME-196](https://jira.mesosphere.com/browse/METRONOME-196) ForcePullImage should not be required
> Metronome 0.3.3 bump on DCOS 1.10

- packages/mesos-dns/buildinfo.json
Added capability in `mesos-dns` of providing DC/OS version it was
validated against.
Currently the `mesos-dns` that comes with DC/OS only returns the version as `dev` when users invoke the `mesos-dns --version` command. This is confusing to users. To fix this we are now going to maintain DC/OS version specific branches in `mesos-dns` and the `mesos-dns` binaries of these branches is going to return the DC/OS version number as its version. 
https://jira.mesosphere.com/browse/DCOS_OSS-1990
- [DCOS_OSS-1990](https://jira.mesosphere.com/browse/DCOS_OSS-1990) 
- [*] Read the [DC/OS contributing …
> Bumped `mesos-dns`.

- gen/__init__.py
- gen/build_deploy/bash.py
- gen/build_deploy/util.py
This fixes an error where, when custom check bins are provided, the installer will attempt to copy the custom check bins package from the Docker container's artifact cache, and fail with an error when it can't find it. This is accomplished by adding the package to the gen result's list of generated stable artifacts, which are skipped when copying artifacts. This error was introduced in bf2032fb4fdf5fc31fa0d79f860b9d0d45255a23.
This also includes a followup refactor, see commits.
- [DCOS_OSS-1982](https://jira.mesosphere.com/browse/DCOS_OSS-1982) genconf fails when custom check bins are provided …
> Fix error when custom check bins are provided during onprem install

- packages/bootstrap/extra/dcos_internal_utils/exhibitor.py
It is a backport of https://github.com/dcos/dcos/pull/2212
> bootstrap: More robust handling of a zk.pid file while waiting for exhibitor[1.9]

- packages/metronome/buildinfo.json
- [DCOS_OSS-2036](https://jira.mesosphere.com/browse/DCOS_OSS-2036) Bump Metronome v0.3.3 Release on DCOS 1.11
- [METRONOME-188](https://jira.mesosphere.com/browse/METRONOME-188) Updated to Protocol Buffers v.3.3.0
- [METRONOME-196](https://jira.mesosphere.com/browse/METRONOME-196) ForcePullImage should not be required
> bump metronome 0.3.3 on dcos 1.11

- packages/bootstrap/extra/dcos_internal_utils/exhibitor.py
It is a backport of https://github.com/dcos/dcos/pull/2212
> bootstrap: More robust handling of a zk.pid file while waiting for exhibitor[master]

- gen/dcos-config.yaml
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
bump dcos-diagnostics to the latest sha
The new features and bug fixes in dcos-diagnostics:
- improve error messages in diagnostics bundle `summaryErrorReport.log`
- handle error responses (non 200 code) when collecting logs for diagnostics bundle
- if the `summaryErrorReport.log` is empty, do not include this file into a diagnostics bundle
- update integration test to make sure there are no empty files in a diagnostics bundle
- remove history service endpoints from diagnostics bundle in OSS since it's running behind the adminrouter [now](https://github.com/dcos/dcos/commit/e2f986a49759a1109b17657b8a4753e1008a32c2#diff-ee8c631a232fb776584c0b43f493138e)
- …
> bump dcos diagnostics

- packages/adminrouter/extra/src/Makefile.common
- packages/adminrouter/extra/src/includes/http/common.conf
- packages/adminrouter/extra/src/includes/server/agent.conf
- packages/adminrouter/extra/src/nginx.agent.conf
- packages/adminrouter/extra/src/test-harness/modules/generic_test_code/generalised_tests.py
- packages/adminrouter/extra/src/test-harness/tests/open/test_generic.config.yml
- packages/adminrouter/extra/src/test-harness/tests/test_agent.py
- packages/adminrouter/extra/src/test-harness/tests/test_generic.config.yml
This PR minimizes the software version information disclosed by Nginx. It does that by:
* minimizes software version information in the `Server:` header of the HTTP reply,
* prevents agent Admin Router from serving Nginx default homepage - it should serve 404 instead
* minimizes software version information in the error pages served by Admin Router:
Please look below to see how the error pages changed. Previously it was:
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>openresty/1.13.6.1</center>
</body>
</html>
```
with `server_tokens` set to `off`: 
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
</body>
</html> …
```
> Admin Router: Minimizing software version information reported by the AR

- packages/dcos-integration-test/extra/test_metronome.py
- [DCOS_OSS-2036](https://jira.mesosphere.com/browse/DCOS_OSS-2036) Bump Metronome v0.3.3 Release on DCOS 1.11
- [METRONOME-188](https://jira.mesosphere.com/browse/METRONOME-188) Updated to Protocol Buffers v.3.3.0
- [METRONOME-196](https://jira.mesosphere.com/browse/METRONOME-196) ForcePullImage should not be required
> Add basic integration test for Metronome

- packages/dcos-oauth/buildinfo.json
This is a backport to 1.10 of https://github.com/dcos/dcos/pull/2038. Description from that:
> This PR bumps dcos-oauth to increase the ZooKeeper connection timeout from 1s to 60s. It also includes a bump from Go 1.6 to Go 1.7.
- [DCOS_OSS-2041](https://jira.mesosphere.com/browse/DCOS_OSS-2041) Integration Test Failure: test_applications.py::test_if_marathon_app_can_be_deployed_with_mesos_containerizer
> dcos-oauth: bump for increased zk connection timeout 1.9

- packages/adminrouter/extra/src/lib/auth/common.lua
- packages/adminrouter/extra/src/test-harness/tests/test_auth.py
This allows a client to use an alternative notation for the
authorization header:
`Authorization: Bearer TOKEN`
An example of clients using that notation is kubectl
- [KUB-115](https://jira.mesosphere.com/browse/KUB-115) Expose the Kubernetes API to adminrouter
___
* …
> adminrouter: add alternative authentication header

- packages/dcos-log/buildinfo.json
bump dcos-log sha
this PR fixes an issue where dcos-log would not release journald file descriptors
- [SOAK-52](https://jira.mesosphere.com/browse/SOAK-52)
- N/A
this fix was tested manually, unfortunately there is no easy way to test this with CI.
___ …
> bump dcos-log sha

- packages/adminrouter/extra/src/includes/http/common.conf
- packages/adminrouter/extra/src/includes/server/agent.conf
- packages/adminrouter/extra/src/nginx.agent.conf
- packages/adminrouter/extra/src/test-harness/modules/generic_test_code/generalised_tests.py
- packages/adminrouter/extra/src/test-harness/tests/open/test_generic.config.yml
- packages/adminrouter/extra/src/test-harness/tests/test_agent.py
- packages/adminrouter/extra/src/test-harness/tests/test_generic.config.yml
Just a backport of https://github.com/dcos/dcos/pull/2154
Jira issue: https://jira.mesosphere.com/browse/DCOS-19765 `Admin Router: port software version scrubbing from DCOS-19534 to 1.10`
> Admin Router: Minimizing software version information reported by the AR [1.10]

- packages/dcos-oauth/buildinfo.json
This is a backport to 1.10 of https://github.com/dcos/dcos/pull/2038. Description from that:
> This PR bumps dcos-oauth to increase the ZooKeeper connection timeout from 1s to 60s. It also includes a bump from Go 1.6 to Go 1.7.
- [DCOS_OSS-2041](https://jira.mesosphere.com/browse/DCOS_OSS-2041) Integration Test Failure: test_applications.py::test_if_marathon_app_can_be_deployed_with_mesos_containerizer
> dcos-oauth: bump for increased zk connection timeout 1.10

- packages/mesos/buildinfo.json
Bumped Mesos to 1.5.0-rc1.
- [DCOS_OSS-2083](https://jira.mesosphere.com/browse/DCOS_OSS-2083) Bump Mesos to 1.5.0-rc1.
___
> Bumped Mesos to 1.5.0-rc1 (1d9b5de7d).

- pkgpanda/__init__.py
- pkgpanda/test_setup.py
Systemd requires that all unit files be readable when it boots. If DC/OS unit files are symlinked to a non-root volume mount that's managed by systemd, that mount won't be available when systemd starts, so systemd won't be able to read DC/OS unit files and will mark those units as failed without starting them. This PR changes the behavior of `pkgpanda setup` to copy unit files instead of symlinking, so that systemd can read DC/OS unit files before it mounts the volume that contains the rest of the installation.
- [DCOS_OSS-1587](https://jira.mesosphere.com/browse/DCOS_OSS-1587) Support DC/OS install on non-root LVM volume
If you are changing components or packages in DC/OS (e.g. you are bumping the …
> Pkgpanda: Copy systemd unit files instead of symlinking

- packages/marathon/buildinfo.json
- Expose volume information for pod instances
- It fixes a race condition in status updates handling in case of pods with two or more containers.
- Persistent volumes for pods ZK data migration.
- Important fixes.
- Minor features.
- [COPS-2072](https://jira.mesosphere.com/browse/COPS-2072) - Expose containerPort as $PORT_NAME env vars
- [MARATHON-7839](https://jira.mesosphere.com/browse/MARATHON-7839) - Introducing missing deployment types
- [MARATHON_EE-1673](https://jira.mesosphere.com/browse/MARATHON_EE-1673) - Introduce lightweight SSE flag
- [MARATHON_EE-1785](https://jira.mesosphere.com/browse/MARATHON_EE-1785) - ZK data migration for persistent volumes for pods
- [MARATHON-8005](https://jira.mesosphere.com/browse/MARATHON-8005) - Fix datetime serialization for the API endpoints.
- …
> Bump Marathon to 11.6.0-pre-270-g3872d5e

- packages/python/buildinfo.json
This resolves the issue where a user requires to have his machines SSH keys registered to github. This is not required for DC/OS Open.
- [DCOS_OSS-2082](https://jira.mesosphere.com/browse/DCOS_OSS-2082) Build process requires SSH GitHub access when HTTPS access would do.
PTAL @branden @amitaekbote
> change git protocol from SSH to HTTPS for pip

- gen/build_deploy/bash.py
- gen/dcos-config.yaml
This PR reserves the port 9273 for dcos-metrics' Prometheus producer. Additionally, a check is added to ensure that this port is available on the node. 
- [DCOS-20073](https://jira.mesosphere.com/browse/DCOS-20073) Reserve port 9273 for dcos-metrics
- [DCOS_OSS-2046](https://jira.mesosphere.com/browse/DCOS_OSS-2046) Add Prometheus Producer for Metrics
> Reserve port 9273 for prometheus metrics

- packages/dcos-ui/buildinfo.json
Update the DC/OS UI package to include the latest fixes, improvements and features.
- [DCOS-19743](https://jira.mesosphere.com/browse/DCOS-19743) Fix bug where the page threw an error after deleting service
- [DCOS-20382](https://jira.mesosphere.com/browse/DCOS-20382) Fix bug where page threw error on tasks tab
- [DCOS-20376](https://jira.mesosphere.com/browse/DCOS-20376) Fix the node detail tab: Master version is not displayed
- [DCOS-20317](https://jira.mesosphere.com/browse/DCOS-20317) Fix the nodes overview page: Wrong disk usage (NaN%) 
- [DCOS-20253](https://jira.mesosphere.com/browse/DCOS-20253) Fix spacing issues in nodes table
- [DCOS-20308](https://jira.mesosphere.com/browse/DCOS-20308) Fix …
> chore(dcos-ui): update package

- packages/metronome/buildinfo.json
- [DCOS_OSS-2095](https://jira.mesosphere.com/browse/DCOS_OSS-2095) Bump Metronome 0.3.4
* [METRONOME-207](https://jira.mesosphere.com/browse/METRONOME-207) V0 Endpoint needs to support ForcePullImage
> Metronome 0.3.4 bump for DC/OS 1.11

- pkgpanda/__init__.py
- pkgpanda/test_setup.py
This reverts commit ec32f171777fee18fd0a808e4c86576fe311819c, which fails on CoreOS 1465.6.0. See https://jira.mesosphere.com/browse/DCOS-20428.
- [DCOS-20428](https://jira.mesosphere.com/browse/DCOS-20428) Unable to spin-up up 1.11-dev cluster on GCP
> Revert "Copy systemd unit files instead of symlinking"

- gen/aws/templates/advanced/infra.json
- gen/aws/templates/cloudformation.json
This removes references to m3.medium instance types, which are being deprecated, and replaces them with m4.large, which is the smallest type in the m4 family.
- [DCOS-20442](https://jira.mesosphere.com/browse/DCOS-20442) Official AWS CloudFormation Stack (infra.json) as an InstanceType has hardcoded value m3.medium
> Replace deprecated m3 instance types with m4 in cloud templates

- packages/dcos-ui/buildinfo.json
We updated the UI with the latest fixes.
- [DCOS-20158](https://jira.mesosphere.com/browse/DCOS-20158) update `marked` package
___ …
> Update DCOS-UI to 1.10.3 

- packages/metronome/buildinfo.json
- [DCOS_OSS-2095](https://jira.mesosphere.com/browse/DCOS_OSS-2095) Bump Metronome 0.3.4
* [METRONOME-207](https://jira.mesosphere.com/browse/METRONOME-207) V0 Endpoint needs to support ForcePullImage
> Metronome 0.3.4 bump for DC/OS 1.10

- docs/admin-ports.md
This PR simply adds port 9273 to the documentation, per @branden's request in #2325. 
- [DCOS-20073](https://jira.mesosphere.com/browse/DCOS-20073) Reserve port 9273 for dcos-metrics
> Add port 9273 to admin-ports.md

- packages/mesos/buildinfo.json
This PR bumps Mesos to the official RC1 release candidate of 1.5.0. This brings in a fix for the operator event stream which can lead to dropped events. This is important for DC/OS 1.11 because the DC/OS UI now relies on the operator event stream.
- [DCOS_OSS-2105](https://jira.mesosphere.com/browse/DCOS_OSS-2105) UI can show stale task state due to dropped events.
- [MESOS-8469](https://issues.apache.org/jira/browse/MESOS-8469) Mesos master might drop some events in the operator API stream.
> Bump Mesos to include operator event stream fix.

- tox.ini
The default pytest version moved to 3.4.0 and apparently in this version catchlog (AKA the `caplog` fixture in pytest) stopped working and so the test that checks the log stream failed.
https://jira.mesosphere.com/browse/DCOS_OSS-2124
> Pin pytest to 3.2.2 and pytest-catchlog to 1.2.2

- packages/marathon/buildinfo.json
- [MARATHON-7990](https://jira.mesosphere.com/browse/MARATHON-7990) Ease up on the `toString` for Group and log clashing ids.
- [COPS-2072](https://jira.mesosphere.com/browse/COPS-2072) Expose `containerPort` as `$PORT_NAME` in environment variables.
- [MARATHON-7914](https://jira.mesosphere.com/browse/MARATHON-7914) Migration from joda-time to java.time.
- [MARATHON-8005](https://jira.mesosphere.com/browse/MARATHON-8005) Fixing OffsetDateTime json serialization that was different form Timestamp serialization.
- [MARATHON-8015](https://jira.mesosphere.com/browse/MARATHON-8015) Fixes v1.5 migration issue with args only apps
- [MARATHON-8011](https://jira.mesosphere.com/browse/MARATHON-8011) Scaling to zero takes too …
> Marathon 1.5.6 bump

- packages/adminrouter/extra/src/includes/server/open/master.conf
Short clarification on why `/exhibitor/v1/cluster/status` needs to be unauthenticated.
- https://jira.mesosphere.com/browse/DCOS_OSS-1545 `Admin Router: Investigate whether `/exhibitor/v1/cluster/status` still needs to be unauthenticated`
DC/OS EE: https://github.com/mesosphere/dcos-enterprise/pull/2131
> Admin Router: Clarify why /exhibitor/v1/cluster/status needs to be unauthenticated

- pkgpanda/__init__.py
- pkgpanda/test_setup.py
Systemd requires that all unit files be readable when it boots. If DC/OS unit files are symlinked to a non-root volume mount that's managed by systemd, that mount won't be available when systemd starts, so systemd won't be able to read DC/OS unit files and will mark those units as failed without starting them. This PR changes the behavior of Pkgpanda to copy unit files instead of symlinking then to the original package files, so that systemd can read DC/OS unit files before it mounts the volume that contains the rest of the installation.
Unit files are copied to the systemd config directory in two steps: First they're copied to a temporary location, and then they're moved to their intended location. This maintains the invariant that Pkgpanda always moves or symlinks files to their …
> (1.11) Pkgpanda: Copy systemd unit files instead of symlinking

- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_auth.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/extra/test_dcos_log.py
- packages/dcos-integration-test/extra/test_endpoints.py
- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_mesos.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_metronome.py
- packages/dcos-integration-test/extra/test_misc.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_packaging.py
- packages/dcos-integration-test/extra/test_rexray.py
- packages/dcos-integration-test/extra/test_rlimit.py
- packages/dcos-integration-test/extra/test_service_discovery.py
- packages/dcos-integration-test/extra/test_sysctl.py
- packages/dcos-integration-test/extra/test_ucr.py
- packages/dcos-integration-test/extra/test_units.py
https://jira.mesosphere.com/browse/DCOS-20355 
When a status check fails, we should make it easy for a developer to be self-sufficient, by helping the developer in identifying the purpose of the test, and provide information on the maintainer for the test.
Along those lines, we'd like to give [information about the various pull request statuses](https://github.com/dcos/dcos/pull/2320) and also give a `_maintainer_` information for the module. These could be useful when reviewing, assigning reviewers, or assisting with test failures.
**Please review this PR** and share your feedback.
* I have assigned members from teams who, I thought, have worked on that piece of code.
* If a different maintainer is desired, please comment on this.
* Similar exercise will be done for the dcos-enterprise …
> Assigning maintainers against tests.

- packages/mesos/buildinfo.json
This bumps DC/OS upstream to include the latest nightly Mesos build.
> Bumped Mesos to include operator API fix.

- pkgpanda/__init__.py
- pkgpanda/test_setup.py
This is a 1.12 port of #2383.
- [DCOS_OSS-1587](https://jira.mesosphere.com/browse/DCOS_OSS-1587) Support DC/OS install on non-root LVM volume
> (1.12) Pkgpanda: Copy systemd unit files instead of symlinking

- NOTICE
We ship JDK 8 and were pointing to Java 6 License.
> Update JDK License link.

- gen/calc.py
As of DC/OS 1.11, IPv6 overlay network is optional. Hence, the
validation check shouldn't assert on the presence of IPv6 overlay.
This patch makes modifies the validation checks such that IPv6
overlay could be optional
- [DCOS-21095](https://jira.mesosphere.com/browse/DCOS-21095) Turn IPv6 Overlay Off in IPv4 Environment
___
**What is the review process and when will my …
> Makes overlay IPv6 validation checks optional

- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-net/buildinfo.json
Once IPVS picks up the packet for load balancing it goes directly to routing layer instead of traversing the IPtables again. However, to reach to the container in bridge mode the packet has to go through the IPtables for DNAT. Hence this issue. The only solution possible is to have actual container IP address as the backend in IPVS configuration. This way container would be accessible through routing instead of port mapping. However, this has to be done only for the agent where the container is running. Other agents would still have to go through the port mapping as container IP, in case of bridge mode, is non-routable.
- [DCOS_OSS-2070](https://jira.mesosphere.com/browse/DCOS_OSS-2070) Service is not …
> [1.11] Fix l4lb VIP from local agent using UCR bridge mode

- dcos_installer/action_lib.py
- packages/mesos/build
- packages/mesos/extra/dcos-mesos-master.service
- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
- packages/mesos/extra/start_mesos.sh
Fix for networkd overlay network in coreOS. Previous fix only worked when the 'install-prereqs' feature of the dcos_installer was used, which is not a guaranteed setup step.
https://jira.mesosphere.com/browse/DCOS_OSS-2003
> [1.10] Move networkd setup to mesos unit

- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-net/buildinfo.json
Once IPVS picks up the packet for load balancing it goes directly to routing layer instead of traversing the IPtables again. However, to reach to the container in bridge mode the packet has to go through the IPtables for DNAT. Hence this issue. The only solution possible is to have actual container IP address as the backend in IPVS configuration. This way container would be accessible through routing instead of port mapping. However, this has to be done only for the agent where the container is running. Other agents would still have to go through the port mapping as container IP, in case of bridge mode, is non-routable.
- [DCOS_OSS-2070](https://jira.mesosphere.com/browse/DCOS_OSS-2070) Service is not …
> Fix l4lb VIP from local agent using UCR bridge mode

- packages/marathon/buildinfo.json
The same as #2473, but into `master` branch.
> Bump Marathon to 1.6.322

- packages/python/build
With this change our DC/OS installations will include the python build specific gdb helper script `python-gdb.py`. This will allow us to interact and debug python based components of DC/OS.
Most Linux distributions bundle this file in a dedicated python-dbg (or similar) package, so it is understandable that it is not part of what `make install` installs into $prefix. As we do however bundle our own build of python and do not currently provide a debug build and or additional debug package, there is no usable python-gdb.py file available.
Please note that the path the file usually goes to is somewhere in '/usr/share/gdb/[...]', so I decided to put in in `$PKG_PATH/share/` as well, although the gdb autoloader wont pick it up automatically from there. This seems to be the most sane solution …
> Adds installation of DC/OS build specific python-gdb.py file

- packages/dcos-cni/buildinfo.json
This PR bump the dcos-cni plugin to include the changes necessary for the plugin to support Kubernetes dns proxy. 
- [DCOS_OSS-2171](https://jira.mesosphere.com/browse/DCOS_OSS-2171) Need to support kube DNS proxy in spartan CNI plugin
___ …
> bump dcos-cni

- gen/aws/templates/advanced/advanced-master.json
- gen/aws/templates/advanced/advanced-priv-agent.json
- gen/aws/templates/advanced/advanced-pub-agent.json
- gen/build_deploy/aws.py
This is a fix for the open and ee "AWS CloudFormation Zen CoreOS" jobs on TeamCity. The problem was that `prereqs` was being appended to the AMI name being put into the template, but the `<os>prereq` AMIs are only applicable to el7 ones, and cloudformation was looking for nonexistant `coreosprereqs` images. This adds some logic to only append prereqs to el7 clusters. 
The EE job also needed a build step added to get it to work, see https://github.com/mesosphere/dcos-enterprise/pull/2094#issuecomment-366081215
https://jira.mesosphere.com/browse/DCOS-20266
https://jira.mesosphere.com/browse/DCOS-20026
___
**PLEASE …
> When generating advanced templates, only append prereq to os_name for el7

- dcos_installer/action_lib.py
- packages/mesos/extra/start_mesos.sh
Fix for networkd overlay network in coreOS. Previous fix only worked when the 'install-prereqs' feature of the dcos_installer was used, which is not a guaranteed setup step.
https://jira.mesosphere.com/browse/DCOS_OSS-2003
> Move networkd setup to mesos unit

- dcos_installer/action_lib.py
- packages/mesos/extra/start_mesos.sh
Fix for networkd overlay network in coreOS. Previous fix only worked when the 'install-prereqs' feature of the dcos_installer was used, which is not a guaranteed setup step.
https://jira.mesosphere.com/browse/DCOS_OSS-2003
> [1.11] Move networkd setup to mesos unit

- packages/mesos/buildinfo.json
This is a routine bump to the latest 1.5.x branch of Mesos.
[mesosphere/mesos diff](https://github.com/mesosphere/mesos/compare/de6c7c6131f46064f6d9eff56b392f8e381b06d4...0ba40f86759307cefab1c8702724debe87007bb0)
> [1.11] Bump Mesos to nightly 1.5.x 83b4969

- packages/metronome/buildinfo.json
- [DCOS_OSS-21523](https://jira.mesosphere.com/browse/DCOS-21523) Bump Metronome 0.4.0
- [METRONOME-190](https://jira.mesosphere.com/browse/METRONOME-190) Added authorized launch queue
- [METRONOME-194](https://jira.mesosphere.com/browse/METRONOME-194) Support FORBID Concurrency Policy
- [METRONOME-100](https://jira.mesosphere.com/browse/METRONOME-100) Metronome Restarts causes duplication of jobruns
- [METRONOME-191](https://jira.mesosphere.com/browse/METRONOME-191) Implement Start Deadline Timeout …
> metronome 0.4.0 bump for DCOS 1.10.5+

- packages/dcos-integration-test/extra/test_service_discovery.py
Encountered this when I was playing with integration tests. 
```
>       assert len(dcos_api_session.slaves) >= 2, "Test requires a minimum of two agents"
E       AssertionError: Test requires a minimum of two agents
E       assert 1 >= 2
E        +  where 1 = len(['172.17.0.3'])
E        +    where ['172.17.0.3'] = <dcos_test_utils.enterprise.EnterpriseApiSession object at 0x7fa73c858128>.slaves
open_source_tests/test_service_discovery.py:72: AssertionError
```
> Change a test setup requirement assertion to a skip.

- packages/dcos-integration-test/extra/test_networking.py
I am not sure why our flake8 didn't complain, but my IDE raised an issue about using `raise` statement without an Exception. This fixes it.
> Raise Exception explicitly

- pkgpanda/docs/package_concepts.md
This is a followup to https://github.com/dcos/dcos/pull/2404 that updates documentation accordingly.
- [DCOS_OSS-2178](https://jira.mesosphere.com/browse/DCOS_OSS-2178) Update pkgpanda docs to cover systemd unit files
> Pkgpanda: Update docs to cover systemd unit files

- packages/adminrouter/docker/requirements-tests.txt
- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/basehandler.py
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/mesos.py
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/recording.py
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
This PR prevents AR's cache code from re-using TCP connections while refreshing cache. This may result in AR trying to fetch e.g. `/mesos/state-summary` from a master that already abdicated which in turn results in failure to refresh the cache.
Please check the linked Jira for detailed analysis and discussion of the bug.
On top of this chance few small enchancements and bugfixes were done to test harness in order to be able to write a test for this change:
* mesos mock should always respond using HTTP/1.1
* the `Content-Length` field should be properly set while sending the response to client
* add `pytest-repeat` package to simplify re-running tests multiple times
- https://jira.mesosphere.com/browse/SOAK-68 - `soak111: Marathon UI not loading, 404 returned by adminrouter`
DC/OS EE PR: …
> Admin Router: Prevent reusing tcp sockets by AR's cache code [master]

- gen/calc.py
- gen/dcos-config.yaml
dcos-net binds dns servers on all ip addresses on start. It works fine on clean node, but once k8s start coredns on 198.51.100.4, dcos-net tries to bind on this ip as well and crashes with eaddrinuse error. To fix it we have to add 198.51.100.4 ip address to the blacklist.
- [DCOS-21486](https://jira.mesosphere.com/browse/DCOS-21486) Don't bind dcos-dns on k8s cluster dns ip address
___ …
> Don't bind dcos-dns on k8s cluster dns ip address

- packages/dcos-history/extra/history/statebuffer.py
- packages/dcos-history/extra/test_history_service.py
When the history service writes data to file, it adds a timestamp. At
exactly zero microseconds past the second, this timestamp was
malformed, and as a result the history service could not load it.
This PR ensures that in such cases the timestamp contains the
microsecond field.
- [DCOS_OSS-2210](https://jira.mesosphere.com/browse/DCOS_OSS-2210) Incomplete timestamp can cause a crash-loop in the history service
___
> Ensure that cache timestamps are well-formed

- packages/adminrouter/docker/Dockerfile
- packages/adminrouter/docker/build-resty.sh
- packages/adminrouter/docker/openresty-1.13.6.1-no_sse42.patch
This is a backport of https://github.com/dcos/dcos/pull/2114/files
- https://jira.mesosphere.com/browse/DCOS_OSS-2181 `Admin Router: bump to OpenResty 1.13.x [1.10]`
- https://jira.mesosphere.com/browse/DCOS_OSS-1859 `Admin Router: bump to OpenResty 1.13.x`
* original PR: https://github.com/dcos/dcos/pull/2114
* DC/OS EE PR: https://github.com/mesosphere/dcos-enterprise/pull/2313
> Admin Router: Bump openresty to 1.13.6 [1.10]

- packages/adminrouter/docker/requirements-tests.txt
- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/basehandler.py
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/mesos.py
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/recording.py
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
This is a backport of https://github.com/dcos/dcos/pull/2511 to 1.10. Check it for more details.
- DCOS-21451 `debug and fix for SOAK-68`
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/2361
DC/OS Open, master branch PR: https://github.com/dcos/dcos/pull/2511
DC/OS EE, master branch PR: https://github.com/mesosphere/dcos-enterprise/pull/2331
> Admin Router: Prevent reusing tcp sockets by AR's cache code [1.10]

- gen/calc.py
- gen/dcos-config.yaml
dcos-net binds dns servers on all ip addresses on start. It works fine on clean node, but once k8s start coredns on 198.51.100.4, dcos-net tries to bind on this ip as well and crashes with eaddrinuse error. To fix it we have to add 198.51.100.4 ip address to the blacklist.
- [DCOS-21486](https://jira.mesosphere.com/browse/DCOS-21486) Don't bind dcos-dns on k8s cluster dns ip address
___ …
> [1.11] Don't bind dcos-dns on k8s cluster dns ip address

- packages/adminrouter/docker/requirements-tests.txt
- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/basehandler.py
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/mesos.py
- packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/recording.py
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
This is a backport of https://github.com/dcos/dcos/pull/2511 to 1.11. Check it for more details.
- DCOS-21451 `debug and fix for SOAK-68`
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/2360
DC/OS Open, master branch PR: https://github.com/dcos/dcos/pull/2511
DC/OS EE, master branch PR: https://github.com/mesosphere/dcos-enterprise/pull/2331
> Admin Router: Prevent reusing tcp sockets by AR's cache code [1.11]

- gen/calc.py
- gen/dcos-config.yaml
dcos-net binds dns servers on all ip addresses on start. It works fine on clean node, but once k8s start coredns on 198.51.100.4, dcos-net tries to bind on this ip as well and crashes with eaddrinuse error. To fix it we have to add 198.51.100.4 ip address to the blacklist.
- [DCOS-21486](https://jira.mesosphere.com/browse/DCOS-21486) Don't bind dcos-dns on k8s cluster dns ip address
___ …
> [1.11.0-GA] Don't bind dcos-dns on k8s cluster dns ip address

- docs/admin-ports.md
- gen/build_deploy/bash.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
This PR moves the dcos-metrics Prometheus producer from port 9273 to port 61091. This avoids the need to update Mesos' reserved ports configuration. Altering Mesos resources in such a way causes various problems, one of which is the possibility of a port collision. 
Using a port which is not available to Mesos (any unoccupied port > 61000) avoids the need to update anything. 
- [DCOS-21549](https://jira.mesosphere.com/browse/DCOS-21594) Unreserve port 9273 (prometheus metrics)
- [DCOS-20072](https://jira.mesosphere.com/browse/DCOS-20072) Add explicit configuration for Prometheus producer in dcos-metrics
- [DCOS-21545](https://jira.mesosphere.com/browse/DCOS-21545) …
> [1.11.0-GA] Move Prometheus producer to port 61091

- docs/admin-ports.md
- gen/build_deploy/bash.py
- gen/calc.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-net/extra/dcos-net-setup.py
- packages/dcos-net/extra/dcos-net-watchdog.service
- packages/dcos-net/extra/dcos-net.service
* [1.11.0-GA] dcos-net not starting if IPv6 is disabled  #2530 
* [1.11.0-GA] Don't bind dcos-dns on k8s cluster dns ip address #2533
* [1.11.0-GA] Move Prometheus producer to port 61091  #2567
> Integration Train for 1.11.0-GA - 2018-03-05

- packages/mesos-modules/buildinfo.json
ZooKeeper configuration is passed to the Mesos modules as the environment variables `MESOS_ZK` and `MESOS_MASTER` for masters and agents respectively. This variables expect ZooKeeper configuration to be stored in the environment variable following the pattern `zk://user:password@zk1:port,zk2:port`. However, mesos has always allowed this configuration to be stored in files. 
With [MESOS-8413](https://issues.apache.org/jira/browse/MESOS-8413) an issue was resolved in which the contents of the files were shown instead of the path of the file, thus preventing accidental leak of ZooKeeper credentials.
While the issue of Mesos is fixed, using ZooKeeper file based configuration cannot yet be used since the mesos-modules do not yet support this feature. This PR addresses this problem.
These DC/OS …
> [1.11] Bumps mesos modules enabling file based ZK configuration.

- docs/admin-ports.md
- gen/build_deploy/bash.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
This PR moves the dcos-metrics Prometheus producer from port 9273 to port 61091. This avoids the need to update Mesos' reserved ports configuration. Altering Mesos resources in such a way causes various problems, one of which is the possibility of a port collision. 
Using a port which is not available to Mesos (any unoccupied port > 61000) avoids the need to update anything. 
- [DCOS-21549](https://jira.mesosphere.com/browse/DCOS-21594) Unreserve port 9273 (prometheus metrics)
- [DCOS-20072](https://jira.mesosphere.com/browse/DCOS-20072) Add explicit configuration for Prometheus producer in dcos-metrics
- [DCOS-21545](https://jira.mesosphere.com/browse/DCOS-21545) …
> [1.11] Move Prometheus producer to port 61091

- packages/marathon/buildinfo.json
- [MARATHON-8088](https://jira.mesosphere.com/browse/MARATHON-8088) Implement gpu_scheduling_behavior parameter and basic functionality.
- [MARATHON-8089](https://jira.mesosphere.com/browse/MARATHON-8089) Application specific override for GPU scheduling behavior
- [MARATHON-8112](https://jira.mesosphere.com/browse/MARATHON-8112) Open the persistence store before taking a backup using CLI
> marathon bump to 1.6.352

- packages/mesos-modules/buildinfo.json
ZooKeeper configuration is passed to the Mesos modules as the environment variables `MESOS_ZK` and `MESOS_MASTER` for masters and agents respectively. This variables expect ZooKeeper configuration to be stored in the environment variable following the pattern `zk://user:password@zk1:port,zk2:port`. However, mesos has always allowed this configuration to be stored in files.
With [MESOS-8413](https://issues.apache.org/jira/browse/MESOS-8413) an issue was resolved in which the contents of the files were shown instead of the path of the file, thus preventing accidental leak of ZooKeeper credentials.
While the issue of Mesos is fixed, using ZooKeeper file based configuration cannot yet be used since the mesos-modules do not yet support this feature. This PR addresses this problem.
These DC/OS …
> Bumps mesos modules enabling file based ZK configuration

- docs/admin-ports.md
- gen/build_deploy/bash.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
This PR moves the dcos-metrics Prometheus producer from port 9273 to port 61091. This avoids the need to update Mesos' reserved ports configuration. Altering Mesos resources in such a way causes various problems, one of which is the possibility of a port collision. 
Using a port which is not available to Mesos (any unoccupied port > 61000) avoids the need to update anything. 
- [DCOS-21549](https://jira.mesosphere.com/browse/DCOS-21594) Unreserve port 9273 (prometheus metrics)
- [DCOS-20072](https://jira.mesosphere.com/browse/DCOS-20072) Add explicit configuration for Prometheus producer in dcos-metrics
- [DCOS-21545](https://jira.mesosphere.com/browse/DCOS-21545) …
> Move Prometheus producer to port 61091

- packages/metronome/buildinfo.json
* [METRONOME-222](https://jira.mesosphere.com/browse/METRONOME-222) CMD or Docker is Required.
* [METRONOME-236](https://jira.mesosphere.com/browse/METRONOME-236) Additional CRON validation to prevent system lock up.
> bumping metronome to 0.4.1

- packages/adminrouter/extra/src/README.md
- packages/adminrouter/extra/src/test-harness/modules/generic_test_code/common.py
- packages/adminrouter/extra/src/test-harness/modules/generic_test_code/generalised_tests.py
- packages/adminrouter/extra/src/test-harness/tests/open/test_generic.config.yml
- packages/adminrouter/extra/src/test-harness/tests/test_agent.py
- packages/adminrouter/extra/src/test-harness/tests/test_generic.config.yml
- packages/adminrouter/extra/src/test-harness/tests/test_master.py
This PR prepares AR test harness for tests needed by the private registry feature [1][2].  This includes:
* some naming changes for response tests, now that they are also capable of testing custom HTTP response status
* make is_response_correct generic test customizable wrt. response status
* make all generic tests accept a parameter defining the "Host" header that is to be sent to the tested AR
[1] https://github.com/mesosphere/dcos-enterprise/pull/1807
[2] https://jira.mesosphere.com/browse/DCOS-2799
- DCOS-21456 `Admin Router: Add missing AR tests for the registry service`
- DCOS-2799 `Package Registry` - linking to the epic, as there are lots of issues there …
> Admin Router: Support for custom 'Host' header and response status for generic tests

- gen/aws/templates/aws.html
- gen/azure/templates/azure.html
Fixing the Azure documentation link as the documentation site has been reorganized recently.
> Fixed broken links for Azure & AWS docs.

- packages/marathon/buildinfo.json
- [MARATHON-8088](https://jira.mesosphere.com/browse/MARATHON-8088) Implement gpu_scheduling_behavior parameter and basic functionality.
- [MARATHON-8089](https://jira.mesosphere.com/browse/MARATHON-8089) Application specific override for GPU scheduling behavior
- [MARATHON-8112](https://jira.mesosphere.com/browse/MARATHON-8112) Open the persistence store before taking a backup using CLI
> marathon 1.6.353 bump

- NOTICE
We ship JDK 8 and were pointing to Java 6 License.
> Update JDK License link. 

- packages/adminrouter/extra/src/master/cache.lua
This is a backport of https://github.com/dcos/dcos/pull/2511 to 1.9. Due to the fact that 1.9 is very old and it is impossible to port the test, I am making here only the functional change.
- DCOS-21451 `debug and fix for SOAK-68`
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/2362
DC/OS Open, master branch PR: https://github.com/dcos/dcos/pull/2511
DC/OS EE, master branch PR: https://github.com/mesosphere/dcos-enterprise/pull/2331
> Admin Router: Prevent reusing tcp sockets by AR's cache code [1.9]

- packages/metronome/buildinfo.json
- [DCOS_OSS-2097](https://jira.mesosphere.com/browse/DCOS_OSS-2097) Bump Metronome 0.3.5 in DC/OS 1.9.
* [METRONOME-236](https://jira.mesosphere.com/browse/METRONOME-236) Additional CRON validation to prevent system lock up.
> bumping metronome to 0.3.5

- packages/mesos/buildinfo.json
This PR incorporates Mesos bug fixes and improvements.
- [MESOS-8488](https://issues.apache.org/jira/browse/MESOS-8488) Docker bug can cause unkillable tasks.
- [MESOS-8574](https://issues.apache.org/jira/browse/MESOS-8574) Docker executor makes no progress when 'docker inspect' hangs.
- [MESOS-8575](https://issues.apache.org/jira/browse/MESOS-8575) Improve discard handling for 'Docker::stop' and 'Docker::pull'.
- [MESOS-8576](https://issues.apache.org/jira/browse/MESOS-8576) Improve discard handling of 'Docker::inspect()'.
- [MESOS-8605](https://issues.apache.org/jira/browse/MESOS-8605) Terminal task status update will not send if 'docker inspect' is hung. …
> Bumped mesos SHA to include the fix for docker daemon hanging issue.

- NOTICE
- packages/adminrouter/extra/src/master/cache.lua
- packages/dcos-ui/buildinfo.json
- packages/mesos/buildinfo.json
- packages/metronome/buildinfo.json
* Update DCOS-UI to 1.9.4 #2326 
* Update JDK License link.  #2441
* Admin Router: Prevent reusing tcp sockets by AR's cache code [1.9]  #2539 
* bumping metronome to 0.3.5 #2562 
* Bumped mesos SHA to include the fix for docker daemon hanging issue. #2582
> 1.9 train march7

- gen/build_deploy/aws.py
- gen/coreos/cloud-config.yaml
- packages/mesos/extra/start_mesos.sh
Updates CoreOS to 1632.2.1 in the AWS CloudFormation Templates, which also includes a bump to docker 17
https://jira.mesosphere.com/browse/DCOS_OSS-2130
> Coreos update 1.11

- gen/aws/templates/aws.html
- gen/azure/templates/azure.html
Fixing the Azure documentation link as the documentation site has been reorganized recently.
> Fixed broken link for Azure & AWS documentation.

- setup.py
> [1.11] Avoid python dependency break for python-dateutil

- setup.py
> Avoid python dependency break for python-dateutil

- setup.py
- tox.ini
> [1.8] Avoid python dependency break for python-dateutil

- setup.py
> [1.9] Avoid python dependency break for python-dateutil

- setup.py
> [1.10] Avoid python dependency break for python-dateutil

- packages/openssl/buildinfo.json
This bumps OpenSSL from 1.0.2k to 1.0.2n.
https://jira.mesosphere.com/browse/DCOS_OSS-1903
> openssl: bump to 1.0.2n

- mergebot-config.json
* https://jira.mesosphere.com/browse/QUALITY-1958 - Suppress Non-Interactive Mergebot Commands from help
More discussion is here - https://github.com/mesosphere/mergebot/pull/121
> Set interactivity to false for certain commands.

- gen/dcos-config.yaml
Mesos Core considers this a bug via:
- [MESOS-7721](https://issues.apache.org/jira/browse/MESOS-7721) Master's agent removal rate limit also applies to agent unreachability.
- [MESOS-5948](https://issues.apache.org/jira/browse/MESOS-5948) Remove rate-limiting for agent removal
A major reason this is not already removed is the PM for the project left the project.   This should have been removed already.   It has likely caused more harm than good.  With companies changing it by our recommendation [under certain situations](https://jira.mesosphere.com/browse/COPS-719)
Mesos is a 2-level scheduler.  It makes NO sense for Mesos to keep and hold information from the "intelligent" scheduler.   `MESOS_SLAVE_REMOVAL_RATE_LIMIT` …
> Node Rate Limiter considered HARMFUL

- gen/dcos-config.yaml
Update of the DC/OS config generator to assign the appropriate default value for gpu_scheduling_behavior for marathon
- [MARATHON-8090](https://jira.mesosphere.com/browse/MARATHON-8090) Update DC/OS configuration to set appropriate defaults on installation.
> Update DC/OS configuration to set appropriate marathon defaults on installation

- packages/curl/buildinfo.json
This PR bumps curl from 17.48 to 7.59.0 in 1.11.
Related PRs:
1.10: https://github.com/dcos/dcos/pull/2647
1.12/master: https://github.com/dcos/dcos/pull/2648
https://jira.mesosphere.com/browse/DCOS-21557
- [x ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
> Bump curl from 7.48 to 7.59 in dcos 1.11

- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
This is a partial work that is required to re-enable SAML integration tests. The change in DC/OS Open is removing `docker-py` package that is unused, outdated and unsupported. The package is replaced with new `docker` library in EE PR.
- [DCOS-21531](https://jira.mesosphere.com/browse/DCOS-21531) dcos-integration-test: enable SAML tests again (PhantomJS doesn't support ES2015 anymore)
> dcos-integration-test: Fix SAML integration tests [1.11]

- dcos_installer/upgrade.py
Fixes a bug in the upgrade script which does not print errors if checks fail after an upgrade
https://jira.mesosphere.com/browse/DCOS_OSS-2028
___
* Developers responsible for code …
> Fix upgrade script to print errors if checks fail after upgrade

- packages/rexray/build
- packages/rexray/buildinfo.json
- packages/rexray/extra/dcos-rexray.service
This upgrades REX-Ray from v0.9.0 to v0.11.2. The current package can't be built due to the issue fixed by https://github.com/rexray/rexray/pull/995, and v0.11.2 is the latest available release.
- [DCOS_OSS-2245](https://jira.mesosphere.com/browse/DCOS_OSS-2245) Rexray does not build in 1.11 and master
> Upgrade REX-Ray to v0.11.2

- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
This is a partial work that is required to re-enable SAML integration tests. The change in DC/OS Open is removing `docker-py` package that is unused, outdated and unsupported. The package is replaced with new `docker` library in EE PR.
- [DCOS-21531](https://jira.mesosphere.com/browse/DCOS-21531) dcos-integration-test: enable SAML tests again (PhantomJS doesn't support ES2015 anymore)
> dcos-integration-test: Fix SAML integration tests

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/extra/test_dcos_log.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_packaging.py
- packages/dcos-test-utils/buildinfo.json
This update to dcos-test-utils removed magic URL path handling which enabled the following to requests to be identical:
```
api.get('/v1/foo/bar') ==> http://dcos.com/v1/foo/bar
api.get('v1/foo/bar')  ==> http://dcos.com/v1/foo/bar
```
Now, paths must be intentionally prefaced with `/` if they are to work in most cases. This is useful for ensuring that test's which may want to push the slash-handling are transparent at the test-harness level.
E.G.
```
api.get('/v1/foo/bar') ==> http://dcos.com/v1/foo/bar
api.get('v1/foo/bar')  ==> http://dcos.comv1/foo/bar
```
https://jira.mesosphere.com/browse/DCOS-13496
> Bump dcos-test-utils: strict URL path handling

- packages/mesos/buildinfo.json
This PR incorporates Mesos bug fixes and improvements.
- [DCOS_OSS-2315](https://jira.mesosphere.com/browse/DCOS_OSS-2315) Bump Mesos SHA for DC/OS 1.10.6.
- [MESOS-8488](https://issues.apache.org/jira/browse/MESOS-8488) Docker bug can cause unkillable tasks.
- [MESOS-8574](https://issues.apache.org/jira/browse/MESOS-8574) Docker executor makes no progress when 'docker inspect' hangs.
- [MESOS-8575](https://issues.apache.org/jira/browse/MESOS-8575) Improve discard handling for 'Docker::stop' and 'Docker::pull'.
- [MESOS-8576](https://issues.apache.org/jira/browse/MESOS-8576) Improve discard handling of 'Docker::inspect()'.
- [MESOS-8605](https://issues.apache.org/jira/browse/MESOS-8605) Terminal task status update will not send if 'docker inspect' is …
> Bumped Mesos SHA to the latest 1.4.x.

- packages/curl/buildinfo.json
This PR bumps curl from 17.48 to 7.59.0 in 1.10
https://jira.mesosphere.com/browse/DCOS-21557
> Bump curl from 7.48 to 7.59 in dcos 1.10

- packages/dcos-integration-test/extra/test_dcos_log.py
- packages/dcos-log/build
- packages/dcos-log/buildinfo.json
bump dcos-log sha
this PR includes:
- fix for task logs Server-Sent-Event
- make dcos-log respect journald files rotation
- [DCOS_OSS-2292](https://jira.mesosphere.com/browse/DCOS_OSS-2292) - fir for server sent events
- [DCOS_OSS-2132](https://jira.mesosphere.com/browse/DCOS_OSS-2132) - respect systemd files rotation
- [COPS-2984](https://jira.mesosphere.com/browse/COPS-2984)
___ …
> Bump dcos log sha for 1.11

- pkgpanda/util.py
Deployments on Azure sometimes fail due to pkgpanda not being
able to download some of the packages. This is caused by Azure
transient temporary DNS failures.
This patch adds retries in pkgpanda when downloading packages.
- [DCOS_OSS-2317](https://jira.mesosphere.com/browse/DCOS_OSS-2317) Pkgpanda lack of retries when downloading packages.
> Add retries for pkgpanda when downloading packages

- packages/curl/buildinfo.json
This PR bumps curl from 17.48 to 7.59.0 in 1.12/master.
Related PRs:
1.11: https://github.com/dcos/dcos/pull/2641
1.10: https://github.com/dcos/dcos/pull/2647
https://jira.mesosphere.com/browse/DCOS-21557
> Bump curl from 7.48 to 7.59 in dcos 1.12/master

- gen/dcos-config.yaml
- gen/tests/test_adminrouter_tls_conf.py
- packages/adminrouter/docker/adminrouter-tls.conf
This PR disables the 3DES bulk encryption algorithm by default.
https://jira.mesosphere.com/browse/DCOS-21957
> [1.10] Disable the 3DES bulk encryption algorithm by default

- packages/marathon/buildinfo.json
Marathon bump 1.5.8
- [DCOS_OSS-2352](https://jira.mesosphere.com/browse/DCOS_OSS-2352) Bump Marathon to 1.5.8
- [MARATHON-7609](https://jira.mesosphere.com/browse/MARATHON-7609) Send Instance health changed event when the overall status changed
- [MARATHON-8104](https://jira.mesosphere.com/browse/MARATHON-8104) SlidingAverageSnapshot fix for metrics
- [MARATHON_EE-1884](https://jira.mesosphere.com/browse/MARATHON_EE-1884) SystemConfig is the Correct Security Constraint
> marathon bump 1.5.8

- gen/dcos-config.yaml
Update of the DC/OS config generator to remove the default value for gpu_scheduling_behavior for marathon
- [MARATHON-8090](https://jira.mesosphere.com/browse/MARATHON-8090) Update DC/OS configuration to set appropriate marathon defaults on installation.
> Update DC/OS configuration to remove marathon GPU defaults on installation

- packages/marathon/buildinfo.json
Lots of clean-ups, removal of dead code, fixing tests and missing Preferential GPU Scheduling features and tests.
- [MARATHON-8092](https://jira.mesosphere.com/browse/MARATHON-8092) Integration tests for Preferential GPU Scheduling in Marathon
- [MARATHON-8091](https://jira.mesosphere.com/browse/MARATHON-8091) GPU preferential scheduling Marathon documentation
- [MARATHON-8124](https://jira.mesosphere.com/browse/MARATHON-8124) Always unreserve resources for non-existing instances
- [MARATHON-8125](https://jira.mesosphere.com/browse/MARATHON-8125) Removing Akka Controllers
- [MARATHON-8091](https://jira.mesosphere.com/browse/MARATHON-8091) Document GPU_scheduling_behavior
- …
> Bumping marathon version to 1.6.392-f9d087d2f

- packages/metronome/buildinfo.json
Metronome bump 0.5.0 on Master
- [DCOS_OSS-2338](https://jira.mesosphere.com/browse/DCOS_OSS-2338) Bump metronome to 0.5.0
> Metronome bump 0.5.0 on Master

- cloud_images/centos7/create_dcos_ami.sh
We had updated the version https://github.com/dcos/dcos/pull/2040/files
but missed updating the default when we want to use `create_dcos_ami.sh`
- https://jira.mesosphere.com/browse/INFINITY-2715
```
Build 'builder-generic' finished.
==> builder-gpu: Creating the AMI: skumaran-7-dcos-centos7-gpu-nvidia-384.130-201804070135
builder-gpu: AMI: ami-d54a2cad
==> builder-gpu: Waiting for AMI to become ready...
==> builder-gpu: Modifying attributes on AMI (ami-d54a2cad)...
builder-gpu: Modifying: description
builder-gpu: Modifying: groups
==> builder-gpu: Modifying attributes on snapshot (snap-0f0086d6df757893b)...
==> builder-gpu: Modifying attributes on snapshot (snap-05452755050872ff0)...
==> builder-gpu: Modifying attributes on snapshot (snap-0ded2cae5b9b8dc72)...
==> builder-gpu: Modifying …
```
> Update the default of the cento-os AMI - ami-a9b24bd1

- packages/rexray/build
- packages/rexray/buildinfo.json
REX-Ray v0.9.0 can no longer be built from source, so we need to reuse [a previously built v0.9.0 binary](https://downloads.dcos.io/dcos/stable/packages/rexray/rexray--da7f17f8a4b772c0bac3f8d289a08abd4ff272b4.tar.xz). See https://github.com/rexray/rexray/pull/995.
- [DCOS_OSS-2310](https://jira.mesosphere.com/browse/DCOS_OSS-2310) REX-Ray integration test is flaky after version bump
> (1.11) Use prebuilt REX-Ray binary

- packages/rexray/build
- packages/rexray/buildinfo.json
REX-Ray v0.9.0 can no longer be built from source, so we need to reuse [a previously built v0.9.0 binary](https://downloads.dcos.io/dcos/stable/packages/rexray/rexray--da7f17f8a4b772c0bac3f8d289a08abd4ff272b4.tar.xz). See https://github.com/rexray/rexray/pull/995.
- [DCOS_OSS-2310](https://jira.mesosphere.com/browse/DCOS_OSS-2310) REX-Ray integration test is flaky after version bump
> (1.10) Use prebuilt REX-Ray binary

- packages/rexray/build
- packages/rexray/buildinfo.json
This reverses https://github.com/dcos/dcos/pull/2593 due to a regression in test stability. Because REX-Ray v0.9.0 can no longer be built from source, we're pulling in a [prebuilt binary from DC/OS 1.11.0](https://downloads.dcos.io/dcos/stable/packages/rexray/rexray--da7f17f8a4b772c0bac3f8d289a08abd4ff272b4.tar.xz).
REX-Ray integration test history:
* [master](https://teamcity.mesosphere.io/project.html?tab=testDetails&testNameId=-4317366092774327&projectId=DcOs_Open_Test_IntegrationTest&buildTypeId=DcOs_Open_Test_IntegrationTest_AwsCloudFormationSimple&branch_DcOs_Open_Test_IntegrationTest=%3Cdefault%3E)
* [This PR](https://teamcity.mesosphere.io/project.html?tab=testDetails&testNameId=-4317366092774327&projectId=DcOs_Open_Test_IntegrationTest&buildTypeId=DcOs_Open_Test_IntegrationTest_Aw …
> Downgrade REX-Ray 0.11.2 -> 0.9.0

- packages/adminrouter/extra/src/README.md
- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/lib/service.lua
- packages/adminrouter/extra/src/test-harness/tests/test_service.py
This PR makes it possible to configure `/service` endpoint upstream request URL rewriting basing on the `DCOS_SERVICE_REWRITE_REQUEST_URLS` label. See the Jira issue for details.
- https://jira.mesosphere.com/browse/DCOS-9032 `Adminrouter option to not rewrite URLs`
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/2570
> Admin Router: /service endpoint url rewriting is now configurable using the Marathon label

- CHANGES.md
- dcos_installer/backend.py
- gen/__init__.py
- gen/calc.py
- gen/tests/test_config.py
This PR fixes genconf to allow changing config values that are provided as files under `genconf/` as part of an upgrade. Without this PR, editing `genconf/detect_ip` and re-running genconf will create a new config package with an updated IP detect script, but with the same ID as the prior config package. Because the ID hasn't changed, Pkgpanda will assume it has the same contents as the config package currently present on cluster nodes, and reuse it instead of downloading the updated package. With this PR, the new config package will have a different ID, causing Pkgpanda to recognize that it is different and use it.
- [DCOS_OSS-2389](https://jira.mesosphere.com/browse/DCOS_OSS-2389) Upgrades Fails to …
> gen: Generate config packages with new IDs after editing files under genconf/

- pkgpanda/test_util.py
- pkgpanda/util.py
This changes `pkgpanda.util.write_string` to avoid a race condition as described in [DCOS-14199](https://jira.mesosphere.com/browse/DCOS-14199).
I have also applied this change to some related functions as a precaution.
I have stopped returning data from the functions as it appears that those return values are never used.
This also adds a test for `write_string` to enshrine the permission requirements and basic functionality of `write_string` (thanks @mhrabovcin for help). That test passes on `master` *and* with the changes here.
- [DCOS-14199](https://jira.mesosphere.com/browse/DCOS-14199) exhibitor.py try_shortcut() failed due to an empty file
```python
filename = 'foo.txt'
while True:
with …
```
> [DCOS-14199] Write strings to files atomically in pkgpanda.util

- packages/dcos-metrics/buildinfo.json
This change fixes an issue where metrics labels offered by the Prometheus producer could be prefixed with numbers, which is illegal. Prometheus would ignore those metrics, dropping data. We now prefix such labels with an underscore. 
- [DCOS_OSS-2360](https://jira.mesosphere.com/browse/DCOS_OSS-2360) Metric names can begin with numbers in dcos-metrics Prometheus endpoint
> [1.11] Bump dcos-metrics

- dcos_installer/backend.py
- gen/__init__.py
- gen/calc.py
- gen/tests/test_config.py
This is a 1.11 backport of #2724.
- [DCOS-21611](https://jira.mesosphere.com/browse/DCOS-21611) DC/OS Upgrades Fails to Update the agents fault-domain-detect script
> (1.11) gen: Generate config packages with new IDs after editing files under genconf/

- gen/dcos-config.yaml
In cases where the agent node is under heavy load, it can take more than
2 seconds (default executor reregistation timeout) for all executors
to reregister with an agent that just failed over. After the timeout,
the executors are explicitly removed and the tasks are marked as
TASK_GONE.
- [DCOS_OSS-2335](https://jira.mesosphere.com/browse/DCOS_OSS-2335) Increase executor reregistration timeout.
Manually tested with the app definition provided in the DC/OS ticket. …
> [1.11] Increase executor reregistration timeout to 10 seconds.

- gen/calc.py
- gen/dcos-config.yaml
- gen/tests/test_adminrouter_tls_conf.py
- packages/adminrouter/docker/adminrouter-tls-master.conf
This PR disables the 3DES bulk encryption algorithm and TLS 1.1 for Master Admin Router by default in DC/OS 1.11.
https://jira.mesosphere.com/browse/DCOS-21958
> [1.11] Disable the 3DES and TLS 1.1 for Master Admin Router by default.

- pkgpanda/test_util.py
- pkgpanda/util.py
**This is a backport of https://github.com/dcos/dcos/pull/2730 which has a Ship It label**
This changes `pkgpanda.util.write_string` to avoid a race condition as described in [DCOS-14199](https://jira.mesosphere.com/browse/DCOS-14199).
I have also applied this change to some related functions as a precaution.
I have stopped returning data from the functions as it appears that those return values are never used.
This also adds a test for `write_string` to enshrine the permission requirements and basic functionality of `write_string` (thanks @mhrabovcin for help). That test passes on `master` *and* with the changes here.
- [DCOS-14199](https://jira.mesosphere.com/browse/DCOS-14199) exhibitor.py …
> [DCOS-14199][1.11] Write strings to files atomically in pkgpanda.util

- packages/mesos/README.md
- packages/mesos/buildinfo.json
- packages/mesos/patches.json
This is a routine bump to the latest 1.5.x branch of Mesos.
[mesosphere/mesos diff](https://github.com/mesosphere/mesos/compare/b2eeb11ede805a7830cd6fb796d0b21a647aba04...0e3da451d379b7dd58b25bfb9ec3569a9b8eac87)
> [1.11] Bump Mesos to nightly 1.5.x aedbcfd

- gen/dcos-config.yaml
In cases where the agent node is under heavy load, it can take more than
2 seconds (default executor reregistation timeout) for all executors
to reregister with an agent that just failed over. After the timeout,
the executors are explicitly removed and the tasks are marked as
TASK_GONE.
- [DCOS_OSS-2335](https://jira.mesosphere.com/browse/DCOS_OSS-2335) Increase executor reregistration timeout.
Manually tested with the app definition provided in the DC/OS ticket. …
> [1.10] Increase executor reregistration timeout to 10 seconds.

- pkgpanda/test_util.py
- pkgpanda/util.py
**This is a backport of https://github.com/dcos/dcos/pull/2730 which has a Ship It label**
This changes `pkgpanda.util.write_string` to avoid a race condition as described in [DCOS-14199](https://jira.mesosphere.com/browse/DCOS-14199).
I have also applied this change to some related functions as a precaution.
I have stopped returning data from the functions as it appears that those return values are never used.
This also adds a test for `write_string` to enshrine the permission requirements and basic functionality of `write_string` (thanks @mhrabovcin for help). That test passes on `master` *and* with the changes here.
- [DCOS-14199](https://jira.mesosphere.com/browse/DCOS-14199) exhibitor.py …
> [DCOS-14199][1.10] Write strings to files atomically in pkgpanda.util

- packages/adminrouter/extra/src/README.md
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/includes/service-location.common.conf
- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/lib/service.lua
- packages/adminrouter/extra/src/test-harness/tests/test_service.py
This PR makes it possible to configure `/service` endpoint request buffering basing on the `DCOS_SERVICE_REQUEST_BUFFERING` label. See the Jira issue for details.
- https://jira.mesosphere.com/browse/DCOS-20269 `Request entity too large error`
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/2587
> Admin Router: Conditional request buffering for /service endpoint

- packages/dcos-checks/build
- packages/dcos-checks/buildinfo.json
This PR bumps dcos-checks for some internal refactoring.
- [DCOS-21728](https://jira.mesosphere.com/browse/DCOS-21728) dcos-checks: add check for cockroachdb 'underreplicated ranges'
___
> dcos-checks: bump for register of subcommands

- packages/dcos-history/extra/history/server_util.py
This is a 1.10 backport of #2829
- [DCOS_OSS-2422](https://jira.mesosphere.com/browse/DCOS_OSS-2422) test_history_service is failing on master
> (1.10) Fix flask-compress import

- packages/dcos-history/extra/history/server_util.py
This is a 1.11 backport of #2829
- [DCOS_OSS-2422](https://jira.mesosphere.com/browse/DCOS_OSS-2422) test_history_service is failing on master
> (1.11) Fix flask-compress import

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
This is a routine bump to the latest 1.4.x branch of Mesos.
[mesosphere/mesos diff](https://github.com/mesosphere/mesos/compare/178a8addd30f5f4e72c5aa3d61bc07e15e75fe87...621ac66716a8606c498c14cc57298af3f1b15597)
> [1.10] Bump Mesos to nightly 1.4.x 315d047

- gen/build_deploy/bash.py
This is backport of #2768 
When using XFS (only supported filesystem for lower level filesystems for Centos) the volumes must be mounted d_type support enabled (ftype=1). This requirement is documented here https://docs.mesosphere.com/1.10/installing/ent/custom/system-requirements/install-docker-centos/#requirements-and-recommendations. DC/OS installer currently does not enforce this and can lead to a lot of pain for users and customers if they discover this requirement after setting installing the cluster and having it operational for some time. Reformatting the volumes is not a trivial task. So If we short circuit the install of DC/OS if the requirement is not met we can save a lot of pain to the users and customers  …
> Add checks for ftype=1 for docker and mesos directories if using XFS

- packages/dcos-history/extra/history/server_util.py
- packages/metronome/buildinfo.json
Metronome bump 0.4.2 on DCOS 1.10.6
- [METRONOME-248](https://jira.mesosphere.com/browse/METRONOME-248)Metronome metrics breaking change
> Metronome 0.4.2 Bump for DCOS 1.10.next

- gen/dcos-config.yaml
In cases where the agent node is under heavy load, it can take more than
2 seconds (default executor reregistation timeout) for all executors
to reregister with an agent that just failed over. After the timeout,
the executors are explicitly removed and the tasks are marked as
TASK_GONE.
- [DCOS_OSS-2335](https://jira.mesosphere.com/browse/DCOS_OSS-2335) Increase executor reregistration timeout.
Manually tested with the app definition provided in the DC/OS ticket. …
> [1.9] Increase executor reregistration timeout to 10 seconds.

- packages/curl/buildinfo.json
This PR bumps curl from 7.48 to 7.59.0 in DC/OS 1.9
https://jira.mesosphere.com/browse/DCOS-21557
https://jira.mesosphere.com/browse/DCOS_OSS-2367
> [1.9] Bump curl from 7.48 to 7.59

- packages/adminrouter/extra/src/nginx.agent.conf
- packages/adminrouter/extra/src/nginx.master.conf
This PR is a backport from 1.10/1.11/master.
It aims to reduce the upper bound of Adminrouter Mesos state cache refresh to 25 + 5 seconds.
Before the TTL was 60 seconds (explicit) for agents and 60 seconds (implicit) for masters.
The resolver used here then caches DNS entries for at most 5 seconds.
- [DCOS-2388](https://jira.mesosphere.com/browse/DCOS_OSS-2388) Adminrouter DNS entry TTL override of 5 seconds OSS.
___
> [Ready for Review] Backport Adminrouter DNS entry TTL override of 5 seconds to 1.9 OSS

- pkgpanda/test_util.py
- pkgpanda/util.py
**This is a backport of https://github.com/dcos/dcos/pull/2730 which has a Ship It label**
This changes `pkgpanda.util.write_string` to avoid a race condition as described in [DCOS-14199](https://jira.mesosphere.com/browse/DCOS-14199).
I have also applied this change to some related functions as a precaution.
I have stopped returning data from the functions as it appears that those return values are never used.
This also adds a test for `write_string` to enshrine the permission requirements and basic functionality of `write_string` (thanks @mhrabovcin for help). That test passes on `master` *and* with the changes here.
- [DCOS-14199](https://jira.mesosphere.com/browse/DCOS-14199) exhibitor.py …
> [DCOS-14199][1.9] Write strings to files atomically in pkgpanda.util

- packages/mesos-modules/buildinfo.json
- packages/mesos/README.md
- packages/mesos/buildinfo.json
- packages/mesos/patches.json
This is a routine bump to the latest mesosphere/1.2.x branch of Mesos.
[mesosphere/mesos diff](https://github.com/mesosphere/mesos/compare/05ba66b1ea2d00f3d784ac732f95f237dff652a8...bf8d2f21f403d8650ee9beeed7f7f2e55b79fc6f)
> [1.9] Bump Mesos to nightly mesosphere/1.2.x 563f24c

- dcos_installer/test_backend.py
- gen/calc.py
- gen/dcos-config.yaml
- packages/adminrouter/extra/src/nginx.agent.conf
- packages/adminrouter/extra/src/nginx.master.conf
- packages/curl/buildinfo.json
- packages/dcos-history/extra/history/server_util.py
- packages/dcos-ui/buildinfo.json
- packages/mesos-modules/buildinfo.json
- packages/mesos/README.md
- packages/mesos/buildinfo.json
- packages/mesos/patches.json
- pkgpanda/test_util.py
- pkgpanda/util.py
* [1.9] Increase executor reregistration timeout to 10 seconds. #2696 
* Fixed bug in `calculate_ip_detect_public_contents()`.  #2731 
* [1.9] Bump curl from 7.48 to 7.59  #2757 
* [Ready for Review] Backport Adminrouter DNS entry TTL override of 5 seconds to 1.9 OSS #2772
* [DCOS-14199][1.9] Write strings to files atomically in pkgpanda.util  #2786 
* Bump dcos-ui 1.9.6 in 1.9 release  #2787
* [1.9] Bump Mesos to nightly mesosphere/1.2.x 563f24c #2807
> Merge Train for DC/OS 1.9.9

- packages/marathon/build
Adding Required Precondition for marathon startup
- [MARATHON-7390](https://jira.mesosphere.com/browse/MARATHON-7390) Marathon Unable to Connect to Zookeeper - No Retries.
> accessability to zk is requirement for a marathon start

- gen/dcos-config.yaml
In cases where the agent node is under heavy load, it can take more than
2 seconds (default executor reregistation timeout) for all executors
to reregister with an agent that just failed over. After the timeout,
the executors are explicitly removed and the tasks are marked as
TASK_GONE.
- [DCOS_OSS-2335](https://jira.mesosphere.com/browse/DCOS_OSS-2335) Increase executor reregistration timeout.
Manually tested with the app definition provided in the DC/OS ticket. …
> Increase executor reregistration timeout to 10 seconds.

- gen/calc.py
- packages/dcos-net/buildinfo.json
- packages/mesos-modules/buildinfo.json
Add MTU configuration for vtep1024.
- [DCOS_OSS-1529](https://jira.mesosphere.com/browse/DCOS_OSS-1529) Missing MTU configuration for VTEP1024
- [DCOS_OSS-728](https://jira.mesosphere.com/browse/DCOS_OSS-728) Create testcase for Mesos master failover with DC/OS overlay modules
- [DCOS_OSS-695](https://jira.mesosphere.com/browse/DCOS_OSS-695) Introduce timeouts for calls to docker deamon in DC/OS overlay module
- [DCOS-21919](https://jira.mesosphere.com/browse/DCOS-21919) dcos-mesos-modules build is broken …
> Add MTU configuration for vtep1024

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
- packages/mesos/patches.json
This is a routine bump to the latest master branch of Mesos.
It also changes 2 DC/OS specific cherry-picks.
1. Following [the recent change in UCR code](https://reviews.apache.org/r/62472/) an update of the cherry-pick related to the GPU isolator failure is required.
`a9f5ddb8614ef057537994f389eb7e19f0c85652` -> `7659c405f51c1771fd341c9fad34085982774014` 
2. Following [an update of the Web controllers in Apache Mesos](https://reviews.apache.org/r/65246/), an update of the cherry-pick affecting those controllers is also required.
`d523dba4ca02ad15c0ce2fb9a93a7a1d7ec0eedf` -> `b6d7b1f3ca61a536132b3e973c32dd695e181005` …
> [master] Bump Mesos to nightly master a1c6a7a

- gen/build_deploy/bash.py
- gen/calc.py
- packages/dcos-checks/buildinfo.json
DC/OS network components depend on `ifconfig`, and will fail if it's not installed. This PR adds a check to the advanced install script that causes it to fail if `ifconfig` is not available on the host. It also adds a poststart node check that will fail if `ifconfig` is not available. This should shorten the debug loop by preventing DC/OS from deploying to hosts without `ifconfig`.
- [DCOS_OSS-2395](https://jira.mesosphere.com/browse/DCOS_OSS-2395) Fail install if ifconfig isn't available
> Check that ifconfig is available on cluster nodes

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This is a port for 1.11. PR for master is available here https://github.com/dcos/dcos/pull/2843
This PR also includes a port of https://github.com/dcos/dcos/pull/2512
Improve integration test for dcos-diagnostics component.
An error log file inside the diagnostics bundle called `summaryErrorsReport.txt` should be empty.
- [DCOS-25670](https://jira.mesosphere.com/browse/DCOS-25670)
- N/A
___
**What is the …
> improve dcos-diagnostics integration test 1.11

- gen/calc.py
- gen/dcos-config.yaml
- gen/tests/test_adminrouter_tls_conf.py
- packages/adminrouter/docker/adminrouter-tls-master.conf
This PR disables the 3DES bulk encryption algorithm and TLS 1.1 for Master Admin Router by default in DC/OS 1.12/master.
https://jira.mesosphere.com/browse/DCOS-21958
It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, …
> [1.12/master] Disable the 3DES and TLS 1.1 for Master Admin Router by default in 1.12/master

- owners.json
This PR removes old entries from owners.json and also removes me from the list.
I am sorry but the amount of noise mergebot is generating is too high for me, trying to create Gmail filters is like playing cat and mouse. I find Jira and Github notifications too important to ignore them/filter them all. 
CC: @orsenthil @gpaul @adamtheturtle @jgehrcke @mhrabovcin @timaa2k @ahairape @sambatyon @jongiddy
> Prune old entries from owners.json, remove me from the list

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Improve integration test for dcos-diagnostics component.
An error log file inside the diagnostics bundle called `summaryErrorsReport.txt` should be empty.
- [DCOS-25670](https://jira.mesosphere.com/browse/DCOS-25670)
- N/A
___
All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-rev …
> improve dcos-diagnostics integration test

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- gen/tests/test_adminrouter_tls_conf.py
- owners.json
- packages/adminrouter/docker/adminrouter-tls-master.conf
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/python/windows.buildinfo.json
* [1.12/master] Disable the 3DES and TLS 1.1 for Master Admin Router by default in 1.12/master  #2796
* Use HTTPS (rather than SSH) in python buildinfo  #2812
* Metronome 0.4.2 bump on Master  #2827 
* Prune old entries from owners.json, remove me from the list #2836 
* improve dcos-diagnostics integration test #2843
> 1.12 Merge Train - May 8th

- packages/metronome/buildinfo.json
Cherry-pick of https://github.com/dcos/dcos/pull/2826 to 1.11.2.
> Metronome 0.4.2 bump on 1.11 [cherry-pick to 1.11.2]

- pkgpanda/test_util.py
`pkgpanda/test_util.py::test_write_string` was written before having Windows unit testing was enabled on PRs, and is thusly failing.
[DCOS_OSS-3508](https://jira.mesosphere.com/browse/DCOS_OSS-3508)- pkgpanda/test_util.py has muted Windows tests requiring investigation
> Mute `pkgpanda/test_util:test_write_string` on Windows

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
- DCOS_OSS-3496
[https://github.com/apache/mesos diff](https://github.com/apache/mesos/compare/a1c6a7a3c54518f97a34f28b1792885b928b948c...a981067d2dd4a1ce6be68d3fd5a7115ce47b3a24)
[https://github.com/dcos/dcos-mesos-modules diff](https://github.com/dcos/dcos-mesos-modules/compare/683d3c137ed66d6e9a7e5da622f62a7ce962d4d1...4061b9e036f90bf9ca8759059723904d3999d4e5)
> [master] Bump Mesos to nightly master a981067

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
[https://github.com/apache/mesos diff](https://github.com/apache/mesos/compare/aedbcfd5dc5b4352bf34088fa91d6ceeabcc641f...9a5a74902b6adc186d7ce304ccd0929ea0cad70a)
> [1.11] Bump Mesos to nightly 1.5.x 9a5a749

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
[https://github.com/apache/mesos diff](https://github.com/apache/mesos/compare/315d04743101de500063d1bd13c539f08ccf3699...6144242b80bbcd3c02e01d9c5f76715c1b872a06)
> [1.10] Bump Mesos to nightly 1.4.x 6144242

- cloud_images/CHANGELOG.md
- cloud_images/centos7/create_dcos_ami.sh
- cloud_images/centos7/packer.json
- cloud_images/lib/el7/configure_dcos_system.sh
- cloud_images/lib/el7/configure_grub.sh
- cloud_images/lib/el7/create_and_mount_rootfs.sh
- cloud_images/lib/el7/dcos_vol_setup.sh
- cloud_images/lib/el7/install_base_packages.sh
- cloud_images/lib/el7/install_dcos_required_packages.sh
- gen/build_deploy/aws.py
These changes provide a new set of AWS EC2 AMIs that support both fourth generation (i.e. `m4.*`) as well as fifth generation (i.e. `m5.*` and `c5.*`) instances types.
There are also some minor changes to the AMI build process, mainly the change of AWS region to us-east-1 and the used instance type to a somewhat smaller but sufficient one.
This Mesosphere internal JIRA ticket must be updated (ideally closed) in the moment this PR lands:
- [SRE-222](https://jira.mesosphere.com/browse/SRE-222)
> SRE-222: Builds AMIs with support for fifth gen EC2 instances

- gen/calc.py
Was previously 1s, which fails on large clusters due to the time spent getting `:5050/metrics/snapshot`. Running `time /opt/mesosphere/bin/dcos-checks --verbose --role master mesos-metrics` takes more than 4 seconds in some of our clusters.
- [DCOS-34593](https://jira.mesosphere.com/browse/DCOS-34593) (private)`:5050/metrics/snapshot` runtime block update
___
> Updated timeout of mesos_master_replog_synchronized check, now 30s (1.10 backport).

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
[https://github.com/apache/mesos diff](https://github.com/apache/mesos/compare/a981067d2dd4a1ce6be68d3fd5a7115ce47b3a24...285d82080748cd69044c226950274c7046048c4b)
[https://github.com/dcos/dcos-mesos-modules diff](https://github.com/dcos/dcos-mesos-modules/compare/4061b9e036f90bf9ca8759059723904d3999d4e5...af814bf5c7cbe42d10644f3214f1ad2a450390da)
> [master] Bump Mesos to nightly master 285d820

- gen/calc.py
Was previously 1s, which fails on large clusters due to the time spent getting `:5050/metrics/snapshot`. Running `time /opt/mesosphere/bin/dcos-checks --verbose --role master mesos-metrics` takes more than 4 seconds in some of our clusters.
- [DCOS-34593](https://jira.mesosphere.com/browse/DCOS-34593) (private)`:5050/metrics/snapshot` runtime block update
___
> Updated timeout of mesos_master_replog_synchronized check, now 30s (1.11 backport).

- CHANGES.md
- gen/build_deploy/aws.py
Testing CoreOS 1688.5.3 against 1.11.3 as well as the following networking fix for this version of CoreOS: #2834 
AMIs were retrieved from here (stable channel which is currently 1688.5.3): https://coreos.com/os/docs/latest/booting-on-ec2.html
JIRA ticket: https://jira.mesosphere.com/browse/DCOS_OSS-3548
> Testing CoreOS 1688.5.3

- packages/mesos/buildinfo.json
[https://github.com/apache/mesos diff](https://github.com/apache/mesos/compare/9a5a74902b6adc186d7ce304ccd0929ea0cad70a...c34f23e16270a8373a1e66d76b0eea1c35842c31)
> [1.11] Bump Mesos to nightly 1.5.x c34f23e

- packages/dcos-integration-test/extra/test_mesos.py
Mesos was modified so that it no longer logs information on tasks standard output, however, some tests relied in this functionality to verify the api to check the output of tasks.
The quick fix was to modify the task definition so that it writes something into its own standard output.
Note that this PR does not change the behavior of the current master, however no mesos bump can be done until this test is modified since all its bumps will fail on  `test_mesos.test_files_api()`.
- [DCOS_OSS-3558](https://jira.mesosphere.com/browse/DCOS_OSS-3558) Nightly Mesos bump breaks DC/OS tests due to expected stdout logging..
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref …
> Modifies test relying on mesos logging in the stdout of a task

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
[https://github.com/apache/mesos diff](https://github.com/apache/mesos/compare/c34f23e16270a8373a1e66d76b0eea1c35842c31...197c9105c2ed08f1529602f1ff72de846cde98c6)
[https://github.com/dcos/dcos-mesos-modules diff](https://github.com/dcos/dcos-mesos-modules/compare/325f2d99cdd6b65569424ce24ed27dc9f6d5f93e...7fa7ce9346e34aa6f770a27703ee74eb7920d8bb)
> [1.11] Bump Mesos to nightly 1.5.x 197c910

- packages/dcos-net/buildinfo.json
This bump fixes the issue wherein if a new agent re-uses the agent ip
of some old discontinued agent then it is able to join the cluster
- [DCOS_OSS-2421](https://jira.mesosphere.com/browse/DCOS_OSS-2421) Support recycling IP agent IP addresses without navstar running into issues
https://github.com/dcos/dcos-net/compare/4818716aa9d102958a50a67d79a6db2eafd6680c...2dcd3bf655fc6d382d16a418ec82699b5bae8446
https://github.com/dcos/lashup/compare/bed14d737e290ed92cf3bdaa4b73596c85f5bdd8...ad18f9c2fd25af847620681c903734783bad9a52 …
> Bumps dcos-net to include fix for IP recycle

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
* https://jira.mesosphere.com/browse/DCOS-37814  - Fixes - Mesos master crash when resources are very small
[https://github.com/apache/mesos diff](https://github.com/apache/mesos/compare/285d82080748cd69044c226950274c7046048c4b...abef72521a9a74fe4d6e7c796d6c99f02ad811dd)
[https://github.com/dcos/dcos-mesos-modules diff](https://github.com/dcos/dcos-mesos-modules/compare/af814bf5c7cbe42d10644f3214f1ad2a450390da...351315d5c4ce03e3c8a759093de5957929fa9f88)
> [master] Bump Mesos to nightly master abef725

- CHANGES.md
- packages/dcos-integration-test/extra/util/delete_ec2_volume.py
- packages/rexray/build
- packages/rexray/buildinfo.json
- packages/rexray/extra/dcos-rexray.service
This PR bumps REX-Ray from v0.9.0 to v0.11.2. It configures REX-Ray to operate in `DOCKER_LEGACY` mode as the newer version of REX-Ray switched to CSI-based logic. The REX-Ray developers seem to agree as REX-Ray's master branch was recently switched to `DOCKER_LEGACY` by default: https://github.com/rexray/rexray/commit/6162a4c0a35255414e0fb82e18a8ed44800d5749.
This PR also improves the `delete_ec2_volume.py` cleanup script by adding logging and better error handling.
- [DCOS_OSS-3597](https://jira.mesosphere.com/browse/DCOS_OSS-3597) Upgrade REX-Ray to v0.11.2
- …
> rexray: upgrade to v0.11.2

- CHANGES.md
- gen/build_deploy/bash.py
Fixes ftype=1 install time check for dcos-docker
https://github.com/dcos/dcos/pull/2768 breaks dcos-docker for very specific (rare but valid dcos-docker) configuration (https://jira.mesosphere.com/browse/DCOS_OSS-3549). This fixes that
If the device being used for docker root directory is not accessible the xfs_info check fails. I have added a block device check before xfs_info check to skip ftype=1 check
- [DCOS_OSS-3549](https://jira.mesosphere.com/browse/DCOS_OSS-3549) ftype=1 pre-flight check has broken dcos-docker for configurations using devicemapper 
- …
> Fix ftype=1 check for dcos-docker

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This bumps dcos-diagnostics to remove its check runner, which was moved to a separate component called dcos-check-runner. The dcos-check-runner component was added to DC/OS with https://github.com/dcos/dcos/pull/2921.
- [DCOS_OSS-3491](https://jira.mesosphere.com/browse/DCOS_OSS-3491) Separate check runner from dcos-diagnostics
> Remove dcos-diagnostics check runner

- dcos_installer/config.py
This removes outdated references to the web installer, which was removed from DC/OS in 1.12.
- [DCOS_OSS-3618](https://jira.mesosphere.com/browse/DCOS_OSS-3618) Genconf error message references nonexistent web installer
> Remove references to web installer in error messages

- packages/windows.treeinfo.json
Disable building `dcos-check-runner` package on Windows; it currently fails as it doesn't not include a `build.ps1` script.
> Exclude `dcos-check-runner` package on Windows

- CHANGES.md
- packages/dcos-check-runner/buildinfo.json
This bumps dcos-check-runner to pull in a new capability to run checks in parallel.
- [DCOS_OSS-2239](https://jira.mesosphere.com/browse/DCOS_OSS-2239) Run checks in parallel
N/A
> Run checks in parallel

- packages/mesos/buildinfo.json
- packages/mesos/patches.json
This is a routine bump to the latest mesosphere/1.2.x branch of Mesos.
[mesosphere/mesos diff](https://github.com/mesosphere/mesos/compare/bf8d2f21f403d8650ee9beeed7f7f2e55b79fc6f...1296f66a67cc498b522caae16c2617977592bd70)
> [1.9] Bump Mesos to nightly mesosphere/1.2.x cb79076

- CHANGES.md
- packages/dcos-integration-test/extra/util/delete_ec2_volume.py
- packages/rexray/build
- packages/rexray/buildinfo.json
- packages/rexray/extra/dcos-rexray.service
_Backport of https://github.com/dcos/dcos/pull/2882 to `1.10`. Contains unit file backport of https://github.com/dcos/dcos/pull/2593/commits/0b66b574f27005c41b5eaeb2b6f2261d6b575113#diff-b4738aec95eb5d18a80de948ec4ce039R16, too._
This PR bumps REX-Ray from v0.9.0 to v0.11.2. It configures REX-Ray to operate in `DOCKER_LEGACY` mode as the newer version of REX-Ray switched to CSI-based logic. The REX-Ray developers seem to agree as REX-Ray's master branch was recently switched to `DOCKER_LEGACY` by default: https://github.com/rexray/rexray/commit/6162a4c0a35255414e0fb82e18a8ed44800d5749.
This PR also improves the `delete_ec2_volume.py` cleanup script by adding logging and better error handling.
These DC/OS JIRA ticket(s) …
> rexray: upgrade to v0.11.2 [Backport to 1.10]

- CHANGES.md
- packages/dcos-integration-test/extra/util/delete_ec2_volume.py
- packages/rexray/build
- packages/rexray/buildinfo.json
- packages/rexray/extra/dcos-rexray.service
_Backport of https://github.com/dcos/dcos/pull/2882 to `1.11`. Contains unit file backport of https://github.com/dcos/dcos/pull/2593/commits/0b66b574f27005c41b5eaeb2b6f2261d6b575113#diff-b4738aec95eb5d18a80de948ec4ce039R16, too.__
This PR bumps REX-Ray from v0.9.0 to v0.11.2. It configures REX-Ray to operate in `DOCKER_LEGACY` mode as the newer version of REX-Ray switched to CSI-based logic. The REX-Ray developers seem to agree as REX-Ray's master branch was recently switched to `DOCKER_LEGACY` by default: https://github.com/rexray/rexray/commit/6162a4c0a35255414e0fb82e18a8ed44800d5749.
This PR also improves the `delete_ec2_volume.py` cleanup script by adding logging and better error handling.
These DC/OS JIRA …
> rexray: upgrade to v0.11.2 [Backport to 1.11]

- packages/mesos/buildinfo.json
[https://github.com/apache/mesos diff](https://github.com/apache/mesos/compare/197c9105c2ed08f1529602f1ff72de846cde98c6...fc8e9746ba5df1e19980ac57a384b7de73ff9e58)
> [1.11] Bump Mesos to nightly 1.5.x fc8e974

- CHANGES.md
- gen/build_deploy/bash.py
Fixes ftype=1 install time check for dcos-docker
https://github.com/dcos/dcos/pull/2822 breaks dcos-docker for very specific (rare but valid dcos-docker) configuration (https://jira.mesosphere.com/browse/DCOS_OSS-3549). This fixes that
If the device being used for docker root directory is not accessible the xfs_info check fails. I have added a block device check before xfs_info check to skip ftype=1 check
- [DCOS_OSS-3549](https://jira.mesosphere.com/browse/DCOS_OSS-3549) ftype=1 pre-flight check has broken dcos-docker for configurations using devicemapper 
- …
> Fix ftype=1 check for dcos-docker (DCOS_OSS-3549)

- packages/cosmos/buildinfo.json
Increase client payload limit when cosmos is talking to marathon.
- [DCOS-34435](https://jira.mesosphere.com/browse/DCOS-34435) Cosmos is limited to loading a max payload of 5MB when talking to /v2/apps from Marathon. Increase this limit.
___ …
> Bump cosmos to latest snapshot version

- packages/dcos-test-utils/buildinfo.json
Bump dcos-test-utils to latest version. This provides better debugging info and allows tests fixtures to be made more robust to network timeouts.
- [DCOS_OSS-3620](https://jira.mesosphere.com/browse/DCOS_OSS-3620) Log stderr on failing command execution
- [DCOS-38213](https://jira.mesosphere.com/browse/DCOS-38213) dcoscli fixture times-out while downloading CLI
___ …
> [DCOS_OSS-3620] Bump dcos-test-utils

- packages/adminrouter/extra/src/includes/server/master.conf
Installing packages through the CLI can occasionally timeout, especially on intermittent connections. The CLI exits with a message like: 
```
Error while fetching [https://172.17.0.2/package/resource?url=https://downloads.mesosphere.io/cli/binaries/linux/x86...61d301f571fe26883b5122d567ac4b79bae7febbd2090c81b6cdda523659eb43/dcos-enterprise-cli]: HTTP 504: "Gateway Time-out"
```
This change increases the timeout in the AdminRouter server, while it is acting as a proxy to Cosmos, to reduce the chance of this occurring.
- [DCOS-38258](https://jira.mesosphere.com/browse/DCOS-38258) Add a longer timeout for package loading
- …
> [master] Increase timeout for package download

- gen/dcos-config.yaml
- packages/dcos-check-runner/buildinfo.json
This fixes a bug where checks that are defined to run only on masters or agents do not get executed by the check runner.
- [DCOS-38309](https://jira.mesosphere.com/browse/DCOS-38309) DC/OS checks with role limitations are not being run by dcos-check-runner
N/A
> Don't skip checks that are limited to a specific role

- packages/adminrouter/windows.build.ps1
This PR is to address a Windows build break caused by the following merge
https://github.com/dcos/dcos/pull/2847#event-1699506333, which the current CI system does not take Windows build validation process
___
All PRs require 2 approvals using GitHub's …
> Fixed Windows-only build break when building AdminRouter for the Windows Agent

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/d22a3d7015567de11b3e96a5a686e65dea04aca1...22471b83a418e614b19a7ae50b73ee028dc7c363
https://github.com/dcos/dcos-mesos-modules/compare/351315d5c4ce03e3c8a759093de5957929fa9f88...15a95b259f86a927ee5c21627b38c51463433d86
> [master] Bump Mesos to nightly master 22471b8

- packages/adminrouter/extra/src/includes/server/master.conf
Back-port to 1.11 of https://github.com/dcos/dcos/pull/2983
Installing packages through the CLI can occasionally timeout, especially on intermittent connections. The CLI exits with a message like: 
```
Error while fetching [https://172.17.0.2/package/resource?url=https://downloads.mesosphere.io/cli/binaries/linux/x86...61d301f571fe26883b5122d567ac4b79bae7febbd2090c81b6cdda523659eb43/dcos-enterprise-cli]: HTTP 504: "Gateway Time-out"
```
This change increases the timeout in the AdminRouter server, while it is acting as a proxy to Cosmos, to reduce the chance of this occurring.
- [DCOS-38258](https://jira.mesosphere.com/browse/DCOS-38258) Add a longer timeout for package loading
- …
> [1.11] Increase timeout for package download

- packages/mesos/buildinfo.json
[https://github.com/apache/mesos diff](https://github.com/apache/mesos/compare/6144242b80bbcd3c02e01d9c5f76715c1b872a06...04f49674ca25fd0bea0ef4cd0d744429e9614a12)
> [1.10] Bump Mesos to nightly 1.4.x 04f4967

- packages/adminrouter/extra/src/includes/server/master.conf
Back-port to 1.10 of https://github.com/dcos/dcos/pull/2983
Installing packages through the CLI can occasionally timeout, especially on intermittent connections. The CLI exits with a message like: 
```
Error while fetching [https://172.17.0.2/package/resource?url=https://downloads.mesosphere.io/cli/binaries/linux/x86...61d301f571fe26883b5122d567ac4b79bae7febbd2090c81b6cdda523659eb43/dcos-enterprise-cli]: HTTP 504: "Gateway Time-out"
```
This change increases the timeout in the AdminRouter server, while it is acting as a proxy to Cosmos, to reduce the chance of this occurring.
- [DCOS-38258](https://jira.mesosphere.com/browse/DCOS-38258) Add a longer timeout for package loading
- …
> [1.10] Increase timeout for package download

- gen/aws/templates/cloudformation.json
Without this, agent nodes do not re-join the cluster after reboot.
This is due to our coreos-aws cloud-config where we expect a /dev/xvdb.
The time service is able to start before the cloud-config.yaml adds
the var-lib.mount unit. After reboot the problem shows up as the
units are on the disk at that point.
- [DCOS_OSS-3683](https://jira.mesosphere.com/browse/DCOS_OSS-3683) Agent node does not re-join the cluster after reboot for a standard CF template based cluster. …
> Added second EBS drive to agents and public agents (1.10 backport).

- packages/metronome/buildinfo.json
* Adds Docker Param support to Metronome for Jobs.
- [DCOS_OSS-3688](https://jira.mesosphere.com/browse/DCOS_OSS-3688) Release Metronome 0.3.6  on DCOS 1.9.
- [DCOS_OSS-2564](https://jira.mesosphere.com/browse/DCOS_OSS-2564) Allow Docker Params for Job Runs
- [DCOS_OSS-2519](https://jira.mesosphere.com/browse/DCOS_OSS-2519) Metronome allows creating jobs with no command and no image.
> Metronome 0.3.6 bump with docker params

- gen/aws/templates/cloudformation.json
Without this, agent nodes do not re-join the cluster after reboot.
This is due to our coreos-aws cloud-config where we expect a /dev/xvdb.
The time service is able to start before the cloud-config.yaml adds
the var-lib.mount unit. After reboot the problem shows up as the
units are on the disk at that point.
- [DCOS_OSS-3683](https://jira.mesosphere.com/browse/DCOS_OSS-3683) Agent node does not re-join the cluster after reboot for a standard CF template based cluster. …
> Added second EBS drive to agents and public agents (1.11 backport).

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- packages/marathon/build
- packages/marathon/extra/marathon.sh
Backport of 0fcc0828..589ef2cd / #2918
- post-installation environment variable configuration can now be placed in
/var/lib/dcos/marathon/environment
- JVM parameters can be specified via MARATHON_JAVA_ARGS
- environment.ip.marathon file is gone; instead we have a launching script to
set these vars
- Add some comments to init file to help users know where environment variables
can be placed
- Add docs at the top of env var files
- Allow DCOS config variables to be overridden
> (Backport) Allow customization of JAVA options for root Marathon, and other changes

- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/6144242b80bbcd3c02e01d9c5f76715c1b872a06...e7b117e0d9072a50756dd90e12d691af572aed7c
> [1.10] Bump Mesos to nightly 1.4.x e7b117e

- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
This is a backport of https://github.com/dcos/dcos/pull/2989 for 1.10
The lua code has been using ngx.timer.at() for the AR cache update. This can lead to the problem described in the JIRA ticket below. This PR replaces ngx.timer.at() with a more robust alternative of ngx.timer.every(), which also fixes the problem described in the JIRA ticket below.
https://jira.mesosphere.com/browse/DCOS-38248
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or …
> [1.10] Use ngx.timer.every() for the AR cache update

- packages/adminrouter/extra/src/lib/cache.lua
This PR increases the timeout of the Lua HTTP client from 10 to 60sec to accomodate for the longer response times from upstream DC/OS components (e.g. Mesos and Marathon). See the corresponding JIRA ticket on details.
https://jira.mesosphere.com/browse/DCOS-38323
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / …
> [1.10] Tuning the Lua HTTP client recv() timeout

- packages/marathon/buildinfo.json
Marathon bump to 1.5.10
- [MARATHON-8159](https://jira.mesosphere.com/browse/MARATHON-8159) Fixed a bug where `taskKillGracePeriodSeconds` parameter was updated incorrectly during a migration to 1.5.
- [DCOS-38317](https://jira.mesosphere.com/browse/DCOS-38317) Fixed a bug where Marathon was unable to restart an app with failing health checks and a persistent volume.
- [MARATHON-8236](https://jira.mesosphere.com/browse/MARATHON-8236) Fixed a bug where specifying a command-line parameter using a MARATHON_CMD prefix results in an error.
- [MARATHON-8283](https://jira.mesosphere.com/browse/MARATHON-8283) Added warning logging when any of the offer resources is zero.
- …
> Marathon bump 1.5.10

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
- packages/marathon/build
- packages/marathon/buildinfo.json
- packages/marathon/extra/marathon.sh
- packages/mesos/buildinfo.json
> PRs had merge conflict, and manual resolution was required to create this train.
Please review carefully.
----
#3029 - (Backport) Allow customization of JAVA options for root Marathon, and other changes
#3040 - [1.10] Use ngx.timer.every() for the AR cache update 
#3041 -  [1.10] Tuning the Lua HTTP client recv() timeout
#3044 - Marathon bump 1.5.10 
#3030 - [1.10] Bump Mesos to nightly 1.4.x e7b117e
> 1.10 Train

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- packages/marathon/build
- packages/marathon/extra/marathon.sh
Forwardport of 0fcc0828..589ef2cd / #2918
- post-installation environment variable configuration can now be placed in
/var/lib/dcos/marathon/environment
- JVM parameters can be specified via MARATHON_JAVA_ARGS
- environment.ip.marathon file is gone; instead we have a launching script to
set these vars
- Add some comments to init file to help users know where environment variables
can be placed
- Add docs at the top of env var files
- Allow DCOS config variables to be overridden
> [1.12] Allow customization of JAVA options for root Marathon, and other changes

- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
Add ExecStartPre step on Mesos agents for resource provider config dir.
Mesos agent expects the directory to be present when resource provider is enabled.
The config dir is under `/var/lib/dcos/mesos` instead of `/opt/mesopshere/etc` because this is a config directory that shouldn't be altered when during a Mesos package upgrade.
This is not a user facing change. They should not be aware of this change.
- [DCOS-38663](https://jira.mesosphere.com/browse/DCOS-38663) Enable storage features by default in DC/OS
___
**PLEASE FILL IN …
> Add ExecStartPre step on Mesos agents for resource provider config dir

- CHANGES.md
- packages/adminrouter/extra/src/includes/http/common.conf
This PR changes the Adminrouter `access_log` syslog facility from `local7` (nginx implicit default) to `daemon`.
Since `daemon` is the default syslog facility for journald logs that do not have a syslog facility assigned, all other components of DC/OS appear to `rsyslog` as logging to `daemon` and therefore end up under `/var/log/messages`. Now Adminrouter access_log are also found in `/var/log/messages` instead of `/var/log/boot.log` with the `rsyslog` default configuration on `CentOS 7`.
- [DCOS_OSS-3793)](https://jira.mesosphere.com/browse/DCOS_OSS-3793) Change Adminrouter access_log syslog logging facility to daemon.
- [DCOS-38622](https://jira.mesosphere.com/browse/DCOS-38622) set 'access_log …
> Change Adminrouter access_log logging facility to daemon

- packages/marathon/buildinfo.json
Include latest Marathon 1.4.12 release in to DC/OS 1.9
- [DCOS_OSS-3673](https://jira.mesosphere.com/browse/DCOS_OSS-3673) Include Marathon 1.4.12 in DC/OS 1.9.10
- Expose `containerPort` as `$PORT_NAME` in environment variables. (#5892)
- [MARATHON-8011](https://jira.mesosphere.com/browse/MARATHON-8011) Scaling to zero takes too much time in case of non-scaling related runspec changes (#5940)
- [MARATHON-8124](https://jira.mesosphere.com/browse/MARATHON-8124) Always unreserve resources for non-existing instances (#6072)
- [MARATHON-7751](https://jira.mesosphere.com/browse/MARATHON-7751) Do not start more instances than needed (#6054) 
- Many documentation improvements
- System tests and integration …
> Include Marathon 1.4.12 in DCOS 1.9.10

- packages/adminrouter/extra/src/common/http.conf
This PR changes the Adminrouter `access_log` syslog facility from `local7` (nginx implicit default) to `daemon`.
Since `daemon` is the default syslog facility for journald logs that do not have a syslog facility assigned, all other components of DC/OS appear to `rsyslog` as logging to `daemon` and therefore end up under `/var/log/messages`. Now Adminrouter access_log are also found in `/var/log/messages` instead of `/var/log/boot.log` with the `rsyslog` default configuration on `CentOS 7`.
- [DCOS_OSS-3793)](https://jira.mesosphere.com/browse/DCOS_OSS-3793) Change Adminrouter access_log syslog logging facility to daemon.
- [DCOS-38622](https://jira.mesosphere.com/browse/DCOS-38622) set 'access_log …
> Change Adminrouter access_log logging facility to daemon [Backport 1.9]

- CHANGES.md
- packages/adminrouter/extra/src/includes/http/common.conf
- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
- packages/dcos-metrics/buildinfo.json
- packages/dcos-net/buildinfo.json
- packages/mesos/buildinfo.json
> Manually Created.
(Please check for merge-conflicts resolved)
* #3054  - [1.11] Use ngx.timer.every() for the AR cache update
* #3058 - [1.11] Bump Mesos to nightly 1.5.x 2440c73
* #3061  - [1.11] Tuning the Lua HTTP client recv() timeout 
* #3072 - Change Adminrouter access_log logging facility to daemon [Backport 1.11]
* #3077 - [1.11] Bump dcos-net
* #2850 - [1.11] Bump DC/OS Metrics
> 1.11 Train 

- CHANGES.md
- packages/dcos-metrics/buildinfo.json
- [DCOS_OSS-2360](https://jira.mesosphere.com/browse/DCOS_OSS-2360) Metric names can begin with numbers in dcos-metrics Prometheus endpoint
- [DCOS_OSS-3304](https://jira.mesosphere.com/browse/DCOS_OSS-3304) Metrics emitted by containers do not contain tags from labels
- [DCOS-37452](https://jira.mesosphere.com/browse/DCOS-37452) Increase the mesos agent response timeout for dcos-metrics
- [DCOS-37451](https://jira.mesosphere.com/browse/DCOS-37451) Filter cosmos bookkeeping tags from metrics	
- [DCOS-38083](https://jira.mesosphere.com/browse/DCOS-38083) Statsd timers are reported incorrectly by dcos-metrics	 …
> [1.11] Bump DC/OS Metrics

- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
The lua code has been using ngx.timer.at() for the AR cache update. This can lead to the problem described in the JIRA ticket below. This PR replaces ngx.timer.at() with a more robust alternative of ngx.timer.every(), which also fixes the problem described in the JIRA ticket below.
https://jira.mesosphere.com/browse/DCOS-38248 …
> [1.11] Use ngx.timer.every() for the AR cache update

- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/fc8e9746ba5df1e19980ac57a384b7de73ff9e58...2440c7310627c835fe828aef6b28b8d072e7371c
> [1.11] Bump Mesos to nightly 1.5.x 2440c73

- packages/adminrouter/extra/src/lib/cache.lua
This is a forward-port of https://github.com/dcos/dcos/pull/3041
This PR increases the timeout of the Lua HTTP client from 10 to 60sec to accomodate for the longer response times from upstream DC/OS components (e.g. Mesos and Marathon). See the corresponding JIRA ticket for details.
https://jira.mesosphere.com/browse/DCOS-38323 …
> [1.11] Tuning the Lua HTTP client recv() timeout

- CHANGES.md
- packages/adminrouter/extra/src/includes/http/common.conf
This PR changes the Adminrouter `access_log` syslog facility from `local7` (nginx implicit default) to `daemon`.
Since `daemon` is the default syslog facility for journald logs that do not have a syslog facility assigned, all other components of DC/OS appear to `rsyslog` as logging to `daemon` and therefore end up under `/var/log/messages`. Now Adminrouter access_log are also found in `/var/log/messages` instead of `/var/log/boot.log` with the `rsyslog` default configuration on `CentOS 7`.
- [DCOS_OSS-3793)](https://jira.mesosphere.com/browse/DCOS_OSS-3793) Change Adminrouter access_log syslog logging facility to daemon.
- [DCOS-38622](https://jira.mesosphere.com/browse/DCOS-38622) set 'access_log …
>  Change Adminrouter access_log logging facility to daemon [Backport 1.11]

- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/22471b83a418e614b19a7ae50b73ee028dc7c363...81a7b5f687e0fc4b742cf484400e43c5fb56c58c
> [master] Bump Mesos to nightly master 81a7b5f

- packages/adminrouter/extra/src/lib/cache.lua
This is a forward-port of https://github.com/dcos/dcos/pull/3041
This PR increases the timeout of the Lua HTTP client from 10 to 60sec to accomodate for the longer response times from upstream DC/OS components (e.g. Mesos and Marathon). See the corresponding JIRA ticket for details.
https://jira.mesosphere.com/browse/DCOS-38323 …
> [1.12/master] Tuning the Lua HTTP client recv() timeout

- packages/adminrouter/extra/src/includes/main/agent.conf
- packages/adminrouter/extra/src/includes/main/common.conf
- packages/adminrouter/extra/src/includes/main/master.conf
- packages/adminrouter/extra/src/nginx.agent.conf
- packages/adminrouter/extra/src/nginx.master.conf
Back-port of https://github.com/dcos/dcos/pull/2866
This PR increases the limit on the number of connections (worker_connections) to 10K for Admin Router.
https://jira.mesosphere.com/browse/SOAK-80
___ …
> [1.11] Increase the limit on worker_connections to 10K for Agent AR

- CHANGES.md
- packages/dcos-checks/extra/dcos-checks-poststart.service
_This is a backport to `1.11` of https://github.com/dcos/dcos/pull/3083._
This PR changes the dcos-checks-poststart.service unit, which periodically runs dcos-checks, to execute as the `root` user. This service accepts no user interaction, serves no requests, and is expected to have any permission necessary in order to assert the health of any component in the system: it simulates the operator periodically checking her cluster. It makes no sense to restrict this service's permissions.
This has the happy side-effect of working around what appears to be a bug in journald where logs are sent to the main journal but are not tagged with the systemd unit that emitted them. This therefore greatly improves the debug experience …
> dcos-check-runner: run dcos-checks-poststart.service as root 

- gen/calc.py
- gen/dcos-config.yaml
- packages/mesos-modules/buildinfo.json
- packages/mesos/build
- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
- packages/mesos/extra/upgrade_cni.py
Currently, host-local ipam cni plugin uses a persistent location
on the disk as its data dir where it keeps the information about
allocated IP addresses. This leads to orphan IP addresses if
the agent reboots. This patch moves the data dir to a tmpfs location
so that all the allocated IP addresses are recycled upon agent reboot.
- [DCOS_OSS-3750](https://jira.mesosphere.com/browse/DCOS_OSS-3750) CNI module should store configuration on a tmpfs dir
___ …
> [backport][1.11] Adds dataDir to ucr bridge cni configuration

- packages/metronome/buildinfo.json
- [DCOS_OSS-3813](https://jira.mesosphere.com/browse/DCOS_OSS-3813) Release Metronome 0.4.3 on DCOS 1.10.
- [DCOS_OSS-2564](https://jira.mesosphere.com/browse/DCOS_OSS-2564) Docker Parameter Support.
- [DCOS_OSS-39324](https://jira.mesosphere.com/browse/DCOS_OSS-39324) Better Error Handling.
- [DCOS_OSS-39102](https://jira.mesosphere.com/browse/DCOS_OSS-39102) Graceful handing of Errors during task launching.
> Metronome 0.4.3 bump for 1.11

- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
The lua code has been using ngx.timer.at() for the AR cache update. This can lead to the problem described in the JIRA ticket below. This PR replaces ngx.timer.at() with a more robust alternative of ngx.timer.every(), which also fixes the problem described in the JIRA ticket below.
https://jira.mesosphere.com/browse/DCOS-38248 …
> [1.12/master] Use ngx.timer.every() for the AR cache update

- gen/calc.py
- gen/dcos-config.yaml
- packages/mesos-modules/buildinfo.json
- packages/mesos/build
- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
- packages/mesos/extra/upgrade_cni.py
Currently, host-local ipam cni plugin uses a persistent location
on the disk as its data dir where it keeps the information about
allocated IP addresses. This leads to orphan IP addresses if
the agent reboots. This patch moves the data dir to a tmpfs location
so that all the allocated IP addresses are recycled upon agent reboot.
- [DCOS_OSS-3750](https://jira.mesosphere.com/browse/DCOS_OSS-3750) CNI module should store configuration on a tmpfs dir
___ …
> Adds dataDir to ucr bridge cni configuration

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/81a7b5f687e0fc4b742cf484400e43c5fb56c58c...9147283171d761a4d38710f24ba654f8a96e325c
https://github.com/dcos/dcos-mesos-modules/compare/15a95b259f86a927ee5c21627b38c51463433d86...c8b12d7a32a718353417e687965d55a58d4e0c29
> [master] Bump Mesos to nightly master 9147283

- CHANGES.md
- packages/adminrouter/extra/src/includes/http/common.conf
This PR changes the Adminrouter `access_log` syslog facility from `local7` (nginx implicit default) to `daemon`.
Since `daemon` is the default syslog facility for journald logs that do not have a syslog facility assigned, all other components of DC/OS appear to `rsyslog` as logging to `daemon` and therefore end up under `/var/log/messages`. Now Adminrouter access_log are also found in `/var/log/messages` instead of `/var/log/boot.log` with the `rsyslog` default configuration on `CentOS 7`.
- [DCOS_OSS-3793)](https://jira.mesosphere.com/browse/DCOS_OSS-3793) Change Adminrouter access_log syslog logging facility to daemon.
- [DCOS-38622](https://jira.mesosphere.com/browse/DCOS-38622) set 'access_log …
> Change Adminrouter access_log logging facility to daemon [Backport 1.10]

- packages/metronome/buildinfo.json
- [DCOS_OSS-3813](https://jira.mesosphere.com/browse/DCOS_OSS-3813) Release Metronome 0.4.3 on DCOS 1.10.
- [DCOS_OSS-2564](https://jira.mesosphere.com/browse/DCOS_OSS-2564) Docker Parameter Support.
- [DCOS_OSS-39324](https://jira.mesosphere.com/browse/DCOS_OSS-39324) Better Error Handling.
- [DCOS_OSS-39102](https://jira.mesosphere.com/browse/DCOS_OSS-39102) Graceful handing of Errors during task launching.
> Metronome 0.4.3 bump for 1.10

- CHANGES.md
- packages/adminrouter/extra/src/includes/http/common.conf
- packages/adminrouter/extra/src/includes/main/agent.conf
- packages/adminrouter/extra/src/includes/main/common.conf
- packages/adminrouter/extra/src/includes/main/master.conf
- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/nginx.agent.conf
- packages/adminrouter/extra/src/nginx.master.conf
- packages/metronome/buildinfo.json
Manually Created Train
* #3036  Change Adminrouter access_log logging facility to daemon [Backport 1.10] 
* #3065 [1.10] Increased the limit on worker_connections to 10K for Agent AR
* #3066 Corrected comment to keep the docs readable
* #3071 Metronome 0.4.3 bump for 1.10
> 1.10 train2

- gen/calc.py
- gen/dcos-config.yaml
This patch adds a DC/OS configuration parameter called `log_offers`.
When this parameter is set to `true` (default value), the mesos masters
will log all offers sent to frameworks.
- [DCOS-38662](https://jira.mesosphere.com/browse/DCOS-38662) Make Mesos optionally log offers sent to frameworks.
___
> Added support for toggling the logging of offers sent by Mesos.

- gen/calc.py
This PR normalizes dcos-checks timeouts to either `1s` or `30s` depending on whether the check is supposed to succeed virtually instantly, or whether it may take a few seconds to complete. The `30s` option is taken from the fact that it is the current highest timeout and @timaa2k and I see no reason to go higher.
The associated Enterprise PR fixes a bug where the `mesos_master_replog_synchronized` never got updated from 1s to 30s due to the weird interaction between the Open and EE repositories.
- [DCOS-39571](https://jira.mesosphere.com/browse/DCOS-39571) dcos-checks-poststart: fix timeouts to fix flakiness
Other tickets related …
> gen/calc: normalize check timeouts

- gen/dcos-config.yaml
- [DCOS_OSS-39620](https://jira.mesosphere.com/browse/DCOS-39620) Bump task launch timeout to match mesos
> Metronome bump launch timeout 1.12

- gen/calc.py
- gen/dcos-config.yaml
- packages/mesos-modules/buildinfo.json
- packages/mesos/build
- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
- packages/mesos/extra/upgrade_cni.py
Currently, host-local ipam cni plugin uses a persistent location
on the disk as its data dir where it keeps the information about
allocated IP addresses. This leads to orphan IP addresses if
the agent reboots. This patch moves the data dir to a tmpfs location
so that all the allocated IP addresses are recycled upon agent reboot.
- [DCOS_OSS-3750](https://jira.mesosphere.com/browse/DCOS_OSS-3750) CNI module should store configuration on a tmpfs dir
___ …
> [Backport][1.10] Adds dataDir to ucr bridge cni configuration

- packages/marathon/build
Backport of #1690
Adding Required Precondition for marathon startup
- MARATHON-7390 Marathon Unable to Connect to Zookeeper - No Retries.
> 1.10: Accessibility to zk is a requirement for Marathon to start

- gen/dcos-config.yaml
This is a fix of previously broken update.
- [DCOS_OSS-39620](https://jira.mesosphere.com/browse/DCOS_OSS-39620) Bump task launch timeout to match mesos
> Bump the timeout to 10 minutes

- CHANGES.md
- packages/cni/buildinfo.json
- packages/mesos-modules/buildinfo.json
1. Docker isolates its networks by adding an explicit DROP iptables rules for any cross communication. However, Overlay (which uses Docker network) allows seamless communication among Docker networks. Overlay by-passes Docker isolation by adding an explicit RETURN as the first iptables rule in the chain. However, due to a bug, Overlay missed adding that rule if Docker network is already
present. This patch fixes that issue
2. Bump cni plugin version to v0.7.1 (latest cni plugin release)
- [DCOS_OSS-3697](https://jira.mesosphere.com/browse/DCOS_OSS-3697) Connectivity between bridged and overlay networks broken
- [DCOS_OSS-3841](https://jira.mesosphere.com/browse/COPS-3474) Update CNI plugins to latest …
> Fixes issue with iptables rule in DC/OS overlay

- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/9147283171d761a4d38710f24ba654f8a96e325c...9af920c75d1fcd001be86c419a418b93d5bf0cf0
> [master] Bump Mesos to nightly master 9af920c

- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
- packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch
- packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0005-Displayed-resource-provider-resources-in-GET_RESOURC.patch
- packages/mesos/extra/patches/0006-Improved-logging-for-offers-and-inverse-offers.patch
This patch adds a DC/OS configuration parameter called `log_offers`.
When this parameter is set to `true` (default value), the mesos masters
will log all offers sent to frameworks.
- [DCOS-38662](https://jira.mesosphere.com/browse/DCOS-38662) Make Mesos optionally log offers sent to frameworks.
___
> [1.11] Added a Mesos patch that makes it possible to enable offer logging.

- packages/marathon/build
Backport of #1690
Adding Required Precondition for marathon startup
- MARATHON-7390 Marathon Unable to Connect to Zookeeper - No Retries.
> 1.11: Accessibility to zk is requirement for a marathon start

- gen/dcos-config.yaml
- packages/bootstrap/extra/dcos_internal_utils/cli.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/telegraf/build
- packages/telegraf/buildinfo.json
- packages/telegraf/extra/dcos-telegraf.service
- packages/telegraf/extra/start_telegraf.sh
- packages/windows.treeinfo.json
This PR adds a new `dcos-telegraf` component, intended to eventually replace `dcos-metrics` in 1.12. `dcos-metrics` will be removed in a later PR once `dcos-telegraf` is ready to replace it.
This PR configures Telegraf to collect CPU and memory metrics from hosts, and then discard them. Further PRs will configure Telegraf to collect more metrics. Outputs will be added to replace `dcos-metrics` when it's removed in a later PR.
- [DCOS_OSS-3715](https://jira.mesosphere.com/browse/DCOS_OSS-3715) Create a build script for telegraf
> Add Telegraf as a DC/OS component

- owners.json
The security team has been taking the responsibility of acting as shepherds to land PR's into DC/OS, however only two members of the team have ownership status, causing them to always stay involved in the shepherding of PR's, therefore this adds some extra members of the team to the owners entry so that the load can be reduced on those members with ownership.
New members are:
@sambatyon
@jongiddy 
@timaa2k 
___ …
> Adding some members of the security team to `owners.json`

- CHANGES.md
- packages/dcos-ui/build
- packages/dcos-ui/buildinfo.json
This PR updates DC/OS UI to version `master+v2.3.0` previous release was `v1.12.0-rc.1`. we changed the way we integrate into DC/OS between these changes, which is the reason for the new version number.
included in this bump is everything between these tags: 
https://github.com/dcos/dcos-ui/compare/v1.12.0-rc.1...master+v2.3.0
- [DCOS_OSS-1550](https://jira.mesosphere.com/browse/DCOS_OSS-1550) - enable service endpoints on ucr
- [DCOS_OSS-1563](https://jira.mesosphere.com/browse/DCOS_OSS-1563) - Update npm
- [DCOS_OSS-1564](https://jira.mesosphere.com/browse/DCOS_OSS-1564) - Update webpack
- [DCOS_OSS-2185](https://jira.mesosphere.com/browse/DCOS_OSS-2185) - Update jest
- …
> chore(dcos-ui): bump DC/OS UI v2.3.0

- packages/dcos-cni/build
The dcos-cni build system uses the latest glide version. However, recently there was a bug introduced in the latest glide version. To have predictable build, this patch locks the glide version. Idea is to control the build-tools to produce predictable builds.
- [DCOS-39841](https://jira.mesosphere.com/browse/DCOS-39841) Unable to build dcos-cni package
___ …
> locks the glide version to fix build issue with the latest version

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/74a6f3cdb8206b41f96e1ebf5981783ea999c250...3ce0e64ba1d357c0894820f1ced9d51fa68484a7
https://github.com/dcos/dcos-mesos-modules/compare/95c2d1dd95bd848d15c687fb8b31b6ba52e1ac25...2ad4a4156614ca6dd096b23fbebaf3a915836f0d
> [1.11] Bump Mesos to nightly 1.5.x 3ce0e64

- packages/java/buildinfo.json
Backport of https://github.com/dcos/dcos/pull/3224
Update java to version 1.8.0_181 which includes security updates.
- [DCOS_OSS-3932](https://jira.mesosphere.com/browse/DCOS_OSS-3932) [1.11] packages/java: Update java to version 1.8.0_181
> [1.11] packages/java: Update Java to 8u181 version

- packages/java/buildinfo.json
Backport of https://github.com/dcos/dcos/pull/3224
Update java to version 1.8.0_181 which includes security updates.
- [DCOS_OSS-3933](https://jira.mesosphere.com/browse/DCOS_OSS-3933) packages/java: Update java to version 1.8.0_181
> [1.10] packages/java: Update Java to 8u181 version

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This PR adds folowing information to diagnostics bundle
* [`/quota`](http://mesos.apache.org/documentation/latest/endpoints/master/quota/)
* [`/containers`](http://mesos.apache.org/documentation/latest/endpoints/slave/containers/)
* [`/proc/[cmdline|cpuinfo|meminfo]`](http://man7.org/linux/man-pages/man5/proc.5.html) – additional hardware infro
* [`ps aux www`](http://man7.org/linux/man-pages/man1/ps.1.html) – lists all proceses with wide information about them
> Add information to diagnostics bundle

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Extract common code responsible for searching expected files
in diagnostic bundle to a function `verify_archived_items`.
> Remove duplicated code in dcos diagnostics test

- CHANGES.md
- packages/exhibitor/extra/start_exhibitor.py
Backport of #3209 
This PR aims to exit the bootstrap on a static Exhibitor backend if the IP returned by the ip-detect script does not match any of the IPs configured in the config.yaml master list.
- [DCOS_OSS-3938](https://jira.mesosphere.com/browse/DCOS_OSS-3938) Static Exhibitor backend bootstrap check: IP returned by ip-detect is contained in configured master list.
- [COPS-3485](https://jira.mesosphere.com/browse/COPS-3485) Exhibitor start script accepts invalid ip address for hostname resulting in loss of zookeeper myid cfg file.
This was tested manually using dcos-e2e with a valid and invalid custom ip-detect script.
___
> [Backport 1.10] Add bootstrap ip-detect check for static backend

- packages/marathon/extra/marathon.sh
- [MARATHON-8361](https://jira.mesosphere.com/browse/MARATHON-8361) Enable support for Mesos maintenance mode by default.
> Marathon Maintenance mode on by default for DCOS

- packages/dcos-cni/build
The dcos-cni build system uses the latest glide version. However, recently there was a bug introduced in the latest glide version. To have predictable build, this patch locks the glide version. Idea is to control the build-tools to produce predictable builds.?
- [DCOS-39841](https://jira.mesosphere.com/browse/DCOS-39841) Unable to build dcos-cni package
___ …
> [Backport][1.10] locks the glide version to fix build issue

- CHANGES.md
- packages/cni/buildinfo.json
1. Bump cni plugin version to v0.7.1 (latest cni plugin release)
-  [DCOS_OSS-3841](https://jira.mesosphere.com/browse/DCOS_OSS-3841) Update CNI plugins to latest release
- [DCOS-40162](https://jira.mesosphere.com/browse/DCOS-40162) CNI bridge plugin DEL might fail
___ …
> [Backport 1.11] bump cni plugins version to v0.7.1

- packages/dcos-cni/build
The dcos-cni build system uses the latest glide version. However, recently there was a bug introduced in the latest glide version. To have predictable build, this patch locks the glide version. Idea is to control the build-tools to produce predictable builds.
- [DCOS-39841](https://jira.mesosphere.com/browse/DCOS-39841) Unable to build dcos-cni package
___ …
> [Backport][1.11] locks the glide version to fix build issue 

- CHANGES.md
- packages/exhibitor/extra/start_exhibitor.py
Backport of #3209 
This PR aims to exit the bootstrap on a static Exhibitor backend if the IP returned by the ip-detect script does not match any of the IPs configured in the config.yaml master list.
- [DCOS_OSS-3937](https://jira.mesosphere.com/browse/DCOS_OSS-3937) Static Exhibitor backend bootstrap check: IP returned by ip-detect is contained in configured master list.
- [COPS-3485](https://jira.mesosphere.com/browse/COPS-3485) Exhibitor start script accepts invalid ip address for hostname resulting in loss of zookeeper myid cfg file.
This was tested manually using dcos-e2e with a valid and invalid custom ip-detect script.
___
> [Backport 1.11] Add bootstrap ip-detect check for static backend

- CHANGES.md
Adds missing release note for https://github.com/dcos/dcos/pull/3225.
Update java to version 1.8.0_181 which includes security updates.
- [DCOS_OSS-3932](https://jira.mesosphere.com/browse/DCOS_OSS-3932) [1.11] packages/java: Update java to version 1.8.0_181
> [1.11] changelog: Add Java update note

- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/3ce0e64ba1d357c0894820f1ced9d51fa68484a7...852e27afb36bdebd822b89722d13df6ee73f139d
> [1.11] Bump Mesos to nightly 1.5.x 852e27a

- packages/marathon/build
Backport of #1690
Adding Required Precondition for marathon startup
- MARATHON-7390 Marathon Unable to Connect to Zookeeper - No Retries.
> 1.9: Accessibility to zk is a requirement for Marathon to start

- CHANGES.md
- gen/dcos-config.yaml
- packages/adminrouter/extra/src/docs/api/nginx.agent.html
- packages/adminrouter/extra/src/docs/api/nginx.agent.yaml
- packages/adminrouter/extra/src/docs/api/nginx.master.html
- packages/adminrouter/extra/src/docs/api/nginx.master.yaml
- packages/adminrouter/extra/src/includes/http/common.conf
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/includes/server/open/agent.conf
- packages/adminrouter/extra/src/includes/server/open/master.conf
- packages/adminrouter/extra/src/lib/auth/open.lua
- packages/adminrouter/extra/src/test-harness/modules/mocker/common.py
- packages/adminrouter/extra/src/test-harness/tests/test_generic.config.yml
- packages/dcos-check-runner/build
- packages/dcos-check-runner/buildinfo.json
- packages/dcos-check-runner/extra/dcos-checks-api.service
- packages/dcos-check-runner/extra/dcos-checks-api.socket
- packages/dcos-check-runner/extra/dcos-checks-poststart.service
- packages/dcos-integration-test/extra/test_checks.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-integration-test/extra/test_misc.py
This adds an API for DC/OS checks at `/system/checks/` on all cluster nodes.
- [DCOS_OSS-1406](https://jira.mesosphere.com/browse/DCOS_OSS-1406) Checks runner HTTP API
N/A
> Add checks API

- packages/marathon/buildinfo.json
- [DCOS_OSS-3979](https://jira.mesosphere.com/browse/DCOS_OSS-3979) Marathon 1.6.544 bump on DC/OS 1.11.
- [MARATHON-7568](https://jira.mesosphere.com/browse/MARATHON-7568) /v2/info leak some ZK credentials
- [MARATHON-7390](https://jira.mesosphere.com/browse/MARATHON-7390) Marathon Unable to Connect to Zookeeper - No Retries
- [MARATHON-8084](https://jira.mesosphere.com/browse/MARATHON-8084) Properly forward HTTP requests from proxy
- [PR-6445](https://github.com/mesosphere/marathon/pull/6445) Fix broken offer rejection statistics when maintenance mode is enabled 
- …
> Marathon 1.6.544 bump on DC/OS 1.11

- packages/bootstrap/extra/dcos_internal_utils/cli.py
DC/OS Telegraf needs the `/var/lib/dcos/cluster-id` file in order to start. Without this, if no other service is creating the `cluster-id` file, the service will just continuously restart.
Usually one does not see any issues if they have `dcos-metrics` enabled. Since `dcos-metrics` service is not mandatory we need the following fix so `dcos-telegraf` service can be able to start.
Fix bug for DC/OS Telegraf.
- [DCOS_OSS-3947](https://jira.mesosphere.com/browse/DCOS_OSS-3947) DC/OS Telegraf missing bootstrap action.
> Implement bootstrap methods for telegraf

- packages/dcos-integration-test/extra/test_networking.py
Purge proxy app.
- [DCOS-39700](https://jira.mesosphere.com/browse/DCOS-39700) test_networking.test_vip ALWAYS failing on AWS Onprem w/ Static Backend and Security Strict
___ …
> test_vip: purge proxy app

- CHANGES.md
- packages/dcos-history/extra/history/server_util.py
- packages/dcos-history/extra/test_history_service.py
dcos-history used a common method for creating the headers used to make
requests to mesos (which could have an Authorization header set with a token)
and making responses to the client.
This led to the auth token being leaked in the header.
- [DCOS-40373](https://jira.mesosphere.com/browse/DCOS-40373) History service returns its auth token in the header
> [1.11] Prevent dcos-history leaking auth tokens 

- packages/dcos-integration-test/extra/test_networking.py
Purge proxy app.
- [DCOS-39700](https://jira.mesosphere.com/browse/DCOS-39700) test_networking.test_vip ALWAYS failing on AWS Onprem w/ Static Backend and Security Strict
___ …
> [1.11] test_vip: purge proxy app

- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/852e27afb36bdebd822b89722d13df6ee73f139d...eacabd70c5d2bdb3269712348cfcebab7fdddbe9
> [1.11] Bump Mesos to nightly 1.5.x eacabd7

- packages/dcos-history/extra/history/server_util.py
- packages/dcos-history/extra/test_history_service.py
dcos-history used a common method for creating the headers used to make
requests to mesos (which could have an Authorization header set with a token)
and making responses to the client.
This led to the auth token being leaked in the header.
- [DCOS-40373](https://jira.mesosphere.com/browse/DCOS-40373) History service returns its auth token in the header
> [1.9] Prevent dcos-history leaking auth tokens

- packages/marathon/build
Bumping a couple of timeouts.
- [DCOS-39290](https://jira.mesosphere.com/browse/DCOS_OSS-39290) Bump Marathon's max_instances_per_offer, task_launch_confirm_timeout, task_launch_timeout, and task_reservation_timeout
> [1.9] Bump Martahon's task_launch_confirm and task_reservation timeouts

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/84749967a1c1384f75c3c017bda45a85eea67787...9127c792c5a20aee2f31a2e56854c2490a9ca608
> [master] Bump Mesos to nightly master 9127c79

- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/eacabd70c5d2bdb3269712348cfcebab7fdddbe9...dd68c0bfb24354d4a0dbad252e1986b33aa9cac6
> [1.11] Bump Mesos to nightly 1.5.x dd68c0b

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This is only for 1.12 OSS I will backport and do a PR for EE after this gets approved
Get following additional things in a diag bundle 
1) Have dmesg with human readable timestamp
2) `timedatectl` for ruling out time sync issues 
3) Get distro version to rule out untested distro bugs
4) Get DC/OS systemd unit status
5) /v2/pods marathon endpoint
Reduced back and forth while debugging cluster issues since more data is collected in the bundle
- [DCOS_OSS-3861](https://jira.mesosphere.com/browse/DCOS_OSS-3861) Add more diagnostics data(e.g. timestamp for dmesg, distro version, systemd unit status etc) into the bundle
If you are …
> Add timestamp for dmesg, distro version, timedatectl and systemd unit status to diag bundle

- packages/mesos/extra/make_disk_resources.py
This concerns agents and the file `/var/lib/dcos/mesos-resources`.
We previously used the free space on the agent's mounted volumes
when using `make_disk_resources.py` to create the Mesos resources
file.
We recently saw that the Mesos agent would not restart due to this
behavior for a specific case: a mount volume is used on an agent
by a framework, the agent is stopped and a new volume is mounted.
This is because, when adding an agent, we create again the Mesos
resources file and, if a mount volume is used, its free disk space
will have decreased. Mesos will then not accept to restart as it
cannot find the volume (due to the change of value).
To fix this, we now use a cache to know what was the original free
amount of disk space available on the mount volumes. When the Mesos
resources …
> Check cache when creating Mesos resources using make_disk_resources.py.

- gen/calc.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_misc.py
Currently in many places marathon port is hardcoded to
8080. There is no easy way to parametrize this.
This commit adds `marathon_port: 8080` variable in calc
and use this value in config.
This change will allow us to keep OSS and EE configs
as similar as possible.
- [DCOS_OSS-3963](https://jira.mesosphere.com/browse/DCOS_OSS-3963) Parametrize marathon port in dcos config.
> Create `marathon_port` variable in config

- packages/dcos-test-utils/buildinfo.json
Bumps dcos-test-utils version to include support for Windows nodes
https://github.com/dcos/dcos-test-utils/pull/56
> Bumping dcos-test-utils version

- CHANGES.md
- packages/dcos-ui/buildinfo.json
Many changes on DC/OS UI
[DCOS_OSS-3801](https://jira.mesosphere.com/browse/DCOS_OSS-3801) - Support docker parameters in Metronome jobs.
[DCOS-37650](https://jira.mesosphere.com/browse/DCOS-37650) - change default request error message
[DCOS_OSS-3992](https://jira.mesosphere.com/browse/DCOS_OSS-3992) - getUsedResources not applicable to Service
[DCOS-40673](https://jira.mesosphere.com/browse/DCOS-40673) - prevent header bar from overlapping popup-like ui
[DCOS-40353](https://jira.mesosphere.com/browse/DCOS-40353) - update list/grid toggle style
[DCOS-40495](https://jira.mesosphere.com/browse/DCOS-40495) -  Remove the (Local) addition when the local region is "N/A" …
> chore(dcos-ui): bump DC/OS UI master+v2.14.0

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
1.10 backport for https://github.com/dcos/dcos/pull/3148
Get following additional things in a diag bundle 
1) Have dmesg with human readable timestamp
2) `timedatectl` for ruling out time sync issues 
3) Get distro version to rule out untested distro bugs
4) Get DC/OS systemd unit status
5) /v2/pods marathon endpoint
Reduced back and forth while debugging cluster issues since more data is collected in the bundle
- [DCOS_OSS-3861](https://jira.mesosphere.com/browse/DCOS_OSS-3861) Add more diagnostics data(e.g. timestamp for dmesg, distro version, systemd unit status etc) into the bundle
If you are changing components or packages in …
> [1.10] Add timestamp for dmesg, distro version, timedatectl, systemd unit status and pods endpoint to diag bundle

- CHANGES.md
- packages/dcos-history/extra/history/server_util.py
- packages/dcos-history/extra/test_history_service.py
dcos-history used a common method for creating the headers used to make
requests to mesos (which could have an Authorization header set with a token)
and making responses to the client.
This led to the auth token being leaked in the header.
- [DCOS-40373](https://jira.mesosphere.com/browse/DCOS-40373) History service returns its auth token in the header
> [1.10] Prevent dcos-history leaking auth tokens

- build_local.sh
Fix the release create step
**Before this change**
```
[10:26:03]	+ release create --noop --local root local_build default installer
[10:26:04]	usage: release [-h] [--noop] [--local] [-c CONFIG]
[10:26:04]	               {promote,create,create-installer} ...
[10:26:04]	release: error: unrecognized arguments: --noop --local
[10:26:04]	Process exited with code 2
[10:26:04]	Process exited with code 2
[10:26:04]	Step build_teamcity (Command Line) failed
```
**After this change**
```
Successfully installed dcos-image
++ whoami
+ release --noop --local create senthil local_build default installer
starting: Building packages
starting: dcos/dcos-builder (adminrouter)
```
> Fix the release create stage.

- packages/mesos/buildinfo.json
- [DCOS-41224](https://jira.mesosphere.com/browse/DCOS-41224) Removing rootfs mounts may fail with EBUSY.
- [MESOS-9196](https://issues.apache.org/jira/browse/MESOS-9196) Removing rootfs mounts may fail with EBUSY.
___
> Bumped Mesos SHA for dc/os 1.11.5 container cleanup EBUSY fix. 

- packages/telegraf/extra/dcos-telegraf.service
Previously, the 'dcos-telegraf.service' file was creating and adding
permissions to '/run/dcos/telegraf' using absolute paths to 'mdkir',
'chmod', and 'chown' commands under '/usr/bin'. Unfortunately, these
commands don't exist at this path in Ubunutu 16.04 (they exist under
'/bin' instead). Likewise, these commands don't exist under '/bin'
on CentOS or CoreOS, leaving us in a bit of a conundrum if we want to
have a single service file that works cross-platform.
In order to make this work cross-platform, we now introduce a level of
indirection through '/bin/bash' (which exists on all platforms) and
allow it to access 'mkdir', 'chmod', and 'chown' in its PATH, regardless
of where these commands exist. …
> Fix unhealthy dcos-telegraf service on Ubuntu-16.04

- CHANGES.md
- packages/dcos-history/extra/history/server_util.py
- packages/dcos-history/extra/test_history_service.py
dcos-history used a common method for creating the headers used to make
requests to mesos (which could have an Authorization header set with a token)
and making responses to the client.
This led to the auth token being leaked in the header.
- [DCOS-40373](https://jira.mesosphere.com/browse/DCOS-40373) History service returns its auth token in the header
> Prevent dcos-history leaking auth tokens

- packages/flask/buildinfo.json
https://jira.mesosphere.com/browse/DCOS-41370 -  Uncached build on Master fails to download flask-compress package
> Fix flask-compress build.

- packages/dcos-integration-test/extra/test_packaging.py
The `poll_marathon_for_app_deployment()` method was replaced by `wait_for_deployments_complete()` method in dcos-test-utils.
JIRA: https://jira.mesosphere.com/browse/DCOS-41198
> Replaced poll_marathon_for_app_deployment method for test_packaging_api.

- packages/mesos-modules/buildinfo.json
Coreos 1800.7.0 comes with default docker version of 18.x which has modified its iptables CHAIN names from DOCKER-ISOLATION to DOCKER-ISOLATION-STAGE-1 and DOCKER-ISOLATION-STAGE-2 which broke mesos overlay module. This patch detects the CHAIN name before applying the iptables rule so that it could work for both old and newer docker versions.
- [DCOS_OSS-3707](https://jira.mesosphere.com/browse/DCOS_OSS-3707) Update to CoreOS v1800.7 leads to networking failure in DC/OS
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE …
> [Backport] [1.11] bump mesos-module to include the fix for coreos 1800.7.0

- packages/exhibitor/buildinfo.json
Bump ZooKeeper for bugixes / reliability improvements.
https://jira.mesosphere.com/browse/DCOS_OSS-4104
> exhibitor package: bump ZooKeeper to 3.4.13 release

- packages/telegraf/extra/start_telegraf.sh
This PR fixes an issue where telegraf could crash-loop on agents. 
- [DCOS-41747](https://jira.mesosphere.com/browse/DCOS-41747) Telegraf dcos_statsd plugin cannot listen on its assigned socket file, causing a crash-loop
- [SOAK-119](https://jira.mesosphere.com/browse/SOAK-119)
> Ensure that statsd socket is cleaned up before launching telegraf

- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/dd68c0bfb24354d4a0dbad252e1986b33aa9cac6...5a7ad47e8fc1a14101e47a29eb8e7e2a20d959c5
> [1.11] Bump Mesos to nightly 1.5.x 5a7ad47

- CHANGES.md
- packages/marathon/buildinfo.json
- [DCOS_OSS-41716](https://jira.mesosphere.com/browse/DCOS-41716) Bump Marathon for 1.11.6.
- [DCOS-37999](https://jira.mesosphere.com/browse/DCOS-37999) Loosen constraint validation during migration.
- [MARATHON-8095](https://jira.mesosphere.com/browse/MARATHON-8095) PATCH call not proxied correctly to active node.
- [MARATHON-8381](https://jira.mesosphere.com/browse/MARATHON-8381) Use Different Exit Code for Marathon Suicide. …
> Marathon 1.6.549 Bump on 1.11

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Currently we have 4 tests that depend on creating a bundle tests. This commit merge them into one big integration test simulation basic use case for diagnostics bundles. This mean we will create, check status, download and delete the bundle in single test. This should prevent tests from failing because due to ordering.
This commit also rearrange entries in `tests_dcos_diagnostics.py`. All tests are at the top and helper functions were moved to the bottom. This make code clear and easier to read.
- [DCOS_OSS-4115](https://jira.mesosphere.com/browse/DCOS_OSS-4115)
> Merge dependent tests into one big scenario

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
- packages/mesos/build
- packages/mesos/buildinfo.json
- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Mesos-UI-Change-paths-pailer-and-logs-to-work-with-a.patch
- packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch
- packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0005-Included-nested-command-check-output-in-the-executor.patch
- packages/mesos/extra/patches/0006-Made-the-log-output-handling-of-TCP-and-HTTP-checks-.patch
- packages/mesos/extra/patches/0007-Raised-the-logging-level-of-some-check-and-health-ch.patch
1.10.5-sky1 build of DC/OS was created from a unofficial branch of DC/OS - https://github.com/mesosphere/dcos-enterprise/pull/2984/files and shipped to customer.
This patch is to make sure that we capture the changes that were given in 1.10.5.1 patch release and tag them so that it archived properly as a release.
JIRA for this change is:
* DCOS-39387 - 1.10.5.1 - Create a proper branch with changes in.
Other related JIRAs are:
* DCOS-38929 - Provide a 1.10.5.1 DC/OS EE image to customer.
* COPS-3542 - Warrant a clean upgrade from DC/OS 1.10.5-sky1 towards 1.10.8.
* MESOS-8830 - Agent gc on old slave sandboxes could empty persistent volume data
* DCOS-39059 - Support sky1 with 1.10.5.1 release
> 1.10.5.1 with fixes for MESOS-8830

- packages/adminrouter/windows.buildinfo.json
This pull request fixes the expected SHA1 checksum for the `rewrite_amd64_en-US.msi` needed when doing a DC/OS Windows build.
This fixes - DCOS-41386
> Fix expected sha1 value for the rewrite_amd64_en-US.msi installer

- packages/dcos-integration-test/extra/test_metrics.py
- packages/telegraf/buildinfo.json
This is a 1.12 backport of #3436.
- [DCOS_OSS-4088](https://jira.mesosphere.com/browse/DCOS_OSS-4088) metrics v0 API 500 error: "Failed to encode value to JSON"
N/A
> (1.12) Fix 500 responses from v0 metrics API

- CHANGES.md
- docs/admin-ports.md
- gen/build_deploy/bash.py
- gen/dcos-config.yaml
- mergebot-config.json
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/windows.buildinfo.json
- packages/dcos-net/buildinfo.json
- packages/dcos-ui/buildinfo.json
- packages/erlang/build
- packages/erlang/buildinfo.json
- packages/marathon/buildinfo.json
- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
* #3375 - [1.12] Bump dcos-net 
* #3458 - Admin Router: add 'Connection:close' header to the responses to requests to /mesos and /agent
* #3461 - Bump DC/OS UI to v2.21.8
* #3477 - [1.12] Bump Mesos to nightly 1.7.x 06eb5ba
* #3484 - Bump Marathon dependency on 1.12
Included
* [1.12] Enabled GC of nested container sandboxes by the Mesos agent #3490
> 1.12.0 beta2

- CHANGES.md
- docs/admin-ports.md
- gen/build_deploy/bash.py
- gen/dcos-config.yaml
- packages/dcos-net/buildinfo.json
- packages/erlang/build
- packages/erlang/buildinfo.json
Bump dcos-net and upgrade OTP version.
- [DCOS_OSS-3655](https://jira.mesosphere.com/browse/DCOS_OSS-3944) Improve logging in dcos-l4lb
- [DCOS_OSS-3655](https://jira.mesosphere.com/browse/DCOS_OSS-3945) Improve logging in dcos-overlay
- [DCOS_OSS-3655](https://jira.mesosphere.com/browse/DCOS_OSS-3655) Upgrade OTP version
- [DCOS-38600](https://jira.mesosphere.com/browse/DCOS-38600) Deadlock when SSL sockets are simultaneously sending/receiving data and buffers are full
- [ERL-622](https://bugs.erlang.org/browse/ERL-622) Deadlock when SSL sockets are simultaneously sending/receiving data and buffers are full
- [ERL-692](https://bugs.erlang.org/browse/ERL-692) …
> Bump dcos-net

- gen/dcos-config.yaml
This flips a flag that instructs the Mesos agent to garbage collect
the sandboxes of nested containers, just like the agent currently
GC's executor sandboxes.  Nested containers always run underneath
another active executor, and have in the past been garbage collected
alongside its parent executor.  However, because the default
executor can now potentially run infinite tasks in its lifetime,
the tasks (which are nested containers) can pile up sandboxes.
Note that this flag is technically a breaking change.  A task can
potentially rely on an artifact inside a sibling task's sandbox.
If the sibling task has exited, the sibling's sandbox can now be
garbage collected.  This scenario is however, considered to be
bad …
> Enabled GC of nested container sandboxes by the Mesos agent.

- packages/dcos-integration-test/extra/test_metrics.py
- packages/telegraf/buildinfo.json
This PR bumps the Telegraf package to pull in a fix for an issue that causes some requests to the v0 metrics API to get 500 responses due to a JSON serialization error.
- [DCOS_OSS-4088](https://jira.mesosphere.com/browse/DCOS_OSS-4088) metrics v0 API 500 error: "Failed to encode value to JSON"
N/A
> Fix 500 responses from v0 metrics API

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
- packages/mesos/extra/patches/0004-Revert-Removed-long-ago-deprecated-endpoints.patch
This change switches DC/OS `master` (= `1.13-dev`) to Mesos `master` (= `1.8-dev`).
> Point DC/OS 1.13-dev to Mesos master.

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Added:
* timestamp for dmesg
* distro version
* timedatectl
* systemd unit status
* pods endpoint
Backport: https://github.com/dcos/dcos/pull/3148
- [DCOS_OSS-4127](https://jira.mesosphere.com/browse/DCOS_OSS-4127)
> [1.11] Add more data to diagnostics bundle

- packages/adminrouter/windows.buildinfo.json
* DCOS-41386 - Skip Windows tests until Azure flakiness is resolved 
Reverts dcos/dcos#3459
> Revert "Fix expected sha1 value for the rewrite_amd64_en-US.msi installer"

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/5a7ad47e8fc1a14101e47a29eb8e7e2a20d959c5...0216002744517a6053fd782b6b4dc3d6cf77dd5e
> [1.11] Bump Mesos to nightly 1.5.x 0216002

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/5f6d4cdc79e1b28bc2d157d4b5b4aaf941a26d91...c635d4cc470ae5450cdfd3f3fbd089546b3b6a5b
https://github.com/dcos/dcos-mesos-modules/compare/5b3577ec734c866c71c70018b9d0fad67ba8aba0...8adedeeba73805c0e6884bac517aacca7623eace
> [1.10] Bump Mesos to nightly 1.4.x c635d4c

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/c635d4cc470ae5450cdfd3f3fbd089546b3b6a5b...c28e0618333378e4a7b4faa4f86347a9d0bdc82a
> [1.10] Bump Mesos to nightly 1.4.x c28e061

- packages/marathon/build
* [DCOS_OSS-4193](https://jira.mesosphere.com/browse/DCOS_OSS-4193) Marathon bootstrap relies on zk-1.zk node to be available.
> Removed marathon start precondition which challenges HA of marathon based on 1 node failure

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
- packages/adminrouter/windows.buildinfo.json
- packages/dcos-integration-test/extra/test_packaging.py
- packages/marathon/build
- packages/marathon/buildinfo.json
#3529 - Marathon remove precheck on single node 1.12
#3544 - [1.12] Update packaging integration tests to ensure testing on smaller clusters
#3550 - Fix the sha1sum for adminrouter rewrite_amd64_en-US.msi installer
#3551 - Update version to 1.12.0-rc1
#3553 - Bump Marathon to 1.7.174
> Train 1.12.0 rc1

- packages/marathon/build
- [DCOS_OSS-4193](https://jira.mesosphere.com/browse/DCOS_OSS-4193) Marathon bootstrap relies on zk-1.zk node to be available.
> Marathon remove precheck on single node 1.12

- packages/dcos-integration-test/extra/test_packaging.py
Currently, in the `test_packaging.py` we are trying to install `kafka` for which i have few concerns:
- It requires 3 agents to run. The intention of this test is to ensure the `/package/install` endpoint works. We should not have to require 3 agent nodes to test this functionality.
- Looking at the [history of this test in teamcity](https://teamcity.mesosphere.io/project.html?tab=testDetails&testNameId=-1224229538779150681&projectId=DcOs), I found out that the test has `0.0%` success rate. (It failed everytime it was ran, and it was ignored most of the time).
Based on above, I decided to install `nginx` instead of `kafka` which requires only one agent node for a successful install.
These DC/OS JIRA ticket(s) must be …
> [1.12] Update packaging integration tests to ensure testing on smaller clusters

- packages/adminrouter/windows.buildinfo.json
Backport of this fix - https://github.com/dcos/dcos/pull/3489
- https://jira.mesosphere.com/browse/DCOS-42046 - teamcity/dcos/build/dcos/windows: Admin Router rewrite_amd64_en-US.msi download failed with signature mismatch
> Fix the sha1sum for adminrouter rewrite_amd64_en-US.msi installer

- mergebot-config.json
Mergebot sync will prevent flakiness with mergebot and will help synchronize the mergebot actions. 
It addresses this flaky issue
* DCOS-39073 - Mergebot shows `aggregate` as red, although downstream has all CI checks green
> Enable Mergebot Sync in dcos/dcos.

- owners.json
Noticed this warning in the mergebot logs.
```
2018-10-05 18:49:12,412 mergebot     WARNING  Failed to add kapil as watcher to https://jira.mesosphere.com/rest/api/2/issue/DCOS-42798/watchers. Please check the username and the URL.
```
> Remove Kapil from owners.json

- packages/dcos-integration-test/extra/test_metrics.py
This PR adds two integration tests which verify that statsd application metrics emitted by Mesos tasks will be collected by the DC/OS metrics service. One test does this for standalone containers, while the other does it for nested containers within a task group ("pod").
- [DCOS_OSS-2271](https://jira.mesosphere.com/browse/DCOS_OSS-2271) dcos-metrics should support standalone containers
- [DCOS_OSS-4183](https://jira.mesosphere.com/browse/DCOS_OSS-4183) Mesos Metrics 2.0: integration tests
- [DCOS_OSS-3714](https://jira.mesosphere.com/browse/DCOS_OSS-3714) Adopt Telegraf as the DC/OS metrics pipeline
If you are changing components or packages in DC/OS (e.g. you …
> [1.12] Add tests for metrics from pods and standalone containers.

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
Routine changes after `master` now represents 1.13-dev.
https://jira.mesosphere.com/browse/DCOS_OSS-4272
> platform: bump version to 1.13-dev

- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/3e185f14075b827b8ea3b03a48ed2cd136ce8158...d0186a2cef8da2ba2af54185eee691b8a94cb305
> [1.12] Bump Mesos to nightly 1.7.x d0186a2

- packages/dcos-integration-test/extra/test_metrics.py
- packages/telegraf/buildinfo.json
This causes app metric names in the v0 API to use `.` instead of `_` as the name field separator.
Depends on #3436.
- [DCOS_OSS-4071](https://jira.mesosphere.com/browse/DCOS_OSS-4071) Metrics v0 API changed some metric names
N/A
> Fix app metric names in v0 API

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
- packages/telegraf/extra/start_telegraf.sh
This removes the `mesos_id` dimension from v0 metrics API responses. This field is currently being set with a placeholder value, and we don't intend to finish implementing it, so we'll remove it.
- [DCOS_OSS-4144](https://jira.mesosphere.com/browse/DCOS_OSS-4144) Remove mesos_id tag from v0 metrics API
N/A
> Remove mesos_id dimension from v0 metrics API

- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- packages/dcos-integration-test/extra/test_users.py
- packages/pytest/build
- packages/pytest/buildinfo.json
- packages/python/build
- packages/python/buildinfo.json
- https://jira.mesosphere.com/browse/DCOS_OSS-3995 (Bump platform CPython to 3.6.6 (or 3.6 latest)
- https://jira.mesosphere.com/browse/DCOS-43029 (Write basic integration tests for (open) DC/OS user management)
This pull request updates pytest for supporting the `allow_module_level` argument.
> Add dcos-integration-test/extra/test_users.py

- packages/exhibitor/extra/dcos-exhibitor.service
This updates the `dcos-exhibitor.service` unit file to assert that the system clock is synced before it tries to start Exhibitor. If the system clock is not synced when Exhibitor starts, it may successfully start but fail to join the cluster. Fixing this requires waiting for the system clock to sync, and then manually restarting `dcos-exhibitor.service`.
- [DCOS_OSS-4287](https://jira.mesosphere.com/browse/DCOS_OSS-4287) Check system clock is synced before starting Exhibitor
- [COPS-3897](https://jira.mesosphere.com/browse/COPS-3897)
N/A
> Assert system clock is synced before starting dcos-exhibitor

- packages/telegraf/buildinfo.json
This bumps Telegraf to pull in a build fix. Without this fix, Telegraf will fail to build. See https://github.com/dcos/telegraf/pull/24.
- [DCOS-43554](https://jira.mesosphere.com/browse/DCOS-43554) DC/OS Uncached Build fails to build telegraf package
- N/A
> Fix Telegraf build

- packages/telegraf/buildinfo.json
This is a 1.12 backport of #3619.
- [DCOS-43554](https://jira.mesosphere.com/browse/DCOS-43554) DC/OS Uncached Build fails to build telegraf package
- N/A
> (1.12) Fix Telegraf build

- CHANGES.md
- packages/exhibitor/extra/dcos-exhibitor.service
This is a 1.12 backport of #3594.
- [DCOS_OSS-4287](https://jira.mesosphere.com/browse/DCOS_OSS-4287) Check system clock is synced before starting Exhibitor
N/A
N/A
> (1.12) Assert system clock is synced before starting dcos-exhibitor

- packages/marathon/build
- [DCOS_OSS-4193](https://jira.mesosphere.com/browse/DCOS_OSS-4193) Marathon bootstrap relies on zk-1.zk node to be available.
> Marathon remove precheck on single node 1.11

- CHANGES.md
- packages/dcos-metrics/build
- packages/dcos-metrics/buildinfo.json
This fixes a bug that was causing a panic in DC/OS metrics agent service when Mesos was unavailable.
- [DCOS-39103](https://jira.mesosphere.com/browse/DCOS-39103) DC/OS metrics agent service can panic if mesos is unavailable
> [1.11] Fix panic in metrics agent service when mesos is unavailable

- packages/dcos-net/buildinfo.json
Bump dcos-net.
- [DCOS_OSS-4320](https://jira.mesosphere.com/browse/DCOS_OSS-4320) dcos-dns incorrectly deletes records in PODs when one container exits.
- [DCOS_OSS-4337](https://jira.mesosphere.com/browse/DCOS_OSS-4337) [dcos-net] DNS issue due to non unique task Id
- [DCOS_OSS-4311](https://jira.mesosphere.com/browse/DCOS_OSS-4311) dcos_dns: make ZK servers configurable
- [DCOS_OSS-4338](https://jira.mesosphere.com/browse/DCOS_OSS-4338) [dcos-net] Make mesos stream parser fault tolerant
- [DCOS_OSS-4336](https://jira.mesosphere.com/browse/DCOS_OSS-4336) [dcos-net] reduce the depth of crashlog …
> [1.12] Bump dcos-net

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
- packages/telegraf/buildinfo.json
This change coerces all metrics to lowercase, in order to preserve 1.11 behaviour. 
- [DCOS-43639](https://jira.mesosphere.com/browse/DCOS-43639) Force telegraf metric fields to lowercase
> [1.12] Lowercase metrics

- packages/dcos-log/buildinfo.json
Fixed file streaming for the Mesos File API in `dcos-log`.
With this PR we address the problems in DCOS-41248.
In order to not overload the Mesos agent with GET requests, we will now
wait one second if we are reading 0 bytes from the Mesos file.
This fix is temporary and not ideal but feels responsive enough to the
enduser and is a better alternative to what we have today.
The right fix here should be a change to the Read semantics so that a
read will block until there is data available.
- [DCOS_OSS-41248](https://jira.mesosphere.com/browse/DCOS-41248) dcos service log smashes the agent
> Bump dcos-log

- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/c28e0618333378e4a7b4faa4f86347a9d0bdc82a...df0a47570e8068861c113048c74d82a0370d12fd
> [1.10] Bump Mesos to nightly 1.4.x df0a475

- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/0216002744517a6053fd782b6b4dc3d6cf77dd5e...305c7f8e4e42f4f92a18f7d83d5c64ea1bcddc6d
> [1.11] Bump Mesos to nightly 1.5.x 305c7f8

- packages/marathon/extra/marathon.sh
In 1.7 we enabled maintenance_mode by default (1.12). So the feature maintenance_mode is not needed anymore. In 1.8 it's even considered an error if that feature is included in the commandline.
- [MARATHON-8479](https://jira.mesosphere.com/browse/MARATHON-8479) Marathon does not start on 1.13 cluster.
> maintenance_mode is enabled by default in 1.8 (1.13)

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
This adds a mesos input plugin to Telegraf to ensure that it has parity with mesos_exporter. Framework offers and allocator metrics were added. With these changes, there will be no need to run mesos_exporter on a DC/OS cluster.
- [DCOS_OSS-3815](https://jira.mesosphere.com/browse/DCOS_OSS-3815) Update the Telegraf Mesos input plugin to parity with mesos_exporter
> Add mesos metrics to telegraf

- gen/dcos-config.yaml
This PR extends the poll-period of the dcos_containers plugin to the mesos operator API. Note that we cherry-pick on top of three commits from #3453 to avoid being blocked by failing tests. 
- [DCOS_OSS-4300](https://jira.mesosphere.com/browse/DCOS_OSS-4300) - Decrease the poll frequency of dcos_containers to 60s
> Decrease Telegraf poll frequency

- packages/dcos-integration-test/extra/test_packaging.py
Currently, in the `test_packaging.py` we are trying to install `kafka` for which i have few concerns:
- It requires 3 agents to run. The intention of this test is to ensure the `/package/install` endpoint works. We should not have to require 3 agent nodes to test this functionality.
- Looking at the [history of this test in teamcity](https://teamcity.mesosphere.io/project.html?tab=testDetails&testNameId=-1224229538779150681&projectId=DcOs), I found out that the test has `0.0%` success rate. (It failed everytime it was ran, and it was ignored most of the time).
Based on above, I decided to install `nginx` instead of `kafka` which requires only one agent node for a successful install.
These DC/OS JIRA ticket(s) must be …
> [1.11] Update packaging integration tests to ensure testing on smaller clusters

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Currently, we pull overlay endpoints to diagnostic bundle
* `:5050/overlay-master/state`
* `:5051/overlay-agent/overlay`
This PR will remove these endpoints when the overlay is [disabled](https://docs.mesosphere.com/1.12/installing/production/advanced-configuration/configuration-reference/#dcos-overlay-enable).
- [DCOS_OSS-4250](https://jira.mesosphere.com/browse/DCOS_OSS-4250) Avoid failure when overlay and related endpoints are not available
___ …
> [1.11] Do not pull overlay data when overlay is disable

- CHANGES.md
- packages/marathon/buildinfo.json
- [DCOS-43816](https://jira.mesosphere.com/browse/DCOS-43816) Marathon latest 1.6 bump for 1.11.7.
- [DCOS-42753](https://jira.mesosphere.com/browse/DCOS-42753) Bump Akka library to fix memory leak issue.
- [MARATHON-8453](https://jira.mesosphere.com/browse/MARATHON-8453) TaskOverdueActor now respects `--kill_retry_timeout`.
- [MARATHON-8452](https://jira.mesosphere.com/browse/MARATHON-8452) Only log zero-value offers for scalar resources.
- [MARATHON-8461](https://jira.mesosphere.com/browse/MARATHON-8461) Write correct version in Zkid (based on scala timestamp changes)
- …
> bump marathon 1.6.654

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/305c7f8e4e42f4f92a18f7d83d5c64ea1bcddc6d...2ead30d0009109e582a5d5943d483e6faaae4d03
https://github.com/dcos/dcos-mesos-modules/compare/9a0631f51506583102d237fce915f25511a11cf3...2f1fb59b0c20959c0dbd4f0b98b13cee08b56633
> [1.11] Bump Mesos to nightly 1.5.x 2ead30d

- packages/dcos-integration-test/extra/test_packaging.py
Currently, in the `test_packaging.py` we are trying to install `kafka` for which i have few concerns:
- It requires 3 agents to run. The intention of this test is to ensure the `/package/install` endpoint works. We should not have to require 3 agent nodes to test this functionality.
- Looking at the [history of this test in teamcity](https://teamcity.mesosphere.io/project.html?tab=testDetails&testNameId=-1224229538779150681&projectId=DcOs), I found out that the test has `0.0%` success rate. (It failed everytime it was ran, and it was ignored most of the time).
Based on above, I decided to install `nginx` instead of `kafka` which requires only one agent node for a successful install.
These DC/OS JIRA ticket(s) must be …
> [1.10] Update packaging integration tests to ensure testing on smaller clusters

- packages/mesos/extra/patches/0011-Put-TerminateEvent-at-the-end-of-the-queue-in-the-Me.patch
- packages/mesos/extra/patches/0012-Waited-for-TEARDOWN-to-be-sent-in-v1-Java-scheduler-.patch
Destruction of the v1 library used in the v1 Java scheduler shim
is not always under our control. For example, the JVM can call JNI
`finalize()` if the Java scheduler nullifies its reference to the
V1Mesos library immediately after sending `TEARDOWN`. We want to make
sure that `TEARDOWN` is sent before the Mesos library is destructed.
___
All …
> [1.10] Add Mesos patches to ensure TEARDOWN is sent in v1 Java shim.

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/df0a47570e8068861c113048c74d82a0370d12fd...3071ff7ba9f3154a8ad7dc7a4d865861ca408320
https://github.com/dcos/dcos-mesos-modules/compare/8adedeeba73805c0e6884bac517aacca7623eace...b566eef9510195bae7f15923c1c17e04351fb2bc
> [1.10] Bump Mesos to nightly 1.4.x 3071ff7

- packages/marathon/buildinfo.json
Sending frequent kill requests to an agent can in certain cases lead to overloading the Docker daemon (if the tasks are docker containers run by the Docker containerizer). Thirty seconds seems to be a more sensible default here. 
Previously, Marathon would automatically request a new framework ID from Mesos if the old one was marked as torn down in Mesos, or if the framework ID record was removed from Zookeeper. This has led to more trouble than it has helped. The new behavior is:
* If Marathon's framework ID has been torn down in Mesos, or if the failover timeout has been exceeded, Marathon will crash, on launch, with a clear message.
* If Marathon's framework ID record was deleted from Zookeeper or is otherwise inaccessible, and there are instances defined, Marathon will refuse to …
> bump marathon to 1.5.12

- CHANGES.md
- packages/java/buildinfo.json
Update Java to `8u192`.
- [DCOS_OSS-4383](https://jira.mesosphere.com/browse/DCOS_OSS-4383) Update DC/OS Java JDK 8 to 8u192
> [1.10] packages/java: Update to 8u192

- packages/dcos-test-utils/buildinfo.json
Flaky Test for Metronome on Looking at Job Run History
- [DCOS_OSS-4294](https://jira.mesosphere.com/browse/DCOS_OSS-4294) Flaky Test for Metronome on Looking at Job Run History
> Update dcos test utils

- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/3071ff7ba9f3154a8ad7dc7a4d865861ca408320...9c6c65e501b2bf31fc761fb7b98b55b6b95512db
> [1.10] Bump Mesos to nightly 1.4.x 9c6c65e

- packages/mesos/extra/patches/0004-Added-received-timestamp-into-process-Request.patch
- packages/mesos/extra/patches/0005-Introduced-logResponse-for-http-handlers.patch
- packages/mesos/extra/patches/0006-Logged-request-processing-time-for-some-endpoints.patch
Add a series of extra patches that enable logging processing
time for some Mesos master and agent endpoints.
These patches are part of Mesos 1.8 and are tested in Mesos.
- [] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
> [1.12] Mesos: logged request processing time.

- CHANGES.md
- packages/java/buildinfo.json
Update Java to `8u192`.
- [DCOS_OSS-4381](https://jira.mesosphere.com/browse/DCOS_OSS-4381) Update DC/OS Java JDK 8 to 8u192
> [1.12] packages/java: Update to 8u192

- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/d0186a2cef8da2ba2af54185eee691b8a94cb305...cb07b697d4fbd8143136b39dd48a64dd634c2c4f
> [1.12] Bump Mesos to nightly 1.7.x cb07b69

- CHANGES.md
- packages/telegraf/buildinfo.json
This is a 1.12 backport of #3692.
This also pulls in a bug fix at dcos/telegraf#28 which is already merged into dcos/telegraf but hasn't yet been included in DC/OS 1.12. Integration tests for this fix will be added in a followup PR, see [here](https://jira.mesosphere.com/browse/DCOS_OSS-4393?focusedCommentId=186516&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-186516).
- [DCOS_OSS-4096](https://jira.mesosphere.com/browse/DCOS_OSS-4096) Telegraf dcos_statsd input plugin fails go race detector
- [DCOS_OSS-4393](https://jira.mesosphere.com/browse/DCOS_OSS-4393) [1.12] Telegraf does not retrieve executor metadata from Mesos
If you are …
> (1.12) Fix Telegraf dcos_statsd plugin race condition

- packages/dcos-integration-test/extra/test_metrics.py
This is a 1.12 backport of #3708.
- [DCOS_OSS-4342](https://jira.mesosphere.com/browse/DCOS_OSS-4342) test_metrics.test_metrics_containers fails with AssertionError
N/A
> (1.12) Improve reliability of metrics tests

- CHANGES.md
- fetch_cluster_logs.bash
- gen/dcos-config.yaml
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-test-utils/buildinfo.json
- packages/java/buildinfo.json
- packages/mesos/buildinfo.json
- packages/mesos/extra/patches/0004-Added-received-timestamp-into-process-Request.patch
- packages/mesos/extra/patches/0005-Introduced-logResponse-for-http-handlers.patch
- packages/mesos/extra/patches/0006-Logged-request-processing-time-for-some-endpoints.patch
- packages/mesos/windows.buildinfo.json
- packages/telegraf/buildinfo.json
#3727 Update dcos-test-utils
#3709 (1.12) Improve reliability of metrics tests
#3702 (1.12) Fix Telegraf dcos_statsd plugin race condition
#3698 [1.12] Bump Mesos to nightly 1.7.x cb07b69
#3695 Add fetch_cluster_logs.bash
#3682 [1.12] packages/java: Update to 8u192
#3631 [1.12] Mesos: logged request processing time.
#3626 [1.12] Update dcos-diagnostics
#3577 [1.12] Do not pull overlay data when overlay is disable
> 1.12 train 11/06/2018

- CHANGES.md
- packages/java/buildinfo.json
Update Java to `8u192`.
- [DCOS_OSS-4382](https://jira.mesosphere.com/browse/DCOS_OSS-4382) Update DC/OS Java JDK 8 to 8u192
> [1.11] packages/java: Update to 8u192

- CHANGES.md
- packages/docker-gc/extra/dcos-docker-gc.service
The LOG_TO_SYSLOG envvar here: https://github.com/spotify/docker-gc/blob/master/docker-gc#L53
will write to stdout if it's set to 0, and syslog if it's set to 1.
Our implementation of it as a systemd unit runs it in a container, so with its current setting of 1, it'll write to syslog inside the container which is destroyed after it runs. I'm changing it to 0 so that it will log to journald on the host system.
- [COPS-4044](https://jira.mesosphere.com/browse/COPS-4044) Docker-gc isn't configured to log
___
**PLEASE FILL IN THE …
> Docker gc log fix

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
This PR adds metrics collection from ZooKeeper instance on master nodes by the `dcos-telegraf` service. The collected logs correspond to the output from the `mntr` command:
https://zookeeper.apache.org/doc/r3.4.8/zookeeperAdmin.html#sc_zkCommands
- [DCOS_OSS-4477](https://jira.mesosphere.com/browse/DCOS_OSS-4477) Instrument and Transmit ZooKeeper Metrics to dcos-telegraf service.
> Collect ZooKeeper Metrics using DC/OS Telegraf

- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/cb07b697d4fbd8143136b39dd48a64dd634c2c4f...706170289a0d3558d788938eeba6d07dc9504225
> [1.12] Bump Mesos to nightly 1.7.x 7061702

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
This adds consistent tagging among DC/OS components to metrics emitted by the ZooKeeper Telegraf plugin.
- [DCOS_OSS-4491](https://jira.mesosphere.com/browse/DCOS_OSS-4491) Tag ZooKeeper metrics according to our Documentation.
> [DCOS_OSS-4491] Tag ZooKeeper metrics

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/d259228b9c9d29e234d609a104005c3e7ee26a0a...22fa5aeac19416fd0c7c2284a1e48a5ee15bdd24
https://github.com/dcos/dcos-mesos-modules/compare/1a68cac61dc2206be704c96839a138a52acaf8c8...0d80a848041a2d82a4e444a17e0ff72e28140e82
> [master] Bump Mesos to nightly master 22fa5ae

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/6008868c715733b7d798279e9b39ae3483f7d955...742471c575f9959f3ea9ffe7b6a317a033bfb42d
https://github.com/dcos/dcos-mesos-modules/compare/2f1fb59b0c20959c0dbd4f0b98b13cee08b56633...9d5cc18a2065864350c23ad56f1c4caa2ae308c5
> [1.11] Bump Mesos to nightly 1.5.x 742471c

- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
[DCOS-43593](https://jira.mesosphere.com/browse/DCOS-43593) - Some Mesos master endpoints do not handle failed authorization properly.
https://github.com/apache/mesos/compare/22fa5aeac19416fd0c7c2284a1e48a5ee15bdd24...49cab93b565d250fd7e88cd8bb9cd49abbdd7da4
> [master] Bump Mesos to nightly master 49cab93

- packages/mesos/buildinfo.json
[DCOS-43593](https://jira.mesosphere.com/browse/DCOS-43593) - Some Mesos master endpoints do not handle failed authorization properly.
https://github.com/apache/mesos/compare/742471c575f9959f3ea9ffe7b6a317a033bfb42d...9c28b265804269de9411f04cfcccefe3bdd8ef1a
> [1.11] Bump Mesos to nightly 1.5.x 9c28b26

- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
[DCOS-43593](https://jira.mesosphere.com/browse/DCOS-43593) - Some Mesos master endpoints do not handle failed authorization properly.
https://github.com/apache/mesos/compare/706170289a0d3558d788938eeba6d07dc9504225...9c68e2a532352a89f02e9352714a4f42ab76e82a
> [1.12] Bump Mesos to nightly 1.7.x 9c68e2a

- CHANGES.md
- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
- packages/mesos/extra/patches/0004-Added-task-health-check-definitions-to-master-API-re.patch
This PR adds a patch on top of OSS Mesos which includes task health check definitions in Mesos master/agent API outputs.
The related ticket for this PR exists in OSS Mesos JIRA:
- [MESOS-8780](https://issues.apache.org/jira/browse/MESOS-8780) Expose Check and HealthCheck information on Mesos HTTP endpoints.
> [1.12] Added a Mesos patch for health check definitions in master API outputs.

- CHANGES.md
- packages/marathon/buildinfo.json
- [MARATHON-8317](https://jira.mesosphere.com/browse/MARATHON-8317) Marathon Bump 1.6 on DCOS 1.11.
- [MARATHON-8493](https://jira.mesosphere.com/browse/MARATHON-8493) Incorrect handling of double precision for pods.
- [MARATHON-8498](https://jira.mesosphere.com/browse/MARATHON-8498) Remove validation for app updates and validate the whole app instead
- [COPS-3764](https://jira.mesosphere.com/browse/COPS-3764) MarathonUI JSON editor secrets validation fails on an update
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), …
> DCOS 1.11 Marathon Bump 1.6.567

- CHANGES.md
- packages/metronome/buildinfo.json
- [DCOS-45564](https://jira.mesosphere.com/browse/DCOS-45564) Metronome Bump on DCOS 1.11
- [DCOS_OSS-3616](https://jira.mesosphere.com/browse/DCOS_OSS-3616) Metronome is hoarding offers.
- [DCOS_OSS-2535](https://jira.mesosphere.com/browse/DCOS_OSS-2535) Info endpoint shows incorrect version of Metronome.
> bump metronome 0.4.5 on dcos 1.11

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-test-utils/buildinfo.json
This bumps dcos-test-utils for a better cleanup of the Marathon state between tests in the DC/OS Integration test suite.
Specifically, this brings this patch: https://github.com/dcos/dcos-test-utils/pull/69/files
To be sure: https://github.com/dcos/dcos-test-utils/compare/713dea0...1286f4b86faadc75
> dcos-test-utils: bump for better Marathon group cleanup

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-test-utils/buildinfo.json
This is a backport of https://github.com/dcos/dcos/pull/3833.
The description of that PR is:
```
This bumps dcos-test-utils for a better cleanup of the Marathon state between tests in the DC/OS Integration test suite.
Specifically, this brings this patch: https://github.com/dcos/dcos-test-utils/pull/69/files
To be sure: dcos/dcos-test-utils@713dea0...1286f4b
```
As this was 
> [1.12] Bump Test Utils to get pods cleaned up by marathon.purge

- CHANGES.md
- packages/dcos-net/buildinfo.json
In case of docker containerizer if the backend to a VIP is the
actual container ip then the application running in the container
cannot access its own VIP. The only way to make it work is to go
through port mapping. This patch fixes the port mapping such that
the backend is the host IP:port intead of container ip:port
jira: DCOS-45115
- [DCOS_45115](https://jira.mesosphere.com/browse/DCOS-45115) COPS-4087: Docker container unable to curl its own VIP
___ …
> [Backport][1.11] bump dcos-net for fix for docker services in bridge/container mode

- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_packaging.py
This fixes a bug in the dcos-metadata plugin in telegraf where executor containers were not being cached. This caused repeated hits on Mesos due to constant cache misses and missing information in the metrics output.
- [DCOS_OSS-4181](https://jira.mesosphere.com/browse/DCOS_OSS-4181) Telegraf does not retrieve executor metadata from Mesos
> [1.13] Cache executor container metadata in metrics

- gen/dcos-config.yaml
This PR fixes an issue in `dcos-config.yaml` which breaks the metrics Mesos module when the overlay network has been disabled at install time.
- [DCOS_OSS-4521](https://jira.mesosphere.com/browse/DCOS_OSS-4521) Metrics Mesos module fails to load if overlay network is disabled
> [master] Fix a metrics module installation bug when overlay network is disabled.

- packages/dcos-integration-test/extra/common.py
- packages/dcos-integration-test/extra/test_dcos_log.py
- packages/dcos-integration-test/extra/test_metrics.py
Backport of https://github.com/dcos/dcos/pull/3795
> Add xfailflake pytest markers to skip tests.

- packages/dcos-integration-test/extra/conftest.py
backport tests: consolidate marathon purge fixture #3856
> backport tests: consolidate marathon purge fixture #3856

- packages/dcos-integration-test/extra/test_dcos_log.py
**This is a backport, see: https://github.com/dcos/dcos/pull/3754**
Currently test was expecting 10 lines when dcos-log returns 10 entries.
Test failed when multiline entry appered. This change check if retrned
text contains 10 entries by checking if it contains 10 timestapms that
are added by dcos-log.
Refs: DCOS_OSS-4416
(cherry picked from commit 34f4116648c23684b8260e211e61c9e54fc95dd1)
> Change dcos-log text test to expect 10 entries

- packages/bouncer-deps/buildinfo.json
- packages/python-cryptography/buildinfo.json
- packages/python-gunicorn/buildinfo.json
- packages/python-jwt/buildinfo.json
- packages/python-passlib/buildinfo.json
- packages/python/buildinfo.json
This is a maintenance patch for including security/bugfix/maintenance releases of Bouncer dependencies; and for generally syncing Bouncer dependencies in DC/OS to those used for Bouncer development/CI.
- https://jira.mesosphere.com/browse/DCOS-45578
> Bump Bouncer dependencies / Python packages consumes by Bouncer

- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
- [MESOS-9411](https://issues.apache.org/jira/browse/MESOS-9411) - Validation of JWT tokens using HS256 hashing algorithm is not thread safe.
https://github.com/apache/mesos/compare/49cab93b565d250fd7e88cd8bb9cd49abbdd7da4...e65ab60bff4b1b7d4dc9fd892dd632f0d5d57083
> [master] Bump Mesos to nightly master e65ab60

- packages/dcos-integration-test/extra/test_metrics.py
This PR adds an integration test which verifies that statsd metrics emitted by standalone container processes will be collected by the DC/OS metrics service.
- [DCOS_OSS-2271](https://jira.mesosphere.com/browse/DCOS_OSS-2271) dcos-metrics should support standalone containers
- [DCOS_OSS-3714](https://jira.mesosphere.com/browse/DCOS_OSS-3714) Adopt Telegraf as the DC/OS metrics pipeline
> [master] Add tests for metrics from standalone containers and pods.

- packages/dcos-integration-test/extra/common.py
* https://jira.mesosphere.com/browse/DCOS-45308- Add the xfailflake pytest marker for 1.10 branch.
> Add the xfailflake pytest marker for 1.10 branch.

- CHANGES.md
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_packaging.py
This fixes a bug in the dcos-metadata plugin in telegraf where executor containers were not being cached. This caused repeated hits on Mesos due to constant cache misses and missing information in the metrics output.
- [DCOS_OSS-4181](https://jira.mesosphere.com/browse/DCOS_OSS-4181) Telegraf does not retrieve executor metadata from Mesos
> [1.12] Cache executor container metadata in metrics

- CHANGES.md
- packages/docker-gc/extra/dcos-docker-gc.service
This is a 1.12 backport of #3710.
- [DCOS_OSS-4469](https://jira.mesosphere.com/browse/DCOS_OSS-4469) Backport docker-gc log fix
N/A
> (1.12) Docker gc log fix

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
- packages/telegraf/buildinfo.json
This adds a whitelist in telegraf config to add certain task labels (that are not prefixed with `DCOS_METRICS_` which are automatically pulled in to tags on the metric) to metrics metadata. For now, we would like to add the `DCOS_SERVICE_NAME` labels, which has been added to the whitelist.
- [DCOS-43591](https://jira.mesosphere.com/browse/DCOS-43591) Add DCOS_SERVICE_NAME label to dcos-telegraf metrics to allow grouping of scheduler tasks
> [1.12] Add whitelist for including labels in telegraf metrics metadata

- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
- packages/mesos/extra/patches/0004-Added-received-timestamp-into-process-Request.patch
- packages/mesos/extra/patches/0005-Added-task-health-check-definitions-to-master-API-re.patch
- packages/mesos/extra/patches/0006-Introduced-logResponse-for-http-handlers.patch
- packages/mesos/extra/patches/0007-Logged-request-processing-time-for-some-endpoints.patch
- packages/mesos/extra/patches/0008-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch
From Mesos 1.6.0, the sandbox mode was changed from 0755 to 0750,
which is not backward compatible in dc/os. Please see DCOS_OSS-4415
for details.
- [DCOS_OSS-4415](https://jira.mesosphere.com/browse/DCOS_OSS-4415) Container launched by Docker cotnainerizer changed the sandbox mode from 0755 yo 0750 in dc/os 1.12.
This issue was caused by:
- [MESOS-8332](https://issues.apache.org/jira/browse/MESOS-8332) Narrow the container sandbox permissions.
___ …
> [1.12] Patched dc/os for sandbox permission change issue from Mesos 1.6.0.

- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
- packages/mesos/extra/patches/0004-Revert-Removed-long-ago-deprecated-endpoints.patch
- packages/mesos/extra/patches/0005-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch
From Mesos 1.6.0, the sandbox mode was changed from 0755 to 0750,
which is not backward compatible in dc/os. Please see DCOS_OSS-4415
for details.
- [DCOS_OSS-4415](https://jira.mesosphere.com/browse/DCOS_OSS-4415) Container launched by Docker cotnainerizer changed the sandbox mode from 0755 yo 0750 in dc/os 1.12.
This issue was caused by:
- [MESOS-8332](https://issues.apache.org/jira/browse/MESOS-8332) Narrow the container sandbox permissions.
___ …
> Patched dc/os for sandbox permission change issue from Mesos 1.6.0.

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/buildinfo.json
- packages/dcos-integration-test/extra/test_metrics.py
This PR adds collection of CockroachDB metrics to DC/OS OSS. It also refactors and moves corresponding metrics tests over from Enterprise.
It also adds back the changelog entry for ZooKeeper metrics being collected which was swallowed by force-pushing over the corresponding PR back when it was added.
- [DCOS_OSS-4529](https://jira.mesosphere.com/browse/DCOS_OSS-4529) Collect CockroachDB metrics via Telegraf.
> Collect CockroachDB metrics via Telegraf

- gen/dcos-config.yaml
This PR prepares DC/OS and adds metrics collection for Vault via Telegraf.
The OSS part duplicates the DC/OS Telegraf StatsD config into master.conf and agent.conf so that they can be overridden separately in DC/OS Enterprise.
- [DCOS-44592](https://jira.mesosphere.com/browse/DCOS-44592) Instrument and Transmit Vault Metrics to dcos-telegraf.
> Collect Vault metrics via Telegraf

- CHANGES.md
- packages/docker-gc/extra/dcos-docker-gc.service
This is a 1.11 backport of #3710.
- [DCOS_OSS-4469](https://jira.mesosphere.com/browse/DCOS_OSS-4469) Backport docker-gc log fix
N/A
> (1.11) Docker gc log fix

- CHANGES.md
- gen/dcos-config.yaml
- packages/adminrouter/build
- packages/adminrouter/docker/Dockerfile
- packages/adminrouter/extra/src/Makefile.common
- packages/adminrouter/extra/src/docs/api/nginx.master.html
- packages/adminrouter/extra/src/docs/api/nginx.master.yaml
- packages/adminrouter/extra/src/includes/http/common.conf
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/test-harness/tests/test_generic.config.yml
- packages/dcos-integration-test/extra/test_metrics.py
This PR adds basic Nginx metrics display on `/nginx/status` for masters and metrics scraping of Nginx by Telegraf via the `/nginx/metrics` endpoint on masters. The underlying module added is 3rd-party module: https://github.com/vozlt/nginx-module-vts
The module seems to be fairly popular, however only developed by one person.
Regarding the issues on the module automatic testing is not a priority there.
I still think this is our best option right now to get metrics in for the MWT.
The module provides basic HTTP metrics for each `upstream` and `proxy_pass` directive individually.
We use the base configuration with an extra large shared memory area size of 32MB.
We expect the minimal performance impact with this configuration, but will probably expand on this in the future.
These DC/OS JIRA …
> Collect Admin Router Nginx VTS metrics via Telegraf

- gen/dcos-config.yaml
- packages/telegraf/buildinfo.json
This adds unique `user_agent` config values to Telegraf plugins to set the `User-Agent` headers in all outgoing requests.
- [DCOS_OSS-4522](https://jira.mesosphere.com/browse/DCOS_OSS-4522) [1.13] Add a distinct user-agent for each Telegraf plugin
> [1.13] Set user-agent configs for telegraf plugins

- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
- packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch
- packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0005-Displayed-resource-provider-resources-in-GET_RESOURC.patch
- packages/mesos/extra/patches/0006-Improved-logging-for-offers-and-inverse-offers.patch
- packages/mesos/extra/patches/0007-Introduced-a-push-based-gauge-metric.patch
- packages/mesos/extra/patches/0008-Added-a-test-for-PushGauge.patch
- packages/mesos/extra/patches/0009-Renamed-Gauge-to-PullGauge-and-documented-difference.patch
- packages/mesos/extra/patches/0010-Updated-mesos-source-for-Gauge-PullGauge-renaming.patch
- packages/mesos/extra/patches/0011-Enabled-per-framework-metrics-in-the-master.patch
- packages/mesos/extra/patches/0012-Added-per-framework-subscribed-metric-and-helpers.patch
- packages/mesos/extra/patches/0013-Added-per-framework-metrics-for-scheduler-calls.patch
- packages/mesos/extra/patches/0014-Added-per-framework-metrics-for-scheduler-events.patch
- packages/mesos/extra/patches/0015-Added-per-framework-offer-metrics.patch
- packages/mesos/extra/patches/0016-Added-per-framework-metrics-for-task-states.patch
- packages/mesos/extra/patches/0017-Added-per-framework-metrics-for-offer-operations.patch
- packages/mesos/extra/patches/0018-Enabled-per-framework-metrics-in-the-allocator.patch
- packages/mesos/extra/patches/0019-Changed-the-capacity_-member-of-BoundedHashMap-to-no.patch
- packages/mesos/extra/patches/0020-Tracked-completed-framework-metrics-in-the-allocator.patch
- packages/mesos/extra/patches/0021-Added-per-framework-metrics-for-suppressed-roles.patch
- packages/mesos/extra/patches/0022-Added-task-health-check-definitions-to-master-API-re.patch
- packages/mesos/extra/patches/0023-Put-TerminateEvent-at-the-end-of-the-queue-in-the-Me.patch
- packages/mesos/extra/patches/0024-Waited-for-TEARDOWN-to-be-sent-in-v1-Java-scheduler-.patch
Add Mesos patches to ensure TEARDOWN is sent in v1 Java shim.
Destruction of the v1 library used in the v1 Java scheduler shim
is not always under our control. For example, the JVM can call JNI
`finalize()` if the Java scheduler nullifies its reference to the
V1Mesos library immediately after sending `TEARDOWN`. We want to make
sure that `TEARDOWN` is sent before the Mesos library is destructed.
___ …
> [1.11] Add Mesos patches to ensure TEARDOWN is sent in v1 Java shim.

- NOTICE
- gen/dcos-config.yaml
- packages/adminrouter/extra/src/docs/api/nginx.agent.html
- packages/adminrouter/extra/src/docs/api/nginx.agent.yaml
- packages/adminrouter/extra/src/docs/api/nginx.master.html
- packages/adminrouter/extra/src/docs/api/nginx.master.yaml
- packages/adminrouter/extra/src/includes/server/common.conf
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/test-harness/tests/test_generic.config.yml
- packages/dcos-integration-test/extra/test_metrics.py
This PR adds Admin Router metric scraping to agents. The `/nginx/metrics` Prometheus endpoint is added for that purpose. The endpoint can also be queried via the master Admin Router proxy as in:
`/system/v1/agent/<agent-id>/nginx/metrics`
Some missing Admin Router tests were also added in this PR. The Admin Router docs were re-generated for the new endpoint.
- [DCOS_OSS-4569](https://jira.mesosphere.com/browse/DCOS_OSS-4569) Add Admin Router metrics scraping to agents.
> Collect Admin Router Nginx metrics from agents

- packages/dcos-test-utils/buildinfo.json
Allows test suite to run individual tests on single slave clusters.
- [DCOS-45784](https://jira.mesosphere.com/browse/DCOS-45784) Testsuite does not allow to run individual tests on single slave clusters.
___ …
> [1.13] Bumped dcos-test-utils to cover DCOS-45784.

- packages/dcos-test-utils/buildinfo.json
Allows test suite to run individual tests on single slave clusters.
- [DCOS-45784](https://jira.mesosphere.com/browse/DCOS-45784) Testsuite does not allow to run individual tests on single slave clusters.
___ …
> [1.12] Bumped dcos-test-utils to cover DCOS-45784.

- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/9c68e2a532352a89f02e9352714a4f42ab76e82a...ce10fa8ab525054d4152d0273972bc7b2b5cb782
> [1.12] Bump Mesos to nightly 1.7.x ce10fa8

- packages/mesos/buildinfo.json
- packages/mesos/extra/patches/0014-Added-per-framework-metrics-for-scheduler-events.patch
https://github.com/apache/mesos/compare/9c28b265804269de9411f04cfcccefe3bdd8ef1a...6fd91063da7230c2a65bea11ca4c69f241ba0877
> [1.11] Bump Mesos to nightly 1.5.x 6fd9106

- packages/dcos-integration-test/extra/test_groups.yaml
Rebalance the test groups to bring Group 3 down somewhat from 17mins and bump Group 4 from 7mins. We aim for something like 14mins vs. 10mins, respectively.
- [DCOS-46073](https://jira.mesosphere.com/browse/DCOS-46073) integration tests: rebalance OSS groups
___
> dcos-integration-test/test_groups.yaml: rebalance group 3

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
- packages/telegraf/buildinfo.json
This adds unique `user_agent` config values to Telegraf plugins to set the `User-Agent` headers in all outgoing requests.
- [DCOS_OSS-4544](https://jira.mesosphere.com/browse/DCOS_OSS-4544) [1.12] Add a distinct user-agent for each Telegraf plugin
> [1.12] Add a distinct user-agent for each Telegraf plugin

- packages/dcos-integration-test/extra/test_networking.py
Mutes two flaky tests in networking test suite till docker version is upgraded to 17.12
- [DCOS-19790](https://jira.mesosphere.com/browse/DCOS-19790) Flaky Test For DCOS Release: test_networking.test_if_overlay_ok
- [DCOS-41896](https://jira.mesosphere.com/browse/DCOS-41896) Flaky test - test_networking test_ipv6 True False
___ …
> Mutes two flaky tests till docker version is upgraded to 17.12

- packages/dcos-integration-test/extra/test_networking.py
Mutes two flaky tests till docker version is upgraded to 17.12
- [DCOS-19790](https://jira.mesosphere.com/browse/DCOS-19790) Flaky Test For DCOS Release: test_networking.test_if_overlay_ok
- [DCOS-41896](https://jira.mesosphere.com/browse/DCOS-41896) Flaky test - test_networking test_ipv6 True False
___ …
> [1.12] Mutes two flaky tests till docker version is upgraded to 17.12

- packages/dcos-integration-test/extra/test_networking.py
Mutes two flaky tests till docker version is upgraded to 17.12
- [DCOS-19790](https://jira.mesosphere.com/browse/DCOS-19790) Flaky Test For DCOS Release: test_networking.test_if_overlay_ok
- [DCOS-41896](https://jira.mesosphere.com/browse/DCOS-41896) Flaky test - test_networking test_ipv6 True False
___ …
> [1.11] Mutes two flaky tests till docker version is upgraded to 17.12

- owners.json
Mergebot should be in owners.json to issue a `merge-it` command and auto-merge PRs.
We plan to use this for auto-merging Train PRs.
https://jira.mesosphere.com/browse/DCOS-46116
> Add mergebot to owners.

- packages/metronome/buildinfo.json
- [DCOS_OSS-4565](https://jira.mesosphere.com/browse/DCOS_OSS-4565) Metronome 0.6.0 bump to DCOS 1.13.
- [PR-314](https://github.com/dcos/metronome/pull/314) Bug fix in JSON Schema for v1 end point.
> Metronome 0.6.6 Bump on DCOS master

- release/storage/azure.py
Backport #3930
* (DCOS-40442) AzureException during storage upload
> Handle AzureException during storage upload

- release/storage/azure.py
* (DCOS-40442) AzureException during storage upload
It is was important to note that problem was not neccessarily due to large file size on Azure platform.
This can be seen on this failure.
```
[15:21:26]Store to azure artifact testing/master/ee.bootstrap.latest by method copy
```
Where ee.bootstrap.latest is not a generate_config.sh that is the largest artifact file.
The failure was in the copy operation, the copy operation was handling only one kind of error `AzureConflictHttpError` and we can simply expand the scope to `AzureException` that was frequently observed.
* More over, instead of retry, we are doing a `abort copy` and copy again. 
(This is same the existing code, but little more stringent).
---- 
Another change was to retry upload 5 times instead of 3
```
- …
```
> Handle Azure Exception During Copy and Upload.

- release/storage/azure.py
Backport #3930
(DCOS-40442) AzureException during storage upload.
> Handle AzureException during storage upload.

- packages/bootstrap/extra/dcos_internal_utils/cli.py
- packages/cockroach/extra/dcos-cockroach.service
From the commit message:
```
This fixes DCOS_OSS-4601. Without this step
register.py is highly likely to find the
ZooKeeper cluster in a state where individual
ZooKeeper instances are still in standalone
mode. This on the other hand leads to individual
CockroachDB instances being launched without
being aware of each other.
```
https://jira.mesosphere.com/browse/DCOS_OSS-4601
> cockroach: use exhibitor_wait as ExecStartPre

- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_networking.py
Add a few xfail markers.
For now, we use one xfail marker per test, as we don't want to break WIP dashboard code.
> Add new xfail pytest markers

- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_service_discovery.py
Marathon randomly assigns host ports. In rare cases it causes port conflicts in the networking integration tests. We shouldn't rely on this feature and have to assign unique port numbers manually.
- [DCOS_OSS-3736](https://jira.mesosphere.com/browse/DCOS_OSS-3736) Update marathon app configuration to match Marathon 1.5 syntax
___ …
> [1.10] Avoid port conflicts in the networking tests.

- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_service_discovery.py
Marathon randomly assigns host ports. In rare cases it causes port conflicts in the networking integration tests. We shouldn't rely on this feature and have to assign unique port numbers manually.
- [DCOS_OSS-3736](https://jira.mesosphere.com/browse/DCOS_OSS-3736) Update marathon app configuration to match Marathon 1.5 syntax
___ …
> [1.12] Avoid port conflicts in the networking tests.

- packages/dcos-integration-test/extra/common.py
- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_checks.py
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_metronome.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_units.py
This removes ``common.py``.
An alternative could be to extend ``common.py`` with a custom mark as so:
```python
base_xfail = pytest.mark.xfail(strict=False)
MarkDecorator = base_xfail.__class__
class require_date(MarkDecorator):
mark = pytest.mark.xfail.mark
def __init__(self, *args, **kwargs):
#... Date validation goes here
xfailflake = MarkDecorator(base_xfail.mark.combined_with(require_date.mark))
```
I believe that this is more pytest-idiomatic. …
> Xfailflake date

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This PR corrects the JIRA tickets of a muted test.
none
none
___ …
> Fixed the wrong ticket in `xfailflake` marker.

- gen/dcos-config.yaml
- packages/telegraf/buildinfo.json
- packages/telegraf/extra/dcos-telegraf.service
Previously, the only way for a user to supply additional telegraf configuration was to modify/add conf files to the telegraf config directory, which is within `/opt/mesosphere`. Now, users can add additional conf files to the `/var/lib/dcos/telegraf/telegraf.d/` directory, which gets automatically pulled in to telegraf at startup.
Will add documentation on this in a docs pr.
- [DCOS-42214](https://jira.mesosphere.com/browse/DCOS-42214) support methods to configure additional settings on dcos-telegraf
> [1.13] Add user-editable telegraf config dir

- packages/dcos-integration-test/extra/test_metrics.py
Fixes to integration test to avoid flakes. Upped the teardown retry time periods to 15min ([matched timing intervals](https://github.com/mesosphere/dcos-enterprise/blob/master/packages/dcos-integration-test/extra/test_registry_cli.py#L28) in DCOS EE tests that included an [sdk framework install/uninstall test](https://github.com/mesosphere/dcos-enterprise/blob/master/packages/dcos-integration-test/extra/test_registry_cli.py#L415)). 
- [DCOS_OSS-4568](https://jira.mesosphere.com/browse/DCOS_OSS-4568) test_metrics.deploy_and_cleanup_dcos_package Framework hello-world still running
> [1.13] Flaky test_metrics.deploy_and_cleanup_dcos_package

- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/f050bf01af8f9f92bbada2c0a2025a459290ed98...26e68578f4390e16e21caca40783a1748bef5990
> [master] Bump Mesos to nightly master 26e6857

- packages/dcos-integration-test/extra/test_metrics.py
Fixes to integration test to avoid flakes. Upped the teardown retry time periods to 15min ([matched timing intervals](https://github.com/mesosphere/dcos-enterprise/blob/master/packages/dcos-integration-test/extra/test_registry_cli.py#L28) in DCOS EE tests that included an [sdk framework install/uninstall test](https://github.com/mesosphere/dcos-enterprise/blob/master/packages/dcos-integration-test/extra/test_registry_cli.py#L415)). 
- [DCOS_OSS-4568](https://jira.mesosphere.com/browse/DCOS_OSS-4568) test_metrics.deploy_and_cleanup_dcos_package Framework hello-world still running
> [1.12] Flaky test_metrics.deploy_and_cleanup_dcos_package

- CHANGES.md
- gen/dcos-config.yaml
- packages/telegraf/buildinfo.json
- packages/telegraf/extra/dcos-telegraf.service
This is a backport of https://github.com/dcos/dcos/pull/4004.
Previously, the only way for a user to supply additional telegraf configuration was to modify/add conf files to the telegraf config directory, which is within `/opt/mesosphere`. Now, users can add additional conf files to the `/var/lib/dcos/telegraf/telegraf.d/` directory, which gets automatically pulled in to telegraf at startup.
- [DCOS-42214](https://jira.mesosphere.com/browse/DCOS-42214) support methods to configure additional settings on dcos-telegraf
> [1.12] Add user-editable telegraf config dir

- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/ce10fa8ab525054d4152d0273972bc7b2b5cb782...b97f0ba29d40a279dec00ffe51512e3b5a146049
> [1.12] Bump Mesos to nightly 1.7.x b97f0ba

- CHANGES.md
- packages/dcos-metrics/buildinfo.json
This fixes a bug in dcos-metrics that could cause its Prometheus producer (exporter) to omit some metric data in responses. See the upstream PR at https://github.com/dcos/dcos-metrics/pull/168 for more information on the bug and its fix.
- [DCOS_OSS-3863](https://jira.mesosphere.com/browse/DCOS_OSS-3863) agent metrics prometheus endpoint does not show all containers running on this agent
N/A
> (1.11) Fix dcos-metrics Prometheus producer omitting some metrics

- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_service_discovery.py
Marathon randomly assigns host ports. In rare cases it causes port conflicts in the networking integration tests. We shouldn't rely on this feature and have to assign unique port numbers manually.
- [DCOS_OSS-3736](https://jira.mesosphere.com/browse/DCOS_OSS-3736) Update marathon app configuration to match Marathon 1.5 syntax
___ …
> [1.11] Avoid port conflicts in the networking tests. 

- packages/bouncer-deps/buildinfo.json
- packages/bouncer/build
- packages/bouncer/extra/dcos-bouncer-migrate-users.service
- packages/bouncer/extra/iam-migrate-users-from-1.12.py
- packages/bouncer/extra/iam-migrate-users-from-zk.py
- packages/dcos-integration-test/buildinfo.json
- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-integration-test/extra/test_groups.yaml
- packages/dcos-integration-test/extra/test_iam_migration.py
Add a migration script that will convert DC/OS Open users from version `1.12` and beyond from Zookeeper database to the new IAM service datastore.
- [DCOS-45632](https://jira.mesosphere.com/browse/DCOS-45632) Write Basic Migration Script
> packages/bouncer: add dcos-oauth user migration service

- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_service_discovery.py
Marathon randomly assigns host ports. In rare cases it causes port conflicts in the networking integration tests. We shouldn't rely on this feature and have to assign unique port numbers manually.
- [DCOS_OSS-3736](https://jira.mesosphere.com/browse/DCOS_OSS-3736) Update marathon app configuration to match Marathon 1.5 syntax
___ …
> Avoid port conflicts in the networking tests.

- fetch_cluster_logs.bash
Everything works:
open dcos aws cluster:
https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&buildTypeId=DcOs_Open_Test_IntegrationTest_AwsOnpremWStaticBackendCopyLogCollectionTest&buildId=1403810
DC/OS E2E Docker Integration Tests:
https://teamcity.mesosphere.io/viewLog.html?buildId=1403807&buildTypeId=DcOs_Open_Test_DcosDocker_CopyForLogCollectionDcOsE2eDockerIntegrationTests&tab=artifacts
master journald logs was over the set limit and was deleted:
https://teamcity.mesosphere.io/viewLog.html?buildId=1403812&buildTypeId=DcOs_Enterprise_Test_Inte_AwsOnpremWStaticBackendAndSecurityStrictCopyLogCollect&tab=artifacts
> Fix dcos-cli, remove artifacts that are too large

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
Update 1.12.1 version that. Port https://github.com/dcos/dcos/pull/3955 to the minor branch that was missed.
> 1.12.1 update version

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/26e68578f4390e16e21caca40783a1748bef5990...1e8ebcb8cf1710052c1ae14e342c1277616fa13d
https://github.com/dcos/dcos-mesos-modules/compare/0d80a848041a2d82a4e444a17e0ff72e28140e82...0143dac6622e89c8ef98683a1c9d8d1113877e79
> [master] Bump Mesos to nightly master 1e8ebcb

- packages/dcos-integration-test/extra/test_metrics.py
Fix flaky `test_pod_application_metrics` by getting the task's container ids and asserting the ids instead of checking for the number of running containers, which can fail assertions occasionally if previous tests' containers were not torn down completely or any other cases where other containers might be running at the same time.
- [DCOS_OSS-4571](https://jira.mesosphere.com/browse/DCOS_OSS-4571) test_metrics test_pod_application_metrics failed with 'Test should create 2 containers'
> [1.13] Fix flaky test_pod_application_metrics test

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_auth.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_legacy_user_management.py
- packages/dcos-integration-test/extra/test_mesos.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_misc.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_packaging.py
- packages/dcos-integration-test/extra/test_rexray.py
- packages/dcos-integration-test/extra/test_service_discovery.py
This allows one to run `pytest --collect-only --confcutdir .` in the integration tests directory of a DC/OS OSS checkout without a cluster running, if the right requirements are installed.
This is part of https://jira.mesosphere.com/browse/DCOS-46438.
This will allow a dashboard which knows about test flakes.
This is also progress towards a test suite which can be run from any host against any cluster.
* Put "skip" conditions which require a cluster into functions, rather than as decorators
* Put import-level opening of files which exist on a cluster into functions
> [master] Allow the collection of tests without a cluster

- packages/dcos-integration-test/extra/test_metrics.py
Flaky test fix was done in https://github.com/dcos/dcos/pull/3947 but test is still muted - unmuting the test here.
- [DCOS_OSS-4568](https://jira.mesosphere.com/browse/DCOS_OSS-4568) test_metrics.deploy_and_cleanup_dcos_package Framework hello-world still running
> [1.12] Unmute test_executor_metrics_metadata test

- packages/dcos-integration-test/extra/test_metrics.py
Fix flaky `test_pod_application_metrics` by getting the task's container ids and asserting the ids instead of checking for the number of running containers, which can fail assertions occasionally if previous tests' containers were not torn down completely or any other cases where other containers might be running at the same time.
- [DCOS_OSS-4571](https://jira.mesosphere.com/browse/DCOS_OSS-4571) test_metrics test_pod_application_metrics failed with 'Test should create 2 containers'
> [1.12] Fix flaky test_pod_application_metrics test

- packages/dcos-integration-test/extra/api_session_fixture.py
- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_auth.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-integration-test/extra/test_endpoints.py
- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_misc.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_packaging.py
- packages/dcos-integration-test/extra/test_rexray.py
- packages/dcos-integration-test/extra/test_service_discovery.py
This allows one to run `pytest --collect-only --confcutdir .` in the integration tests directory of a DC/OS OSS checkout without a cluster running, if the right requirements are installed.
This is part of https://jira.mesosphere.com/browse/DCOS-46438.
This will allow a dashboard which knows about test flakes.
This is also progress towards a test suite which can be run from any host against any cluster.
* Put "skip" conditions which require a cluster into functions, rather than as decorators
* Put import-level opening of files which exist on a cluster into functions
> [1.10] Allow the collection of tests without a cluster

- packages/dcos-integration-test/extra/api_session_fixture.py
- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_auth.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_mesos.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_misc.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_packaging.py
- packages/dcos-integration-test/extra/test_rexray.py
- packages/dcos-integration-test/extra/test_service_discovery.py
This allows one to run `pytest --collect-only --confcutdir .` in the integration tests directory of a DC/OS OSS checkout without a cluster running, if the right requirements are installed.
This is part of https://jira.mesosphere.com/browse/DCOS-46438.
This will allow a dashboard which knows about test flakes.
This is also progress towards a test suite which can be run from any host against any cluster.
* Put "skip" conditions which require a cluster into functions, rather than as decorators
* Put import-level opening of files which exist on a cluster into functions
> [1.11] Allow the collection of tests without a cluster

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_auth.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_mesos.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_misc.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_packaging.py
- packages/dcos-integration-test/extra/test_rexray.py
- packages/dcos-integration-test/extra/test_service_discovery.py
This allows one to run `pytest --collect-only --confcutdir .` in the integration tests directory of a DC/OS OSS checkout without a cluster running, if the right requirements are installed.
This will allow a dashboard which knows about test flakes.
This is also progress towards a test suite which can be run from any host against any cluster.
* Put "skip" conditions which require a cluster into functions, rather than as decorators
* Put import-level opening of files which exist on a cluster into functions
> [1.12] Allow the collection of tests without a cluster

- packages/dcos-integration-test/extra/test_networking.py
This unmutes a test given that the issue is apparently fixed.
> [1.12] Remove xfailflake marker for DCOS-46220

- packages/dcos-integration-test/extra/test_dcos_log.py
This unmutes a test given that the test is apparently fixed.
- [DCOS_OSS-4416](https://jira.mesosphere.com/browse/DCOS_OSS-4416) dcos-log returns more lines than requested limit
> [1.11] Backport adamdangoor/unmute-DCOS_OSS-4416

- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/1e8ebcb8cf1710052c1ae14e342c1277616fa13d...386b1fe99bb9d10af2abaca4832bf584b6181799
> [master] Bump Mesos to nightly master 386b1fe

- packages/dcos-integration-test/extra/test_metrics.py
Flaky test fix was done in https://github.com/dcos/dcos/pull/3947 but test is still muted - unmuting the test here.
- [DCOS_OSS-4568](https://jira.mesosphere.com/browse/DCOS_OSS-4568) test_metrics.deploy_and_cleanup_dcos_package Framework hello-world still running
> [1.13] Unmute test_executor_metrics_metadata test

- packages/metronome/buildinfo.json
- [DCOS_OSS-46752](https://jira.mesosphere.com/browse/DCOS_OSS-46752) Release Metronome latest 0.6 on 1.12.
- [PR-317](https://github.com/dcos/metronome/pull/317) Updated to the latest version of Marathon 1.7 lib.
- [DCOS-41675](https://jira.mesosphere.com/browse/DCOS-41675) Azure Out of memory: Java heap space Exception. Observed on Azure platform.
- This supersedes https://github.com/dcos/dcos/pull/3922
> updating 1.12 to the latest metronome

- packages/metronome/buildinfo.json
- [DCOS_OSS-46751](https://jira.mesosphere.com/browse/DCOS_OSS-46751) Release Metronome latest 0.6 on Master.
- [PR-317](https://github.com/dcos/metronome/pull/317) Updated to the latest version of Marathon 1.7 lib.
> Metronome 0.6.10 Bump on Master (1.13)

- packages/dcos-integration-test/extra/test_metrics.py
This unmutes a flaky test that [fails infrequently](https://teamcity.mesosphere.io/project.html?tab=testDetails&projectId=DcOs_Open_Test_IntegrationTest&testNameId=-4813183735307993658&branch_DcOs_Open_Test_IntegrationTest=%3Cdefault%3E&page=1), and has been difficult to reproduce manually, in order to collect more data around the failure. This is specifically intended to help collect DC/OS component logs, which are only collected by CI if an integration test job fails.
N/A
If you …
> Unmute test_metrics_containers

- packages/dcos-integration-test/extra/test_dcos_log.py
This unmutes a test given that the test is apparently fixed.
- [DCOS_OSS-4416](https://jira.mesosphere.com/browse/DCOS_OSS-4416) dcos-log returns more lines than requested limit
> [1.12] Unmute `test_log_text`

- packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/9c6c65e501b2bf31fc761fb7b98b55b6b95512db...6791ab059b9f2fb3968a54cb257d219c28fdcba1
> [1.10] Bump Mesos to nightly 1.4.x 6791ab0

- packages/dcos-integration-test/extra/test_endpoints.py
test_endpoints.test_if_overlay_master_agent_is_up fails for 1.11 upgraded clusters.
- [DCOS-46506](https://jira.mesosphere.com/browse/DCOS-46506) test_endpoints.test_if_overlay_master_agent_is_up fails for 1.11 upgraded clusters
___ …
> [1.11] Fix validation of overlay backends

- packages/dcos-integration-test/extra/test_metrics.py
This is a 1.12 backport of #4093.
N/A
> (1.12) Unmute test_metrics_containers

- packages/dcos-integration-test/extra/test_endpoints.py
test_endpoints.test_if_overlay_master_agent_is_up fails for 1.11 upgraded clusters.
- [DCOS-46506](https://jira.mesosphere.com/browse/DCOS-46506) test_endpoints.test_if_overlay_master_agent_is_up fails for 1.11 upgraded clusters
___ …
> [1.12] Fix validation of overlay backends

- packages/dcos-integration-test/extra/test_networking.py
Unmute test_vip. Please see last comments in the linked jira ticket.
- [DCOS-45799](https://jira.mesosphere.com/browse/DCOS-45799) test_networking.test_vip [Container_MESOS-Network_HOST-Network_HOST]  (container stuck in PROVISIONING)
___ …
> [1.12] Unmute test_vip

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This is a backport of the changes in https://github.com/dcos/dcos/pull/4110 which  fixes a once flaky test which has been muted because of its flakyness. The version of the test in 1.12 is free of the bugs that made the tests fail in `master`, so this backport only unmutes the test.
- [DCOS_OSS-4531](https://jira.mesosphere.com/browse/DCOS_OSS-4531) test_dcos_diagnostics.test_dcos_diagnostics_bundle_download_and_extract assertionerror test bundle download and validate zip file
___
**PLEASE …
> [1.12] Add missing comma, fix formatting and unmute diagnostics test

- packages/dvdcli/buildinfo.json
The dvdcli package fails to build because the golang image that is using is out of date.
> [Backport 1.10] DCOS-45295 - Upgrade dvdcli golang to a more recent version to prevent build failures

- packages/dvdcli/buildinfo.json
The dvdcli package fails to build because the golang image that is using is out of date.
> [Backport 1.11] DCOS-45295 - Upgrade dvdcli golang to a more recent version to prevent build failures

- packages/dcos-integration-test/extra/test_endpoints.py
test_endpoints.test_if_overlay_master_agent_is_up fails for 1.11 upgraded clusters.
- [DCOS-46506](https://jira.mesosphere.com/browse/DCOS-46506) test_endpoints.test_if_overlay_master_agent_is_up fails for 1.11 upgraded clusters
___ …
> Fix validation of overlay backends

- README.md
The DC/OS readme currently tells users to use dcos-e2e which is deprecated in favor of minidcos (and some of the links are broken). Updates the README to reference minidcos instead.
- [DCOS-46756](https://jira.mesosphere.com/browse/DCOS-46756) Update DCOS documentation to refer to minidcos instead of dcos-e2e
- [DCOS_OSS-4591](https://jira.mesosphere.com/browse/DCOS_OSS-4591) DC/OS OSS README - Use new `minidcos` commands
> DCOS-46756 - Replace dcos-e2e cli with minidcos.

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- gen/tests/test_config.py
This patch exposes a mesos flag --network_cni_root_dir_persist
through dcos config so that an operator may choose to persist
the cni root dir across the host reboot. The default value is `false` 
for the backward compatibility
- [DCOS_OSS-4667](https://jira.mesosphere.com/browse/DCOS_OSS-4667) Expose a Mesos flag to allow the network CNI root directory to be persisted across host reboot
___ …
> [Backport] [1.10] Exposes mesos flag to persist cni root directory across host reboot.

- packages/dvdcli/buildinfo.json
The dvdcli package fails to build because the golang image that is using is out of date.
> [Backport 1.12] DCOS-45295 - Upgrade dvdcli golang to a more recent version to prevent build failures

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- gen/tests/test_config.py
This patch exposes a mesos flag --network_cni_root_dir_persist
through dcos config so that an operator may choose to persist
the cni root dir across the host reboot. The default value is `false` 
for the backward compatibility
- [DCOS_OSS-4667](https://jira.mesosphere.com/browse/DCOS_OSS-4667) Expose a Mesos flag to allow the network CNI root directory to be persisted across host reboot
___ …
> [Backport][1.11] Exposes mesos flag to persist cni root directory across host reboot.

- packages/dcos-integration-test/extra/test_checks.py
This sort of addresses test flakiness for `test_checks.test_checks_api`. It now no longer checks the result code from the checks API because `dcos_api_session` will essentially wait for and require a healthy cluster in order to continue and run this test. Since we're assuming a healthy cluster I don't think it makes sense to check the status because we thus always expect it to be 0 and if something unexpected goes wrong, it's very likely to be some transient failure in a different component as seen by the issue in the associated ticket.
- [DCOS-42722](https://jira.mesosphere.com/browse/DCOS-42722) test_checks.test_checks_api is flaky …
> Change test_checks to improve its output and reduce the number of irrelevant failures

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
- packages/telegraf/buildinfo.json
This PR enables Prometheus metrics collection from ports on tasks which specify `DCOS_METRICS_FORMAT=prometheus` in their labels.
- [DCOS_OSS-3717](https://jira.mesosphere.com/browse/DCOS_OSS-3717) Add Mesos service discovery to the Telegraf prometheus metrics input plugin
> Gather Prometheus metrics from tasks

- packages/dcos-integration-test/extra/test_metrics.py
Increases retry period from 10s to 5min. Also increased all other retry periods to minimum of 5min to avoid more potential flakes down the line.
- [DCOS-46190](https://jira.mesosphere.com/browse/DCOS-46190) test_metrics.test_standalone_container_metrics
> [1.13] Fix flaky test_standalone_container_metrics

- packages/dvdcli/buildinfo.json
The dvdcli package fails to build because the golang image that is using is out of date.
> DCOS-45295 - Upgrade dvdcli golang to a more recent version to prevent build failures

- packages/dcos-integration-test/extra/test_metrics.py
`test_metrics_containers` and `test_metrics_containers_app` sometimes fail because they assume that all containers have a `task_name`, which is false. Some containers are executors, and will never have a `task_name`. `test_metrics_containers` now ignores all containers in a metrics API response that don't have a `task_name` of `statsd-emitter`. `test_metrics_containers_app` no longer fails if it finds container metrics that don't have a `task_name`.
- N/A …
> Fix container metrics tests for the v0 metrics API

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_endpoints.py
- packages/mesos-modules/buildinfo.json
dcos6 interface shown in the UI even when enable_ipv6 was set to false.
- [DCOS-40539](https://jira.mesosphere.com/browse/DCOS-40539) dcos6 interface shown in the UI even when enable_ipv6 was set to false
https://github.com/dcos/dcos-mesos-modules/compare/0143dac6622e89c8ef98683a1c9d8d1113877e79...0ed50a4d16dc560554f3abe843f2e0af4f52fcba
https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/modules/job/DCOS_OSS_Mesos_Modules-pr/20/
___ …
> dcos6 interface shown in the UI even when enable_ipv6 was set to false

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This PR fixes the flakyness of the test by making it more resilient to changing file types. Since we do not care about the file types but only that the files exist, this change makes sure that the test passes even if the file we expect exists in a gzipped version.
- [DCOS_OSS-4531 ](https://jira.mesosphere.com/browse/DCOS_OSS-4531) test_dcos_diagnostics.test_dcos_diagnostics_bundle_download_and_extract assertionerror test bundle download and validate zip file
- [DCOS-44935](https://jira.mesosphere.com/browse/DCOS-44935) [test_dcos_diagnostics.test_dcos_diagnostics_bundle_create_download_delete] - Flaky Test
If you are changing components or packages in DC/OS (e.g. …
> DCOS_OSS-4531 - Fix flaky test by making it more resilient

- packages/dcos-installer-ui/buildinfo.json
The uncached nightly builds for 1.10 are failing due to issues with the dcos-installer-ui package. These issues have been fixed in dcos-installer-ui's master branch, but not updated here.
> [1.10] DCOS-45295 - Bump dcos-installer-ui to latest commit to pull in the fixes for issues with dependencies and gulp.

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/386b1fe99bb9d10af2abaca4832bf584b6181799...a5d6635b351d1b357e9fcc396b155cccfad6aae5
https://github.com/dcos/dcos-mesos-modules/compare/0143dac6622e89c8ef98683a1c9d8d1113877e79...0ed50a4d16dc560554f3abe843f2e0af4f52fcba
> [master] Bump Mesos to nightly master a5d6635

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/extra/util/delete_ec2_volume.py
There are multiple benefits to merging this pair of PRs (this PR + the DC/OS Enterprise change).
The driver for this is to progress towards making it possible to use `pytest` to collect and later run integration tests from a computer which is not a DC/OS cluster, such as a developer's laptop.
That will allow us to complete [DCOS-46439](https://jira.mesosphere.com/browse/DCOS-46439) but will also allow for greater developer productivity.
This PR alone does not achieve that, but it helps, as someone with a checkout of the DC/OS Enterprise repository will not necessarily be able to import open source tests.
I also consider this to be a clean up of some technical debt - this removes:
* Imports from test files - all common helpers should go in a common helpers file, or in DC/OS Test Utils
* …
> [master/1.13] Use DC/OS Test Utils helpers for diagnostics tests

- packages/mesos/buildinfo.json
- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Mesos-UI-Change-paths-pailer-and-logs-to-work-with-a.patch
- packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch
- packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0005-Included-nested-command-check-output-in-the-executor.patch
- packages/mesos/extra/patches/0006-Made-the-log-output-handling-of-TCP-and-HTTP-checks-.patch
- packages/mesos/extra/patches/0007-Raised-the-logging-level-of-some-check-and-health-ch.patch
- packages/mesos/extra/patches/0008-Improved-logging-for-offers-and-inverse-offers.patch
- packages/mesos/extra/patches/0009-Logged-the-resources-in-DRF-sorter-CHECKs.patch
- packages/mesos/extra/patches/0010-Added-verbose-logging-in-Sorter-Allocation.patch
- packages/mesos/extra/patches/0011-Put-TerminateEvent-at-the-end-of-the-queue-in-the-Me.patch
- packages/mesos/extra/patches/0012-Waited-for-TEARDOWN-to-be-sent-in-v1-Java-scheduler-.patch
- packages/mesos/extra/patches/0013-Added-task-health-check-definitions-to-master-API-re.patch
https://github.com/apache/mesos/compare/6791ab059b9f2fb3968a54cb257d219c28fdcba1...e929d413328e10f6d358899500d5aaedd9d9bc51
> [1.10] Bump Mesos to nightly 1.4.x e929d41

- packages/dcos-integration-test/extra/test_metrics.py
This is a 1.12 backport of #4161.
- N/A
> (1.12) Fix container metrics tests for the v0 metrics API

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- gen/tests/test_config.py
This patch exposes a mesos flag --network_cni_root_dir_persist
through dcos config so that an operator may choose to persist
the cni root dir across the host reboot. The default value is `false` 
for the backward compatibility
- [DCOS_OSS-4667](https://jira.mesosphere.com/browse/DCOS_OSS-4667) Expose a Mesos flag to allow the network CNI root directory to be persisted across host reboot
___ …
> [Backport][1.12] Exposes mesos flag to persist cni root directory across host reboot.

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_endpoints.py
- packages/mesos-modules/buildinfo.json
dcos6 interface shown in the UI even when enable_ipv6 was set to false.
- [DCOS-40539](https://jira.mesosphere.com/browse/DCOS-40539) dcos6 interface shown in the UI even when enable_ipv6 was set to false
https://github.com/dcos/dcos-mesos-modules/compare/9d5cc18a2065864350c23ad56f1c4caa2ae308c5...f1a0c5870e6744c79714e16e4adfee1010ebf78f
https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/modules/job/DCOS_OSS_Mesos_Modules-pr/30/
___ …
> [1.11] dcos6 interface shown in the UI even when enable_ipv6 was set to false

- packages/dcos-installer-ui/buildinfo.json
The uncached nightly builds for 1.11 are failing due to issues with the dcos-installer-ui package. These issues have been fixed in dcos-installer-ui's master branch, but not updated here.
> [1.11] DCOS-45295 - Bump dcos-installer-ui to latest commit to pull in the fixes for issues with dependencies and gulp.

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
- packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch
- packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0005-Displayed-resource-provider-resources-in-GET_RESOURC.patch
- packages/mesos/extra/patches/0006-Improved-logging-for-offers-and-inverse-offers.patch
- packages/mesos/extra/patches/0007-Introduced-a-push-based-gauge-metric.patch
- packages/mesos/extra/patches/0008-Added-a-test-for-PushGauge.patch
- packages/mesos/extra/patches/0009-Renamed-Gauge-to-PullGauge-and-documented-difference.patch
- packages/mesos/extra/patches/0010-Updated-mesos-source-for-Gauge-PullGauge-renaming.patch
- packages/mesos/extra/patches/0011-Enabled-per-framework-metrics-in-the-master.patch
- packages/mesos/extra/patches/0012-Added-per-framework-subscribed-metric-and-helpers.patch
- packages/mesos/extra/patches/0013-Added-per-framework-metrics-for-scheduler-calls.patch
- packages/mesos/extra/patches/0014-Added-per-framework-metrics-for-scheduler-events.patch
- packages/mesos/extra/patches/0015-Added-per-framework-offer-metrics.patch
- packages/mesos/extra/patches/0016-Added-per-framework-metrics-for-task-states.patch
- packages/mesos/extra/patches/0017-Added-per-framework-metrics-for-offer-operations.patch
- packages/mesos/extra/patches/0018-Enabled-per-framework-metrics-in-the-allocator.patch
- packages/mesos/extra/patches/0019-Changed-the-capacity_-member-of-BoundedHashMap-to-no.patch
- packages/mesos/extra/patches/0020-Tracked-completed-framework-metrics-in-the-allocator.patch
- packages/mesos/extra/patches/0021-Added-per-framework-metrics-for-suppressed-roles.patch
- packages/mesos/extra/patches/0022-Added-task-health-check-definitions-to-master-API-re.patch
- packages/mesos/extra/patches/0023-Put-TerminateEvent-at-the-end-of-the-queue-in-the-Me.patch
- packages/mesos/extra/patches/0024-Waited-for-TEARDOWN-to-be-sent-in-v1-Java-scheduler-.patch
https://github.com/apache/mesos/compare/6fd91063da7230c2a65bea11ca4c69f241ba0877...5f6225bd6e039c633b7758f02d2b5fbabc8e0169
https://github.com/dcos/dcos-mesos-modules/compare/9d5cc18a2065864350c23ad56f1c4caa2ae308c5...f1a0c5870e6744c79714e16e4adfee1010ebf78f
> [1.11] Bump Mesos to nightly 1.5.x 5f6225b

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_endpoints.py
- packages/mesos-modules/buildinfo.json
dcos6 interface shown in the UI even when enable_ipv6 was set to false.
- [DCOS-40539](https://jira.mesosphere.com/browse/DCOS-40539) dcos6 interface shown in the UI even when enable_ipv6 was set to false
https://github.com/dcos/dcos-mesos-modules/compare/545c3ff25e8bf5dcff166b83ee419584db22a5c4...85a3ee2e4ac2b180b13690ea98fd87a8ef473697
https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/modules/job/DCOS_OSS_Mesos_Modules-pr/23/
___ …
> [1.12] dcos6 interface shown in the UI even when enable_ipv6 was set to false

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/b97f0ba29d40a279dec00ffe51512e3b5a146049...4f21147a9334ef9ed84dcf11742ce448062f3ec1
https://github.com/dcos/dcos-mesos-modules/compare/545c3ff25e8bf5dcff166b83ee419584db22a5c4...85a3ee2e4ac2b180b13690ea98fd87a8ef473697
> [1.12] Bump Mesos to nightly 1.7.x 4f21147

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/extra/util/delete_ec2_volume.py
This is a backport of https://github.com/dcos/dcos/pull/4148
See original description below:
```
There are multiple benefits to merging this pair of PRs (this PR + the DC/OS Enterprise change).
The driver for this is to progress towards making it possible to use `pytest` to collect and later run integration tests from a computer which is not a DC/OS cluster, such as a developer's laptop.
That will allow us to complete [DCOS-46439](https://jira.mesosphere.com/browse/DCOS-46439) but will also allow for greater developer productivity.
This PR alone does not achieve that, but it helps, as someone with a checkout of the DC/OS Enterprise repository will not necessarily be able to import open source tests.
I also consider this to be a clean up of some technical debt - this removes:
* Imports …
```
> [1.12] Backport adamdangoor/test-utils-diagnostics

- packages/dcos-integration-test/extra/test_metrics.py
This changes metrics tests to be more tolerant of 204s for container metrics, which are not necessarily an error. Some tasks are not expected to provide container metrics.
- [DCOS_OSS-4682](https://jira.mesosphere.com/browse/DCOS_OSS-4682) Metrics tests (test_metrics_containers) fail on expected 204 from v0 metrics API
- N/A
> Fix handling of 204s from metrics v0 API in metrics tests

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This is the backport of https://github.com/dcos/dcos/pull/4162 to 1.12
- [DCOS_OSS-4531 ](https://jira.mesosphere.com/browse/DCOS_OSS-4531) test_dcos_diagnostics.test_dcos_diagnostics_bundle_download_and_extract assertionerror test bundle download and validate zip file
- [DCOS-44935](https://jira.mesosphere.com/browse/DCOS-44935) [test_dcos_diagnostics.test_dcos_diagnostics_bundle_create_download_delete] - Flaky Test
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS …
> [1.12] DCOS_OSS-4531 - Fix flaky test by making it more resilient

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This is the backport of https://github.com/dcos/dcos/pull/4162 to 1.11
- [DCOS_OSS-4531 ](https://jira.mesosphere.com/browse/DCOS_OSS-4531) test_dcos_diagnostics.test_dcos_diagnostics_bundle_download_and_extract assertionerror test bundle download and validate zip file
- [DCOS-44935](https://jira.mesosphere.com/browse/DCOS-44935) [test_dcos_diagnostics.test_dcos_diagnostics_bundle_create_download_delete] - Flaky Test
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS …
> [1.11] DCOS_OSS-4531 - Fix flaky test by making it more resilient

- CHANGES.md
- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
- packages/mesos/extra/patches/0004-Added-received-timestamp-into-process-Request.patch
- packages/mesos/extra/patches/0005-Added-task-health-check-definitions-to-master-API-re.patch
- packages/mesos/extra/patches/0006-Introduced-logResponse-for-http-handlers.patch
- packages/mesos/extra/patches/0007-Logged-request-processing-time-for-some-endpoints.patch
- packages/mesos/extra/patches/0008-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch
- packages/mesos/extra/patches/0009-Added-HEARTBEAT-events-and-calls-for-the-executor-HT.patch
- packages/mesos/extra/patches/0010-Refactored-master-and-agent-streaming-connections.patch
- packages/mesos/extra/patches/0011-Added-heartbeaters-for-agent-and-HTTP-executors.patch
- packages/mesos/extra/patches/0012-Added-tests-for-agent-executor-heartbeating.patch
- packages/mesos/extra/patches/0013-Changed-master-to-hold-subscribers-in-a-circular-buf.patch
- packages/mesos/extra/patches/0014-Added-gauge-metric-for-operator-event-stream-subscri.patch
This PR adds new patches on top of OSS Mesos which address an issue where connections of subscribers to the master's operator API can leak due to network intermediaries such as ELB.
- [DCOS_OSS-4164](https://jira.mesosphere.com/browse/DCOS_OSS-4164) Prevent subscribers to the master's event stream from leaking connections
___ …
> [1.12] Add patches to address Mesos operator API subscriber leak.

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- gen/tests/test_config.py
Adds a `enable_mesos_input_plugin` config option to allow operator to turn on/off the Mesos input plugin. Defaults to `false` in 1.12.
I have tested this by using minidcos to run a cluster off the TeamCity build of this PR, and then passing in the config option `enable_mesos_input_plugin: true` which added the plugin to the Telegraf config.
Still need to: update docs and make changes to Terraform to add the config option to the installer
- [DCOS_OSS-4688](https://jira.mesosphere.com/browse/DCOS_OSS-4688) Add config option to turn on/off mesos input plugin
> [1.12] enable_mesos_input_plugin config option

- CHANGES.md
- gen/dcos-config.yaml
This PR enables telegraf's internal metrics plugin.
- [DCOS_OSS-4608](https://jira.mesosphere.com/browse/DCOS_OSS-4608) Enable telegraf's internal metrics plugin
> Configure telegraf's internal metrics to on

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/extra/util/delete_ec2_volume.py
This is a backport of https://github.com/dcos/dcos/pull/4148
See original description below:
```
There are multiple benefits to merging this pair of PRs (this PR + the DC/OS Enterprise change).
The driver for this is to progress towards making it possible to use `pytest` to collect and later run integration tests from a computer which is not a DC/OS cluster, such as a developer's laptop.
That will allow us to complete [DCOS-46439](https://jira.mesosphere.com/browse/DCOS-46439) but will also allow for greater developer productivity.
This PR alone does not achieve that, but it helps, as someone with a checkout of the DC/OS Enterprise repository will not necessarily be able to import open source tests.
I also consider this to be a clean up of some technical debt - this removes:
* Imports …
```
> [1.11] Backport adamdangoor/test-utils-diagnostics

- CHANGES.md
- packages/telegraf/buildinfo.json
Bumps telegraf version to include a fix that was causing the metrics api to occasionally 204 on the /containers endpoint.
- [DCOS_OSS-4679](https://jira.mesosphere.com/browse/DCOS_OSS-4679) Metric timestamp field not set
- [COPS-4333](https://jira.mesosphere.com/browse/COPS-4333) DC/OS 1.12; "dcos task metrics summary <task-id>" returns HTTP 204
> [1.13] Fix missing metrics timestamp causing metrics api 204s

- CHANGES.md
- packages/telegraf/buildinfo.json
Bumps telegraf version to include a fix that was causing the metrics api to occasionally 204 on the /containers endpoint. Curious to see if this will fix https://jira.mesosphere.com/browse/DCOS_OSS-4682 as well.
- [DCOS_OSS-4679](https://jira.mesosphere.com/browse/DCOS_OSS-4679) Metric timestamp field not set
- [COPS-4333](https://jira.mesosphere.com/browse/COPS-4333) DC/OS 1.12; "dcos task metrics summary <task-id>" returns HTTP 204
> [1.12] Fix missing metrics timestamp causing metrics api 204s

- packages/dcos-integration-test/extra/api_session_fixture.py
- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/extra/test_dcos_log.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_packaging.py
- packages/dcos-integration-test/extra/util/delete_ec2_volume.py
- packages/dcos-test-utils/buildinfo.json
This is a backport of https://github.com/dcos/dcos/pull/4148
See original description below.
However, this change also required a backport of a DC/OS Test Utils bump.
I pulled this in from #3789.
```
There are multiple benefits to merging this pair of PRs (this PR + the DC/OS Enterprise change).
The driver for this is to progress towards making it possible to use `pytest` to collect and later run integration tests from a computer which is not a DC/OS cluster, such as a developer's laptop.
That will allow us to complete [DCOS-46439](https://jira.mesosphere.com/browse/DCOS-46439) but will also allow for greater developer productivity.
This PR alone does not achieve that, but it helps, as someone with a checkout of the DC/OS Enterprise repository will not necessarily be able to import open …
```
> [1.10] Backport adamdangoor/test-utils-diagnostics

- gen/calc.py
- gen/dcos-config.yaml
- gen/tests/test_config.py
Adds a `enable_mesos_input_plugin` config option to allow operator to turn on/off the Mesos input plugin. Defaults to `true` in 1.13+ (defaults to false in 1.12).
- [DCOS_OSS-4688](https://jira.mesosphere.com/browse/DCOS_OSS-4688) Add config option to turn on/off mesos input plugin
> [1.13] Add enable_mesos_input_plugin config option

- packages/dcos-integration-test/extra/test_composition.py
This prevents `test_dcos_cluster_is_up` from hanging indefinitely when something goes wrong with the calls to `docker`. It will wait 1 minute for each call and if the call times out, it will continue logging only an error message. Any other failures will still cause the test to fail.
- [DCOS-41679](https://jira.mesosphere.com/browse/DCOS-41679)
___ …
> Prevent hang in test_composition.test_dcos_cluster_is_up

- gen/dcos-config.yaml
This adds a comment with rationale about a specific
Mesos flag for posterity. No code has been changed.
> Add a comment with rationale for `MESOS_HOSTNAME_LOOKUP=false` in DC/OS.

- packages/dcos-metrics/buildinfo.json
This bump ensures that containers are tracked in Mesos metrics isolator,
which prevents remove attempts of unknown containers.
- [DCOS_OSS-4630](https://jira.mesosphere.com/browse/DCOS_OSS-4630) com_mesosphere_MetricsIsolatorModule fails to track individual containers' lifecycle.
- [COPS-4310](https://jira.mesosphere.com/browse/COPS-4310)
* This has been tested manually on a 1.11.8 cluster, see https://github.com/dcos/dcos-metrics/pull/172
* https://github.com/dcos/dcos-metrics/compare/033c3f4c51b06c14a3e204274b3ffc06c0edad38...606ebcf702f2fafa0b9db6a545d9d905d32023e7
* N/A
> [1.11] dcos-metrics: bump to latest commit.

- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
- packages/mesos/extra/patches/0004-Added-received-timestamp-into-process-Request.patch
- packages/mesos/extra/patches/0005-Added-task-health-check-definitions-to-master-API-re.patch
- packages/mesos/extra/patches/0006-Introduced-logResponse-for-http-handlers.patch
- packages/mesos/extra/patches/0007-Logged-request-processing-time-for-some-endpoints.patch
- packages/mesos/extra/patches/0008-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch
- packages/mesos/extra/patches/0009-Added-HEARTBEAT-events-and-calls-for-the-executor-HT.patch
- packages/mesos/extra/patches/0010-Refactored-master-and-agent-streaming-connections.patch
- packages/mesos/extra/patches/0011-Added-heartbeaters-for-agent-and-HTTP-executors.patch
- packages/mesos/extra/patches/0012-Added-tests-for-agent-executor-heartbeating.patch
- packages/mesos/extra/patches/0013-Changed-master-to-hold-subscribers-in-a-circular-buf.patch
- packages/mesos/extra/patches/0014-Added-gauge-metric-for-operator-event-stream-subscri.patch
- packages/mesos/extra/patches/0015-Reverted-the-container-sandbox-permission-from-0750-.patch
This patch is used to revert the sandbox permission semantic change
in Mesos 1.6.0 (caused by this commit 04dd7f32). 04dd7f32 caused
nestd container could not traverse its parent container's sandbox
if the nested container user is an arbitrary non-root user and
different from its parent's user.
Without this revert, there will be two issues:
1. Some modules may not be able to create files under the sandbox
as a non-root user.
2. Task launched as non-root users may not be able to open files
under the sandbox if the task is launched as a non-root user.
This patch could be removed once DCOS-47501 and MESOS-9536 are
landed.
- [DCOS-47699](https://jira.mesosphere.com/browse/DCOS-47699) Revert the 1.12 …
> [1.12] Reverted the sandbox permission change from 0750 back to 0755.

- packages/telegraf/buildinfo.json
Includes additional container metrics if provided
- DiskStatistics (tags with `volume_persistence_id`, `volume_persistence_principal` if applicable)
- Perf
- NetTrafficControlStatistics
- NetSNMPStatistics
- Blkio cfq_recursive and throttling stats; return all ops, not just `TOTAL`
- [DCOS_OSS-4624](https://jira.mesosphere.com/browse/DCOS_OSS-4624) Add missing container metrics
> [1.13] Additional container metrics

- CHANGES.md
- packages/telegraf/buildinfo.json
Includes additional container metrics if provided
- DiskStatistics (tags with `volume_persistence_id`, `volume_persistence_principal` if applicable)
- Perf
- NetTrafficControlStatistics
- NetSNMPStatistics
- Blkio cfq_recursive and throttling stats; return all ops, not just `TOTAL`
- [DCOS_OSS-4624](https://jira.mesosphere.com/browse/DCOS_OSS-4624) Add missing container metrics
> [1.12] Additional container metrics

- mypy.ini
- test-e2e/README.md
- test-e2e/cluster_helpers.py
- test-e2e/conftest.py
- test-e2e/requirements.txt
- test-e2e/test_e2e_module.py
- test-e2e/test_service_account.py
- tox.ini
This PR add a test for the newly introduced superuser service account login in DC/OS 1.13.
This test is not run on CI - [DCOS_OSS-2032](https://jira.mesosphere.com/browse/DCOS_OSS-2032) is needed for that. It was tested locally and is known to pass.
- [DCOS-45325](https://jira.mesosphere.com/browse/DCOS-45325) Build E2E tests for testing new config options superuser_service_account_uid/public_key (for both DC/OS variants).
> Add E2E test for superuser service account login
