- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Simplify debugging by adding SELinux information into diagnostics bundle
- [DCOS_OSS-4123](https://jira.mesosphere.com/browse/DCOS_OSS-4123) Get SELinux details from dcos-diagnostics bundle
> Add SELinux details to diagnostics bundle

- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/test-harness/tests/test_master.py
https://jira.mesosphere.com/browse/DCOS-45281
___
All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request- …
> [1.11] dcos/dcos setup for the UI banner plugin is broken

- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/test-harness/tests/test_master.py
https://jira.mesosphere.com/browse/DCOS-45280
___
All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request- …
> [1.10] fix ui headers to allow ui being opened in iframe

- packages/dcos-integration-test/extra/common.py
- packages/dcos-integration-test/extra/test_checks.py
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/extra/test_dcos_log.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_metronome.py
- packages/dcos-integration-test/extra/test_units.py
* DCOS-45308 - Muting flakes using xfailflake custom marker.
> DCOS-45308 - Muting flakes using xfailflake custom marker.

- packages/dcos-integration-test/extra/conftest.py
See code comments in the patch; downstream this will address https://jira.mesosphere.com/browse/DCOS-45746.
> tests: consolidate marathon purge fixture

- packages/bouncer-deps/buildinfo.json
- packages/python-cryptography/buildinfo.json
- packages/python-gunicorn/buildinfo.json
- packages/python-jwt/buildinfo.json
- packages/python-passlib/buildinfo.json
- packages/python/buildinfo.json
Contains:
- https://github.com/dcos/dcos/pull/3850
> master train 181130

- packages/dcos-integration-test/extra/conftest.py
> backport tests: consolidate marathon purge fixture #3856

- gen/dcos-config.yaml
This PR fixes a bug which prevents the Mesos agent from starting when overlay network has been disabled at install time.
- [DCOS_OSS-4521](https://jira.mesosphere.com/browse/DCOS_OSS-4521) Metrics Mesos module fails to load if overlay network is disabled
___
All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/) …
> [1.12] Fix a metrics module installation bug when overlay network is disabled.

- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/test-harness/tests/test_master.py
https://jira.mesosphere.com/browse/DCOS-45279
___
All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request- …
> [1.12] dcos/dcos setup for the UI banner plugin is broken

- CHANGES.md
- packages/docker-gc/extra/dcos-docker-gc.service
This is a 1.10 backport of #3710.
- [DCOS_OSS-4469](https://jira.mesosphere.com/browse/DCOS_OSS-4469) Backport docker-gc log fix
N/A
> (1.10) Docker gc log fix

- CHANGES.md
- gen/dcos-config.yaml
- packages/adminrouter/extra/src/includes/main/common.conf
- packages/adminrouter/extra/src/test-harness/modules/generic_test_code/common.py
- packages/adminrouter/extra/src/test-harness/modules/runner/common.py
- packages/adminrouter/extra/src/test-harness/modules/util.py
- packages/adminrouter/extra/src/test-harness/tests/conftest.py
- packages/adminrouter/extra/src/test-harness/tests/open/test_auth.py
- packages/adminrouter/extra/src/test-harness/tests/open/test_master.py
- packages/adminrouter/extra/src/test-harness/tests/test_auth.py
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-ui/buildinfo.json
- packages/metronome/buildinfo.json
- packages/telegraf/buildinfo.json
[master] chore(dcos-ui): bump DC/OS UI v2.40.0  #3886
Metronome 0.6.x Bump to DCOS 1.13  #3883 
[1.13] Set user-agent configs for telegraf plugins #3870 
Route Admin Router error log to /dev/log #3862
Bump dcos-diagnostics  #3797
> Master train 12/06/2018

- CHANGES.md
- packages/adminrouter/extra/src/includes/main/common.conf
- packages/adminrouter/extra/src/test-harness/modules/generic_test_code/common.py
- packages/adminrouter/extra/src/test-harness/modules/runner/common.py
- packages/adminrouter/extra/src/test-harness/modules/util.py
- packages/adminrouter/extra/src/test-harness/tests/conftest.py
- packages/adminrouter/extra/src/test-harness/tests/open/test_auth.py
- packages/adminrouter/extra/src/test-harness/tests/open/test_master.py
- packages/adminrouter/extra/src/test-harness/tests/test_auth.py
Route error_log messages to /dev/log instead of stderr.
- [https://jira.mesosphere.com/browse/DCOS-43956](https://jira.mesosphere.com/browse/DCOS-43956) Switch AR `error_log` directive to log using `syslog` protocol
___ …
> Route Admin Router error log to /dev/log

- CHANGES.md
- packages/metronome/buildinfo.json
- [DCOS_OSS-4565](https://jira.mesosphere.com/browse/DCOS_OSS-4565) Metronome 0.6.0 bump to DCOS 1.13.
- [DCOS_OSS-4239](https://jira.mesosphere.com/browse/DCOS_OSS-4239) Metronome does not crash when exception during startup happens.
- [DCOS_OSS-4344](https://jira.mesosphere.com/browse/DCOS_OSS-4344) Expose ability to enable and disable suppression.
- [DCOS_OSS-4434](https://jira.mesosphere.com/browse/DCOS_OSS-4434) UCR Support.
- [DCOS_OSS-4464](https://jira.mesosphere.com/browse/DCOS_OSS-4464) Add support for `IS` operator for constraints
- …
> Metronome 0.6.x Bump to DCOS 1.13

- CHANGES.md
- packages/dcos-ui/buildinfo.json
* [DCOS_OSS-4245](https://jira.mesosphere.com/browse/DCOS_OSS-4245) Owner column alignment is incorrect on the files tab of a task detail
* [DCOS-45393](https://jira.mesosphere.com/browse/DCOS-45393) Add GPU to Nodes Detail Page
* [DCOS-44456](https://jira.mesosphere.com/browse/DCOS-44456) Localize sidebar categories and primary navigation
* [DCOS-44138](https://jira.mesosphere.com/browse/DCOS-44138) i18n Mark is imported twice in VirtualNetworkDetail
* [DCOS-43620](https://jira.mesosphere.com/browse/DCOS-43620) Multi-container JSON editor deletes properties not supported by the form
* …
> [master] chore(dcos-ui): bump DC/OS UI v2.40.0

- CHANGES.md
- packages/dcos-net/buildinfo.json
In case of docker containerizer if the backend to a VIP is the
actual container ip then the application running in the container
cannot access its own VIP. The only way to make it work is to go
through port mapping. This patch fixes the port mapping such that
the backend is the host IP:port intead of container ip:port
jira: DCOS-45115
- [DCOS_45115](https://jira.mesosphere.com/browse/DCOS-45115) COPS-4087: Docker container unable to curl its own VIP
___ …
> [Backport][1.12] bump dcos-net for fix for docker services in bridge/container mode

- packages/dcos-net/buildinfo.json
In case of docker containerizer if the backend to a VIP is the
actual container ip then the application running in the container
cannot access its own VIP. The only way to make it work is to go
through port mapping. This patch fixes the port mapping such that
the backend is the host IP:port intead of container ip:port
jira: DCOS-45115
- [DCOS_45115](https://jira.mesosphere.com/browse/DCOS-45115) COPS-4087: Docker container unable to curl its own VIP
___ …
> bump dcos-net for fix for docker services in bridge/container mode

- packages/mesos/extra/patches/0006-Made-agent-state-consistent-with-forwarded-updates.patch
- packages/mesos/extra/patches/0007-Added-agent-and-resource-provider-IDs-to-operation-s.patch
- packages/mesos/extra/patches/0008-Set-agent-and-or-resource-provider-ID-in-operation-s.patch
- [MESOS-9293](https://issues.apache.org/jira/browse/MESOS-9293) If a framework looses operation information it cannot reconcile to acknowledge updates.
> [master] Backport MESOS-9293 to DC/OS Mesos master version

- CHANGES.md
Addresses PR feedback - https://github.com/dcos/dcos/pull/3864/files#r238655451
- [DCOS-45870](https://jira.mesosphere.com/browse/DCOS-45870) Remove note about fixing bug in `iam-database-restore` from DC/OS Open - 1.13
> CHANGES.md: Remove incorrect iam-database-restore message

- CHANGES.md
- gen/dcos-config.yaml
- packages/mesos-modules/buildinfo.json
- packages/mesos/extra/start_mesos.sh
Bump mesos module package to include fix for CoreOS 1800.x
- [DCOS_43865](https://jira.mesosphere.com/browse/DCOS-43865) Networking integration tests fail for CoreOS 1800.6.0 1800.7.0, & 1855.4.0 on DC/OS 1.10.8
___ …
> [Backport][1.10] bump mesos module to include fix for CoreOS 1800.x

- CHANGES.md
- packages/adminrouter/extra/src/docs/api/nginx.master.yaml
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/lib/auth/open.lua
- packages/adminrouter/extra/src/test-harness/tests/test_generic.config.yml
- packages/dcos-net/buildinfo.json
Expose Public IPs.
- [DCOS_OSS-4514](https://jira.mesosphere.com/browse/DCOS_OSS-4514) Expose Public IP
- [DCOS_OSS-1837](https://jira.mesosphere.com/browse/DCOS_OSS-1837) Add path-based routing to AR to routing requests to dcos-net
https://github.com/dcos/dcos-net/compare/84ebac51549480817d03d9eabba93438d5df9591...e23a0a53b47f1eb0de66e38cf60e8ecf8f74592d
https://github.com/dcos/dcos-net/pull/104
https://circleci.com/gh/dcos/dcos-net/776 …
> Expose Public IPs

- CHANGES.md
- packages/dcos-ui/buildinfo.json
- [DCOS-46127](https://jira.mesosphere.com/browse/DCOS-46127) Don't fail on flakes
- [DCOS-46056](https://jira.mesosphere.com/browse/DCOS-46056) [1.13] COPS: DC/OS UI shouldn't send Content-Type with GET requests
- [DCOS-45801](https://jira.mesosphere.com/browse/DCOS-45801) [1.13] Some service configuration tabs fails to load
- [DCOS-44661](https://jira.mesosphere.com/browse/DCOS-44661) Extract Data-Layer as it's own library
- [DCOS-43091](https://jira.mesosphere.com/browse/DCOS-43091) [COPS] Logs view / Nodes view don't scroll in Firefox
- [DCOS-44502](https://jira.mesosphere.com/browse/DCOS-44502) [COPS] DC/OS UI crashes after …
> chore(dcos-ui): bump DC/OS UI v2.40.6

- CHANGES.md
- packages/dcos-ui/buildinfo.json
- [DCOS-43324](https://jira.mesosphere.com/browse/DCOS-43324) 
- [DCOS-45494](https://jira.mesosphere.com/browse/DCOS-45494) 
- [DCOS-45698](https://jira.mesosphere.com/browse/DCOS-45698) 
___ …
> [1.12] chore(dcos-ui): bump DC/OS UI v2.25.5

- CHANGES.md
- packages/dcos-ui/buildinfo.json
- DCOS-14285
- DCOS-46169 
- DCOS-14285
- DCOS-46169 
___
* Developers …
> [master] Bump DC/OS UI v2.40.8

- packages/mesos-dns/buildinfo.json
* Bump mesos-dns to golang 1.11 builder
* Fixes illegal host record record compression for SRV responses (via miekg/dns bump)
- [DCOS_OSS-4128](https://jira.mesosphere.com/browse/DCOS_OSS-4128) Update mesos-dns jobs + repo to use &gt; golang17
___ …
> mesos-dns: bump golang to 1.11, misc fixes

- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
- packages/mesos/extra/patches/0004-Added-received-timestamp-into-process-Request.patch
- packages/mesos/extra/patches/0005-Added-task-health-check-definitions-to-master-API-re.patch
- packages/mesos/extra/patches/0006-Introduced-logResponse-for-http-handlers.patch
- packages/mesos/extra/patches/0007-Logged-request-processing-time-for-some-endpoints.patch
- packages/mesos/extra/patches/0008-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch
- packages/mesos/extra/patches/0009-Added-HEARTBEAT-events-and-calls-for-the-executor-HT.patch
- packages/mesos/extra/patches/0010-Refactored-master-and-agent-streaming-connections.patch
- packages/mesos/extra/patches/0011-Added-heartbeaters-for-agent-and-HTTP-executors.patch
- packages/mesos/extra/patches/0012-Added-tests-for-agent-executor-heartbeating.patch
This PR adds patches to Mesos 1.7.x to integrate functionality which has been merged into Mesos master: bidirectional executor <=> agent heartbeats. These serve to prevent network intermediaries from interfering with agent/executor communication when those connections would otherwise sit idle for long periods of time.
- [DCOS_OSS-4607](https://jira.mesosphere.com/browse/DCOS_OSS-4607) Add Mesos agent <=> executor heartbeats
___
**What is the …
> Add Mesos patches for executor <=> agent heartbeats.

- CHANGES.md
- packages/dcos-ui/buildinfo.json
DCOS-46279 DCOS-44814 
DCOS-46279 DCOS-44814 
___
* Developers …
> [master] Bump DC/OS UI v2.40.10

- owners.json
adding Julian & Lee to owners.json
___ …
> Add Julian & Lee to owners.json

- CHANGES.md
- packages/dcos-ui/buildinfo.json
DCOS_OSS-4597 
DCOS_OSS-4597 
___ …
> [1.12] Bump DC/OS UI v2.25.11

- packages/marathon/buildinfo.json
Bump marathon to 1.7.188
- [MARATHON-8498](https://jira.mesosphere.com/browse/MARATHON-8498) - Fixed a secrets validator error which previously did not allow the users to submit a change to a secret environment variable without also submitting the corresponding secrets section.
- [MARATHON-8493](https://jira.mesosphere.com/browse/MARATHON-8493) - Fixed a rare precision issue when computing resources needed to start a pod. Additionally, we now count in executor GPU resources when computing the resource consumption. 
- [MARATHON-8453](https://jira.mesosphere.com/browse/MARATHON-8453) - Fixed a bug where overdue tasks (those that take too much time to start) would be killed without taking …
> Bump marathon to 1.7.188

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-ui/buildinfo.json
- packages/marathon/buildinfo.json
- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
- packages/telegraf/buildinfo.json
- packages/telegraf/extra/dcos-telegraf.service
[1.12] Bump Mesos to nightly 1.7.x b97f0ba  #4032
[1.12] Add user-editable telegraf config dir  #4021
[1.12] Bump DC/OS UI v2.25.11  #4007
[1.12] Flaky test_metrics.deploy_and_cleanup_dcos_package  #4002
Bump marathon to 1.7.188 #4020
> 1.12 train 12/19

- packages/dcos-ui/buildinfo.json
DCOS-46171 DCOS-45803 DCOS-46127 DCOS-40640 
DCOS-46171 DCOS-45803 DCOS-46127 DCOS-40640 
___
* Developers who understand the …
> [1.11] Automated Bump DC/OS UI v1.26.2

- packages/marathon/buildinfo.json
Bump Marathon to 1.7.189
- [MARATHON-8539](https://jira.mesosphere.com/browse/MARATHON-8539) Marathon drops on recognized fields for volume sources on offer reply
> Bump Marathon to 1.7.189

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
* Update DC/OS version to 1.12.1
* We should not be updating the fixVersion yet.
> Update version to 1.12.1

- packages/dcos-integration-test/extra/test_metrics.py
This PR addresses some comments made previously in another PR: https://github.com/dcos/dcos/pull/3495
- [DCOS_OSS-4566](https://jira.mesosphere.com/browse/DCOS_OSS-4566) Fixes for DC/OS metrics tests
___
* Developers who understand the …
> Small fixes and cleanup in the metrics tests.

- packages/adminrouter/docker/requirements-tests.txt
- packages/python-requests/buildinfo.json
- setup.py
* DCOS_OSS-4418 - Address Github Reported Security Vulnerability
> DCOS_OSS-4418 - Address Github Reported Security Vulnerability

- packages/adminrouter/docker/requirements-tests.txt
- packages/python-requests/buildinfo.json
- setup.py
DCOS_OSS-4418 - Address Github Reported Security Vulnerability 
Cherry pick - https://github.com/dcos/dcos/pull/3786/
> Update requests to 2.20.1 and urllib3 to 1.24.1

- packages/dcos-ui/buildinfo.json
> [1.11] Automated Bump DC/OS UI v1.26.3

- packages/dcos-ui/buildinfo.json
DCOS-46247 DCOS_OSS-4579 
DCOS-46247 DCOS_OSS-4579 
___
* Developers …
> [1.12] Automated Bump DC/OS UI v2.25.12

- packages/dcos-ui/buildinfo.json
DCOS-44594 DCOS-34504 DCOS-21270 DCOS-21203 DCOS-20690 DCOS-46278 DCOS-21600 DCOS-21600 DCOS-46294 
DCOS-44594 DCOS-34504 DCOS-21270 DCOS-21203 DCOS-20690 DCOS-46278 DCOS-21600 DCOS-21600 DCOS-46294 
___ …
> [master] Automated Bump DC/OS UI v2.42.1

- packages/dcos-integration-test/extra/test_meta.py
(cherry picked from commit 727edb87fd429dabb225299dc5edee5ef61f3db8)
Set the maintainer / contact metadata for `test_meta.py`.
- [DCOS-46574](https://jira.mesosphere.com/browse/DCOS-46574) Set maintainer metadata on test_meta.py
___
> dcos-integration-test/test_meta.py: add contact metadata [1.10]

- packages/marathon/buildinfo.json
* Bump Marathon to 1.7.189
* Cherry-pick of 78257b9fe67124a3d25c5cad4a8604a52cf8d580, which already landed on the 1.12 branch.
- [MARATHON-8539](https://jira.mesosphere.com/browse/MARATHON-8539) Marathon drops on recognized fields for volume sources on offer reply
___ …
> marathon: bump to version 1.7.189-48bfd6000

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This PR unmutes and fixes a once flaky test which has been muted because of its flakyness. But since it's been muted other bugs have been introduced that did not lead to a failed test. 
- [DCOS_OSS-4531](https://jira.mesosphere.com/browse/DCOS_OSS-4531) test_dcos_diagnostics.test_dcos_diagnostics_bundle_download_and_extract assertionerror test bundle download and validate zip file
___ …
> Add missing comma, fix formatting and unmute diagnostics test

- packages/curl/build
- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- packages/flask/buildinfo.json
- packages/python-certifi/build
- packages/python-certifi/buildinfo.json
- packages/python-cryptography/buildinfo.json
- packages/python-idna/build
- packages/python-idna/buildinfo.json
- packages/python-requests/build
- packages/python-requests/buildinfo.json
- setup.py
* DCOS-OSS-4418 - Address Requests Security Vulnerability
> Update Requests Library for DC/OS 1.10

- packages/dcos-integration-test/extra/test_metrics.py
Increases retry period from 10s to 5min. Also increased all other retry periods to minimum of 5min to avoid more potential flakes down the line.
- [DCOS-46190](https://jira.mesosphere.com/browse/DCOS-46190) test_metrics.test_standalone_container_metrics
> [1.12] Fix flaky test_standalone_container_metrics

- mergebot-config.json
Update mergebot fix version map for 1.12
> Update mergebot fix version map for 1.12

- gen/calc.py
- gen/dcos-config.yaml
- packages/bootstrap/extra/dcos_internal_utils/bootstrap.py
- packages/bootstrap/extra/dcos_internal_utils/cli.py
- packages/dcos-net/buildinfo.json
- packages/dcos-net/extra/dcos-net-env
Erlang cookie serves as membership token in a distributed system.
Having it configurable would allow different DC/OS clusters to
co-exist without interfering each other.
- [DCOS_OSS-4620](https://jira.mesosphere.com/browse/DCOS_OSS-4620) Make cluster identity configurable in dcos-net
___ …
> [Backport] [1.11.7-1] Makes erlang cookie configurable.

- gen/dcos-config.yaml
Add Metronome jobs to diagnostics bundle
- [DCOS_OSS-4634](Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-4634) Add Metronome jobs to diagnostics bundle
> Add Metronome jobs to diagnostics bundle

- packages/dcos-integration-test/extra/test_networking.py
Unmute test_vip. Please see last comments in the linked jira ticket.
- [DCOS-45799](https://jira.mesosphere.com/browse/DCOS-45799) test_networking.test_vip [Container_MESOS-Network_HOST-Network_HOST]  (container stuck in PROVISIONING)
___ …
> Unmute test_vip

- packages/dcos-integration-test/extra/test_meta.py
(cherry picked from commit 727edb87fd429dabb225299dc5edee5ef61f3db8)
Set the maintainer / contact metadata for `test_meta.py`.
- [DCOS-46574](https://jira.mesosphere.com/browse/DCOS-46574) Set maintainer metadata on test_meta.py
___
> dcos-integration-test/test_meta.py: add contact metadata [1.11]

- packages/dcos-integration-test/extra/test_meta.py
Set the maintainer / contact metadata for `test_meta.py`.
- [DCOS-46574](https://jira.mesosphere.com/browse/DCOS-46574) Set maintainer metadata on test_meta.py
___
> dcos-integration-test/test_meta.py: add contact metadata

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- gen/tests/test_config.py
This patch exposes a mesos flag --network_cni_root_dir_persist
through dcos config so that an operator may choose to persist
the cni root dir. The default value is `false` for backward
compatibility
- [DCOS_OSS-4667](https://jira.mesosphere.com/browse/DCOS_OSS-4667) Expose mesos flag to persist network cni root directory
___ …
> Exposes mesos flag to persist cni root directory across host reboot.

- dcos_installer/test_backend.py
- gen/calc.py
Update DC/OS 1.10 version to 1.10.10
> Update Version to 1.10.10

- packages/dcos-integration-test/extra/test_metrics.py
Changes some metrics integration tests (where applicable) to run tests on one node per role (public/private agent, master).
- [DCOS_OSS-4356](https://jira.mesosphere.com/browse/DCOS_OSS-4356) Run metrics tests on one node from each role
> [1.13] Run metrics tests on one node per role

- packages/dcos-ui/buildinfo.json
DCOS-44820 DCOS-44818 DCOS-43909 DCOS-41059 
DCOS-44820 DCOS-44818 DCOS-43909 DCOS-41059 
___
* Developers who understand the …
> [master] Automated Bump DC/OS UI v2.45.0

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- packages/bootstrap/extra/dcos_internal_utils/bootstrap.py
- packages/bootstrap/extra/dcos_internal_utils/cli.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-net/buildinfo.json
- packages/dcos-net/extra/dcos-net-env
Erlang cookie serves as a membership token in a distributed system. Having it configurable would allow different DC/OS clusters to co-exist without interfering each other. The requirement is that it should be unique and persistent during the lifecycle for a given DC/OS cluster. The idea is to use `cluster_id` as it satisfies both the requirements.
- [DCOS_OSS-4620](https://jira.mesosphere.com/browse/DCOS_OSS-4620) Make cluster identity configurable in dcos-net
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY …
> Makes erlang cookie configurable

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- packages/bootstrap/extra/dcos_internal_utils/bootstrap.py
- packages/bootstrap/extra/dcos_internal_utils/cli.py
- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-net/buildinfo.json
- packages/dcos-net/extra/dcos-net-env
Erlang cookie serves as a membership token in a distributed system. Having it configurable would allow different DC/OS clusters to co-exist without interfering each other. The requirement is that it should be unique and persistent during the lifecycle for a given DC/OS cluster. The idea is to use cluster_id as it satisfies both the requirements.
- [DCOS_OSS-4620](https://jira.mesosphere.com/browse/DCOS_OSS-4620) Make cluster identity configurable in dcos-net
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY …
> [Backport] [1.11] Makes erlang cookie configurable.

- packages/dcos-integration-test/extra/test_meta.py
(cherry picked from commit 727edb87fd429dabb225299dc5edee5ef61f3db8)
Set the maintainer / contact metadata for `test_meta.py`.
- [DCOS-46574](https://jira.mesosphere.com/browse/DCOS-46574) Set maintainer metadata on test_meta.py
___
> dcos-integration-test/test_meta.py: add contact metadata [1.12]

- gen/dcos-config.yaml
Looks like there was a rebase/merge error somewhere in master which resulted in duplicated configs. Just cleaning that up here.
> [1.13] Fix merge error in config

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
These tests were accidently deleted while refactoring the diagnostics
test suite in b0848af86370031e8f41a63881f2e33b4afdd3aa.
Since the first of these two tests is why [DCOS-43987](https://jira.mesosphere.com/browse/DCOS-43987) was created, we mark it as flaky after bringing it back.
- [DCOS-43987](https://jira.mesosphere.com/browse/DCOS-43987) test_dcos_diagnostics.test_dcos_diagnostics_runner_poststart is flaky
___ …
> [1.11] DCOS-43987 - Restore accidently deleted tests

- gen/dcos-config.yaml
Add Metronome jobs to diagnostics bundle
Backports: #4100 
---
- [DCOS_OSS-4718](Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-4718) Add Metronome jobs to diagnostics bundle
> [1.11] Add Metronome jobs to diagnostics bundle

- packages/dcos-integration-test/extra/test_metrics.py
Changes some metrics integration tests (where applicable) to run tests on one node per role (public/private agent, master).
- [DCOS_OSS-4356](https://jira.mesosphere.com/browse/DCOS_OSS-4356) Run metrics tests on one node from each role
> [1.12] Run metrics tests on one node per role

- packages/dcos-ui/buildinfo.json
DCOS-47536 DCOS-47513 DCOS-47339 
DCOS-47536 DCOS-47513 DCOS-47339 
___
* …
> [1.12] Automated Bump DC/OS UI v2.26.2

- gen/dcos-config.yaml
Add Metronome jobs to diagnostics bundle
Backports: #4100 
---
- [DCOS_OSS-4717](Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-4717) Add Metronome jobs to diagnostics bundle
> [1.12] Add Metronome jobs to diagnostics bundle

- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Bacports: #4141 #4266 
---
- [DCOS_OSS-4610](https://jira.mesosphere.com/browse/DCOS_OSS-4610) dcos-diagnostics long running command block status requests
___ …
> [1.12] Bump dcos-diagnostics

- .gitattributes
- CHANGES.md
Backport of https://github.com/dcos/dcos/pull/4272
Add .gitattributes and update CHANGES.md
> Add .gitattributes and update CHANGES.md

- pkgpanda/__init__.py
- pkgpanda/build/src_fetchers.py
- pkgpanda/docs/create_and_maintain_packages.md
- pkgpanda/util.py
Fix two small bugs in pkgpanda
___
It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the …
> Pkgpanda bugfixes

- gen/dcos-config.yaml
Add Metronome jobs to diagnostics bundle
Backports: #4100 
---
- [DCOS_OSS-4719](Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-4719) Add Metronome jobs to diagnostics bundle
> [1.10] Add Metronome jobs to diagnostics bundle

- .gitattributes
Backport of #4272
Add .gitattributes to deal with CHANGES.md conflict
> Add .gitattributes to deal with CHANGES.md conflict

- packages/mesos-dns/buildinfo.json
* More verbose log message when new masters are detected.
* Clarify error message when there are no masters to query.
- [DCOS_OSS-1880](https://jira.mesosphere.com/browse/DCOS_OSS-1880) Update Mesos DNS configuration to print more logs.
* This is a logging change.
* This is a logging change.
* https://github.com/mesosphere/mesos-dns/compare/0b2f907d03325a46295d8da524a8099d3cb68deb...28427c25d147e2324452702fda50f42a5dd8723b
* N/A
___ …
> mesos-dns: bump to latest master

- owners.json
> Add adamdangoor owner 1.13

- CHANGES.md
- packages/dcos-integration-test/extra/test_exhibitor.py
- packages/dcos-integration-test/extra/test_groups.yaml
- packages/exhibitor/extra/start_exhibitor.py
Back-port of #4316
Tighten up permissions for ZooKeeper data directories
- [DCOS-47687](https://jira.mesosphere.com/browse/DCOS-47687) Tighten up permissions on /var/log/dcos/exhibitor
___ …
> [1.12] Tighten up permissions for ZooKeeper data directories

- packages/cosmos/buildinfo.json
- [DCOS_OSS-4662](https://jira.mesosphere.com/browse/DCOS_OSS-4662) Better logging during uninstall of a package in Cosmos
- [DCOS-45776](https://jira.mesosphere.com/browse/DCOS-45776) Cosmos should be able to handle large numbers for Longs
- [DCOS-45802](https://jira.mesosphere.com/browse/DCOS-45802) 'dcos', 'package', 'install', 'dcos-enterprise-cli' fails with "Could not access data at URI for repository"
If you are changing components or packages in DC/OS (e.g. you are bumping the …
> Update to latest version of cosmos

- CHANGES.md
- packages/docker-gc/extra/dcos-docker-gc.service
Allows users to configure `docker-gc` without those changes resetting on cluster upgrade.
- [DCOS_OSS-1140](https://jira.mesosphere.com/browse/DCOS_OSS-1140)
___
* Developers …
> Change docker-gc to allow for changing envvars in user-accessible location

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Add docker version to diagnostics bundle
Backports: #4310
---
___ …
> [1.11] Add docker version to diagnostics bundle

- packages/cosmos/buildinfo.json
Backport for #4301
- [DCOS_OSS-4662](https://jira.mesosphere.com/browse/DCOS_OSS-4662) Better logging during uninstall of a package in Cosmos
- [DCOS-45776](https://jira.mesosphere.com/browse/DCOS-45776) Cosmos should be able to handle large numbers for Longs
- [DCOS-45802](https://jira.mesosphere.com/browse/DCOS-45802) 'dcos', 'package', 'install', 'dcos-enterprise-cli' fails with "Could not access data at URI for repository"
If you are changing components or packages in DC/OS (e.g. you …
> [1.12] Update to latest version of cosmos

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Add docker version to diagnostics bundle
___ …
> Add docker version to diagnostics bundle

- packages/dcos-test-utils/buildinfo.json
Bump test utils
- [DCOS-41819](https://jira.mesosphere.com/browse/DCOS-41819)
___
It is …
> Bump dcos-test-utils to latest commit on master

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Add docker version to diagnostics bundle
Backports: #4310
---
___ …
> [1.10] Add docker version to diagnostics bundle

- CHANGES.md
- gen/build_deploy/bash.py
Backport of https://github.com/dcos/dcos/pull/4396
- [[DCOS-15890] DCOS advance installer pre-flight check has a wrong error message](https://jira.mesosphere.com/browse/DCOS-15890)
- 
___
* …
> [1.12] DCOS-15890 - Check Docker is running before version check

- gen/build_deploy/bash/installer_internal_wrapper.in
This backports https://github.com/dcos/dcos/pull/4397
> [1.12] DCOS-16098 - Correct filename in dcos_generate_config.ee.sh help

- mergebot-config.json
* Fix the mergebot config for 1.11
* Remove 1.9 branch reference
> Fix the mergebot config for 1.11

- CHANGES.md
- gen/build_deploy/bash.py
Backport of https://github.com/dcos/dcos/pull/4396
- [[DCOS-15890] DCOS advance installer pre-flight check has a wrong error message](https://jira.mesosphere.com/browse/DCOS-15890)
- 
___
* …
> [1.11] DCOS-15890 - Check Docker is running before version check

- pkgpanda/docker/dcos-builder/Dockerfile
Bump docker-builder go version
- [DCOS_OSS-3733](https://jira.mesosphere.com/browse/DCOS_OSS-3733)
___ …
> Update Go version in dcos-builder

- gen/build_deploy/bash/installer_internal_wrapper.in
This backports https://github.com/dcos/dcos/pull/4397
> [1.11] DCOS-16098 - Correct filename in dcos_generate_config.ee.sh help

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- [DCOS_OSS-4757](https://jira.mesosphere.com/browse/DCOS_OSS-4757) Include detect_ip in dcos-diagnostics bundle
___
All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-revi …
> Add detect_ip to diagnostics bundle

- packages/cosmos/buildinfo.json
- [DCOS-45428](https://jira.mesosphere.com/browse/DCOS_45428) Cosmos decodes URL parameter and it breaks resource links
___
All PRs require 2 approvals using GitHub's …
> [DCOS-45428] Bump cosmos to latest version

- packages/cosmos/buildinfo.json
Backport of #4409 
- [DCOS-45428](https://jira.mesosphere.com/browse/DCOS_45428) Cosmos decodes URL parameter and it breaks resource links
___ …
> [1.12][DCOS-45428] Bump cosmos to latest version

- packages/dcos-integration-test/extra/test_metrics.py
Tried wrapping the `cosmos.uninstall_package` in a 15min retry, but the retry complained that the package was already uninstalled. Switched to looking at `completed_frameworks` mesos /state response, but also ran into flake. I added some logs of the frameworks response, and found that in the flake, the framework remained under `'frameworks'` object but the `tasks` list within eventually emptied out to 0 (moved to `completed_tasks`). I think this could be a good way of assessing the framework as been torn down sufficiently if there are no longer any running tasks.
- [DCOS_OSS-4568](https://jira.mesosphere.com/browse/DCOS_OSS-4568) test_metrics.deploy_and_cleanup_dcos_package Framework hello-world still …
> [1.12] Fix hello-world flaky teardown

- packages/dcos-integration-test/extra/test_metrics.py
Tried wrapping the `cosmos.uninstall_package` in a 15min retry, but the retry complained that the package was already uninstalled. Switched to looking at `completed_frameworks` mesos /state response, but also ran into flake. I added some logs of the frameworks response, and found that in the flake, the framework remained under `'frameworks'` object but the `tasks` list within eventually emptied out to 0 (moved to `completed_tasks`). I think this could be a good way of assessing the framework as been torn down sufficiently if there are no longer any running tasks.
- [DCOS_OSS-4568](https://jira.mesosphere.com/browse/DCOS_OSS-4568) test_metrics.deploy_and_cleanup_dcos_package Framework hello-world still …
> [1.13] Fix hello-world flaky teardown

- test-e2e/test_groups.yaml
* Exercise test-e2e on dcos/dcos  
Test Execution here: https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Open_Test_DcosDocker_DcosTestE2eGroup1&branch_DcOs_Open_Test_DcosDocker=pull%2F4445&tab=buildTypeStatusDiv
Test Execution status is published under key *teamcity/dcos/test/test-e2e/group1* (Can be seen in this PR)
> Exercise test-e2e on dcos/dcos 

- packages/mesos/build
- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
- packages/mesos/extra/patches/0004-Added-received-timestamp-into-process-Request.patch
- packages/mesos/extra/patches/0005-Added-task-health-check-definitions-to-master-API-re.patch
- packages/mesos/extra/patches/0006-Introduced-logResponse-for-http-handlers.patch
- packages/mesos/extra/patches/0007-Logged-request-processing-time-for-some-endpoints.patch
- packages/mesos/extra/patches/0008-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch
- packages/mesos/extra/patches/0009-Added-HEARTBEAT-events-and-calls-for-the-executor-HT.patch
- packages/mesos/extra/patches/0010-Refactored-master-and-agent-streaming-connections.patch
- packages/mesos/extra/patches/0011-Added-heartbeaters-for-agent-and-HTTP-executors.patch
- packages/mesos/extra/patches/0012-Added-tests-for-agent-executor-heartbeating.patch
- packages/mesos/extra/patches/0013-Changed-master-to-hold-subscribers-in-a-circular-buf.patch
- packages/mesos/extra/patches/0014-Added-gauge-metric-for-operator-event-stream-subscri.patch
- packages/mesos/extra/patches/0015-Reverted-the-container-sandbox-permission-from-0750-.patch
- packages/mesos/extra/patches/0016-Added-Linux-memfd-support.patch
- packages/mesos/extra/patches/0017-Made-the-code-more-robust-related-to-sendfile.patch
- packages/mesos/extra/patches/0018-Added-a-test-to-test-memfd-file-clone.patch
- packages/mesos/extra/patches/0019-Updated-handleWhitelistFds-to-avoid-closing-FDs-with.patch
- packages/mesos/extra/patches/0020-Cloned-a-sealed-file-of-launcher-binary.patch
- packages/mesos/extra/patches/0021-Cleaned-up-command-executor-redundant-command-string.patch
- packages/mesos/extra/patches/0022-Added-enable-launcher-sealing-compiler-flag.patch
- packages/mesos/extra/patches/0023-Enabled-launcher-sealing-depending-on-corresponding-.patch
- packages/mesos/extra/patches/0024-Fixed-ROOT_PidNamespace-test-after-enabling-launcher.patch
- packages/mesos/extra/patches/0025-Secured-mesos-executor-binary-using-memfd.patch
> DCOS-48052: 1.12.2

- packages/mesos/build
- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Mesos-UI-Change-paths-pailer-and-logs-to-work-with-a.patch
- packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch
- packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0005-Included-nested-command-check-output-in-the-executor.patch
- packages/mesos/extra/patches/0006-Made-the-log-output-handling-of-TCP-and-HTTP-checks-.patch
- packages/mesos/extra/patches/0007-Raised-the-logging-level-of-some-check-and-health-ch.patch
- packages/mesos/extra/patches/0008-Improved-logging-for-offers-and-inverse-offers.patch
- packages/mesos/extra/patches/0009-Logged-the-resources-in-DRF-sorter-CHECKs.patch
- packages/mesos/extra/patches/0010-Added-verbose-logging-in-Sorter-Allocation.patch
- packages/mesos/extra/patches/0011-Put-TerminateEvent-at-the-end-of-the-queue-in-the-Me.patch
- packages/mesos/extra/patches/0012-Waited-for-TEARDOWN-to-be-sent-in-v1-Java-scheduler-.patch
- packages/mesos/extra/patches/0013-Added-task-health-check-definitions-to-master-API-re.patch
- packages/mesos/extra/patches/0014-Added-Linux-memfd-support.patch
- packages/mesos/extra/patches/0015-Made-the-code-more-robust-related-to-sendfile.patch
- packages/mesos/extra/patches/0016-Added-a-test-to-test-memfd-file-clone.patch
- packages/mesos/extra/patches/0017-Cloned-a-sealed-file-of-launcher-binary.patch
- packages/mesos/extra/patches/0018-Cleaned-up-command-executor-redundant-command-string.patch
- packages/mesos/extra/patches/0019-Added-disable-libtool-wrapper-configuration-to-Mesos.patch
- packages/mesos/extra/patches/0020-Added-enable-launcher-sealing-compiler-flag.patch
- packages/mesos/extra/patches/0021-Enabled-launcher-sealing-depending-on-corresponding-.patch
- packages/mesos/extra/patches/0022-Fixed-ROOT_PidNamespace-test-after-enabling-launcher.patch
- packages/mesos/extra/patches/0023-Secured-mesos-executor-binary-using-memfd.patch
> DCOS-48052: 1.10.10.1

- dcos_installer/test_backend.py
- gen/calc.py
> update version to 1.10.10.1

- dcos_installer/test_backend.py
- gen/calc.py
Update version number to 1.11.9.1
> Update DC/OS Version number to 1.11.9.1

- packages/dcos-integration-test/extra/test_iam.py
Adds missing integration test for supporting user account creation + uid/password login.
- [DCOS_OSS-4767](https://jira.mesosphere.com/browse/DCOS_OSS-4767) OSS integration test for Bouncer password authentication.
> Integration test for user account functionality

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Bacports: https://github.com/dcos/dcos/pull/4394
---
- [DCOS_OSS-4757](https://jira.mesosphere.com/browse/DCOS_OSS-4757) Include detect_ip in dcos-diagnostics bundle
___ …
> [1.11] Add detect_ip to diagnostics bundle

- gen/calc.py
- gen/dcos-config.yaml
Added `ui-update` plugin to `/etc/ui-config.json` to enable a new ui plugin that gives access to update the UI using the new UI update service.
- [DCOS-47966](https://jira.mesosphere.com/browse/DCOS-47966) UX for UI Update/Reset flow.
___ …
> DCOS-47966 Enable UI-Update plugin for UI

- mergebot-config.json
* https://jira.mesosphere.com/browse/DCOS-48369 -  Update fix Versions to active supported Versions of DC/OS 
--- 
How to Review
* Make sure that these versions point to our in-development version of DC/OS
> Update Mergebot Fix Versions.

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Add docker version to diagnostics bundle
Backports: #4310
---
___ …
> [1.12] Add docker version to diagnostics bundle

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Backports: https://github.com/dcos/dcos/pull/4499
---
- [DCOS-42928](https://jira.mesosphere.com/browse/DCOS-42928) Include docker ps in diagnostics bundle
___ …
> [1.11] Include docker ps in diagnostics bundle

- packages/dcos-integration-test/extra/test_units.py
Remove flaky test marker for DCOS-41819
- [DCOS-41819](https://jira.mesosphere.com/browse/DCOS-41819)
___
* Developers responsible for code that interacts with or depends on the code …
> Remove flaky test marker for DCOS-41819

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Include `docker ps` in diagnostics bundle
- [DCOS-42928](https://jira.mesosphere.com/browse/DCOS-42928) Include docker ps in diagnostics bundle
___ …
> Include docker ps in diagnostics bundle

- packages/dcos-integration-test/extra/test_units.py
This unmutes the tests after unable to reproduce test flakiness both on CI and locally. After test is unmuted, I will monitor it for a few days.
- [DCOS-45174](https://jira.mesosphere.com/browse/DCOS-45174) test_units.test_socket_files_teardown failing with 503 Server Error: Service Unavailable for url
___ …
> [DCOS-45174] Unmute test_units.test_socket_files

- pkgpanda/__init__.py
This is the backport of https://github.com/dcos/dcos/pull/4482
> [1.11] DCOS_OSS-4097 - Explicitly create user groups in pkgpanda

- pkgpanda/__init__.py
This the backport of https://github.com/dcos/dcos/pull/4482
> [1.12] DCOS_OSS-4097 - Explicitly create user groups in pkgpanda

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
---
- [DCOS_OSS-4757](https://jira.mesosphere.com/browse/DCOS_OSS-4757) Include detect_ip in dcos-diagnostics bundle
- [DCOS-42928](https://jira.mesosphere.com/browse/DCOS-42928) Include docker ps in diagnostics bundle
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE …
> [1.12] include docker ps in diagnostic bundle

- packages/dcos-integration-test/extra/test_units.py
(cherry picked from commit ceff696d277691796c1d91fde5a761a4a2dc155d)
Backports [4500](https://github.com/dcos/dcos/pull/4500)
___ …
> [1.12] Unmute test_units.test_socket_files

- CHANGES.md
- packages/adminrouter/extra/src/docs/api/nginx.agent.html
- packages/adminrouter/extra/src/docs/api/nginx.agent.yaml
- packages/adminrouter/extra/src/docs/api/nginx.master.html
- packages/adminrouter/extra/src/docs/api/nginx.master.yaml
- packages/adminrouter/extra/src/includes/http/agent.conf
- packages/adminrouter/extra/src/includes/http/common.conf
- packages/adminrouter/extra/src/includes/http/master.conf
- packages/adminrouter/extra/src/includes/http/open/master.conf
- packages/adminrouter/extra/src/includes/server/common.conf
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/includes/server/open/master.conf
- packages/adminrouter/extra/src/test-harness/modules/generic_test_code/common.py
- packages/adminrouter/extra/src/test-harness/tests/test_security.py
- packages/adminrouter/extra/src/test-harness/tests/test_service.py
- packages/dcos-integration-test/extra/test_adminrouter_open.py
- packages/dcos-integration-test/extra/test_groups.yaml
Stop Admin Router using the `Host` header for redirections.
Code review identified that generated API docs had been manually edited, so this PR also updates the source references to latest versions.
- [DCOS-47845](https://jira.mesosphere.com/browse/DCOS-47845) Modify Admin Router rewrites to not redirect to Host header address
___
All PRs …
> Use relative redirects to avoid using Host header

- pkgpanda/__init__.py
pkgpanda previously relied on the fact that the `useradd` command creates a matching group for a newly-created user.
But that's not always the case and only worked "by accident" because it was set in the `USERGROUPS_ENAB` setting in `/etc/login.defs`. (See https://linux.die.net/man/8/useradd for more information about this)
This commit makes the behaviour explicit and work regardless of preconfigured settings by using the `--user-group`/`-U` argument to `useradd`.
- [[DCOS_OSS-4097] pkgpanda: Explicitly create user groups for all users - JIRA](https://jira.mesosphere.com/browse/DCOS_OSS-4097)
-  …
> DCOS_OSS-4097 - Explicitly create user groups in pkgpanda

- packages/dcos-diagnostics/buildinfo.json
- [DCOS-47646](https://jira.mesosphere.com/browse/DCOS-47646) 
___ …
> Bunp dcos-diagnostics

- CHANGES.md
- gen/dcos-config.yaml
- packages/adminrouter/docker/Dockerfile
- packages/adminrouter/extra/src/docs/api/nginx.master.html
- packages/adminrouter/extra/src/docs/api/nginx.master.yaml
- packages/adminrouter/extra/src/includes/http/master.conf
- packages/adminrouter/extra/src/includes/http/open/master.conf
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/includes/server/open/master.conf
- packages/adminrouter/extra/src/test-harness/tests/test_master.py
- packages/dcos-integration-test/extra/test_ui_update_service.py
- packages/dcos-ui-update-service/build
- packages/dcos-ui-update-service/buildinfo.json
- packages/dcos-ui-update-service/extra/dcos-ui-update-service-pre-start.sh
- packages/dcos-ui-update-service/extra/dcos-ui-update-service.service
- [DCOS-46389](https://jira.mesosphere.com/browse/DCOS-46389) Update Service to swap symlinks instead of serving files by itself
- [DCOS-47996](https://jira.mesosphere.com/browse/DCOS-47996) UI-Update-Service: Return version for Pre-bundled UI
- [DCOS-45188](https://jira.mesosphere.com/browse/DCOS-45188) EE Integration
> UI-service integration part 2

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-net/buildinfo.json
Add basic support for prometheus to dcos-net.
- [DCOS_OSS-4738](https://jira.mesosphere.com/browse/DCOS_OSS-4738) Add basic support for prometheus
https://github.com/dcos/dcos-net/compare/b6fb529a276b5be9b02072f4af9cf07a34b70312...999f63e44f1a663df680bd54a2d5b4d2518cc9dd
https://github.com/dcos/dcos-net/pull/113
https://github.com/dcos/dcos-net/pull/114
https://github.com/dcos/dcos-net/pull/115
https://circleci.com/gh/dcos/dcos-net/849 …
> Add basic support for prometheus

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS-48447) 
___ …
> Add test to check if bundle contains frameworks

- gen/dcos-config.yaml
This change forces Mesos master to have port resources in
every offer unless the offer contains disks. This helps to reduce
the number of offers with no ports which are not useful for most
frameworks.
- [DCOS-46554](https://jira.mesosphere.com/browse/DCOS-46554) Extending the `min_allocatable_resources` to cover non-scalar resources to mitigate port starvation.
___
**What …
> Instruct Mesos master to include port resources in offers.

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Bacports: https://github.com/dcos/dcos/pull/4545
---
___ …
> [1.11] Add test to check if bundle contains frameworks

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Bacports: https://github.com/dcos/dcos/pull/4545
---
___ …
> [1.12] Add test to check if bundle contains frameworks

- gen/tests/test_config.py
This is a 1.12 backport of #4597.
- [DCOS_OSS-4829](https://jira.mesosphere.com/browse/DCOS_OSS-4829) tox failure: test_config.test_validate_check_config
N/A
> (1.12) Fix tests for schema 0.7.0

- gen/tests/test_config.py
This is a 1.11 backport of #4597.
- [DCOS_OSS-4829](https://jira.mesosphere.com/browse/DCOS_OSS-4829) tox failure: test_config.test_validate_check_config
N/A
> (1.11) Fix tests for schema 0.7.0

- gen/tests/test_config.py
This is a 1.10 backport of #4597.
- [DCOS_OSS-4829](https://jira.mesosphere.com/browse/DCOS_OSS-4829) tox failure: test_config.test_validate_check_config
N/A
> (1.10) Fix tests for schema 0.7.0

- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_metronome.py
- packages/dcos-integration-test/extra/test_packaging.py
This only changes the contact/email address for a couple tests from marathon-team@ to orchestration-team@. This is therefor not a user facing change.
There are no associated JIRA tickets
___
* Developers responsible for code that interacts with or depends on the code …
> Updated contacts and team email for tests from marathon-team to orchestration-team

- packages/marathon/buildinfo.json
- [MARATHON-8555](https://jira.mesosphere.com/browse/MARATHON-8555) Parameter --leader_proxy_max_open_connections does not actually allow more concurrent connections
- [MARATHON-8563](https://jira.mesosphere.com/browse/MARATHON-8563) Speed up `v2/pods/::status`
- [MARATHON-8566](https://jira.mesosphere.com/browse/MARATHON-8566) Fix race condition causing deployment info to not be available
- [MARATHON-8555](https://jira.mesosphere.com/browse/MARATHON-8577) Include app-id in illegal-state-exception
- [MARATHON-8586](https://jira.mesosphere.com/browse/MARATHON-8586) Bump marathon for 1.12.3
If you are changing components or packages …
> Bump marathon for 1.12

- packages/dcos-integration-test/extra/test_metronome.py
Test is already unmuted on master.
- [DCOS-40611](https://jira.mesosphere.com/browse/DCOS-40611) test_metronome.test_metronome failed sporadically on Azure ARM platform.
___ …
> Unmute test_metronome

- packages/dcos-integration-test/extra/test_checks.py
Unmute test that is already unmuted on master.
- [DCOS-45278](https://jira.mesosphere.com/browse/DCOS-45278) teamcity/dcos/test/azure/arm: Metronome error 'history for that job run is not available'.
___ …
> Unmute test_checks

- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- setup.py
- test-e2e/requirements.txt
DCOS-49198 - prep_teamcity failing for all DCOS builds
> Fix dcos-image cryptography package dep.

- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- setup.py
- test-e2e/requirements.txt
* DCOS-49198 - prep_teamcity failing for all DCOS builds
> Require wheel package as a dependency for dcos-image.

- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- setup.py
- test-e2e/requirements.txt
DCOS-49198 - prep_teamcity failing for all DCOS builds
> Cherry Pick fix for DCOS-49198 - Fix dcos-image dependency.

- packages/mesos/extra/dcos-mesos-master.service
- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
These three `EnvironmentFile`s will enable the setting of custom `MESOS_DEFAULT_ROLE` through the Universal Installer.
See Design Doc: https://docs.google.com/document/d/1-V_cyUJ9WL0OMmnguKheP0L11ZBrk-PaC9AoUCB8etk/edit#
- [[DCOS-49092] Add three new EnvironmentFiles to Mesos systemd units - JIRA](https://jira.mesosphere.com/browse/DCOS-49092)
- Feature: [[DCOS-47319] Configure custom mesos role with DC/OS Provisioner (install binary) on (some, not all) private agents at install time - JIRA](https://jira.mesosphere.com/browse/DCOS-47319)
- Epic: [[DCOS-48454] Configure custom mesos role with DC/OS Provisioner (install binary) on (some, not all) private agents at …
> DCOS-48402 - Add new EnvironmentFiles to Mesos systemd units

- packages/marathon/buildinfo.json
- [MARATHON-8587](https://jira.mesosphere.com/browse/MARATHON-8587) Handle wrapped requests.
___ …
> Bump Marathon for 1.12.3

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
> update version to 1.12.3

- mergebot-config.json
* Update mergebot fixversion to 1.12.4 - https://jira.mesosphere.com/browse/DCOS-49306
> update mergebot config for next version of DC/OS 1.12

- pkgpanda/test_util.py
- pkgpanda/util.py
This is the backport of https://github.com/dcos/dcos/pull/4629
> [1.11] DCOS-46615 - Make pkgpanda resistant to missing content-length

- pkgpanda/test_util.py
- pkgpanda/util.py
This is the backport of https://github.com/dcos/dcos/pull/4629
> [1.12] DCOS-46615 - Make pkgpanda resistant to missing content-length

- packages/dcos-check-runner/buildinfo.json
Bump check runner.
Changes response when requesting a check that doesn't exist to a 404 instead of a 200 while silently ignoring the missing check.
- [DCOS_OSS-3797](https://jira.mesosphere.com/browse/DCOS_OSS-3797)
___
* Developers …
> bump dcos-check-runner

- gen/aws/templates/cloudformation.json
> DCOS-18825 - Pin the Availability Zone per region for the AWS CF Template

- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_networking.py
> DCOS-46608 - docker pull image ahead of usage in test

- CHANGES.md
- packages/openssl/buildinfo.json
https://jira.mesosphere.com/browse/DCOS_OSS-4868
> openssl: bump to 1.0.2r release

- release/storage/azure.py
This backports - Catch Additional Azure Exceptions #4325
Fixes
* https://jira.mesosphere.com/browse/DCOS-46370 
* https://jira.mesosphere.com/browse/DCOS_OSS-4875
> DCOS_OSS-4875 - Backport Fix to AttributeError: 'Blob' object has no attribute id

- release/storage/azure.py
This backports Catch Additional Azure Exceptions #4325
Fixes
* https://jira.mesosphere.com/browse/DCOS-46370 
* https://jira.mesosphere.com/browse/DCOS_OSS-4875
> DCOS_OSS-4875 - Backport Fix to AttributeError: 'Blob' object has no attribute 'id'

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-net/buildinfo.json
Add dcos-dns metrics for forwarders.
- [DCOS-48336](https://jira.mesosphere.com/browse/DCOS-48336)  Add dcos-dns metrics for forwarders
> [dcos/dcos-net@999f63e...3e6119a](https://github.com/dcos/dcos-net/compare/3e6119ae51ac1d457d98ef3719a483ab073d3d67...03975850c8240821a6dbe2e00750fb0fcc568e2a)
> [dcos/dcos-net#117](https://github.com/dcos/dcos-net/pull/118)
> https://circleci.com/gh/dcos/dcos-net/911
> https://codecov.io/github/dcos/dcos-net/commit/03975850c8240821a6dbe2e00750fb0fcc568e2a
___
**PLEASE FILL IN THE TEMPLATE …
> Add dcos-dns metrics registry to telegraf

- gen/dcos-config.yaml
When this flag is specified, if a task running as non-root user uses
a shared persistent volume or a PARENT type SANDBOX_PATH volume, the
volume will be owned by a gid allocated from this range and have the
`setgid` bit set, and the task process will be launched with the gid
as its supplementary group to make sure it can access the volume.
- [DCOS-45857](https://jira.mesosphere.com/browse/DCOS-45857) Enable the Mesos agent flag `--volume_gid_range` in DC/OS. …
> Turned on the mesos agent flag '--volume_gid_range'.

- gen/calc.py
All `gen` and `gen_extra` (Enterprise) validators which use `validate_int_in_range` and set the `high` parameter to `None` get the error message "'Must be above <MINIMUM_VALUE>" if the given value is too low. This is not the case - the given value must be above or equal to the minimum value.
- [DCOS_OSS-3739](https://jira.mesosphere.com/browse/DCOS_OSS-3739) `gen.calc.validate_int_in_range` error message says "Must be above", should be "Must be at least" …
> Fixes DCOS_OSS-3739 - Fix calc error message

- packages/dcos-check-runner/build
- packages/dcos-check-runner/extra/dcos-checks-api-agent.service
- packages/dcos-check-runner/extra/dcos-checks-api-master.service
- packages/dcos-diagnostics/extra/dcos-diagnostics-agent.service
- packages/dcos-diagnostics/extra/dcos-diagnostics-master.service
Changes the permission bootstrapping for checks to be handled by the check runner service rather than by diagnostics since these services have been split apart.
- [DCOS_OSS-3691](https://jira.mesosphere.com/browse/DCOS_OSS-3691)
___
* …
> Move checks permission bootstrapping to check-runner from diagnostics

- gen/dcos-config.yaml
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-integration-test/extra/test_metrics.py
Add metrics for dcos-diagnostics
- [DCOS_OSS-4876](https://jira.mesosphere.com/browse/DCOS_OSS-4876) Add metrics for dcos-diagnostics
___ …
> Bump dcos-diagnostics and wire prometheus metrics

- gen/aws/templates/cloudformation.json
- gen/build_deploy/aws.py
- gen/tests/test_installer_aws.py
* Remove the Availability Zone Pinning.
* Update EL7 AMIs.
* We are not including gov cloud region now.
> DCOS-18825 - Update CORE OS AMI used CloudFormation templates.

- CHANGES.md
- gen/calc.py
- packages/dcos-integration-test/extra/test_networking.py
We upgraded os images multiple times since we discovered kernel crashes on centos 7.4, I've tried to enable the test once again and it seems like it works fine at the moment. 
- [DCOS_OSS-1993](https://jira.mesosphere.com/browse/DCOS_OSS-1993) ipv6 docker containers reboot agent nodes on aws.
- [DCOS_OSS-2010](https://jira.mesosphere.com/browse/DCOS_OSS-2010) Create bug against RHEL 7 and CentOS 7 for kernel bug related to IPVS with IPv6.
___ …
> Enable ipv6 support for l4lb

- gen/dcos-config.yaml
- [DCOS-50311](https://jira.mesosphere.com/browse/DCOS-50311) Switch gid manager off on Mesos.
> Switched gid manager off on Mesos.

- packages/dcos-integration-test/extra/test_ucr.py
Disable the test for volume gid manager since volume gid manage has been switched off (see https://github.com/dcos/dcos/pull/4795)
- [DCOS-50408](https://jira.mesosphere.com/browse/DCOS-50408) Mute the test `test_if_ucr_pods_can_be_deployed_with_non_root_user_ephemeral_volume`
___ …
> Mute the test for volume gid manager.

- dcos_installer/test_backend.py
- gen/calc.py
* https://jira.mesosphere.com/browse/DCOS-49926
> DCOS-49926  - Updated version to 1.13.0-alpha.

- gen/calc.py
The ip_detect_script check calls the detect_ip script on the system and
validates the response. On AWS systems, this check makes a request to an
external AWS metadata endpoint. Occassionally this request takes longer
than 1s (current timeout).
This change fixes flaky tests that are failing due to detect_ip script taking longer than the 1s timeout. See the discussion on [this ticket](https://jira.mesosphere.com/browse/DCOS-50156)
- [DCOS-50156](https://jira.mesosphere.com/browse/DCOS-50156) …
> [1.11] Update ip_detect_script check to 30s

- gen/calc.py
The ip_detect_script check calls the detect_ip script on the system and
validates the response. On AWS systems, this check makes a request to an
external AWS metadata endpoint. Occassionally this request takes longer
than 1s (current timeout).
This change fixes flaky tests that are failing due to detect_ip script taking longer than the 1s timeout. See the discussion on [this ticket](https://jira.mesosphere.com/browse/DCOS-50156)
- [DCOS-50156](https://jira.mesosphere.com/browse/DCOS-50156) …
> Update ip_detect_script check to 30s

- gen/calc.py
The ip_detect_script check calls the detect_ip script on the system and
validates the response. On AWS systems, this check makes a request to an
external AWS metadata endpoint. Occassionally this request takes longer
than 1s (current timeout).
This change fixes flaky tests that are failing due to detect_ip script taking longer than the 1s timeout. See the discussion on [this ticket](https://jira.mesosphere.com/browse/DCOS-50156)
- [DCOS-50156](https://jira.mesosphere.com/browse/DCOS-50156) …
> [1.12] Update ip_detect_script check to 30s

- gen/calc.py
As discussed in [DCOS-50400](https://jira.mesosphere.com/browse/DCOS-50400) this increases the timeout for the check from `1s` to `30s` since it could potentially take longer.
- [[DCOS-50400] test_checks.test_checks_cli  failed with a dcos-checks exceeded timeout 1s - JIRA](https://jira.mesosphere.com/browse/DCOS-50400)
___ …
> DCOS-50400 - Increase mesos_agent_registered_with_masters timeout

- CHANGES.md
- packages/docker-gc/buildinfo.json
- packages/docker-gc/extra/dcos-docker-gc.service
* Updated docker-gc to the latest version to get the 'remove volumes' functionality
* Added envvar so that the 'remove volumes' function is on by default
- [DCOS_OSS-1502](https://jira.mesosphere.com/browse/DCOS_OSS-1502) dcos-docker-gc does not clean leftover volumes
___ …
> DCOS_OSS-1502 - dcos-docker-gc does not clean leftover volumes

- gen/calc.py
This is the backport of https://github.com/dcos/dcos/pull/4847
> [1.12] DCOS-50400 - Increase mesos_agent_registered_with_masters timeout

- packages/adminrouter/extra/src/docs/api/nginx.master.html
- packages/adminrouter/extra/src/docs/api/nginx.master.yaml
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/lib/auth/open.lua
This change passes path variable to the `access_dcos_ui_update_service_api_endpoint` handler to enable whitelisting the dcos-ui-update-service/api/v1/version endpoint for authenticated users who don't have the "dcos:adminrouter:ops:dcos-ui-update-service" permission.
- [DCOS-50170](https://jira.mesosphere.com/browse/DCOS-50170)
N/A
___
All PRs …
> DCOS-50170: whitelist ui update service version for unprivileged users

- CHANGES.md
- packages/docker-gc/extra/dcos-docker-gc.service
There's a bug in docker-gc that causes the systemd unit to fail
(https://github.com/spotify/docker-gc/issues/201)
- [DCOS_OSS-4952](https://jira.mesosphere.com/browse/DCOS_OSS-4952) dcos-docker-gc systemd unit is constantly unhealthy
___ …
> DCOS_OSS-4952 don't remove volumes per default

- packages/dcos-ui-update-service/build
- packages/dcos-ui-update-service/buildinfo.json
- packages/dcos-ui-update-service/extra/dcos-ui-update-service.service
Bumps dcos-ui-update service in order to removes ZK creds from logs by allowing alternative configuration of same via ENV and config file
- [DCOS-46083](https://jira.mesosphere.com/browse/DCOS-46083) Configure the ui-update service with a config file instead of CLI Flags
___ …
> chore: bump dcos-ui-update-service package

- gen/aws/templates/advanced/advanced-master.json
- gen/aws/templates/advanced/advanced-priv-agent.json
- gen/aws/templates/advanced/advanced-pub-agent.json
- gen/aws/templates/advanced/infra.json
- gen/aws/templates/advanced/zen.json
- gen/aws/templates/cloudformation.json
- gen/build_deploy/aws.py.orig
Backport of Update NAT AMIS to address CloudFormation Resource Errors #4890 
* https://jira.mesosphere.com/browse/DCOS-18825
> Update NAT AMIS to address CloudFormation Resource Errors

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
Enables the telegraf procstat plugin for all OS processes.
- [DCOS-50778](https://jira.mesosphere.com/browse/DCOS-50778) Enable `procstat` input plugin on telegraf nodes.
___
* …
> Enable procstat plugin for all OS processes.

- packages/dcos-ui-update-service/buildinfo.json
- [DCOS-46390](https://jira.mesosphere.com/browse/DCOS-46390)
- [DCOS-50422](https://jira.mesosphere.com/browse/DCOS-50422)
- [DCOS-50172](https://jira.mesosphere.com/browse/DCOS-50172)
___
**What is the review process and when …
> Bump dcos-ui-update-service package

- packages/adminrouter/extra/src/includes/server/open/agent.conf
- packages/adminrouter/extra/src/includes/server/open/master.conf
Fix double annotations.
- [DCOS_OSS-4945](https://jira.mesosphere.com/browse/DCOS_OSS-4945) Annotate all upstreams including original URI for Admin Router metrics.
> Remove double annotations

- packages/marathon/buildinfo.json
Improved Marathon stability and scalability
- [MARATHON-8596](https://jira.mesosphere.com/browse/MARATHON-8596) Introduced global throttling to Marathon health checks
- [MARATHON-8575](https://jira.mesosphere.com/browse/MARATHON-8575) Fixed a broken migration for app definitions with port mappings protocol "tcp,udp" which is no longer valid and should be "udp,tcp"
- [MARATHON-8566](https://jira.mesosphere.com/browse/MARATHON-8566) Fixed a rare bug where deployment was sometimes not immediately visible through the v2/deployments endpoint after creation
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY …
> Bump marathon to 1.5.14

- packages/dcos-integration-test/extra/test_networking.py
Muting test_vip_ipv6 due to DCOS-50427
- N/A.  Muting due to https://jira.mesosphere.com/browse/DCOS-50427
- https://jira.mesosphere.com/browse/DCOS-50427
___ …
> Muting test_vip_ipv6

- CHANGES.md
- gen/dcos-config.yaml
- [DCOS_OSS-4935](https://jira.mesosphere.com/browse/DCOS_OSS-4935) Configure metrics exporter for Metronome.
> Metronome configured to use Telegraf

- packages/dcos-checks/buildinfo.json
Bumps dcos-checks
- [DCOS-50756](https://jira.mesosphere.com/browse/DCOS-50756)
___
It is …
> Bump dcos-checks

- CHANGES.md
- packages/openssl/buildinfo.json
- https://jira.mesosphere.com/browse/DCOS_OSS-4868
> openssl: bump to 1.0.2r release [1.11]

- packages/adminrouter/extra/src/includes/metrics-service-location-level.conf
- packages/adminrouter/extra/src/includes/metrics-upstream-location-level.conf
- packages/adminrouter/extra/src/includes/server/master.conf
- packages/adminrouter/extra/src/lib/service.lua
- packages/adminrouter/extra/src/test-harness/tests/open/test_metrics.py
This PR provides annotation for metrics for services accessible under /service/... location via Admin Router.
https://jira.mesosphere.com/browse/DCOS_OSS-4950
> Annotate metrics for /service/... upstream location

- packages/marathon/buildinfo.json
- [DCOS_OSS-4997](https://jira.mesosphere.com/browse/DCOS_OSS-4997) Fix restarting unhealthy instances.
- [MARATHON-8607](https://jira.mesosphere.com/browse/MARATHON-8607) Abandon reservation for resident task in response to TASK_GONE_BY_OPERATOR.
- [MARATHON-8611](https://jira.mesosphere.com/browse/MARATHON-8611) Do not forceexpunge when timeout is hit.
- `save_tasks_to_launch_timeout` option was removed
___ …
> Bump marathon to 1.8.172

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Add sysctl to diagnostics bundle
- [DCOS_OSS-4845](https://jira.mesosphere.com/browse/DCOS_OSS-4845)
___ …
> Add sysctl to diagnostics bundle

- packages/dcos-diagnostics/build
- packages/dcos-diagnostics/buildinfo.json
* Switch to Go Modules
* Improve speed of `make test`
- [DCOS_OSS-4984](https://jira.mesosphere.com/browse/DCOS_OSS-4984) Switch to Go Modules
- [DCOS_OSS-5007](https://jira.mesosphere.com/browse/DCOS_OSS-5007) Improve speed of `make test`
___ …
> Bump dcos-diagnostics and adapt build

- packages/mesos-modules/buildinfo.json
- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
In preparation for the upcoming 1.13 release of DC/OS,
update the Mesos package to track the Mesos 1.8 release
branch which will be the version included in the release.
- [DCOS-51386](https://jira.mesosphere.com/browse/DCOS-51386) Update DC/OS to track the Mesos 1.8 release branch
___ …
> Update DC/OS to track Mesos 1.8.x release branch.

- packages/dcos-signal/buildinfo.json
Bump dcos-signal
- [DCOS-50795](https://jira.mesosphere.com/browse/DCOS-50795)
___
* …
> Bump dcos-signal

- packages/marathon/buildinfo.json
Bugfixing and stability.
- [DCOS_OSS-4997](https://jira.mesosphere.com/browse/DCOS_OSS-4997) Fix a bug where an unhealthy service instance was not restarted
___
It is best to …
> Bump Marathon to 1.5.15

- packages/cosmos/buildinfo.json
- [DCOS-49256](https://jira.mesosphere.com/browse/DCOS-49256) Retry on ALL upstream exceptions in cosmos (even 4xx's). Also addresses [DCOS-51139](https://jira.mesosphere.com/browse/DCOS-51139)
- [DCOS-49941](https://jira.mesosphere.com/browse/DCOS-49941) dcos-jenkins does not update constraints in marathon
- [DCOS_OSS-5013](https://jira.mesosphere.com/browse/DCOS_OSS-5013) Remove zip based universe metrics from cosmos code.
If you are changing components or packages in DC/OS (e.g. you …
> Bump cosmos to latest snapshot

- packages/dcos-integration-test/extra/test_metrics.py
This PR addresses @adamtheturtle's post-merge comment on the related PR: https://github.com/dcos/dcos/pull/5023#pullrequestreview-224116155
to minimize the chances of potentially introducing flakiness with already merged change
https://jira.mesosphere.com/browse/DCOS_OSS-5014
> Fix integration test for Telegraf metrics

- packages/metronome/buildinfo.json
Added missing HTTP metrics for Metronome.
- [DCOS_OSS-5020](https://jira.mesosphere.com/browse/DCOS_OSS-5020) Add missing HTTP metrics in Metronome.
___ …
> Bump metronome on DC/OS 1.13

- CHANGES.md
- packages/marathon/buildinfo.json
- [DCOS-50599](https://jira.mesosphere.com/browse/DCOS-50599) Marathon Support seccomp
- [DCOS-50607](https://jira.mesosphere.com/browse/DCOS-50607) Marathon seccomp Proto and Conversion Implementation
- [DCOS-50608](https://jira.mesosphere.com/browse/DCOS-50608) Marathon Seccomp TaskBuilder / TaskGroupBuilder Impl
> bumping Marathon 1.8.180 for seccomp

- packages/cosmos/buildinfo.json
Backport of #5039 
- [DCOS-49256](https://jira.mesosphere.com/browse/DCOS-49256) Retry on ALL upstream exceptions in cosmos (even 4xx's). Also addresses [DCOS-51139](https://jira.mesosphere.com/browse/DCOS-51139) and [DCOS-46435](https://jira.mesosphere.com/browse/DCOS-46435)
- [DCOS-49941](https://jira.mesosphere.com/browse/DCOS-49941) dcos-jenkins does not update constraints in marathon
- [DCOS_OSS-5013](https://jira.mesosphere.com/browse/DCOS_OSS-5013) Remove zip based universe metrics from cosmos code.
If you are changing components or packages in DC/OS …
> [1.12] Bump cosmos to latest version

- CHANGES.md
- packages/dcos-diagnostics/buildinfo.json
* support for optional HTTP endpoints
- [DCOS_OSS-5031](https://jira.mesosphere.com/browse/DCOS_OSS-5031) DC/OS Diagnostics: HTTP endpoint targets can be marked optional.
- [DCOS-51618](https://jira.mesosphere.com/browse/DCOS-51618) DC/OS Diagnostics should include output of DSS /diagnostics endpoint.
___ …
> dcos-diagnostics: bump to 84f0d569

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
* Update DC/OS Version to 1.13.0-beta
> Update version to 1.13.0-beta

- CHANGES.md
- mergebot-config.json
* DCOS-51706  - Update Mergebot Config for Master
> Update Mergebot Config for Master.

- owners.json
> Added vinodkone to owners.json.

- CHANGES.md
- gen/calc.py
The configuration variables `aws_secret_access_key` and `exhibitor_azure_account_key` (https://docs.mesosphere.com/1.11/installing/production/advanced-configuration/configuration-reference/#exhibitor-storage-backend) must be marked as secret so that they are not accidentally revealed by diagnostics tools.
- [DCOS-51751](https://jira.mesosphere.com/browse/DCOS-51751) aws_secret_access_key is not hidden in diagnostics bundle …
> Hide secret keys from user.config.yaml

- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
- packages/mesos/extra/patches/0004-Added-received-timestamp-into-process-Request.patch
- packages/mesos/extra/patches/0005-Added-task-health-check-definitions-to-master-API-re.patch
- packages/mesos/extra/patches/0006-Introduced-logResponse-for-http-handlers.patch
- packages/mesos/extra/patches/0007-Logged-request-processing-time-for-some-endpoints.patch
- packages/mesos/extra/patches/0008-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch
- packages/mesos/extra/patches/0009-Added-HEARTBEAT-events-and-calls-for-the-executor-HT.patch
- packages/mesos/extra/patches/0010-Refactored-master-and-agent-streaming-connections.patch
- packages/mesos/extra/patches/0011-Added-heartbeaters-for-agent-and-HTTP-executors.patch
- packages/mesos/extra/patches/0012-Added-tests-for-agent-executor-heartbeating.patch
- packages/mesos/extra/patches/0013-Changed-master-to-hold-subscribers-in-a-circular-buf.patch
- packages/mesos/extra/patches/0014-Added-gauge-metric-for-operator-event-stream-subscri.patch
- packages/mesos/extra/patches/0015-Reverted-the-container-sandbox-permission-from-0750-.patch
- packages/mesos/extra/patches/0016-Special-cased-HEARTBEAT-call-handling-in-agent.patch
The agent was not properly special-casing HEARTBEAT calls from executors.  This led to logs showing up in the executor's output, like the following:
```
E ... default_executor.cpp:294] Error: Received unexpected '400 Bad Request' (Framework cannot be found) for HEARTBEAT 
```
As an error level log, the message looks more threatening than it actually is.   The error has no adverse effects on the task or agent and can be safely silenced.
This PR is separated into two commits for readability.  The first commit re-applies all existing patches, which results in a little churn because these patches are rebased onto Mesos 1.7.x.  The second commit adds the new patch.
These DC/OS JIRA ticket(s) must be updated (ideally closed) …
> [1.12] Add patch to silence an error message from executor heartbeats.

- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_networking.py
Moving to updated distro and lighter weight image for tests
- https://jira.mesosphere.com/browse/DCOS-50035
___ …
> [BACKPORT][DCOS-50035] lighter weight image and updated distro for tests

- packages/dcos-integration-test/extra/test_applications.py
- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_networking.py
Moving to updated distro and lighter weight image for tests
- https://jira.mesosphere.com/browse/DCOS-50035
___ …
> [BACKPORT][DCOS-50035] Moving to smaller image and updated distro for tests

- CHANGES.md
- docs/admin-ports.md
- gen/build_deploy/bash.py
- gen/dcos-config.yaml
- packages/fluent-bit/build
Backport of #5133
- [DCOS-51855](https://jira.mesosphere.com/browse/DCOS-51855) Build fluent bit with metrics support
> [1.13] Enable fluent bit metrics

- CHANGES.md
- packages/docker-gc/buildinfo.json
- packages/docker-gc/extra/dcos-docker-gc.service
* Enable removal of volumes using env var
* Switch to mesosphere/docker-gc fork that actually works
- [DCOS_OSS-1502](https://jira.mesosphere.com/browse/DCOS_OSS-1502) dcos-docker-gc does not clean leftover volumes
___
**What is …
> [1.13] dcos-docker-gc does not clean leftover volumes

- CHANGES.md
- packages/marathon/buildinfo.json
Bump Marathon to 1.7.216
[MARATHON-8596](https://jira.mesosphere.com/browse/MARATHON-8596) Introduced global throttling for Marathon health checks
[MARATHON-8590](https://jira.mesosphere.com/browse/MARATHON-8590) Do not fail on offers with RAW and BLOCK disk types
[MARATHON-8575](https://jira.mesosphere.com/browse/MARATHON-8575) Map `tcp,udp` to `udp,tcp` during migration
[MARATHON-8581](https://jira.mesosphere.com/browse/MARATHON-8581) Allow all users to execute /marathon/bin/marathon
[MARATHON-8562](https://jira.mesosphere.com/browse/MARATHON-8562) Response asynchronously for all endpoints
[DCOS-49521](https://jira.mesosphere.com/browse/DCOS-49521) Force expunge and Decommission all instances on …
> Bump Marathon to 1.7.216

- packages/dcos-ui/buildinfo.json
DCOS-50836
___
* Developers responsible for code that interacts with or …
> [1.13] Automated Bump DC/OS UI v2.82.0

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
* Created DC/OS branch 1.13.0 
* Updated DC/OS Version to 1.13.0
> Updated DC/OS version to 1.13.0

- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-signal/buildinfo.json
- packages/dcos-signal/extra/dcos-signal.service
This adds a license_id to all segment tracks from signal.
[DCOS-50809](https://jira.mesosphere.com/browse/DCOS-50809)
N/A
___
It is best to proactively ask for 2 reviews by …
> [1.13] DCOS-50809 - Add LicenseID to Signal

- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-signal/buildinfo.json
- packages/dcos-signal/extra/dcos-signal.service
This adds a license_id to all segment tracks from signal.
[DCOS-50809](https://jira.mesosphere.com/browse/DCOS-50809)
N/A
___
It is best to proactively ask for 2 reviews by …
> [master] DCOS-50809 - Add LicenseID to Signal

- gen/aws/templates/cloudformation.json
* DCOS-51332 - NatInstance to reference Default Instance Type
> NatInstance to reference Default InstanceType.

- gen/aws/templates/cloudformation.json
* DCOS-51332 - NatInstance to reference Default Instance Type
> DCOS-51332 - NatInstance to reference Default InstanceType.

- packages/dcos-test-utils/buildinfo.json
https://jira.mesosphere.com/browse/DCOS-51877
> Bump dcos-test-utils to pin dcos cli

- gen/aws/templates/cloudformation.json
* DCOS-51332 - NatInstance to reference Default Instance Type
> DCOS-51332 - NatInstance to reference Default Instance Type

- CHANGES.md
- packages/dcos-net/buildinfo.json
Bump dcos-net
- [DCOS_OSS-5080](https://jira.mesosphere.com/browse/DCOS_OSS-5080) ipset mgr crash looping on kernel with ipset ver. 7
https://github.com/dcos/dcos-net/compare/d660500895765c9f966a997ec66779677cc5477b...3653b56643f2578c68dfd39f61a557cc14aff51e
https://github.com/dcos/dcos-net/pull/142
https://github.com/dcos/dcos-net/pull/144
https://circleci.com/gh/dcos/dcos-net/1111
https://codecov.io/github/dcos/dcos-net/commit/3653b56643f2578c68dfd39f61a557cc14aff51e
___
**PLEASE FILL IN …
> [1.13] Bump dcos-net

- dcos_installer/action_lib.py
- dcos_installer/cli.py
Adds deprecation notices to some installer options
- [DCOS-50264](https://jira.mesosphere.com/browse/DCOS-50264)
- [DCOS-50263](https://jira.mesosphere.com/browse/DCOS-50263)
___
* …
> Add deprecation notices to installer CLI

- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
Switches the repository source branch of Apache Mesos from `1.8.x` to `master`.  
[DCOS-51898](https://jira.mesosphere.com/browse/DCOS-51898) - Bump DCOS master to Mesos master.
___ …
> Switched Mesos to current master.

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Backports: #5054 
---
Bump dcos-diagnostics to allow optional commands in dcos-diagnostics and configure number of diagnostics fetchers.
It's not a user facing change. It's just change how w handle optional commands in dcos diagnostics config and how we report errors.
- [DCOS_OSS-5026
](https://jira.mesosphere.com/browse/DCOS_OSS-5026)
- [DCOS-51483](https://jira.mesosphere.com/browse/DCOS-51483) …
> [1.13] Allow optional commands in dcos-diagnostics

- CHANGES.md
- packages/dcos-net/buildinfo.json
Bump dcos-net
- [DCOS_OSS-5108](https://jira.mesosphere.com/browse/DCOS_OSS-5108) CNAME records should appear before A/AAAA records
- [DCOS_OSS-5080](https://jira.mesosphere.com/browse/DCOS_OSS-5080) ipset mgr crash looping on kernel with ipset ver. 7
https://github.com/dcos/dcos-net/compare/d660500895765c9f966a997ec66779677cc5477b...3485521f64167be55bd8730ad8c5486db8f345fc
https://github.com/dcos/dcos-net/pull/142
https://github.com/dcos/dcos-net/pull/144 …
> [1.13.0] Bump dcos-net

- packages/adminrouter/extra/src/includes/server/master.conf
- packages/dcos-integration-test/extra/test_adminrouter_open.py
The UI configuration in Admin Router was modified in #5140. This was back-ported to 1.13 in #5281 with some additional changes based on further discussion. This PR forward-ports those additional changes back into `master` to keep the configurations aligned.
- [DCOS-5978](https://jira.mesosphere.com/browse/DCOS-5978) Admin Router: enable gzip compression for relevant MIME types
___ …
> Update cache headers to more appropriate values

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Use `docker ps` instead `docker up` in diagnostics bundle.
- [DCOS_OSS-5105](https://jira.mesosphere.com/browse/DCOS_OSS-5105) Use `docker ps` instead `docker up` in diagnostics bundle.
___ …
> Use `docker ps` instead of `docker up` in diagnostics

- CHANGES.md
- packages/dcos-diagnostics/buildinfo.json
* Added timeout to systemd log reading; fixed `verbose` flag
* Add bundle creation time gauge for Prometheus
* Allow optional commands
* Make number of fetchers configurable
* Read providers configuration from multiple files
- [DCOS_OSS-5097](https://jira.mesosphere.com/browse/DCOS_OSS-5097) Added timeout to systemd log reading; fixed `verbose` flag
- [DCOS_OSS-4962](https://jira.mesosphere.com/browse/DCOS_OSS-4962) Add bundle creation time gauge for Prometheus
- [DCOS_OSS-5026](https://jira.mesosphere.com/browse/DCOS_OSS-5026) Allow optional commands
- [DCOS_OSS-4964](https://jira.mesosphere.com/browse/DCOS_OSS-4964) Make number …
> [1.13] Bump dcos-diagnostics

- gen/fault-domain-detect/cloud.sh
Backport of DCOS-51792
- [DCOS-51792](https://jira.mesosphere.com/browse/DCOS-51792)
___ …
> Fix syntax error in domain detect script

- CHANGES.md
Those changes are not in 1.13.0 but in 1.13.1.
- [DCOS_OSS-5097](https://jira.mesosphere.com/browse/DCOS_OSS-5097) Add timeouts and retries in dcos-diagnostics
___
All …
> Fixed changelog entry for dcos-diagnostics changes

- CHANGES.md
This is an editorial update for CHANGES.md.
Part of the 2019 changelog initiative.
> CHANGES.md: editorial update for 1.13.1 development

- CHANGES.md
This is an editorial update for CHANGES.md.
Part of the 2019 changelog initiative.
> CHANGES.md: editorial update for 1.12 development

- CHANGES.md
This is an editorial update for CHANGES.md.
Part of the 2019 changelog initiative.
> CHANGES.md: editorial update for 1.10 branch

- CHANGES.md
See https://github.com/dcos/dcos/pull/5368
> CHANGES.md: another editorial overhaul for 1.10

- gen/aws/templates/cloudformation.json
Enabling AWS ELB features for Edge-LB CI
- https://jira.mesosphere.com/browse/DCOS-51350
___ …
> DCOS-51350 - adding ELB permissions to cloudformation templates

- packages/dcos-integration-test/extra/test_networking.py
- [DCOS-50427](https://jira.mesosphere.com/browse/DCOS-50427) test_networking.test_vip_ipv6 fails on an unrelated change
- [DCOS_OSS-5119](https://jira.mesosphere.com/browse/DCOS_OSS-5119) test_vip_port_mapping is very slow
___ …
> Fixes and improvements to networking integration tests

- gen/aws/templates/cloudformation.json
Adding ELB permissions to Cloudformation template for Edge-LB
- https://jira.mesosphere.com/browse/DCOS-51350
___ …
> [BACKPORT][1.11][DCOS-51350] - add ELB permissions to CF template

- gen/aws/templates/cloudformation.json
Adding ELB permissions to CloudFormation template for Edge-LB
- https://jira.mesosphere.com/browse/DCOS-51350
___ …
> [BACKPORT][1.13][DCOS-51350] - add ELB permissions to CF template

- gen/aws/templates/cloudformation.json
Adding ELB permissions to Cloudformation template for Edge-LB
- https://jira.mesosphere.com/browse/DCOS-51350
___ …
> [BACKPORT][1.10][DCOS-51350] - add ELB permissions to CF template

- CHANGES.md
- packages/python-requests/buildinfo.json
- setup.py
Updating urllib3 version fo security update
- https://jira.mesosphere.com/browse/DCOS-52210
___ …
> Bumping urllib3 version due to security vulnerability

- packages/dcos-integration-test/extra/test_networking.py
- [DCOS-50427](https://jira.mesosphere.com/browse/DCOS-50427) test_networking.test_vip_ipv6 fails on an unrelated change
- [DCOS_OSS-5119](https://jira.mesosphere.com/browse/DCOS_OSS-5119) test_vip_port_mapping is very slow
___ …
> [1.13] Fixes and improvements to networking integration tests

- owners.json
> fixes github account in owners.json

- owners.json
> fixes github account name in owners.json

- CHANGES.md
This is a major `CHANGES.md` content overhaul for the 1.13 branch, in alignment with the 2019 changelog initiative.
> [1.13] CHANGES.md editorial update

- CHANGES.md
- packages/dvdcli/buildinfo.json
- packages/exhibitor/buildinfo.json
Updating dvdcli and zookeeper versions / refs to get uncached builds passing in CI
- https://jira.mesosphere.com/browse/DCOS-52091
___
* …
> DCOS-52091 - Fix uncached builds for 1.11

- CHANGES.md
- packages/dvdcli/buildinfo.json
- packages/exhibitor/buildinfo.json
Updating dvdcli ref to get uncached builds passing
- https://jira.mesosphere.com/browse/DCOS-52092
___ …
> Updating ref for dvdcli to get test passing

- packages/dcos-ui/buildinfo.json
> chore: Bump DC/OS UI v2.82.1

- packages/dcos-integration-test/extra/test_mesos.py
Disable the test `test_mesos.test_blkio_stats tests` on Azure since the Linux VM created on Azure does not have the blkio cgroups files needed by `cgroups/blkio` isolator in Mesos.
- [DCOS-49023](https://jira.mesosphere.com/browse/DCOS-49023) test_mesos.test_blkio_stats tests fails on KeyError for teamcity/dcos/test/azure/arm
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE …
> Do not run blkio test on Azure env

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
This PR backports https://github.com/dcos/dcos/pull/5344
* DCOS-52191 - Mute flaky test test_dcos_diagnostics_bundle_create_download_delete
> DCOS-52191 - Mute flaky test test_dcos_diagnostics_bundle

- packages/dcos-integration-test/extra/test_composition.py
- packages/dcos-signal/build
- packages/dcos-signal/buildinfo.json
- packages/dcos-signal/extra/dcos-signal.service
- pkgpanda/docker/dcos-builder/Dockerfile
This adds a license_id to all segment tracks from signal.
[DCOS-50809](https://jira.mesosphere.com/browse/DCOS-50809)
N/A
___
It is best to proactively ask for 2 reviews by …
> [1.11] DCOS-50809 - Add LicenseID to Signal

- packages/mesos-dns/buildinfo.json
Proper release of mesos-dns for DC/OS (fixes the reported version).
- [DCOS_OSS-5151](https://jira.mesosphere.com/browse/DCOS_OSS-5151) mesos-dns reports version "dev" instead of "1.13".
___
All PRs require 2 approvals using GitHub's …
> mesos-dns: bump to official 1.13 tag

- packages/mesos-dns/buildinfo.json
Proper release of mesos-dns for DC/OS (fixes the reported version).
* cherry picked from commit 9485f09f78f0735bd1cf8ca5e9c81fb1425582dd, see #5470 
- [DCOS_OSS-5151](https://jira.mesosphere.com/browse/DCOS_OSS-5151) mesos-dns reports version "dev" instead of "1.13".
___
**What is the review process …
> [1.13] mesos-dns: bump to official 1.13 tag

- dcos_installer/test_backend.py
- gen/calc.py
- packages/dcos-test-utils/buildinfo.json
* DCOS-53681 - Update DC/OS Version in master branch to 1.14-dev
> Update DC/OS master version to 1.14-dev

- dcos_installer/test_backend.py
- gen/calc.py
* https://jira.mesosphere.com/browse/DCOS-53938 - Set UI versions consistently across all in-development branches
> Update 1.13 version in UI to 1.13.1-dev

- packages/dcos-diagnostics/build
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- pkgpanda/docker/dcos-builder/Dockerfile
Backports: #5054 
---
Bump dcos-diagnostics to allow optional commands in dcos-diagnostics and configure number of diagnostics fetchers.
It's not a user facing change. It's just change how w handle optional commands in dcos diagnostics config and how we report errors.
- [DCOS_OSS-5026
](https://jira.mesosphere.com/browse/DCOS_OSS-5026)
- [DCOS-51483](https://jira.mesosphere.com/browse/DCOS-51483)
- [DCOS-5104](https://jira.mesosphere.com/browse/DCOS-5104) …
> [1.12] Allow optional commands in dcos-diagnostics

- dcos_installer/test_backend.py
- gen/calc.py
* Update the master version of DC/OS to 1.14.0-dev
- [DCOS-53938](https://jira.mesosphere.com/browse/DCOS-53938) Set UI versions consistently across all in-development branches
> Update master version of DC/OS to 1.14.0-dev

- PULL_REQUEST_TEMPLATE.md
https://jira.mesosphere.com/browse/DCOS-42490 - Update Mergebot to parse *directly associated* JIRA tickets from PR description, and to update them in a special way
* PULL_REQUEST_TEMPLATE maintenance.
* Clean up instructions.
* Provide Instructions in comments.
* Add a comment to Related tickets (Optional) section, this section will be excluded in the mergebot parsing.
> DCOS-42490 - PULL_REQUEST_TEMPLATE maintenance.

- packages/dcos-net/buildinfo.json
- packages/erlang/buildinfo.json
- packages/libsodium/buildinfo.json
Upgrade OTP version
- [DCOS_OSS-5164](https://jira.mesosphere.com/browse/DCOS_OSS-5164) Upgrade OTP version
https://github.com/erlang/otp/compare/295b1b0914f1f9828471d6851b00ad3133174c20...cbd793d6c9f9e4e159ca444290d46f6515e4383e
https://github.com/dcos/dcos-net/compare/295b1b0914f1f9828471d6851b00ad3133174c20...c03517e1039cf680938597d66aec20c9ab5d15d4
https://github.com/dcos/dcos-net/pull/152
https://circleci.com/gh/dcos/dcos-net/1186 …
> Upgrade OTP version to 22.0

- CHANGES.md
This is just the changelog for #5524
- [DCOS_OSS-5152](https://jira.mesosphere.com/browse/DCOS_OSS-5152) Modify dcos-installer not to warn on missing optional ssh_* keys in dcos-config.yml
> [1.12] Added changelog entry for DCOS_OSS_5152

- CHANGES.md
This is just the changelog for #5523 
- [DCOS_OSS-5152](https://jira.mesosphere.com/browse/DCOS_OSS-5152) Modify dcos-installer not to warn on missing optional ssh_* keys in dcos-config.yml
> [1.13] Added changelog entry for DCOS_OSS_5152

- CHANGES.md
This is just the changelog for #5525
- [DCOS_OSS-5152](https://jira.mesosphere.com/browse/DCOS_OSS-5152) Modify dcos-installer not to warn on missing optional ssh_* keys in dcos-config.yml
> [1.11] Added changelog entry for DCOS_OSS_5152

- dcos_installer/test_backend.py
- gen/calc.py
* Set UI version for 1.12 development branch.
* DCOS-53938 - Set UI versions consistently across all in-development branches.
> Set UI version for 1.12 development branch.

- packages/dcos-net/extra/gen_resolvconf.py
The bug was caused by a race condition that resulted in an empty
resolv.conf that has been picked up by DC/OS Diagnostics and then
Diagnostics was not able to resolve any hostname.
This bug only appears in Docker enviroments (i.e. dcos-e2e) causing
flaky tests.
- [DCOS-47608](https://jira.mesosphere.com/browse/DCOS-47608) Error executing DC/OS components health check: unable to create HTTP client: dial tcp: lookup master.mesos on [::1]:53: dial udp [::1]:53: connect: network is unreachable …
> DCOS-47608 fix race condition when rewriting resolv.conf

- packages/dcos-net/extra/gen_resolvconf.py
The bug was caused by a race condition that resulted in an empty
resolv.conf that has been picked up by DC/OS Diagnostics and then
Diagnostics was not able to resolve any hostname.
This bug only appears in Docker enviroments (i.e. dcos-e2e) causing
flaky tests.
- [DCOS-47608](https://jira.mesosphere.com/browse/DCOS-47608) Error executing DC/OS components health check: unable to create HTTP client: dial tcp: lookup master.mesos on [::1]:53: dial udp [::1]:53: connect: network is unreachable …
> [1.12] DCOS-47608 fix race condition when rewriting resolv.conf

- packages/dcos-net/extra/gen_resolvconf.py
The bug was caused by a race condition that resulted in an empty
resolv.conf that has been picked up by DC/OS Diagnostics and then
Diagnostics was not able to resolve any hostname.
This bug only appears in Docker enviroments (i.e. dcos-e2e) causing
flaky tests.
- [DCOS-47608](https://jira.mesosphere.com/browse/DCOS-47608) Error executing DC/OS components health check: unable to create HTTP client: dial tcp: lookup master.mesos on [::1]:53: dial udp [::1]:53: connect: network is unreachable …
> [1.11] DCOS-47608 fix race condition when rewriting resolv.conf

- packages/dcos-net/extra/gen_resolvconf.py
The bug was caused by a race condition that resulted in an empty
resolv.conf that has been picked up by DC/OS Diagnostics and then
Diagnostics was not able to resolve any hostname.
This bug only appears in Docker enviroments (i.e. dcos-e2e) causing
flaky tests.
- [DCOS-47608](https://jira.mesosphere.com/browse/DCOS-47608) Error executing DC/OS components health check: unable to create HTTP client: dial tcp: lookup master.mesos on [::1]:53: dial udp [::1]:53: connect: network is unreachable …
> [1.13] DCOS-47608 fix race condition when rewriting resolv.conf

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
DC/OS UI Version update.
* DCOS-54311  - Update DC/OS 1.11 UI to 1.11.12-dev, and update the DC/OS 1.11.12 Changes.md header
> DCOS-54311  - Update DC/OS 1.11 UI to 1.11.12-dev, and update the DC/OS 1.11.12 Changes.md header

- packages/dcos-integration-test/extra/test_mesos.py
This test was introduced to test the correct behavior of a custom
setting for Mesos' `min_allocatable_resources` flag. We have since
removed this custom flag setting which both caused this test to fail
while also removing any need for this test, so we are removing the test
in this patch.
> Remove unneeded `test_min_allocatable_resources`

- PULL_REQUEST_TEMPLATE.md
* DCOS-42490 - Pull Request Template maintenance.
* Address review comments from https://github.com/dcos/dcos/pull/5541 
* Address Formatting issues that were visible after the previous PR was merged.
> DCOS-42490 - Pull Request Template maintenance.

- packages/dcos-integration-test/extra/test_mesos.py
This test was introduced to test the correct behavior of a custom
setting for Mesos' `min_allocatable_resources` flag. We have since
removed this custom flag setting which both caused this test to fail
while also removing any need for this test, so we are removing the test
in this patch.
> bbannier/dcos 53469 1.13

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_mesos.py
- [DCOS-49202](https://jira.mesosphere.com/browse/DCOS-49202) Remove "|disk:32" from the min_allocatable_resources flag.
> Remove "|disk:32" from the min_allocatable_resources flag

- packages/bouncer/extra/dcos-bouncer.service
Ensure Bouncer uses configured proxy. Using Auth0 from behind a web proxy does not work due tothe lack of this setting.
- [DCOS_OSS-5167](https://jira.mesosphere.com/browse/DCOS_OSS-5167) Bouncer does not use proxy to access external sites
We do not have a suitable test environment for testing proxy setups. See the JIRA issue for confirmation from a user that this fix works.
> [master] Ensure Bouncer uses configured proxy

- CHANGES.md
- packages/bouncer/extra/dcos-bouncer.service
Ensure Bouncer uses configured proxy. Using Auth0 from behind a web proxy does not work due tothe lack of this setting.
- [DCOS_OSS-5167](https://jira.mesosphere.com/browse/DCOS_OSS-5167) Bouncer does not use proxy to access external sites
We do not have a suitable test environment for testing proxy setups. See the JIRA issue for confirmation from a user that this fix works.
> [1.13] Ensure Bouncer uses configured proxy

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Do not fail when there are more than 2 frameworks installed.
- [DCOS-54487](https://jira.mesosphere.com/browse/DCOS-54487) 
> Check if we see at least 2 frameworks

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
We use to have only two frameworks: Marathon and Metronome so we only need to check if we can see their tasks in the bundle. Now we have 9 frameworks so we need to sum all the tasks we have.
- [DCOS-54487](https://jira.mesosphere.com/browse/DCOS-54487) 
> Sum all tasks from all frameworks in diag test

- mergebot-config.json
Mergebot is getting updates for **bump-ee** command and a new **request-review** command, both of which require changes to mergebot configs. Introducing said changes.
> Mergebot configs changes for upcoming mergebot updates

- mergebot-config.json
DCOS-53580 - Introduce a command changelog-not-required to override changes.md status check requirement.
> Introduce changelog-not-required command.

- CHANGES.md
- gen/dcos-config.yaml
This is a 1.13 backport of #5632.
I tested this manually by installing dcos-monitoring and querying Prometheus to confirm that procstat metrics are present for all components.
- [DCOS-53589](https://jira.mesosphere.com/browse/DCOS-53589) Whitelist the processes to monitor when using the procstat input plugin
N/A
> (1.13) Collect procstat metrics only for components

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
This PR configures telegraf to gather metrics from Fluent Bit
- [DCOS-54425](https://jira.mesosphere.com/browse/DCOS-54425) Configure Telegraf to gather metrics from Fluent Bit
> Gather metrics from Fluent Bit

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
This PR configures telegraf to gather metrics from Fluent Bit
- [DCOS-54425](https://jira.mesosphere.com/browse/DCOS-54425) Configure Telegraf to gather metrics from Fluent Bit
> [1.13] Gather metrics from Fluent Bit

- CHANGES.md
- packages/mesos-modules/buildinfo.json
This is a 1.13 backport of #5503. This bumps mesos-modules to include https://github.com/dcos/dcos-mesos-modules/pull/111.
- [DCOS-53834](https://jira.mesosphere.com/browse/DCOS-53834) Integrate Mesos task log module fix with DC/OS
N/A
> (1.13) Include task metadata with task logs sent to Fluent Bit

- packages/cosmos/buildinfo.json
Backport of #5657
- [DCOS-54077](https://jira.mesosphere.com/browse/DCOS-54077) cosmos: fetching enterprise cli fails with 400 response
- [DCOS-44111](https://jira.mesosphere.com/browse/DCOS-44111) Cosmos behaviour changed from 1.11 to 1.12 when running describe
> [1.13] Bump cosmos to latest version

- packages/marathon/buildinfo.json
- [DCOS-54927](https://jira.mesosphere.com/browse/DCOS-54927) - Fixed an issue where two independent deployments could interfere with each other resulting in too many tasks launched and/or possibly a stuck deployment.
> Bumped Marathon to 1.8.204-5209e3183

- packages/marathon/buildinfo.json
- [DCOS-54927](https://jira.mesosphere.com/browse/DCOS-54927) - Fixed an issue where two independent deployments could interfere with each other resulting in too many tasks launched and/or possibly a stuck deployment.
> Bump Marathon to 1.8.204-5209e3183

- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_service_discovery.py
Fix test_dcos_cni_l4lb integration test
Bugs:
* Client task has a VIP label, the same as server task's VIP label
* The test checks only connectivity, but not correctness of the output
* It must kill all the tasks, but it keeps them running
Improvements:
* Let's use `MarathonApp` class everywhere
* Run tasks on random ports
* Use human-readable task names
* Make logging sane
* Enable test_service_discovery_docker_bridged_network test
> [1.13] Fix test_dcos_cni_l4lb integration test

- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_service_discovery.py
Fix test_dcos_cni_l4lb integration test
Bugs:
* Client task has a VIP label, the same as server task's VIP label
* The test checks only connectivity, but not correctness of the output
* It must kill all the tasks, but it keeps them running
Improvements:
* Let's use `MarathonApp` class everywhere
* Run tasks on random ports
* Use human-readable task names
* Make logging sane
* Enable test_service_discovery_docker_bridged_network test
> Fix test_dcos_cni_l4lb integration test

- packages/dcos-integration-test/extra/test_networking.py
Fix test_dcos_cni_l4lb integration test
Bugs:
* Client task has a VIP label, the same as server task's VIP label
* The test checks only connectivity, but not correctness of the output
* It must kill all the tasks, but it keeps them running
Improvements:
* Let's use `MarathonApp` class everywhere
* Run tasks on random ports
* Use human-readable task names
* Make logging sane
> [1.11] Fix test_dcos_cni_l4lb integration test

- packages/dcos-integration-test/extra/test_networking.py
- packages/dcos-integration-test/extra/test_service_discovery.py
Fix test_dcos_cni_l4lb integration test
Bugs:
* Client task has a VIP label, the same as server task's VIP label
* The test checks only connectivity, but not correctness of the output
* It must kill all the tasks, but it keeps them running
Improvements:
* Let's use `MarathonApp` class everywhere
* Run tasks on random ports
* Use human-readable task names
* Make logging sane
* Enable test_service_discovery_docker_bridged_network test
> [1.12] Fix test_dcos_cni_l4lb integration test

- packages/metronome/buildinfo.json
Bump Metronome to 0.6.27
- [DCOS_OSS-5019](https://jira.mesosphere.com/browse/DCOS_OSS-5019) Improve secrets validation to only point out unprovided secrets.
- [DCOS-54879](https://jira.mesosphere.com/browse/DCOS-54879) Include taskids in job history.
> Bump Metronome to 0.6.27

- packages/metronome/buildinfo.json
Bump Metronome to 0.6.23
- [DCOS_OSS-5019](https://jira.mesosphere.com/browse/DCOS_OSS-5019) Improve secrets validation to only point out unprovided secrets.
- [DCOS-54879](https://jira.mesosphere.com/browse/DCOS-54879) Include taskids in job history.
> Update metronome to 0.6.27

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
* DCOS-55360 - Config / Version Updates for DC/OS 1.12.5
> DCOS-55360 - Version changes for DC/OS 1.12.5

- packages/marathon/buildinfo.json
- [MARATHON-8422](https://jira.mesosphere.com/browse/MARATHON-8422) Marathon won't get stuck killing an unreachable instance.
- [MARATHON-8631](https://jira.mesosphere.com/browse/MARATHON-8631) Persistent volumes with profile now default to DiskType.Mount
> Update Marathon to 1.8.207-9f3550487

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
* Update 1.13 to next version 1.13.3 - DCOS-55578
> Update in-development Version String of DC/OS 1.13

- packages/libevent/buildinfo.json
- packages/openssl/buildinfo.json
- [DCOS-54110](https://jira.mesosphere.com/browse/DCOS-54110) Update to latest OpenSSL 1.1.1x.
> Bumped to OpenSSL 1.1.1c and libevent 2.1.10.

- CHANGES.md
- packages/adminrouter/docker/Dockerfile
- packages/adminrouter/extra/src/lib/agent.lua
- packages/adminrouter/extra/src/lib/auth/common.lua
- packages/adminrouter/extra/src/lib/auth/open.lua
- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/lib/service.lua
- packages/adminrouter/extra/src/lib/util.lua
Bump OpenResty/nginx (for Admin Router) from 1.13.x to 1.15.x
https://jira.mesosphere.com/browse/DCOS_OSS-5320
> Bump OpenResty/nginx (for Admin Router) from 1.13.x to 1.15.x

- gen/calc.py
Attempts to reduce the relatively common occurrence of timeouts in checks that have no real way to time out by increasing the timeout to 5 seconds in case load is preventing a cluster from being able to run the check in the normal 1 second.
Bacports: https://github.com/dcos/dcos/pull/5529
---
- [DCOS-53742](https://jira.mesosphere.com/browse/DCOS-53742)
> [1.12] Increase "instant" checks timeout to 5s

- gen/calc.py
Attempts to reduce the relatively common occurrence of timeouts in checks that have no real way to time out by increasing the timeout to 5 seconds in case load is preventing a cluster from being able to run the check in the normal 1 second.
Bacports: https://github.com/dcos/dcos/pull/5529
---
- [DCOS-53742](https://jira.mesosphere.com/browse/DCOS-53742)
> [1.13] Increase "instant" checks timeout to 5s

- CHANGES.md
This is an editorial update of `CHANGES.md` in the `master` branch.
> CHANGES.md: editorial update

- packages/dcos-integration-test/extra/test_networking.py
Fix l4lb integration tests.
- [DCOS-54675](https://jira.mesosphere.com/browse/DCOS-54675) Flaky test test_vip_port_mapping: fails on 'assert not errors'
> [1.11] Fix l4lb integration tests

- packages/dcos-integration-test/extra/test_networking.py
Fix l4lb integration tests.
- [DCOS-54675](https://jira.mesosphere.com/browse/DCOS-54675) Flaky test test_vip_port_mapping: fails on 'assert not errors'
> [1.13] Fix l4lb integration tests

- packages/dcos-integration-test/extra/test_networking.py
Fix l4lb integration tests.
- [DCOS-54675](https://jira.mesosphere.com/browse/DCOS-54675) Flaky test test_vip_port_mapping: fails on 'assert not errors'
> Fix l4lb integration tests

- packages/dcos-integration-test/extra/test_networking.py
Fix l4lb integration tests.
- [DCOS-54675](https://jira.mesosphere.com/browse/DCOS-54675) Flaky test test_vip_port_mapping: fails on 'assert not errors'
> [1.12] Fix l4lb integration tests

- mergebot-config.json
This removes 1.12.5 from required statuses in mergebot-config.json. Should not have been added yet.
> Remove 1.12.5 from mergebot-config as it should not be there yet

- mergebot-config.json
Removes 1.13.2 from mergebot-config.json post-release
> Removing 1.13.2 from mergebot-config.json post-release

- mergebot-config.json
Next milestone in the CHANGES.md 2019 initiative: making the new CI check _required_ to pass.
> mergebot config: make changes_md check required

- CHANGES.md
- packages/dcos-signal/build
- packages/dcos-signal/buildinfo.json
- packages/dcos-signal/extra/dcos-signal.service
Since open source clusters don't have licenses, I'm moving the licensing information for signal to dcos-enterprise. See https://github.com/mesosphere/dcos-enterprise/pull/6095
- [DCOS-55882](https://jira.mesosphere.com/browse/DCOS-55882)
> Move signal licensing details to enterprise and bump signal version

- CHANGES.md
- packages/mesos/buildinfo.json
- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0006-Override-source-address-for-executors.patch
This PR bumps Mesos to a version that permits server certificate verification to be enabled in the corresponding EE PR.
- [DCOS_OSS-5345](https://jira.mesosphere.com/browse/DCOS_OSS-5345) Bump Mesos to the version with all the "proper TLS" goodies.
Included in DC/OS Enterprise, since the change will only affect enterprise strict mode by default.
> Server certificate verification for Mesos components.

- CHANGES.md
- gen/dcos-config.yaml
- packages/telegraf/buildinfo.json
This PR adds [mesos operations metrics](https://mesos.apache.org/documentation/latest/monitoring/#operations) to the Telegraf metrics pipeline.
- [DCOS_OSS-5023](https://jira.mesosphere.com/browse/DCOS_OSS-5023) Add Mesos operations metrics to Telegraf
> Mesos operations metrics

- packages/exhibitor/extra/dcos_zk_backup.py
This PR changes the ZooKeeper backup/restore script so that it checks that the ZooKeeper process is not running. Before it only asserted that `dcos-exhibitor` was not running which we suspect to not coincide with the former 100% of the cases.
The change enables getting a better understanding of the failure mode next time the flaky test in the JIRA fails. This is not a fix but a mere improvement of the debug output.
- [DCOS-55827](https://jira.mesosphere.com/browse/DCOS-55827) TestZooKeeperBackup.test_transaction_log_backup_and_restore if flaky.
**edit by @adamtheturtle : We now have an issue just for this, https://jira.mesosphere.com/browse/DCOS-56097 **
> Assert ZooKeeper is not running on backup

- CHANGES.md
- packages/dcos-signal/build
- packages/dcos-signal/buildinfo.json
- packages/dcos-signal/extra/dcos-signal.service
Bumps signal version and corrects the licensing socket location
- [DCOS-55882](https://jira.mesosphere.com/browse/DCOS-55882) 
> [1.11] Bump dcos-signal version

- CHANGES.md
- packages/dcos-signal/build
- packages/dcos-signal/buildinfo.json
- packages/dcos-signal/extra/dcos-signal.service
Bumps signal version and corrects the licensing socket location
- [DCOS-55882](https://jira.mesosphere.com/browse/DCOS-55882) 
> [1.13] Bump dcos-signal version

- CHANGES.md
- packages/dcos-integration-test/extra/test_metrics.py
- packages/mesos-modules/buildinfo.json
Add overlay metrics to ease detection of common issues users of the overlay module encounter.
- [DCOS_OSS-5322](https://jira.mesosphere.com/browse/DCOS_OSS-5322) Export metrics from Mesos overlay module.
> Bump Mesos modules to have overlay metrics exposed

- CHANGES.md
- packages/dcos-signal/build
- packages/dcos-signal/buildinfo.json
- packages/dcos-signal/extra/dcos-signal.service
Bumps signal version and corrects the licensing socket location
- [DCOS-55882](https://jira.mesosphere.com/browse/DCOS-55882) 
> [1.12] Bump dcos-signal version

- CHANGES.md
- packages/telegraf/buildinfo.json
This PR is a 1.13 backport of #5812. It updates the Telegraf Prometheus plugin to use the IP address specified in a task's container status field, rather than relying on the private node IP. This fixes an issue where prometheus metrics could not be collected from tasks using container networking mode.
- [DCOS-56018](https://jira.mesosphere.com/browse/DCOS-56018) Telegraf Prometheus plugin sources metrics from node IP, not task IP
> [1.13] Update Telegraf prometheus plugin for container mode

- mergebot-config.json
- [DCOS-56358](https://jira.mesosphere.com/browse/DCOS-56358) DC/OS 1.13.3 Release for SOAK.
> [DCOS-56358] Code freeze for 1.13.3

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
- [DCOS-56358](https://jira.mesosphere.com/browse/DCOS-56358) DC/OS 1.13.3 Release for SOAK.
> [DCOS-56358] - Update version to 1.13.4-dev

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
- packages/telegraf/buildinfo.json
Bump the Telegraf version in order to have Mesos overlay module metrics collected and pushed to Prometheus.
- [DCOS_OSS-5323](https://jira.mesosphere.com/browse/DCOS_OSS-5323) Adjust Telegraf's Mesos plugin to collect overlay metrics from Mesos
> Bump Telegraf to have Mesos overlay module metrics collected

- packages/dcos-net/extra/dcos-net-watchdog.py
Just fixes a little typo in exception handling
- [DCOS_OSS-5359](https://jira.mesosphere.com/browse/DCOS_OSS-5359) Typo in dcos-net-watchdog.py
> fixed typo erorr => error

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- gen/tests/test_config.py
Add two configuration parameters for container IPC.
- [DCOS-56619](https://jira.mesosphere.com/browse/DCOS-56619) Add IPC related configuration parameters in DC/OS
> gen: add two configuration parameters for container IPC.

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-net/buildinfo.json
Expose overlay networking metrics from `dcos-net`.
- [DCOS_OSS-5324](https://jira.mesosphere.com/browse/DCOS_OSS-5324) Expose metrics from dcos-overlay
> Add dcos-net overlay metrics

- CHANGES.md
- packages/mesos/buildinfo.json
- packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch
- packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch
- packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch
- packages/mesos/extra/patches/0004-Revert-Removed-long-ago-deprecated-endpoints.patch
- packages/mesos/extra/patches/0005-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch
- packages/mesos/extra/patches/0006-Override-source-address-for-executors.patch
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/9932550e9632e7fbb9a45b217793c7f508f57001...f3b827fa0206715ea1242ab839c3f7c0d7f685f4
> [master] Bump Mesos to nightly master f3b827f

- CHANGES.md
- packages/marathon/buildinfo.json
- [DCOS-56722](https://jira.mesosphere.com/browse/DCOS-56722) bump for DC/OS with Marathon 1.9 multi-tenancy features
- [] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
- [] Code Coverage (if available): N/A
> Bump to Marathon 1.9.20 to DCOS 1.14 (master)

- CHANGES.md
- packages/dcos-ui/buildinfo.json
Update to latest DC/OS UI (v1.127.1)
- [DCOS-56452](https://jira.mesosphere.com/browse/DCOS-56452)
- [DCOS-56743](https://jira.mesosphere.com/browse/DCOS-56743)
N/A
> [master] Bump DC/OS UI v2.127.1

- packages/dcos-integration-test/extra/test_mesos.py
Added an integration test that verifies availability of `/containerizer/debug` [endpoint exposed](http://mesos.apache.org/documentation/latest/endpoints/slave/containerizer/debug/) by the Mesos agent.
- [DCOS-56672](https://jira.mesosphere.com/browse/DCOS-56672) DCOS integration test for container debuggability
- [DCOS-55383](https://jira.mesosphere.com/browse/DCOS-55383) Containerizer debug endpoint (epic).
- Depends on [this PR](https://github.com/dcos/dcos/pull/5892).
N/A - not a functional change
> DCOS-56672 - Add integration test for container debuggability.

- CHANGES.md
- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/f3b827fa0206715ea1242ab839c3f7c0d7f685f4...ff8c9a96be6ae1ee47faf9d5b80a518dfb4a3db0
> [master] Bump Mesos to nightly master ff8c9a9

- packages/dcos-integration-test/extra/test_networking.py
- [DCOS-56871](https://jira.mesosphere.com/browse/DCOS-56871) test_networking.test_l4lb is flaky
> [1.11] test_networking.test_l4lb is flaky

- packages/dcos-integration-test/extra/test_ucr.py
Add an integration test for sharing /dev/shm in a pod.
- [DCOS-54620](https://jira.mesosphere.com/browse/DCOS-54620) Add an integration test for sharing /dev/shm in a pod.
> Added an integration test for sharing /dev/shm in a pod.

- packages/dcos-integration-test/extra/test_networking.py
- [DCOS-56871](https://jira.mesosphere.com/browse/DCOS-56871) test_networking.test_l4lb is flaky
> test_networking.test_l4lb is flaky

- packages/dcos-integration-test/extra/test_networking.py
- [DCOS-56871](https://jira.mesosphere.com/browse/DCOS-56871) test_networking.test_l4lb is flaky
> [1.13] test_networking.test_l4lb is flaky

- test_util/terraform_logs.sh
This fixes collection of sandbox logs. Before, we tried to SSH to the ELB which did not work - we should SSH to the IP.
- [DCOS_OSS-5373](https://jira.mesosphere.com/browse/DCOS_OSS-5373) Failed test bundles should include sandbox logs
> DCOS_OSS-5373 - Use master IP and not master FQDN to collect logs.

- packages/dcos-integration-test/extra/test_networking.py
- [DCOS-56871](https://jira.mesosphere.com/browse/DCOS-56871) test_networking.test_l4lb is flaky
> [1.12] test_networking.test_l4lb is flaky

- gen/dcos-config.yaml
- packages/dcos-diagnostics/build
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-diagnostics/extra/dcos-diagnostics-mesos-state.service
- packages/dcos-diagnostics/extra/dcos-diagnostics-mesos-state.timer
- packages/dcos-integration-test/extra/test_composition.py
Update dcos-diagnostics to latest version including `mesos-state` feature.
Add a systemd service generating mesos-state.tar wit 90 days of logs.
Add mesos-state.tar to the bundle.
- [DCOS-56379](https://jira.mesosphere.com/browse/DCOS-56379)
- [DCOS-56380](https://jira.mesosphere.com/browse/DCOS-56380)
- [DCOS-56403](https://jira.mesosphere.com/browse/DCOS-56403)
> Create Mesos state log and add it to the bunlde

- dcos_installer/test_backend.py
- gen/calc.py
* DCOS-56899  - Set DC/OS Version to 1.14.0-Alpha
> Set DC/OS version to 1.14.0-alpha-dev

- CHANGES.md
- packages/dcos-diagnostics/build
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-diagnostics/extra/dcos-diagnostics-mesos-state.service
- packages/dcos-diagnostics/extra/dcos-diagnostics-mesos-state.timer
- packages/dcos-integration-test/extra/test_composition.py
Update dcos-diagnostics to latest version including `mesos-state` feature.
Add a systemd service generating mesos-state.tar wit 90 days of logs.
Add mesos-state.tar to the bundle.
Backports https://github.com/dcos/dcos/pull/5907
---
- [DCOS-56379](https://jira.mesosphere.com/browse/DCOS-56379)
- [DCOS-56380](https://jira.mesosphere.com/browse/DCOS-56380)
- [DCOS-56403](https://jira.mesosphere.com/browse/DCOS-56403)
> [1.12] Crete Mesos state log and add it to the bunlde

- dcos_installer/test_backend.py
- gen/calc.py
* DCOS-56899 - DC/OS Version to 1.14.0-Alpha
* Artifacts created in this branch will be handed over to SOAK (DCOS-56603)
> Set DC/OS version to 1.14.0-alpha.

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-diagnostics/build
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-diagnostics/extra/dcos-diagnostics-mesos-state.service
- packages/dcos-diagnostics/extra/dcos-diagnostics-mesos-state.timer
- packages/dcos-integration-test/extra/test_composition.py
Update dcos-diagnostics to latest version including `mesos-state` feature.
Add a systemd service generating mesos-state.tar wit 90 days of logs.
Add mesos-state.tar to the bundle.
Bacports https://github.com/dcos/dcos/pull/5907
---
- [DCOS-56379](https://jira.mesosphere.com/browse/DCOS-56379)
- [DCOS-56380](https://jira.mesosphere.com/browse/DCOS-56380)
- [DCOS-56403](https://jira.mesosphere.com/browse/DCOS-56403)
> [1.13] Crete Mesos state log and add it to the bunlde

- packages/dcos-test-utils/buildinfo.json
Added this: dcos/dcos-test-utils@f2e8527a1d9f8de6062fc11d70f7063f348772a5
To solve this: https://jira.mesosphere.com/browse/DCOS-54793
> dcos test utils bump

- mergebot-config.json
* DCOS-56899 - DC/OS 1.14.0-alpha in required statuses.
> DC/OS 1.14.0-alpha in required statuses.

- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/env_helper.py
- packages/dcos-integration-test/extra/requirements.txt
- packages/pytest/buildinfo.json
> Pytest xdist

- CHANGES.md
- gen/cloud-config.yaml
Remove the increased journald rate limit. Scale testing demonstrates that the raised limit causes problems for other components that get delayed or lost logs. Logging that exceeds the default indicates that a component is logging excessively, and should be remedied in that component.
- [DCOS-53763](https://jira.mesosphere.com/browse/DCOS-53763) "too many" Admin Router access log lines went missing in MWST 15
Change to logging only.
> Revert to default journald rate limit

- mergebot-config.json
> Update mergebot-config.json (remove non-existent branch)

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
This PR added a DC/OS configuration option to allow chown docker volume.
- [DCOS_OSS-5381](https://jira.mesosphere.com/browse/DCOS_OSS-5381) Add a configuration option to change docker volume ownership to the task user.
> Added a DC/OS configuration option to allow chown docker volume.

- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/test_legacy_user_management.py
https://jira.mesosphere.com/browse/DCOS-57266
make CLI instantiation a fixture
> Pin cli plugins

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
Updated a configuration name to 'mesos_docker_volume_chown'.
- [DCOS_OSS-5381](https://jira.mesosphere.com/browse/DCOS_OSS-5381) Add a configuration option to change docker volume ownership to the task user.
> Updated a configuration name to 'mesos_docker_volume_chown'.

- CHANGES.md
- packages/telegraf/buildinfo.json
This bumps Telegraf to pull in https://github.com/dcos/telegraf/pull/61, which adds `framework_id` tags to Mesos master `framework_offers` metrics, so that the metrics of different framework instances with the same name can be distinguished. These metrics are documented here: https://mesos.apache.org/documentation/latest/monitoring/#frameworks.
- [DCOS-53302](https://jira.mesosphere.com/browse/DCOS-53302) Mesos per framework metrics can be incorrect if there are multiple instances of the framework
N/A
> Add framework_id tag to Mesos framework_offers metrics

- pkgpanda/docker/dcos-builder/Dockerfile
This updates the Go version that's used for building DC/OS to the latest version 1.12.8.
> Update go in dcos builder

- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- packages/dcos-integration-test/README.md
- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/env_helper.py
- packages/dcos-integration-test/extra/requirements.txt
- packages/dcos-integration-test/requirements.txt
- packages/pytest/buildinfo.json
- tox.ini
backport of pytest-xdist feature
passed here: https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&buildTypeId=DcOs_Open_Test_IntegrationTest_TerraformBasedIntegrationTests_PytestXdistTestAws&buildId=2181243
> 1.11 pytest xdist

- packages/windows.treeinfo.json
This is fixing windows builds by excluding dcos-bootstrap-ca
- [DCOS-57695](https://jira.mesosphere.com/browse/DCOS-57695) JIRA title / short description.
- [DCOS-57695](https://jira.mesosphere.com/browse/DCOS-57695) JIRA title / short description.
> Exclude dcos-bootstrap-ca from windows.

- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- packages/dcos-integration-test/README.md
- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/env_helper.py
- packages/dcos-integration-test/extra/requirements.txt
- packages/dcos-integration-test/requirements.txt
- packages/pytest/buildinfo.json
- tox.ini
backport of pytest-xdist feature
passed here: https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&buildTypeId=DcOs_Open_Test_IntegrationTest_TerraformBasedIntegrationTests_PytestXdistTestAws&buildId=2181241
> 1.12 pytest xdist

- packages/dcos-image-deps/build
- packages/dcos-image-deps/buildinfo.json
- packages/dcos-integration-test/README.md
- packages/dcos-integration-test/extra/conftest.py
- packages/dcos-integration-test/extra/env_helper.py
- packages/dcos-integration-test/extra/requirements.txt
- packages/dcos-integration-test/requirements.txt
- packages/pytest/buildinfo.json
- tox.ini
backport of pytest-xdist feature
passed here: https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&buildTypeId=DcOs_Open_Test_IntegrationTest_TerraformBasedIntegrationTests_PytestXdistTestAws&buildId=2181239
> 1.13 pytest xdist

- packages/bouncer/buildinfo.json
Bump Bouncer to perform group imports one user at a time. This should make group import more robust against database consistency errors.
- [DCOS-55766](https://jira.mesosphere.com/browse/DCOS-55766) TestOpenLdap.test_groupimport_large is flaky (Bouncer DB transaction fails with "transaction deadline exceeded")
[Bouncer EE](https://github.com/mesosphere/bouncer/compare/b55ebe30ae66683a9b3e2497d322a8a09f9d1705...df70e51acd183679a8d6c8ba8cfa67dbdf8e41da)
This attempts to resolve a flaky test issue, for which is difficult to …
> Bump bouncer

- packages/dcos-integration-test/extra/test_dcos_log.py
This places a retry around some logging API test assertions, which should make them less flaky.
- [DCOS-56866](https://jira.mesosphere.com/browse/DCOS-56866) teamcity/dcos/test/terraform/aws/onprem/static/group2 has flaky test: test_log_v2_pod_logs
N/A
> (1.11) Retry logging API test assertions

- packages/dcos-integration-test/extra/test_dcos_log.py
This places a retry around some logging API test assertions, which should make them less flaky.
- [DCOS-56866](https://jira.mesosphere.com/browse/DCOS-56866) teamcity/dcos/test/terraform/aws/onprem/static/group2 has flaky test: test_log_v2_pod_logs
N/A
> (1.13) Retry logging API test assertions

- gen/exhibitor_tls_bootstrap.py
always set values for gen.
Corrects an issue causing integration tests to fail
DCOS-56036
- [DCOS-56036](https://jira.mesosphere.com/browse/DCOS-DCOS-56036)
> match provider, not platform

- packages/dcos-integration-test/extra/test_dcos_log.py
This places a retry around some logging API test assertions, which should make them less flaky.
- [DCOS-56866](https://jira.mesosphere.com/browse/DCOS-56866) teamcity/dcos/test/terraform/aws/onprem/static/group2 has flaky test: test_log_v2_pod_logs
N/A
> (1.12) Retry logging API test assertions

- packages/dcos-net/buildinfo.json
Names of some internal metrics are improved.
- [DCOS_OSS-5436](https://jira.mesosphere.com/browse/DCOS_OSS-5436) Enhance Lashup metrics
> [1.13] Bump DC/OS Net

- CHANGES.md
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-diagnostics/extra/dcos-diagnostics-agent.service
- packages/dcos-diagnostics/extra/dcos-diagnostics-master.service
- packages/dcos-image-deps/buildinfo.json
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/requirements.txt
- packages/dcos-test-utils/buildinfo.json
- packages/python-responses/build
- packages/python-responses/buildinfo.json
- setup.py
- test-e2e/requirements.txt
This PR changes test to test both legacy and current diagnostics API.
* Use only one diagnostic client instead of creating one for every function
* Parametrize tests to have the same source code for legacy and new API
* Remove unecessary `.gz` suffix from expected files. For more context, see: [DCOS_OSS-4531](https://jira.mesosphere.com/browse/DCOS_OSS-4531)
* Update dcos-test-util to version that supports new diagnostics API https://github.com/dcos/dcos-test-utils/pull/97
* Updates dcos-diagnostics and it's configuration
- [DCOS_OSS-5426](https://jira.mesosphere.com/browse/DCOS_OSS-5426) Add E2E test for new API for bundle creation 
- [DCOS_OSS-5435](https://jira.mesosphere.com/browse/DCOS_OSS-5435) Implement new API in dcos-test-utils 
- …
> Enable new DC/OS Diagnostics API

- packages/dcos-integration-test/extra/test_dcos_log.py
This places a retry around some logging API test assertions, which should make them less flaky.
- [DCOS-56866](https://jira.mesosphere.com/browse/DCOS-56866) teamcity/dcos/test/terraform/aws/onprem/static/group2 has flaky test: test_log_v2_pod_logs
N/A
> Retry logging API test assertions

- packages/dcos-net/buildinfo.json
Names of some internal metrics are improved.
- [DCOS_OSS-5436](https://jira.mesosphere.com/browse/DCOS_OSS-5436) Enhance Lashup metrics
> Bump DC/OS Net

- gen/build_deploy/bash/dcos_generate_config.sh.in
this allows process to remain resident when executed via ssh with 'sh -c'
This patch allows exhibitor tls bootstrap automation to occur properly when invoked by terraform or dcos-launch onprem.  
- [DCOS-57807](https://jira.mesosphere.com/browse/DCOS-57807)
> Detach bootstrap ca process from parent

- packages/dcos-integration-test/extra/test_groups.yaml
- packages/dcos-integration-test/extra/test_signal.py
This test was at the wrong location.
- [DCOS_OSS-5479](https://jira.mesosphere.com/browse/DCOS_OSS-5479)     DC/OS Signal integration test not run
> Fixed location of DC/OS Signal integration test

- CHANGES.md
- packages/marathon/buildinfo.json
- packages/marathon/extra/marathon.sh
* [MARATHON-8672](https://jira.mesosphere.com/browse/MARATHON-8672) - Changing the role for resident service results in old instances unable to relaunch
* [MARATHON-8654](https://jira.mesosphere.com/browse/MARATHON-8654) - Data Migration to cull out invalid resource roles in acceptedResourceRoles
* [MARATHON-8659](https://jira.mesosphere.com/browse/MARATHON-8659), [MARATHON-8655](https://jira.mesosphere.com/browse/MARATHON-8655) - Replace --default_accepted_resource_roles with multi-role compliant --accepted_resource_roles_default_behavior
* [MARATHON-8687](https://jira.mesosphere.com/browse/MARATHON-8687) - Expose instance role via the pod instance status endpoint
* …
> Bump Marathon to 1.9.64

- mergebot-config.json
* DCOS-57906 - Set the FixVersion for 1.13 branch to 1.13.5
> Update mergebot config fixVersion for 1.13 branch to 1.13.5.

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
DCOS-57906 - Set 1.13 Development Version to 1.13.5.
>  DCOS-57906 - Set 1.13 Development Version to 1.13.5.

- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Update dcos-diagnostics with fixes for new unreleased API. Changelog is not required since this API was not announced yet.
- [DCOS_OSS-5467](https://jira.mesosphere.com/browse/DCOS_OSS-5467) Include optional file in the bundle
- [DCOS_OSS-5470](https://jira.mesosphere.com/browse/DCOS_OSS-5470) Deletion of cluster bundle doesn't delete node bundles
- [DCOS_OSS-5449](https://jira.mesosphere.com/browse/DCOS_OSS-5449) Empty files in a bundle
- [DCOS_OSS-5456](https://jira.mesosphere.com/browse/DCOS_OSS-5456) Cluster Bundle Handler includes any bundles on the master nodes
- [DCOS_OSS-5454](https://jira.mesosphere.com/browse/DCOS_OSS-5454) diagnostics list breaks when no bundles have been created
- [DCOS-57879](https://jira.mesosphere.com/browse/DCOS-57879) Creating a cluster bundle remains in …
> Update dcos diagnostics

- packages/dcos-integration-test/extra/test_metrics.py
Muting a flaky test for https://jira.mesosphere.com/browse/DCOS-57896
- https://jira.mesosphere.com/browse/DCOS-57896 - test failing due to not finding expected metrics
> Muting flaky test for DCOS-57896

- CHANGES.md
This PR updates `CHANGES.md` to include notes about the new node draining feature as well as command health check performance improvements.
- [DCOS-53654](https://jira.mesosphere.com/browse/DCOS-53654) [Mesos] Node draining
- [DCOS-53656](https://jira.mesosphere.com/browse/DCOS-53656) [Mesos] Benchmark command healthcheck scalability and document supported scale
> Update CHANGES.md for node draining and health check scalability.

- CHANGES.md
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-diagnostics/extra/dcos-diagnostics-agent.service
- packages/dcos-diagnostics/extra/dcos-diagnostics-master.service
- packages/dcos-image-deps/buildinfo.json
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/requirements.txt
- packages/dcos-test-utils/buildinfo.json
- packages/python-responses/build
- packages/python-responses/buildinfo.json
- setup.py
- test-e2e/requirements.txt
Backports:
* https://github.com/dcos/dcos/pull/6032
* https://github.com/dcos/dcos/pull/6132
Fixes:
- [DCOS_OSS-5098](https://jira.mesosphere.com/browse/DCOS_OSS-5098)
> [1.13] Enable new dcos-diagnostics API

- CHANGES.md
- packages/dcos-diagnostics/buildinfo.json
- packages/dcos-diagnostics/extra/dcos-diagnostics-agent.service
- packages/dcos-diagnostics/extra/dcos-diagnostics-master.service
- packages/dcos-image-deps/buildinfo.json
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/requirements.txt
- packages/dcos-test-utils/buildinfo.json
- packages/python-responses/build
- packages/python-responses/buildinfo.json
- setup.py
- test-e2e/requirements.txt
Backports:
* https://github.com/dcos/dcos/pull/6032
* https://github.com/dcos/dcos/pull/6132
Fixes:
* https://jira.mesosphere.com/browse/DCOS_OSS-5098
> [1.12] Enable new dcos-diagnostics API

- packages/dcos-integration-test/extra/test_ucr.py
Add an integration test for launching app with a specified size of /dev/shm
- [DCOS-58025](https://jira.mesosphere.com/browse/DCOS-58025) Add integration test for launching app with a specified size of /dev/shm.
> Add a test for launching app with a specified size of /dev/shm

- packages/windows.treeinfo.json
This change excludes python-response package from the windows build.
- [DCOS_OSS-5504](https://jira.mesosphere.com/browse/DCOS_OSS-5504) Remove python-response from windows build.
- [DCOS_OSS-5504](https://jira.mesosphere.com/browse/DCOS_OSS-5504) Remove python-response from windows build.
> Removing python-requests from windows builds.

- packages/mesos/extra/patches/0007-Disabled-hostname-validation-for-master-scheduler-communication.patch
Removed two unnecessary hunks from the patch effectively disabling
hostname validation for Master -> Scheduler TLS communication,
reducing the surface are for future merge conflicts.
- [58066](https://jira.mesosphere.com/browse/DCOS-58066) Remove unnecessary changes from Mesos TLS cherry-pick
> Pruned Mesos Patch for Master -> Scheduler TLS connections.

- CHANGES.md
- packages/mesos/buildinfo.json
- packages/mesos/windows.buildinfo.json
Bump Mesos to 1.9.0-rc3
- [DCOS_OSS-5342](https://jira.mesosphere.com/browse/DCOS_OSS-5342) Bump Mesos for DC/OS 1.14.0-beta
> [master] Bump Mesos to 1.9.0-rc3

- CHANGES.md
- packages/dcos-ui/buildinfo.json
Bumps DC/OS UI to v2.148.2, which includes a bug fix for quota limit status display
- [DCOS_OSS-5510](https://jira.mesosphere.com/browse/DCOS_OSS-5510) Quota enforced shows incorrectly for services that are not quota-enforced
> chore(dcos-ui): bump to v2.148.2

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
* DCOS-58261 - Set DC/OS version to 2.0.0-beta
> DC/OS version 2.0.0-beta.

- mergebot-config.json
Set the Branch Protections for 2.0 branch.
The `master` branch is 2.1.0 and `2.0` branch is for `2.0.0`
* https://jira.mesosphere.com/browse/DCOS-58261
> Set Branch Protections for 2.0 Branch.

- CHANGES.md
- packages/dcos-diagnostics/buildinfo.json
Bump dcos-diagnostics
Backports https://github.com/dcos/dcos/pull/6195
---
- [DCOS-58105](https://jira.mesosphere.com/browse/DCOS-58105)
- [DCOS_OSS-5494](https://jira.mesosphere.com/browse/DCOS_OSS-5494)
> [1.12] Bump dcos-diagnostics version

- CHANGES.md
- packages/dcos-diagnostics/buildinfo.json
Bump dcos-diagnostics
Backports https://github.com/dcos/dcos/pull/6195
---
- [DCOS-58105](https://jira.mesosphere.com/browse/DCOS-58105)
- [DCOS_OSS-5494](https://jira.mesosphere.com/browse/DCOS_OSS-5494)
> [1.13] Bump dcos-diagnostics version

- CHANGES.md
- packages/dcos-diagnostics/buildinfo.json
Bump dcos-diagnostics
- [DCOS-58105](https://jira.mesosphere.com/browse/DCOS-58105)
- [DCOS_OSS-5494](https://jira.mesosphere.com/browse/DCOS_OSS-5494)
> Bump dcos-diagnostics version

- owners.json
Cluster Ops team needs to have an owner on DC/OS to be able to
carefully override CI failures. We have been blocked multiple times
for a non-trivial amount of time from flaky tests since no owner was
available (in our timezone).
> Add myself to owners file and remove Adam

- fetch_cluster_logs.bash
Adds output to fetch_cluster_logs output in the event of a file that is larger than maximum artifact size.
If the file is a tarball, it dumps out contents to assist with debugging (what was in tarball, why was file oversize, etc).
In any event, it provides information on how to adjust the size threshhold.
- [DCOS-55767](https://jira.mesosphere.com/browse/DCOS-55767) test_registry_cli.test_framework_install fails in the integration test.
> Updating fetch_cluster_logs to provide info on oversize files

- packages/dcos-diagnostics/extra/dcos-diagnostics-master.service
Backport Exhibitor TLS client fixes
- [DCOS-58361](https://jira.mesosphere.com/browse/DCOS-58361) [Backport] Fix DC/OS clients that do not adhere to Exhibitor TLS (1.12, 1.13)
> Backport Exhibitor TLS client changes 1.12

- gen/dcos-config.yaml
- packages/dcos-diagnostics/extra/dcos-diagnostics-master.service
Backport Exhibitor TLS client fixes
- [DCOS-58361](https://jira.mesosphere.com/browse/DCOS-58361) [Backport] Fix DC/OS clients that do not adhere to Exhibitor TLS (1.12, 1.13)
> Backport Exhibitor TLS client changes 1.13

- fetch_cluster_logs.bash
https://jira.mesosphere.com/browse/DCOS-57008
The collected logs would be very minimal. Only the last second. As you can see in the linked artifacts, they are all significantly larger (closer to 1 MB)
proof it works:
Open 1.10: https://teamcity.mesosphere.io/viewLog.html?buildId=2252983&buildTypeId=DcOs_Open_Test_IntegrationTest_TestLogFetcherAwsOnpremWStaticBackendGroup1&tab=artifacts
Open master: https://teamcity.mesosphere.io/viewLog.html?buildId=2252985&buildTypeId=DcOs_Open_Test_IntegrationTest_TestLogFetcherAwsOnpremWStaticBackendGroup1&tab=artifacts
EE 1.10: https://teamcity.mesosphere.io/viewLog.html?buildId=2252987&buildTypeId=DcOs_Enterprise_Test_Inte_TestLogCollectionAwsOnpremWStaticBackendAndSecurityStr&tab=artifacts
EE master : …
> Collect all lines for mesos node logs

- packages/dcos-diagnostics/buildinfo.json
Backports:  #6224
---
- [DCOS_OSS-5516](https://jira.mesosphere.com/browse/DCOS_OSS-5516) Limit how long single collector can work
> [2.0] Bump dcos-diagnostics

- fetch_cluster_logs.bash
Updating fetch_logs function to provide additional output in the event of an oversized file.
Will dump tarball contents if it triggers oversize condition and reports how to adjust threshhold
- [DCOS-55767](https://jira.mesosphere.com/browse/DCOS-55767) test_registry_cli.test_framework_install fails in the integration test.
> Adding logic to list oversized tarball contents to help debugging

- pkgpanda/util.py
This is fixing the windows build by using bzip2 mode for creating a tar file on windows.
- [/DCOS_OSS-5499](https://jira.mesosphere.com/browse/DCOS_OSS-5499) Fix Teamcity CI/CD build
> Fix windows build

- CHANGES.md
- packages/java/build
- packages/java/buildinfo.json
https://jira.mesosphere.com/browse/DCOS-54902
> Oracle JDK -> Open JDK

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
* DCOS-58190 - Set DC/OS version of `1.13` to 1.13.6-dev
> Set the 1.13 in-development version to 1.13.6

- CHANGES.md
- packages/cni/buildinfo.json
Bump CNI to latest version in 0.7.x branch 
Updated used Go version to 1.13
> Bump CNI to 0.7.6

- CHANGES.md
- packages/java/build
- packages/java/buildinfo.json
> Oracle Java -> OpenJDK

- CHANGES.md
*  DCOS-58854 - Removed Fixed and Improved Section as per [changes.md guidelines ](https://github.com/dcos/dcos/wiki/CHANGES.md-guidelines) and [review comment](https://github.com/dcos/dcos/pull/6261#issuecomment-531632271)
> Removed Fixed and Improved section as per changelog protocol.

- packages/dcos-diagnostics/windows.build.ps1
- packages/dcos-diagnostics/windows.buildinfo.json
- packages/windows.treeinfo.json
- pkgpanda/docker.windows/dcos-builder/Dockerfile
- pkgpanda/docker.windows/dcos-builder/setup-golang.ps1
Adding dcos-diagnostics build.
- [DCOS_OSS-5543](https://jira.mesosphere.com/browse/DCOS_OSS-5543) Adding dcos-diagnostics Windows build.
> Adding dcos-diagnostics Windows build.

- mergebot-config.json
Change is making Windows builds required.
> Windows builds are required by now.

- packages/dcos-integration-test/extra/test_networking.py
https://jira.mesosphere.com/browse/DCOS-53552 resolved
> Unmute test_if_overlay_ok

- packages/mesos/windows.build.ps1
This makes a few small, but important changes:
* The `-DENABLE_LIBEVENT` configuration is buggy and unsupported on Windows.  So it has been removed.
* To produce an optimized release build, the build line needs to be run via `--config Release`.
* Multi-process builds are the default, so the `-- /m` arguments are extraneous.
- None
- None
> Updated Windows build script.

- CHANGES.md
- gen/dcos-config.yaml
Number of diagnostics feathers controls the parallelism level of diagnostics bundle creation job. We did test it on latest master release and it is safe to increase it to 100. This should significantly reduce diagnostics bundle generation time.
- [DCOS-51483](https://jira.mesosphere.com/browse/DCOS-51483) Increase number of workers configured
> [1.12] Increase number of diagnostics fetchers

- CHANGES.md
- gen/dcos-config.yaml
Number of diagnostics feathers controls the parallelism level of diagnostics bundle creation job. We did test it on latest master release and it is safe to increase it to 100. This should significantly reduce diagnostics bundle generation time.
https://github.com/dcos/dcos/pull/6293
- [DCOS-51483](https://jira.mesosphere.com/browse/DCOS-51483) Increase number of workers configured
> [1.13] Increase number of diagnostics fetchers

- CHANGES.md
- packages/mesos/buildinfo.json
This is a preparatory change for the corresponding EE PR.
- [DCOS-59098](https://jira.mesosphere.com/browse/DCOS-59098) Frameworks using libmesos1.8 and container networking may fail TLS hostname validation
> [Master] Bump Mesos to include SSL environment variable renamings.

- CHANGES.md
- packages/mesos/buildinfo.json
In the last MWT, we discovered a connectivity issue with the
Spark framework when running in CNI networking mode that were
caused by accidentally leaking agent configuration variables
into the scheduler environment, in combination with broken
behaviour of TLS hostname validation in older versions of
Mesos.
While the issue is already fixed for Spark at the framework
level, this bump introduces a more general change in Mesos
that will prevent other frameworks running n similar CNI
configuration in user environments from experiencing the same
issues.
- [DCOS-59098](https://jira.mesosphere.com/browse/DCOS-59098) Frameworks using libmesos1.8 and container networking may fail TLS hostname validation
If …
> [2.0] Bump Mesos to include SSL environment variable renamings.

- packages/adminrouter/docker/requirements-tests.txt
- test-e2e/requirements.txt
- tox.ini
* DCOS_OSS-5579 - Pin attrs dependency for a breaking change.
> Pin attrs version to 19.1.0

- packages/adminrouter/docker/requirements-tests.txt
- test-e2e/requirements.txt
- tox.ini
* DCOS_OSS-5579 - Pin attrs dependency for a breaking change.
> DCOS_OSS-5579 - Pin attrs dependency for a breaking change.

- packages/dcos-integration-test/extra/test_adminrouter_open.py
Use bridge networking to simplify network setup and, in particular, to prevent delays in propagating the overlay network from affecting the test.
- [DCOS-58518](https://jira.mesosphere.com/browse/DCOS-58518) TestStateCacheUpdate.test_invalid_dcos_service_port_index test is flaky 
> Use bridge networking for invalid service port test

- packages/telegraf/windows.build.ps1
- packages/telegraf/windows.buildinfo.json
- packages/windows.treeinfo.json
Provide a telegraf build for windows. this is based on the work of @AleksanderBelov (for reference https://github.com/dcos/dcos/pull/6319)
- [DCOS_OSS-5556](https://jira.mesosphere.com/browse/DCOS_OSS-5556) JIRA title / short description.
> Provide telegraf windows build

- CHANGES.md
- packages/dcos-ui/buildinfo.json
- [DCOS-59316](https://jira.mesosphere.com/browse/DCOS-59316) 
> chore: Bump DC/OS UI v2.149.4

- packages/dcos-diagnostics/buildinfo.json
Update dcos-diagnostics
- [DCOS_OSS-5472](https://jira.mesosphere.com/browse/DCOS_OSS-5472) Create a bundle only for selected nodes
> [2.0] Update dcos-diagnostics

- packages/cockroach/extra/cockroach.sh
- packages/cockroach/extra/register.py
Fixes an issuer where cockroachdb would advertise the node hostname
- [DCOS-59735](https://jira.mesosphere.com/browse/DCOS-59735) CockroachDB uses DNS names for inter-node comms, instead of IP addresses (breaks cert verification, breaks cluster)
> Use correct start arguments for cockroachdb 2.1

- packages/cockroach/extra/cockroach.sh
- packages/cockroach/extra/register.py
Fixes an issuer where cockroachdb would advertise the node hostname
- [DCOS-59735](https://jira.mesosphere.com/browse/DCOS-59735) CockroachDB uses DNS names for inter-node comms, instead of IP addresses (breaks cert verification, breaks cluster)
> [DCOS 2.0] Use correct start arguments for cockroachdb 2.1 

- packages/dcos-diagnostics/windows.buildinfo.json
Update dcos-diagnostics
- [DCOS_OSS-5472](https://jira.mesosphere.com/browse/DCOS_OSS-5472) Create a bundle only for selected nodes
> Update dcos-diagnostics for windows

- gen/build_deploy/bash.py
- setup.py
That one of steps to integrate the dcos_install.ps1 into dcos_generate_config.sh so that it will be deployed to Bootrsrtap machine
There is no packages changes introduced.
- [DCOS_OSS-5562](https://jira.mesosphere.com/browse/DCOS_OSS-5562) Integrate Universal Installer to Winpanda setup process .
@jongiddy , @DominikDary , please review/approve/merge. That's "easy" integration  we were talking on Architecture meeting, 10th of Oct 2019.
@mesosphere-mergebot , changelog-not-required Preparation to add Winpanda
> DCOS_OSS-5562: added make_powershell function to 

- CHANGES.md
- packages/dcos-ui/buildinfo.json
> chore: Bump DC/OS UI v2.150.0

- CHANGES.md
- packages/marathon/buildinfo.json
Bump Marathon to 1.9.100. Fixes blocked issue MARTHON-8706. Also includes some performance improvements and a fix for external volumes.
JIRA Issues:
- [MARATHON-8707](https://jira.mesosphere.com/browse/MARATHON-8707) - Fix a regression from MARATHON-8706 in which mid-level groups would attempt to enable enforceRole
- [MARATHON-8706](https://jira.mesosphere.com/browse/MARATHON-8706) - Fixed an issue where `--new_group_enforce_role top` was not abided when auto-creating groups for services posted in not-yet-existing groups.
- [MARATHON-8703](https://jira.mesosphere.com/browse/MARATHON-8703) - UpgradeIntegrationTest should test upgrades from 1.7 and 1.8
- [MARATHON-8567](https://jira.mesosphere.com/browse/MARATHON-8567) - …
> Bump marathon to 1.9.100

- mergebot-config.json
- DCOS-60193 Update DC/OS Fix Versions and Versions after release of 2.0.0
> Update the mergebot fix version for 2.0 branch.

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
* DCOS-60193 Update DC/OS Fix Versions and Versions after release of 2.0.0
> Update version and change.md for 2.0.1

- packages/installer.treeinfo.json
- packages/nssm/windows.build.ps1
- packages/nssm/windows.buildinfo.json
- packages/treeinfo.json
- packages/vcredist/windows.build.ps1
- packages/vcredist/windows.buildinfo.json
- packages/windows.treeinfo.json
- [DCOS_OSS-5592](https://jira.mesosphere.com/browse/DCOS_OSS-5592) JIRA title / short description.
@mesosphere-mergebot changelog-not-required
@mesosphere-mergebot request-review @jongiddy 
@mesosphere-mergebot request-review @DominikDary
> add packages vcredist and nssm (DCOS_OSS-5592)

- gen/ip-detect/aws.sh
- gen/ip-detect/aws6.sh
- gen/ip-detect/aws_public.sh
closes https://jira.mesosphere.com/browse/DCOS-59678
Adds a retry mechanism to the AWS ip-detect scripts to account for temporary unavailability of the AWS metadata service.
- [DCOS-59678](https://jira.mesosphere.com/browse/DCOS-59678) TestCockroachCluster.test_cluster_ensemble failed: detect_ip fails with status code 7 on AWS CI cluster.
> Add retry mechanism to AWS ip-detect scripts

- packages/cni/buildinfo.json
- packages/dvdcli/buildinfo.json
- packages/mesos-dns/buildinfo.json
- packages/telegraf/buildinfo.json
By removing specific docker version in buildinfo.json, pkgpanda will use
dcos/dcos-builder.
https://github.com/dcos/dcos/blob/c9e43e3af91c54c4b3f13fb12c3b935a3517c276/pkgpanda/docker/dcos-builder/Dockerfile#L54-L56
https://golang.org/doc/go1.13
- [DCOS_OSS-5517](https://jira.mesosphere.com/browse/DCOS_OSS-5517) Switch to go 1.13
> Use the same golang version for all projects

- packages/docker-gc/extra/dcos-docker-gc.service
`docker system prune` will remove networks that do not have containers
currently attached to them. This will remove the `dcos` and `dcos6`
network if they are not in use. Instead prune just the objects desired.
- [DCOS_OSS-5441](https://jira.mesosphere.com/browse/DCOS_OSS-5441) Switch to `docker system prune`.
> docker-gc: don't run `system prune`

- CHANGES.md
- packages/dcos-diagnostics/buildinfo.json
Fixes https://jira.mesosphere.com/browse/COPS-5509
- [COPS-5509](https://jira.mesosphere.com/browse/COPS-5509) DC/OS Diagnostics Bundle Download fails via Master Load Balancer
> Bump DC/OS Diagnostics

- CHANGES.md
- packages/dcos-ui/buildinfo.json
- [DCOS-60342](https://jira.mesosphere.com/browse/DCOS-60342)
- [DCOS-60344](https://jira.mesosphere.com/browse/DCOS-60344)
> chore: Bump DC/OS UI v2.83.0

- packages/installer.treeinfo.json
- packages/treeinfo.json
- packages/windows.treeinfo.json
- packages/winpanda/windows.build.ps1
- packages/winpanda/windows.buildinfo.json
- pkgpanda/docker.windows/dcos-builder/Dockerfile
- pkgpanda/docker.windows/dcos-builder/setup-python36.ps1
- [DCOS_OSS-5636](https://jira.mesosphere.com/browse/DCOS_OSS-5636) Add Winpanda build scripts (Winpanda - Package Installation for Windows)
> Add Winpanda build scripts (DCOS_OSS-5636)

- gen/__init__.py
- gen/calc.py
- gen/dcos-config-win.yaml
- setup.py
Create a `dcos-config-win` package on Linux bootstrap. This contains the Windows configuration YAML and the expanded variables. Unlike other setup packages, the YAML file is not interpreted on the Linux bootstrap node. Instead, the package needs to be downloaded to the Windows agent node and interpreted there.
To create the additional package, the `config.yaml` file must contain
```yaml
enable_windows_agents: true
```
- [DCOS_OSS-5656](https://jira.mesosphere.com/browse/DCOS_OSS-5656) Creat dcos-config-windows package on bootstrap node …
> Add Windows config to Linux build

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
https://jira.mesosphere.com/browse/DCOS-60977
Updating 1.11.13-dev to 1.11.14-dev
> 1.11.14-dev

- packages/winpanda/extra/src/winpanda/core/utils.py
- packages/winpanda/extra/src/winpanda/requirements.txt
1) implement loader routine for YAML-formatted resource files
2) add Jinja2 template rendering support to JSON-, INI- and
YAML-formatted resource file loader routines
3) refine/adjust requirements list
JIRA: DCOS_OSS-5570 - Winpanda App: Add Support For Extra
DC/OS Package Installation Helpers
> Winpanda App: Add Support For Extra DC/OS Package Installation Helpers

- CHANGES.md
- README.md
- packages/bootstrap/extra/dcos_internal_utils/cli.py
- packages/dcos-integration-test/extra/test_composition.py
- packages/etcd/build
- packages/etcd/buildinfo.json
- packages/etcd/extra/Makefile
- packages/etcd/extra/README.txt
- packages/etcd/extra/etcd_discovery/etcd_discovery.py
- packages/etcd/extra/systemd/dcos-etcd.service
- packages/etcd/extra/systemd/etcd.sh
- packages/etcd/extra/tests/Makefile
- packages/etcd/extra/tests/README.md
- packages/etcd/extra/tests/conftest.py
- packages/etcd/extra/tests/test_etcd_discovery.py
- packages/windows.treeinfo.json
This PR integrates ETCD into open source DC/OS.
It's basically a copy and paste from  [ETCD in EE DC/OS PR](https://github.com/mesosphere/dcos-enterprise/pull/6705)
- [DCOS-59004](https://jira.mesosphere.com/browse/DCOS-59004) Port POC code from EE to Open.
> add etcd into open source DC/OS

- CHANGES.md
- packages/libpq/buildinfo.json
Remove redundant `libpq` package in Enterprise, so Open contains the single supported version. Update that version to latest patch version of 9.6
- [DCOS-59145](https://jira.mesosphere.com/browse/DCOS-59145) Merge libpq on Open and EE
> Update libpq to 9.6.15

- gen/build_deploy/powershell/dcos_install.ps1
dcos_install.ps1 enhancements and bug-fixes:
- removed RunOnce logic
- updated cluster.conf params
- added Set-EnvPath function for properly handle Path variable, in idempotent way 
- downloaded detect_ip*ps1 scripts
- [DCOS_OSS-5672](https://jira.mesosphere.com/browse/DCOS_OSS-5672) Remove RunOnce.ps1, start winpanda directly from dcos_install.ps1 w/o reboot
- [DCOS_OSS-5677](https://jira.mesosphere.com/browse/DCOS_OSS-5677) Fix cluster config generation
- [DCOS_OSS-5673](https://jira.mesosphere.com/browse/DCOS_OSS-5673) added Set-EnvPath function for properly handle Path variable, in idempotent way …
> DCOS_OSS-5672: 3 fixes to dcos_install.ps1

- packages/winpanda/extra/src/winpanda/common/storage.py
- packages/winpanda/extra/src/winpanda/common/utils.py
- packages/winpanda/extra/src/winpanda/core/package/manifest.py
- packages/winpanda/extra/src/winpanda/extm/extm.py
1) change supported names of DC/OS package's installation related configuration
files to  <package_name>.<base_extension>.j2 form (e.g. package.extra.j2) to
reflect that fact that they are Jinja2-style templates, and require
rendering procedure to become real pieces of package configuration
2) remove excessive pre-processing of command line string definitions specified
in extra DC/OS package installation options configuration file
3) minor code style fixes
JIRA: DCOS_OSS-5676 - Winpanda App: Fix Recognition Of Configuration File
Templates
- [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short …
> Winpanda App: Fix Recognition Of Configuration File Templates

- gen/dcos-config-win.yaml
- test-e2e/test_groups.yaml
- test-e2e/test_windows.py
Using the `enable_windows_agents: true` configuration to generate Windows configs files creates a `dcos-config-win--setup` package. Although this is unused in Linux, the lack of a `pkginfo.json` in this package causes Linux installation to fail. Add `pkginfo.json` so it succeeds.
Add an e2e test that checks that a Linux-only cluster can be started when Windows agents are enabled. (We don't yet have the capability to create an e2e test that actually tests a Windows agent).
- [https://jira.mesosphere.com/browse/DCOS_OSS-5682](https://jira.mesosphere.com/browse/DCOS_OSS-5682) Creating Windows configuration fails on Linux master. …
> Add pkginfo.json to dcos-config-win package

- fetch_cluster_logs.bash
Use new CLI command to fetch bundle after tests
- [DCOS_OSS-5478](https://jira.mesosphere.com/browse/DCOS_OSS-5478) Use new CLI command to fetch bundle after tests
>  Use new CLI to generate diagnostics bundle

- packages/winpanda/extra/src/winpanda/bin/winpanda.py
- packages/winpanda/extra/src/winpanda/common/cli.py
- packages/winpanda/extra/src/winpanda/common/storage.py
- packages/winpanda/extra/src/winpanda/core/cmdconf.py
- packages/winpanda/extra/src/winpanda/core/command.py
- packages/winpanda/extra/src/winpanda/core/package/manifest.py
- packages/winpanda/extra/src/winpanda/core/package/package.py
- packages/winpanda/extra/src/winpanda/core/rc_ctx.py
- packages/winpanda/extra/src/winpanda/core/utils.py
- packages/winpanda/extra/src/winpanda/extm/extm.py
- packages/winpanda/extra/src/winpanda/svcm/nssm.py
1) decline execution of the NSSM executable verification procedure at service
manager instance creation time to allow the NSSM application itself to be
installed as a regular DC/OS package
2) introduce support for shared executables an sharedd libraries directories
within DC/OS installation storage structure
3) extended the generic resource contex object with elements for DC/OS
installation storage 'work', 'run', 'log', 'bin' and 'lib' directories
4) add support for aggregated DC/OS configuration object
(dcos-config-windows.yaml)
5) refine log messages
JIRA: DCOS_OSS-5687 - Fix placement of the NSSM executable verification procedure
JIRA: DCOS_OSS-5655 - Winpanda App: Add Support For dcos_config_windows.yaml
- …
> Winpanda App: Add Support For dcos-config-windows.yaml

- packages/bootstrap/extra/dcos_internal_utils/bootstrap.py
- packages/bootstrap/extra/dcos_internal_utils/cli.py
- packages/bootstrap/extra/dcos_internal_utils/exhibitor.py
- packages/bootstrap/extra/dcos_internal_utils/utils.py
- packages/bootstrap/extra/tests/test_bootstrap.py
- packages/bootstrap/windows.build.ps1
- packages/bootstrap/windows.buildinfo.json
- tox.ini
Modify DC/OS bootstrap.py to support Windows
- [DCOS_OSS-5698](https://jira.mesosphere.com/browse/DCOS_OSS-5698) Port Open bootstrap.py to Windows
> Add Windows bootstrap package

- gen/build_deploy/powershell/dcos_install.ps1
Winpanda uses default C:\dcos unless inst-root-dir param with value specified. Therefore passing the parameter to call(& python winpanda.py)
- [DCOS_OSS-5689](https://jira.mesosphere.com/browse/DCOS_OSS-5689) Winpanda uses default C:\dcos unless inst-root-dir param with value specified
> DCOS_OSS-5689: [Windows BETA] Winpanda.py vs Dcos_Install.PS1 integration fix.

- packages/bootstrap/extra/dcos_internal_utils/utils.py
Paths read from JSON file must be converted to pathlib Paths.
> Fix type of paths read from JSON file

- packages/winpanda/extra/src/winpanda/cfgm/cfgm.py
- packages/winpanda/extra/src/winpanda/cfgm/exceptions.py
- packages/winpanda/extra/src/winpanda/common/storage.py
- packages/winpanda/extra/src/winpanda/core/command.py
- packages/winpanda/extra/src/winpanda/core/constants.py
- packages/winpanda/extra/src/winpanda/core/package/manifest.py
- packages/winpanda/extra/src/winpanda/core/package/package.py
- packages/winpanda/extra/src/winpanda/docs/PLACEHOLDER.md
> Dcos4windows

- gen/calc.py
- gen/dcos-config-windows.yaml
- gen/tests/test_config.py
Add variables to gen to provide Windows paths
> Add Windows path variables to gen

- owners.json
This PR removes timaa2k and mhrabovcin as an owner of DC/OS.
> Remove timaa2k and mhrabovcin as an owner

- packages/winpanda/extra/src/winpanda/cfgm/cfgm.py
> Do not template files without .j2 suffix

- gen/__init__.py
> Remove dcos-config-windows package from Windows build

- CHANGES.md
- packages/cockroach/build
> [1.13] packages/cockroach: use golang 1.10.8 for build

- CHANGES.md
- packages/mesos/buildinfo.json
Bump Mesos to include a fix for MESOS-9968. (WWWAuthenticate header parsing fails when commas are in (quoted) realm)
- [DCOS-61529](https://jira.mesosphere.com/browse/DCOS-61529) Backport MESOS-9968 to DC/OS 1.13
Tested by mesos unit tests.
> Backport MESOS-9968 to DC/OS 1.13

- CHANGES.md
- packages/mesos/buildinfo.json
Bump Mesos to include a fix for MESOS-9968. (WWWAuthenticate header parsing fails when commas are in (quoted) realm)
- [DCOS-61529](https://jira.mesosphere.com/browse/DCOS-61529) Backport MESOS-9968 to DC/OS 1.13
Tested by mesos unit tests.
> Backport MESOS-9968 to DC/OS 2.0

- packages/winpanda/extra/src/winpanda/common/utils.py
- packages/winpanda/extra/src/winpanda/core/command.py
- packages/winpanda/extra/src/winpanda/svcm/exceptions.py
- packages/winpanda/extra/src/winpanda/svcm/nssm.py
Changes to winpanda to:
1. implement operation retrying helper tools
2. rework the winpanda "start" command to support retrying logic for service start operation
3. change logic of the winpanda "start" command for not to fail entire chain of service start commands, if a single service fails to start
This is slightly updated version of #6628 since changes cannot be made to it without access to the original repo.
- [DCOS_OSS-5731](https://jira.mesosphere.com/browse/DCOS_OSS-5731) Winpanda App: Tolerate Service Start Failures
> Patch anatolii borysov/tolerate service failures

- gen/dcos-config-windows.yaml
Deleted not used paths and fix agent-port and Location for mesos-agent logs in dcos-config-windows.yaml
- [DCOS-ID](https://jira.mesosphere.com/browse/DCOS_OSS-5742) JIRA title / short description.
> Deleted not used paths and fix agent-port and Location for mesos-agent logs in dcos-config-windows.yaml

- gen/build_deploy/powershell/dcos_install.ps1
- [DCOS_OSS-5744](https://jira.mesosphere.com/browse/DCOS_OSS-5744) docs-installer.ps1 should fail if winpanda setup fails
> [BUGFIX] [Windows BETA] DCOS_OSS-5744: dcos_install.ps1

- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
> Add output of `df` to diagnostics bundle

- packages/bootstrap/windows.buildinfo.json
- packages/windows.treeinfo.json
For some reason adding of bootstrap package to the list of packages to be built for variant "windows" has been missed for DC/OS open.
- [DCOS_OSS-5765](https://jira.mesosphere.com/browse/DCOS_OSS-5765) WinpandaApp: Add Bootstrap Package Into Sorted Dependency List.
> updated bootstrap package to be built for windows variant

- packages/winpanda/extra/src/winpanda/core/utils.py
1) add the bootstrap package into internal sorted list of package dependencies
2) improve error reporting
JIRA: DCOS_OSS-5765 - WinpandaApp: Add Bootstrap Package Into Sorted Dependency List
> Winpanda App: Add Bootstrap Package Into Sorted Dependency List

- gen/build_deploy/powershell/dcos_install.ps1
- [DCOS_OSS-5783](https://jira.mesosphere.com/browse/DCOS_OSS-5783) Combine dcos_install URL and version into single URL
> DCOS_OSS-5783: Combine dcos_install URL and version into single URL

- CHANGES.md
- packages/marathon/buildinfo.json
- [DCOS-62078](https://jira.mesosphere.com/browse/DCOS-62078) Marathon launches too many tasks.
- [DCOS_OSS-5679](https://jira.mesosphere.com/browse/DCOS_OSS-5679) Problem with tasks multiplication during application upgrade.
> Bump Marathon to 1.8.232.

- CHANGES.md
- packages/marathon/buildinfo.json
- [MARATHON-2071](https://jira.mesosphere.com/browse/MARATHON-2071) Do not log sensitive information on startup
- [DCOS-62078](https://jira.mesosphere.com/browse/DCOS-62078) Marathon launches too many tasks.  
> Bump Marathon to 1.9.116.

- CHANGES.md
- packages/adminrouter/docker/build-resty.sh
Disable use of SSE4.2 instructions in Admin Router, to allow it to run on older processors.
- [DCOS_OSS-5643](https://jira.mesosphere.com/browse/DCOS_OSS-5643) adminrouter-agent failing to start on older CPUs that are missing SSE 4.2.
We do not have a suitable platform to run no-SSE4.2 tests. We have had confirmation from one of the affected users that this change fixes the problem.
> [2.0] Compile Admin Router without SSE4.2 instructions

- packages/adminrouter/docker/build-resty.sh
Disable use of SSE4.2 instructions in Admin Router, to allow it to run on older processors.
- [DCOS_OSS-5643](https://jira.mesosphere.com/browse/DCOS_OSS-5643) adminrouter-agent failing to start on older CPUs that are missing SSE 4.2.
> Compile Admin Router without SSE4.2 instructions

- .gitlint
- .pre-commit-config.yaml
- README.md
This commits adds a configuration file for the `pre-commit`
git hook lifecycle management framework. It is used to
run various linting checks on all git commits.
In particular, initially we check that all commit messages
start with an uppercase letter, no line exceeds 72 characters,
that all executables have valid shebangs, and that no non-ascii
characters are introduced accidentallu.
To enable pre-commit for this repository, first pre-commit must
be installed
pip3 install pre-commit
and afterwards the following commands must be run once in the
the root folder of the git repository:
pre-commit install --install-hooks --hook-type pre-commit
pre-commit install --install-hooks --hook-type commit-msg
Subsequent changes to the linter configuration will be picked
up automatically.
For more …
> Added linting for DC/OS commits.

- packages/dcos-integration-test/extra/test_metrics.py
This test started failing after the latest alpine image was bumped to 3.11. I haven't identified the change that causes the failure, and similar tests in the same file continue to work. Pinning to the previous version to keep the test working.
- [DCOS-62478](https://jira.mesosphere.com/browse/DCOS-62478) open_source_tests/test_metrics.py test_metrics_agent_statsd Expected statsd metrics not found
> [master] Fix test_metrics

- mergebot-config.json
Make the `teamcity/dcos/build/tox/windows` a required test. It rarely fails and we want to detect if a PR makes it fail.
> Require Windows tox tests to pass

- packages/winpanda/extra/pytest.ini
- packages/winpanda/extra/src/winpanda/README.md
- tox.ini
Add docs on how to test winpanda code, and avoid hitting top-level `conftest.py`.
> Document how to test winpanda

- gen/dcos-config-windows.yaml
- [DCOS_OSS-5806](https://jira.mesosphere.com/browse/DCOS_OSS-5806) Update log location
> Update log location (DCOS_OSS-5806)

- packages/dcos-integration-test/extra/test_metrics.py
This test started failing after the latest alpine image was bumped to 3.11. I haven't identified the change that causes the failure, and similar tests in the same file continue to work. Pinning to the previous version to keep the test working.
This is a back-port of #6697 - as this branch has not had a recent update, you can see that the failure occurs in the first commit and is fixed in the second.
- [DCOS-62478](https://jira.mesosphere.com/browse/DCOS-62478) open_source_tests/test_metrics.py test_metrics_agent_statsd Expected statsd metrics not found
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to …
> [2.0] Fix metrics test

- packages/dcos-integration-test/extra/test_metrics.py
This test started failing after the latest alpine image was bumped to 3.11. I haven't identified the change that causes the failure, and similar tests in the same file continue to work. Pinning to the previous version to keep the test working.
This is a backport of #6697 - as this branch has not had a recent update, you can see that the failure occurs in the first commit and is fixed in the second.
- [DCOS-62478](https://jira.mesosphere.com/browse/DCOS-62478) open_source_tests/test_metrics.py test_metrics_agent_statsd Expected statsd metrics not found
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to …
> [1.13] Fix test_metrics

- packages/calico/README.md
Add documentation for Calico networking in DC/OS, including components introduced, configurations exposed to the operators, network policy explanation and examples.
As calico for docker runtime is still in discussion, we don't include this feature related doc here.
- [DCOS-58586](https://jira.mesosphere.com/browse/DCOS-58586) document for Calico in DC/OS
> add doc for calico networking in DC/OS

- packages/winpanda/extra/src/winpanda/common/utils.py
- packages/winpanda/extra/src/winpanda/tests/test_common_utils.py
Add tests for winpanda subprocess functions
> Add Windows run process tests

- packages/java/build
- packages/java/buildinfo.json
Update JDK to OpenJDK 8u232, to undo the regression in versions introduced during the change from Oracle to OpenJDK.
- [DCOS-62548](https://jira.mesosphere.com/browse/DCOS-62548) COPS-5738: Rationale behind an old version of Java
> Update JDK to OpenJDK 8u232

- CHANGES.md
- packages/java/build
- packages/java/buildinfo.json
Update JDK to OpenJDK 8u232, to undo the regression in versions introduced during the change from Oracle to OpenJDK.
- [DCOS-62548](https://jira.mesosphere.com/browse/DCOS-62548) COPS-5738: Rationale behind an old version of Java
> [2.0] Update JDK to OpenJDK 8u232

- CHANGES.md
- packages/marathon/buildinfo.json
This bump includes a simple bug fix that enable pod status reports for task with `TASK_UNKOWN`
status.
- [MARATHON-8710](https://jira.mesosphere.com/browse/MARATHON-8710) Marathon hides resident pod instances with task status TASK_UNKNOWN from /v2/pods/::status
> Bump Marathon to 1.9.118 on 2.0

- CHANGES.md
- packages/adminrouter/docker/Dockerfile
HTTP/2 will be enabled in DC/OS 2.1 for Calico support. OpenResty 1.15.8.2 is a patch release addressing security vulnerabilities in the HTTP/2 protocol which may cause excessive memory consumption and CPU usage
- [DCOS-61159](https://jira.mesosphere.com/browse/DCOS-61159) Upgrade OpenResty to 1.15.8.2.
> Update OpenResty to 1.15.8.2

- gen/dcos-config-windows.yaml
- packages/adminrouter/extra/src/nginx.agent.windows.conf
- packages/adminrouter/windows.build.ps1
The PR adds two files to dcos-config-windows.yaml and change nginx config windows platform.
- [DCOS_OSS-5834](https://jira.mesosphere.com/browse/DCOS_OSS-5834) JIRA title / short description.
> Fix adminrouter config

- CHANGES.md
- packages/marathon/buildinfo.json
- [MARATHON-8710](https://jira.mesosphere.com/browse/MARATHON-8710) Marathon hides resident pod instances with task status TASK_UNKNOWN from /v2/pods/::status.
> Bump Marathon to 1.8.233.

- CHANGES.md
- packages/dcos-integration-test/requirements.txt
- packages/python-kazoo/buildinfo.json
Version 2.4 of Kazoo uses `async` as a function parameter name. In Python 3.7 this becomes a keyword. Upgrade Kazoo to 2.6.1 to prevent this conflict.
- [DCOS-63065](https://jira.mesosphere.com/browse/DCOS-63065) Integration tests use async keyword for parameters
> Update Kazoo to 2.6.1

- packages/mesos/extra/mesos.nssm.j2
Added NSSM stdout/stderr redirect for mesos-agent service.
Added Mesos-Agent dependency on Docker service
Truncated log_dir parameter
(Enterprise build due to conflict at https://github.com/mesosphere/dcos-enterprise/pull/7191, therefore submitted new PR )
- [DCOS_OSS-5811](https://jira.mesosphere.com/browse/DCOS_OSS-5811) added NSSM stdout/stderr redirect for mesos-agent service
> [NEW PR] DCOS_OSS-5811: added NSSM stdout/stderr redirect for mesos-agent service

- gen/calc.py
- packages/dcos-integration-test/extra/test_dcos_log.py
- packages/mesos/extra/make_disk_resources.py
- test-e2e/test_master_node_replacement.py
Single backslashes in Python strings display a warning in Python 3.6 when they are not followed by a string escape character. Previously these were accepted and passed through, so were commonly used in regex's.
Now that we are using Python 3.6 in more places (e.g. Windows) we see these warnings, and will soon see errors. Fix these to eliminate noise while debugging other problems.
- [DCOS-63183](https://jira.mesosphere.com/browse/DCOS-63183) Replace incorrect regex escapes
> Update regex escapes to use raw strings

- packages/winpanda/extra/src/winpanda/svcm/nssm.py
1) introduce event hooks configuration options for NSSM configuration file
JIRA: DCOS_OSS-5632 - Winpanda App: Add Support For Pre/Post Actions For
Start/Stop Events For Windows Services
> Winpanda App: Add Event Hooks Support For Windows Services

- gen/build_deploy/powershell/dcos_install.ps1
- [DCOS_OSS-5855](https://jira.mesosphere.com/browse/DCOS_OSS-5855) copy fault-domain-detect-win.ps1 from \bootstrap to \bin
> copy fault-domain-detect-win.ps1 to \bin (DCOS_OSS-5855)

- packages/winpanda/extra/src/winpanda/README.md
- packages/winpanda/extra/src/winpanda/tests/test_common_utils.py
- packages/winpanda/extra/src/winpanda/tests/test_svcm_nssm.py
Add tests for #6774 - these tests were added during review and were not added to the original PR because it was in an external repo.
> Add NSSM Service Manager tests

- CHANGES.md
- gen/build_deploy/bash.py
See https://github.com/dcos/dcos/pull/5766
https://jira.mesosphere.com/browse/DCOS-59406
> Backport of #5766

- pkgpanda/__init__.py
To reduce warnings and errors for newer versions of Python, we need to ensure regexes use raw strings. #6787 fixed most of these, but missed `\-` and `\]`. 
- [DCOS-63183](https://jira.mesosphere.com/browse/DCOS-63183) Replace incorrect regex escapes
> Escape backslash-hypen in regex

- dcos_installer/upgrade.py
- gen/build_deploy/bash.py
- packages/exhibitor/extra/start_exhibitor.py
Ensure more Python string escapes are represented correctly for Python 3.7
- [DCOS-63183](https://jira.d2iq.com/browse/D2IQ-63183) Replace incorrect regex escapes
> Ensure Python backslashes are doubled or in raw strings

- packages/winpanda/extra/src/winpanda/core/cmdconf.py
1) refactor the DC/OS Aggregated Config fetch/preprocess function
2) implement error handling/reporting for individual fetch/preprocess steps
3) refine existing error messages
JIRA: DCOS_OSS-5849 - Winpanda App: Improve Error Handling For DC/OS
Aggregated Config Fetch/Preprocess Procedure
> Winpanda App: Improve DC/OS Aggregated Config Fetch/Preprocess Err Handling

- gen/build_deploy/powershell/dcos_install.ps1
Windows dcos_install.ps1 must throw an error if DC/OS already installed
- [DCOS_OSS-5850](https://jira.mesosphere.com/browse/DCOS_OSS-5850) Windows dcos_install.ps1 must throw an error if DC/OS already installed
> DCOS_OSS-5850: 1) throw error when 2nd time dcos_install.ps1 run; 2) re-factored logging

- gen/build_deploy/powershell/dcos_generate_config_win.sh.in
at ./genconf/config.yaml before unpack DC/OS Win installer
- [DCOS_OSS-5894](https://jira.mesosphere.com/browse/DCOS_OSS-5894)  verify 'enable_windows_agents: true'
> [Windows BETA] DCOS_OSS-5894: verify 'enable_windows_agents: true'

- CHANGES.md
- [DCOS_OSS-5909](https://jira.mesosphere.com/browse/DCOS_OSS-5909) Mesos CI bumpbot fails to build DC/OS 1.12, 1.13
> Fixed mesos-ci build.

- packages/dcos-integration-test/extra/test_mesos.py
- [DCOS-61186](https://jira.mesosphere.com/browse/DCOS-61186) Write end-to-end test for domain socket support
> Add test validating domain sockets are used for executor communication

- packages/adminrouter/docker/Dockerfile
Pin virtualenv to pre-v20 to prevent failure to build AR container
- [https://jira.d2iq.com/browse/DCOS_OSS-5914](https://jira.d2iq.com/browse/DCOS_OSS-5914) virtualenv 20 fails
> Pin virtualenv

- packages/winpanda/extra/src/winpanda/common/storage.py
- packages/winpanda/extra/src/winpanda/core/cmdconf.py
- packages/winpanda/extra/src/winpanda/core/command.py
- packages/winpanda/extra/src/winpanda/core/rc_ctx.py
- packages/winpanda/extra/src/winpanda/tests/test_core_command.py
Add a test for Winpanda templating of dcos-config-windows.yaml.
Changes to code:
- Removed use of `drive` in file structure. This is not used to any benefit. Removing this enables the new test to run on Linux, which makes cross-platform testing simpler. Also, some Windows paths can have an empty drive value (e.g. UNC).
- Fixed JSON escaping. Previously, it stripped double-quotes from the escaped value. This broke when a string ended in a double-quote (e.g. `"\"hello\""` became `\"hello\` instead of `\"hello\"`).
- Stopped using JSON escapes for `dcos-config-windows.yaml`. Since escaping is already available for relevant bootstrap variables, e.g. `windows_dcos_install_path_json` this led to double-escaping in the final file.
The test identified two outstanding problems, which are most …
> Add Winpanda dcos-config-windows template tests

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
-  D2IQ-63973 -  Set the development version to 2.1.0-beta2-dev
> Set the development version to 2.1.0-beta2-dev

- CHANGES.md
- gen/build_deploy/aws.py
Update Core OS AMIs to latest stable version.
- [D2IQ-64271](https://jira.d2iq.com/browse/D2IQ-64271) Upgrade core os AMIs.
> update to latest stable CoreOS AMIs

- README.md
Provide windows artifact download locations.
> Adding windows artifact urls

- CHANGES.md
- gen/cloud-config.yaml
Backport of #6006 
Remove the increased journald rate limit. Scale testing demonstrates that the raised limit causes problems for other components that get delayed or lost logs. Logging that exceeds the default indicates that a component is logging excessively, and should be remedied in that component.
- [DCOS-53763](https://jira.mesosphere.com/browse/DCOS-53763) "too many" Admin Router access log lines went missing in MWST 15
> [1.13] Revert to default journald rate limit

- CHANGES.md
- gen/cloud-config.yaml
Backport of #6006 
Remove the increased journald rate limit. Scale testing demonstrates that the raised limit causes problems for other components that get delayed or lost logs. Logging that exceeds the default indicates that a component is logging excessively, and should be remedied in that component.
- [DCOS-53763](https://jira.mesosphere.com/browse/DCOS-53763) "too many" Admin Router access log lines went missing in MWST 15
> [1.12] Revert to default journald rate limit

- CHANGES.md
- packages/telegraf/extra/tools/migrate_containers_dir.sh
Backport of #6880 
The Telegraf migration script fails if there are no containers in the legacy directory. Handel this case correctly.
- [D2IQ-64507](https://jira.d2iq.com/browse/D2IQ-64507) COPS-5868: Unable to launch UCR containers after upgrade from 1.11->1.13
> [2.0] Do not chmod files when no files exist

- CHANGES.md
- packages/telegraf/extra/tools/migrate_containers_dir.sh
The Telegraf migration script fails if there are no containers in the legacy directory. Handel this case correctly.
- [D2IQ-64507](https://jira.d2iq.com/browse/D2IQ-64507) COPS-5868: Unable to launch UCR containers after upgrade from 1.11->1.13
> Do not chmod files when no files exist

- CHANGES.md
- packages/telegraf/extra/tools/migrate_containers_dir.sh
Backport of #6880 
The Telegraf migration script fails if there are no containers in the legacy directory. Handel this case correctly.
- [D2IQ-64507](https://jira.d2iq.com/browse/D2IQ-64507) COPS-5868: Unable to launch UCR containers after upgrade from 1.11->1.13
> [1.13] Do not chmod files when no files exist

- test-e2e/test_master_node_replacement.py
- test-e2e/test_zookeeper_backup.py
Log output for installer run during e2e tests. This output is important when the installer fails.
- [D2IQ-64620](https://jira.d2iq.com/browse/D2IQ-64620) Some e2e tests do not log errors from bootstrap installer
> Capture output for e2e test installers

- gen/dcos-config.yaml
- packages/mesos/extra/dcos-mesos-slave-public.service
- packages/mesos/extra/dcos-mesos-slave.service
Mesos Agent can not create a unix domain socket due to incompatibilities with systemd provided in CoreOS. For more deals, see https://jira.d2iq.com/browse/D2IQ-63177?focusedCommentId=319969#comment-319969 and https://issues.apache.org/jira/browse/MESOS-10098
- [D2IQ-63177](https://jira.d2iq.com/browse/D2IQ-63177) AWS CloudFormation Simple test failing in cluster launch step
> Fixed domain sockets creation on CoreOS via systemd.

- packages/dcos-integration-test/README.md
- packages/dcos-integration-test/extra/test_groups.yaml
- packages/dcos-integration-test/extra/test_windows.py
- test_util/README.md
This fixes the Windows test bug that merged somehow. It also documents how to configure
test clusters launched with Terraform.
> Fix Windows test and document cluster parameters.

- gen/dcos-config.yaml
- packages/marathon/build
- packages/marathon/extra/marathon.sh
It's easier to mantain config when it's in a single place.
This change moves configuration from marathon.sh to dcos-config.yaml.
> Move defaults to dcos-config.yaml

- pkgpanda/__init__.py
- pkgpanda/cli.py
- pkgpanda/test_setup.py
- pkgpanda/util.py
- https://jira.d2iq.com/browse/COPS-5428.
> Add more logs to pkgpanda

- build_genconf_windows.ps1
- dcos_installer/backend.py
- dcos_installer/cli.py
- dcos_installer/config_util.py
- dcos_installer/test_cli.py
- dcos_installer/upgrade_win.py
- gen/build_deploy/bash.py
- gen/build_deploy/powershell.py
- gen/build_deploy/powershell/dcos_install.ps1.in
- gen/build_deploy/powershell/dcos_node_upgrade.ps1.in
- setup.py
There is set of JIRAs under epic D2IQ-61891 : Support Windows Node Update which covers:
- templatizing dcos_install.ps1 and adding bootstrap_url/masters as gen_out arguments.
- pass generation of dcos_install.ps1 to gen.build_deploy.powershell.py
- created a template for dcos_node_upgrade and similarly to upgrade.py such put into upgrade_win.py
- generation of dcos_node_upgrade.py using upgrade_win.py
- [D2IQ-61891](https://jira.d2iq.com/browse/D2IQ-61891) EPIC to Support Windows Node Update (Jon Giddy)
- [D2IQ-64278](https://jira.d2iq.com/browse/D2IQ-64278) Fill up functionality requires in dcos_node_upgrade.ps1/.py (Vadym Zagorodko)
- [D2IQ-64275](https://jira.d2iq.com/browse/D2IQ-64275) Create …
> [Windows Upgrade] EPIC D2IQ-61891 : Support Windows Node Update - improved

- test_util/terraform_init.sh
> use standalone version for aws-spot-instance

- packages/metronome/build
Use the same build script in OSS and EE. This allows us to remove metronome package from EE since it will differ only on configuration.
> Unify metronome build script

- Jenkinsfile
This migrates the Adminrouter build to a declarative Jenkins pipeline. This enables us to add
other stages and build steps faster in the future.
> Define declarative Jenkins pipeline.

- gen/calc.py
- gen/dcos-config.yaml
- packages/adminrouter/docker/Dockerfile
- packages/adminrouter/docker/adminrouter-grpc-proxy-port.conf
- packages/adminrouter/extra/src/nginx.master.conf
- test-e2e/requirements.txt
- test-e2e/test_adminrouter_grpc.py
- test-e2e/test_e2e_module.py
- test-e2e/test_groups.yaml
- test-e2e/test_service_account.py
Adds a configuration option to change the AdminRouter gRPC proxy port.
- [D2IQ-61007](https://jira.d2iq.com/browse/D2IQ-61007) Make the gRPC socket port configurable via install config param.
> adminrouter: make grpc proxy port configurable

- packages/winpanda/extra/src/winpanda/core/utils.py
- packages/winpanda/extra/src/winpanda/tests/unit/test_core_utils.py
Add decorator common.utils.exception_handler for rc_load_json, rc_load_ini and rc_load_yaml for better maintainability and decrease code duplication.
- [D2IQ-65069](https://jira.d2iq.com/browse/D2IQ-65069) Add decorator common.utils.exception_handler for rc_load_json, rc_load_ini and rc_load_yaml.
> Add decorator common.utils.exception_handler for rc_load_… functions

- packages/winpanda/extra/src/winpanda/README.md
- packages/winpanda/extra/src/winpanda/cfgm/cfgm.py
- packages/winpanda/extra/src/winpanda/tests/unit/test_cfgm_cfgm.py
winpanda deletes the `<install>/etc/<package>` directory during installation. This prevents config files being placed there from either the package `etc` folder or from other packages.
We need this to allow dynamic Mesos modules to be positioned correctly.
This change removes the deletion of the directories. Any cleanup of these directories must be done before the installation process starts.
- [https://jira.d2iq.com/browse/D2IQ-65261](https://jira.d2iq.com/browse/D2IQ-65261) Do not remove files from etc directory in Windows …
> Keep existing configuration files during installation

- gen/dcos-config-windows.yaml
- packages/dcos-integration-test/extra/test_metrics.py
Add dcos-diagnostics to telegraf inputs on Windows.
Fix test_metrics to work even if diagnostic bundle was not generated.
> Gather metrics from dcos diag on windows

- CHANGES.md
- packages/dcos-net/buildinfo.json
---
↩️  _This PR back-ports  #6962 to 1.13._
---
Bump dcos-net to include changes that allow for graceful shutdown of connections by changing the VIP backend weight to `0` when tasks are unhealthy or enter the `TASK_KILLING` state instead of removing them.
- [D2IQ-61077](https://jira.d2iq.com/browse/D2IQ-61077) Improve connection shutdown behavior.
> D2IQ-61077: Adjust l4lb task state handling

- gen/build_deploy/powershell/dcos_node_upgrade.ps1.in
…emplate
While testing latest Winpanda Upgrade functionality, there was found missing "start" action. Therefore goal of the PR to add "winpanda.py start" cmd to dcos_node_upgrade.ps1 template
- [D2IQ-65474](https://jira.d2iq.com/browse/D2IQ-65474) dcos_node_upgrade.ps1 - missing start command
> [Windows GA] D2IQ-65474 : added winpanda.py start cmd to dcos_node_upgrade.ps1 template

- packages/winpanda/extra/src/winpanda/cfgm/cfgm.py
- packages/winpanda/extra/src/winpanda/common/logger.py
- packages/winpanda/extra/src/winpanda/common/storage.py
- packages/winpanda/extra/src/winpanda/common/utils.py
- packages/winpanda/extra/src/winpanda/core/cmdconf.py
- packages/winpanda/extra/src/winpanda/core/command.py
- packages/winpanda/extra/src/winpanda/core/istate.py
- packages/winpanda/extra/src/winpanda/core/package/id.py
- packages/winpanda/extra/src/winpanda/core/package/manifest.py
- packages/winpanda/extra/src/winpanda/core/package/package.py
- packages/winpanda/extra/src/winpanda/core/rc_ctx.py
- packages/winpanda/extra/src/winpanda/core/template.py
- packages/winpanda/extra/src/winpanda/core/utils.py
- packages/winpanda/extra/src/winpanda/dstor/http.py
- packages/winpanda/extra/src/winpanda/extm/extm.py
- packages/winpanda/extra/src/winpanda/svcm/base.py
- packages/winpanda/extra/src/winpanda/svcm/nssm.py
- packages/winpanda/extra/src/winpanda/tests/unit/test_core_utils.py
- packages/winpanda/extra/src/winpanda/tests/unit/test_extm_extm.py
- tox.ini
Introduce passive code checks implement an optional static type checker for Python.
- [D2IQ-64328](https://jira.d2iq.com/browse/D2IQ-64328) Introduce passive code checks.
> Introduce passive code checks

- packages/adminrouter/docker/requirements-tests.txt
psutil (aka python-psutil) through 5.6.5 can have a double free. This occurs because of refcount mishandling within a while or for loop that converts system data into a Python object.
* https://github.com/advisories/GHSA-qfc5-mcwq-26q8
* https://nvd.nist.gov/vuln/detail/CVE-2019-18874
>  Double Free in psutil

- test_util/main.tf
* https://jira.d2iq.com/browse/D2IQ-65565
Terraform delete was failing with
```
[10:22:18]Step 3/3: make destroy (Command Line) (1s)
[10:22:18]Starting: /teamcity/temp/agentTmp/custom_script5821832035693021883
[10:22:18]in directory: /teamcity/work/f76365414248b6de
[10:22:18]./terraform destroy -auto-approve;
[10:22:20]
[10:22:20]Error: Error asking for user input: 1 error occurred:
[10:22:20]	* module.dcos.module.dcos-infrastructure.local.ssh_key_content: local.ssh_key_content: file: open /root/.ssh/id_rsa.pub: no such file or directory in:
[10:22:20]
[10:22:20]${var.ssh_public_key_file == "" ? var.ssh_public_key : file(local.ssh_public_key_file)}
```
> Provide the correct key to main.tf

- packages/telegraf/buildinfo.json
- packages/telegraf/windows.buildinfo.json
Bump to latest telegraf to incorporate https://github.com/dcos/telegraf/pull/63
- [COPS-5629](https://jira.d2iq.com/browse/COPS-5629) Telegraf saturates CPU on agents
> Bump Telegraf

- packages/bootstrap/extra/dcos_internal_utils/utils.py
- packages/winpanda/extra/src/winpanda/common/utils.py
- packages/winpanda/extra/src/winpanda/core/command.py
- packages/winpanda/extra/src/winpanda/requirements.txt
- packages/winpanda/extra/src/winpanda/tests/integration/test_command_state.py
- packages/winpanda/windows.buildinfo.json
Add atomic writes of files in Windows to `bootstrap.py` and `winpanda`. We use different methods for each. In `bootstrap.py` we use our hand-rolled version that does not fsync. In winpanda, we use a third-party library that always fsyncs.
Use this to provide winpanda with a safe implementation of files to save in-progress state. This is basically a one-word database on the filesystem, hence the need for fsync.
Make `winpanda setup` store and detect state file, and fail if a state file exists. This means that `winpanda setup` only works when the installation was not in an intermediate state previously.
Later, we plan to recover from intermediate states,  to allow installation to proceed safely.
- [D2IQ-65526](https://jira.d2iq.com/browse/D2IQ-65526) Create winpanda state file code
- …
> winpanda setup state files

- CHANGES.md
- packages/openssl/buildinfo.json
Update to latest version of OpenSSL for Linux.
Back-port of #7002 
- [D2IQ-65604](https://jira.d2iq.com/browse/D2IQ-65604) Bump OpenSSL to 1.1.1d
> [2.0] Update to OpenSSL 1.1.1d

- CHANGES.md
- packages/openssl/buildinfo.json
Update to latest version of OpenSSL for Linux. This matches the version we are using on Windows.
- [D2IQ-65604](https://jira.d2iq.com/browse/D2IQ-65604) Bump OpenSSL to 1.1.1d
> Update to OpenSSL 1.1.1d

- pkgpanda/docker/dcos-builder/Dockerfile
> Bump Go to 1.14

- test_util/Makefile
- test_util/README.md
- test_util/main.tf
This change allow customizing terraform with variables.
> Move hardcoded values to variables.

- test_util/Makefile
This just corrects some merging errors.
> Pass DC/OS license to EE cluster creation.

- packages/dcos-integration-test/extra/test_metrics.py
Skip metrics tests that requires dcos_metrics output configured on telegraph since is not supported on Windows.
See:
* https://github.com/dcos/telegraf/blame/d3666e/plugins/outputs/dcos_metrics/README.md#L5
* https://jira.d2iq.com/browse/D2IQ-65777
* https://jira.d2iq.com/browse/D2IQ-65401
- [D2IQ-65708](https://jira.d2iq.com/browse/D2IQ-65708) 
> Skip metrics tests on Windows.

- packages/dcos-integration-test/extra/test_metrics.py
Calico and Overlay is currently not supported on Windows.
- [D2IQ-65708](https://jira.d2iq.com/browse/D2IQ-65708) 
> Do not run calico and overlay metrics test on Windows

- packages/calico/README.md
This PR is based on this PR: https://github.com/dcos/dcos/pull/6980 The difference is that some review comments have been incorporated.
- [D2IQ-62521](https://jira.d2iq.com/browse/D2IQ-62521) Add doc to replace DC/OS overlay with Calico
> Add doc to replace dcos overlay with calico network

- packages/dcos-integration-test/extra/test_metrics.py
FluentBit, statsd and executor metrics are not supported on Windows Agent.
- [D2IQ-65708](https://jira.d2iq.com/browse/D2IQ-65708) 
> Skip unsupported metrics tests on windows

- packages/winpanda/extra/src/winpanda/common/storage.py
- packages/winpanda/extra/src/winpanda/common/utils.py
- packages/winpanda/extra/src/winpanda/core/cmdconf.py
- packages/winpanda/extra/src/winpanda/requirements.txt
- packages/winpanda/extra/src/winpanda/tests/integration/test_common_utils.py
- packages/winpanda/extra/src/winpanda/tests/unit/test_common_utils.py
- packages/winpanda/windows.buildinfo.json
pySmartDL uses threads to download a file. We wait for the thread to terminate. So we can just as easily use the `requests` package.
We see an error using `pySmartDL`: `cannot join thread before it is started` so let's just replace it.
- [DCOS_OSS-5813](https://jira.d2iq.com/browse/DCOS_OSS-5813) Windows pySmartDL RuntimeError: cannot join thread before it is started
> Replace pySmartDL with requests package

- test_util/main.tf
https://mesosphere.slack.com/archives/CHPEMR8VA/p1584906404252700
> Use the latest Ansible bundled container for Windows GA deployments

- mergebot-config.json
> Mark Windows integration test required

- packages/dcos-integration-test/extra/test_metrics.py
This tests are not working on Windows.
If we run Windows only cluster they are failing.
- [D2IQ-65708](https://jira.d2iq.com/browse/D2IQ-65708)
- [D2IQ-65403](https://jira.mesosphere.com/browse/D2IQ-65403) enable adminrouter metrics on Windows.
> Skip unsupported metrics tests

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
> Update 2.0 with 2.0.4-dev

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- packages/dcos-integration-test/extra/test_helpers.py
- packages/dcos-integration-test/extra/test_metrics.py
- packages/dcos-integration-test/extra/test_windows.py
- test_util/main.tf
In order to really test Windows agents we need to ensure that they are hit by tests we are running. To do that we need to remove private Linux nodes and run tests only on Windows node.
We can't remove Linux public nodes since this results in tests not starting at all.
This PR fixes dcos-diagnostics tests to accept clusters without Linux private nodes and to use Docker App that's running on Windows and Linux.
This PR skip couple of metrics tests since statsd metrics are not working on Windows and apps used in tests do not run on Windows.
Fises: 
- [D2IQ-65996](https://jira.d2iq.com/browse/D2IQ-65996)
- [D2IQ-66051](https://jira.mesosphere.com/browse/D2IQ-66051)
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then …
> Run Windows tests without Linux

- build_local_windows.ps1
Set the cache headers on Windows installers, so that they do not get cached in CloudFront.
This replaces the change made in https://github.com/dcos/dcos/pull/7051 which had no effect.
- [D2IQ-65806](https://jira.d2iq.com/browse/D2IQ-65806) Windows Enterprise installer does not get updated after first commit
> Use HeaderCollection to set installer caching

- packages/marathon/extra/marathon.sh
!--
Please fill in the applicable sections of this template, remove any default text which is not applicable and provide a cohesive, readable pull request description.
This template has some special rules embedded.
1. Mergebot parses JIRA tickets listed in the title of the PR, in the High-Level Description and Corresponding DC/OS tickets (Required) section. Fix Version field of those JIRA tickets is updated upon merge of this PR.
2. Fix Version field will not be updated for the JIRA tickets listed in Related tickets (optional) section.
3. A comment is added to any JIRA tickets mentioned in the title or description upon merge of this PR.
-->
Fixes: https://github.com/dcos/dcos/commit/bb39a48aa6b1fa77a0efc7e892be756ff137b736#r38060488
- [D2IQ-ID](https://jira.d2iq.com/browse/D2IQ-ID) JIRA …
> Do not overwrite env if was set by a user.

- CHANGES.md
- dcos_installer/test_backend.py
- gen/__init__.py
- gen/build_deploy/aws.py
- gen/build_deploy/azure.py
- gen/build_deploy/bash.py
- gen/calc.py
- gen/tests/test_config.py
- gen/tests/test_validate.py
- gen/tests/utils.py
- packages/calico/README.md
_Imported and rebased https://github.com/dcos/dcos/pull/6633_
This PR set the `calico_network_cidr` default to be `172.29.0.0/16`. Overlapped subnets of calico and infrastructure may bring unrecoverable/tremendous problems into the infrastructure especially for an on-premise environment.
This PR is blocked by the task described in [DCOS-62550](https://jira.mesosphere.com/browse/DCOS-62550), which make calico configurations configurable through terraform.
Also, before we can turn all tests into green, we need to first `addcalico_network_cidr` into main.tf defined in teamcity project.
- [DCOS-60734](https://jira.d2iq.com/browse/D2IQ-60734) make calico-network-cidr mandatory to set by the operator
This PR is currently blocked my this task
- …
> Default calico network CIDR

- gen/build_deploy/azure.py
- gen/build_deploy/powershell/dcos_install.ps1.in
- gen/calc.py
- gen/dcos-config-windows.yaml
- gen/dcos-config.yaml
- gen/ip-detect/azure.ps1
- packages/winpanda/extra/src/winpanda/bin/winpanda.py
- packages/winpanda/extra/src/winpanda/cfgm/cfgm.py
- packages/winpanda/extra/src/winpanda/common/utils.py
- packages/winpanda/extra/src/winpanda/core/cmdconf.py
- packages/winpanda/extra/src/winpanda/core/command.py
- packages/winpanda/extra/src/winpanda/core/package/package.py
- packages/winpanda/extra/src/winpanda/core/rc_ctx.py
- setup.py
Move ip-detect and fault-domain handling out of dcos-install.ps1 and into dcos-config-windows.yaml. This is closer to the Linux way of doing things.
With this change it becomes easier for the universal installer to set the contents of these files and to ensure that these files are recreated correctly after a failure in `winpanda setup`.
- [D2IQ-65527](https://jira.d2iq.com/browse/D2IQ-65527) Handle winpanda setup from INSTALLING state
> Move ip-detect and fault-domain into dcos-config-windows.yaml

- packages/dcos-integration-test/extra/test_metrics.py
tests are failing and sometimes needs more than 3 minutes https://teamcity.mesosphere.io/viewLog.html?buildId=2670899&buildTypeId=DcOs_Enterprise_Test_Inte_AwsOnpremWStaticBackendAndSecurityStrictGroup1Terraf_2
> change metrics test timeout to 4 minutes

- packages/etcd/extra/etcdctl/dcos_etcdctl.py
- packages/exhibitor/extra/dcos_zk_backup.py
A change from the etcd code derived from ZK code was wrongly applied backj to the ZK code. This PR makes things good again. And simplifies the etcd code slightly too.
- [D2IQ-66238](https://jira.d2iq.com/browse/D2IQ-66238) ZK backup script decodes command output incorrectly
> Fix types for printing command errors

- CHANGES.md
- packages/adminrouter/extra/src/README.md
- packages/adminrouter/extra/src/includes/http/common-windows.conf
- packages/adminrouter/extra/src/includes/http/common.conf
- packages/adminrouter/extra/src/lib/auth/common.lua
- packages/adminrouter/extra/src/lib/auth/open.lua
- packages/adminrouter/extra/src/lib/cache.lua
- packages/adminrouter/extra/src/test-harness/modules/generic_test_code/generalised_tests.py
- packages/adminrouter/extra/src/test-harness/tests/test_auth.py
- packages/adminrouter/extra/src/test-harness/tests/test_boot_envvars.py
- packages/adminrouter/extra/src/test-harness/tests/test_cache.py
Reduce the size of Admin Router logs, while keeping the info conveyed the same or improved.
The additional info helps with debugging, especially with calls coming in on the GRPC port for Calico.
The reduced size helps avoid lost logs when journald traffic is high.
- [D2IQ-43957](https://jira.d2iq.com/browse/D2IQ-43957) Investigate what log messages that `Admin Router` emits can be safely dropped to decrease amount of logs
- [D2IQ-62839](https://jira.d2iq.com/browse/D2IQ-62839) Add host and scheme to AR access_log
> Update Admin Router logs

- packages/winpanda/extra/src/winpanda/svcm/nssm.py
When a Windows node is under heavy load, the NSSM check timeout of 5 seconds can be reached. Increase the timeout to 15 seconds, since waiting a bit longer is preferable to having installation fail.
> Increase timeout for NSSM test

- docs/admin-ports.md
- gen/build_deploy/bash.py
dcos-oauth was replaced by dcos-bouncer in 1.13 - modify some references to it.
- [D2IQ-60470](https://jira.d2iq.com/browse/D2IQ-60470) Remove references to dcos-oauth
> Modify references to dcos-oauth to dcos-bouncer

- CHANGES.md
- packages/calico/build
- packages/calico/extra/calico-cni-wrapper.go
- packages/dcos-integration-test/extra/test_networking.py
This PR provides a temporary fix to D2IQ-62219 by compressing the network labels passed to the calico CNI plugin. This is considered "temporary" since it should eventually be fixed on marathon, after the proper design review phase.
This PR includes:
- Modifications to the `build` script to install a golang build environment, since we are building within the `calico/node:v3.8.2` image that does not have it
- Addition of the `calico-cni-wrapper.go`, designed not to have any additional golang dependency and to simply wrap the actual CNI plugin and translate the STDIN 
- [D2IQ-62219](https://jira.d2iq.com/browse/D2IQ-62219) Marathon task app label length is too long for calico CNI.
_None_ …
> Adding CNI wrapper to fix D2IQ-62219 on calico-side

- test-e2e/test_external_calicoctl.py
- test-e2e/test_groups.yaml
Add tests for accessing calico from outside the cluster.
- [D2IQ-61011](https://jira.d2iq.com/browse/D2IQ-61011) DC/OS integration tests for accessing calicoctl from outside of the cluster
> e2e: add external calico tests

- CHANGES.md
- gen/dcos-config.yaml
- packages/dcos-integration-test/extra/test_metrics.py
- packages/etcd/extra/etcd_discovery/etcd_discovery.py
Adds the etcd metrics endpoint as one of the scraping sources on telegraf.
- [D2IQ-61004](https://jira.d2iq.com/browse/D2IQ-61004) Include etcd in the dc/os monitoring, add dashboards.
_(none)_
> D2IQ-61004: Adding etcd metrics on telegraf

- CHANGES.md
- packages/dcos-ui/buildinfo.json
> Chore(dcos-ui): bump DC/OS UI v5.0.0

- packages/winpanda/extra/src/winpanda/svcm/nssm.py
- packages/winpanda/extra/src/winpanda/tests/unit/test_svcm_nssm.py
During an upgrade the `nssm stop` command timed-out at 30 seconds. Increase the timeout for all NSSM commands to 90 seconds.
> Increase NSSM command timeout to 90 seconds

- gen/build_deploy/powershell/dcos_node_upgrade.ps1.in
ip-detect and fault-domain scripts are now provided by `dcos-config-windows.yaml` so do not need to be downloaded. I missed removing the download from the upgrade script.
- [D2IQ-65527](https://jira.d2iq.com/browse/D2IQ-65527) Move ip-detect and fault-domain scripts to dcos-config-windows
> Remove ip-detect and fault-domain download from Windows upgrade

- gen/build_deploy/powershell/dcos_install.ps1.in
- gen/build_deploy/powershell/dcos_node_upgrade.ps1.in
- packages/winpanda/extra/src/winpanda/core/command.py
Bootstrap requires the `etc\roles` directory and contents to exist. Tell winpanda to keep this directory during upgrade.
> Keep etc\roles directory on Windows during upgrade

- dcos_installer/test_backend.py
- gen/calc.py
- packages/winpanda/extra/src/winpanda/tests/data/expanded.config.full.json
* https://jira.d2iq.com/browse/D2IQ-66483 - Set the version of DCOS to 2.1.0-rc1-dev in master branch of DC/OS
> Update version to 2.1.0-rc1-dev

- packages/telegraf/windows.build.ps1
The `telegraf.extra.j2` file was missing from the Windows package.
- [D2IQ-66230](https://jira.d2iq.com/browse/D2IQ-66230) Telegraf cannot auth with Mesos
> Copy Telegraf extra file into Windows package

- packages/winpanda/extra/src/winpanda/core/command.py
- packages/winpanda/extra/src/winpanda/tests/integration/test_dcos_config.py
Log messages about dcos-config-windows rendering at info level, so we can debug issues.
> Log dcos config rendering at info level

- packages/adminrouter/docker/Dockerfile
- packages/adminrouter/windows.build.ps1
- packages/adminrouter/windows.buildinfo.json
Upgrade OpenResty to 1.15.8.3
- [D2IQ-66506](https://jira.d2iq.com/browse/D2IQ-66506) Upgrade OpenResty to 1.15.8.3
> Upgrade OpenResty to 1.15.8.3

- gen/build_deploy/powershell/dcos_generate_config_win.sh.in
- packages/adminrouter/extra/src/lib/auth/common.lua
- packages/adminrouter/extra/src/lib/util.lua
- packages/mesos/extra/mesos.nssm.j2
- packages/winpanda/extra/src/winpanda/core/command.py
Some small fixes for spelling and backslashes. The Enterprise PR also removes a duplicated URL from Admin Router audit logs.
> Cleanup spelling and incorrect backslashes

- CHANGES.md
- packages/adminrouter/windows.buildinfo.json
Obtain the upgraded OpenResty from our own repo to avoid problems with changes to the original site.
- [D2IQ-66506](https://jira.d2iq.com/browse/D2IQ-66506) Upgrade OpenResty to 1.15.8.3
> Use local repo for OpenResty

- build_local_windows.ps1
> Only install modules if needed

- CHANGES.md
- packages/adminrouter/docker/Dockerfile
Update OpenResty to 1.15.8.3
- [D2IQ-66506](https://jira.d2iq.com/browse/D2IQ-66506) Upgrade OpenResty to 1.15.8.3
> [2.0] Update OpenResty to 1.15.8.3

- packages/winpanda/extra/src/winpanda/svcm/nssm.py
- packages/winpanda/extra/src/winpanda/tests/unit/test_svcm_nssm.py
Upgrade fails on dcos-diagnostics service stop.
Force to kill process after unsuccessful stop.
- [D2IQ-66446](https://jira.d2iq.com/browse/D2IQ-66446) Upgrade fails on dcos-diagnostics service stop.
> D2IQ-66446 Upgrade fails on dcos-diagnostics service stop

- packages/adminrouter/extra/src/lib/cache.lua
Missing concat in error message
- [D2IQ-66551](https://jira.d2iq.com/browse/D2IQ-66551) AR log fails on HTTP error
> Fix missing concatentation operator

- packages/mesos/extra/mesos.ps1
Mesos startup script was not changed to point to the bootstrap.ps1 script when it was created.
- [D2IQ-66264](https://jira.d2iq.com/browse/D2IQ-66264) mesos.ps1 on OPEN cluster fails with missing "$pathtobootstrap\bin\bootstrap"
> Call bootstrap.ps1 when installing Mesos on Windows

- CHANGES.md
- packages/openssl/buildinfo.json
Update OpenSSL to 1.1.1f on Linux. Windows requires an upload to our local repo.
- [D2IQ-66526](https://jira.d2iq.com/browse/D2IQ-66526) Bump OpenSSL to 1.1.1e
> Update OpenSSL on Linux to 1.1.1f

- packages/winpanda/extra/src/winpanda/core/command.py
The fix is to avoid cleaning C:\d2iq\dcos\var.
Workload's Docker container should remain in the running state, regardless mesos-agent fail due to outage or went to upgrade. Particularly for the upgrade action it's causing extra problems, as Winpanda tries to clean up C:\d2iq\dcos\var\ catalogue where the docker container tries to save workload data.
- [D2IQ-66497](https://jira.d2iq.com/browse/D2IQ-66497) Attempt to upgrade a cluster with running service fails
> D2IQ-66497: avoid clean up of C:\d2iq\dcos\var dir

- test_util/main.tf
We can use smaller machines for our CI, to save some money.
- [D2IQ-66575](https://jira.d2iq.com/browse/D2IQ-66575)
- [D2IQ-66580](https://jira.d2iq.com/browse/D2IQ-66580)  
- [D2IQ-66576](https://jira.mesosphere.com/browse/D2IQ-66576)
> Reduce Windows machine size

- packages/openssl/buildinfo.json
Use a Mesosphere repo for Linux download of OpenSSL.
- [D2IQ-66526](https://jira.d2iq.com/browse/D2IQ-66526) Bump OpenSSL to 1.1.1e
> Move Linux openssl to Mesosphere repo

- packages/mesos-modules/windows.build.ps1
- packages/mesos-modules/windows.buildinfo.json
- packages/mesos/windows.build.ps1
- packages/mesos/windows.buildinfo.json
- packages/openssl/windows.build.ps1
- packages/openssl/windows.buildinfo.json
https://jira.d2iq.com/browse/D2IQ-66608
> Updated OpenSSL on Windows to 1.1.1f.

- CHANGES.md
- packages/openssl/buildinfo.json
Update OpenSSL to the latest release.
Apart from noting the change in the changelog, also delete a duplicated entry for the previous update which seems to be the result of a bad back-port.
- [D2IQ-66526](https://jira.d2iq.com/browse/D2IQ-66526) Bump OpenSSL to 1.1.1e
> [2.0] Update OpenSSL to 1.1.1f

- CHANGES.md
- packages/openssl/buildinfo.json
Update to the latest OpenSSL in the 1.0.2 series.
- [D2IQ-66526](https://jira.d2iq.com/browse/D2IQ-66526) Bump OpenSSL to latest
> [1.13] Update to OpenSSL 1.0.2u

- packages/winpanda/extra/src/winpanda/core/command.py
- packages/winpanda/extra/src/winpanda/core/package/package.py
- [D2IQ-66671](https://jira.d2iq.com/browse/D2IQ-66671) Downgrade back to master failed "Cannot create a file when that file already exists: 'C:\d2iq\dcos\etc' -> 'C:\d2iq\dcos\var\tmp\etc.old'" fix.
- [D2IQ-66496](https://jira.mesosphere.com/browse/D2IQ-66496) Downgrade back to master failed.
> D2IQ-66671 Downgrade back to master failed

- test_util/Makefile
This leads to weird situations when we want to destroy cluster but first we need to create a diagnostics bundle for it. It's especially annoying when you want to stop cluster creation and free resources but first need to finish cluster creation and then destroy it.
After merging this change we need to add step to our CI to generate diagnostics bundle even if previous step failed.
- [D2IQ-65565](https://jira.d2iq.com/browse/D2IQ-65565)
> Do not require diagnostics on destroy.

- CHANGES.md
- packages/openssl/buildinfo.json
Update to latest OpenSSL in the 1.0.2 series
- [D2IQ-66526](https://jira.d2iq.com/browse/D2IQ-66526) Bump OpenSSL to latest
> [1.12] Update to OpenSSL 1.0.2u

- build_local_windows.ps1
We have troubles to get packages from https://www.powershellgallery.com/ in our CI.
After investigation I got to the point where requests failed due to SSL.
```
SystemDefault
Ssl3
Tls
Tls11
Tls12
```
```
GET 
https://psg-prod-eastus.azureedge.net/packages/aws.tools.s3.4.0.5.nupkg
with  0-byte payload
The request was aborted: Could not create SSL/TLS secure channel.
```
```
WARNING: Source Location 
'https://www.powershellgallery.com/api/v2/package/AWS.Tools.Common/4.0.5'
is not valid.
Package 'AWS.Tools.Common' failed to download.
```
If you are changing components or packages in DC/OS (e.g. you are bumping the sha …
> Set TLS to 1.2 in Windows build script

- pkgpanda/docker/dcos-builder/Dockerfile
Updated cmake in dcos-builder docker image.
[D2IQ-6671](https://jira.d2iq.com/browse/D2IQ-66810)
> Updated cmake in dcos-builder docker image.

- CHANGES.md
- packages/logrotate/buildinfo.json
Updating logrotate from 3.9.1 to 3.14 to fix the bug described in the following tickets:
https://bugs.launchpad.net/ubuntu/+source/logrotate/+bug/1630516
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850009
- [DCOS_OSS-5947](https://jira.d2iq.com/browse/DCOS_OSS-5947) Bump logrotate to 3.14.0
> logrotate package: update to 3.14.0

- CHANGES.md
- packages/dcos-ui/buildinfo.json
> [master] Automated Bump DC/OS UI v5.0.23

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Fix single escapes in Python strings. These are not causing errors now, but are deprecated and will cause errors when we upgrade Python.
> Fix escapes in diagnostics test

- CHANGES.md
- packages/openssl/buildinfo.json
Update to OpenSSL 1.1.1g
- [D2IQ-67050](https://jira.d2iq.com/browse/D2IQ-67050) Upgrade to OpenSSL 1.1.1g
> Update to OpenSSL 1.1.1g

- CHANGES.md
- packages/dcos-ui/buildinfo.json
> [1.13] Automated Bump DC/OS UI v4.0.1

- CHANGES.md
- packages/dcos-net/buildinfo.json
Bump dcos-net to include changes that allow for graceful shutdown of connections by changing the VIP backend weight to `0` when tasks are unhealthy or enter the `TASK_KILLING` state instead of removing them.
- [D2IQ-61077](https://jira.d2iq.com/browse/D2IQ-61077) Rolling Upgrade Impact on Long Running Services.
> dcos-net: improve shutdown behavior

- CHANGES.md
- packages/dcos-net/buildinfo.json
Bump dcos-net to include changes that allow for graceful shutdown of connections by changing the VIP backend weight to `0` when tasks are unhealthy or enter the `TASK_KILLING` state instead of removing them.
- [D2IQ-61077](https://jira.d2iq.com/browse/D2IQ-61077) Rolling Upgrade Impact on Long Running Services.
> [1.13] dcos-net: improve shutdown behavior

- CHANGES.md
- packages/dcos-ui/buildinfo.json
> [2.0] Automated Bump DC/OS UI v4.0.1

- CHANGES.md
- packages/openssl/buildinfo.json
Back-port of #7210 
Update to OpenSSL 1.1.1g
- [D2IQ-67050](https://jira.d2iq.com/browse/D2IQ-67050) Upgrade to OpenSSL 1.1.1g
> [2.0] Update to OpenSSL 1.1.1g

- CHANGES.md
- packages/dcos-net/buildinfo.json
Bump dcos-net to include changes that allow for graceful shutdown of connections by changing the VIP backend weight to `0` when tasks are unhealthy or enter the `TASK_KILLING` state instead of removing them.
- [D2IQ-61077](https://jira.d2iq.com/browse/D2IQ-61077) Rolling Upgrade Impact on Long Running Services.
> [2.0] dcos-net: improve shutdown behavior

- CHANGES.md
- gen/dcos-config.yaml
Having Windows agent introduced with "os" attributes where value is "windows", the Linux agent needs to be distinguished. Therefore adding "os:linux" for all Linux slaves by default, regardless it's private or public.
- [D2IQ-67223](https://jira.d2iq.com/browse/D2IQ-67223) Linux nodes are not flagged with the os:linux attribute
> D2IQ-67223: add 'os' attributes for Linux agents by default

- packages/dcos-integration-test/extra/test_helpers.py
Tests that launches docker app sometimes fails. We need to increase `gracePeriodSeconds` to not kill app that is about to work.
- [D2IQ-67372](https://jira.d2iq.com/browse/D2IQ-67372) test_if_docker_app_can_be_deployed_window if flaky
> Increase gracePeriodSeconds for test docker app

- packages/calico/extra/dcos-calico-libnetwork-plugin.service
Set `CALICO_LIBNETWORK_LABEL_ENDPOINTS=true` in the libnetwork plugin
service so docker labels will be copied.
- [D2IQ-67993](https://jira.d2iq.com/browse/D2IQ-67993) Missing CALICO_LIBNETWORK_LABEL_ENDPOINTS en
> calico: set `CALICO_LIBNETWORK_LABEL_ENDPOINTS`

- tox.ini
This simply remove some Windows test environments from tox.
> Remove Windows environments from tox.ini.

- mergebot-config.json
> Enable test command in mergebot-config.json

- CHANGES.md
- packages/dcos-ui/buildinfo.json
> [master] Automated Bump DC/OS UI v5.0.41

- test_util/Makefile
- test_util/main.tf
The `test_util/main.tf` and the corresponding Makefile had some references to Windows.
> Remove Windows from main.tf

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
* D2IQ-68616 - Fix DC/OS Branch version string and changes.md string.
> Update version for 2.0.5-dev

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
* D2IQ-68616 - Fix DC/OS Branch version string and changes.md string.
*Update 2.1 branch to reflect version as 2.1.0-rc3 (in development).*
> Update 2.1 branch to reflect version as 2.1.0-rc3 (in development).

- CHANGES.md
* D2IQ-68616 - Fix DC/OS Branch version updates.
*Update release date in CHANGES.md*
> Update release date in CHANGES.md

- CHANGES.md
- packages/etcd/extra/etcd_discovery/etcd_discovery.py
- packages/etcd/extra/etcdctl/dcos_etcdctl.py
- packages/etcd/extra/systemd/dcos-etcd.service
- packages/etcd/extra/systemd/etcd.sh
> etcd: persisting initial-nodes across reboots

- gen/dcos-config.yaml
- packages/mesos-modules/build
- packages/mesos-modules/buildinfo.json
- packages/mesos/build
- packages/mesos/buildinfo.json
Build dcos linux mesos package with cmake.
- [D2IQ-66807](https://jira.d2iq.com/browse/D2IQ-66807) build dcos linux mesos package with cmake.
> Updated mesos package to use cmake.

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
> Set 2.1 version to 2.1.0-rc5-dev

- packages/mesos/buildinfo.json
Fix [D2IQ-65497](https://jira.d2iq.com/browse/D2IQ-65497).
- [D2IQ-65497](https://jira.d2iq.com/browse/D2IQ-65497) COPS-5920: Unmouting volume error after restarting the task (External persistant volumes in Marathon)
> [2.0] Bump Mesos to 802a50f4902f1f5ca3829dca4a472d8a582f7b9b.

- mergebot-config.json
> Update 2.1 JIRA Fix Version

- CHANGES.md
- packages/dcos-ui/buildinfo.json
* [D2IQ-67819](https://jira.d2iq.com/browse/D2IQ-67819)
* [D2IQ-68541](https://jira.d2iq.com/browse/D2IQ-68541)
> [master] Automated Bump DC/OS UI v5.0.57

- CHANGES.md
- packages/dcos-ui/buildinfo.json
* [COPS-6139](https://jira.d2iq.com/browse/COPS-6139)
* [COPS-6085](https://jira.d2iq.com/browse/COPS-6085)
> [master] Automated Bump DC/OS UI v5.1.1

- CHANGES.md
- packages/adminrouter/docker/Dockerfile
- packages/adminrouter/extra/src/test-harness/tests/test_master.py
OpenResty 1.15.8.3 has a bug that prevents spaces in service URL's being passed to the service correctly. https://github.com/openresty/lua-nginx-module/issues/1676
There is a fix on the 1.15.8 branch, but it has not been released.
~For `master` branch, upgrade to the next version of OpenResty (1.17.8.1rc1). We need to upgrade this to a GA release before DC/OS 2.2.~
1.17.8.1rc1 does not have the fix, so we change this to use 1.15.8.4 as for 2.1
- [DCOS_OSS-5967](https://jira.d2iq.com/browse/DCOS_OSS-5967) Upgrade OpenResty in AdminRouter to 1.15.8.4 version.
- [COPS-6166](https://jira.mesosphere.com/browse/COPS-6166) Unable to rename/delete folders in Data Science Engine UI
> Upgrade to OpenResty 1.15.8.4

- CHANGES.md
- gen/dcos-config.yaml
- packages/fluent-bit/build
- packages/fluent-bit/buildinfo.json
- packages/fluent-bit/extra/dcos-fluent-bit.service
* Update fluentbit to version that solves 
* https://github.com/fluent/fluent-bit/issues/1706
* https://github.com/fluent/fluent-bit/issues/1864
* https://github.com/fluent/fluent-bit/issues/659
* https://github.com/fluent/fluent-bit/issues/1798
* Use jemalloc to prevent memory fragmentation in fluentbit
* Update fluentbit default configuration to support filesystem buffering
- [COPS-6218](https://jira.d2iq.com/browse/COPS-6218) dcos-fluent-bit.service consuming memory to the point of exhaustion
> Fluentbit refresh

- packages/mesos/buildinfo.json
Fix [D2IQ-65497](https://jira.d2iq.com/browse/D2IQ-65497).
- [D2IQ-65497](https://jira.d2iq.com/browse/D2IQ-65497) COPS-5920: Unmouting volume error after restarting the task (External persistant volumes in Marathon)
> [1.13] Bump Mesos to f8b8f1e9c0fbf0a3ee769eebcebf0b4e98e0bfa6.

- CHANGES.md
- gen/dcos-config.yaml
Current configuration may lead to high CPU and MEM usage.
This changes will reduce used resources with slightly reducing
intervals and increasing buffer sizes. This should not reduce metrics
granularity but will only change metrics refresh interval.
- [COPS-5629](https://jira.d2iq.com/browse/COPS-5629) Telegraf saturates CPU on agents
> Adjust telegraph configuration

- tox.ini
Upgrade MyPy to work with Python 3.8
- [D2IQ-69787](https://jira.d2iq.com/browse/D2IQ-69787) tox fails with Python 3.8
> Upgrade to MyPy 0.782

- owners.json
> Update owners file

- mergebot-config.json
Adds priorities for the CI triggers.
> Add priorities to mergebot-config.json

- test-e2e/conditional.py
- test-e2e/test_e2e_module.py
Log which files are changed in a PR. This is the first step to conditionally skipping e2e tests that are not required for a given change. This PR does not skip any tests, it only logs which files are considered to be changed, so that we can check that PR's, trains, and release branches are handled correctly.
The build log for this PR's e2e test contains the lines
```
INFO:root:INSTALLER_URL=https://downloads.dcos.io/dcos/testing/pull/7430/dcos_generate_config.sh
INFO:root:Remaining requests: 59
INFO:root:Merging mesosphere:jongiddy/D2IQ-70071-conditional-e2e into dcos:master
INFO:root:Modified files: ['test-e2e/conditional.py', 'test-e2e/test_e2e_module.py']
```
- [D2IQ-70071](https://jira.d2iq.com/browse/D2IQ-70071) Collect changed files
- …
> Log files changed in PR

- packages/bouncer/buildinfo.json
Update Bouncer to set user description to user's email address
- [D2IQ-70199](https://jira.d2iq.com/browse/D2IQ-70199) COPS-6295: modify user description for UI
> [master] Bump Bouncer to use email address for OIDC login

- CHANGES.md
- packages/bouncer/buildinfo.json
Back-port of #7448 
Update Bouncer to set user description to user's email address
- [D2IQ-70199](https://jira.d2iq.com/browse/D2IQ-70199) COPS-6295: modify user description for UI
> [2.1] Bump Bouncer to use email address for OIDC login

- CHANGES.md
- packages/bouncer/buildinfo.json
Back-port of #7448 
Update Bouncer to set user description to user's email address
- [D2IQ-70199](https://jira.d2iq.com/browse/D2IQ-70199) COPS-6295: modify user description for UI
> [2.0] Bump Bouncer to use email address for OIDC login

- CHANGES.md
- packages/bouncer/buildinfo.json
Back-port of #7448 
Update Bouncer to set user description to user's email address
This update required the Bouncer dependency for 1.13 to be branched off.
- [D2IQ-70199](https://jira.d2iq.com/browse/D2IQ-70199) COPS-6295: modify user description for UI
> [1.13] Bump Bouncer to use email address for OIDC login

- README.md
Update README to describe e2e testing and skipping.
All e2e tests were skipped for this simple change and the test took 1m11s instead of an hour:
```
[11:04:25] :	 [Step 2/3] conditional.py              41 INFO     INSTALLER_URL=https://downloads.dcos.io/dcos/testing/pull/7459/dcos_generate_config.sh
[11:04:26] :	 [Step 2/3] conditional.py              62 INFO     Remaining requests: 59
[11:04:26] :	 [Step 2/3] conditional.py             103 INFO     Merging mesosphere:jongiddy/readme-e2e-tests into dcos:master
[11:04:26] :	 [Step 2/3] conditional.py             112 INFO     Modified files: ['README.md']
[11:04:26] :	 [Step 2/3] conditional.py             150 INFO     test-e2e/test_etcd_backup.py:137: All changed files in safelist
[11:04:26] :	 [Step 2/3] conditional.py             150 …
```
> Update README to describe how to run e2e tests

- packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Use python server in diagnostics test minimize application startup time and resources consumption.
Revert change introduced in #7034 
- [D2IQ-70253](https://jira.d2iq.com/browse/D2IQ-70253) Application deployment failed - operation was not completed in 120 seconds.
> Do not use docker app in diagnostics test

- CHANGES.md
- packages/exhibitor/buildinfo.json
Uses the latest exhibitor based on Jetty 9.4.x. This helps with backlog and performance issues.
- [COPS-6326](https://jira.d2iq.com/browse/COPS-6326) Unable to get consistent exhibitor endpoint response (502 error)
> exhibitor: bump

- mergebot-config.json
* https://jira.d2iq.com/browse/D2IQ-71044 - Update 2.1 fix version to 2.1.2
> Update 2.1 FixVersion to 2.1.2

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
* D2IQ-71044 - Update 2.1 version to 2.1.2-dev
> Update 2.1 version to 2.1.2-dev

- pkgpanda/docker/dcos-builder/Dockerfile
Just update Go version to latest https://golang.org/doc/go1.15
> Update Go to 1.15

- CHANGES.md
- packages/dcos-net/extra/gen_resolvconf.py
When replacing the resolv.conf instead of just showing the new
resolv.conf, show the diff of the modification.
- [COPS-6411](https://jira.d2iq.com/browse/COPS-6411) Hostname Resolution fails for VIPs.
> dcos-net: log resolv.conf diff

- CHANGES.md
- packages/cockroach/buildinfo.json
Upgrade to CockroachDB 19.1.11
- [D2IQ-69872](https://jira.d2iq.com/browse/D2IQ-69872) Upgrade CockroachDB to 19.1
- [D2IQ-71241](https://jira.d2iq.com/browse/D2IQ-71241) Update DC/OS to CockroachDB 19.1
> Upgrade to CockroachDB 19.1.11

- CHANGES.md
- packages/dcos-ui/buildinfo.json
* closes [COPS-4665](https://jira.d2iq.com/browse/COPS-4665)
* closes [D2IQ-57756](https://jira.d2iq.com/browse/D2IQ-57756)
> [master] Automated Bump DC/OS UI v5.2.1

- CHANGES.md
- gen/calc.py
- gen/dcos-config.yaml
- packages/calico/extra/dcos-calico-bird.service
- packages/calico/extra/dcos-calico-confd.service
- packages/calico/extra/dcos-calico-felix.service
- packages/calico/extra/dcos-calico-libnetwork-plugin.service
- test-e2e/test_calico_networking.py
Reverts removal of option to disable calico overlay.
- [COPS-6451](https://jira.d2iq.com/browse/COPS-6451) Should be able to disable Calico in config.yaml
> Allow disable calico

- CHANGES.md
- packages/metronome/buildinfo.json
Jobs with dependencies
This adds support for Jobs with Dependencies
- [DCOS_OSS-5974](https://jira.mesosphere.com/browse/DCOS_OSS-5974)
- [D2IQ-70391](https://jira.mesosphere.com/browse/D2IQ-70391)
- [DCOS_OSS-5978](https://jira.mesosphere.com/browse/DCOS_OSS-5978)
- [DCOS_OSS-5971](https://jira.mesosphere.com/browse/DCOS_OSS-5971)
- [DCOS_OSS-5970](https://jira.mesosphere.com/browse/DCOS_OSS-5970)
- [D2IQ-69445](https://jira.mesosphere.com/browse/D2IQ-69445)
> Bump Metronome to version 0.6.61

- Jenkinsfile
> Fix master branch

- packages/metronome/buildinfo.json
Bump Metronome 
- [DCOS_OSS-5988](https://jira.d2iq.com/browse/DCOS_OSS-5988) 
>  Bump Metronome to version 0.6.62

- CHANGES.md
- packages/dcos-ui/buildinfo.json
>   chore: Bump DC/OS UI v5.4.0

- pkgpanda/__init__.py
We do not need to display warring about deleting not existing file – debug will be enough.
Refs: https://github.com/dcos/dcos/pull/6924
- [COPS-6506](https://jira.d2iq.com/browse/COPS-6506) 
> Don't display warrning about removing not existing file on upgrade

- packages/calico/extra/create-calico-docker-network.py
On some OS versions, following a reboot, the Docker unit will fail before bootstrap creates the certificates used by the libnetwork plugin for Calico. Reset the Start Limit counters before attempting to restart it.
Manually tested that this fixes the problem. Extract from Docker journal after a reboot:
```
Sep 30 12:00:21 ip-172-16-0-49.ec2.internal systemd[1]: Failed to start Docker Application Container Engine.
Sep 30 12:00:21 ip-172-16-0-49.ec2.internal systemd[1]: Unit docker.service entered failed state.
Sep 30 12:00:21 ip-172-16-0-49.ec2.internal systemd[1]: docker.service failed.
Sep 30 12:00:24 ip-172-16-0-49.ec2.internal systemd[1]: docker.service holdoff time over, scheduling restart.
Sep 30 12:00:24 ip-172-16-0-49.ec2.internal systemd[1]: start request repeated too quickly for …
```
> Reset Docker unit before restarting it

- CHANGES.md
- packages/marathon/buildinfo.json
* https://jira.d2iq.com/browse/MARATHON-8762
* https://jira.d2iq.com/browse/COPS-5897
> [2.1] Bump Marathon to 1.10.27

- CHANGES.md
- packages/marathon/buildinfo.json
* https://jira.d2iq.com/browse/MARATHON-8762
* https://jira.d2iq.com/browse/COPS-5897
> [2.0] Bump Marathon to 1.9.141

- packages/metronome/buildinfo.json
* [D2IQ-71940](https://jira.d2iq.com/browse/D2IQ-71940)
> Bump Metronome to 0.6.63

- CHANGES.md
- packages/dcos-ui/buildinfo.json
* [COPS-6491](https://jira.d2iq.com/browse/COPS-6491)
* [D2IQ-71334](https://jira.d2iq.com/browse/D2IQ-71334)
* [COPS-6555](https://jira.d2iq.com/browse/COPS-6555)
> [master] Automated Bump DC/OS UI v6.1.5

- CHANGES.md
- packages/dcos-ui/buildinfo.json
* [D2IQ-72446](https://jira.d2iq.com/browse/D2IQ-72446)
> [master] Automated Bump DC/OS UI v6.1.7

- packages/metronome/buildinfo.json
> Bump Metronome to 0.6.65

- CHANGES.md
- packages/marathon/buildinfo.json
Bump Marathon to 1.11.14
JIRA Issues:
- [MARATHON-8773](https://jira.mesosphere.com/browse/MARATHON-8773)
- [MARATHON-8769](https://jira.mesosphere.com/browse/MARATHON-8769)
- [MARATHON-8767](https://jira.mesosphere.com/browse/MARATHON-8767)
- [MARATHON-8762](https://jira.mesosphere.com/browse/MARATHON-8762)
- [COPS-5897](https://jira.d2iq.com/browse/COPS-5897)
- [COPS-6529](https://jira.d2iq.com/browse/COPS-6529)
- [COPS-6590](https://jira.d2iq.com/browse/COPS-6590)
> Bump Marathon to 1.11.14

- CHANGES.md
- packages/marathon/buildinfo.json
* [COPS-6533](https://jira.mesosphere.com/browse/COPS-6533)
* [MARATHON-8770](https://jira.mesosphere.com/browse/MARATHON-8770)
* [D2IQ-72504](https://jira.mesosphere.com/browse/D2IQ-72504)
> Bump Marathon to 1.11.16

- CHANGES.md
- dcos_installer/test_backend.py
- gen/calc.py
- mergebot-config.json
https://jira.d2iq.com/browse/D2IQ-72554
> Update master version to 2.3.0-dev

- packages/dcos-integration-test/extra/test_applications.py
> Add a Marathon integration test using NFS CSI volume.

- packages/metronome/buildinfo.json
- [D2IQ-72421](https://jira.d2iq.com/browse/D2IQ-72421)
> Bump Metronome to 0.6.67

- packages/metronome/buildinfo.json
> Bump Metronome to 0.6.68

- CHANGES.md
- packages/dcos-ui/buildinfo.json
* [COPS-6589](https://jira.d2iq.com/browse/COPS-6589)
* [D2IQ-72705](https://jira.d2iq.com/browse/D2IQ-72705)
> [master] Automated Bump DC/OS UI v6.1.16

- CHANGES.md
- packages/marathon/buildinfo.json
- [MARATHON-8774](https://jira.mesosphere.com/browse/MARATHON-8774)
- [MARATHON-8752](https://jira.mesosphere.com/browse/MARATHON-8752)
- [MARATHON-8764](https://jira.mesosphere.com/browse/MARATHON-8764)
- [COPS-6599](https://jira.mesosphere.com/browse/COPS-6599)
> 2.2: Bump Marathon to 1.11.23

- CHANGES.md
- packages/marathon/buildinfo.json
* MARATHON-8752
* MARATHON-8774
* COPS-6217
> Bump Marathon to 1.10.34 

- CHANGES.md
- packages/marathon/buildinfo.json
- [MARATHON-8775](https://jira.mesosphere.com/browse/MARATHON-8775)
- [COPS-6562](https://jira.mesosphere.com/browse/COPS-6562)
> Bump Marathon to 1.8.247

- CHANGES.md
- packages/marathon/buildinfo.json
* MARATHON-8748
* MARATHON-8774
- COPS-6145
> Bump Marathon to 1.9.145

- packages/calico/extra/create-calico-docker-network.py
Only restart Docker if a restart file exists. This allows bootstrap to determine when a restart is necessary while keeping the certificate name the same.
- [D2IQ-72846](https://jira.d2iq.com/browse/D2IQ-72846) upgrade from 2.1.{0,1} to 2.2.0 stops workloads 
> Restart Docker only if restart file exists

- mergebot-config.json
* Update Mergebot Config for releases 2.2.2, and 2.1.3
> Update Mergebot Config for releases 2.2.2, and 2.1.3

- CHANGES.md
- packages/dcos-ui/buildinfo.json
* [COPS-6624](https://jira.d2iq.com/browse/COPS-6624)
> [master] Automated Bump DC/OS UI v6.1.19

- CHANGES.md
- packages/marathon/buildinfo.json
- [MARATHON-8771](https://jira.d2iq.com/browse/MARATHON-8771)
> Bump Marathon to 1.11.24

- CHANGES.md
- packages/marathon/buildinfo.json
- [MARATHON-8771](https://jira.d2iq.com/browse/MARATHON-8771)
> [2.1] Bump Marathon to 1.10.36

- CHANGES.md
- packages/metronome/buildinfo.json
- setup.py
- test-e2e/requirements.txt
> metronome: bump

- README.md
Add EOL message to DC/OS README. Fixes #7882 
- https://mesosphere.slack.com/archives/CQQ4HV5NY/p1624976673455500?thread_ts=1624361195.358000&cid=CQQ4HV5NY
> Add DC/OS End of Life message
