packages/dcos-integration-test/extra/conftest.py
This ups the timeout for bundle generation to 20 minutes instead of 2 to
ensure that the cluster has enough time to generate the bundle which
is the cause of the vast majority of the flakes for this test.
It also adds logging the time taken to generate the bundle to the output
to get a better idea of how much time it really takes to generate the
bundle.
- [DCOS-41819]https://jira.mesosphere.com/browse/DCOS-41819) dcos-e2e/docker/static/strict tests (open_source_tests.test_units.test_socket_files_teardown) failed with "ResourceWarning: unclosed SSL socket"
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the …
=> Attempt to reduce flakes and gather data on bundle generation.

flake8_dcos_lint/setup.py
* https://jira.mesosphere.com/browse/DCOS-47755 - tox failing on master - unpinned dependency
This might need to be backported to other active versions.
=> Pin the dependency for pep8-naming.

gen/tests/__init__.py
Backport of #4336
This PR adds proper AssertionError reporting with the full output why the assert failed.
- [DCOS_OSS-4742](https://jira.mesosphere.com/browse/DCOS_OSS-4742) Failed gen validate does not show reason for failure of assertions.
=> [1.11] Improve gen validate AssertionError

packages/dcos-integration-test/extra/test_exhibitor.py, packages/dcos-integration-test/extra/test_groups.yaml, packages/exhibitor/extra/start_exhibitor.py
Tighten up permissions for ZooKeeper data directories
- [DCOS-47687](https://jira.mesosphere.com/browse/DCOS-47687) Tighten up permissions on /var/log/dcos/exhibitor
Plan to back-port to 1.12
___ …
=> ZooKeeper file permissions

gen/calc.py, gen/tests/test_config.py, gen/tests/test_service_account.py, gen/tests/utils.py, tox.ini
This PR fixes the bug where DC/OS gen would accept partially specified superuser service account credentials (either uid or public_key missing).
It also adds unit tests for every possible combination.
Skipping the tests for Windows is tracked here:
https://jira.mesosphere.com/browse/DCOS_OSS-4741
This should be investigated and closed once DC/OS has full Windows build support.
- [DCOS-47650](https://jira.mesosphere.com/browse/DCOS-47650) Partially specified superuser_service_account_uid/public_key accepted by gen.
=> Fix superuser service account credentials checking

gen/tests/__init__.py
Backport of #4336
This PR adds proper AssertionError reporting with the full output why the assert failed.
- [DCOS_OSS-4742](https://jira.mesosphere.com/browse/DCOS_OSS-4742) Failed gen validate does not show reason for failure of assertions.
=> [1.12] Improve AssertionError debug output

CHANGES.md, dcos_installer/test_backend.py, gen/calc.py
DCOS-47790 - DC/OS v1.12.2 is marked as 1.12.1
* Update DC/OS version for 1.12.2 to DC/OS 1.12.2
=> Update 1.12.2 version to 1.12.2

CHANGES.md, dcos_installer/test_backend.py, gen/calc.py
Fixes changes.md and let's the development version of 1.12 as 1.12-dev
=> Update CHANGES.md for 1.12-dev

packages/dcos-integration-test/buildinfo.json, packages/dcos-integration-test/extra/test_metrics.py, packages/python-prometheus_client/build, packages/python-prometheus_client/buildinfo.json
Improve metrics integration tests by using the `prometheus_client` python library to parse prom responses for expected metrics instead of checking for substrings in the response string.
- [DCOS_OSS-4572](https://jira.mesosphere.com/browse/DCOS_OSS-4572) Parse Prometheus exporter responses in integration tests
=> [1.12] Use prometheus parser for metrics tests

packages/dcos-metrics/build, packages/dcos-metrics/buildinfo.json
This bump ensures that containers are tracked in Mesos metrics isolator,
which prevents remove attempts of unknown containers.
- [DCOS_OSS-4630](https://jira.mesosphere.com/browse/DCOS_OSS-4630) com_mesosphere_MetricsIsolatorModule fails to track individual containers' lifecycle.
- [COPS-4310](https://jira.mesosphere.com/browse/COPS-4310)
* This has been tested manually on a 1.11.8 cluster, see https://github.com/dcos/dcos-metrics/pull/172
=> [1.10] dcos-metrics: bump to latest commit.

packages/adminrouter/extra/src/docs/api/nginx.agent.html, packages/adminrouter/extra/src/docs/api/nginx.agent.yaml, packages/adminrouter/extra/src/docs/api/nginx.master.html, packages/adminrouter/extra/src/docs/api/nginx.master.yaml, packages/adminrouter/extra/src/lib/cache.lua, packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/marathon.py, packages/adminrouter/extra/src/test-harness/tests/test_cache.py, packages/dcos-integration-test/extra/test_networking.py
This PR is a particular case of https://github.com/dcos/dcos/pull/3855 for DC/OS v1.11.
Due to Marathon app description syntax change https://github.com/mesosphere/marathon/blob/master/docs/docs/upgrade/network-api-migration.md#example-definitions AR is not able to expose apps requiring ip-per-container feature at /service/<app-id> endpoint. This PR fixes this issue.
https://jira.mesosphere.com/browse/DCOS-45468
https://jira.mesosphere.com/browse/DCOS-45468
- [ x ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
- [ x ] Read the [DC/OS contributing …
=> Add AR routing logic support for ip-per-container feature

packages/dcos-integration-test/extra/conftest.py, packages/dcos-test-utils/buildinfo.json
This moves the xfailflake plugin code into dcos-test-utils so that it does not need to be duplicated for every branch and repository. It also adds a pytest hook to write out a report of all tests that are marked flakey.
-  [DCOS-46439](https://jira.mesosphere.com/browse/DCOS-46439) xfailflake dashboard - collect marked issues without a cluster and without regex
=> DCOS-46439 - Move xfailflake collection to dcos-test-utils.

CHANGES.md, gen/build_deploy/bash.py
This adds a proper message in case Docker is not running instead of
telling the user that the Docker version doesn't match.
`docker info` sets its exit-code according to whether Docker is running,
so we can use that in a platform-independent way to make sure it is.
See: https://docs.docker.com/config/daemon/#check-whether-docker-is-running
So before we check the Docker version, we check for the exit code of
`docker info`.
- [[DCOS-15890] DCOS advance installer pre-flight check has a wrong error message](https://jira.mesosphere.com/browse/DCOS-15890)
-  …
=> DCOS-15890 - Check Docker is running before version check 

gen/build_deploy/bash/installer_internal_wrapper.in
Before this change the ARGV0 that's used by `dcos_install` when printing the `--help` output was always `dcos_generate_config.sh`, even when it was built for another variant. In the case of the ticket: `ee`.
This change checks whether `$BOOTSTRAP_VARIANT` is empty or not. And if it's not empty, it uses it to construct the correct filename.
And just to make sure that my shell/ash scripting is up to the task, I tried the `-z` switch etc. in a busybox container with ash:
```
$ docker run -it --rm busybox
/ # export BOOTSTRAP_VARIANT=
/ # if [[ -z $BOOTSTRAP_VARIANT ]];
> then
>   export INSTALLER_ARGV0="dcos_generate_config.sh"
> else
>   export INSTALLER_ARGV0="dcos_generate_config.${BOOTSTRAP_VARIANT}.sh"
> fi
/ # echo $INSTALLER_ARGV0
dcos_generate_config.sh
/ # export …
```
=> DCOS-16098 - Correct filename in dcos_generate_config.ee.sh help

packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/a5d6635b351d1b357e9fcc396b155cccfad6aae5...9f6ccbd41a55846e54297ecb31fddbeee3be50c9
https://github.com/dcos/dcos-mesos-modules/compare/0ed50a4d16dc560554f3abe843f2e0af4f52fcba...885a3c01d048c232f373c832f61403b7578ac605
=> [master] Bump Mesos to nightly master 9f6ccbd

CHANGES.md, dcos_installer/test_backend.py, ssh/validate.py
This backports https://github.com/dcos/dcos/pull/4414
=> [1.12] DCOS_OSS-4613 - Use default `ssh_user` in deprecated CLI installer validations

CHANGES.md, dcos_installer/test_backend.py, ssh/validate.py
Requiring the `ssh_user` attribute in `config.yaml` was part of the CLI installer.
But even though the CLI installer was deprecated, users now run into validation errors when they run `./dcos_generate_config.sh` without specifying a `ssh_user` in their `config.yaml`, even though we explictly say in our documentation that the field is not required.
This is now the first step to fix the ticket and resolve the issue for the customer: by setting a default value for `ssh_user` users won't run into a validation error, but if they change the value, we still validate it.
It's the smallest possible fix.
The proper solution would be to remove the deprecated code and rip out the the parts of the CLI installer that are not needed anymore (I did a first spike for this in …
=> DCOS_OSS-4613 - Use default `ssh_user` in deprecated CLI installer validations

packages/windows.treeinfo.json
Exclude the newly added prometheus_client python dependency from windows build to prevent windows builds from failing.
N/A
=> [1.12] Exclude prometheus_client from windows build

packages/dcos-image-deps/buildinfo.json, packages/liblzma/build, packages/liblzma/buildinfo.json, packages/python/buildinfo.json, pkgpanda/__init__.py, pkgpanda/docker/dcos-builder/Dockerfile, pkgpanda/test_util.py, pkgpanda/util.py
This PR removes operating system specific tar commands in favor of Python's built-in `tarfile` module. It adds a new DC/OS package `liblzma` which is used by `tarfile` to do `lzma` compression for `xz` archives.
This was a collaborative effort together with @adamtheturtle. It enables running DC/OS OSS unit tests natively on macOS.
- [DCOS_OSS-4764](https://jira.mesosphere.com/browse/DCOS_OSS-4764) Make it possible/documented to run unit tests on macOS.
=> Use Python's tarfile in make_tar to avoid Linux/macOS difference in tar distributions

CHANGES.md, packages/bouncer-deps/buildinfo.json, packages/bouncer/buildinfo.json, packages/cockroach/build, packages/cockroach/buildinfo.json, packages/cockroach/extra/cockroachdb-change-config.py, packages/cockroach/extra/iam-database-restore
This PR:
- bumps `cockroachdb` to vesion `2.0.7`
- bumps `bouncer` to the latest version that is compatible with `cockroachdb` version `2.0.7`
- improves `iam-database-restore` script to do the DB rename in a single transaction
- [DCOS-38395](https://jira.mesosphere.com/browse/DCOS-38395) bouncer: upgrade to cockroachdb v2.0.7
___
=> packages: Upgrade cockroachdb to 2.0.7

packages/adminrouter/extra/src/lib/cache.lua, packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/marathon.py, packages/adminrouter/extra/src/test-harness/tests/test_cache.py, packages/dcos-integration-test/extra/test_networking.py
Due to Marathon app description syntax change https://github.com/mesosphere/marathon/blob/master/docs/docs/upgrade/network-api-migration.md#example-definitions AR is not able to expose apps requiring ip-per-container feature at /service/ endpoint. This PR fixes this issue.
https://jira.mesosphere.com/browse/DCOS-47348
https://jira.mesosphere.com/browse/DCOS-46381
- [ x ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
If …
=> [1.12] Add AR routing logic support for ip-per-container feature for Marathon 1.5+

CHANGES.md, dcos_installer/test_backend.py, ssh/validate.py
This backports https://github.com/dcos/dcos/pull/4414
=> [1.11] DCOS_OSS-4613 - Use default `ssh_user` in deprecated CLI installer validations

packages/dcos-integration-test/extra/test_metrics.py
This unmutes `test_metrics.test_metrics_containers`, which was muted with #3836. There are no overrides for this test on the 1.11 branch in the ticket linked in the decorator. This test hasn't failed on the 1.11 branch in its available history, going back to September at the time of this writing: https://teamcity.mesosphere.io/project.html?tab=testDetails&projectId=DcOs_Open_Test_IntegrationTest&testNameId=-4813183735307993658&branch_DcOs_Open_Test_IntegrationTest=1.11.
N/A
If you …
=> (1.11) Unmute test_metrics_containers

packages/dcos-integration-test/extra/conftest.py, packages/dcos-test-utils/buildinfo.json
Original PR: #4320 
This moves the xfailflake plugin code into dcos-test-utils so that it does not need to be duplicated for every branch and repository. It also adds a pytest hook to write out a report of all tests that are marked flakey.
-  [DCOS-46439](https://jira.mesosphere.com/browse/DCOS-46439) xfailflake dashboard - collect marked issues without a cluster and without regex
=> [BACKPORT] [1.10] DCOS-46439 - Move xfailflake collection to dcos-test-utils.

packages/dcos-integration-test/extra/conftest.py, packages/dcos-test-utils/buildinfo.json
Original PR: #4320 
This moves the xfailflake plugin code into dcos-test-utils so that it does not need to be duplicated for every branch and repository. It also adds a pytest hook to write out a report of all tests that are marked flakey.
-  [DCOS-46439](https://jira.mesosphere.com/browse/DCOS-46439) xfailflake dashboard - collect marked issues without a cluster and without regex
=> [BACKPORT] [1.11] DCOS-46439 - Move xfailflake collection to dcos-test-utils.

packages/dcos-integration-test/extra/conftest.py, packages/dcos-test-utils/buildinfo.json
Original PR: #4320 
This moves the xfailflake plugin code into dcos-test-utils so that it does not need to be duplicated for every branch and repository. It also adds a pytest hook to write out a report of all tests that are marked flakey.
-  [DCOS-46439](https://jira.mesosphere.com/browse/DCOS-46439) xfailflake dashboard - collect marked issues without a cluster and without regex
=> [BACKPORT] [1.12] DCOS-46439 - Move xfailflake collection to dcos-test-utils.

pkgpanda/util.py
This PR reverts the decompression part of: [#4388](https://github.com/dcos/dcos/pull/4388/files)
After the aforementioned PR was merged we noticed that the CI runs into this Python bug:
https://bugs.python.org/issue21872
Due to complications to reproduce the issue locally this should be reverted to the old functionality for now.
- [DCOS-48220](https://jira.mesosphere.com/browse/DCOS-48220) pkgpanda: Compressed file ended before the end-of-stream marker was reached.
=> Revert back to platform-dependent tar decompression

packages/dcos-integration-test/extra/requirements.txt, tox.ini
Adds a tox target and requirements.txt that allows the integration tests to be collected locally without needing to be run inside of a cluster.
- [DCOS-46438](https://jira.mesosphere.com/browse/DCOS-46438) Make it possible to collect DC/OS integration tests without a running cluster
=> DCOS-46438 - Support collecting integration tests locally without a cluster.

dcos_installer/test_backend.py, gen/calc.py
https://jira.mesosphere.com/browse/DCOS-48228 - Update the next release of 1.10 DC/OS version to 1.10.11
* Go to https://dcos.io/releases/ and make sure the version mentioned in this change is the next version of DC/OS for 1.10 release
* The target branch will be renamed to `1.10.11` after we merge this PR.
=> Update DC/OS version to 1.10.11

dcos_installer/test_backend.py, gen/calc.py
https://jira.mesosphere.com/browse/DCOS-48228 - Update the next release of 1.11 DC/OS version to 1.11.10
* Go to https://dcos.io/releases/ and make sure the version mentioned in this change is the next version of DC/OS for 1.11 release
* The target branch `1.11.9.1` will be renamed to `1.11.10` after we merge this PR.
=> update the version of DC/OS to 1.11.10

packages/dcos-integration-test/extra/requirements.txt, packages/dcos-integration-test/extra/test_networking.py, tox.ini
Adds a tox target and requirements.txt that allows the integration tests to be collected locally without needing to be run inside of a cluster.
- [DCOS-46438](https://jira.mesosphere.com/browse/DCOS-46438) Make it possible to collect DC/OS integration tests without a running cluster
=> [BACKPORT] [1.10] DCOS-46438 - Support collecting integration tests locally without a cluster.

packages/adminrouter/extra/src/docs/api/nginx.master.html, packages/adminrouter/extra/src/docs/api/nginx.master.yaml, packages/adminrouter/extra/src/includes/server/master.conf, packages/adminrouter/extra/src/lib/auth/open.lua
These endpoints are used to install CLI extensions through the `dcos
package install` subcommand (eg. `dcos package install
dcos-enterprise-cli`) and currently require the full
dcos:adminrouter:package permission even though they do not install
anything on the cluster side.
This change opens these endpoints to all authenticated users, making it
easier for unprivileged CLI users to install package subcommands.
https://jira.mesosphere.com/browse/DCOS_OSS-4651
=> Open /package/describe and /package/resource to any authenticated user

packages/cockroach/extra/iam-database-restore
This reverts commit 0bcab681a26f1e9152c24af320592989a07b2df0.
The #4251 changed `iam-database-restore` script on a false assumption that database renames could be handled transactionally.
After consulting with CockroachDB https://forum.cockroachlabs.com/t/renaming-database-in-a-transaction/2397 I've confirmed that this is not the case and we need to revert to a previous restore script version.
- [DCOS-48182](https://jira.mesosphere.com/browse/DCOS-48182) cockroach: confirm that database renames are transactional
=> Revert "packages/cockroach: improve iam-database-restore script"

packages/dcos-integration-test/extra/requirements.txt
Bump PyYaml in integration-test requirements.txt to a version not affected by CVE-2017-18342.
=> DCOS-46438 - Do not use vulnerable PyYaml version in tests.

packages/dcos-integration-test/extra/requirements.txt, tox.ini
Adds a tox target and requirements.txt that allows the integration tests to be collected locally without needing to be run inside of a cluster.
- [DCOS-46438](https://jira.mesosphere.com/browse/DCOS-46438) Make it possible to collect DC/OS integration tests without a running cluster
=> [BACKPORT] [1.11] DCOS-46438 - Support collecting integration tests locally without a cluster.

packages/metronome/build
Remove redundant code in the build script
- [DCOS-45513](https://jira.mesosphere.com/browse/DCOS-45513) packages/metronome: metronome incorrectly writes its PID into /opt/mesosphere location
=> Metronome PID is not written to this location

packages/dcos-integration-test/extra/requirements.txt, tox.ini
Adds a tox target and requirements.txt that allows the integration tests to be collected locally without needing to be run inside of a cluster.
- [DCOS-46438](https://jira.mesosphere.com/browse/DCOS-46438) Make it possible to collect DC/OS integration tests without a running cluster
=> [BACKPORT] [1.12] DCOS-46438 - Support collecting integration tests locally without a cluster.

gen/calc.py, packages/dcos-checks/buildinfo.json, test-e2e/requirements.txt, test-e2e/test_groups.yaml, test-e2e/test_master_node_replacement.py
CockroachDB is introduced to DC/OS in version 1.13. To make sure that no master node replacements/upgrades can happen too quickly for CockroachDB nodes to rebalance their data we introduce also this dcos-check from DC/OS Enterprise.
This PR adds the dcos-check for CockroachDB underreplicated ranges to DC/OS from DC/OS Enterprise. It also adds a test that replaces all master nodes in 3 master cluster one after another to test that the check works correctly.
- [DCOS_OSS-4753](https://jira.mesosphere.com/browse/DCOS_OSS-4753) Add dcos-check fo cockroachdb replication to DC/OS.
The plan is to have a follow-up PR for Enterprise that incorporates this check from dcos-checks. …
=> Open-source CockroachDB ranges check

CHANGES.md, packages/telegraf/buildinfo.json
In the last MWST, we discovered a bug in Telegraf's Mesos input plugin that was causing some mesos metrics to be mis-tagged. The bug has been fixed in Telegraf, bumping the version here.
- [DCOS_OSS-4760](https://jira.mesosphere.com/browse/DCOS_OSS-4760) Some metrics may have wrong tags
- [DCOS-47991](https://jira.mesosphere.com/browse/DCOS-47991) Gaps in the Mesos MoM dashboards
- [] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: upstream tests in Telegraf should be sufficient. adding an integration test that forces this test case would be difficult.
If you are changing components or packages in DC/OS …
=> [1.12] Fix mesos metrics bug

CHANGES.md, packages/telegraf/build, packages/telegraf/buildinfo.json
This upgrades Telegraf from 1.7.2 to 1.9.4.
- [DCOS_OSS-4675](https://jira.mesosphere.com/browse/DCOS_OSS-4675) Rebase DC/OS Telegraf against upstream Telegraf
- N/A
=> Upgrade Telegraf to 1.9.4

gen/dcos-config.yaml, packages/dcos-integration-test/extra/test_metrics.py, packages/telegraf/extra/dcos-telegraf.service, packages/telegraf/extra/start_telegraf.sh, packages/telegraf/extra/tools/extract_fault_domain.py
This PR introduces an additional step to the telegraf startup script. If the fault domain script (see https://docs.mesosphere.com/1.12/deploying-services/fault-domain-awareness/#installation-steps) is present, it is executed to yield the fault domain region and zone. These are then written to the telegraf configuration directory in an override configuration (see https://github.com/influxdata/telegraf/tree/master/plugins/processors/override).
This means that:-
- if no fault domain script is set, no tags will be added
- if a fault domain script is set, tags will be added
- if a fault domain script is set but cannot be parsed, no tags will be added
- …
=> Write override config for fault domain tags

gen/dcos-config.yaml
This increases Telegraf's UDP message queue size from 10000 to 100000 to help ensure that messages are not dropped when a cluster is under load.
- [DCOS_OSS-4761](https://jira.mesosphere.com/browse/DCOS_OSS-4761) Telegraf drops statsd metrics at scale
N/A
=> Grow Telegraf's statsd UDP message queue

packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/e929d413328e10f6d358899500d5aaedd9d9bc51...1fee9b5365bf2424e4768dc1d5209c6c78dfece6
=> [1.10] Bump Mesos to nightly 1.4.x 1fee9b5

packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/extra/patches/0015-Reverted-the-container-sandbox-permission-from-0750-.patch, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/4f21147a9334ef9ed84dcf11742ce448062f3ec1...33c3d49db5a57a500fd2fee0ca81945d350ab80f
https://github.com/dcos/dcos-mesos-modules/compare/85a3ee2e4ac2b180b13690ea98fd87a8ef473697...35d3b464be910867ccb308fb57bd981747ed8568
=> [1.12] Bump Mesos to nightly 1.7.x 33c3d49

pkgpanda/__init__.py
This change reverts [1.11] DCOS_OSS-4097 - Explicitly create user groups in pkgpanda #4484
---- 
This reverts commit c2693ce845c44b9e20fa0f96cd761857402128d7, reversing
changes made to 52ab76e615d150589bc1207fed8a8f6ebd691096.
It looks like #4484
broke 1.11 Enterprise DC/OS branch
https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Enterprise_Test_DockerBased_E2eGroup4&page=2&tab=buildTypeHistoryList&branch_DcOs_Enterprise_Test_DockerBased=1.11
=> Revert "Merge #4484" -DCOS_OSS-4097 - Explicitly create user groups in pkgpanda

packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/5f6225bd6e039c633b7758f02d2b5fbabc8e0169...7a75370fb3671e8f194a9d66fa2ba5c148c89016
=> [1.11] Bump Mesos to nightly 1.5.x 7a75370

packages/bouncer/build, packages/bouncer/extra/dcos_add_user.py, packages/dcos-integration-test/extra/test_legacy_user_management.py
Script contributed by @timaa2k: https://github.com/dcos/dcos/commit/c5d20500af61e9b0597c3d982760934c051fe383
Prior to DC/OS version 1.13 a user could directly be created in ZooKeeper by
utilizing a script `dcos_add_user.py`
This script is intended to enable the same functionality for DC/OS 1.13+. It is meant to add remote users
specifically for the Auth0 identity provider.
This script uses legacy user management to create a user in the IAM service.
https://jira.mesosphere.com/browse/DCOS-45284
- [ x ] Followed relevant code rules [Rules for Packages and …
=> Restore IAM user creation script for adding remote users for Auth0 identity provider in DC/OS 1.13+

packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/9f6ccbd41a55846e54297ecb31fddbeee3be50c9...3886e2a0b77a8f8233d95f785ddb55403e638677
https://github.com/dcos/dcos-mesos-modules/compare/885a3c01d048c232f373c832f61403b7578ac605...17e36a905c27008f0c83be44f52bf05091e5fd80
=> [master] Bump Mesos to nightly master 3886e2a

packages/dcos-integration-test/extra/test_metronome.py
Re-enable the test. I looked into last ~20 runs on ARM and no failure. Also this is pretty much the ONLY test that covers metronome so it should NEVER be muted.
It's possible that it's fixed already. We had problems with Metronome on ARM that we solved by bumping the marathon dependency.
- [DCOS-40611](https://jira.mesosphere.com/browse/DCOS-40611) test_metronome.test_metronome failed sporadically on Azure ARM platform.
=> Re-enable test_metronome

packages/dcos-integration-test/extra/test_checks.py
Re-enable the test. I did not see it fail in last 20 runs of ARM build. Also we were not able to reproduce locally and there were many metronome fixes in last X months.
- [DCOS-45278](https://jira.mesosphere.com/browse/DCOS-45278) teamcity/dcos/test/azure/arm: Metronome error 'history for that job run is not available'
=> Re-enable test_checks_cli test

CHANGES.md, packages/marathon/buildinfo.json
- [MARATHON-8574](https://jira.mesosphere.com/browse/MARATHON-8574) Release Marathon 1.5.13.
[MARATHON-8493](https://jira.mesosphere.com/browse/MARATHON-8493) Fixed precision bug associated with summing pod resources.
[MARATHON-8498](https://jira.mesosphere.com/browse/MARATHON-8498) Fixed secrets validator when changing secret env.
[MARATHON-8466](https://jira.mesosphere.com/browse/MARATHON-8466) Prohibit the use of reserve words in app and pod ids
[COPS-4483](https://jira.mesosphere.com/browse/COPS-4483) Provide backward compatible way to produce container ports for text/plain GET requests …
=> marathon 1.5.13 bump on dcos 1.10

packages/dcos-integration-test/buildinfo.json, packages/dcos-integration-test/extra/requirements.txt, packages/dcos-integration-test/extra/test_metrics.py, packages/python-prometheus_client/build, packages/python-prometheus_client/buildinfo.json, packages/windows.treeinfo.json
Improve metrics integration tests by using the `prometheus_client` python library to parse prom responses for expected metrics instead of checking for substrings in the response string.
- [DCOS_OSS-4572](https://jira.mesosphere.com/browse/DCOS_OSS-4572) Parse Prometheus exporter responses in integration tests
=> [1.13] Use prometheus parser for metrics tests

CHANGES.md, packages/telegraf/buildinfo.json
This adds an internal metric to Telegraf's statsd input plugin: `internal_statsd_dropped_messages`. This metric reports the number of incoming metric messages that have been dropped due to a full queue.
- [DCOS_OSS-4759](https://jira.mesosphere.com/browse/DCOS_OSS-4759) Telegraf statsd input plugin: report UDP metrics
N/A
=> Bump Telegraf to add internal metrics for statsd plugin

packages/dcos-integration-test/extra/test_units.py
Backport removing flaky test marker for DCOS-41819
- [DCOS-41819](https://jira.mesosphere.com/browse/DCOS-41819)
___
* Developers responsible for code that interacts with or depends …
=> Backport removal of flaky test marker to 1.12

test-e2e/README.md, test-e2e/cluster_helpers.py, test-e2e/conftest.py, test-e2e/requirements.txt, test-e2e/test_e2e_module.py, test-e2e/test_groups.yaml, test-e2e/test_make_disk_resources.py, tox.ini
* DCOS_OSS-2032 - Add ability to run E2E tests in DC/OS Open version
This is a backport of https://github.com/dcos/dcos/pull/4445 to 1.12 branch.
This also brings one enterprise test from EE branch to Open (after minor customization for dcos-test-utils) - https://github.com/mesosphere/dcos-enterprise/pull/3255/
This will make sure that we will have at-least one test and a group to exercise against in Teamcity CI and we can enable the status check.
How to review:
Please make sure there is  a status called *teamcity/dcos/test/test-e2e/group1* and you can visit the teamcity details link from that status.
=> Introduce test-e2e to dcos/dcos 1.10

gen/tests/test_config.py
The 0.7.0 release of the schema package changed the wording in some error messages. This updates tests to reflect the change.
- [DCOS_OSS-4829](https://jira.mesosphere.com/browse/DCOS_OSS-4829) tox failure: test_config.test_validate_check_config
N/A
=> Fix tests for schema 0.7.0

test-e2e/README.md, test-e2e/cluster_helpers.py, test-e2e/conftest.py, test-e2e/requirements.txt, test-e2e/test_e2e_module.py, test-e2e/test_groups.yaml, test-e2e/test_make_disk_resources.py, tox.ini
* DCOS_OSS-2032 - Add ability to run E2E tests in DC/OS Open version
This is a backport of https://github.com/dcos/dcos/pull/4445 to 1.12 branch.
This also brings one enterprise test from EE branch to Open (after minor customization for dcos-test-utils) - https://github.com/mesosphere/dcos-enterprise/pull/3255/
This will make sure that we will have at-least one test and a group to exercise against in Teamcity CI and we can enable the status check.
How to review:
Please make sure there is  a status called *teamcity/dcos/test/test-e2e/group1* and you can visit the teamcity details link from that status.
=> Introduce test-e2e to dcos/dcos 1.11

pkgpanda/exceptions.py, pkgpanda/test_util.py, pkgpanda/util.py
AWS S3, from which we download pre-built pkgpanda packages, might sometimes end the connection before the package has been fully downloaded. (See https://github.com/aws/aws-sdk-js/issues/312 and https://github.com/boto/boto3/issues/540 for more context on this)
In our case that leads to invalid `tar.xz` archives which cause `unexpected end of input` errors and result in faulty builds of DC/OS (`dcos_generate_config.sh`) which contain these invalid archives and then result in install-time errors for users. See this comment for an investigation into how this can affect installation errors: https://jira.mesosphere.com/browse/DCOS_OSS-4097?focusedCommentId=219259&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-219259
This change here adds a sanity check to the …
=> DCOS-46615 - Retry downloading pkgpanda pkg if file size incorrect

pkgpanda/exceptions.py, pkgpanda/test_util.py, pkgpanda/util.py
This is the backport of [DCOS-46615 - Retry downloading pkgpanda pkg if file size incorrect](https://github.com/dcos/dcos/pull/4549)
=> [1.11] DCOS-46615 - Retry downloading pkgpanda pkg if file size incorrect

test-e2e/README.md, test-e2e/cluster_helpers.py, test-e2e/conftest.py, test-e2e/requirements.txt, test-e2e/test_e2e_module.py, test-e2e/test_groups.yaml, test-e2e/test_make_disk_resources.py, tox.ini
* DCOS_OSS-2032 - Add ability to run E2E tests in DC/OS Open version
This is a backport of https://github.com/dcos/dcos/pull/4445 to 1.12 branch.
This also brings one enterprise test from EE branch to Open (after minor customization for dcos-test-utils) - https://github.com/mesosphere/dcos-enterprise/pull/3255/
This will make sure that we will have at-least one test and a group to exercise against in Teamcity CI and we can enable the status check.
How to review:
Please make sure there is  a status called *teamcity/dcos/test/test-e2e/group1* and you can visit the teamcity details link from that status.
=> Introduce test-e2e to dcos/dcos 1.12

pkgpanda/exceptions.py, pkgpanda/test_util.py, pkgpanda/util.py
This is the backport of [DCOS-46615 - Retry downloading pkgpanda pkg if file size incorrect](https://github.com/dcos/dcos/pull/4549)
=> [1.12] DCOS-46615 - Retry downloading pkgpanda pkg if file size incorrect

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
[[MESOS-8887](https://issues.apache.org/jira/browse/MESOS-8887)] - Unreachable tasks are not GC'ed when unreachable agent is GC'ed.
[[MESOS-9340](https://issues.apache.org/jira/browse/MESOS-9340)] - Log all socket errors in libprocess.
[[MESOS-9507](https://issues.apache.org/jira/browse/MESOS-9507)] - Agent could not recover due to empty docker volume checkpointed files.
[[MESOS-9549](https://issues.apache.org/jira/browse/MESOS-9549)] - nvidia/cuda 10 does not work on GPU isolator.
[[MESOS-9555](https://issues.apache.org/jira/browse/MESOS-9555)] - Allocator CHECK failure: reservationScalarQuantities.contains(role). …
=> [1.12] Bump Mesos to nightly 1.7.x 5e234c8

pkgpanda/test_util.py, pkgpanda/util.py
This fixes an issue that [popped up when making an uncached build of DC/OS](https://jira.mesosphere.com/browse/DCOS-46615?focusedCommentId=222075&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-222075) where pkgpanda was downloading files that didn't come with a `Content-Length` header in their HTTP responses. Example:
```
$ curl -I -L https://github.com/pallets/flask/archive/0.11.1.tar.gz
HTTP/1.1 302 Found
Server: GitHub.com
Date: Thu, 28 Feb 2019 07:59:14 GMT
Content-Type: text/html; charset=utf-8
Status: 302 Found
Location: https://codeload.github.com/pallets/flask/tar.gz/0.11.1
[...]
HTTP/1.1 200 OK
Access-Control-Allow-Origin: https://render.githubusercontent.com
ETag: "d1d82ca8ce7262ad9d27245ce44f86571287810e"
Content-Type: application/x-gzip …
```
=> DCOS-46615 - Make pkgpanda resistant to missing content-length

test-e2e/test_master_node_replacement.py
This PR fixes the broken master node replacement E2E test by reverting changes applied after moving it over from Enterprise.
- [DCOS_OSS-4844](https://jira.mesosphere.com/browse/DCOS_OSS-4844) test_master_node_replacement.test_replace_all_static is failing on master.
=> [DCOS_OSS-4844] Fix master node replacement test

packages/mesos/build
This is a cherry pick of 32a013a , which landed on the 1.12.2 tag only.  The reason for the disjointed merge was to maintain secrecy of the security hole prior to fixing it immediately once the CVE's embargo was lifted.
This is the 1.12 version of #4620.
- [DCOS-49211](https://jira.mesosphere.com/browse/DCOS-49211) Enable mesos launcher sealing for upstream branches.
- [DCOS-48052](https://jira.mesosphere.com/browse/DCOS-48052) Mesos containerizer launch binary and command executor are under the risk of being overwritten.
- [CVE-2019-5736](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019- …
=> [1.12] Enabled mesos launcher sealing.

packages/dcos-integration-test/extra/test_networking.py
Re-enable flakey tests `test_ipv6` and `test_if_overlay_ok` as Docker has been upgraded DCOS-38144
- [DCOS-46146](https://jira.mesosphere.com/browse/DCOS-46146) networking integration test instability, to be fixed by upgrading Docker to version 17.12.x
- [DCOS-38144](https://jira.mesosphere.com/browse/DCOS-38144) Update Docker on all TeamCity agents to 18.09.1-ce
=> [BACKPORT] [1.11] DCOS-46146 - Re-enable test_ipv6 and test_if_overlay_ok

packages/metronome/buildinfo.json
- [DCOS-48948](https://jira.mesosphere.com/browse/DCOS-48948) Bump DC/OS 1.12 to latest Metronome
* [MARATHON-8555](https://jira.mesosphere.com/browse/MARATHON-8555) Parameter --leader_proxy_max_open_connections does not actually allow more concurrent connections
* [MARATHON-8566](https://jira.mesosphere.com/browse/MARATHON-8566) Fix race condition causing deployment info to not be available
* [MARATHON-8555](https://jira.mesosphere.com/browse/MARATHON-8577) Include app-id in illegal-state-exception …
=> bumping metronome 0.6.11 on dcos 1.12

packages/dcos-integration-test/extra/test_networking.py
Re-enable flakey tests `test_ipv6` and `test_if_overlay_ok` as Docker has been upgraded DCOS-38144
- [DCOS-46146](https://jira.mesosphere.com/browse/DCOS-46146) networking integration test instability, to be fixed by upgrading Docker to version 17.12.x
- [DCOS-38144](https://jira.mesosphere.com/browse/DCOS-38144) Update Docker on all TeamCity agents to 18.09.1-ce
=> DCOS-46146 - Re-enable test_ipv6 and test_if_overlay_ok

gen/aws/templates/cloudformation.json
DCOS-18825 - Pin the Availability Zone per region for the AWS CF Template
**NOTE** - Cloudformation tests are successful with this change:
1. https://teamcity.mesosphere.io/viewLog.html?buildId=1642996&buildTypeId=DcOs_Open_Test_IntegrationTest_AwsCloudFormationSimple 
2. The list of regions map to the supported ones listed here:
https://github.com/dcos/dcos/blob/master/gen/build_deploy/aws.py#L129
3. If we have to update the instance support from `m4.xlarge` (https://github.com/dcos/dcos/blob/master/gen/aws/templates/cloudformation.json#L35) to something else like m5, we will have to update the list of amis per region that is built for the instance in step 2. That's a larger change, and this change makes sure that our default cloudformation templates will keep working.
=> Update the cloud-formation templates to use specific Availability Zone

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/test_applications.py, packages/dcos-integration-test/extra/test_helpers.py, packages/dcos-integration-test/extra/test_networking.py
DCOS-46608 - Docker pull instabilities. 
This PR adds a helper which will do a docker pull of the image before we use in the integration test.
=> DCOS-46608 - docker pull image ahead of usage in test

packages/adminrouter/extra/src/lib/cache.lua, packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/marathon.py, packages/adminrouter/extra/src/test-harness/tests/test_cache.py, packages/dcos-integration-test/extra/test_networking.py
Adds support for latest Marathon networking modes to Admin Router `/service` proxying endpoint.
- [DCOS-48134](https://jira.mesosphere.com/browse/DCOS-48134) Add supporting endpoints for services running in CNI (e.g. Calico) to AdminRouter
=> Add AR routing logic support for ip-per-container feature for Marathon 1.5+

packages/bootstrap/extra/dcos_internal_utils/cli.py
Add the pid to bootstrap logs. Bootstrap runs concurrently on start-up, and sometimes we get logs that have not been separated by unit, especially if they come from the `dcos node log` command. Adding the pid disambiguates these cases.
- [https://jira.mesosphere.com/browse/DCOS-48768](https://jira.mesosphere.com/browse/DCOS-48768) Add component name to bootstrap logs
Change to log format
Change to log format
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the …
=> Add pid to bootstrap logs to distinguish concurrent runs

prep_local_windows.ps1
Fix for DCOS-45501
As noted here:
https://github.com/pypa/pip/issues/5109
there can be an 'Access denied' error message when calling a pip
upgrade directly as this is a known issue with updating binaries
on Windows.
This change removes the potentially confusing error message, but
does not completely fix Windows builds.
- https://jira.mesosphere.com/browse/DCOS-45501 teamcity/dcos/build/dcos/windows fails at start_dcos_windows_build.ps1 with PermissionError
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS …
=> Updating invocation of pip upgrade to remove error message.

packages/mesos/buildinfo.json
[MESOS-9555](https://jira.apache.org/jira/browse/MESOS-9555) - Allocator CHECK failure: reservationScalarQuantities.contains(role).
[MESOS-9507](https://jira.apache.org/jira/browse/MESOS-9507) - Agent could not recover due to empty docker volume checkpointed files.
[MESOS-8887](https://jira.apache.org/jira/browse/MESOS-8887) - Unreachable tasks are not GC'ed when unreachable agent is GC'ed.
https://github.com/apache/mesos/compare/7a75370fb3671e8f194a9d66fa2ba5c148c89016...8b7ab8403365db54b2d2315cbebe2bc332444fab
=> [1.11] Bump Mesos to nightly 1.5.x 8b7ab84

CHANGES.md, gen/dcos-config.yaml
Increased Telegraf's buffer limit to 20K (doubled from previous 10K) to avoid dropping massive amounts of metrics (bug surfaced from MWST13)
- [DCOS-49277](https://jira.mesosphere.com/browse/DCOS-49277) Dropped Telegraf metrics
=> [1.12] Increase Telegraf buffer size limit to 20K

gen/dcos-config.yaml
Increased Telegraf's buffer limit to 20K (doubled from previous 10K) to avoid dropping large amounts of metrics (bug surfaced from MWST13)
- [DCOS-49277](https://jira.mesosphere.com/browse/DCOS-49277) Dropped Telegraf metrics
=> [1.13] Increase Telegraf buffer limit to 20K

packages/mesos/buildinfo.json
[MESOS-9507](https://jira.apache.org/jira/browse/MESOS-9507) - Agent could not recover due to empty docker volume checkpointed files.
https://github.com/apache/mesos/compare/1fee9b5365bf2424e4768dc1d5209c6c78dfece6...177bc5252829e6f9730122c41ad9cd1d37b3f070
=> [1.10] Bump Mesos to nightly 1.4.x 177bc52

CHANGES.md, gen/dcos-config.yaml
In the last MWT, we saw many metrics getting dropped (e.g. internal plugin) while mesos/containers metrics were getting reported in the prom output. We noticed that these two plugins override the default polling interval (defaulted to 10s) to 60s. We should change the default polling interval to 20s and monitor in the next MWT to see if it improves performance and lowers the amount of dropped metrics.
- [DCOS-49301](https://jira.mesosphere.com/browse/DCOS-49301) Decrease default Telegraf polling interval
=> [1.12] Decrease default Telegraf polling frequency

gen/dcos-config.yaml
In the last MWT, we saw many metrics getting dropped (e.g. internal plugin) while mesos/containers metrics were getting reported in the prom output. We noticed that these two plugins override the default polling interval (defaulted to 10s) to 60s. We should change the default polling interval to 20s and monitor in the next MWT to see if it improves performance and lowers the amount of dropped metrics.
- [DCOS-49301](https://jira.mesosphere.com/browse/DCOS-49301) Decrease default Telegraf polling interval
=> [1.13] Decrease default Telegraf polling frequency

packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
[ASF-2844](https://jira.mesosphere.com/browse/ASF-2844) - Support seccomp `unconfined` option for whitelisting.
https://github.com/apache/mesos/compare/3886e2a0b77a8f8233d95f785ddb55403e638677...50167a73bd53884b11330b2598d220f71aef7c17
https://github.com/dcos/dcos-mesos-modules/compare/17e36a905c27008f0c83be44f52bf05091e5fd80...d566b1416c6833b5ea03e681bc1bdcb14aee5277
=> [master] Bump Mesos to nightly master 50167a7

packages/bootstrap/extra/dcos_internal_utils/cli.py, packages/bootstrap/extra/dcos_internal_utils/exhibitor.py
Forward-port of 1.12 PR #4681 
This forward-ports to `master` a few fixes identified while back-porting the original `master` PR https://github.com/dcos/dcos/pull/4658 to 1.12.
- [https://jira.mesosphere.com/browse/DCOS-48768](https://jira.mesosphere.com/browse/DCOS-48768) Add component name to bootstrap logs
Change to log format
Change to log format
___
**PLEASE FILL IN THE TEMPLATE …
=> Add prefix to logged pid, and fix deprecated escape

packages/bootstrap/extra/dcos_internal_utils/cli.py, packages/bootstrap/extra/dcos_internal_utils/exhibitor.py
Back-port to 1.12. Includes change suggested by @mhrabovcin in #4658
Add the pid to bootstrap logs. Bootstrap runs concurrently on start-up, and sometimes we get logs that have not been separated by unit, especially if they come from the `dcos node log` command. Adding the pid disambiguates these cases.
- [https://jira.mesosphere.com/browse/DCOS-48768](https://jira.mesosphere.com/browse/DCOS-48768) Add component name to bootstrap logs
Change to log format
Change to log format
If you are changing components or packages in DC/OS (e.g. you are bumping the sha …
=> [1.12] Add pid to bootstrap logs to distinguish concurrent runs

packages/dcos-integration-test/extra/test_networking.py
Re-enable flakey tests `test_ipv6` and `test_if_overlay_ok` as Docker has been upgraded DCOS-38144
- [DCOS-46146](https://jira.mesosphere.com/browse/DCOS-46146) networking integration test instability, to be fixed by upgrading Docker to version 17.12.x
- [DCOS-38144](https://jira.mesosphere.com/browse/DCOS-38144) Update Docker on all TeamCity agents to 18.09.1-ce
=> [BACKPORT] [1.12] DCOS-46146 - Re-enable test_ipv6 and test_if_overlay_ok

CHANGES.md, packages/dcos-net/extra/dcos-net-setup.py
Makes the systemd network configuration directory (`/etc/systemd/network`) if it does not already exists.
- [DCOS-49711](https://jira.mesosphere.com/browse/DCOS-49711) COPS-4621: dcos-net-setup.py fails if systemd-networkd is installed but not active.
=> dcos-net: ensure the desination directory exists

CHANGES.md, packages/dcos-net/extra/dcos-net-setup.py
Makes the systemd network configuration directory (`/etc/systemd/network`) if it does not already exists.
- [DCOS-49711](https://jira.mesosphere.com/browse/DCOS-49711) COPS-4621: dcos-net-setup.py fails if systemd-networkd is installed but not active.
=> [BACKPORT][1.11] dcos-net: ensure the desination directory exists

CHANGES.md, packages/dcos-net/extra/dcos-net-setup.py
Makes the systemd network configuration directory (`/etc/systemd/network`) if it does not already exists.
- [DCOS-49711](https://jira.mesosphere.com/browse/DCOS-49711) COPS-4621: dcos-net-setup.py fails if systemd-networkd is installed but not active.
=> [BACKPORT][1.12] dcos-net: ensure the desination directory exists

packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/50167a73bd53884b11330b2598d220f71aef7c17...a5b9f6e1cdb2ec26baf6e49706e1a0d59f3ce4d1
https://github.com/dcos/dcos-mesos-modules/compare/d566b1416c6833b5ea03e681bc1bdcb14aee5277...92e932c524fac7349d3a1e31b780bacefdfd21c5
=> [master] Bump Mesos to nightly master a5b9f6e

gen/build_deploy/bash.py
Fixes: DCOS_OSS-2438
With no use of getopt, OPTIND will always be 1 and this is a no-op. Remove this line, for simplicity.
- [DCOS_OSS-2438](https://jira.mesosphere.com/browse/DCOS_OSS-2438) Remove shift $(($OPTIND - 1)) from dcos-install.sh
- [DCOS_OSS-](https://jira.mesosphere.com/browse/DCOS_OSS-) Foo the Bar so it stops Bazzing.
___
All PRs …
=> DCOS_OSS-2438 - Remove use of $OPTIND in dcos-install.sh

CHANGES.md, gen/build_deploy/bash.py
This adds a check to the installer that checks whether the `raid1` and `dm_raid` kernel modules that are required by DSS are loaded or not.
If they're not loaded, it does _not_ fail the installation. It only prints a warning message to notify the user that usage of DSS depends on `raid1` and `dm_raid` being loaded.
This is what it looks like when a module is not loaded:
And this is what it looks like when both are loaded:
- [[DCOS-49088] Add a new pre-install check for RAID kernel modules to installer bash script - JIRA](https://jira.mesosphere.com/browse/DCOS-49088) …
=> DCOS-49088 - Check in installer if DSS kernel modules are loaded

packages/mesos/build
This is a cherry pick of 090b56c , which landed on the 1.11.10 tag only.  The reason for the disjointed merge was to maintain secrecy of the security hole prior to fixing it immediately once the CVE's embargo was lifted.
This is the 1.11 version of #4620.
- [DCOS-49211](https://jira.mesosphere.com/browse/DCOS-49211) Enable mesos launcher sealing for upstream branches.
- [DCOS-48052](https://jira.mesosphere.com/browse/DCOS-48052) Mesos containerizer launch binary and command executor are under the risk of being overwritten.
- [CVE-2019-5736](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019 …
=> [1.11] Enabled mesos launcher sealing.

packages/mesos/build
This is a cherry pick of 32a013a , which landed on the 1.12.2 tag only.  The reason for the disjointed merge was to maintain secrecy of the security hole prior to fixing it immediately once the CVE's embargo was lifted.
- [DCOS-49211](https://jira.mesosphere.com/browse/DCOS-49211) Enable mesos launcher sealing for upstream branches.
- [DCOS-48052](https://jira.mesosphere.com/browse/DCOS-48052) Mesos containerizer launch binary and command executor are under the risk of being overwritten.
- [CVE-2019-5736](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5736) Runc at risk of being …
=> Enabled mesos launcher sealing.

fetch_cluster_logs.bash
This makes it easier to debug integration tests by ensuring we pick up all logs instead of just logs since the most recent reboot.
- [DCOS-49963](https://jira.mesosphere.com/browse/DCOS-49963) Collect all systemd logs in integration tests
- [DCOS-45732](https://jira.mesosphere.com/browse/DCOS-45732) test_if_ucr_app_can_be_deployed fails with Application deployment failed - Agents not reachable
=> DCOS-49963 - Update fetch_cluster_logs.bash to include logs from the beginning of time instead of current reboot.

fetch_cluster_logs.bash
This makes it easier to debug integration tests by ensuring we pick up all logs instead of just logs since the most recent reboot.
- [DCOS-49963](https://jira.mesosphere.com/browse/DCOS-49963) Collect all systemd logs in integration tests
- [DCOS-45732](https://jira.mesosphere.com/browse/DCOS-45732) test_if_ucr_app_can_be_deployed fails with Application deployment failed - Agents not reachable
=> [BACKPORT] [1.10] DCOS-49963 - Update fetch_cluster_logs.bash to include logs from the beginning of time instead of current reboot.

fetch_cluster_logs.bash
This makes it easier to debug integration tests by ensuring we pick up all logs instead of just logs since the most recent reboot.
- [DCOS-49963](https://jira.mesosphere.com/browse/DCOS-49963) Collect all systemd logs in integration tests
- [DCOS-45732](https://jira.mesosphere.com/browse/DCOS-45732) test_if_ucr_app_can_be_deployed fails with Application deployment failed - Agents not reachable
=> [BACKPORT] [1.12] DCOS-49963 - Update fetch_cluster_logs.bash to include logs from the beginning of time instead of current reboot.

fetch_cluster_logs.bash
This makes it easier to debug integration tests by ensuring we pick up all logs instead of just logs since the most recent reboot.
- [DCOS-49963](https://jira.mesosphere.com/browse/DCOS-49963) Collect all systemd logs in integration tests
- [DCOS-45732](https://jira.mesosphere.com/browse/DCOS-45732) test_if_ucr_app_can_be_deployed fails with Application deployment failed - Agents not reachable
=> [BACKPORT] [1.11] DCOS-49963 - Update fetch_cluster_logs.bash to include logs from the beginning of time instead of current reboot.

CHANGES.md, packages/rexray/buildinfo.json
Signed-off-by: Chris Gianelloni <cgianelloni@applause.com>
Version bump to the latest release of REX-Ray, which includes support for
AWS NVMe storage. Users will still be required to provide `udev` scripts
and provide the `nvme-cli` package on the host. Details can be found in
the original REX-Ray [pull request](https://github.com/rexray/rexray/pull/1252)
- [DCOS_OSS-4316](https://jira.mesosphere.com/browse/DCOS_OSS-4316) Support NVMe EBS volumes
- [COPS-3961](https://jira.mesosphere.com/browse/COPS-3961) Support NVMe EBS volumes …
=> DCOS_OSS-4316 REX-Ray: bump to v0.11.4

gen/aws/templates/cloudformation.json, gen/build_deploy/aws.py, gen/tests/test_installer_aws.py
* Use m5.large as the default instance type.
* Update CoreOS AMI used from the AMI in dcos-images.
=> DCOS-18825- Update CORE OS AMI used in CloudFormation templates.

CHANGES.md, gen/dcos-config.yaml, packages/dcos-integration-test/extra/test_metrics.py
Exposes result of exhibitor status endpoint as a telegraf metric.
- [DCOS-45353](https://jira.mesosphere.com/browse/DCOS-45353) Exhibitor instrumentation
=> telegraf: add exhibitor status metrics

packages/dcos-integration-test/extra/test_ucr.py
Add an integration for launching pod with non-root user and ephemeral volume
- [DCOS-47640](https://jira.mesosphere.com/browse/DCOS-47640) Add an integration test for launching pod with non-root user and ephemeral volume.
- [DCOS-47501](https://jira.mesosphere.com/browse/DCOS-47501) Pod cannot be launched with non-root user.
- [DCOS-39884](https://jira.mesosphere.com/browse/DCOS-39884) Volume ownership and permission improvements.
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE …
=> Add a test for launching pod with non-root user and ephemeral volume.

prep_local_windows.ps1
Update to windows scripts to remove pip upgrade errors
- https://jira.mesosphere.com/browse/DCOS-45501 - teamcity/dcos/build/dcos/windows fails at start_dcos_windows_build.ps1 with PermissionError
___ …
=> [BACKPORT][1.12] Updating pip upgrade on windows to remove error message

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
[MESOS-7124](https://issues.apache.org/jira/browse/MESOS-7124) - Replace monadic type get() functions with operator*.
[MESOS-9637](https://issues.apache.org/jira/browse/MESOS-9637) - Impossible to CREATE a volume on resource provider resources over the operator API.
[MESOS-9643](https://issues.apache.org/jira/browse/MESOS-9643) - Make setting volume ownership asynchronous in volume gid manager.
https://github.com/apache/mesos/compare/a5b9f6e1cdb2ec26baf6e49706e1a0d59f3ce4d1...fe83816d51d3dd134376621944ef556ea52b4900
=> [master] Bump Mesos to nightly master fe83816

packages/metronome/buildinfo.json
- [DCOS-48948](https://jira.mesosphere.com/browse/DCOS-48948) Bump DC/OS 1.13 to latest Metronome
* [MARATHON-8555](https://jira.mesosphere.com/browse/MARATHON-8555) Parameter --leader_proxy_max_open_connections does not actually allow more concurrent connections
* [MARATHON-8566](https://jira.mesosphere.com/browse/MARATHON-8566) Fix race condition causing deployment info to not be available
* [MARATHON-8555](https://jira.mesosphere.com/browse/MARATHON-8577) Include app-id in illegal-state-exception …
=> bump of metronome 0.6.11 on dcos 1.13 master

packages/dcos-integration-test/extra/requirements.txt, packages/dcos-test-utils/buildinfo.json
Previously, dcos-test-utils would raise an exception if jobs results were not yet ready, but exceptions are not retried, so we instead log and return False.
- [DCOS_OSS-4877](https://jira.mesosphere.com/browse/DCOS_OSS-4877) Waiting for job run to be finished, but history for that job run is not available
=> [BACKPORT] [1.10] DCOS_OSS-4877 - Bump dcos-test-utils to latest.

packages/dcos-integration-test/extra/requirements.txt, packages/dcos-test-utils/buildinfo.json
Previously, dcos-test-utils would raise an exception if jobs results were not yet ready, but exceptions are not retried, so we instead log and return False.
- [DCOS_OSS-4877](https://jira.mesosphere.com/browse/DCOS_OSS-4877) Waiting for job run to be finished, but history for that job run is not available
=> [BACKPORT] [1.12] DCOS_OSS-4877 - Bump dcos-test-utils to latest.

packages/dcos-integration-test/extra/requirements.txt, packages/dcos-test-utils/buildinfo.json
Previously, dcos-test-utils would raise an exception if jobs results were not yet ready, but exceptions are not retried, so we instead log and return False.
- [DCOS_OSS-4877](https://jira.mesosphere.com/browse/DCOS_OSS-4877) Waiting for job run to be finished, but history for that job run is not available
=> [BACKPORT] [1.11] DCOS_OSS-4877 - Bump dcos-test-utils to latest.

packages/dcos-integration-test/extra/requirements.txt, packages/dcos-test-utils/buildinfo.json
Previously, dcos-test-utils would raise an exception if jobs results were not yet ready, but exceptions are not retried, so we instead log and return False.
- [DCOS_OSS-4877](https://jira.mesosphere.com/browse/DCOS_OSS-4877) Waiting for job run to be finished, but history for that job run is not available
=> DCOS_OSS-4877 - Bump dcos-test-utils to latest.

packages/dcos-integration-test/extra/test_metronome.py, packages/dcos-integration-test/extra/test_rexray.py
This mutes tests that are known to be flakey.
- [DCOS-50823](https://jira.mesosphere.com/browse/DCOS-50823) Mute flakey tests.
- [DCOS-46578](https://jira.mesosphere.com/browse/DCOS-46578) DC/OS Enterprise - test_metronome.test_metronome flake - Exception: Job run failed - operation was not completed in 300 seconds.
=> [BACKPORT] [1.11] DCOS-50823 - Mute frequently flakey tests.

CHANGES.md, packages/marathon/buildinfo.json
- [DCOS_OSS-4563](https://jira.mesosphere.com/browse/DCOS_OSS-4563) Bump Marathon 1.8.x on DCOS 1.13
- [DCOS_OSS-4325](https://jira.mesosphere.com/browse/DCOS_OSS-4325) Allow operator to reset Marathon task launch delay.
- [MARATHON-8587](https://jira.mesosphere.com/browse/MARATHON-8587) Marathon metrics HTTP handler exception
- [MARATHON-8431](https://jira.mesosphere.com/browse/MARATHON-8431) Remove sync proxy
- [MARATHON-8485](https://jira.mesosphere.com/browse/MARATHON-8485) GroupsResource should Creation of a group with same path as an existing app should be prohibited
- …
=> bumping marathon to 1.8 on dcos 1.13

gen/dcos-config.yaml
DSS (master, and soon the 0.5.x series) has been upgraded to leverage the new FrameworkInfo.OfferFilters API in order to explicitly set its own min-allocatable-resources. Thus, this global setting is no longer needed.
- [DCOS-49202](https://jira.mesosphere.com/browse/DCOS-49202) Remove "|disk:32" from the min_allocatable_resources flag.
- [DCOS-47867](https://jira.mesosphere.com/browse/DCOS-47867) Update DSS to specify the resources that it's interested in.
* DSS is the only consumer of disk-only offers
* Now that DSS has been upgraded, this global change is no longer needed. Nothing else should break, no additional test needed.
If you are changing components or …
=> gen: remove `disk:32` from min allocatable rez

gen/dcos-config.yaml, packages/adminrouter/extra/src/includes/metrics-http-level.conf, packages/adminrouter/extra/src/includes/metrics-location-level.conf, packages/adminrouter/extra/src/includes/metrics-server-level.conf, packages/adminrouter/extra/src/test-harness/tests/test_metrics.py, packages/dcos-integration-test/extra/test_metrics.py, packages/telegraf/buildinfo.json
This PR adds fine-grained Admin Router metrics to the Telegraf output. We introduce a `nginx_vts_processor` plugin in Telegraf to transform Prometheus metrics output from the Nginx VTS module which can then be easily parsed in Grafana to build better dashboards.
This greatly reduces the amount of time-series ending up in Prometheus because all unused metrics are dropped on the Telegraf level.
As a follow-up we need to look into long URI and useragent string corrupting the Nginx VTS module Prometheus output. With this PR we deactivated the useragent and URI output for this reason.
Given the experience from SOAK and the MWTs we can now also think about reducing the shared memory region size of the Nginx VTS module.
These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment …
=> Bump Telegraf to include nginx_vts_processor

CHANGES.md, packages/telegraf/buildinfo.json
This telegraf update prefixes any prometheus metric which starts with a number with an underscore.
So, `123.foo.bar` becomes `_123_foo_bar` instead of `123_foo_bar`
This prevents Prometheus dropping such metrics.
- [DCOS_OSS-4900](https://jira.mesosphere.com/browse/DCOS_OSS-4900) Metric names can begin with numbers in Telegraf Prometheus output plugin
=> [1.12] Fix illegal prometheus metric names

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
MESOS-9661 - Fixed an agent crash bug when SLRP recovers dropped operations.
https://github.com/apache/mesos/compare/fe83816d51d3dd134376621944ef556ea52b4900...bbfa90d5faa422436c7da271d08e3fb94b94fc1c
=> [master] Bump Mesos to nightly master bbfa90d

packages/mesos/build
This is a cherry pick of 0681401 , which landed on the 1.10.11 tag only.  The reason for the disjointed merge was to maintain secrecy of the security hole prior to fixing it immediately once the CVE's embargo was lifted.
This is the 1.10 version of #4620.
- [DCOS-49211](https://jira.mesosphere.com/browse/DCOS-49211) Enable mesos launcher sealing for upstream branches.
- [DCOS-48052](https://jira.mesosphere.com/browse/DCOS-48052) Mesos containerizer launch binary and command executor are under the risk of being overwritten.
- [CVE-2019-5736](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019 …
=> [1.10] Enabled mesos launcher sealing.

CHANGES.md
This telegraf update prefixes any prometheus metric which starts with a number with an underscore.
So, `123.foo.bar` becomes `_123_foo_bar` instead of `123_foo_bar`
This prevents Prometheus dropping such metrics.
- [DCOS_OSS-4900](https://jira.mesosphere.com/browse/DCOS_OSS-4900) Metric names can begin with numbers in Telegraf Prometheus output plugin
=> Fix illegal prometheus metric names

gen/calc.py
- adding install controllable capabilities for turning on gpu support i…n marathon and metronome, along with validation
- [DCOS_OSS-4824](https://jira.mesosphere.com/browse/DCOS_OSS-4824) Metronome needs to be prepared for GPU by default on DCOS 1.13.
=> Metronome / Marathon Removal of "Undefined" GPU Option  on DCOS 1.13

packages/dcos-integration-test/extra/test_checks.py, packages/dcos-integration-test/extra/test_networking.py
This mutes tests that are known to be flakey.
- [DCOS-50823](https://jira.mesosphere.com/browse/DCOS-50823) Mute flakey tests.
- [DCOS-50427](https://jira.mesosphere.com/browse/DCOS-50427) test_networking.test_vip_ipv6 fails on an unrelated change
- [DCOS-50400](https://jira.mesosphere.com/browse/DCOS-50400) test_checks.test_checks_cli  failed with a Metronome Exception
=> DCOS-50823 - Mute test_checks_cli and test_vip_ipv6.

packages/dcos-integration-test/extra/test_rexray.py
This mutes tests that are known to be flakey.
- [DCOS-50823](https://jira.mesosphere.com/browse/DCOS-50823) Mute flakey tests.
- [DCOS_OSS-4922](https://jira.mesosphere.com/browse/DCOS_OSS-4922) test_rexray.test_move_external_volume_to_new_agent fails on master.
=> DCOS-50823 - Mute flaky test_rexray.

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/5e234c8d8edc1bb73ba557f5774c609fa460c9e7...0f8faa042dc51384928fef8b6a39baed222e8a30
=> [1.12] Bump Mesos to nightly 1.7.x 0f8faa0

CHANGES.md, packages/docker-gc/buildinfo.json, packages/docker-gc/extra/dcos-docker-gc.service
=> [1.12]  DCOS_OSS-1502 - dcos-docker-gc does not clean leftover volumes

packages/dcos-integration-test/extra/test_networking.py
Added a retry to `test_dcos_net_cluster_identity` to prevent it being flake.
- [DCOS-47438](https://jira.mesosphere.com/browse/DCOS-47438) test_networking.test_dcos_net_cluster_identity[true] non-zero exit status 1
___ …
=> DCOS-47438 - Add retry to cluster identity test

packages/dcos-integration-test/extra/test_rexray.py
* DCOS_OSS-4922 - Mute test_rexray.test_move_external_volume_to_new_agent
The failure was observed in this train PR - https://github.com/mesosphere/dcos-enterprise/pull/5038
=> DCOS_OSS-4922 - Mute test_rexray.test_move_external_volume_to_new_agent

CHANGES.md, dcos_installer/test_backend.py, gen/calc.py, packages/openssl/build, packages/openssl/buildinfo.json
* DCOS-50051 - FIPS complaint DC/OS build on top of stable DC/OS 1.12.3 
This PR is to create the FIPS compliant DC/OS build. The Open DC/OS and Enterprise DC/OS artifacts can be utilized for creating a release.
```
[centos@ip-10-10-0-101 openssl--805434a819503df1af1d2a999c2a04a24f092654]$ OPENSSL_FIPS=1 LD_LIBRARY_PATH=lib bin/openssl version
OpenSSL 1.0.2r-fips  26 Feb 2019
```
=> DC/OS 1.12.3-fips with OpenSSL 1.0.2r-fips.

packages/dcos-check-runner/extra/dcos-checks-api-agent.service, packages/dcos-check-runner/extra/dcos-checks-api-master.service
This PR fixes a bug where dcos-checks-runner would start before DNS is ready, causing lookups to fail and breaking some builds. 
[This](https://jira.mesosphere.com/browse/DCOS-47608?focusedCommentId=252609&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-252609) comment on the ticket explains the issue further.
- [DCOS-47608](https://jira.mesosphere.com/browse/DCOS-47608)
___ …
=> Check that DNS is ready before starting checks

packages/adminrouter/extra/src/includes/server/master.conf, packages/adminrouter/extra/src/includes/server/open/agent.conf, packages/adminrouter/extra/src/includes/server/open/master.conf, packages/adminrouter/extra/src/test-harness/tests/open/test_metrics.py, packages/adminrouter/extra/src/test-harness/tests/test_metrics.py
This PR is continuation of the work started earlier: https://github.com/dcos/dcos/pull/3996
It annotates the following upstreams in AR configuration files: Exhibitor, DC/OS Net, DC/OS Log, DC/OS Diagnostics.
https://jira.mesosphere.com/browse/DCOS-47256
=> Add annotations to AR config for static upstreams IAM, Exhibitor, Diagnostics, Log, Net, Pkgpanda, Metrics, Checks, Mesos DNS

packages/bouncer/extra/dcos_add_user.py, packages/dcos-integration-test/extra/test_legacy_user_management.py
This PR fixes the bug in dcos_add_user.py script and adds integration tests to check the user addition in Open DC/OS.
https://jira.mesosphere.com/browse/DCOS_OSS-4930
=> Fix dcos_add_user.py script for OSS

CHANGES.md, gen/calc.py, gen/dcos-config.yaml, gen/tests/test_adminrouter_ui.py, packages/adminrouter/docker/Dockerfile, packages/adminrouter/docker/adminrouter-ui-security.conf, packages/adminrouter/extra/src/includes/server/master.conf, packages/adminrouter/extra/src/test-harness/tests/test_master.py
Provides a new configuration `adminrouter_x_frame_options` that allows configuring `X-Frame-Options` value for DC/OS UI responses.
- [DCOS-49594](https://jira.mesosphere.com/browse/DCOS-49594) Allow X-Frame-Options to be set in cluster configuration
=> gen: Make X-Frame-Options configurable for DC/OS UI

packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/bbfa90d5faa422436c7da271d08e3fb94b94fc1c...0635d234e0bd6589bba3c75f1c580990abfc0f73
https://github.com/dcos/dcos-mesos-modules/compare/92e932c524fac7349d3a1e31b780bacefdfd21c5...18a3002b4b2ded64ce85e490f6fa2da4cea15dc4
=> [master] Bump Mesos to nightly master 0635d23

packages/dcos-check-runner/extra/dcos-checks-api.service
See: https://github.com/dcos/dcos/pull/4884
This PR fixes a bug where dcos-checks-runner would start before DNS is ready, causing lookups to fail and breaking some builds. 
[This](https://jira.mesosphere.com/browse/DCOS-47608?focusedCommentId=252609&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-252609) comment on the ticket explains the issue further.
- [DCOS-47608](https://jira.mesosphere.com/browse/DCOS-47608)
___
**PLEASE FILL IN THE TEMPLATE ABOVE** …
=> [1.12] Check that DNS is ready before starting checks

packages/dcos-integration-test/extra/test_networking.py
Added a retry to `test_dcos_net_cluster_identity` to prevent it being flake.
- [DCOS-47438](https://jira.mesosphere.com/browse/DCOS-47438) test_networking.test_dcos_net_cluster_identity[true] non-zero exit status 1
___ …
=> [1.11] DCOS-47438 - Add retry to cluster identity test

packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/0f8faa042dc51384928fef8b6a39baed222e8a30...ad85a647c06190dd222e7871b8575cf4d04d4098
https://github.com/dcos/dcos-mesos-modules/compare/35d3b464be910867ccb308fb57bd981747ed8568...c4a639e1c58f448d60159a7eb5e58d17f93c36f9
=> [1.12] Bump Mesos to nightly 1.7.x ad85a64

CHANGES.md, packages/docker-gc/extra/dcos-docker-gc.service
There's a bug in docker-gc that causes the systemd unit to fail
(https://github.com/spotify/docker-gc/issues/201)
- [DCOS_OSS-4952](https://jira.mesosphere.com/browse/DCOS_OSS-4952) dcos-docker-gc systemd unit is constantly unhealthy
___ …
=> DCOS_OSS-4952 don't remove volumes per default

packages/dcos-integration-test/extra/test_networking.py
Added a retry to `test_dcos_net_cluster_identity` to prevent it being flake.
- [DCOS-47438](https://jira.mesosphere.com/browse/DCOS-47438) test_networking.test_dcos_net_cluster_identity[true] non-zero exit status 1
___ …
=> [1.12] DCOS-47438 - Add retry to cluster identity test

CHANGES.md, gen/calc.py, gen/dcos-config.yaml, gen/tests/test_adminrouter_ui.py, packages/adminrouter/docker/Dockerfile, packages/adminrouter/docker/adminrouter-ui-security.conf, packages/adminrouter/extra/src/includes/server/master.conf, packages/adminrouter/extra/src/test-harness/tests/test_master.py
This is a backport of https://github.com/dcos/dcos/pull/4888 with changed default value from `DENY` to `SAMEORIGIN`.
Provides a new configuration `adminrouter_x_frame_options` that allows configuring `X-Frame-Options` value for DC/OS UI responses.
- [DCOS-49594](https://jira.mesosphere.com/browse/DCOS-49594) Allow X-Frame-Options to be set in cluster configuration
=> [1.12] gen: Make X-Frame-Options configurable for DC/OS UI

gen/aws/templates/advanced/advanced-master.json, gen/aws/templates/advanced/advanced-priv-agent.json, gen/aws/templates/advanced/advanced-pub-agent.json, gen/aws/templates/advanced/infra.json, gen/aws/templates/advanced/zen.json, gen/aws/templates/cloudformation.json, gen/build_deploy/aws.py
was observed due to resource unavailability of the NAT AMI. The error message in the console had this errror
```
Your requested instance type (m3.medium) is not supported in your requested Availability Zone (us-west-2d). Please retry your request by not specifying an Availability Zone or choosing us-west-2c, us-west-2b, us-west-2a. (Service: AmazonEC2; Status Code: 400; Error Code: Unsupported; Request ID: 11bba17d-87a4-4e7c-a0b1-3d3c09257a4a)
```
Attempting to resolve this issue by upgrading the NAT AMI provided by Amazon to the latest version (https://aws.amazon.com/amazon-linux-ami/2018.03-release-notes/) 
* https://jira.mesosphere.com/browse/DCOS-18825
=> Update NAT AMIS to address CloudFormation Resource Errors

packages/dcos-integration-test/extra/test_checks.py
After fixing the timeout that caused the test to fail, this commit now
unmutes the test.
- [[DCOS-50400] test_checks.test_checks_cli  failed with a dcos-checks exceeded timeout 1s - JIRA](https://jira.mesosphere.com/browse/DCOS-50400)
- 
___ …
=> DCOS-50400 - Unmute fixed tests

packages/adminrouter/extra/src/includes/metrics-upstream-location-level.conf, packages/adminrouter/extra/src/includes/server/master.conf, packages/adminrouter/extra/src/includes/server/open/agent.conf, packages/adminrouter/extra/src/includes/server/open/master.conf, packages/adminrouter/extra/src/test-harness/tests/open/test_metrics.py
This PR annotates all Admin Router location directives that include a `proxy_pass` other than
agent proxy locations or locations under `/service`. We refer to the currently annotated set of locations as Upstreams (apart from Mesos all of the annotated requests are handled locally on a master node).
Each Upstream is given an `$upstream_tag` that identifies it in terms of DC/OS terminology. Each location annotation also makes sure that Upstream metrics are tagged with the `$original_uri` to Admin Router rather than the rewritten `$uri` that was actually used in the `proxy_pass`.
- [DCOS_OSS-4945](https://jira.mesosphere.com/browse/DCOS_OSS-4945) Annotate all upstreams including original URI for Admin …
=> Annotate all upstreams including original URI

CHANGES.md
Change the release note for `X-Frame-Options` config option default value, which has been changed from `SAMEORIGIN` to `DENY`.
- [DCOS-49594](https://jira.mesosphere.com/browse/DCOS-49594) Allow X-Frame-Options to be set in cluster configuration
=> CHANGES.md: Improve X-Frame-Options note

packages/adminrouter/extra/src/includes/metrics-server-level.conf
Small PR that adds collecting HTTP status codes for server level request useragent and URI reporting as well.
I've tested this locally on my machine.
___
=> Add HTTP status collection to server level

gen/dcos-config.yaml, packages/dcos-integration-test/extra/test_metrics.py
Changes `dcos-telegraf` to drop unnecessary metrics reported by NGINX `vts` module. The removed metrics are `nginx_vts_server_*` and `nginx_vts_upstream_*`.
- [DCOS_OSS-4960](https://jira.mesosphere.com/browse/DCOS_OSS-4960) Drop default VTS module metrics
=> gen/dcos-config.yaml: Remove nginx_vts_upstream and nginx_vts_server metrics

gen/dcos-config.yaml, packages/dcos-integration-test/extra/test_metrics.py
This was a collaborative effort with @mhrabovcin .
This drops some inaccurate measurements from Telegraf.
- [DCOS_OSS-4959](https://jira.mesosphere.com/browse/DCOS_OSS-4959) Drop latency measurements
=> Start of test that we drop nginx_vts_*_request_seconds* metrics

CHANGES.md, packages/telegraf/buildinfo.json
(backport of #4928) The HTTP client used in the Mesos input plugin was setting its own timeout to 4s, which was effectively taking precedent over the timeout configured in DCOS (30s). We are now using the configured timeout in the http client and have removed the timeout query param from the mesos snapshot request altogether to avoid emitting partial metrics if a timeout were hit in mesos.
- [DCOS-50672](https://jira.mesosphere.com/browse/DCOS-50672) Mesos metrics dropping due to snapshots timeout
=> [1.12] Use configured timeout in http client instead of mesos query param

CHANGES.md, gen/dcos-config.yaml
This is a 1.12 backport of #4939.
- [DCOS-50994](https://jira.mesosphere.com/browse/DCOS-50994) Telegraf started to drop metrics on some agents
N/A
=> (1.12) Telegraf scale tuning

packages/telegraf/buildinfo.json
The HTTP client used in the Mesos input plugin was setting its own timeout to 4s, which was effectively taking precedent over the timeout configured in DCOS (30s). We are now using the configured timeout in the http client and have removed the timeout query param from the mesos snapshot request altogether to avoid emitting partial metrics if a timeout were hit in mesos.
- [DCOS-50672](https://jira.mesosphere.com/browse/DCOS-50672) Mesos metrics dropping due to snapshots timeout
=> [1.13] Use configured timeout in http client instead of mesos query param

gen/dcos-config.yaml
This PR edits Telegraf config to help prevent dropped metrics on busy agents. This is accomplished by increasing the number of metrics output pluggins can buffer before they start dropping metrics (`metric_buffer_limit`), and by increasing the collection `interval` for the `dcos_statsd` input plugin, which reduces the rate at which it collects metrics, thus reducing pressure on output buffers.
This PR also reduces the default `interval` for all input plugins to 10s. Most inputs don't need to be throttled on a busy agent, since they emit a consistent number of metrics that doesn't increase as workloads are executed on an agent.
Last, this PR sets `expiration_interval` for the `prometheus_client` output to its default value, instead of using it implicitly.
I'll backport this fix to 1.12, so …
=> Telegraf scale tuning

packages/marathon/buildinfo.json
Marathon health checks is a deprecated feature and customers are strongly recommended to switch to Mesos health checks for scalability reasons. However, we've seen a number of issues when excessive number of Marathon health checks (HTTP and TCP) would overload parts of Marathon. Hence we introduced a new parameter `--max_concurrent_marathon_health_checks` that defines maximum number (256 by default) of *Marathon* health checks (HTTP/S and TCP) that can be executed concurrently in the given moment. Note that setting a big value here and using many services with Marathon health checks will overload Marathon leading to internal timeouts and unstable behavior.  
The default GPU Scheduling Behavior has been changed to `restricted`, and `undefined` has been deprecated and will be removed in …
=> Bump Marathon to 1.8.164 on DC/OS 1.13

packages/telegraf/extra/start_telegraf.sh, packages/telegraf/extra/tools/extract_fault_domain.py
The Telegraf startup script intends to run the fault domain detect script and extract the names of the region and zone from its output, in order to set these values in environment variables that can be referenced in Telegraf config. The current implementation is setting these environment variables in a subshell, which is then immediately exited, discarding the environment variables, and causing Telegraf to tag metrics with the names of the env vars it intends to reference.
This commit fixes the startup script by setting these environment variables in the same shell that execs Telegraf. This is accomplished by modifying extract_fault_domain.py to print either the zone or region with each run, and then running it twice to get both the zone and region names and assign them to env vars.
I …
=> Fix fault domain metric tags

CHANGES.md, packages/exhibitor/buildinfo.json
This bumps DC/OS' ZooKeeper from version 3.4.13 to version 3.4.14.
https://jira.mesosphere.com/browse/DCOS_OSS-4988
=> Bump ZooKeeper to 3.4.14 [1.12]

packages/metronome/buildinfo.json
- [DCOS_OSS-4994](https://jira.mesosphere.com/browse/DCOS_OSS-4994) Release Metronome 1.6.18 on Master.
- [DCOS_OSS-4636 ](https://jira.mesosphere.com/browse/DCOS_OSS-4636 ) Failure when restart policy is ON_FAILURE. This bug was introduced through the fix of another bug regarding stopping invalid extra instances of a job run. Metronome should not check the launch queue when a restart is invoked.
- [DCOS_OSS-4636 ](https://jira.mesosphere.com/browse/DCOS_OSS-4978 ) Allow using IS operator when creating jobs. This was broken since introduction of the IS operator, which replaced EQ but was not a …
=> metronome 0.6.18 bump on dcos 1.11

packages/metronome/buildinfo.json
- [DCOS_OSS-4994](https://jira.mesosphere.com/browse/DCOS_OSS-4994) Release Metronome 1.6.18 on Master.
- [DCOS_OSS-4636 ](https://jira.mesosphere.com/browse/DCOS_OSS-4636 ) Failure when restart policy is ON_FAILURE. This bug was introduced through the fix of another bug regarding stopping invalid extra instances of a job run. Metronome should not check the launch queue when a restart is invoked.
- [DCOS_OSS-4636 ](https://jira.mesosphere.com/browse/DCOS_OSS-4978 ) Allow using IS operator when creating jobs. This was broken since introduction of the IS operator, which replaced EQ but was not a …
=> metronome 0.6.18 bump on dcos 1.12

packages/dcos-integration-test/extra/test_metronome.py
Unmute test_metronome since the bump to 0.6.11 two weeks ago was supposed to mitigate flakes
- [DCOS-46578](https://jira.mesosphere.com/browse/DCOS-46578) DC/OS Enterprise - test_metronome.test_metronome flake - Exception: Job run failed - operation was not completed in 300 seconds.
Other tickets related to this change: n/a
___
=> unmute test_metronome

CHANGES.md, packages/metronome/buildinfo.json
- [DCOS_OSS-4994](https://jira.mesosphere.com/browse/DCOS_OSS-4994) Release Metronome 1.6.18 on Master.
- [DCOS_OSS-4636 ](https://jira.mesosphere.com/browse/DCOS_OSS-4636 ) Failure when restart policy is ON_FAILURE. This bug was introduced through the fix of another bug regarding stopping invalid extra instances of a job run. Metronome should not check the launch queue when a restart is invoked.
- [DCOS_OSS-4636 ](https://jira.mesosphere.com/browse/DCOS_OSS-4978 ) Allow using IS operator when creating jobs. This was broken since introduction of the IS operator, which replaced EQ but was not a …
=> Metronome 0.6.18 bump to master

packages/fluent-bit/buildinfo.json
Fluent Bit in EE and EE strict modes currently does not have the permissions to read `/var/log/journal` which belongs to the `systemd-journal` group. This adds the Fluent Bit user `dcos_fluent_bit` to the group, which allows it to access the journald logs. I've tested this on a cluster. Without this update, Fluent Bit was not collecting any logs from journald. With the fix, I saw that `dcos_fluent_bit` belonged to the `systemd-journal` group, and saw journald logs coming in.
- [DCOS_OSS-5004](https://jira.mesosphere.com/browse/DCOS_OSS-5004) Add dcos_fluent_bit user to systemd-journal group
=> [1.13] Add dcos_fluent_bit user to systemd-journal group

CHANGES.md, packages/adminrouter/extra/src/lib/service.lua
This PR fixes a bug in service.lua library. See corresponding JIRA ticket for details. This is a backport of a change implemented as part of DCOS_OSS-4950.
https://jira.mesosphere.com/browse/DCOS_OSS-4999
- [] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
No test is included since the behaviour of AR resulting from the bug is non-deterministic.
=> [1.11] Fix lua variable scope bug in service.lua

CHANGES.md, packages/adminrouter/extra/src/lib/service.lua
This PR fixes a bug in service.lua library. See corresponding JIRA ticket for details. This is a backport of a change implemented as part of DCOS_OSS-4950.
https://jira.mesosphere.com/browse/DCOS_OSS-4999
No test is included since the behaviour of AR resulting from the bug is non-deterministic.
=> [1.12] Fix lua variable scope bug in service.lua

CHANGES.md, packages/adminrouter/extra/src/lib/service.lua
This PR fixes a bug in service.lua library. See corresponding JIRA ticket for details. This is a backport of a change implemented as part of DCOS_OSS-4950.
https://jira.mesosphere.com/browse/DCOS_OSS-4999
No test is included since the behaviour of AR resulting from the bug is non-deterministic.
=> [1.10] Fix lua variable scope bug in service.lua

packages/dcos-integration-test/extra/test_metrics.py
This PR adds an integration test checking that nginx_service_* metrics are reported through Telegraf.
https://jira.mesosphere.com/browse/DCOS_OSS-5014
=> Add integration test for checking nginx_service_* Telegraf metrics

CHANGES.md, packages/adminrouter/extra/src/includes/service-location.common.conf, packages/adminrouter/extra/src/test-harness/tests/test_master.py
This PR causes adminrouter to stop stripping the `Accept-Encoding` header from requests to `/service/<service-name>` before it proxies them to service backends. This allows service backends to compress responses.
- [DCOS_OSS-4906](https://jira.mesosphere.com/browse/DCOS_OSS-4906) Admin Router service endpoint: forward Accept-Encoding header to upstream
N/A
=> Pass Accept-Encoding header to service backends

gen/dcos-config.yaml
This is a subtle change that changes the processing order for
operations associated with launching, monitoring, or stopping
containers.  Effectively, the Mesos agent will try the Mesos
containerizer before the Docker containerizer.
This change improves performance of launching Mesos containers when
there are a large number of Docker containers running on the same
agent.  The Docker containerizer tends to spend most of its time
waiting on the Docker daemon to respond, sometimes blocking further
progress if there are too many containers.  Sometimes, this waiting
will cause Mesos containers to take excessively long times to launch,
as we get blocked while executing the launch command on each
containerizer, *in order*.  If …
=> Changed order of containerizers on Mesos agents.

packages/erlang/buildinfo.json
Upgrade OTP version to 21.3.3 w/ ERL-900
- [DCOS_OSS-4943](https://jira.mesosphere.com/browse/DCOS_OSS-4943) Driver gone away without deselecting
- [ERL-900](https://bugs.erlang.org/browse/ERL-900) procket: driver gone away without deselecting
https://github.com/erlang/otp/compare/620ac3e68c5bc8b36143965fcf2892a07dc005c4...04c57e50c50d167b65c625d6a9fece8d7b4c7954
https://github.com/erlang/otp/commit/04c57e50c50d167b65c625d6a9fece8d7b4c7954
___ …
=> Upgrade OTP version

packages/telegraf/extra/dcos-telegraf.service, packages/telegraf/extra/start_telegraf.sh, packages/telegraf/extra/tools/migrate_containers_dir.sh
The mesos module's containers directory is owned by root. We therefore migrate
its contents in an ExecPre step, instead of in Exec using the dcos_telegraf
user.
- [DCOS-50697](https://jira.mesosphere.com/browse/DCOS-50697) Evidence of Telegraf failures after upgrading from 1.11 to 1.13.0-alpha
=> Migrate telegraf containers dir as root

docs/admin-ports.md, gen/calc.py, gen/dcos-config.yaml, packages/fluent-bit/build, packages/fluent-bit/extra/dcos-fluent-bit.service, packages/mesos-modules/buildinfo.json
This PR bumps mesos-modules to pull in https://github.com/dcos/dcos-mesos-modules/pull/105, and adds configuration that directs Mesos agents to send task logs to Fluent Bit.
This also simplifies the Fluent Bit build script by moving the logic for defining Fluent Bit's service name to dcos-config.yaml.
I manually tested that task logs are being sent to Fluent Bit. I launched a Marathon app where tasks echo on a loop, configured dcos-fluent-bit.service on an agent to output logs to stdout, and observed task logs in dcos-fluent-bit.service's journal.
- [DCOS-50078](https://jira.mesosphere.com/browse/DCOS-50078) Integrate Mesos task log module changes with DC/OS
N/A
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), …
=> Send task logs to Fluent Bit

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/2c7cee0fded247da6f8f66e75fc759f0b11be42f...2f8c3d17691df767bb0fac1274077bbc8b6da0f0
=> [master] Bump Mesos to nightly 1.8.x 2f8c3d1

CHANGES.md, packages/rexray/buildinfo.json
*Backport of https://github.com/dcos/dcos/pull/4552 to 1.10*
Version bump to the latest release of REX-Ray, which includes support for
AWS NVMe storage. Users will still be required to provide `udev` scripts
and provide the `nvme-cli` package on the host. Details can be found in
the original REX-Ray [pull request](https://github.com/rexray/rexray/pull/1252)
Signed-off-by: Chris Gianelloni <cgianelloni@applause.com>
(cherry picked from commit b07fc98a0269f26ac8a027ea6c5c91eae4748cd5)
Version bump to the latest release of REX-Ray, which includes support for
AWS NVMe storage. Users will still be required to provide udev scripts
and provide the nvme-cli package on the host. Details can be found in
the original REX-Ray …
=> DCOS_OSS-4316 REX-Ray: bump to v0.11.4 [1.10 Backport] and unmute test_rexray.py

packages/dcos-integration-test/extra/test_rexray.py
This PR unmutes the test in `test_rexray.py` but skips it in strict mode.
- [DCOS_OSS-4922](https://jira.mesosphere.com/browse/DCOS_OSS-4922) test_rexray.test_move_external_volume_to_new_agent fails on master
___
=> dcos-integration-test: skip rexray test in strict mode, unmute it

CHANGES.md, packages/rexray/buildinfo.json
*Backport of https://github.com/dcos/dcos/pull/4552 to 1.11*
Version bump to the latest release of REX-Ray, which includes support for
AWS NVMe storage. Users will still be required to provide `udev` scripts
and provide the `nvme-cli` package on the host. Details can be found in
the original REX-Ray [pull request](https://github.com/rexray/rexray/pull/1252)
Signed-off-by: Chris Gianelloni <cgianelloni@applause.com>
(cherry picked from commit b07fc98a0269f26ac8a027ea6c5c91eae4748cd5)
Version bump to the latest release of REX-Ray, which includes support for
AWS NVMe storage. Users will still be required to provide udev scripts
and provide the nvme-cli package on the host. Details can be found in
the original REX-Ray …
=> DCOS_OSS-4316 REX-Ray: bump to v0.11.4 [1.11 Backport] and unmute test_rexray.py

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/2f8c3d17691df767bb0fac1274077bbc8b6da0f0...0c503b01d3a9428ec9db35d09da5e237d737c570
=> [master] Bump Mesos to nightly 1.8.x 0c503b0

CHANGES.md, packages/rexray/buildinfo.json
*Backport of https://github.com/dcos/dcos/pull/4552 to 1.12*
Version bump to the latest release of REX-Ray, which includes support for
AWS NVMe storage. Users will still be required to provide `udev` scripts
and provide the `nvme-cli` package on the host. Details can be found in
the original REX-Ray [pull request](https://github.com/rexray/rexray/pull/1252)
Signed-off-by: Chris Gianelloni <cgianelloni@applause.com>
(cherry picked from commit b07fc98a0269f26ac8a027ea6c5c91eae4748cd5)
Version bump to the latest release of REX-Ray, which includes support for
AWS NVMe storage. Users will still be required to provide udev scripts
and provide the nvme-cli package on the host. Details can be found in
the original REX-Ray …
=> DCOS_OSS-4316 REX-Ray: bump to v0.11.4 [1.12 Backport] and unmute test_rexray.py

CHANGES.md, gen/calc.py
The configuration variables `aws_secret_access_key` and `exhibitor_azure_account_key` (https://docs.mesosphere.com/1.12/installing/production/advanced-configuration/configuration-reference/#exhibitor-storage-backend) must be marked as secret so that they are not accidentally revealed by diagnostics tools.
- [DCOS-51751](https://jira.mesosphere.com/browse/DCOS-51751) aws_secret_access_key is not hidden in diagnostics bundle …
=> Hide secret keys from user.config.yaml

packages/dcos-integration-test/extra/test_checks.py
This changes the checks API test to log the result before it attempts to assert on the statuses of the checks. If there are any issues, this makes it possible to look at the logs and see the output of any failed checks.
- [DCOS-51593](https://jira.mesosphere.com/browse/DCOS-51593)
___ …
=> Log checks API result before status assertion

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
[MESOS-9729](https://issues.apache.org/jira/browse/MESOS-9729) - Unpublishing a volume that is failed to publish crashes the agent with CSI v1.
[MESOS-9704](https://issues.apache.org/jira/browse/MESOS-9704) - Support docker manifest v2s2 config GC.
https://github.com/apache/mesos/compare/0c503b01d3a9428ec9db35d09da5e237d737c570...dfc217ea19ae265fa7b34853dd929b48561207e3
=> [master] Bump Mesos to nightly 1.8.x dfc217e

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
MESOS-9707 - Calling link::lo() may cause runtime error.
MESOS-9704 - Support docker manifest v2s2 config GC.
MESOS-9692 - Quota may be under allocated for disk resources.
MESOS-9675 - Docker Manifest V2 Schema2 Support.
MESOS-9540 - Support `DESTROY_DISK` on preprovisioned CSI volumes.
MESOS-9529 - `/proc` should be remounted even if a nested container set `share_pid_namespace` to true.
MESOS-9159 - Support Foreign URLs in docker registry puller on windows.
MESOS-8467 - Destroyed executors might be used after `Slave::publishResource()`. …
=> [1.12] Bump Mesos to nightly 1.7.x 0f4e34b

gen/dcos-config.yaml
Backport of #5131
- [DCOS-51758](https://jira.mesosphere.com/browse/DCOS-51758) Masters and many agents got unreachable after upgrading soak113s from 1.13.0-alpha to 1.13.0-beta
=> [1.13] Tune fluent bit's configuration

packages/dcos-integration-test/extra/test_metrics.py, packages/telegraf/buildinfo.json
Backports #5141
- [DCOS_OSS-5022](https://jira.mesosphere.com/browse/DCOS_OSS-5022) Prometheus task metrics don't work in bridge or virtual IP mode
=> [1.13] Fix prometheus task metrics in bridged and virtual IP mode

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
[MESOS-9729](https://issues.apache.org/jira/browse/MESOS-9729) - Unpublishing a volume that is failed to publish crashes the agent with CSI v1.
[MESOS-9704](https://issues.apache.org/jira/browse/MESOS-9704) - Support docker manifest v2s2 config GC.
https://github.com/apache/mesos/compare/0c503b01d3a9428ec9db35d09da5e237d737c570...424a1931062936c00113185a6492465c251d036b
=> [1.13] Bump Mesos to nightly 1.8.x 424a193

packages/mesos/buildinfo.json
MESOS-9707 - Calling link::lo() may cause runtime error.
MESOS-9704 - Support docker manifest v2s2 config GC.
MESOS-9675 - Docker Manifest V2 Schema2 Support.
MESOS-9529 - `/proc` should be remounted even if a nested container set `share_pid_namespace` to true.
MESOS-9159 - Support Foreign URLs in docker registry puller on windows.
https://github.com/apache/mesos/compare/8b7ab8403365db54b2d2315cbebe2bc332444fab...5f07b10b05f7d58a08735498215bec8bb3a12518
=> [1.11] Bump Mesos to nightly 1.5.x 5f07b10

gen/dcos-config.yaml
This PR contains updates to the fluent bit configuration file intended to tune it to perform better.
- [DCOS-51758](https://jira.mesosphere.com/browse/DCOS-51758) Masters and many agents got unreachable after upgrading soak113s from 1.13.0-alpha to 1.13.0-beta
=> Tune fluent bit's configuration

packages/dcos-integration-test/extra/test_metrics.py, packages/telegraf/buildinfo.json
This PR updates telegraf to collect metrics from the mesos agent's IP address, rather than its host's loopback address.
- [DCOS_OSS-5022](https://jira.mesosphere.com/browse/DCOS_OSS-5022) Prometheus task metrics don't work in bridge or virtual IP mode
=> Fix prometheus task metrics in bridged and virtual IP mode

packages/mesos/buildinfo.json
MESOS-9675 - Docker Manifest V2 Schema2 Support.
MESOS-9159 - Support Foreign URLs in docker registry puller on windows.
https://github.com/apache/mesos/compare/177bc5252829e6f9730122c41ad9cd1d37b3f070...1a762020ec9fdc46b55754afd955d81f1da8880f
=> [1.10] Bump Mesos to nightly 1.4.x 1a76202

CHANGES.md, packages/adminrouter/extra/src/includes/server/master.conf, packages/dcos-integration-test/extra/test_adminrouter_open.py
Serve pre-compressed UI assets to clients that provide an `Accept-Encoding` header containing `gzip`.
This also sets a cache header for 10 hours, to helps speed up UI interaction.
Note, this is an alternative solution to #5063 
- [DCOS-5978](https://jira.mesosphere.com/browse/DCOS-5978) Admin Router: enable gzip compression for relevant MIME types
___
**PLEASE FILL IN THE TEMPLATE …
=> Send pre-compressed UI assets if possible.

docs/admin-ports.md, gen/build_deploy/bash.py, gen/dcos-config.yaml, packages/fluent-bit/build
This PR builds fluent-bit with three extra flags to enable the metrics server, so that we can configure it to be monitored. It enables the fluent bit metrics server in the common configuration file.
- [DCOS-51855](https://jira.mesosphere.com/browse/DCOS-51855) Build fluent bit with metrics support
=> Enable fluent bit metrics

CHANGES.md, packages/docker-gc/buildinfo.json, packages/docker-gc/extra/dcos-docker-gc.service
* Enable removal of volumes using env var
* Switch to mesosphere/docker-gc fork that actually works
- [DCOS_OSS-1502](https://jira.mesosphere.com/browse/DCOS_OSS-1502) dcos-docker-gc does not clean leftover volumes
___
**What is …
=> [1.11] dcos-docker-gc does not clean leftover volumes

CHANGES.md, packages/docker-gc/buildinfo.json, packages/docker-gc/extra/dcos-docker-gc.service
* Enable removal of volumes using env var
* Switch to mesosphere/docker-gc fork that actually works
- [DCOS_OSS-1502](https://jira.mesosphere.com/browse/DCOS_OSS-1502) dcos-docker-gc does not clean leftover volumes
___
**What is …
=> [1.12] dcos-docker-gc does not clean leftover volumes

test-e2e/cluster_helpers.py
Adds `.log` extension to the log files produced by `wait_for_dcos_oss` test helper.
- [DCOS-43359](https://jira.mesosphere.com/browse/DCOS-43359) DC/OS Enterprise test-e2e tests: Use `.log` extensions on logs
=> test-e2e/cluster_helpers: save cluster log files with log extension

test-e2e/cluster_helpers.py
Backport of https://github.com/dcos/dcos/pull/5198
Adds `.log` extension to the log files produced by `wait_for_dcos_oss` test helper.
- [DCOS-43359](https://jira.mesosphere.com/browse/DCOS-43359) DC/OS Enterprise test-e2e tests: Use `.log` extensions on logs
=> [1.13] test-e2e/cluster_helpers: save cluster log files with log extension

test-e2e/cluster_helpers.py
Backport of https://github.com/dcos/dcos/pull/5198
Adds `.log` extension to the log files produced by `wait_for_dcos_oss` test helper.
- [DCOS-43359](https://jira.mesosphere.com/browse/DCOS-43359) DC/OS Enterprise test-e2e tests: Use `.log` extensions on logs
=> [1.11] test-e2e/cluster_helpers: save cluster log files with log extension

test-e2e/cluster_helpers.py
Backport of https://github.com/dcos/dcos/pull/5198
Adds `.log` extension to the log files produced by `wait_for_dcos_oss` test helper.
- [DCOS-43359](https://jira.mesosphere.com/browse/DCOS-43359) DC/OS Enterprise test-e2e tests: Use `.log` extensions on logs
=> [1.12] test-e2e/cluster_helpers: save cluster log files with log extension

CHANGES.md, packages/adminrouter/extra/src/includes/server/master.conf, packages/dcos-integration-test/extra/test_adminrouter_open.py
Back-port of #5140 - sets more appropriate cache headers based on discussion with @nLight 
Serve pre-compressed UI assets to clients that provide an `Accept-Encoding` header containing `gzip`.
This also sets a cache header for 2 days, to helps speed up UI interaction.
- [DCOS-5978](https://jira.mesosphere.com/browse/DCOS-5978) Admin Router: enable gzip compression for relevant MIME types …
=> [1.13] Send pre-compressed UI assets if possible.

packages/mesos/extra/patches/0006-Revert-Validated-the-match-between-Type-and-Infos-in.patch
During the Mesos 1.8 development cycle, an additional validation check was
added to the Mesos master that verifies that the protobuf union inside
a `ContainerInfo` is set correctly, i.e. `DOCKER`-type messages should
have their `docker` field set and `MESOS`-type message should have
their `mesos` field set.
However, during a MWT15 pre-test we found that 13 out of 17 agents
were running tasks that violate these constraints.
Therefore, we disable this validation inside DC/OS for now.
- [DCOS-55219](https://jira.mesosphere.com/browse/DCOS-52219) premwt15 agents wont re-register with cluster after 1.13 upgrade.
- …
=> [1.13.0] Added mesos patch that reverts ContainerInfo protobuf validation.

test-e2e/conftest.py, test-e2e/requirements.txt, test-e2e/test_e2e_module.py, test-e2e/test_master_node_replacement.py
This updates DC/OS E2E to bring in better log control and fixes.
Disables debug log output for `urllib3` and `docker` modules in `e2e` tests.
`Output.LOG_AND_CAPTURE` is now used for various `run` commands because the default, `Output.CAPTURE`, no longer logs anything at all - it used to log errors.
This adds `teamcity-messages` as a test requirement.
When this is merged and backported we will remove `-s` in the `PARAMETERS` arguments for the TeamCity jobs.
This will allow us to separate log output for different tests.
In the case of a cluster not starting, we now store journal logs and so we do not need to see extensive logs while waiting for DC/OS to start.
This cuts down the build log to approximately 1/3 of the size and it will make finding the real problems much easier.
These DC/OS …
=> test-e2e: remove unnecessary debug logging

CHANGES.md, packages/dcos-net/buildinfo.json
Bump dcos-net
- [DCOS-52780](https://jira.mesosphere.com/browse/DCOS-52780) ipset protocol ignores a missing `match` flag on some kernel versions
https://github.com/dcos/dcos-net/compare/3485521f64167be55bd8730ad8c5486db8f345fc...d699ab1bd5c0c1e5911b3851ebb416d15ddfb4a0
https://github.com/dcos/dcos-net/pull/147
https://circleci.com/gh/dcos/dcos-net/1124
https://codecov.io/github/dcos/dcos-net/commit/d699ab1bd5c0c1e5911b3851ebb416d15ddfb4a0
___ …
=> [1.13.0] Bump dcos-net

packages/mesos/extra/patches/0006-Revert-Validated-the-match-between-Type-and-Infos-in.patch
During the Mesos 1.8 development cycle, an additional validation check was
added to the Mesos master that verifies that the protobuf union inside
a `ContainerInfo` is set correctly, i.e. `DOCKER`-type messages should
have their `docker` field set and `MESOS`-type message should have
their `mesos` field set.
However, during a MWT15 pre-test we found that 13 out of 17 agents
were running tasks that violate these constraints.
Therefore, we disable this validation inside DC/OS for now.
- [DCOS-55219](https://jira.mesosphere.com/browse/DCOS-52219) premwt15 agents wont re-register with cluster after 1.13 upgrade.
- …
=> [1.13] Added mesos patch that reverts ContainerInfo protobuf validation.

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/424a1931062936c00113185a6492465c251d036b...d2a368363c6738d83c721e5c7eb5e1f2ebc9cb07
=> [1.13.0] Bump Mesos to nightly 1.8.x d2a3683

CHANGES.md, packages/dcos-net/buildinfo.json
Bump dcos-net
- [DCOS-52780](https://jira.mesosphere.com/browse/DCOS-52780) ipset protocol ignores a missing `match` flag on some kernel versions
https://github.com/dcos/dcos-net/compare/c32f9a4b910d6375f68351153c2282e1b9251018...9a51d7dece816c59eea4410d12e2f1689da911e7
https://github.com/dcos/dcos-net/pull/149
https://circleci.com/gh/dcos/dcos-net/1126
https://codecov.io/github/dcos/dcos-net/commit/9a51d7dece816c59eea4410d12e2f1689da911e7
___ …
=> [1.11] Bump dcos-net

packages/mesos/extra/patches/0006-Revert-Validated-the-match-between-Type-and-Infos-in.patch
During the Mesos 1.8 development cycle, an additional validation check was
added to the Mesos master that verifies that the protobuf union inside
a `ContainerInfo` is set correctly, i.e. `DOCKER`-type messages should
have their `docker` field set and `MESOS`-type message should have
their `mesos` field set.
However, during a MWT15 pre-test we found that 13 out of 17 agents
were running tasks that violate these constraints.
Therefore, we disable this validation inside DC/OS for now.
- [DCOS-55219](https://jira.mesosphere.com/browse/DCOS-52219) premwt15 agents wont re-register with cluster after 1.13 upgrade.
- …
=> Added mesos patch that reverts ContainerInfo protobuf validation.

packages/dcos-diagnostics/buildinfo.json, packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Remove dcos-history usage form dcos-diagnostics.
- [DCOS-5104](https://jira.mesosphere.com/browse/DCOS-5104) Remove dcos-history usage form dcos-diagnostics.
___ …
=> Remove dcos-history usage form dcos-diagnostics.

pkgpanda/__init__.py
pkgpanda previously relied on the fact that the `useradd` command
creates a matching group for a newly-created user.
But that's not always the case and only worked "by accident" because it
was set in the `USERGROUPS_ENAB` setting in `/etc/login.defs`. (See
https://linux.die.net/man/8/useradd for more information about this)
This commit makes the behaviour explicit and work regardless of
preconfigured settings by using the `--user-group`/`-U` argument to
`useradd` in case no other group was configured with `-g`, because those
are in conflict.
Backports #4482
---
- [DCOS_OSS-5106](https://jira.mesosphere.com/browse/DCOS_OSS-5106) pkgpanda: Explicitly create user groups for all users [1.11]
- …
=> DCOS_OSS-4097 - Explicitly create user groups in pkgpanda

packages/dcos-integration-test/extra/test_dcos_diagnostics.py
test_dcos_diagnostics_bundle_create_download_delete is a flaky test and should be muted.
- [DCOS-52191](https://jira.mesosphere.com/browse/DCOS-52191) test_dcos_diagnostics_bundle_create_download_delete failing with Timeout errors
=> DCOS-52191 - Mute flaky test test_dcos_diagnostics_bundle_create_download_delete

CHANGES.md
This is an editorial update for `CHANGES.md`.
Part of the 2019 changelog initiative.
=> CHANGES.md: editorial update for 1.14.0 development

test-e2e/conftest.py, test-e2e/requirements.txt, test-e2e/test_e2e_module.py
This is a backport of #5224.
Original description of that PR Is below:
```
This updates DC/OS E2E to bring in better log control and fixes.
Disables debug log output for `urllib3` and `docker` modules in `e2e` tests.
`Output.LOG_AND_CAPTURE` is now used for various `run` commands because the default, `Output.CAPTURE`, no longer logs anything at all - it used to log errors.
This adds `teamcity-messages` as a test requirement.
When this is merged and backported we will remove `-s` in the `PARAMETERS` arguments for the TeamCity jobs.
This will allow us to separate log output for different tests.
In the case of a cluster not starting, we now store journal logs and so we do not need to see extensive logs while waiting for DC/OS to start.
This cuts down the build log to approximately 1/3 of the …
```
=> [1.12][DCOS_OSS-5088] test-e2e: remove unnecessary debug logging

test-e2e/conftest.py, test-e2e/requirements.txt, test-e2e/test_e2e_module.py, test-e2e/test_master_node_replacement.py
This is a backport of #5224.
Original description of that PR Is below:
```
This updates DC/OS E2E to bring in better log control and fixes.
Disables debug log output for `urllib3` and `docker` modules in `e2e` tests.
`Output.LOG_AND_CAPTURE` is now used for various `run` commands because the default, `Output.CAPTURE`, no longer logs anything at all - it used to log errors.
This adds `teamcity-messages` as a test requirement.
When this is merged and backported we will remove `-s` in the `PARAMETERS` arguments for the TeamCity jobs.
This will allow us to separate log output for different tests.
In the case of a cluster not starting, we now store journal logs and so we do not need to see extensive logs while waiting for DC/OS to start.
This cuts down the build log to approximately 1/3 of the …
```
=> [1.13][DCOS_OSS-5088] test-e2e: remove unnecessary debug logging

test-e2e/conftest.py, test-e2e/requirements.txt, test-e2e/test_e2e_module.py
This is a backport of #5224.
Original description of that PR Is below:
```
This updates DC/OS E2E to bring in better log control and fixes.
Disables debug log output for `urllib3` and `docker` modules in `e2e` tests.
`Output.LOG_AND_CAPTURE` is now used for various `run` commands because the default, `Output.CAPTURE`, no longer logs anything at all - it used to log errors.
This adds `teamcity-messages` as a test requirement.
When this is merged and backported we will remove `-s` in the `PARAMETERS` arguments for the TeamCity jobs.
This will allow us to separate log output for different tests.
In the case of a cluster not starting, we now store journal logs and so we do not need to see extensive logs while waiting for DC/OS to start.
This cuts down the build log to approximately 1/3 of the …
```
=> [1.11][DCOS_OSS-5088] test-e2e: remove unnecessary debug logging

CHANGES.md
This adds a CHANGES.md entry which we missed to add for https://github.com/dcos/dcos/pull/5366.
=> CHANGES.md: add note for mesos_seccomp_enabled

CHANGES.md, packages/telegraf/buildinfo.json
This is a 1.12 backport of #5354.
- [DCOS_OSS-5039](https://jira.mesosphere.com/browse/DCOS_OSS-5039) Mesos telegraf plugin doesn't "percent-decode" per-framework metrics tags
N/A
=> (1.12) Telegraf: Use decoded framework name in metric tags

packages/telegraf/buildinfo.json
This bumps Telegraf to pull in https://github.com/dcos/telegraf/pull/54, which causes Telegraf's mesos input plugin to decode framework names before tagging metrics with them. Without this PR, framework names in metric tags may appear malformed.
- [DCOS_OSS-5039](https://jira.mesosphere.com/browse/DCOS_OSS-5039) Mesos telegraf plugin doesn't "percent-decode" per-framework metrics tags
N/A
=> Telegraf: Use decoded framework name in metric tags

CHANGES.md, packages/telegraf/buildinfo.json
This is a 1.13 backport of #5354.
- [DCOS_OSS-5039](https://jira.mesosphere.com/browse/DCOS_OSS-5039) Mesos telegraf plugin doesn't "percent-decode" per-framework metrics tags
N/A
=> (1.13) Telegraf: Use decoded framework name in metric tags

packages/adminrouter/extra/src/includes/server/master.conf
Support large uploads and long processing times for services accessed through Admin Router's `/service` endpoint. This supports package upload, required for package registries launched using Marathon.
This has been tested manually using the 10GB `beta-mesosphere-jupyter-service-1.3.0-0.35.4-beta.dcos` package.
There is a separate issue [DCOS-51222](https://jira.mesosphere.com/browse/DCOS-51222) for creation of an integration test. I consider this separation to be appropriate in this case, as there are non-trivial problems to be overcome for the test (time and bandwidth usage).
- [DCOS-52768](https://jira.mesosphere.com/browse/DCOS-52768) COPS-4651 repo 413 Entity too large / 504 timeout
Other tickets …
=> Support large uploads and processing times for services via AR

CHANGES.md, packages/adminrouter/extra/src/includes/server/master.conf
Backport #5376 to 1.13
Support large uploads and long processing times for services accessed through Admin Router's `/service` endpoint. This supports package upload, required for package registries launched using Marathon.
This has been tested manually using the 10GB `beta-mesosphere-jupyter-service-1.3.0-0.35.4-beta.dcos` package.
There is a separate issue DCOS-51222 for creation of an integration test. I consider this separation to be appropriate in this case, as there are non-trivial problems to be overcome for the test (time and bandwidth usage).
- [DCOS-52768](https://jira.mesosphere.com/browse/DCOS-52768) COPS-4651 repo 413 Entity too large / 504 timeout
- …
=> [1.13] Support large uploads and processing times for services via AR

packages/dcos-integration-test/extra/test_packaging.py
* DCOS-53467 - test_mom_installation fails on Permissive Mode Cluster 
Skip the test_mom_installation as the test hangs on the permissive mode cluster.
=> DCOS-53467 - test_mom_installation fails on Permissive Mode Cluster

CHANGES.md, packages/adminrouter/extra/src/includes/server/master.conf
Backport #5376 to 1.12
Support large uploads and long processing times for services accessed through Admin Router's `/service` endpoint. This supports package upload, required for package registries launched using Marathon.
This has been tested manually using the 10GB `beta-mesosphere-jupyter-service-1.3.0-0.35.4-beta.dcos` package.
There is a separate issue DCOS-51222 for creation of an integration test. I consider this separation to be appropriate in this case, as there are non-trivial problems to be overcome for the test (time and bandwidth usage).
- [DCOS-52768](https://jira.mesosphere.com/browse/DCOS-52768) COPS-4651 repo 413 Entity too large / 504 timeout
- …
=> [1.12] Support large uploads and processing times for services via AR

CHANGES.md, packages/dvdcli/buildinfo.json
This fixes the dvdcli package build.
- [DCOS-53581](https://jira.mesosphere.com/browse/DCOS-53581) Update dvdcli reference to fix dvdcli package build.
=> DCOS-53581 - Update dvdcli reference to fix dvdcli package build.

CHANGES.md, packages/dvdcli/buildinfo.json
This fixes the dvdcli package build.
- [DCOS-53581](https://jira.mesosphere.com/browse/DCOS-53581) Update dvdcli reference to fix dvdcli package build.
=> [BACKPORT 1.12] DCOS-53581 - Update dvdcli reference to fix dvdcli package build.

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/0f4e34b4dfe98178a7d94f5242041b5958eb7a24...658e793c2bec7a6862875e78b0ae9f8afdef8248
=> [1.12] Bump Mesos to nightly 1.7.x 658e793

packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/5f07b10b05f7d58a08735498215bec8bb3a12518...f38b69c2299152b28a2d263d5e6c5af79c78ca49
=> [1.11] Bump Mesos to nightly 1.5.x f38b69c

packages/libseccomp/build, packages/libseccomp/buildinfo.json, packages/mesos/build, packages/mesos/buildinfo.json
This patch adds `libseccomp` package which is used by the Mesos agent.
Previously, we linked `libseccomp` library statically which violated
the license agreement. This patch enables dynamic linking with
`libseccomp` library by default in order to meet license requirements.
- [DCOS-53450](https://jira.mesosphere.com/browse/DCOS-53450) De-couple libseccomp static bundle from dc/os because of LGPL2 license.
=> Added libseccomp package for dynamic linking with Mesos due to license.

dcos_installer/test_backend.py, ssh/test_unit.py, ssh/validate.py
Backport of #5522 
The `ssh_key_path` is only used by the deprecated/undocumented CLI
installer. No one should be using this, anymore. Since there's no easy
way to make the validation warning go away for `ssh_key_path` I simply
removed the validation of it completely for two reasons:
1. No one should be using it, anymore.
2. People that are using it most probably have a working configuration
in place.
As Thorsten stated in eaff454200578f1bcea243f556af926da75c57fb we
should really get rid of this installation method and all of its
accompanying code.
- [DCOS_OSS-5152](https://jira.mesosphere.com/browse/DCOS_OSS-5152)  Modify …
=> [1.13] DCOS_OSS-5152 - remove ssh_key_path validation

packages/dcos-integration-test/extra/test_mesos.py
* DCOS-53469 test_min_allocatable_resources fails on a Permissive mode
=> DCOS-53469 test_min_allocatable_resources fails on a Permissive mode

dcos_installer/test_backend.py, ssh/test_unit.py, ssh/validate.py
The `ssh_key_path` is only used by the deprecated/undocumented CLI
installer. No one should be using this, anymore. Since there's no easy
way to make the validation warning go away for `ssh_key_path` I simply
removed the validation of it completely for two reasons:
1. No one should be using it, anymore.
2. People that are using it most probably have a working configuration
in place.
As Thorsten stated in eaff454200578f1bcea243f556af926da75c57fb we
should really get rid of this installation method and all of its
accompanying code.
- [DCOS_OSS-5152](https://jira.mesosphere.com/browse/DCOS_OSS-5152) Modify dcos-installer not to warn …
=> DCOS_OSS-5152 - remove ssh_key_path validation

dcos_installer/test_backend.py, ssh/test_unit.py, ssh/validate.py
Backport of #5522 
The `ssh_key_path` is only used by the deprecated/undocumented CLI
installer. No one should be using this, anymore. Since there's no easy
way to make the validation warning go away for `ssh_key_path` I simply
removed the validation of it completely for two reasons:
1. No one should be using it, anymore.
2. People that are using it most probably have a working configuration
in place.
As Thorsten stated in eaff454200578f1bcea243f556af926da75c57fb we
should really get rid of this installation method and all of its
accompanying code.
- [DCOS_OSS-5152](https://jira.mesosphere.com/browse/DCOS_OSS-5152)  Modify …
=> [1.11] DCOS_OSS-5152 - remove ssh_key_path validation

dcos_installer/test_backend.py, ssh/test_unit.py, ssh/validate.py
Backport of #5522 
The `ssh_key_path` is only used by the deprecated/undocumented CLI
installer. No one should be using this, anymore. Since there's no easy
way to make the validation warning go away for `ssh_key_path` I simply
removed the validation of it completely for two reasons:
1. No one should be using it, anymore.
2. People that are using it most probably have a working configuration
in place.
As Thorsten stated in eaff454200578f1bcea243f556af926da75c57fb we
should really get rid of this installation method and all of its
accompanying code.
- [DCOS_OSS-5152](https://jira.mesosphere.com/browse/DCOS_OSS-5152)  Modify …
=> [1.12] DCOS_OSS-5152 - remove ssh_key_path validation

gen/calc.py
Attempts to reduce the relatively common occurrence of timeouts in checks that have no real way to time out by increasing the timeout to 5 seconds in case load is preventing a cluster from being able to run the check in the normal 1 second.
- [DCOS-53742](https://jira.mesosphere.com/browse/DCOS-53742)
- [ X] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
___
**What is the review process …
=> Increase default checks timeout to 5 seconds for "instant" checks

packages/dcos-integration-test/extra/test_dcos_diagnostics.py, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/f38b69c2299152b28a2d263d5e6c5af79c78ca49...6a8b61b59498dcea64d9380a233d517ce65dc2ef
=> [1.11] Bump Mesos to nightly 1.5.x 6a8b61b

dcos_installer/test_backend.py, gen/calc.py
* Update the 1.10 version to 1.10.11-dev
* DCOS-53938 - Set UI versions consistently across all in-development branches
=> Update 1.10 version to 1.10.11-dev.

dcos_installer/test_backend.py, gen/calc.py
* Set the 1.11 branch UI version to 1.11.11-dev
* DCOS-53938 - Set UI versions consistently across all in-development branches
=> Set the 1.11 branch UI version to 1.11.11-dev.

packages/dcos-integration-test/extra/test_dcos_diagnostics.py, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/658e793c2bec7a6862875e78b0ae9f8afdef8248...4a2949cb075ab02086fd9e3065bcab83855bf9cc
=> [1.12] Bump Mesos to nightly 1.7.x 4a2949c

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/61e5fcd1a6cb9252454dda62b0d6c0be17c144d2...eecb82c77117998af0c67a53c64e9b1e975acfa4
=> [master] Bump Mesos to nightly master eecb82c

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/4a2949cb075ab02086fd9e3065bcab83855bf9cc...40ea2b571b62dc90bacb80b4977b30da6c73a48f
=> [1.12] Bump Mesos to nightly 1.7.x 40ea2b5

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/a07fe233df91f9d945339bf9cffeefa3d0e5f7ad...f5770dcf322bd8a88e6c88041364a4089d92be90
=> [1.13] Bump Mesos to nightly 1.8.x f5770dc

CHANGES.md, packages/marathon/buildinfo.json
Bump Marathon to 1.6.585-3e0898228
- [MARATHON-8596](https://jira.mesosphere.com/browse/MARATHON-8596) Introduced global throttling for Marathon health checks
- [MARATHON-8590](https://jira.mesosphere.com/browse/MARATHON-8590) Do not fail on offers with RAW and BLOCK disk types
- [MARATHON-8575](https://jira.mesosphere.com/browse/MARATHON-8575) Map `tcp,udp` to `udp,tcp` during migration
- [MARATHON-8581](https://jira.mesosphere.com/browse/MARATHON-8581) Allow all users to execute /marathon/bin/marathon
- [MARATHON-8562](https://jira.mesosphere.com/browse/MARATHON-8562) Response asynchronously for all endpoints
- [MARATHON-8587](https://jira.mesosphere.com/browse/MARATHON-8587) Handle wrapped requests
- …
=> Bump Marathon to 1.6.585-3e0898228

packages/marathon/buildinfo.json
- [DCOS_OSS-5212](https://jira.mesosphere.com/browse/DCOS_OSS-5212) Fix restarting resident apps and pods.
- [DCOS_OSS-5211](https://jira.mesosphere.com/browse/DCOS_OSS-5211) Only match disk with profile if that profile is needed.
- [MARATHON-8623](https://jira.mesosphere.com/browse/MARATHON-8623) Better handle invalid state command exceptions in InstanceTrackerActor.
- [MARATHON-8624](https://jira.mesosphere.com/browse/MARATHON-8624) Add TASK_UNKNOWN to the valid mesos task status enums.
- [MARATHON-8616](https://jira.mesosphere.com/browse/MARATHON-8616) Prevent a rare but benign NPE when a deployment is canceled.
- [DCOS-51375](https://jira.mesosphere.com/browse/DCOS-51375) Prevent instance leak.
- Introduce new exit error code when the framework was removed from Mesos.
n/a
If you are …
=> Bump Marathon to 1.8.194-1590825ea.

gen/dcos-config.yaml, packages/dcos-integration-test/extra/test_metrics.py
This splits up the instance of the Prometheus input plugin that was collecting both adminrouter and task metrics. It creates one input for collecting adminrouter metrics, and another for collecting task metrics. This prevents task metrics from being inadvertently dropped if they meet the filter criteria for adminrouter metrics.
- [DCOS_OSS-5032](https://jira.mesosphere.com/browse/DCOS_OSS-5032) Don't apply Telegraf config for adminrouter metrics to Mesos task metrics
N/A
=> Collect adminrouter and task metrics with separate plugins

packages/dcos-integration-test/extra/test_dcos_diagnostics.py
* DCOS-54568 - Disable test_dcos_diagnostics for ifconfig comand not found in $PATH
=> DCOS-54568 - Disable test_dcos_diagnostics for ifconfig comand not found in PATH

CHANGES.md, gen/dcos-config.yaml, packages/dcos-integration-test/extra/test_metrics.py
This is a 1.13 backport of #5462. 
- [DCOS_OSS-5032](https://jira.mesosphere.com/browse/DCOS_OSS-5032) Don't apply Telegraf config for adminrouter metrics to Mesos task metrics
N/A
=> (1.13) Collect adminrouter and task metrics with separate plugins

gen/dcos-config.yaml
This PR removes config that directs Telegraf to monitor resource consumption for all processes running on all cluster nodes. This is wasteful on agents with many Mesos tasks, because task metrics are already collected by other inputs. Instead we provide a whitelist of component systemd units to monitor. This causes Telegraf to monitor the main PID for each component.
I tested this manually by installing dcos-monitoring and querying Prometheus to confirm that procstat metrics are present for all components.
This will be backported to 1.13, so no changelog entry is necessary.
- [DCOS-53589](https://jira.mesosphere.com/browse/DCOS-53589) Whitelist the processes to monitor when using the procstat input plugin
N/A
If you are changing components or packages in DC/OS (e.g. you are bumping the …
=> Collect procstat metrics only for components

packages/mesos-modules/buildinfo.json
This bumps mesos-modules to include https://github.com/dcos/dcos-mesos-modules/pull/109.
- [DCOS-53834](https://jira.mesosphere.com/browse/DCOS-53834) Integrate Mesos task log module fix with DC/OS
N/A
=> Include task metadata with task logs sent to Fluent Bit

CHANGES.md, packages/metronome/buildinfo.json
Bump Metronome to 0.6.23
- [DCOS_OSS-5020](https://jira.mesosphere.com/browse/DCOS_OSS-5020) Missing request metrics in Metronome
- [DCOS_OSS-5019](https://jira.mesosphere.com/browse/DCOS_OSS-5019) Improve secrets validation to only point out unprovided secrets
=> Bump Metronome to 0.6.23

CHANGES.md, packages/exhibitor/build, packages/exhibitor/extra/dcos_zk_backup.py, test-e2e/requirements.txt, test-e2e/test_groups.yaml, test-e2e/test_zookeeper_backup.py, tox.ini
Backport of #5575 
Only `CHANGES.md` differs.
The backup strategy was shifted to a backup/restore script shipped with DC/OS that will do a node local backup/restore on the particular master node that it is executed on.
The backup/restore script is now ported to Python3 and comprises a single file + CLI interface with commands backup and restore.
This PR adds two E2E tests for our ZooKeeper backup/restore procedures.
The actual backup/restore test is split into two because we want to test are two different scenarios:
* Restore from a ZooKeeper transaction log
* Restore from a ZooKeeper snapshot
Normally one would like to test `1.` with a snapshot+transaction log but success is difficult to assert in this case. Splitting it into to different test cases gives us confidence that a transaction …
=> [Backport 1.13] ZooKeeper backup and restore scripts

CHANGES.md, packages/exhibitor/build, packages/exhibitor/extra/dcos_zk_backup.py, test-e2e/requirements.txt, test-e2e/test_groups.yaml, test-e2e/test_zookeeper_backup.py
Backport of #5575 
Differences:
- CHANGES.md entry
- Explicit Docker dependency (was missing from the 1.12 branch even though it is used.)
The backup strategy was shifted to a backup/restore script shipped with DC/OS that will do a node local backup/restore on the particular master node that it is executed on.
The backup/restore script is now ported to Python3 and comprises a single file + CLI interface with commands backup and restore.
This PR adds two E2E tests for our ZooKeeper backup/restore procedures.
The actual backup/restore test is split into two because we want to test are two different scenarios:
* Restore from a ZooKeeper transaction log
* Restore from a ZooKeeper snapshot
Normally one would like to test `1.` with a snapshot+transaction log but success is difficult to assert …
=> [Backport 1.12] ZooKeeper backup and restore scripts

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/40ea2b571b62dc90bacb80b4977b30da6c73a48f...33a1ba97041f178f8be53cdeb7cbeb7c78b89798
=> [1.12] Bump Mesos to nightly 1.7.x 33a1ba9

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/f5770dcf322bd8a88e6c88041364a4089d92be90...d19ca42d1f27a3d2a4ad974f84a04d6f4fb1b129
=> [1.13] Bump Mesos to nightly 1.8.x d19ca42

packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/d19ca42d1f27a3d2a4ad974f84a04d6f4fb1b129...fca89344aff96a8e2ec1b5b70f4a3cb0e899c352
https://github.com/dcos/dcos-mesos-modules/compare/2633cb7135c978f640d08819f2408c541d6dedb2...1869381f77ff89e60fba20540e7775cd8d6fdbc2
=> [1.13] Bump Mesos to nightly 1.8.x fca8934

packages/dcos-integration-test/extra/test_service_discovery.py
* DCOS-54432 - Skip test_service_discovery_docker_bridged_network until dependencies are resolved.
=> Skip test_service_discovery_docker_bridged_network until dependencies are resolved.

packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Backport of  https://github.com/dcos/dcos/pull/5634/
Fixes: DCOS-54487 - test_dcos_diagnostics_bundle_create_download_delete fails on Permissive mode cluster
=> DCOS-52080 - Fix AWS Onprem w/ Static Backend and Security Permissive CI

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/eecb82c77117998af0c67a53c64e9b1e975acfa4...1961e41a61def2b7baca7563c0b7e1855880b55c
=> [master] Bump Mesos to nightly master 1961e41

CHANGES.md, packages/telegraf/buildinfo.json
Telegraph bump to include changes from DCOS-55100.
- [DCOS-25655](https://jira.mesosphere.com/browse/DCOS-55100) `Add support for using the port name in metrics endpoint discovery done by our Telegraf fork`
=> DCOS-55100 Bump telegraf

CHANGES.md, packages/cockroach/build, packages/cockroach/buildinfo.json, packages/cockroach/extra/cockroachdb-change-config.py, packages/cockroach/extra/register.py
This PR upgrades CockroachDB to version [2.1.7](
https://www.cockroachlabs.com/docs/releases/v2.1.7.html) in DC/OS.
The PR removes `set_cluster_version` which was previously used to `finalize` an upgrade of CockroachDB. With version 2.1.x CockroachDB [auto-finalizes](https://www.cockroachlabs.com/docs/v2.1/upgrade-cockroach-version.html#step-3-decide-how-the-upgrade-will-be-finalized) upgraded nodes by default.
The PR fixes a race-condition in our CockroachDB init procedure where we first start one CockroachDB instance that initializes a new cluster before it get killed to then restart and `join` the cluster it previously created. The problem there appeared to be that the instance got terminated to quickly which led to the cluster not being properly initialized in rare cases.
- …
=> Upgrade CockroachDB to version 2.1.7

test-e2e/requirements.txt, test-e2e/test_e2e_module.py
This change bumps the version of DC/OS E2E used in tests.
The main goal of this is to keep more logs in the event of a `DCOSTimeoutError` - a long running test which times out after an hour of waiting for DC/OS previously kept only ~20 minutes of logs.
In particular, [DC/OS E2E PR #1857](https://github.com/dcos/dcos-e2e/pull/1857) provides a change we want to bring in.
This PR is submitted without evidence that more logs are kept by DC/OS.
One test we could do is add a loop to bootstrap which would mean that the cluster start up time is > 1h, and then we could check the amount of logs kept with or without this change.
We prefer not to do this and instead reason that this change will work, and then come back if we get evidence that it has not worked.
Reviewer feedback on that strategy is …
=> [1.14 / master] Bump DC/OS E2E to 2019.06.19.0

packages/marathon/buildinfo.json
- [MARATHON-8422](https://jira.mesosphere.com/browse/MARATHON-8422) Marathon won't get stuck killing an unreachable instance.
- [MARATHON-8631](https://jira.mesosphere.com/browse/MARATHON-8631) Persistent volumes with profile now default to DiskType.Mount
=> Update Marathon to 1.8.207-9f3550487

packages/cockroach/build, packages/cockroach/extra/iam-database-backup.py, packages/cockroach/extra/iam-database-restore.py, tox.ini
This PR improves the IAM database restore script to handle the case gracefully where CockroachDB state has been wiped out completely. I also reduces the amount of errors shown in the logs when a failure occurs. In addition, it also enables `tox` linting in the `packages/cockroach/extra` folder.
- [DCOS-46121](https://jira.mesosphere.com/browse/DCOS-46121) packages/cockroachdb: improve exception handling in `iam-database-restore` script.
- [COPS-4976](https://jira.mesosphere.com/browse/COPS-4976) Cockroachdb failing with message: "failed node liveness heartbeat: context deadline exceeded" - recovery failed.
=> Improve IAM database restore error handling

CHANGES.md, packages/cockroach/build, packages/cockroach/extra/iam-database-backup.py, packages/cockroach/extra/iam-database-restore.py, tox.ini
Backport of @timaa2k 's PR at #5747. There are no intended changes.
The description from that PR:
```
This PR improves the IAM database restore script to handle the case gracefully where CockroachDB state has been wiped out completely. I also reduces the amount of errors shown in the logs when a failure occurs. In addition, it also enables `tox` linting in the `packages/cockroach/extra` folder.
- [DCOS-46121](https://jira.mesosphere.com/browse/DCOS-46121) packages/cockroachdb: improve exception handling in `iam-database-restore` script.
- [COPS-4976](https://jira.mesosphere.com/browse/COPS-4976) Cockroachdb failing with message: "failed node liveness heartbeat: context deadline exceeded" - recovery failed.
```
=> [1.13] Backport tweidner/improve-iam-database-restore

packages/python/buildinfo.json
This changes system CPython from release 3.6.6 to the latest maintenance release 3.6.8.
https://jira.mesosphere.com/browse/DCOS_OSS-5318
=> platform CPython: bump from 3.6.6 to 3.6.8

CHANGES.md, packages/curl/buildinfo.json
This bumps platform curl from 7.59.0 to 7.65.1.
Various components use curl/libcurl for some of the heavy lifting HTTP machinery within DC/OS, such as the Mesos fetcher.
https://jira.mesosphere.com/browse/DCOS_OSS-5319
=> Bump platform curl from 7.59.0 to 7.65.1.

docs/terraform-integration-tests.md, test_util/terraform_init.sh, test_util/terraform_logs.sh, test_util/terraform_test.sh
This adds a script `terraform_init.sh` that sets up Terraform modules and providers in order to run the integration tests or reproduce a CI test run.
This is a part of the user documentation for running dcos-terraform jobs.
- [DCOS-54806](https://jira.mesosphere.com/browse/DCOS-54806) - Write documentation for Terraform integration tests.
=> DCOS-54806 - Add script and documentation for setting up Terraform for running integration tests.

gen/build_deploy/bash.py
According to the documentation `xfs_info` is supposed to be supplied with a mount point: 
`xfs_info [ -t mtab ] mount-point`
> The mount-point argument is the pathname of the **directory** where the filesystem is mounted.
At the moment, `dcos_install.sh` performs the `xfs_info` operation on a **device**:
`ftype_value="$(xfs_info $filesystem_device | grep -oE ftype=[0-9])"`
On some systems, such as Oracle Linux 7, this leads to a failure while trying to install DCOS on an agent node:
```
$ cd /tmp/dcos
$ sudo bash dcos_install.sh slave_public
Starting DC/OS Install Process
Running preflight checks
Checking if DC/OS is already installed: PASS (Not installed)
...
Checking if /var/lib/mesos is mounted with ftype=1: xfs_info: /dev/xvdz1 is not a mounted XFS filesystem
FAIL ()
...
Preflight …
```
=> dcos_install.sh - xfs_info - use mount point instead of a device

packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/1961e41a61def2b7baca7563c0b7e1855880b55c...fe7be9701e92d863734621ae1a3d339bb8598044
=> [master] Bump Mesos to nightly master fe7be97

mergebot-config.json
Make DC/OS Terraform integration tests required checks.
- [DCOS-54811](https://jira.mesosphere.com/browse/DCOS-54811) - Make the DC/OS Terraform integration tests required checks.
- [DCOS-54316](https://jira.mesosphere.com/browse/DCOS-54316) - Enable dcos-terraform tests for integration test group 3.
=> DCOS-54811 - Make the DC/OS Terraform integration tests required checks.

mergebot-config.json
Make dcos-terraform integration test group 3 required, make dcos-launch test group 3 not required.
- [DCOS-54316](https://jira.mesosphere.com/browse/DCOS-54316) Enable dcos-terraform tests for integration test group 3
- [DCOS-55957](https://jira.mesosphere.com/browse/DCOS-55957) Disable dcos-launch tests
=> DCOS-54316 - Enable dcos-terraform tests for integration test group 3

test_util/terraform_init.sh
Sometimes terraform init fails due to network issues. This makes us retry on Terraform init errors.
- [DCOS-56054](https://jira.mesosphere.com/browse/DCOS-56054) Retry downloading Terraform modules if it fails.
=> DCOS-56054 - Retry on Terraform init errors.

CHANGES.md, packages/metronome/buildinfo.json
- [DCOS_OSS-5337](https://jira.mesosphere.com/browse/DCOS_OSS-5337) Bump Metronome 0.6.33.
- [DCOS_OSS-5166](https://jira.mesosphere.com/browse/DCOS_OSS-5166)  Fixed metronome not using revive operation
=> Metronome 0.6.33 Bump on 1.13

CHANGES.md, packages/metronome/buildinfo.json
- [DCOS_OSS-5337](https://jira.mesosphere.com/browse/DCOS_OSS-5337) Bump Metronome 0.6.33.
- [DCOS_OSS-5166](https://jira.mesosphere.com/browse/DCOS_OSS-5166)  Fixed metronome not using revive operation
=> Metronome 0.6.33 Bump on 1.11

CHANGES.md, packages/metronome/buildinfo.json
- [DCOS_OSS-5337](https://jira.mesosphere.com/browse/DCOS_OSS-5337) Bump Metronome 0.6.33.
- [DCOS_OSS-5166](https://jira.mesosphere.com/browse/DCOS_OSS-5166)  Fixed metronome not using revive operation
=> Bump Metronome 0.6.33 on Master

CHANGES.md, packages/metronome/buildinfo.json
- [DCOS_OSS-5337](https://jira.mesosphere.com/browse/DCOS_OSS-5337) Bump Metronome 0.6.33.
- [DCOS_OSS-5166](https://jira.mesosphere.com/browse/DCOS_OSS-5166)  Fixed metronome not using revive operation
=> Metronome 0.6.33 Bump on 1.12

packages/telegraf/buildinfo.json
This PR updates the Telegraf Prometheus plugin to use the IP address specified in a task's container status field, rather than relying on the private node IP. This fixes an issue where prometheus metrics could not be collected from tasks using container networking mode.
- [DCOS-56018](https://jira.mesosphere.com/browse/DCOS-56018) Telegraf Prometheus plugin sources metrics from node IP, not task IP
=> Update Telegraf prometheus plugin for container mode

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/fca89344aff96a8e2ec1b5b70f4a3cb0e899c352...07d053f68b75505a4386913f05d521fa5e36373d
=> [1.13] Bump Mesos to nightly 1.8.x 07d053f

CHANGES.md, packages/exhibitor/extra/dcos_zk_backup.py
Backport of @timaa2k 's #5810, with `CHANGES.md` change added and a comment added as suggested by @jgehrcke on the original PR at https://github.com/dcos/dcos/pull/5810/files#r300683262.
Original PR's description:
```
This PR changes the ZooKeeper backup/restore script so that it checks that the ZooKeeper process is not running. Before it only asserted that `dcos-exhibitor` was not running which we suspect to not coincide with the former 100% of the cases.
The change enables getting a better understanding of the failure mode next time the flaky test in the JIRA fails. This is not a fix but a mere improvement of the debug output.
- [DCOS-55827](https://jira.mesosphere.com/browse/DCOS-55827) TestZooKeeperBackup.test_transaction_log_backup_and_restore if flaky.
**edit by @adamtheturtle : We …
```
=> [1.12] Backport tweidner/assert-zk-not-running-during-backup

CHANGES.md, packages/exhibitor/extra/dcos_zk_backup.py
Backport of @timaa2k 's #5810, with `CHANGES.md` change added and a comment added as suggested by @jgehrcke on the original PR at https://github.com/dcos/dcos/pull/5810/files#r300683262.
Original PR's description:
```
This PR changes the ZooKeeper backup/restore script so that it checks that the ZooKeeper process is not running. Before it only asserted that `dcos-exhibitor` was not running which we suspect to not coincide with the former 100% of the cases.
The change enables getting a better understanding of the failure mode next time the flaky test in the JIRA fails. This is not a fix but a mere improvement of the debug output.
- [DCOS-55827](https://jira.mesosphere.com/browse/DCOS-55827) TestZooKeeperBackup.test_transaction_log_backup_and_restore if flaky.
**edit by @adamtheturtle : We …
```
=> [1.13] Backport tweidner/assert-zk-not-running-during-backup

test_util/terraform_logs.sh
Do not collect logs from successful jobs.
We clean up these lines by just checking for the `all_tests_passed` marker file. I am not sure what the purpose of the removed lines was, but they made the logic more complicated and brittle.
- [DCOS-56234](https://jira.mesosphere.com/browse/DCOS-56234) Do not collect logs from successful jobs.
=> DCOS-56234 - Do not collect logs from successful jobs.

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/1a6760c60dc823b088ffbcf48909cf3e371570f3...bd618c175a70e60c1aa5dae42e01652ac29f7861
=> [master] Bump Mesos to nightly master bd618c1

packages/dcos-integration-test/extra/test_networking.py
happened here:
https://teamcity.mesosphere.io/viewLog.html?buildId=2066343&buildTypeId=DcOs_Enterprise_Test_Inte_AwsOnpremWStaticBackendAndSecurityStrictGroup2Terraf_2
=> mark xfail test_networking.test_if_overlay_ok

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/bd618c175a70e60c1aa5dae42e01652ac29f7861...9932550e9632e7fbb9a45b217793c7f508f57001
=> [master] Bump Mesos to nightly master 9932550

CHANGES.md, packages/cockroach/buildinfo.json
This PR upgrade CockroachDB from version [2.1.7](https://www.cockroachlabs.com/docs/releases/v2.1.7.html) to version [2.1.8](https://www.cockroachlabs.com/docs/releases/v2.1.8.html).
The 2.1.8 release includes a [bugfix](https://github.com/cockroachdb/cockroach/issues/38146) (named Security Improvement) which we found when upgrading to 2.1.7.
- [DCOS_OSS-5360](https://jira.mesosphere.com/browse/DCOS_OSS-5360) Upgrade CockroachDB to version 2.1.8.
- [here](https://github.com/dcos/bouncer/pull/11)
=> Upgrade CockroachDB to v2.1.8

docs/terraform-integration-tests.md, test_util/terraform_init.sh
In order to allow debugging clusters while terraform is still running, we print the SSH key prior to running terraform in CI.
- [DCOS-56740](https://jira.mesosphere.com/browse/DCOS-56740) Print SSH key prior to running terraform in integration tests
=> DCOS-56740 - Print SSH key prior to running terraform in integration tests

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/test_networking.py
This changes `clean_marathon_state` to `module` scoped - so that it can exist in EE and OSS, and coexist with module scoped fixtures which create Marathon resources. See the JIRA issue for alternatives discussed.
- [DCOS-45746](https://jira.mesosphere.com/browse/DCOS-45746) tests: autouse=True Marathon fixture breaks module-scoped Marathon app fixtures.
=> Module scoped, autouse `clean_marathon_state`

CHANGES.md, packages/marathon/buildinfo.json
Bump Marathon to 1.9 latest, with the primary feature being multi-role support. See the related tickets for new features introduced in this bump.
- [DCOS-56722](https://jira.mesosphere.com/browse/DCOS-56722) Include Marathon 1.9 snapshot it DC/OS latest
* [MARATHON-8642](https://jira.mesosphere.com/browse/MARATHON-8642), [MARATHON-8666](https://jira.mesosphere.com/browse/MARATHON-8666) - Task role metadata
* [MARATHON-8650](https://jira.mesosphere.com/browse/MARATHON-8650) - Default group role behavior
* [MARATHON-8651](https://jira.mesosphere.com/browse/MARATHON-8651) - Patch group enforce role
* [MARATHON-8662](https://jira.mesosphere.com/browse/MARATHON-8662) - Support reservations for multirole
* [MARATHON-8653](https://jira.mesosphere.com/browse/MARATHON-8653) - Add deprecated …
=> Bump to latest Marathon snapshot

README.md
Remove obsolete `dcos-oauth` instruction from README.
=> [Backport 1.13] Remove dcos-oauth instructions from README

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/test_networking.py
This is a backport of #5896
Description form that below:
This changes `clean_marathon_state` to `module` scoped - so that it can exist in EE and OSS, and coexist with module scoped fixtures which create Marathon resources. See the JIRA issue for alternatives discussed.
- [DCOS-45746](https://jira.mesosphere.com/browse/DCOS-45746) tests: autouse=True Marathon fixture breaks module-scoped Marathon app fixtures.
=> [1.13] Backport change-scope-fixtures

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/test_networking.py
This is a backport of #5896
Description form that below:
This changes `clean_marathon_state` to `module` scoped - so that it can exist in EE and OSS, and coexist with module scoped fixtures which create Marathon resources. See the JIRA issue for alternatives discussed.
- [DCOS-45746](https://jira.mesosphere.com/browse/DCOS-45746) tests: autouse=True Marathon fixture breaks module-scoped Marathon app fixtures.
=> [1.12] Backport change-scope-fixtures

README.md
The README talks about dcos-oauth but it no longer exists.
=> dcos-oauth does no longer exist, remove it from the README

CHANGES.md, packages/marathon/buildinfo.json
This includes the fix for multiRole enforcement and leading slashes
- [DCOS-56722](https://jira.mesosphere.com/browse/DCOS-56722) Include Marathon 1.9 snapshot it DC/OS latest
* [MARATHON-8669](https://jira.mesosphere.com/browse/MARATHON-8669) - enforceRole not respected for POST to /v2/apps if relative path is used
* [MARATHON-8637](https://jira.mesosphere.com/browse/MARATHON-8637) - persist and expose instance role in /v2/tasks
* [MARATHON-8673](https://jira.mesosphere.com/browse/MARATHON-8673) - Fix an issue in which the migration for groupRole would fail to run for sub-groups
=> Bump marathon to 1.9.34

CHANGES.md, packages/dcos-net/buildinfo.json
Prune VIPs with no backends in order to avoid unbounded growth of state and messages exchanged among `dcos-net` processes.
- [DCOS_OSS-5356](https://jira.mesosphere.com/browse/DCOS_OSS-5356) dcos-net should prune VIP entries with no backends
=> [1.12] Prune VIPs with no backends in dcos-net

CHANGES.md, packages/dcos-net/buildinfo.json
Prune VIPs with no backends in order to avoid unbounded growth of state and messages exchanged among `dcos-net` processes.
- [DCOS_OSS-5356](https://jira.mesosphere.com/browse/DCOS_OSS-5356) dcos-net should prune VIP entries with no backends
=> Prune VIPs with no backends in dcos-net

CHANGES.md, packages/dcos-net/buildinfo.json
Prune VIPs with no backends in order to avoid unbounded growth of state and messages exchanged among `dcos-net` processes.
- [DCOS_OSS-5356](https://jira.mesosphere.com/browse/DCOS_OSS-5356) dcos-net should prune VIP entries with no backends
=> [1.13] Prune VIPs with no backends in dcos-net

CHANGES.md, gen/build_deploy/bash.py
Fix problems with docker version > 1.19 which added new entries to `docker version` output.
Latest docker hase more entries in `docker version` output. See folowing examples
```yaml
Client: Docker Engine - Community
Version:           19.03.1
API version:       1.35 (downgraded from 1.40)
Go version:        go1.12.5
Git commit:        74b1e89
Built:             Thu Jul 25 21:21:07 2019
OS/Arch:           linux/amd64
Experimental:      false
Server:
Engine:
Version:          17.12.1-ce
API version:      1.35 (minimum version 1.12)
Go version:       go1.9.4
Git commit:       7390fc6
Built:            Tue Feb 27 22:20:43 2018
OS/Arch:          linux/amd64
Experimental:     false
```
```yaml
Client: Docker Engine - Community
Version:           19.03.1
API version:       1.40
Go version: …
```
=> Replace artisanal docer version detect script

CHANGES.md, gen/build_deploy/bash.py
Backports: https://github.com/dcos/dcos/pull/5993
---
Fix problems with docker version > 1.19 which added new entries to `docker version` output.
Latest docker hase more entries in `docker version` output. See folowing examples
```yaml
Client: Docker Engine - Community
Version:           19.03.1
API version:       1.35 (downgraded from 1.40)
Go version:        go1.12.5
Git commit:        74b1e89
Built:             Thu Jul 25 21:21:07 2019
OS/Arch:           linux/amd64
Experimental:      false
Server:
Engine:
Version:          17.12.1-ce
API version:      1.35 (minimum version 1.12)
Go version:       go1.9.4
Git commit:       7390fc6
Built:            Tue Feb 27 22:20:43 2018
OS/Arch:          linux/amd64
Experimental:     false
```
```yaml
Client: Docker Engine - Community
Version: …
```
=> [1.13] Replace artisanal docer version detect script

packages/dcos-signal/extra/dcos-signal.service
DC/OS Signal must be able to read the license ID from the socket file `/run/dcos/dcos-licensing.sock` that's owned by the group `dcos_adminrouter`.
- [DCOS-57291](https://jira.mesosphere.com/browse/DCOS-57291) DC/OS Signal doesn't report license ID
- [] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
=> [DCOS-57291] make DC/OS Signal report the license ID

dcos_installer/test_backend.py, gen/calc.py
* Revert the change done for DCOS-56899 - Set DC/OS Version to 1.14.0-Alpha. (PR: https://github.com/dcos/dcos/pull/5933) 
* We have a release branch for 1.14.0-alpha https://github.com/dcos/dcos/tree/1.14.0-alpha, and master version can be set to `1.14.0-dev`.
=> Set the DC/OS Version in master to 1.14.0-dev

CHANGES.md, packages/marathon/buildinfo.json
This is PR #5967 repeated on 1.14 Alpha
- [DCOS-56722](https://jira.mesosphere.com/browse/DCOS-56722)  Include Marathon 1.9 snapshot it DC/OS latest
- [MARATHON-8669](https://jira.mesosphere.com/browse/MARATHON-8669) - enforceRole not respected for POST to /v2/apps if relative path is used.
- [MARATHON-8637](https://jira.mesosphere.com/browse/MARATHON-8637) - persist and expose instance role in /v2/tasks.
- [MARATHON-8673](https://jira.mesosphere.com/browse/MARATHON-8673) - Fix an issue in which the migration for groupRole would fail to run for sub-groups. …
=> Marathon 1.9.34 bump on 1.14-alpha

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/07d053f68b75505a4386913f05d521fa5e36373d...6ecaa5106ffd5b2f712854e97b5386741b1d14a7
=> [1.13] Bump Mesos to nightly 1.8.x 6ecaa51

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch, packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch, packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch, packages/mesos/extra/patches/0004-Added-received-timestamp-into-process-Request.patch, packages/mesos/extra/patches/0005-Added-task-health-check-definitions-to-master-API-re.patch, packages/mesos/extra/patches/0006-Introduced-logResponse-for-http-handlers.patch, packages/mesos/extra/patches/0007-Logged-request-processing-time-for-some-endpoints.patch, packages/mesos/extra/patches/0008-Changed-sandbox-mode-to-0755-in-docker-containerizer.patch, packages/mesos/extra/patches/0009-Added-HEARTBEAT-events-and-calls-for-the-executor-HT.patch, packages/mesos/extra/patches/0010-Refactored-master-and-agent-streaming-connections.patch, packages/mesos/extra/patches/0011-Added-heartbeaters-for-agent-and-HTTP-executors.patch, packages/mesos/extra/patches/0012-Added-tests-for-agent-executor-heartbeating.patch, packages/mesos/extra/patches/0013-Changed-master-to-hold-subscribers-in-a-circular-buf.patch, packages/mesos/extra/patches/0014-Added-gauge-metric-for-operator-event-stream-subscri.patch, packages/mesos/extra/patches/0015-Reverted-the-container-sandbox-permission-from-0750-.patch, packages/mesos/extra/patches/0016-Special-cased-HEARTBEAT-call-handling-in-agent.patch, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/33a1ba97041f178f8be53cdeb7cbeb7c78b89798...ccecf11e250621aad286564ecc1e98c307777277
=> [1.12] Bump Mesos to nightly 1.7.x ccecf11

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/ff8c9a96be6ae1ee47faf9d5b80a518dfb4a3db0...ea953482f82131fcf033aca60145b1471ce4fcb2
=> [master] Bump Mesos to nightly master ea95348

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch, packages/mesos/extra/patches/0002-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch, packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch, packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch, packages/mesos/extra/patches/0005-Displayed-resource-provider-resources-in-GET_RESOURC.patch, packages/mesos/extra/patches/0006-Improved-logging-for-offers-and-inverse-offers.patch, packages/mesos/extra/patches/0007-Introduced-a-push-based-gauge-metric.patch, packages/mesos/extra/patches/0008-Added-a-test-for-PushGauge.patch, packages/mesos/extra/patches/0009-Renamed-Gauge-to-PullGauge-and-documented-difference.patch, packages/mesos/extra/patches/0010-Updated-mesos-source-for-Gauge-PullGauge-renaming.patch, packages/mesos/extra/patches/0011-Enabled-per-framework-metrics-in-the-master.patch, packages/mesos/extra/patches/0012-Added-per-framework-subscribed-metric-and-helpers.patch, packages/mesos/extra/patches/0013-Added-per-framework-metrics-for-scheduler-calls.patch, packages/mesos/extra/patches/0014-Added-per-framework-metrics-for-scheduler-events.patch, packages/mesos/extra/patches/0015-Added-per-framework-offer-metrics.patch, packages/mesos/extra/patches/0016-Added-per-framework-metrics-for-task-states.patch, packages/mesos/extra/patches/0017-Added-per-framework-metrics-for-offer-operations.patch, packages/mesos/extra/patches/0018-Enabled-per-framework-metrics-in-the-allocator.patch, packages/mesos/extra/patches/0019-Changed-the-capacity_-member-of-BoundedHashMap-to-no.patch, packages/mesos/extra/patches/0020-Tracked-completed-framework-metrics-in-the-allocator.patch, packages/mesos/extra/patches/0021-Added-per-framework-metrics-for-suppressed-roles.patch, packages/mesos/extra/patches/0022-Added-task-health-check-definitions-to-master-API-re.patch, packages/mesos/extra/patches/0023-Put-TerminateEvent-at-the-end-of-the-queue-in-the-Me.patch, packages/mesos/extra/patches/0024-Waited-for-TEARDOWN-to-be-sent-in-v1-Java-scheduler-.patch
https://github.com/apache/mesos/compare/6a8b61b59498dcea64d9380a233d517ce65dc2ef...14904009a193636bb715115419bfa2f235beb33f
=> [1.11] Bump Mesos to nightly 1.5.x 1490400

packages/dcos-image-deps/build, packages/dcos-image-deps/buildinfo.json, packages/dcos-integration-test/README.md, packages/dcos-integration-test/requirements.txt, tox.ini
- The only real dependency needed was execnet, not all of pytest-xdist.
- Adding a README for how to run tests
- Pinning all pytest-xdist dependencies because pytest-xdist package doesn't and it sometimes causes errors, like recently when execnet was updated and broke pytest-xdist, even if pytest-xdist version was pinned!
- Moving packages/dcos-integration-test/extra/requirements.txt to packages/dcos-integration-test/requirements.txt so that the whole virtual environment is not copied to the remote cluster when integration tests are ran with pytest-xdist. The whole "extra" directory is synced to the remote cluster when pytest runs.
=> Replace pytest-xdist by execnet

packages/dcos-image-deps/build, packages/dcos-image-deps/buildinfo.json
When pytest-xdist feature was tested, it was determined that execnet had to be installed on the remote host. We have since then added execnet as a dependency to DC/OS. However, it appears pytest-xdist's dependencies are not pinned (moving targets). So without any changes to DC/OS, pytest-xdist feature stopped working. The solution was to not only pin pytest-xdist (was already the case), but also all its dependencies. Those changes went into DC/OS, but there was still an issue that wasn't fixed. Pinning all the dependencies wasn't enough. Adding apipkg on the remote host was also necessary. This was not caught because we don't test pytest-xdist feature in CI. This is about to change with this PR: https://github.com/dcos/dcos/pull/6070
The current PR was also tested with the pytest-xdist …
=> Add apipkg dependency

packages/exhibitor/extra/bootstrap_exhibitor_tls.py
This PR adds new-line stripping to the Exhibitor lock-down PSK reading script.
This PR improves upon existing E2E tests for the automated Exhibitor lock-down feature to make it more easily maintainable.
- [DCOS-57648](https://jira.mesosphere.com/browse/DCOS-57648) Automated Exhibitor lock-down: Clean up E2E tests.
=> Improve upon initial automated Exhibitor lock-down E2E tests

CHANGES.md, gen/build_deploy/bash.py
Backports: https://github.com/dcos/dcos/pull/5993
---
Fix problems with docker version > 1.19 which added new entries to `docker version` output.
Latest docker hase more entries in `docker version` output. See folowing examples
```yaml
Client: Docker Engine - Community
Version:           19.03.1
API version:       1.35 (downgraded from 1.40)
Go version:        go1.12.5
Git commit:        74b1e89
Built:             Thu Jul 25 21:21:07 2019
OS/Arch:           linux/amd64
Experimental:      false
Server:
Engine:
Version:          17.12.1-ce
API version:      1.35 (minimum version 1.12)
Go version:       go1.9.4
Git commit:       7390fc6
Built:            Tue Feb 27 22:20:43 2018
OS/Arch:          linux/amd64
Experimental:     false
```
```yaml
Client: Docker Engine - Community
Version: …
```
=> [1.11] Replace artisanal docer version detect script

packages/cockroach/extra/dcos-cockroachdb-config-change.service, packages/dcos-integration-test/extra/test_cockroach_config.py, packages/dcos-integration-test/extra/test_groups.yaml
This PR adds a test for CockroachDB config changes actually being applied by the corresponding service.
In Enterprise we work around a critical bug that prevented the CockroachDB `num_replicas` being set by the `cockroachdb-config-change.py` script in subsequent runs (after the initial CockroachDB unit start, if unsuccessful) for CockroachDB 2.1.7.
An issue with CockroachDB for the bug has been filed here:
https://github.com/cockroachdb/cockroach/issues/39760
Legacy comments were removed which are no longer true.
- [DCOS-57769](https://jira.mesosphere.com/browse/DCOS-57769) Fix dcos-cockroachdb-config-change to correctly update num_replicas.
=> Add test for CockroachDB config change service

CHANGES.md, gen/build_deploy/bash.py
Backports: https://github.com/dcos/dcos/pull/5993
---
Fix problems with docker version > 1.19 which added new entries to `docker version` output.
Latest docker hase more entries in `docker version` output. See folowing examples
```yaml
Client: Docker Engine - Community
Version:           19.03.1
API version:       1.35 (downgraded from 1.40)
Go version:        go1.12.5
Git commit:        74b1e89
Built:             Thu Jul 25 21:21:07 2019
OS/Arch:           linux/amd64
Experimental:      false
Server:
Engine:
Version:          17.12.1-ce
API version:      1.35 (minimum version 1.12)
Go version:       go1.9.4
Git commit:       7390fc6
Built:            Tue Feb 27 22:20:43 2018
OS/Arch:          linux/amd64
Experimental:     false
```
```yaml
Client: Docker Engine - Community
Version: …
```
=> [1.10] Replace artisanal docer version detect script

packages/exhibitor/extra/bootstrap_exhibitor_tls.py
Changes the location of expected bootstrap PSK
- [DCOS-57650](https://jira.mesosphere.com/browse/DCOS-57650) automated exhibitor lock-down: expect psk under /var/lib/dcos/... (not /root)
=> packages/exhibitor: change location of exhibitor bootstrap psk

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/6ecaa5106ffd5b2f712854e97b5386741b1d14a7...adc958f553c3728aab5529de56b0ddc30c0f9b68
=> [1.13] Bump Mesos to nightly 1.8.x adc958f

packages/adminrouter/extra/src/lib/cache.lua, packages/adminrouter/extra/src/test-harness/tests/test_cache.py, packages/dcos-integration-test/extra/test_adminrouter_open.py
Forward port of #6139
Previously, specifying an invalid `DCOS_SERVICE_PORT_INDEX` value in a Marathon app definition led to `Admin Router` crash looping on Marathon state cache refresh.
Now this scenario logs an appropriate error and the cache refresh continues by skipping such apps.
- [DCOS_OSS-5491](https://jira.mesosphere.com/browse/DCOS_OSS-5491) Admin Router: wrong value in DCOS_SERVICE_PORT_INDEX breaks AR cache.
- [COPS-5147](https://jira.mesosphere.com/browse/COPS-5147) Specifying incorrect DCOS_SERVICE_PORT_INDEX breaks /service routing in adminrouter.
=> [Forward port master] Fix Admin Router: Error on invalid Marathon service port label

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/ccecf11e250621aad286564ecc1e98c307777277...80d42b9a2c9223665a82bbaaf3cbc222a094e2ef
=> [1.12] Bump Mesos to nightly 1.7.x 80d42b9

CHANGES.md, packages/marathon/buildinfo.json
- [MARATHON-8694](https://jira.mesosphere.com/browse/MARATHON-8694) - Allow modification of enforceRole via the PUT /v2/groups endpoint
- [MARATHON-8693](https://jira.mesosphere.com/browse/MARATHON-8693) - Fix rare bug in which resident service because stuck and unremovable when Mesos fails to create a reservation
- [MARATHON-8682](https://jira.mesosphere.com/browse/MARATHON-8682) - Internal refactoring to make treatment of paths in Marathon less error-prone.
=> Bump Marathon to 1.9.71

CHANGES.md, packages/adminrouter/extra/src/lib/cache.lua, packages/adminrouter/extra/src/test-harness/tests/test_cache.py, packages/dcos-integration-test/extra/test_adminrouter_open.py
Previously, specifying an invalid `DCOS_SERVICE_PORT_INDEX` value in a Marathon app definition led to `Admin Router` crash looping on Marathon state cache refresh.
Now this scenario logs an appropriate error and the cache refresh continues by skipping such apps.
- [DCOS_OSS-5491](https://jira.mesosphere.com/browse/DCOS_OSS-5491) Admin Router: wrong value in DCOS_SERVICE_PORT_INDEX breaks AR cache.
- [COPS-5147](https://jira.mesosphere.com/browse/COPS-5147) Specifying incorrect DCOS_SERVICE_PORT_INDEX breaks /service routing in adminrouter.
=> Admin Router invalid Marathon service port fix

test-e2e/requirements.txt
Backport of #6169 
Bump DC/OS E2E to version 2019.08.28.0
- [DCOS-58001](https://jira.mesosphere.com/browse/DCOS-58001) Bump dcos-e2e in 1.12, 1.13 and master branches.
=> [Backport 1.13] Bump DC/OS E2E

test-e2e/requirements.txt
Backport of #6169 
Bump DC/OS E2E to version 2019.08.28.0
- [DCOS-58001](https://jira.mesosphere.com/browse/DCOS-58001) Bump dcos-e2e in 1.12, 1.13 and master branches.
=> [Backport 1.12] Bump DC/OS E2E

gen/dcos-config.yaml, packages/dcos-diagnostics/extra/dcos-diagnostics-master.service, packages/dcos-integration-test/extra/test_metrics.py
This PR redirects Exhibitor clients through Admin Router because with Exhibitor TLS enabled they no longer have direct access.
- [DCOS-57704](https://jira.mesosphere.com/browse/DCOS-57704) Fix DC/OS clients that do not adhere to Exhibitor TLS.
=> Fix Exhibitor clients

test-e2e/requirements.txt
Bump DC/OS E2E to version 2019.08.28.0
- [DCOS-58001](https://jira.mesosphere.com/browse/DCOS-58001) Bump dcos-e2e in 1.12, 1.13 and master branches.
=> Bump DC/OS E2E

CHANGES.md, packages/dcos-net/buildinfo.json
Improves stability of DC/OS Net in case of high-load.
- [DCOS_OSS-5459](https://jira.mesosphere.com/browse/DCOS_OSS-5459) DC/OS Net: use exponential backoff when retrying failed requests to Mesos in order not to impose additional load onto potentially already overloaded Mesos.
- [DCOS_OSS-5461](https://jira.mesosphere.com/browse/DCOS_OSS-5461) DC/OS Net: switch to Erlang/OTP's Logger in order to be able to handle log message bursts without compromising the system stability.
=> Bump DC/OS Net

CHANGES.md, cloud_images/lib/el7/configure_dcos_system.sh, gen/build_deploy/bash.py
ATT&T is blocked from upgrading DC/OS because their security team does not allow non-standard linux group creation. We currently create the `nogroup` group, but it appears that it may not actually be used any longer. It looks like it was originally used by nginx (admin router). Depending where the service was started from, it'd set the nginx configuration to use either the `nobody` group (for Redhat based systems), or the `nogroup` group (for Debian based systems). It looks like we started creating the `nogroup` group on all systems to keep things consistent.
- [COPS-5220](https://jira.mesosphere.com/browse/COPS-5220) …
=> Remove nogroup group creation

CHANGES.md, packages/marathon/buildinfo.json
See corresponding tickets
- [MARATHON-8695](https://jira.mesosphere.com/browse/MARATHON-8695) Fix a regression with Marathon /v2/groups that caused `dcos marathon group update` cli commands to fail.
=> Bump Marathon to 1.9.73

mergebot-config.json
* DCOS-58261 - Set JIRA fix Version to DC/OS 1.14.0
=> Set JIRA fix Version to DC/OS 1.14.0

CHANGES.md, packages/metronome/build
This change modifies the init config file for Metronome to source a post-install configuration file for Metronome, similar to that which exists for Marathon.
- [DCOS_OSS-5509](https://jira.mesosphere.com/browse/DCOS_OSS-5509) Support adding post-install environment variables to Metronome in `/var/lib/dcos/marathon/environment`
N/A
=> Allow post-installation customization of Metronome config

CHANGES.md, packages/metronome/build
This change modifies the init config file for Metronome to source a post-install configuration file for Metronome, similar to that which exists for Marathon.
- [DCOS_OSS-5509](https://jira.mesosphere.com/browse/DCOS_OSS-5509) Support adding post-install environment variables to Metronome in `/var/lib/dcos/marathon/environment`
N/A
=> Allow post-installation customization of Metronome config 

packages/dcos-integration-test/extra/conftest.py
This bumps the dcos-core-cli used in tests to the latest release.
https://jira.mesosphere.com/browse/DCOS-56863
=> Use dcos-core-cli-2.0-patch.2 in tests

CHANGES.md, packages/mesos-modules/buildinfo.json
An HTTP endpoint should be introduced that accepts a list of agent IP addresses to remove from the Mesos overlay state. It is needed to drop such records for agents that are gone.
- [DCOS_OSS-5536](https://jira.mesosphere.com/browse/DCOS_OSS-5536) Mesos overlay networking: support dropping agents from the state
=> [1.12] Bump Mesos modules

CHANGES.md, packages/mesos-modules/buildinfo.json
An HTTP endpoint should be introduced that accepts a list of agent IP addresses to remove from the Mesos overlay state. It is needed to drop such records for agents that are gone.
- [DCOS_OSS-5536](https://jira.mesosphere.com/browse/DCOS_OSS-5536) Mesos overlay networking: support dropping agents from the state
=> [2.0] Bump Mesos modules

CHANGES.md, packages/mesos-modules/buildinfo.json
An HTTP endpoint should be introduced that accepts a list of agent IP addresses to remove from the Mesos overlay state. It is needed to drop such records for agents that are gone.
- [DCOS_OSS-5536](https://jira.mesosphere.com/browse/DCOS_OSS-5536) Mesos overlay networking: support dropping agents from the state
=> Bump Mesos modules

CHANGES.md, packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/cacc0e7a629de4fb1e678d814b30fd716bcb29d7...c115fb0e4842f5c1211c7464d38a7a67994f08ae
https://github.com/dcos/dcos-mesos-modules/compare/694479cfdb0b461e486ab7d51147baaba2621883...b7bb3ffce52c5f57e0c29ce08408952aa9971342
=> [2.0] Bump Mesos to nightly 1.9.x c115fb0

CHANGES.md, packages/mesos-modules/buildinfo.json
An HTTP endpoint should be introduced that accepts a list of agent IP addresses to remove from the Mesos overlay state. It is needed to drop such records for agents that are gone.
- [DCOS_OSS-5536](https://jira.mesosphere.com/browse/DCOS_OSS-5536) Mesos overlay networking: support dropping agents from the state
=> [1.13] Bump Mesos modules

CHANGES.md, dcos_installer/test_backend.py, gen/calc.py
* DCOS-58854 - Set the master version of DC/OS to 2.1.0-dev.
=> Set the master version of DC/OS to 2.1.0-dev.

CHANGES.md, gen/calc.py, gen/dcos-config.yaml
This adds a new config option to the DC/OS installer, marathon_new_group_enforce_role, and defaults it to 'top'. This causes new services for not-yet-created groups to default to use the group-role, rather than the default mesos role. The same thing happens when we 
- [DCOS_OSS-5532](https://jira.mesosphere.com/browse/DCOS_OSS-5532) Change the default for root marathon to enable enforceRole by default for new top-level groups
=> Add marathon_new_group_enforce_role config option to the DC/OS installer

CHANGES.md, cloud_images/lib/el7/configure_dcos_system.sh, gen/build_deploy/bash.py
ATT&T is blocked from upgrading DC/OS because their security team does not allow non-standard linux group creation. We currently create the nogroup group, but it appears that it may not actually be used any longer. It looks like it was originally used by nginx (admin router). Depending where the service was started from, it'd set the nginx configuration to use either the nobody group (for Redhat based systems), or the nogroup group (for Debian based systems). It looks like we started creating the nogroup group on all systems to keep things consistent.
Backports: https://github.com/dcos/dcos/pull/6166
---
- [COPS-5220](https://jira.mesosphere.com/browse/COPS-5220)  …
=> [1.11] Remove nogroup group creation

CHANGES.md, cloud_images/lib/el7/configure_dcos_system.sh, gen/build_deploy/bash.py
ATT&T is blocked from upgrading DC/OS because their security team does not allow non-standard linux group creation. We currently create the nogroup group, but it appears that it may not actually be used any longer. It looks like it was originally used by nginx (admin router). Depending where the service was started from, it'd set the nginx configuration to use either the nobody group (for Redhat based systems), or the nogroup group (for Debian based systems). It looks like we started creating the nogroup group on all systems to keep things consistent.
Backports: https://github.com/dcos/dcos/pull/6166
---
- [COPS-5220](https://jira.mesosphere.com/browse/COPS-5220)  …
=> [1.12] Remove nogroup group creation

CHANGES.md, cloud_images/lib/el7/configure_dcos_system.sh, gen/build_deploy/bash.py
ATT&T is blocked from upgrading DC/OS because their security team does not allow non-standard linux group creation. We currently create the nogroup group, but it appears that it may not actually be used any longer. It looks like it was originally used by nginx (admin router). Depending where the service was started from, it'd set the nginx configuration to use either the nobody group (for Redhat based systems), or the nogroup group (for Debian based systems). It looks like we started creating the nogroup group on all systems to keep things consistent.
Backports: https://github.com/dcos/dcos/pull/6166
---
- [COPS-5220](https://jira.mesosphere.com/browse/COPS-5220)  …
=> [1.13] Remove nogroup group creation

CHANGES.md, packages/dcos-net/buildinfo.json
Upon a Mesos failover or simple reconnect to Mesos, `dcos-net`'s Mesos listener waits for some time till agents are registered and tasks accumulated before publishing updates to its subscribers in order to avoid flushing of DNS records, which might cause unavailability.
- [DCOS_OSS-5463](https://jira.mesosphere.com/browse/DCOS_OSS-5463) dcos-net: use cached Mesos state in case of Mesos instability
- [DCOS_OSS-5523](https://jira.mesosphere.com/browse/DCOS_OSS-5523) dcos-dns polls Mesos DNS on each DC/OS master node
=> [2.0] Bump DC/OS Net

packages/dcos-test-utils/buildinfo.json
This PR bumps `dcos-test-utils` to include new test helpers which are needed for a flaky test fix in the Enterprise build.
- [DCOS-57093](https://jira.mesosphere.com/browse/DCOS-57093) test_secret_leakage.test_pod_secret_leakage looks flaky
=> Bumped dcos-test-utils to include new test helpers.

dcos_installer/test_backend.py, gen/calc.py
* DCOS-59103 - Set the 2.0 DC/OS version to 2.0.0-dev
=> DCOS-59103 - Set the 2.0 DC/OS version to 2.0.0-dev

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/14904009a193636bb715115419bfa2f235beb33f...f902fc6f447f3477e137639824ece7cbf3b31fe7
=> [1.11] Bump Mesos to nightly 1.5.x f902fc6

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
Since the `2.0` branch of DC/OS has been established, the `master` branch should once again point to a commit on the `master` branch of Mesos. This PR accomplishes this change.
- [DCOS_OSS-5342](https://jira.mesosphere.com/browse/DCOS_OSS-5342) Bump Mesos for DC/OS 1.14.0-beta
=> Pointed DC/OS master back to Mesos master.

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/80d42b9a2c9223665a82bbaaf3cbc222a094e2ef...71685b5c807e4d4d1a5ebe33a3c3c0a2f824b9b4
=> [1.12] Bump Mesos to nightly 1.7.x 71685b5

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/adc958f553c3728aab5529de56b0ddc30c0f9b68...ed1c7ee1db94a1c886e3d5a99f66b6abaec30f49
=> [1.13] Bump Mesos to nightly 1.8.x ed1c7ee

CHANGES.md, packages/adminrouter/extra/src/lib/cache.lua
Fix for an edge case where the marathon apps endpoint returns null for the task list instead of an empty array
- [DCOS_OSS-5541](https://jira.mesosphere.com/browse/DCOS_OSS-5541) AdminRouter Cache Fails When Marathon returns no task field
=> Check if the returned JSON from marathon actually is an empty list or nil

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/4895d4430f1349dc126fb004102184f8d0e9d2b3...88697cb136555a7c7406349cbb78c6f3b15beac5
=> [2.0] Bump Mesos to nightly 1.9.x 88697cb

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/ed1c7ee1db94a1c886e3d5a99f66b6abaec30f49...91e6cef51e98bc4a4daca6f4941d9f0121046d76
=> [1.13] Bump Mesos to nightly 1.8.x 91e6cef

CHANGES.md, gen/dcos-config.yaml, packages/marathon/buildinfo.json
Bump Marathon to 1.8.230
Also, backport pod-status change
- [MARATHON-8698](https://jira.mesosphere.com/browse/MARATHON-8698) - Marathon tries to store Task StatusUpdate without checking the message size
- [DCOS_OSS-5616](https://jira.mesosphere.com/browse/DCOS_OSS-5616) - Include Marathon pod instances in diagnostic bundle
=> Bump Marathon to 1.8.230 (and include pod instances in diagnostic bundle)

CHANGES.md, packages/dcos-net/buildinfo.json
Various `dcos-net` bug-fixes.
- [DCOS_OSS-5620](https://jira.mesosphere.com/browse/DCOS_OSS-5620) DC/OS overlay networks should be compared by-value.
- [DCOS_OSS-5634](https://jira.mesosphere.com/browse/DCOS_OSS-5634) Drop labels from Lashup's kv_message_queue_overflows_total metric.
=> [1.13] Bump dcos-net

CHANGES.md, packages/dcos-net/buildinfo.json
Various `dcos-net` bug-fixes.
- [DCOS_OSS-5495](https://jira.mesosphere.com/browse/DCOS_OSS-5495) dcos-net: task update leads to two DNS zone updates.
- [DCOS_OSS-5620](https://jira.mesosphere.com/browse/DCOS_OSS-5620) DC/OS overlay networks should be compared by-value.
- [DCOS_OSS-5634](https://jira.mesosphere.com/browse/DCOS_OSS-5634) Drop labels from Lashup's kv_message_queue_overflows_total metric.
=> [2.0] Bump dcos-net

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/f902fc6f447f3477e137639824ece7cbf3b31fe7...ea5e6e87eb5053dcfbcb11237902d3e2126c41cf
=> [1.11] Bump Mesos to nightly 1.5.x ea5e6e8

CHANGES.md, packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/71685b5c807e4d4d1a5ebe33a3c3c0a2f824b9b4...d8acd9cfacd2edf8500f07f63a8837aa0ddd14ba
https://github.com/dcos/dcos-mesos-modules/compare/3f87e3d7d4706decdc20a046fa280a47c2e2954a...e6cd9e3844a666752b4758e383a5d46e965a27db
=> [1.12] Bump Mesos to nightly 1.7.x d8acd9c

CHANGES.md, packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/88697cb136555a7c7406349cbb78c6f3b15beac5...c31316814398990abf1013bb0681a907426a4fec
https://github.com/dcos/dcos-mesos-modules/compare/e9edd2d93d9fce88c8e3f5536c7f9abc326093d9...c5cf5bd36307c6461e74fc5a4743c27b94c00e75
=> [2.0] Bump Mesos to nightly 1.9.x c313168

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/270a3dce490d5b334f9a0011ea416ffc42e187e4...2a1c5d518b43be21673b2cfdf72fc2e60658a826
=> [master] Bump Mesos to nightly master 2a1c5d5

CHANGES.md, packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/91e6cef51e98bc4a4daca6f4941d9f0121046d76...0744bb6185cd181a8f4ab678a9220c5359f0e0f9
https://github.com/dcos/dcos-mesos-modules/compare/43250a0e30804d2f28d16c400f7980e6ad7463bc...26d45a9f43f3c6b6c664c2ca43b74ce24c9f05ca
=> [1.13] Bump Mesos to nightly 1.8.x 0744bb6

mergebot-config.json
A part of preparation for the release of **backport** command for Mergebot. Need to enable it in the repo config.
=> Enable backport mergebot command in repo config

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/c31316814398990abf1013bb0681a907426a4fec...95d34e7f30c6ca8a074bd2af0359ed96310adee3
=> [2.0] Bump Mesos to nightly 1.9.x 95d34e7

packages/marathon/buildinfo.json
This fixes a Marathon migration error that would occur during upgrade if a Marathon deployment was in progress during the upgrade attempt.
JIRA Issues:
- [MARATHON-8712](https://jira.mesosphere.com/browse/MARATHON-8712)
- [MARATHON-8711](https://jira.mesosphere.com/browse/MARATHON-8711)
- [MARATHON-8713](https://jira.mesosphere.com/browse/MARATHON-8713)
=> 2.0 - Bump marathon to 1.9.108

packages/marathon/buildinfo.json
This fixes a Marathon migration error that would occur during upgrade if a Marathon deployment was in progress during the upgrade attempt.
JIRA Issues:
- [MARATHON-8712](https://jira.mesosphere.com/browse/MARATHON-8712)
- [MARATHON-8711](https://jira.mesosphere.com/browse/MARATHON-8711)
- [MARATHON-8713](https://jira.mesosphere.com/browse/MARATHON-8713)
=> 2.1 - bump Marathon to 1.9.109

CHANGES.md, packages/dcos-net/extra/dcos-net-setup.py
This was first introduced in https://github.com/dcos/dcos/pull/2833 which set network interfaces used by DC/OS as unmanaged by networkd on all releases of Linux, and before this happens only on coreos. 
This may bring errors when networkd is enabled on other Linux releases, refer to [cops ticket explanation](https://jira.mesosphere.com/browse/COPS-5575?focusedCommentId=303879&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-303879) for detailed explanation.
Here we change the configuration takes effect only on coreos, and since coreos 1409.x.0, unmanaged link is supported in coreos networkd. But the interfaces are unmanaged by default.
```
[root@osboxes2 ~]# networkctl
IDX LINK …
```
=> [1.12] set interfaces as unmanaged by coreos networkd

CHANGES.md, packages/dcos-net/extra/dcos-net-setup.py
This was first introduced in https://github.com/dcos/dcos/pull/2833 which set network interfaces used by DC/OS as unmanaged by networkd on all releases of Linux, and before this happens only on coreos. 
This may bring errors when networkd is enabled on other Linux releases, refer to [cops ticket explanation](https://jira.mesosphere.com/browse/COPS-5575?focusedCommentId=303879&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-303879) for detailed explanation.
Here we change the configuration takes effect only on coreos, and since coreos 1409.x.0, unmanaged link is supported in coreos networkd. But the interfaces are unmanaged by default.
```
[root@osboxes2 ~]# networkctl
IDX LINK …
```
=> [2.0] set interfaces as unmanaged by coreos networkd

CHANGES.md, packages/dcos-net/extra/dcos-net-setup.py
This was first introduced in https://github.com/dcos/dcos/pull/2833 which set network interfaces used by DC/OS as unmanaged by networkd on all releases of Linux, and before this happens only on coreos. 
This may bring errors when networkd is enabled on other Linux releases, refer to [cops ticket explanation](https://jira.mesosphere.com/browse/COPS-5575?focusedCommentId=303879&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-303879) for detailed explanation.
Here we change the configuration takes effect only on coreos, and since coreos 1409.x.0, unmanaged link is supported in coreos networkd. But the interfaces are unmanaged by default.
```
[root@osboxes2 ~]# networkctl
IDX LINK …
```
=> [master] set interfaces as unmanaged by coreos networkd

CHANGES.md, packages/dcos-net/extra/dcos-net-setup.py
This was first introduced in https://github.com/dcos/dcos/pull/2833 which set network interfaces used by DC/OS as unmanaged by networkd on all releases of Linux, and before this happens only on coreos. 
This may bring errors when networkd is enabled on other Linux releases, refer to [cops ticket explanation](https://jira.mesosphere.com/browse/COPS-5575?focusedCommentId=303879&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-303879) for detailed explanation.
Here we change the configuration takes effect only on coreos, and since coreos 1409.x.0, unmanaged link is supported in coreos networkd. But the interfaces are unmanaged by default.
```
[root@osboxes2 ~]# networkctl
IDX LINK …
```
=> [1.13] set interfaces as unmanaged by coreos networkd

packages/winpanda/extra/src/winpanda/bin/winpanda.py, packages/winpanda/extra/src/winpanda/common/constants.py
1) create applications log directory on fixed location -
"C:\d2iq\dcos\var\log\winpanda"
2) increase upper limit of the log file size
JIRA: DCOS_OSS-5733 - Winpanda App: Adjust Log Directory Location
=> Winpanda App: Adjust Log Directory Location

packages/winpanda/extra/src/winpanda/common/utils.py, packages/winpanda/extra/src/winpanda/core/command.py, packages/winpanda/extra/src/winpanda/svcm/exceptions.py, packages/winpanda/extra/src/winpanda/svcm/nssm.py
1) implement operation retrying helper tools
2) rework the winpanda "start" command to support retrying logic for service
start operation
3) change logic of the winpanda "start" command for not to fail entire
chain of service start commands, if a single service fails to start
JIRA: DCOS_OSS-5731 - Winpanda App: Tolerate Service Start Failures
=> Winpanda App: Tolerate Service Start Failures

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/2a1c5d518b43be21673b2cfdf72fc2e60658a826...0bf3646174e02062abc5170e5f0c68376f1ced96
https://github.com/dcos/dcos-mesos-modules/compare/c5cf5bd36307c6461e74fc5a4743c27b94c00e75...2043f7ead0f1f928554f869a0c16a0e4cf40afe4
=> [master] Bump Mesos to nightly master 0bf3646

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/0bf3646174e02062abc5170e5f0c68376f1ced96...77ba44ccd6837367ed3a059fc559b2dd7dcf06ec
=> [master] Bump Mesos to nightly master 77ba44c

packages/winpanda/extra/src/winpanda/core/command.py
1) change logic of the "Setup" command to perform all the package configuration preparation steps before calling package's custom extra installation helpers and setting up a corresponding service
JIRA: DCOS_OSS-5793 - Package Extra Installation Helper Fails Because of
Incomplete Package Config
=> Winpanda App: Fix Sparse Package Configuration Processing

gen/build_deploy/bash.py
Corresponding JIRA ticket:
https://jira.mesosphere.com/browse/DCOS-59406
Backport of #5766
xfs_info - use mount point instead of a device
Back-porting this fix specifically to 1.12.3 as per customer request: https://jira.mesosphere.com/browse/COPS-5604
=> Unicom 1.12.5

packages/adminrouter/extra/src/nginx.master.conf
etcd does not tollerate the `authorization` header we set to do authn&authz as it expects it's own authorization token there instead of DC/OS authentication token. The solution is to filter it out in AR.
- https://jira.mesosphere.com/browse/DCOS-62479 `Prevent AR from passing Authorization header to etcd`
=> admin router: prevent adminrouter from passing authrization header to etcd

packages/winpanda/extra/src/winpanda/common/utils.py, packages/winpanda/extra/src/winpanda/core/command.py, packages/winpanda/extra/src/winpanda/core/package/package.py, packages/winpanda/extra/src/winpanda/extm/extm.py, packages/winpanda/extra/src/winpanda/tests/test_common_utils.py
1) check and handle exit code from package extra installation helper
2) catch and save stdout/stderr streams from package extra installtion helper to facilitate debugging process
JIRA: DCOS_OSS-5785 - Winpanda Is To Handle Subprocess Exit Codes
JIRA: DCOS_OSS-5786 - Winpanda App: Redirect stdout and stderr Streams From
an External Command To Dedicated Log Files
=> Winpanda App: Handle Execution Status Of External Commands

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/77ba44ccd6837367ed3a059fc559b2dd7dcf06ec...34bac34419ebec8441e69d3a5684381468352399
=> [master] Bump Mesos to nightly master 34bac34

CHANGES.md, packages/adminrouter/extra/src/includes/http/common-windows.conf, packages/adminrouter/extra/src/includes/http/common.conf
This format provides a clearer layout for Admin Router logs:
- AR worker
- `<` client identity and request
- `>` proxy server identity and response, with `code=xxx` to make searching for response statuses easier
It also adds the connection ID which is useful for matching access logs to error logs, and the source port which can be useful for matching with client logs.
With these changes, logs now look like:
```
Jan 10 14:53:00 master1 nginx[3632]: master1 nginx: 2020/01/10 14:53:00 [notice] 3632#0: *77 [lua] common.lua:183: validate_jwt(): UID from the valid DC/OS authentication token: `dcos_checks_master`, client: 172.17.0.2, server: master.mesos, request: "GET /exhibitor/exhibitor/v1/ui/index.html HTTP/1.1", host: "172.17.0.2:443"
Jan 10 14:53:00 master1 nginx[3632]: master1 nginx: …
```
=> Modify Admin Router log format

CHANGES.md, gen/calc.py, gen/dcos-config.yaml, packages/dcos-integration-test/extra/test_composition.py, packages/mesos/build, packages/mesos/buildinfo.json, packages/mesos/extra/dcos-mesos-slave-public.service, packages/mesos/extra/dcos-mesos-slave-public.socket, packages/mesos/extra/dcos-mesos-slave.service, packages/mesos/extra/dcos-mesos-slave.socket
This PR enables support for the mesos agent to communicate with executors via domain sockets, to enable operators to enable stricter firewall settings on their mesos agents.
https://jira.mesosphere.com/browse/DCOS-58820
- [DCOS-58820](https://jira.mesosphere.com/browse/DCOS-58820) Domain socket based agent/executor communication.
=> Add unix domain socket support for Mesos agents

packages/winpanda/extra/src/winpanda/extm/extm.py
1) raise package extra installation helpers execution timeout from 30 sec to 90 sec
JIRA: DCOS_OSS-5841 - Winpanda App: Raise Timeout For Extra Installation Helpers
=> Winpanda App: Raise Timeout For Extra Installation Helpers

CHANGES.md, packages/marathon/buildinfo.json
- [MARATHON-8719](https://jira.mesosphere.com/browse/MARATHON-8719) With UnreachableStrategy, setting expungeAfterSeconds and inactiveAfterSeconds to the same value will cause the instance to be expunged immediately; this helps with `GROUP_BY` or `UNIQUE` constraints.
- [MARATHON-8720](https://jira.mesosphere.com/browse/MARATHON-8720) Fix regression in `ExpungeOverdueLostTaskActor`.
=> Bump Marathon to 1.9.124-e04033c6f

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/21ccad220f04369a7accf2bafae8f1d5002646bb...3d197d8e815f1f2de0565ce64547f409997c5e82
https://github.com/dcos/dcos-mesos-modules/compare/2043f7ead0f1f928554f869a0c16a0e4cf40afe4...7d91c7f92c94f483f427e74b55046e34df0420c7
=> [master] Bump Mesos to nightly master 3d197d8

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/ea5e6e87eb5053dcfbcb11237902d3e2126c41cf...d440095b5a94872eabbd66def49a588d6f8f2b38
=> [1.11] Bump Mesos to nightly 1.5.x d440095

.github/CODEOWNERS, PULL_REQUEST_TEMPLATE.md, mergebot-config.json
- https://jira.d2iq.com/browse/D2IQ-63811 - Mergebot FixVersion was not updated for D2IQ- JIRA tickets.
=> Add D2IQ to the supported JIRA prefix.

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/3d197d8e815f1f2de0565ce64547f409997c5e82...4990d2cd6e76da340b30e200be0d700124dac2b1
=> [master] Bump Mesos to nightly master 4990d2c

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/c7c716dbc9ee4363ba6267591585b9984d8920b8...b17ed79106b11c5f382006c453b4f885721e3f23
=> [1.13] Bump Mesos to nightly 1.8.x b17ed79

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/d8acd9cfacd2edf8500f07f63a8837aa0ddd14ba...8af5a6d50c64abb683b803f25bbc02e320fe70f6
=> [1.12] Bump Mesos to nightly 1.7.x 8af5a6d

packages/winpanda/extra/src/winpanda/svcm/nssm.py
1) fix passing command line arguments to external commands executed as
sub-processes
2) refactor the external command launch method of the NSSM-based windows
service manager type
3) refactor service management (API) methods of the NSSM-based windows
service manager type
4) add support for the "AppEnvironment" NSSM configuration option
5) improve logging and error reporting
JIRA: DCOS_OSS-5769 - Winpanda App: Mishandling Of The AppEnvironmentExtra
Option For NSSM
=> Winpanda App: Fix Mishandling Of The AppEnvironmentExtra Option For NSSM

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/4990d2cd6e76da340b30e200be0d700124dac2b1...cb8106fb7fc9282232a98b27bd1aca43c52a7f69
=> [master] Bump Mesos to nightly master cb8106f

CHANGES.md, packages/marathon/buildinfo.json
Bump Marathon to 1.7.236
- [MARATHON-8632](https://jira.mesosphere.com/browse/MARATHON-8632) - Fix a race condition after startup prevents suppressing offers
- [MARATHON-8719](https://jira.mesosphere.com/browse/MARATHON-8719) - With unreachable instances, UnreachableInactive causes issues with placement constraints
- [MARATHON-8721](https://jira.mesosphere.com/browse/MARATHON-8721) - /v2/tasks plaintext output in Marathon 1.5 and later returns container network endpoints in an unusable way
- [MARATHON-8698](https://jira.mesosphere.com/browse/MARATHON-8698) - Marathon tries to store Task StatusUpdate without checking the message size
- [MARATHON-8660](https://jira.mesosphere.com/browse/MARATHON-8660) - Include maintenance mode configuration in info Endpoint
- …
=> Bump Marathon to 1.7.236

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/cb8106fb7fc9282232a98b27bd1aca43c52a7f69...ea670eca55af847bd7fcba1510726dd0059edf32
=> [master] Bump Mesos to nightly master ea670ec

CHANGES.md, packages/marathon/buildinfo.json
Bump Marathon to 1.8.239
JIRA Issues:
- [MARATHON-8721](https://jira.mesosphere.com/browse/MARATHON-8721)
- [MARATHON-8719](https://jira.mesosphere.com/browse/MARATHON-8719)
- [MARATHON-8725](https://jira.mesosphere.com/browse/MARATHON-8725)
=> Bump Marathon to 1.8.239

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/b17ed79106b11c5f382006c453b4f885721e3f23...bb32bf8732af3e941aa651c82f5c4f3f03e2e139
=> [1.13] Bump Mesos to nightly 1.8.x bb32bf8

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/8af5a6d50c64abb683b803f25bbc02e320fe70f6...3c4691e1c13d2908389436794b420dd9e19bd92a
=> [1.12] Bump Mesos to nightly 1.7.x 3c4691e

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/4575c9b452c25f64e6c6cc3eddc12ed3b1f8538b...b84b0a4bd8945b0901214b90b61e6a54fa4b3215
=> [2.0] Bump Mesos to nightly 1.9.x b84b0a4

packages/winpanda/extra/src/winpanda/common/utils.py
This is FIX for common.utils.retry_on_exc function. This FIX change default parameter `max_attempts` value from 0 to 1 because in a case 0 attemps decorated function will not be invoked. 
- [D2IQ-64994](https://jira.d2iq.com/browse/D2IQ-64994) Default max_attempts for common.utils.retry_on_exc function does not invoke decorated function.
=> Fix max_attempts for common.utils.retry_on_exc function

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/test_composition.py, packages/dcos-integration-test/extra/test_dcos_diagnostics.py, packages/dcos-integration-test/extra/test_endpoints.py, packages/dcos-integration-test/extra/test_rexray.py, packages/dcos-integration-test/extra/test_units.py, packages/dcos-integration-test/extra/test_windows.py, test_util/README.md, test_util/windows.tfvars
Select all Windows tests from D2IQ-61892. We mark those as expecting to fail that have
not been fixed yet. The tests are simply run by passing `--windows-only` to `pytest`.
=> Select Windows tests

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/ea670eca55af847bd7fcba1510726dd0059edf32...aefa4bdb8a111c74f1d0f7e851a486f4e2ec47e7
=> [master] Bump Mesos to nightly master aefa4bd

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/aefa4bdb8a111c74f1d0f7e851a486f4e2ec47e7...9ba066a7d3372d51c9ff111ae613eed9b565738d
=> [master] Bump Mesos to nightly master 9ba066a

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/9ba066a7d3372d51c9ff111ae613eed9b565738d...54227a33b68d83b97ef1a7c14283351d45322317
=> [master] Bump Mesos to nightly master 54227a3

build_genconf_windows.ps1, gen/build_deploy/powershell.py
There is issue in broken compatibility of old Ansible container "mesosphere/dcos-ansible-bundle:windows-beta-support" with recent (new) changes to DC/OS installer(s) - another word move of dcos_install.ps1 from DC/OS Windows installer to DC/OS Linux installer.
There is a task under Bootstrap role called "Unpack Windows installer packages" in Ansible. How does it work - if dcos_install.ps1 missing on file system, then Ansible unpacks Windows installer. Otherwise skip the task. Another word - the dcos_install.ps1 used as trigger to run the task. And now this file is unpacked earlier by DC/OS Linux installer.
To resolve the issue unpack of dcos_install.ps1 by DC/OS Windows Installer and DC/OS Linux Installer proposed to  different locations:
Windows' one -  to …
=> [Windows Upgrade] Hotfix: added backward compatibility of new DC/OS Linux installer with upgrade func vs old Ansible Windows BETA container

gen/aws/templates/advanced/advanced-master.json, gen/aws/templates/advanced/infra.json, gen/aws/templates/cloudformation.json
This PR adds support for newly added Admin Router's gRPC port.
- [D2IQ-ID](https://jira.d2iq.com/browse/D2IQ-62476) Adjust cloud formation templates and Terraform modules to open AR's new gRPC port
=> CLOUD_FORMATION: Add Admin Router gRPC port

packages/winpanda/extra/src/winpanda/bin/winpanda.py, packages/winpanda/extra/src/winpanda/common/cli.py, packages/winpanda/extra/src/winpanda/common/constants.py, packages/winpanda/extra/src/winpanda/common/storage.py, packages/winpanda/extra/src/winpanda/core/cmdconf.py, packages/winpanda/extra/src/winpanda/core/command.py, packages/winpanda/extra/src/winpanda/core/exceptions.py, packages/winpanda/extra/src/winpanda/core/istate.py, packages/winpanda/extra/src/winpanda/core/package/manifest.py, packages/winpanda/extra/src/winpanda/core/package/package.py, packages/winpanda/extra/src/winpanda/svcm/exceptions.py
1) add configuration manager type for the "upgrade" command (CmdConfigUpgrade)
2) add command manager type for the "upgrade" command (CmdUpgrade)
3) add DC/OS installation state manager type (InstallationState)
4) add support for DC/OS installation state recognition/handling to the "setup" command manager (CmdSetup)
5) fix issue of mishandling DC/OS installation root directory in the DC/OS installation storage manager (InstallationStorage)
6) move package specific functionality from command manager classes (CmdSetup, CmdUpgrade) to the package manager class (Package) for better code reuse
7) add TODO sections to guide further codebase improvements
- [D2IQ-64317](https://jira.mesosphere.com/browse/D2IQ-64317) Winpanda App: Implement the "Upgrade" command
=> Winpanda App: Add the Upgrade command

gen/build_deploy/powershell/dcos_install.ps1.in, gen/build_deploy/powershell/dcos_node_upgrade.ps1.in
BugFix: currently if some NativeApplication being failed on Windows machine, and then when the detect script (cmdlet) is ran, $LASTEXITCODE of a previous Native Application (not cmdlet, but python, or an exe, or some service) being picked up instead of real exit code of cmdlet. As per official documentation $LASTEXICODE works only with external apps such as cmds, python, exe, etc, but not with Powershell cmdlets. Which is very odd limitation of PS as scripting language. 
Therefore for running the detect script only "Invoke-NativeApplication" removed as executor, new executor  suggested -  simple `try { } catch { }`  construction.
- [D2IQ-65203](https://jira.d2iq.com/browse/D2IQ-65203)  upgrade_win.ps1 stops with an error
- [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA …
=> [Windows Upgrade] [BugFix] D2IQ-65203: fixed way the detect script is executed

test_util/Makefile, test_util/README.md, test_util/main.tf
* D2IQ-65138  - Enable CI for Windows Tests on Open 
We are going to enable CI for windows tests on Open DC/OS via Makefile.
---
This introduces testing based on a checkined `main.tf` and with Makefile.
The pipeline here setups only these.
* Introduces steps for `make test`
* Setups a CI pipeline for [Open DC/OS](https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Open_Test_IntegrationTest_WindowsIntegrationTEsts&branch_DcOs_Open_Test_IntegrationTest=pull%2F6965&tab=buildTypeStatusDiv) and [Enterprise DC/OS](https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Enterprise_Test_Inte_WindowsIntegrationTest&branch_DcOs_Enterprise_Test_Inte=pull%2F7471&tab=buildTypeStatusDiv)
* This will start reporting status to the Open and Enterprise PRs.
* Same `makefile` is used for …
=> Introduce Makefile in test_util directory to exercise integration tests for Windows

packages/dcos-integration-test/extra/test_metrics.py
```python
test_metrics.py::test_metrics_ping PASSED
test_metrics.py::test_metrics_agents_prom PASSED
test_metrics.py::test_metrics_procstat PASSED
test_metrics.py::test_metrics_agents_mesos PASSED
test_metrics.py::test_metrics_master_mesos PASSED
test_metrics.py::test_metrics_agents_mesos_overlay PASSED
test_metrics.py::test_metrics_master_mesos_overlay PASSED
test_metrics.py::test_metrics_master_zookeeper PASSED
test_metrics.py::test_metrics_master_cockroachdb PASSED
test_metrics.py::test_metrics_master_calico PASSED
test_metrics.py::test_metrics_agents_calico PASSED
test_metrics.py::test_metrics_master_adminrouter_nginx_vts PASSED
test_metrics.py::test_metrics_master_exhibitor_status PASSED
test_metrics.py::test_metrics_master_adminrouter_nginx_drop_requests_seconds PASSED …
```
=> Enable test_metrics on Windows.

packages/calico/README.md
Adding documentation regarding the `calico-libnetwork-plugin` support on DC/OS.
- [D2IQ-62589](https://jira.d2iq.com/browse/D2IQ-62589) add doc for for calico libnetwork
_(none)_
=> D2IQ-62589: Add calico-libnetwork documentation

test_util/Makefile, test_util/main.tf
* Enable TemCity CI steps in `pytest` runs.
* Set `DCOS_LOGIN_UNAME` and `DCOS_LOGIN_PW` for enterprise tests.
* Create service messages for TeamCity.
* Concat Windows and Linux agent private IPs.
- [D2IQ-65651](https://jira.d2iq.com/browse/D2IQ-65651) 
- [D2IQ-65649](https://jira.d2iq.com/browse/D2IQ-65649)
=> Run integration tests with TeamCity output.

packages/dcos-integration-test/extra/test_endpoints.py
`test_endpoints.test_if_all_mesos_slaves_have_registered` passes as expected.
This we can remove the `xfail`.
=> Enable test_endpoints for Windows.

packages/dcos-integration-test/extra/test_composition.py
* `state.json` was removed from Mesos.
* `docker` is not part of the Windows units status.
- [D2IQ-65706](https://jira.d2iq.com/browse/D2IQ-65706) Fix test_composition for Windows.
=> Fix test_composition for Windows.

packages/dcos-integration-test/extra/test_dcos_diagnostics.py
The Mesos service unit has a different name on Windows so we query that one as well.
The expected files of the diagnostics bundle are different as well.
- [D2IQ-65707](https://jira.d2iq.com/browse/D2IQ-65707)
=> Fix `test_dcos_diagnotics` for Windows.

CHANGES.md, packages/marathon/buildinfo.json
Bump Marathon to 1.9.136
JIRA Issues:
-  [MARATHON-8731](https://jira.mesosphere.com/browse/MARATHON-8731) - Marathon checks validation for unrelated apps when performing a kill operations
- [MARATHON-8716](https://jira.mesosphere.com/browse/MARATHON-8716) - Too many instances of deploying application killed after leader re-election
- [MARATHON-8721](https://jira.mesosphere.com/browse/MARATHON-8721) - /v2/tasks plaintext output in Marathon 1.5 and later returns container network endpoints in an unusable way
- [MARATHON-8725](https://jira.mesosphere.com/browse/MARATHON-8725)
=> 2.0: Bump Marathon to 1.9.136

CHANGES.md, packages/metronome/buildinfo.json
Bump Metronome to 0.6.41
- [MARATHON-8730](https://jira.mesosphere.com/browse/MARATHON-8730)
- [MARATHON-8709](https://jira.mesosphere.com/browse/MARATHON-8709)
=> 2.0: Metronome bump to 0.6.41

gen/dcos-config.yaml, packages/etcd/README.md, packages/etcd/build, packages/etcd/extra/etcdctl/dcos_etcdctl.py, packages/exhibitor/extra/dcos_zk_backup.py, test-e2e/test_etcd_backup.py, test-e2e/test_groups.yaml
_This PR rebases https://github.com/dcos/dcos/pull/6957_
This PR introduces a utility `dcos-etcdctl` on `/opt/mesosphere` that can be used to import/export the etcd state.
- [D2IQ-66110](https://jira.d2iq.com/browse/D2IQ-66110) https://jira.d2iq.com/browse/D2IQ-66110.
- [D2IQ-58912](https://jira.d2iq.com/browse/D2IQ-58912) include etcd in backup and diagnostic bundles.
=> Backup and restore etcd

packages/dcos-integration-test/extra/test_mesos.py, packages/dcos-integration-test/extra/test_windows.py
The Windows app test should pass because the `windows-` fault domains have been
removed.
- [D2IQ-66235](https://jira.d2iq.com/browse/D2IQ-66235)
- [D2IQ-65808](https://jira.d2iq.com/browse/D2IQ-65808)
=> Enable Windows App tests.

CHANGES.md, packages/mesos-modules/windows.buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/12e5e870c38681bfc0455960f89a41127dac3daf...beaf0cd844f3658bfccb86049f7181036b0e6ae4
https://github.com/dcos/dcos-mesos-modules/compare/6231ccf068c247064d1915298070d84885678351...4ba1e573ec4a80ec1d5514d54d5cc9529e5e1d98
=> [master] Bump Mesos to nightly master beaf0cd

CHANGES.md, packages/marathon/buildinfo.json
Bump Marathon to 1.10.6, fixing a critical issue that would cause Marathon to sometimes fail to start.
- [MARATHON-8741](https://jira.d2iq.com/browse/MARATHON-8741) LaunchQueueActor receives command to load instances before leader election occurs
=> Bump marathon with flake fix

CHANGES.md
Marathon 1.9 deprecated the specification of invalid acceptedResourceRoles. In Marathon 1.10, we're turning it off by default. We should make this clear to users that are upgrading.
=> Note an important breaking change

packages/dcos-integration-test/extra/test_metrics.py
* Fixing Strict mode on Windows so that telegraph can authenticate with Mesos.
- [D2IQ-66230](https://jira.d2iq.com/browse/D2IQ-66230) Telegraf cannot auth with Mesos
=> Enable Telegraf test on Windows.

gen/build_deploy/aws.py
previous AMIs have been deprecated by CoreOS.
=> Update CoreOS AMIs for cloudformation

CHANGES.md, packages/mesos-modules/windows.buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/beaf0cd844f3658bfccb86049f7181036b0e6ae4...e6b15b1e968649c794d67bb97961e8f0216e2ed8
=> [master] Bump Mesos to nightly master e6b15b1

CHANGES.md, packages/metronome/buildinfo.json
Bump Metronome to 0.6.42; add networking support to Metronome.
- [MARATHON-8727](https://jira.mesosphere.com/browse/MARATHON-8727)
- x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [a4d46e8..b46cd62](https://github.com/dcos/metronome/compare/a4d46e8...b46cd62)
=> Bump Metronome to 0.6.42

packages/dcos-integration-test/extra/test_ucr.py
Fix the integration test `test_if_ucr_pods_can_be_deployed_with_auto_cgroups` for nested cgroups support.
- [D2IQ-66711](https://jira.d2iq.com/browse/D2IQ-66711) test_ucr.test_if_ucr_pods_can_be_deployed_with_auto_cgroups.
=> Fix an integration test for nested cgroups support.

packages/dcos-integration-test/extra/test_helpers.py
sometimes test deploying docker app fails. This PR adjust settings to limit resources and increase grace period and health check interval.
https://teamcity.mesosphere.io/viewLog.html?buildId=2698101&buildTypeId=DcOs_Enterprise_Test_Inte_WindowsIntegrationTestStrict
=> Change options for default docker app

CHANGES.md, packages/marathon/buildinfo.json
Bump Marathon to 1.8.242
- Marathon was checking authorization for unrelated apps when performing a kill-and-scale operations; this has been resolved.  [MARATHON-8741](https://jira.mesosphere.com/browse/MARATHON-8741)
=> 1.13: Bump Marathon to 1.8.242

CHANGES.md, packages/mesos-modules/windows.buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/e6b15b1e968649c794d67bb97961e8f0216e2ed8...00466fe6138138ead1ca676df37c3af69104956d
=> [master] Bump Mesos to nightly master 00466fe

packages/calico/extra/create-calico-docker-network.py
Fixes a condition where the ZK lock remains acquired. This can be catastrophic since it might block the regular boot sequence of the agents, requiring a manual intervention on removal of the lock from zookeeper. 
- [D2IQ-67029](https://jira.d2iq.com/browse/D2IQ-67029) Revise the way the dcos-calico-libnetwork-plugin.service acquires cluster-wide lock.
_None_
=> D2IQ-67029: Guarding against exceptions while in ZK lock

packages/mesos-modules/windows.build.ps1, packages/mesos/windows.build.ps1
This speeds up mesos and mesos-modules Windows build scripts by 15 minutes each.
- [D2IQ-67207](https://jira.d2iq.com/browse/D2IQ-67207) Windows builds of Mesos and mesos-modules on DCOS OSS hang for 15 munutes after cmake exit.
=> Eliminated 15-minutes hang after completing mesos/mesos-modules cmake.

CHANGES.md, packages/metronome/buildinfo.json
- A bug was introduced in Metronome for DC/OS 2.0.3 in which jobs created in previous versions of DC/OS were not seen. This has been fixed, and jobs created before 2.0.3 are visible once again.  [MARATHON-8746](https://jira.mesosphere.com/browse/MARATHON-8746)
- Metronome jobs can be configured to join container networks - [MARATHON-8727](https://jira.mesosphere.com/browse/MARATHON-8727)
=> Bump Metronome to 0.6.44

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/00466fe6138138ead1ca676df37c3af69104956d...8682b5ddf8b773beffe8bf0428c9350d6ae59412
=> [master] Bump Mesos to nightly master 8682b5d

CHANGES.md, packages/mesos/buildinfo.json
This changes ref_origin in `mesos` pachake to 1.10.x  Mesos branch and bumps Mesos.
- [D2IQ-68266](https://jira.d2iq.com/browse/D2IQ-68266) Make DCOS 2.1 branch use corresponding branches of mesos/modules.
=> Bumped mesos to 1.10.x d4afcd10b6

CHANGES.md, packages/marathon/buildinfo.json
Bump Marathon to 1.10.17; fix important bug where apps are not restart in response to resourceLimits. 
JIRA Issues:
- [MARATHON-8744](https://jira.mesosphere.com/browse/MARATHON-8744) - Restart tasks when updating only resourceLimits
- [D2IQ-67033](https://jira.mesosphere.com/browse/D2IQ-67033) - Show error message when string other than "undefined" passed to resourceLimits, rather than 500 error
- [MARATHON-8743](https://jira.mesosphere.com/browse/MARATHON-8743) - improve logic for restarting healthCheckActor if the update stream closes.
=> Bump Marathon to 1.10.17

CHANGES.md, packages/mesos/buildinfo.json, packages/mesos/windows.buildinfo.json
https://github.com/apache/mesos/compare/b84b0a4bd8945b0901214b90b61e6a54fa4b3215...b3b6dbb27a93a9ace4e4d2d1e83b16ea92f1a8e1
=> [2.0] Bump Mesos to nightly 1.9.x b3b6dbb

packages/calico/build, packages/calico/buildinfo.json
- [COPS-6121](https://jira.d2iq.com/browse//COPS-6121) Beta4: Calico networking not working with Docker
- [D2IQ-65076](https://jira.d2iq.com/browse/D2IQ-65076) Bump calico to the latest version before releasing dc/os containing it
=> calico: bump version to v3.14.0

packages/calico/build, packages/calico/buildinfo.json
- [COPS-6121](https://jira.d2iq.com/browse//COPS-6121) Beta4: Calico networking not working with Docker
- [D2IQ-65076](https://jira.d2iq.com/browse/D2IQ-65076) Bump calico to the latest version before releasing dc/os containing it
=> [2.1] bump calico

gen/dcos-config.yaml
This is a part of the windows cleanup that reverts adding 'os:linux` attribute to agents.
- [D2IQ-68446](https://jira.d2iq.com/browse/D2IQ-68446) Remove the os:linux attribute from mesos agents.
=> Removed `os:linux` agent attribute.

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/d4afcd10b6535d91c5a6a544aed2f09af6201b46...1ff2fcd90eabd98786531748869b8596120f7dfe
=> [2.1] Bump Mesos to nightly 1.10.x 1ff2fcd

packages/exhibitor/extra/start_exhibitor.py
Remove newline from ZK log lines. Log lines with stack traces will still have newlines, but this change
allows all other log lines to be forwarded to syslog.
Additional fixes are included:
- double a backslash escape
- fix the GCE format, even though it is not used
- use the same format for AWS and Azure to be more consistent
- [D2IQ-68394](https://jira.d2iq.com/browse/D2IQ-68394) COPS-6128: Zookeeper log messages not being forwarded to syslog
=> Remove newline from ZK log lines

packages/exhibitor/extra/start_exhibitor.py
Back-port of #7295 
Remove newline from ZK log lines. Log lines with stack traces will still have newlines, but this change
allows all other log lines to be forwarded to syslog.
Additional fixes are included:
- double a backslash escape
- fix the GCE format, even though it is not used
- use the same format for AWS and Azure to be more consistent
- [D2IQ-68394](https://jira.d2iq.com/browse/D2IQ-68394) COPS-6128: Zookeeper log messages not being forwarded to syslog
=> [2.1] Remove newline from ZK log lines.

CHANGES.md, packages/exhibitor/extra/start_exhibitor.py
Back-port of #7295 
Remove newline from ZK log lines. Log lines with stack traces will still have newlines, but this change
allows all other log lines to be forwarded to syslog.
Additional fixes are included:
- double a backslash escape
- fix the GCE format, even though it is not used
- use the same format for AWS and Azure to be more consistent
- [D2IQ-68394](https://jira.d2iq.com/browse/D2IQ-68394) COPS-6128: Zookeeper log messages not being forwarded to syslog
=> [1.13] Remove newline from ZK log lines.

CHANGES.md, packages/exhibitor/extra/start_exhibitor.py
Back-port of #7295
Remove newline from ZK log lines. Log lines with stack traces will still have newlines, but this change
allows all other log lines to be forwarded to syslog.
Additional fixes are included:
- double a backslash escape
- fix the GCE format, even though it is not used
- use the same format for AWS and Azure to be more consistent
- [D2IQ-68394](https://jira.d2iq.com/browse/D2IQ-68394) COPS-6128: Zookeeper log messages not being forwarded to syslog
=> [2.0] Remove newline from ZK log lines.

packages/exhibitor/buildinfo.json
This was intended to be the PR that fixed an Exhibitor problem, but it now synchronizes DC/OS `master` with the current Exhibitor `master` so that we're starting with latest versions of both.
Remove `python-requests` dependency, as the code that used it no longer exists in the package: https://github.com/dcos/dcos/commit/c3012f9f331fe06ff1ab038293d4cad2212354f2
=> Use latest Exhibitor master

packages/adminrouter/extra/src/includes/server/common.conf
as during a SOAK update the UI did not consistently report the correct
version of the cluster, we now let the UI know, that it must always
revalidate `dcos-version.json`.
=> add cache-header for dcos-version.json

CHANGES.md, packages/exhibitor/extra/start_exhibitor.py
ZooKeeper 3.4 introduced autopurge to clean up old snapshots and transaction logs. This was also one of the responsibilities handled by Exhibitor. For some time we have had ZK running autopurge every 6 hours, but also Exhibitor calling ZK purge every 5 minutes.
Exhibitor does not pass the configured JNA temporary directory through to its explicit purge, so it causes ZooKeeper to to use `/tmp` for executable files, even if it is mounted `noexec`.
This PR stops the Exhibitor purge, and changes the ZK autopurge to run every hour (the minimum). 
=> Use ZooKeeper autopurge instead of Exhibitor periodic cleanup

CHANGES.md, packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/d4afcd10b6535d91c5a6a544aed2f09af6201b46...365ebb9fb8eebdfaa809dc87a33be22df89a8e85
https://github.com/dcos/dcos-mesos-modules/compare/4ba1e573ec4a80ec1d5514d54d5cc9529e5e1d98...00e67b4e355485effbef07f29d4d8d2fbb019cac
=> [master] Bump Mesos to nightly 1.10.x 365ebb9

gen/dcos-config.yaml
The `os:linux` attribute should not be visible on DC/OS agents. Private agents have had this removed, but public agents still have it.
- [D2IQ-69018](https://jira.d2iq.com/browse/D2IQ-69018) os:linux attribute still exposed on public agents
- [D2IQ-68446](https://jira.d2iq.com/browse/D2IQ-68446) Remove the os:linux attribute from mesos agents
=> [master] Remove `os:linux` attribute from public agents

gen/dcos-config.yaml
Back-port of #7322 to 2.1
The `os:linux` attribute should not be visible on DC/OS agents. Private agents have had this removed, but public agents still have it.
- [D2IQ-69018](https://jira.d2iq.com/browse/D2IQ-69018) os:linux attribute still exposed on public agents
- [D2IQ-68446](https://jira.d2iq.com/browse/D2IQ-68446) Remove the os:linux attribute from mesos agents
=> [2.1] Remove `os:linux` attribute from public agents

CHANGES.md, packages/adminrouter/docker/Dockerfile, packages/adminrouter/extra/src/test-harness/tests/test_master.py
OpenResty 1.15.8.3 fails to pass spaces in the `/services` endpoint. Upgrade to 1.15.8.4 which contains the fix.
- [DCOS_OSS-5967](https://jira.d2iq.com/browse/DCOS_OSS-5967) Upgrade OpenResty in AdminRouter to 1.15.8.4 version
- [COPS-6166](https://jira.mesosphere.com/browse/COPS-6166) Unable to rename/delete folders in Data Science Engine UI
=> [2.0] Upgrade OpenResty to fix spaces in URLs

CHANGES.md, packages/adminrouter/docker/Dockerfile, packages/adminrouter/extra/src/test-harness/tests/test_master.py
OpenResty 1.15.8.3 fails to pass spaces in the `/services` endpoint. Upgrade to 1.15.8.4 which contains the fix.
- [DCOS_OSS-5967](https://jira.d2iq.com/browse/DCOS_OSS-5967) Upgrade OpenResty in AdminRouter to 1.15.8.4 version
- [COPS-6166](https://jira.mesosphere.com/browse/COPS-6166) Unable to rename/delete folders in Data Science Engine UI
=> [2.1] Upgrade OpenResty to fix spaces in URLs

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/3d68993c8743231b6067738050786e750edda9b1...a679eb4bc35bd2d7c4cffdd9440ab301d8fc8986
=> [master] Bump Mesos to nightly master a679eb4

gen/build_deploy/bash/dcos_generate_config.sh.in
The installer maps port 9000 (or $PORT) on the host to the container, where the GUI installer used to listen before DC/OS 1.12.
The port is now unused, and can occasionally cause problems since, even though unused, the port must be available on the bootstrap host.
- [D2IQ-66022](https://jira.d2iq.com/browse/D2IQ-66022) test-e2e/test_external_cert.py: bind: address already in use
- [D2IQ-67994](https://jira.d2iq.com/browse/D2IQ-67994) TestCertUpdate is flaky
- [D2IQ-61304](https://jira.d2iq.com/browse/D2IQ-61304) docker driver failed programming external connectivity on endpoint: address already in use
- [D2IQ-7844](https://jira.d2iq.com/browse/D2IQ-7844) CLI Installer binds on :9000?
=> Remove vestigial GUI installer port from installer

gen/build_deploy/bash/dcos_generate_config.sh.in
Back-port of #7394 
The installer maps port 9000 (or $PORT) on the host to the container, where the GUI installer used to listen before DC/OS 1.12.
The port is now unused, and can occasionally cause problems since, even though unused, the port must be available on the bootstrap host.
- [D2IQ-66022](https://jira.d2iq.com/browse/D2IQ-66022) test-e2e/test_external_cert.py: bind: address already in use
- [D2IQ-67994](https://jira.d2iq.com/browse/D2IQ-67994) TestCertUpdate is flaky
- [D2IQ-61304](https://jira.d2iq.com/browse/D2IQ-61304) docker driver failed programming external connectivity on endpoint: address already in use
- [D2IQ-7844](https://jira.d2iq.com/browse/D2IQ-7844) CLI Installer binds on :9000?
=> [2.1] Remove vestigial GUI installer port from installer

gen/build_deploy/bash/dcos_generate_config.sh.in
Back-port of #7394 
The installer maps port 9000 (or $PORT) on the host to the container, where the GUI installer used to listen before DC/OS 1.12.
The port is now unused, and can occasionally cause problems since, even though unused, the port must be available on the bootstrap host.
- [D2IQ-66022](https://jira.d2iq.com/browse/D2IQ-66022) test-e2e/test_external_cert.py: bind: address already in use
- [D2IQ-67994](https://jira.d2iq.com/browse/D2IQ-67994) TestCertUpdate is flaky
- [D2IQ-61304](https://jira.d2iq.com/browse/D2IQ-61304) docker driver failed programming external connectivity on endpoint: address already in use
- [D2IQ-7844](https://jira.d2iq.com/browse/D2IQ-7844) CLI Installer binds on :9000?
=> [2.0] Remove vestigial GUI installer port from installer

CHANGES.md, packages/metronome/buildinfo.json
Bump Metronome to 0.6.48
- [DCOS_OSS-5965](https://jira.mesosphere.com/browse/DCOS_OSS-5965) - Metronome becomes unresponsive after launching due to a race between JobRunExecutorActor instance loading and InstanceTracker responding
=> 2.1: Bump Metronome to 0.6.48

packages/bootstrap/extra/dcos_internal_utils/cli.py, packages/bootstrap/extra/dcos_internal_utils/exhibitor.py, packages/bootstrap/extra/dcos_internal_utils/utils.py, packages/bootstrap/extra/setup.py, test-e2e/test_e2e_module.py, test-e2e/test_etcd_backup.py, test-e2e/test_exhibitor_quorum.py, test-e2e/test_groups.yaml
This change allows service bootstrap to proceed without all ZooKeeper nodes available, where there is no chance of ZooKeeper being started in standalone mode (in static clusters).
- [D2IQ-4248](https://jira.d2iq.com/browse/D2IQ-4248) Master node should be able to rejoin the cluster after failure/restart when another master is offline or being upgraded
- [COPS-1754](https://jira.d2iq.com/browse/COPS-1754) Master node should be able to rejoin the cluster after failure/restart when another master is offline or being upgraded
=> Static clusters only require ZooKeeper quorum for bootstrap to proceed

CHANGES.md, packages/bootstrap/buildinfo.json, packages/bootstrap/extra/dcos_internal_utils/bootstrap.py, packages/bootstrap/extra/dcos_internal_utils/cli.py, packages/bootstrap/extra/dcos_internal_utils/exhibitor.py, packages/bootstrap/extra/dcos_internal_utils/utils.py, packages/bootstrap/extra/pytest.ini, packages/bootstrap/extra/setup.py, packages/bootstrap/extra/tests/test_bootstrap.py, packages/bootstrap/extra/tests/test_cli.py, test-e2e/test_e2e_module.py, test-e2e/test_exhibitor_quorum.py, test-e2e/test_groups.yaml, tox.ini
Back-port of #7427
This change allows service bootstrap to proceed without all ZooKeeper nodes available, where there is no chance of ZooKeeper being started in standalone mode (in static clusters).
- [D2IQ-4248](https://jira.d2iq.com/browse/D2IQ-4248) Master node should be able to rejoin the cluster after failure/restart when another master is offline or being upgraded
- [COPS-1754](https://jira.d2iq.com/browse/COPS-1754) Master node should be able to rejoin the cluster after failure/restart when another master is offline or being upgraded
=> [2.0] Static clusters only require ZooKeeper quorum for bootstrap to proceed

CHANGES.md, packages/bootstrap/extra/dcos_internal_utils/cli.py, packages/bootstrap/extra/dcos_internal_utils/exhibitor.py, packages/bootstrap/extra/dcos_internal_utils/utils.py, packages/bootstrap/extra/setup.py, test-e2e/test_e2e_module.py, test-e2e/test_etcd_backup.py, test-e2e/test_exhibitor_quorum.py, test-e2e/test_groups.yaml
Back-port of #7427
This change allows service bootstrap to proceed without all ZooKeeper nodes available, where there is no chance of ZooKeeper being started in standalone mode (in static clusters).
- [D2IQ-4248](https://jira.d2iq.com/browse/D2IQ-4248) Master node should be able to rejoin the cluster after failure/restart when another master is offline or being upgraded
- [COPS-1754](https://jira.d2iq.com/browse/COPS-1754) Master node should be able to rejoin the cluster after failure/restart when another master is offline or being upgraded
=> [2.1] Static clusters only require ZooKeeper quorum for bootstrap to proceed

packages/mesos-modules/buildinfo.json
This switches dcos-mesos-modules package to using 2.1 dcos-mesos-modules branch.
SHA is not changed.
- [D2IQ-68266](https://jira.d2iq.com/browse/D2IQ-68266) Make DCOS 2.1 branch use corresponding branches of mesos/modules.
=> Switched dcos-mesos-modules to 2.1 branch

CHANGES.md, packages/bootstrap/extra/dcos_internal_utils/cli.py, packages/bootstrap/extra/dcos_internal_utils/exhibitor.py, packages/bootstrap/extra/dcos_internal_utils/utils.py, packages/bootstrap/extra/setup.py, test-e2e/test_e2e_module.py, test-e2e/test_exhibitor_quorum.py, test-e2e/test_groups.yaml
Back-port of #7427
This change allows service bootstrap to proceed without all ZooKeeper nodes available, where there is no chance of ZooKeeper being started in standalone mode (in static clusters).
- [D2IQ-4248](https://jira.d2iq.com/browse/D2IQ-4248) Master node should be able to rejoin the cluster after failure/restart when another master is offline or being upgraded
- [COPS-1754](https://jira.d2iq.com/browse/COPS-1754) Master node should be able to rejoin the cluster after failure/restart when another master is offline or being upgraded
=> [1.13] Static clusters only require ZooKeeper quorum for bootstrap to proceed

test-e2e/conditional.py, test-e2e/pytest.ini, test-e2e/requirements.txt, test-e2e/test_e2e_module.py, test-e2e/test_exhibitor_quorum.py
Add a decorator to skip e2e tests if only safe files are modified. Only one test is decorated, until we've seen that it works for PR's, trains, and masters (it should only skip in the non-train PR).
In e2e test build log
```
[09:50:20] :	 [Step 2/3] ----------------------------- live log collection ------------------------------
[09:50:20] :	 [Step 2/3] conditional.py              31 INFO     INSTALLER_URL=https://downloads.dcos.io/dcos/testing/pull/7445/dcos_generate_config.sh
[09:50:21] :	 [Step 2/3] conditional.py              52 INFO     Remaining requests: 59
[09:50:21] :	 [Step 2/3] conditional.py              84 INFO     Merging mesosphere:jongiddy/D2IQ-70118-e2e-change-decorator into dcos:master
[09:50:21] :	 [Step 2/3] conditional.py              93 INFO     Modified files: …
```
=> Add decorator to skip e2e tests

CHANGES.md, packages/etcd/buildinfo.json
This commit bumps the etcd version to 3.4.9  (back-ported to 2.1)
- [COPS-6341](https://jira.d2iq.com/browse/COPS-6341) Etcd need to be upgraded to 3.4.9
(None)
=> [Backport-2.1] Bumping the etcd version to v3.4.9

CHANGES.md, packages/exhibitor/extra/start_exhibitor.py
Back-port of #7314
ZooKeeper 3.4 introduced autopurge to clean up old snapshots and transaction logs. This was also one of the responsibilities handled by Exhibitor. For some time we have had ZK running autopurge every 6 hours, but also Exhibitor calling ZK purge every 5 minutes.
Exhibitor does not pass the configured JNA temporary directory through to its explicit purge, so it causes ZooKeeper to to use `/tmp` for executable files, even if it is mounted `noexec`.
This PR stops the Exhibitor purge, and changes the ZK autopurge to run every hour (the minimum). 
- [D2IQ-68868](https://jira.d2iq.com/browse/D2IQ-68868) Back-port dropping Exhibitor purge
=> [1.13] Use ZooKeeper autopurge instead of Exhibitor periodic cleanup

CHANGES.md, packages/exhibitor/extra/start_exhibitor.py
Back-port of #7314
ZooKeeper 3.4 introduced autopurge to clean up old snapshots and transaction logs. This was also one of the responsibilities handled by Exhibitor. For some time we have had ZK running autopurge every 6 hours, but also Exhibitor calling ZK purge every 5 minutes.
Exhibitor does not pass the configured JNA temporary directory through to its explicit purge, so it causes ZooKeeper to to use `/tmp` for executable files, even if it is mounted `noexec`.
This PR stops the Exhibitor purge, and changes the ZK autopurge to run every hour (the minimum). 
- [D2IQ-68868](https://jira.d2iq.com/browse/D2IQ-68868) Back-port dropping Exhibitor purge
=> [2.0] Use ZooKeeper autopurge instead of Exhibitor periodic cleanup

packages/telegraf/extra/dcos-telegraf.service
Currently Mesos (and other components) does network check before starting bootstrap.
Let's introduce the same check to start telegraph at the same time as Mesos and
do not allow any retries or timeouts in bootstrap phase.
```python
30.333688 [INFO] Clearing proxy environment variables
30.334119 [INFO] Setting ENABLE_CHECK_TIME to true
30.337367 Checking whether time is synchronized using the kernel adjtimex API.
30.337512 Time can be synchronized via most popular mechanisms (ntpd, chrony, systemd-timesyncd, etc.)
30.337662 Time is in sync!
30.338111 [INFO] No zk.pid last mtime found at /var/lib/dcos/bootstrap/exhibitor_pid_stat
30.338261 [INFO] Shortcut failed, waiting for exhibitor to bring up zookeeper and stabilize
30.338411 [INFO] master_count file doesn't exist, not waiting
30.338567 …
```
=> Make telegraf wait for network

CHANGES.md, packages/etcd/buildinfo.json
This commit bumps the etcd version to 3.4.9 
- [COPS-6341](https://jira.d2iq.com/browse/COPS-6341) Etcd need to be upgraded to 3.4.9
(None)
=> Bumping the etcd version to v3.4.9

CHANGES.md, packages/exhibitor/extra/start_exhibitor.py
Back-port of #7314
ZooKeeper 3.4 introduced autopurge to clean up old snapshots and transaction logs. This was also one of the responsibilities handled by Exhibitor. For some time we have had ZK running autopurge every 6 hours, but also Exhibitor calling ZK purge every 5 minutes.
Exhibitor does not pass the configured JNA temporary directory through to its explicit purge, so it causes ZooKeeper to to use `/tmp` for executable files, even if it is mounted `noexec`.
This PR stops the Exhibitor purge, and changes the ZK autopurge to run every hour (the minimum). 
- [D2IQ-68868](https://jira.d2iq.com/browse/D2IQ-68868) Back-port dropping Exhibitor purge
=> [2.1] Use ZooKeeper autopurge instead of Exhibitor periodic cleanup

test-e2e/test_etcd_backup.py
Currently, we don't capture the stdout / stderr of the Docker command used by the client put command in `test_snapshot_backup_and_restore`. This makes it very difficult to debug failures here.
- [D2IQ-70431](https://jira.d2iq.com/browse/D2IQ-70431) test_snapshot_backup_and_restore etcd_client.put(test_key, test_val) CalledProcessError
=> Add logging to etcd put command in e2e tests

setup.py
Just released version of pytest 6.0.0 causes tox to failure.
This has been resolved by pytest https://github.com/pytest-dev/pytest/pull/7565, however, as we wait for update, we could approach the problem at our end by pinning pytest to previous stable version.
- [D2IQ-70503](https://jira.d2iq.com/browse/D2IQ-70503) Pin pytest to fix tox failures in DC/OS
=> Fix tox failure by pinning pytest dependency.

CHANGES.md, packages/bouncer-deps/buildinfo.json, packages/dcos-integration-test/extra/get_test_group.py, packages/dcos-integration-test/extra/test_meta.py, packages/dcos-integration-test/extra/test_misc.py, packages/python-certifi/buildinfo.json, packages/python-cryptography/buildinfo.json, packages/python-future/buildinfo.json, packages/python-idna/buildinfo.json, packages/python-isodate/buildinfo.json, packages/python-jose/buildinfo.json, packages/python-jwt/buildinfo.json, packages/python-markupsafe/buildinfo.json, packages/python-passlib/buildinfo.json, packages/python-pycparser/buildinfo.json, packages/python-pyyaml/buildinfo.json, packages/python-requests/buildinfo.json, packages/six/buildinfo.json, setup.py
Update Bouncer dependencies that are provided by DC/OS. This follows on from https://github.com/dcos/dcos/pull/7499 which only changes the dependencies in the Bouncer repo (e.g. used for testing).
- [D2IQ-54115](https://jira.d2iq.com/browse/D2IQ-54115) Bump Bouncer dependencies conservatively
- [D2IQ-62221](https://jira.d2iq.com/browse/D2IQ-62221) Update cockroachdb Python package to 0.3.2+
=> Bump Bouncer dependencies in DC/OS

CHANGES.md, packages/bouncer-deps/buildinfo.json
Upgrade CockroachDB and other dependencies for Bouncer. This back-port is more limited than the changes to `master` in #7507.
- [D2IQ-62221](https://jira.d2iq.com/browse/D2IQ-62221) Update cockroachdb Python package to 0.3.2+
=> [2.1] Update Bouncer dependencies

CHANGES.md, packages/bouncer-deps/buildinfo.json
Upgrade CockroachDB and other dependencies for Bouncer. This back-port is more limited than the changes to `master` in #7507.
- [D2IQ-62221](https://jira.d2iq.com/browse/D2IQ-62221) Update cockroachdb Python package to 0.3.2+
=>  [2.0] Update Bouncer dependencies

CHANGES.md, packages/bouncer-deps/buildinfo.json
Upgrade CockroachDB and other dependencies for Bouncer. This back-port is more limited than the changes to `master` in #7507.
- [D2IQ-62221](https://jira.d2iq.com/browse/D2IQ-62221) Update cockroachdb Python package to 0.3.2+
=> [1.13] Update Bouncer dependencies

release/storage/aws.py
Fix D2IQ-70676 - AWS S3 Copy with (AccessDenied) when calling the Copy Object operation
Use ACL for S3 Bucket Upload and Copy Operation
This ACL is useful if the give permissions to S3 operations via ACL. The
x-amz- header is sent by adding this ACL to boto3 library.
There are two separate calls, upload and copy, both need to send the
ACL as indicated in the AWS Documentation.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#object
When copying an object, you can preserve all metadata (default) or
specify new metadata. However, the ACL is not preserved and is set to
private for the user making the request. To override the default ACL
setting, specify a new ACL when generating a copy request. For more
information, see Using ACLs .
- D2IQ-70676 - AWS S3 …
=>  Use ACL for S3 Bucket Upload and Copy Operation

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/a679eb4bc35bd2d7c4cffdd9440ab301d8fc8986...c78dc333fc893a43d40dc33299a61987198a6ea9
=> [master] Bump Mesos to nightly master c78dc33

CHANGES.md, packages/calico/extra/create-calico-docker-network.py, packages/calico/extra/dcos-calico-libnetwork-plugin.service, test-e2e/test_calico_networking.py
The Calico startup is relatively new, and we've seen some problems with the way timeouts are set. This PR updates the timeouts to make more sense. Also, the setup changes a Docker config file, which interferes with existing config managers. Although we can't "fix" that, we can keep the JSON in the original order to make the structure more predictable. This also ensures that updates to the network setup in future versions will be reflected in the Docker configuration.
This change was developed as WIP in #7521
- [D2IQ-70674](https://jira.d2iq.com/browse/D2IQ-70674) packages/calico/extra/dcos-calico-libnetwork-plugin.service problems.
=> Minimize Docker daemon configuration changes, set Calico timeouts more consistently

packages/java/build, packages/java/buildinfo.json
Update JDK to most recent 8u265b01. This includes a fix for large open file limits: https://bugs.openjdk.java.net/browse/JDK-8236662
- [D2IQ-70809](https://jira.d2iq.com/browse/D2IQ-70809) Restrict systemd file descriptors for java.
- [COPS-6422](https://jira.d2iq.com/browse/COPS-6422) DC/OS installation crashes on flatcar linux due to LimitNoFile
=> Upgrade to JDK 8u265b01

build_local.sh, build_teamcity
The DC/OS build step in CI gets allocated to some nodes with Python 3.5 and some with Python 3.6. Modify the build scripts to use any Python 3 for the build, not just 3.5
This was added to #7534 (2.1) and #7535 (2.0) in order to get them to build.
=> Use any Python 3 in build scripts

CHANGES.md, build_local.sh, build_teamcity, packages/java/build, packages/java/buildinfo.json
Back-port of #7527 
Update JDK to most recent 8u265b01. This includes a fix for large open file limits: https://bugs.openjdk.java.net/browse/JDK-8236662
- [D2IQ-70809](https://jira.d2iq.com/browse/D2IQ-70809) Restrict systemd file descriptors for java.
- [COPS-6422](https://jira.d2iq.com/browse/COPS-6422) DC/OS installation crashes on flatcar linux due to LimitNoFile
=> [2.1] Upgrade to JDK 8u265b01

CHANGES.md, build_local.sh, build_teamcity, packages/java/build, packages/java/buildinfo.json
Back-port of #7527 
Update JDK to most recent 8u265b01. This includes a fix for large open file limits: https://bugs.openjdk.java.net/browse/JDK-8236662
- [D2IQ-70809](https://jira.d2iq.com/browse/D2IQ-70809) Restrict systemd file descriptors for java.
- [COPS-6422](https://jira.d2iq.com/browse/COPS-6422) DC/OS installation crashes on flatcar linux due to LimitNoFile
=> [2.0] Upgrade to JDK 8u265b01

build_local.sh, build_teamcity
The DC/OS build step in CI gets allocated to some nodes with Python 3.5 and some with Python 3.6. Modify the build scripts to use any Python 3 for the build, not just 3.5
This was added to #7534 (2.1) and #7535 (2.0) in order to get them to build.
=> [1.13] Use any Python 3 in build scripts

CHANGES.md, packages/calico/extra/create-calico-docker-network.py, packages/calico/extra/dcos-calico-libnetwork-plugin.service, test-e2e/test_calico_networking.py
Back-port of #7526 
The Calico startup is relatively new, and we've seen some problems with the way timeouts are set. This PR updates the timeouts to make more sense. Also, the setup changes a Docker config file, which interferes with existing config managers. Although we can't "fix" that, we can keep the JSON in the original order to make the structure more predictable. This also ensures that updates to the network setup in future versions will be reflected in the Docker configuration.
- [D2IQ-70674](https://jira.d2iq.com/browse/D2IQ-70674) packages/calico/extra/dcos-calico-libnetwork-plugin.service problems.
=> [2.1] Minimize Docker daemon configuration changes, set Calico timeouts more consistently

CHANGES.md, packages/marathon/buildinfo.json
- [MARATHON-8758](https://jira.mesosphere.com/browse/MARATHON-8758) Fix a regression where Marathon would sometimes fail to replace lost unreachable tasks
=> Bump Marathon to 1.10.26

packages/python-requests/buildinfo.json, setup.py
- [D2IQ-70906](https://jira.d2iq.com/browse/D2IQ-70906) DC/OS build fails with a moving urllib3 dependency
=> Pin urllib3 to 1.25.10 as responses 0.10.16 requires urllib3>=1.25.10

CHANGES.md, packages/marathon/buildinfo.json
- [MARATHON-8758](https://jira.mesosphere.com/browse/MARATHON-8758) Fix a regression where Marathon would sometimes fail to replace lost unreachable tasks 
- [MARATHON-8743](https://jira.mesosphere.com/browse/MARATHON-8743) Improved the reliability of error handling for health check handling
- [COPS-6329](https://jira.d2iq.com/browse/COPS-6329) MoM not scheduling new instances of app unless manually triggered
=> Bump Marathon to 1.8.244

CHANGES.md, packages/marathon/buildinfo.json
Bump Marathon to 1.9.140
- [MARATHON-8758](https://jira.mesosphere.com/browse/MARATHON-8758) Fix a regression where Marathon would sometimes fail to replace lost unreachable tasks 
- [MARATHON-8743](https://jira.mesosphere.com/browse/MARATHON-8743) Improved the reliability of error handling for health check handling
- [MARATHON-8741](https://jira.d2iq.com/browse/MARATHON-8741) Address an issue where Marathon could, in rare cases, become unresponsive after leader election
- [COPS-6329](https://jira.d2iq.com/browse/COPS-6329) MoM not scheduling new instances of app unless manually triggered
=> Bump Marathon to 1.9.140

CHANGES.md, gen/calc.py, gen/tests/test_config.py
Setting the spartan addresses (`198.51.100.1-3`) in the resolvers list
will lead to resolution failures as spartan will end up querying itself
in an infinate loop. Check that they are not in the list at install
time.
- [COPS-4616](https://jira.d2iq.com/browse/COPS-4616) Installer should make sure Spartan IP's are not set as the 'resolvers'
=> gen: check spartan addresses are not in resolvers

packages/mesos/extra/dcos-mesos-slave-public.service, packages/mesos/extra/dcos-mesos-slave.service
Mesos Agent tasks requires telegraf so Mesos should wait for telegraf
socket to appear.
Refs:  https://github.com/dcos/dcos/pull/7473#discussion_r468721781
Fixes: https://jira.d2iq.com/browse/COPS-6355
=> Make Mesos Agent waits for Telegraf

packages/adminrouter/docker/Dockerfile, tox.ini
Pin `setuptools<50` as changes in new version break CI
- [D2IQ-71457](https://jira.mesosphere.com/browse/D2IQ-71457) continuous-integration/jenkins SystemError: Parent module setuptools
=> For Admin Router pin `setuptools<50`

packages/mesos/buildinfo.json
Bump Mesos for the CSI external volume support
- [D2IQ-71267](https://jira.d2iq.com/browse/D2IQ-71267) Bump Mesos in DC/OS for the statically provisioned CSI volumes support
=> Bump Mesos for the CSI external volume support

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/f8b8f1e9c0fbf0a3ee769eebcebf0b4e98e0bfa6...d160015e544082ff310a7e4d2e94e3c4eae9499b
=> [1.13] Bump Mesos to nightly 1.8.x d160015

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/8683463a9fade9d86d77c0cea8336089fa2c10ca...3ca3879d52ea0f9bff05443d331d63105b2cc4db
=> [2.1] Bump Mesos to nightly 1.10.x 3ca3879

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/802a50f4902f1f5ca3829dca4a472d8a582f7b9b...e98ced1e93751b78c3248221115fcf4db8a39b29
=> [2.0] Bump Mesos to nightly 1.9.x e98ced1

gen/calc.py, gen/dcos-config.yaml
Enable `volume/csi` isolator by default in DC/OS.
- [D2IQ-71295](https://jira.d2iq.com/browse/D2IQ-71295) Enable the `volume/csi` isolator by default in DC/OS
=> Enable `volume/csi` isolator by default in DC/OS

test-e2e/test_calico_networking.py
Follow up to https://github.com/dcos/dcos/pull/7575 to restrict the test running to only when calico files change.
- Same as #7575
=> e2e: only run calico disabled when calico modified

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/a16f3439dca13982bb4a2b9190c24aaf4eb73b0e...2bf7f5d8dcb359845a663a011a941809ffc2366d
=> [master] Bump Mesos to nightly master 2bf7f5d

packages/calico/extra/create-calico-docker-network.py, packages/calico/extra/dcos-calico-libnetwork-plugin.service, test-e2e/test_external_calicoctl.py
Changes to Calico configuration to ensure that bootstrap files are run before Docker libnetwork plugin, and that it is reset when certificates are updated.
- [D2IQ-71077](https://jira.d2iq.com/browse/D2IQ-71077) Fix Calico / etcd certificate propagation
=> Run `bootstrap calico-felix` before `libnetwork-plugin`

config/dcos-release.config.yaml
-https://jira.d2iq.com/browse/D2IQ-71632 indicates the credentials of Azure have changed.
I also realized that we don't use Azure URLs for releases.   So, we either fix with updated credentials or if this PR succeeds we can remove storing of artifacts in the azure cloud.
=> Remove Storing artifacts in Azure Cloud.

CHANGES.md, gen/build_deploy/bash.py
Turn on `enable_docker_gc` for on-prem by default.
- [D2IQ-71626](https://jira.d2iq.com/browse/D2IQ-71626) Turn on enable_docker_gc by default for all types of DC/OS installations
=> Turn on `enable_docker_gc` for on-prem by default

packages/bootstrap/extra/dcos_internal_utils/cli.py, packages/calico/extra/create-calico-docker-network.py, packages/calico/extra/dcos-calico-libnetwork-plugin.service
To avoid conflicts in Enterprise bootstrap steps, run a separate bootstrap for the Calico libnetwork bootstrap process.
This is used to generate different client certificates for libnetwork, and avoid errors during startup. If any libnetwork config changes, reload or restart Docker to ensure it takes effect.
- [D2IQ-71567](https://jira.d2iq.com/browse/D2IQ-71567) TestReplaceCert test_ee_systemd_units_are_healthy assert unhealthy_nodes == 0 fails
=> Run a separate bootstrap for Calico libnetwork

config/dcos-release.config.yaml, packages/bootstrap/extra/dcos_internal_utils/cli.py, packages/calico/extra/create-calico-docker-network.py, packages/calico/extra/dcos-calico-libnetwork-plugin.service
Back-port of #7581, #7617 (to resolve a flake introduced by #7581), and #7613 (to fix CI)
Changes to Calico configuration to ensure that bootstrap files are run before Docker libnetwork plugin, and that it is reset when certificates are updated.
- [D2IQ-71077](https://jira.d2iq.com/browse/D2IQ-71077) Fix Calico / etcd certificate propagation
- [D2IQ-71567](https://jira.d2iq.com/browse/D2IQ-71567) TestReplaceCert test_ee_systemd_units_are_healthy assert unhealthy_nodes == 0 fails
- [D2IQ-71632](https://jira.d2iq.com/browse/D2IQ-71632) binascii.Error: Incorrect padding during DC/OS build
=> [2.1] Run `bootstrap calico-felix` before `libnetwork-plugin`

config/dcos-release.config.yaml, packages/dcos-integration-test/extra/test_metrics.py
Display any difference between the expected and retrieved metrics, to help diagnose flaky test
- [D2IQ-68640](https://jira.d2iq.com/browse/D2IQ-68640) test_metrics.test_metrics_agent_statsd Expected statsd metrics not found
- [D2IQ-71632](https://jira.d2iq.com/browse/D2IQ-71632) binascii.Error: Incorrect padding during DC/OS build
=> [2.0] Print more info on test_metrics failure

CHANGES.md, packages/marathon/buildinfo.json
Include Marathon 1.11 (snapshot version) with support for CSI
- [MARATHON-8765](https://jira.d2iq.com/browse/MARATHON-8765) CSI Support in Marathon
=> Bump Marathon to 1.11 snapshot build

CHANGES.md, pkgpanda/__init__.py
Currently we stop servies one by one. This may lead to a situation when we stop service before we stop it's socket activator. So if any packet gets sent to that socket, the service will be activated. To prevent this we need to stop all services in a single command.
- [COPS-6512](https://jira.d2iq.com/browse/COPS-6512) [DC/OS] [1.13.9]dcos-telegraf.socket  down after a patch
=> Stop all services at once during upgrade

packages/mesos-modules/buildinfo.json
Bump mesos-modules to master edc45dc57664ba87d15eef44f35288a4837d3799.
- [D2IQ-71789](https://jira.d2iq.com/browse/D2IQ-71789) Mesos module in DC/OS failed to build
=> Bump mesos-modules to master edc45dc57664ba87d15eef44f35288a4837d3799.

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/2bf7f5d8dcb359845a663a011a941809ffc2366d...c28fd3a93e0d9d9a868aec2380abd1dd338304ef
=> [master] Bump Mesos to nightly master c28fd3a

CHANGES.md, packages/bouncer/extra/dcos-bouncer.service, packages/cockroach/extra/dcos-cockroach.service, packages/cockroach/extra/dcos-cockroachdb-config-change.timer
This change prevents a timeout in the CockroachDB systemd ExecStartPost commands from terminating CockroachDB.
This is a simpler version of #7648 - not as complete a solution, but fewer changes to the existing release.
- [D2IQ-69871](https://jira.d2iq.com/browse/D2IQ-69871) Set cockroach change config to timeout if connection to CDB cannot be made
- [D2IQ-62292](https://jira.d2iq.com/browse/D2IQ-62292) Remove possibility of timeouts in systemd ExecStartPost
- [D2IQ-51276](https://jira.d2iq.com/browse/D2IQ-51276) Consoldiate CA bootstrap? (CA bootstrap does not retry or fail on Docker reload failure)
- https://jira.d2iq.com/browse/COPS-5601
- https://jira.d2iq.com/browse/COPS-5795
- https://jira.d2iq.com/browse/COPS-6063
=> [2.1] Timeout CockroachDB configuration in post-start step

packages/exhibitor/extra/dcos-exhibitor.service
The original test for ZooKeeper status uses `lsof`. The `lsof` command is not available on all systems. Use the `curl` command that is installed by DC/OS instead.
- [D2IQ-62292](https://jira.d2iq.com/browse/D2IQ-62292) Remove possibility of timeouts in systemd ExecStartPost
=> Check ZooKeeper status using curl

CHANGES.md, gen/dcos-config.yaml, packages/dcos-net/extra/dcos-net-setup.py, packages/dcos-net/extra/dcos-net.service
Adds an ignore device file for NetworkManager similar to how we do for systemd-networkd. It appears that in RHEL 7.8 sometimes NetworkManager starts after dcos-net and that ends up wiping out the 2nd and 3rd ip (198.51.100.2-3) on the spartan device. 
- [COPS-6519](https://jira.d2iq.com/browse/COPS-6519) dcos-net not always able to set all Spartan IP addresses after node reboot
=> NetworkManager ignores

packages/marathon/buildinfo.json
This has equivalent functionality to 1.11.12-30444c7d2 but is
built from the Marathon master instead of a feature branch
=> Bump Marathon to 1.11.2 (non-snapshot build)

CHANGES.md, packages/marathon/buildinfo.json
Bump Marathon to 1.8.245
* https://jira.d2iq.com/browse/MARATHON-8762
* https://jira.d2iq.com/browse/COPS-5897
=> [1.13] Bump Marathon to 1.8.245

packages/marathon/buildinfo.json
Adds CSI Validations
* [MARATHON-8767](https://jira.d2iq.com/browse/MARATHON-8767)
=> Bump Marathon to 1.11.3

tox.ini
Pin mypy for integration tests, to prevent stricter checks failing after mypy 0.790 was released. Also run other tests with any Python 3, not just unsupported 3.5
- [D2IQ-72431](https://jira.d2iq.com/browse/D2IQ-72431) mypy failure following upgrade
=> Pin mypy for integration tests

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/c28fd3a93e0d9d9a868aec2380abd1dd338304ef...d4678d33b223fec5d48007f8246f1ed1cda5e90d
=> [master] Bump Mesos to nightly master d4678d3

packages/exhibitor/buildinfo.json
Use cached version of ZooKeeper, since original site has stopped hosting
- [D2IQ-72462](https://jira.d2iq.com/browse/D2IQ-72462) Build DC/OS Uncached Master Failing on missing Zookeeper download
=> Use cached repo for ZooKeeper

packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json
This changes ref_origins (no SHA bump!) of Mesos and modules in preparation for DCOS 2.2 branchoff.
- [D2IQ-72537](https://jira.d2iq.com/browse/D2IQ-72537) Mesos and modules branchoff in DCOS 2.2
=> Switched ref_origin for Mesos to 1.11.x and for mesos-modules to 2.2.

CHANGES.md, packages/marathon/buildinfo.json
- [MARATHON-8769](https://jira.d2iq.com/browse/MARATHON-8769) enforceRole property shows for sub-groups, creating confusion.
- [MARATHON-8773](https://jira.d2iq.com/browse/MARATHON-8773) - ResourceLimits are not read from persistence
- [MARATHON-8770](https://jira.d2iq.com/browse/MARATHON-8770) - enforceRole behavior and setting ignored for PUT /v2/groups
- [COPS-6533](https://jira.d2iq.com/browse/COPS-6533)
- [COPS-6590](https://jira.d2iq.com/browse/COPS-6590)
=> Bump Marathon to 1.10.32

CHANGES.md, packages/marathon/buildinfo.json
- [COPS-6533](https://jira.d2iq.com/browse/COPS-6533)
- [COPS-6529](https://jira.d2iq.com/browse/COPS-6529)
- [MARATHON-8769](https://jira.d2iq.com/browse/MARATHON-8769) - enforceRole property shows for sub-groups, creating confusion
- [MARATHON-8770](https://jira.d2iq.com/browse/MARATHON-8770) - enforceRole behavior and setting ignored for PUT /v2/groups
=> Bump Marathon to 1.9.143

packages/installer.treeinfo.json, packages/treeinfo.json, test-e2e/conditional.py, test-e2e/test_adminrouter_grpc.py, test-e2e/test_calico_networking.py, test-e2e/test_etcd_backup.py, test-e2e/test_service_account.py, test-e2e/test_zookeeper_backup.py, test-e2e/test_zookeeper_quorum.py
The e2e tests skipping generally identifies two sets of files:
1. files that do not contribute to the delivered artifact of DC/OS (e.g. Markdown files);
2. files that, despite contributing to the artifact, are not expected to affect the outcome of the specific e2e test.
The first subset is generally those files identified in the `E2E_SAFE_DEFAULT` variable. If a PR only changes these files, there is practically no chance that the e2e test outcomes should be affected.
This PR allows trains to skip e2e testing when only files in `E2E_SAFE_DEFAULT` are changed.
As a minor addition, I removed some defunct packages from `treeinfo.json`. This allowed me to check that the change to the `packages/**` patterns do run the tests when `treeinfo.json` changes.
- …
=> Skip e2e tests on trains for safe subset of changes

packages/adminrouter/docker/requirements-tests.txt, packages/exhibitor/buildinfo.json, packages/python-requests/buildinfo.json, setup.py
Pin the version of `requests` and `urllib` to allow CI to pass. Get ZooKeeper from our own repo
=> [1.13] Update urllib to fix build problem

CHANGES.md, packages/mesos/buildinfo.json
https://github.com/apache/mesos/compare/d4678d33b223fec5d48007f8246f1ed1cda5e90d...cb6cfe9b122d1b60a8264b28b6abb38a3c8417b4
=> [2.2] Bump Mesos to nightly 1.11.x cb6cfe9

tox.ini
Don't require Python 3.5 for tox integration test collection. Use whichever Python 3 is available.
This relatively minor change was actually made to test whether tox is failing on master in CI (it's not). However, it is a useful change and as long as it tests OK, we should add it.
=> Use any Python 3 for integration test collection

packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json
This changes ref_origins of Mesos and modules back to master after the DCOS 2.2 branchoff.
- [/D2IQ-72537](https://jira.d2iq.com/browse/D2IQ-72537) Mesos and modules branchoff in DCOS 2.2.
=> Switched ref_origin for Mesos and mesos-modules back to master.

packages/dcos-integration-test/extra/test_networking.py
D2IQ-43857 is mentioning that this feature doesn't work at all. The truth is that only the first call fails. Doing a second call to the same address works fine. With that in mind this PR adds retry logic to `test_dcos_cni_l4lb` so this test no longer fails on centos >= 7.6
- [D2IQ-43857](https://jira.d2iq.com/browse/D2IQ-43857) test_dcos_cni_l4lb fails for 1.12.0-rc3 & 1.11.6 on RHEL 7.5
=> Use retry on test_dcos_cni_l4lb as from centos 7.6 first call will fail

packages/calico/build
Fixes the repo in the "build" container to the new centos vault url.
- [D2IQ-72821](https://jira.d2iq.com/browse/D2IQ-72821) Calico fails to build centos/8.1.1911 repo unavailable
=> calico: fix build

packages/calico/extra/create-calico-docker-network.py, packages/calico/extra/dcos-calico-libnetwork-plugin.service
Only restart Docker if a restart file exists. This allows bootstrap to determine when a restart is necessary while keeping the certificate name the same.
This variation orders Felix startup before libnetwork startup, which allows both to use the same certificate.
- [D2IQ-72846](https://jira.d2iq.com/browse/D2IQ-72846) upgrade from 2.1.{0,1} to 2.2.0 stops workloads 
- [D2IQ-72784](https://jira.d2iq.com/browse/D2IQ-72784) Cosmos bootstrap 400 errors
=> Restart Docker variation 2

packages/calico/extra/create-calico-docker-network.py, packages/calico/extra/dcos-calico-libnetwork-plugin.service
Forward-port of #7815
Only restart Docker if a restart file exists. This allows bootstrap to determine when a restart is necessary while keeping the certificate name the same.
This variation orders Felix startup before libnetwork startup, which allows both to use the same certificate.
- [D2IQ-72846](https://jira.d2iq.com/browse/D2IQ-72846) upgrade from 2.1.{0,1} to 2.2.0 stops workloads 
- [D2IQ-72784](https://jira.d2iq.com/browse/D2IQ-72784) Cosmos bootstrap 400 errors
=> [master] Restart Docker if restart file exists

packages/calico/extra/create-calico-docker-network.py, packages/calico/extra/dcos-calico-libnetwork-plugin.service
Back-port of #7815
Only restart Docker if a restart file exists. This allows bootstrap to determine when a restart is necessary while keeping the certificate name the same.
This variation orders Felix startup before libnetwork startup, which allows both to use the same certificate.
- [D2IQ-72846](https://jira.d2iq.com/browse/D2IQ-72846) upgrade from 2.1.{0,1} to 2.2.0 stops workloads 
- [D2IQ-72784](https://jira.d2iq.com/browse/D2IQ-72784) Cosmos bootstrap 400 errors
=> [2.1] Restart Docker if restart file exists

CHANGES.md, gen/dcos-config.yaml, packages/dcos-net/extra/dcos-net-setup.py
dcos-net: fix argument order for `add_config`
- [D2IQ-73113](https://jira.d2iq.com/browse/D2IQ-73113) dcos-net fails to start on RHEL/Centos 7.8 in dcos 2.2
- [COPS-6519](https://jira.d2iq.com/browse/COPS-6519) dcos-net not always able to set all Spartan IP addresses after node reboot
=> dcos-net: fix argument order for `add_config`

CHANGES.md, packages/marathon/buildinfo.json
- [MARATHON-8771](https://jira.d2iq.com/browse/MARATHON-8771)
=> [2.0] Bump Marathon to 1.9.146

packages/dcos-integration-test/requirements.txt, packages/python-certifi/buildinfo.json, packages/python-cryptography/build, packages/python-cryptography/buildinfo.json, test-e2e/requirements.txt, tox.ini
Bump Python security libraries, particularly `cryptography` to fix CVE-2020-25659
- [D2IQ-73273](https://jira.d2iq.com/browse/D2IQ-73273) Update Python cryptography library to 3.2+
=> Update Python security libraries

CHANGES.md, gen/dcos-config.yaml, packages/adminrouter/docker/Dockerfile, packages/adminrouter/docker/adminrouter-grpc-proxy-etcd.conf, packages/adminrouter/extra/src/nginx.master.conf, packages/etcd/extra/systemd/dcos-etcd.service, test-e2e/test_calico_networking.py
When calico is disabled, we should also disable etcd.
- [D2IQ-73299](https://jira.d2iq.com/browse/D2IQ-73299) Disable etcd with calico
=> etcd: disable etcd when calico is disabled

test-e2e/test_etcd_backup.py
There is a small typo in test-e2e/test_etcd_backup.py.
Should read `through` rather than `thsrough`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, thsrough -> through
