README.md
=> Add a more comprehensive Getting Started section

ext/dcos-installer/dcos_installer/__init__.py, gen/installer/bash.py
=> Merge Train 0

gen/aws/templates/advanced/advanced-master.json, gen/aws/templates/advanced/advanced-pub-agent.json, gen/aws/templates/advanced/infra.json, gen/aws/templates/cloudformation.json, gen/azure/templates/acs.json, gen/azure/templates/azuredeploy.json, packages/dcos-history-service/extra/README.md, packages/dcos-installer-ui/buildinfo.json, packages/openssl/buildinfo.json
Contains: #45, #44, #39, #35, #27, #23
=> Merge Train 1

packages/dcos-history-service/extra/README.md
Cover the basics of the API and file persistence
=> Update README.md for dcos-history-service

packages/openssl/buildinfo.json
https://www.openssl.org/news/changelog.html#x1
=> openssl package: update to 1.0.2h

gen/azure/templates/acs.json, gen/azure/templates/azuredeploy.json
Update from Ubuntu 16.04 LTS daily snapshots to the official LTS release.
=> Update to Ubuntu 16.04 LTS Release

README.md, ext/dcos-installer/dcos_installer/config/__init__.py, gen/aws/templates/advanced/advanced-priv-agent.json, gen/aws/templates/advanced/advanced-pub-agent.json, gen/azure/templates/azure.html, pytest/test_installer_backend.py, test_util/integration_test.py
- Some missing slash
- Some misplaced slash
=> Fix various instances of DC/OS

ext/dcos-installer/dcos_installer/action_lib/__init__.py, ext/dcos-installer/dcos_installer/action_lib/utils.py, ssh/ssh_runner.py, ssh/utils.py
DCOS-6431
The result will include a comment from a command chain. This should give
a human readable description of a command being executed on a host.
=> ssh: add stage field to process output result

packages/dcos-signal/buildinfo.json
https://github.com/dcos/dcos-signal/pull/4
=> Signal v1.0.10

contributing.md
Lots still TODO. Outlining the basics of updating a component
=> Adding documentation / guidelines around various contributions

README.md, config/dcos-release.config.yaml, gen/calc.py, gen/dcos-config.yaml, gen/installer/aws.py, gen/installer/bash.py, gen/installer/bash/Dockerfile.in, pytest/test_release.py, release/__init__.py
Making things flexible in ways needed for Mesosphere downstream. Mainly tweaks to make things more configurable.
=> Changes for Downstreams

test_util/installer_api_test.py, test_util/test_installer_ccm.py
Replace parallel implementation of one-off SSH
communication with ssh/ssh_tunnel.py module
=> Unify SSH runner in installer_api_test.py

pkgpanda/__init__.py
=> Better error for conflicting files in packages

test_util/run-all
Currently stored in TC, but needs to edited with every test configuration change. Rather, it should just live with the test
=> Check in CI log collection

ext/dcos-installer/dcos_installer/action_lib/__init__.py, ext/dcos-installer/dcos_installer/async_server.py, pytest/test_installer_async_api.py, pytest/test_installer_backend.py, pytest/test_ssh_unittest.py, ssh/validate.py, test_util/installer_api_test.py, test_util/integration_test.py, test_util/run-all, test_util/test_installer_ccm.py
- add public agent role to installer.
- refactor installer code.
- update integration / unit tests.
- make agent_list and agent_public_list not required to pass validation.
=> add public agent role

packages/dcos-installer-ui/buildinfo.json
This includes the public agent UI elements as well as the options to disable telemetry and authentication.
=> Update to latest Installer UI SHA

test_util/test_installer_ccm.py
-Minuteman enabled is a deprecated configuration option
-Collect AWS env vars in the same manner as everything else
-Add ability to set cluster size/composition
=> Update options for test_installer_ccm.py

README.md, build_local.sh
Sets up a python virtual env and uses sane commands to do a full dcos build
=> Add a build_local script to help doing dev work

test_util/integration_test.py
Hopefully fixes some of the CI test flaky failures which appeared recently.
=> Wait for all slaves to join, rather than just some slaves

pkgpanda/actions.py, pkgpanda/build/__init__.py, pkgpanda/cli.py
=> Pkgpanda: Separate package management actions from CLI

gen/azure/calc.py
cc: @lingmann who found the azure broken recently.
=> Fix Azure to use it's ip-detect script rather than AWS'

pkgpanda/actions.py, pkgpanda/cli.py
=> Pkgpanda: Remove exit() from actions

test_util/test_installer_ccm.py, test_util/test_runner.py
Makes the code a little more sensible and fixes some documentation
=> Cleanup test_runner

packages/3dt/buildinfo.json, packages/dcos-history-service/buildinfo.json, packages/dcos-history-service/extra/dcos-history.service, test_util/integration_test.py
=> Update dcos-history-service to have a state directory, run as non-root (dcos_history)

packages/3dt/buildinfo.json, test_util/integration_test.py
- fix for history service location
https://github.com/dcos/3dt/pull/29
- add system metrics
https://github.com/dcos/3dt/pull/23
- code refactor
- fix integration test
=> use latest 3dt

pkgpanda/build/__init__.py
Found by #155, where the package wasn't rebuilt as these variables changed.
=> Include username, state_dir flag in a package's package_id

packages/3dt/build, packages/3dt/buildinfo.json
=> Make 3dt not run as root

packages/erlang/build, packages/erlang/buildinfo.json
=> Make erlang non-root

packages/dcos-signal/buildinfo.json, packages/dcos-signal/extra/dcos-signal.service
=> Make dcos-signal non-root

packages/cosmos/build, packages/cosmos/buildinfo.json
=> Make cosmos run as non-root

packages/adminrouter/build, packages/dcos-oauth/buildinfo.json, packages/dcos-oauth/extra/dcos-oauth-setup.py, packages/dcos-oauth/extra/dcos-oauth.service
=> Make dcos-oauth run as non-root

gen/dcos-config.yaml, packages/logrotate/build, packages/logrotate/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/extra/dcos-mesos-master.service, test_util/integration_test.py
=> Make mesos master run as non-root

gen/__init__.py, gen/aws/calc.py, gen/aws/templates/advanced/advanced-master.json, gen/aws/templates/advanced/advanced-priv-agent.json, gen/aws/templates/advanced/advanced-pub-agent.json, gen/aws/templates/advanced/infra.json, gen/aws/templates/advanced/zen.json, gen/azure/cloud-config.yaml, gen/calc.py, gen/installer/aws.py, gen/installer/azure.py
Support for EL7 and custom AMI's with AWS Advanced Templates
=> AWS Advanced Template support for EL7

packages/mesos/extra/make_disk_resources.py
Should fix Issue reported in Slack: https://dcos-community.slack.com/archives/general/p1464956464021830
=> make_disk_resources.py: Assign disk resources the mesos default role, rather than `*`

test_util/installer_api_test.py
See https://mesosphere.atlassian.net/browse/DCOS-5906
=> make curl fail for non-200 status code in download

packages/mesos-dns/build, packages/mesos-dns/buildinfo.json
This is a build from Mesos-DNS master that we'll cut before 1.8 release
=> Bump to Mesos-DNS head

gen/aws/templates/advanced/infra.json, gen/aws/templates/cloudformation.json
Code originally by @lingmann in older DC/OS repository.
=> Fix AWS HTTPS accessibility issue

packages/openssl/build
Also switch both finds to -delete for consistency
=> Delete man pages from openssl build

packages/python/build, packages/python/buildinfo.json
- setuptools 21.0.0
- pip 0.8.2
=> python: Take control of setuptools and pip version

packages/3dt/build, test_util/integration_test.py
=> Rename systemd unit dcos-ddt -> dcos-3dt

docs/admin-ports.md
Verified by running `sudo netstat -nlp` on a master, agent, and public agent.
=> Add admin ports doc

packages/mesos-dns/buildinfo.json
Fixing typo introduced here : https://github.com/dcos/dcos/pull/241
=> Fix typo for Mesos-DNS repo

test_util/test_installer_ccm.py, test_util/test_runner.py
Should have been caught when this variable was removed in the first place
=> Remove unused env variable

release/__init__.py
Verify if version is < 1.10 and if > remove force flag from `docker tag`
=> This is the fix for DCOS-196

ext/dcos-installer/dcos_installer/action_lib/__init__.py
https://mesosphere.atlassian.net/browse/DCOS-7930
=> run 3dt -diag as root

packages/bootstrap/build, packages/bootstrap/extra/dcos_internal_utils/bootstrap/cli.py, packages/bootstrap/extra/setup.py, packages/bootstrap/extra/tests/test_bootstrap.py, tox.ini
Should help with some of the dirty build problems we've been seeing
=> Switch bootstrap to use entry_points, cleanup packaging a little

packages/exhibitor/buildinfo.json
This should land after #191 (Mesos bundles a zk...)
=> Update zookeeper to 3.4.8

packages/dcos-installer-ui/buildinfo.json
This includes:
* "Stage of Stage" UI Updates
* Telemetry and OAuth toggles
* Public agent form field
=> Update latest Installer UI SHA

gen/installer/util.py, pkgpanda/build/__init__.py
This PR allows treeinfo files to include a `bootstrap_package_list`, which declares the packages that are installed into the bootstrap tarball. This changes the semantics of `core_package_list` to mean the set of all packages that comprise a DC/OS release, of which `bootstrap_package_list` may be a subset.
If `bootstrap_package_list` isn't declared, it defaults to `core_package_list`. This means existing treeinfo files will produce the same build output.
Packages that aren't included in the bootstrap tarball are not yet included in a release, so `bootstrap_package_list` should not be used except for testing. A followup PR will modify release code to include all built packages along with the bootstrap tarball.
=> Add support for bootstrap_package_list in treeinfo files

packages/mesos-dns/build, packages/mesos-dns/buildinfo.json
-Includes the security work
-Hash: 22146c64f14e9d4f067cbaa00f45a6b7f78d01e4
=> Bump Mesos DNS to master

packages/3dt/build, packages/3dt/buildinfo.json, test_util/integration_test.py
backend PR https://github.com/dcos/3dt/pull/43
CLI PR https://github.com/dcos/dcos-cli/pull/675
DCOS-8227
=> rename snapshot to diagnostics bundle

gen/installer/bash.py
None -> empty variant
https://dcosjira.atlassian.net/browse/DCOS-210
=> Print out the variant string rather than uninterpreted variant

packages/3dt/build, packages/3dt/buildinfo.json, test_util/integration_test.py
sometimes it can take up to 2-3 seconds to list the available snapshots off the
filesystem after job is finished.
=> try to list snapshots after the job is done

gen/aws/calc.py, gen/aws/templates/advanced/advanced-master.json, gen/aws/templates/advanced/advanced-priv-agent.json, gen/aws/templates/advanced/advanced-pub-agent.json, gen/aws/templates/advanced/zen.json, gen/aws/templates/cloudformation.json
- Remove a configurable we don't use
- Enable Turn on `EbsOptimized`.
=> Misc. AWS CloudFormation fixes

packages/dcos-signal/buildinfo.json, test_util/integration_test.py
https://github.com/dcos/dcos-signal/pull/26
https://github.com/dcos/dcos-signal/pull/25
https://github.com/dcos/dcos-signal/pull/23
=> Updated signal

test_util/installer_api_test.py
Don't bother checking git blame; that monstrosity is mine :(
=> Fix incorrect syntax

gen/aws/calc.py, gen/aws/templates/advanced/advanced-master.json, gen/aws/templates/advanced/advanced-priv-agent.json, gen/aws/templates/advanced/advanced-pub-agent.json, gen/aws/templates/advanced/zen.json, gen/aws/templates/cloudformation.json
Revert https://github.com/dcos/dcos/pull/287 for now
=> Revert #287

ext/dcos-installer/dcos_installer/backend.py, ext/dcos-installer/dcos_installer/util/__init__.py, gen/aws/calc.py, gen/calc.py, gen/cloud-config.yaml, gen/dcos-config.yaml, packages/dcos-integration-test/extra/integration_test.py, packages/dvdcli/build, packages/dvdcli/buildinfo.json, packages/marathon/build, packages/rexray/build, packages/rexray/buildinfo.json, packages/rexray/extra/dcos-rexray.service, test_util/installer_api_test.py, test_util/run-all, test_util/test_installer_ccm.py
=> Adding Rex-Ray support to DC/OS

README.md
Small fix to change premise to premises (see http://itsonpremises.com) and varios to various.
=> fixed minor typos in README.md 

ssh/ssh_tunnel.py
Did not realize %C was so new when this was first implemented
=> Make SSHTunnel compatible with ssh<6.7

packages/dcos-integration-test/extra/integration_test.py
-remove default values in health checks
-add large timeout for slow build and push
-read test_server resources off disk, not via definition
=> Adjust cluster_registry marathon app

gen/aws/templates/advanced/advanced-priv-agent.json, gen/aws/templates/advanced/advanced-pub-agent.json, gen/aws/templates/cloudformation.json
Allow cloudwatch:PutMetricData and autoscaling:DescribeAutoScalingGroups from agents.
=> Update IAM to allow Cloudwatch stats publishing

test_util/test_installer_ccm.py, test_util/test_runner.py
Also allows pluggable pytest_dir and pytest_cmd
=> Collect pytest first to catch setup failures

packages/dcos-integration-test/extra/test_env.export
Helps facilitate on-prem debugging
=> Add naive test environment

release/__init__.py
Ideally all this logic should live inside pkgpanda (and the dockers should be lazily built / pulled as needed). This is an MVP so we don't have to maintain more dockers out of band.
cc: @vespian
=> Teach release to build all dockers in the `pkgpanda/docker` folder

packages/dcos-ui/buildinfo.json
=> Bump dcos-ui 1.8

pkgpanda/build/__init__.py, pytest/test_release.py, release/__init__.py
This adds `complete_dict`, `all_completes`, and `<variant>.complete.latest.json` to build metadata.
=> Add complete build metadata to metadata.json

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/test_composition.py
use protocol consistent with dns
=> Propogate URL scheme (Fix test_composition.py)

README.md, packages/exhibitor/buildinfo.json, packages/python/buildinfo.json
=> Upgrade python to 3.4.5

packages/spartan/buildinfo.json
-Fix the healthcheck issue when new interfaces come online
-Add localhost (TLD)
=> Bump Spartan

packages/3dt/build, packages/3dt/buildinfo.json
- make 3dt report more verbose errors
https://github.com/dcos/3dt/pull/49
- fix bug to inject git commit to revision variable
=> enhance 3dt errors and bug fixes

ext/dcos-installer/dcos_installer/cli_dispatcher.py, ext/dcos-installer/dcos_installer/installer_analytics.py
Non-blocker, expected GA.
https://mesosphere.atlassian.net/browse/DCOS-8489
Results:
```
analytics.track('installer', {
'bootstrap_id': '0f11ac4a2b11f5601c6171c61746776a556fe9b2',
'provider': 'onprem',
'source': 'installer',
'variant': 'enterprise',
'errors': 6,
'install_id': 'e458f0f7-14fa-4893-85b9-edba23229c5a',
'customerKey': null,
'install_method': 'cli',
'action_name': 'preflight'
})```
=> CLI Signal 1.8 Improvements

gen/__init__.py, gen/dcos-config.yaml, packages/dcos-integration-test/extra/test_misc.py
=> Teach gen to make a special expanded config json blob, which contains all arguments but itself

pkgpanda/__init__.py, pkgpanda/build/cli.py, pkgpanda/cli.py, pkgpanda/integration-tests/test_setup.py, pkgpanda/tests/test_install.py, pkgpanda/tests/test_repository.py
Various cleanups and Fixes that I noticed. 
* Submitting this as a separate PR as it can reduce unrelated noise in other PRs.
Please review @spahl , @cmaloney
=> Minor clean up, spell fixes and syntax fixes.

packages/mesos-overlay-modules/buildinfo.json
Also, modified overlay master recovery so that the state of recovery
can be inferred from the replicated log store rather than by maintain
explicit state variables, which was error prone.
=> Added batch write support to overlay replicated log.

packages/dcos-ui/buildinfo.json
=> Bump dcos-ui version 1.8

pkgpanda/build/__init__.py, pkgpanda/util.py, release/__init__.py
This is very early WIP, just for sake of disusing stuff.
=> Add custom builders support

ext/dcos-installer/dcos_installer/action_lib/__init__.py
related PR: https://github.com/dcos/dcos/pull/477
=> run `install_prereqs` only once on a host

packages/dcos-ui/buildinfo.json
=> Version bump dcos-ui 1.8

NOTICE
=> Moved to 2016 on copyright

packages/dcos-integration-test/extra/test_applications.py
Tests running a Docker image with the Mesos containerizer (aka Unified
Containerizer).
=> Add an integration test for the Mesos containerizer.

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/delete_ec2_volume.py, packages/dcos-integration-test/extra/test_ec2.py
=> Change delete EC2 volume to a metronome one-off

setup.py, test_util/test_installer_ccm.py, test_util/test_runner.py
1. removed python file references that no longer exist
2. changed comments which were references to older code which were refactored.
=> python test clean up

packages/minuteman/buildinfo.json
This change fixes minuteman for named VIPs with 2 or more ports in use
=> Fixes minuteman for named VIPs with 2 or more ports in use

ext/dcos-installer/dcos_installer/cli.py, ext/dcos-installer/dcos_installer/cli_dispatcher.py
Satisfies https://mesosphere.atlassian.net/browse/DCOS-9283
=> CLI flag to disable installer CLI telemetry

prep_local, prep_teamcity
Just a good hygiene that if we are relying on pip, make sure that it's latest version.
Also, prevents this warning the stderr
```
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
=> upgrade pip before proceeding with other installs.

docs/admin-ports.md, gen/calc.py, test_util/test_installer_ccm.py
=> Move REX-Ray out of the agent port range

gen/aws/calc.py, gen/aws/templates/cloudformation.json
The parts of #287 that won't break the various DC/OS frameworks
=> Misc. AWS CloudFormation fixes take 2

ext/dcos-installer/dcos_installer/async_server.py, tests/test_installer_async_api.py
Fixes https://dcosjira.atlassian.net/browse/DCOS-94
=> Add a simple API to the web installer to get the DC/OS version

packages/3dt/buildinfo.json
make sure the main process returned 0 status code
https://github.com/dcos/3dt/pull/57
DCOS-9323
=> 3dt: add check for `ExecMainStatus`

packages/3dt/buildinfo.json
- persistent http connections bug
https://github.com/dcos/3dt/pull/60
DCOS-9446
- small bug fixes
https://github.com/dcos/3dt/pull/61
https://github.com/dcos/3dt/pull/58
=> 3dt: use latest 3dt

ext/dcos-installer/dcos_installer/action_lib/configure.py, pkgpanda/build/__init__.py
A couple of the code changes in #575 pulled out to land independently
=> Complexity cherry picks

packages/dcos-ui/buildinfo.json
Bump DC/OS UI version ref to latest and greatest.
=> Update DC/OS UI version ref

gen/calc.py, tests/test_gen_validation.py
These two come up really often, nice to have some common code for them.
@jgrehrcke came up with this in a closed downstream of this, moving to upstream
because it's useful.
=> Add a validate_one_of and validate_true_false to gen/calc.py

packages/dcos-integration-test/extra/test_applications.py, packages/octarine/buildinfo.json
The update includes aesthetic changes (should be no effect) as well as a small change to how URLs are parsed (should also be no effect). As well as a fix to a bug in the integration test.
=> Octarine package and integration test update

gen/installer/aws.py, gen/installer/azure.py, gen/installer/bash.py, release/__init__.py
cc: @lingmann to review if this seems actually simpler.
=> Switch do_create to yield artifacts rather than having every function build a list

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/test_applications.py, packages/dcos-integration-test/extra/test_networking.py, packages/dcos-integration-test/extra/test_service_discovery.py
We're using the host python anyways. Should hopefully help avoid dockerhub pull issues a bit.
=> Switch to running mesos-native containers for the most part, small docker when required.

gen/calc.py
Found by @jgehrcke https://github.com/dcos/dcos/pull/594/files#r76564327
=> Update docstring to be accurate

packages/bootstrap/extra/tests/test_bootstrap.py
=> Convert test_bootstrap to pytest format

ext/dcos-installer/dcos_installer/action_lib/configure.py, ext/dcos-installer/dcos_installer/config.py, gen/calc.py, gen/test_validate.py
- Set ip_detect_filename default for onprem installs
- Make bootstrap_id set via calc
- Fix broken erroring if dcos_image_commit can't be gotten.
=> Misc. DCOSConfig related cleanup

ext/dcos-installer/dcos_installer/backend.py, ext/dcos-installer/dcos_installer/cli.py
It was only used one place, the local defined in function function didn't make any sense
=> Fold hash_password into dcos_installer.cli

packages/3dt/buildinfo.json
DCOS-9499
https://github.com/dcos/3dt/pull/62
=> fix flaky 3dt test

packages/dcos-integration-test/extra/test_3dt.py
The tests have shown it takes about 1 second per node to fetch the logs. While
the static timeout works well for small clusters it does not work for large
ones. That being said, we shall calculate the timeout in runtime based on a
number of nodes in a cluster + 15% tolerance.
=> calculate diagnostics job timeout

gen/aws/templates/advanced/advanced-master.json, gen/aws/templates/advanced/advanced-priv-agent.json, gen/aws/templates/advanced/advanced-pub-agent.json, gen/aws/templates/advanced/zen.json, gen/installer/aws.py
FIXES: https://dcosjira.atlassian.net/browse/DCOS-321
=> Configuring oauth in the advanced templates

ext/dcos-installer/README.md, ext/dcos-installer/dcos_installer/action_lib.py, ext/dcos-installer/dcos_installer/async_server.py, ext/dcos-installer/dcos_installer/backend.py, ext/dcos-installer/dcos_installer/config_util.py, test_util/installer_api_test.py
See individual commits for more details.
=> Make paths in installer for /genconf and /artifacts relative, better errors in installer_api_test

ext/dcos-installer/dcos_installer/backend.py
Simplify conditionals to make the business logic easier to follow
cc: @malnick
=> Cleanup backend.determine_config_type a bit, make it more DRY

ext/dcos-installer/dcos_installer/backend.py, gen/installer/aws.py, ssh/validate.py
- Fix the printed bucket path being wrong
- Make it so public_agent_list is defaulted properly.
=> Advanced aws fixes

packages/dcos-integration-test/extra/conftest.py
allows cleaner deploy->checks->cleanup
=> Add context manager for marathon apps

packages/dcos-integration-test/extra/test_3dt.py
- latest 3dt version exposes a `job_progress_percentage`. Make the test to
track the progress. If test detects that the diagnostics job is stale, it will
fail right away.
https://github.com/dcos/3dt/pull/65
- typo fix
https://github.com/dcos/3dt/pull/64
=> fix flaky `test_3dt_bundle_create` test

gen/installer/bash/dcos_generate_config.sh.in, pkgpanda/build/__init__.py
Figured this would be good to have in place so that we don't leave 200+ exited containers lying around after each build.
=> Cleanup containers

packages/spartan/extra/dcos-spartan-watchdog.service, packages/spartan/extra/dcos-spartan-watchdog.timer
=> Make dcos-spartan-watchdog start later rather than have a random 60 second sleep

ext/dcos-installer/dcos_installer/async_server.py
Recommendations from: http://stackoverflow.com/questions/49547/making-sure-a-web-page-is-not-cached-across-all-browsers with input from the UI team
cc: @rcorral 
https://mesosphere.atlassian.net/browse/DCOS-9649
=> Teach the installer to cache even less

ext/dcos-installer/dcos_installer/action_lib.py, ext/dcos-installer/dcos_installer/async_server.py, ext/dcos-installer/dcos_installer/backend.py, ext/dcos-installer/dcos_installer/cli.py, ext/dcos-installer/dcos_installer/config.py, ext/dcos-installer/dcos_installer/config_util.py, ext/dcos-installer/dcos_installer/installer_analytics.py, gen/__init__.py, gen/calc.py, gen/test_validate.py, ssh/validate.py, test_util/installer_api_test.py, tests/test_installer_async_api.py, tests/test_installer_backend.py, tests/test_installer_init.py, tox.ini
Includes some misc. fixes / cleanup.
Some hacks in here, but I think there is definite net improvement. The hacks will be removed in time.
=> Replace DCOSConfig with a new Config class

packages/dcos-ui/buildinfo.json
Includes version tracking of UI JS errors.
=> bump dcos-ui

test_util/aws.py, test_util/cluster.py, test_util/test_aws_cf.py, test_util/test_aws_vpc.py, test_util/test_runner.py
This is a series of refactors and fixups in support of #648. Depends on #622.
=> Add test_util.cluster.Cluster

test_util/aws.py
When boto waiters fail they just say " botocore.exceptions.WaiterError: Waiter InstanceRunning failed: Waiter encountered a terminal failure state" which is effectively worthless. So, add a wrapper to catch that error and dump the stack event info. Regardless of which client is waiting, client('cloudformation').describe_stack_events() is probably the most relevant thing to dump upon bumping into a failure in time domain
=> Replace boto waiter with simple loop

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/resiliency/test_aws_cf.py, test_util/aws.py, test_util/helpers.py, test_util/test_aws_cf.py
Add first resiliency test. This test will:
1. Start 2 apps using VIPs
2. Ping the two apps
3. kill all nodes
4. wait for autoscaling group to repopulate the nodes
5. reset the agent lists
6. ping the 2 apps
=> Resiliency test

ext/dcos-installer/dcos_installer/config.py
=> Copyedit a user visible string courtesy the docs team

gen/dcos-config.yaml
The dcos-config.yaml template was failing to generated
valid yaml when we included some proxy configuraiton.
Fixes https://dcosjira.atlassian.net/browse/DCOS-387
=> Fix generation of http proxy configuration

gen/calc.py, tests/test_installer_backend.py
1.8 stable was released, is now in a branch + cherry-picks. Master is heading to 1.9
=> Bump version to 1.9-dev

gen/calc.py, packages/mesos-dns/buildinfo.json, packages/spartan/extra/gen_resolvconf.py, tests/test_gen_validation.py
Addresses the Gen portion of https://github.com/mesosphere/mesos-dns/issues/459
=> Support non-standard ports for upstreams

gen/calc.py, gen/dcos-config.yaml
@sargun @cmaloney  Request you to please review this PR
=> Bug DCOS-9371: Makes named VIP subnet configurable from gen

packages/dcos-integration-test/extra/test_3dt.py
Minimial refactor so that 3DT is compatible
with SSL enabled clusters
See: https://github.com/mesosphere/dcos-enterprise/pull/316
for downstream results with this change
=> Modify for 3DT for downstream compatibility

packages/mesos/buildinfo.json
=> Rebase off Mesos 1.0.x branch

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/test_3dt.py, packages/dcos-integration-test/extra/test_applications.py, packages/dcos-integration-test/extra/test_auth.py, packages/dcos-integration-test/extra/test_composition.py, test_util/cluster_api.py, test_util/helpers.py
Builds on work from https://github.com/dcos/dcos/pull/772
Note: 0e8cbec987d89dbf3dd59b8683f2027d8b11ae96 is taking advantage of this change to have adminrouter URL construction in only one place
=> Consolidated request methods

test_util/aws.py
-Catches client error and if the error is due to throttling, the poll interval will be increased
-Frees up the API quota by adding a sleep before beginning to poll as we can be reasonable certain a given cloud formation will not come up in less than N minutes
=> Handle AWS Client Throttling Error

dcos_installer/backend.py
The installer is exiting 1 even if --aws-cloudformation
completed without error
=> Fix Custom Cloudformation Error Code

gen/calc.py
=> Switch dcos overlay configuration to be json.dump() rather than hand-coded json

packages/adminrouter/build, packages/curl/build, packages/erlang/build, packages/libsodium/build, packages/mesos-modules/build, packages/mesos-overlay-modules/build, packages/mesos/build, packages/ncurses/build, packages/python/build, pkgpanda/build/__init__.py
@cmaloney what do you think about applying this change to many of the other components as well?
=> Build packages with the number of cores that the machine has

packages/marathon/buildinfo.json
=> Marathon 1.3.1

packages/dcos-history/build, packages/dcos-history/buildinfo.json, packages/dcos-history/extra/dcos-history.service, packages/dcos-history/extra/history/dcos_history_conf.py, packages/dcos-history/extra/history/server.py, packages/dcos-history/extra/setup.py, packages/dcos-integration-test/extra/test_endpoints.py
This reverts commit 9cf07a7ce10e3a3689725ec86c7e37f4a987c2be.
Short term to make the UI look good until a proper fix is completed / can be landed.
cc: @amitaekbote
=> Revert "Handle connection error on dcos-history"

packages/dcos-ui/buildinfo.json
This PR should merge into `master` branch only.
=> Fixes dcos-ui package.

packages/spartan/buildinfo.json
- points dcos package to latest spartan build with fix for DCOS-9149
=> Bug DCOS-9149: Adds timeout to spartan fetching Exhibitor data

packages/minuteman/buildinfo.json
This is tied to the Minuteman commit https://github.com/dcos/minuteman/commit/611e60cc0d8bd9728579454cdca26e841925c441
=> Fix SSL strict mode for Minuteman

gen/aws/calc.py, gen/calc.py
When true ip_detect_public gets a public ip from the AWS Metadata endpoint
When false it gets the private ip from the AWS Metadata endpoint
=> Add new aws_masters_have_public_ip configuration option

test_util/cluster_api.py
internal issue: https://mesosphere.atlassian.net/browse/DCOS-10327
=> fix python_test_server.py running as nobody

gen/dcos-config.yaml
https://mesosphere.atlassian.net/browse/DCOS-10425
=> Add dummy mesos module json so that there's always at least one mesos module

packages/dcos-ui/buildinfo.json
Update DCOS UI version to include the latest bug fixes.
=> Update DCOS UI version

gen/aws/templates/advanced/advanced-master.json, gen/aws/templates/advanced/advanced-priv-agent.json, gen/aws/templates/advanced/advanced-pub-agent.json, gen/aws/templates/advanced/infra.json, gen/aws/templates/cloudformation.json, gen/installer/aws.py, gen/test_installer_aws.py
Unit tests pass , more testing required before final review
=> Abstracting Region and NAT ami mapping

packages/dcos-integration-test/extra/resiliency/test_aws_cf.py, test_util/aws.py, test_util/helpers.py, test_util/test_aws_cf.py
-decrease boto verbosity
-catch another rate exception
=> Add boto rate limit decorator

packages/3dt/buildinfo.json
- replace log with logrus
- fix https://dcosjira.atlassian.net/browse/DCOS-432
- code cleanup
https://github.com/dcos/3dt/pull/71
=> refactor 3dt

dcos_installer/backend.py, tests/test_installer_backend.py
When config.yaml provided to dcos_installer/backend.py contains `aws_template_upload: true` `aws_template_storage_region_name` will be set to the actual region of the specified s3 bucket.
The actual region of the s3 bucket is determined by calling `get_bucket_location` using boto3 s3 client.
=> Update dcos_installer/backend.py to use s3 region when aws_template_upload is true

test_util/aws.py
CI tests are failing because Cloudformations report as "CREATE_COMPLETE" yet they have less than the number of instances required by the deployment. Eventually those instances seem to appear and the logs don't indicate that our client could have done any better with the information returned. See:
https://teamcity.mesosphere.io/viewLog.html?buildId=456276&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_DcosOssCcmInstallTestAp
Thus, keep retrying until we get the expected number of nodes.
=> Account for AWS under-provisioning

packages/marathon/buildinfo.json
=> Upgrade marathon to 1.3.5

packages/dcos-ui/buildinfo.json
=> bump dcos-ui package. release:next

packages/mesos/extra/make_disk_resources.py
Just fixing a typo in Informational message  in the script
Correct spelling looks good
No impact in t he grander scheme of things
[DCOS-<number>](https://dcosjira.atlassian.net/browse/DCOS-<number>)
...
=> Fix spelling for Volume

docs/admin-ports.md
This PR removes an irrelevant port and applies consistent formatting and naming.
N/A
=> Clean up admin ports doc

packages/dcos-image/extra/dcos-shell
fix dcos-shell with single argument
=> fix dcos-shell with single argument

packages/exhibitor/extra/start_exhibitor.py, pkgpanda/build/cli.py, release/__init__.py, release/storage/aws.py, release/storage/azure.py, release/storage/http.py, release/storage/local.py, test_util/azure_test_driver.py, test_util/test_aws_cf.py
PyCodeStyle got updated:
https://github.com/PyCQA/pycodestyle/blob/master/CHANGES.txt#L24
causing:
https://teamcity.mesosphere.io/viewLog.html?buildId=473704&buildTypeId=DcosIo_Dcos_CodeQuality&tab=buildResultsDiv
=> Fix old pep8 errors

test_util/cluster_api.py, test_util/helpers.py
PR #950 was not actually verified when it was merged due to muted build. Reverting that PR to stabilize master and re-review that code
=> Revert "Abstract wrapper class"

test_util/cluster_api.py, test_util/helpers.py, test_util/marathon.py
I am confused how this even got merged in the first place. Nothing should be working as requests.request.get is not a thing.
=> Fix requests wrapper

test_util/marathon.py
This is a follow-up PR from pull/358. It fixes a small logging nit that was not fixed in the previous PR.
=> Fixed a non-idiomatic logging statement in the test utils.

packages/spartan/buildinfo.json
- It fixes Spartan TCP proxying. It fixes the issue when someone would send two queries across a TCP DNS question before waiting for a reply
It includes the following:
```
commit b44292fc37acb165d85f996b4965ac769f35cec0
Author: Sargun Dhillon <sargun@sargun.me>
Date:   Wed Nov 16 16:40:43 2016 -0800
Make sure dig runs against test server
commit 02e026e97ee33f4f6e1faf79bf16f1b2659fbe55
Author: Sargun Dhillon <sargun@sargun.me>
Date:   Wed Nov 16 16:23:34 2016 -0800
Use test fixture zone
commit c9507d75b04b94dfdcbc5f6bb577a862d01a4ad5
Author: Sargun Dhillon <sargun@sargun.me>
Date:   Wed Nov 16 16:01:46 2016 -0800
adjust circle.yml to Ubuntu 14.04
commit 6eccc614554459c3e208778ec872d744874ba2d2
Author: Sargun Dhillon <sargun@sargun.me>
Date:   Wed Nov 16 …
```
=> Fix Spartan TCP handling

gen/dcos-config.yaml, packages/adminrouter/buildinfo.json, packages/bootstrap/extra/dcos_internal_utils/cli.py, packages/dcos-integration-test/extra/test_composition.py, packages/dcos-integration-test/extra/test_dcos_log.py, packages/dcos-log/build, packages/dcos-log/buildinfo.json, test_util/cluster_api.py
- Enable system components: DC/OS Log service, DC/OS Log socket on all DC/OS nodes.
- Add [DC/OS Logging service](https://github.com/dcos/dcos-log) as pkgpanda service.
- Bump adminrouter to include the required routes.
- 
[DCOS-10116](https://mesosphere.atlassian.net/browse/DCOS-10116)
=> add pkgpanda service `dcos-log`

pkgpanda/docker/dcos-builder/Dockerfile
Update Go to 1.7.4 (security fixes).
=> Update Go to 1.7.4 (security fixes)

packages/boost-libs/build, packages/boost-libs/buildinfo.json, packages/mesos-modules/build, packages/mesos-modules/buildinfo.json, packages/mesos/build, packages/mesos/buildinfo.json
- use separate boost package instead of the 3rd party mesos included one
- this is in preparation of merging metrics (https://github.com/dcos/dcos/pull/778)
=> boost-libs package

packages/dcos-ui/buildinfo.json
---
ℹ️   _This branch depends on features that will be introduced with #971 and #1024 thus not all of the features will work until the respective branches got merged. For further details please see the integration section._
---
Update DC/OS to include the latest DC/OS UI 1.9 release. The new DC/OS UI has a brand new look and feel, provides new tools to debug services, and features a much-improved flow for creating services.
_Much-improved flow for creating services._
_New look and feel._
_New tools to debug services._
This DC/OS UI version uses a set of new endpoints and packages that will land with #1045 and #1024 therefore not all of the features will work.   Nevertheless, it's ok to integrate the DC/OS UI packages first, as it was build in a way that the UI shouldn't break if those …
=> Update DC/OS UI to 1.9

docs/package-rules.md
=> pyton typo

packages/marathon/buildinfo.json
- Upgrades Marathon to version 1.4.0-RC3.
=> update marathon to version 1.4.0-RC3

packages/dcos-integration-test/extra/cluster_fixture.py, packages/dcos-integration-test/extra/test_composition.py, test_util/cluster_api.py, test_util/helpers.py, test_util/test_upgrade_vpc.py
Uses the integration test infrastructure to add a application and task.
* Verifies task is running after upgrade.
* Verifies that task is not restarted during upgrade.
[DCOS-11453](https://mesosphere.atlassian.net/browse/DCOS-11453)
=> Upgrade Testing With apps and task.

packages/metronome/buildinfo.json
=> bump metronome to v0.2.0

dcos_installer/async_server.py, packages/dcos-integration-test/extra/test_applications.py, test_util/aws.py, test_util/cluster.py, test_util/helpers.py, test_util/marathon.py, test_util/runner.py, test_util/test_aws_cf.py, test_util/test_aws_vpc.py
* These are generic fixes in the test code that I found when working on #984 
* Presenting them separately so that other one can stay focussed on functionality.
=> General fixes in the test code.

packages/dcos-integration-test/extra/test_endpoints.py
* Allows overlay upgrades from 1.8 -> 1.9
* Allows any agent configuration change (disabling mesos or docker network) to be allowed during upgrades
*Earlier the test cases were assuming that the configuration applied by the Master will always be the configuration given to the network configuration of the agent. This is obviously not true during upgrades since the overlay configuration for a specific agent is retrieved from the replicated log.
We are therefore changing the test to learn the overlay configuration being applied by the Master, and ensure that the configuration is reflected on the agent end-point.
[DCOS-557](https://dcosjira.atlassian.net/browse/DCOS-557)
...
=> Fixed upgrade issue (1.8->1.9) with overlay-modules.

packages/dcos-integration-test/extra/resiliency/test_aws_cf.py, packages/dcos-integration-test/extra/test_dcos_log.py, packages/dcos-integration-test/extra/test_service_discovery.py, packages/dcos-integration-test/extra/util/python_test_server.py, test_util/marathon.py
- Cosmetic Improvements throughout the module.
@mellenburg : Should be easy to review!
/cc
@cmaloney , @lingmann and @spahl  : This should be ready to go.
=> minor improvements in docs-integration-test.

packages/adminrouter/buildinfo.json
Updates adminrouter to include latest master
Notable changes:
- adds route for cosmos
- add fixes for metrics service
- add fixes for debugging features
=> bump adminrouter to 86a5967adf45844ae22315c09e4a0476c8f815da

packages/dcos-integration-test/extra/test_metrics.py
- Removes unnecessary retry logic from /node test. 
https://mesosphere.atlassian.net/browse/DCOS-12223
=> Remove retry from /node test

gen/calc.py, gen/dcos-config.yaml, packages/dcos-ui/buildinfo.json
****
[DCOS-10834](https://mesosphere.atlassian.net/browse/DCOS-10834)
[DCOS-12045](https://mesosphere.atlassian.net/browse/DCOS-12045)
Logs bug fix, new filtering and funnel for declined offers. **See below for new feature screenshots**
[Diff between commits](https://github.com/dcos/dcos-ui/compare/ffec1877fbfd15e2f44c045d60059107782c6dd2...bbb9d2740bd2067752b33fb383ce60f8f7b6745c)
```
Test Suites: 235 passed, 235 total
Tests:       2790 passed, 2790 total
Snapshots:   0 total
Time:        400.007s
Ran all test suites.
```
Adds Filtering to the services UI page
Adds funnel to declined offers view
=> Bump dcos-ui package.

ssh/tunnel.py
Test logs currently generate this very unhelpful message that makes debugging much harder
=> Avoid tempfile cannot be deleted error

packages/marathon/buildinfo.json
- Bug fix release for Marathon. We discovered a serious migration issue in RC3.
- Fixes https://github.com/mesosphere/marathon/issues/4873 - Tasks with configured Marathon HealthChecks fail HealthChecks after migration to 1.4
- Fixes https://github.com/mesosphere/marathon/issues/4842 - by also writing deprecated pods to the proto.
- Fixes https://github.com/mesosphere/marathon/issues/4828 - Use async InstanceTracker methods in SchedulerActor
- Fixes https://github.com/mesosphere/marathon/issues/4882 - by renaming KillSelection enum values
- Fixes https://github.com/mesosphere/marathon/issues/4890 - Quote some vars and make sed more explicit 
- Fixes https://github.com/mesosphere/marathon/issues/4872 - Disallow usage of Command Checks on Pods until mesos …
=> Use Marathon 1.4.0-RC4.

gen/internals.py
- Fix the attribute error for the `dcos_generate_config.sh`
[DCOS-12709](https://mesosphere.atlassian.net/browse/DCOS-12709)
=> Fix the AttributeError for dcos_generate_config.sh --aws-cloudformation.

test_util/azure_test_driver.py
Attempts to fix certain infrastructure flakiness with Azure.
The main change is this.
```
@retry(retry_on_exception=retry_if_assertion_error, stop_max_attempt_number=45)
```
Rest of the changes are only cursory improvements in the code that I touched.
Issues
* [DCOS-12673](https://mesosphere.atlassian.net/browse/DCOS-12673)
Checklist
[ ] Included a test which will fail if code is reverted but test is not
[ ] Followed relevant code rules Rules for Packages and Systemd
=> DCOS-12673/fix_azure_flaky

test_util/test_upgrade_vpc.py
Two new environment variables have been added that allow providing a path to a config.yaml that defines override properties for the install of the cluster and the upgrade of the cluster.
* CONFIG_YAML_OVERRIDE_INSTALL
* CONFIG_YAML_OVERRIDE_UPGRADE
[DCOS-9717](https://mesosphere.atlassian.net/browse/DCOS-9717)
=> Add parameters to test_upgrade_vpc.py to all overrides

packages/dcos-ui/buildinfo.json
- Adds multiple container create form 
[DCOS-<number>](https://dcosjira.atlassian.net/browse/DCOS-<number>)
...
This is what it looks like
cc/ @spahl
=> Bump dcos-ui package for 1.9.  Adds multi container form.

test_util/marathon.py, test_util/test_upgrade_vpc.py
* Drain Deployments before upgrade.
This is discussed in this ticket: https://mesosphere.atlassian.net/browse/DCOS-12746
=> Fix upgrade integration test

packages/dcos-integration-test/extra/test_3dt.py
-way too much unused information is being pumped out by default
-attempts to limit data dump to failure scenarios only
=> Reduce 3dt test verbosity

dcos_installer/prettyprint.py, test_util/aws.py
- Factors out three different bits of duplicate code CodeClimate found (most the others it found (https://codeclimate.com/github/dcos/dcos/issues) I don't think are worth fixing at the moment or make code much more complicated to fix. These are low hanging fruit.
=> Factor out common / duplicate code

packages/adminrouter/buildinfo.json
- clean up webui_url handling in AR
- Add missing headers configuration to exhibitor endpoint
- Unify all upstreams on 127.0.0.1 instead of localhost
- Make resolver configuraiton for agent match the DC/OS configuration
[DCOS-11947](https://mesosphere.atlassian.net/browse/DCOS-11947)
[DCOS-380](https://dcosjira.atlassian.net/browse/DCOS-380>)
=> Admin Router bump

packages/java/buildinfo.json
[DCOS-615](https://dcosjira.atlassian.net/browse/DCOS-615)
=> Bump JDK version to 1.8u121

packages/dcos-ui/buildinfo.json
- Muti-container create modal
- Many fixes to single container create flow
- Many minor UI fixes and stylistic fixes
[DCOS-9159](https://mesosphere.atlassian.net/browse/DCOS-9159)
[DCOS-13075](https://mesosphere.atlassian.net/browse/DCOS-13075)
[DCOS-12458](https://mesosphere.atlassian.net/browse/DCOS-12458)
[DCOS-12449](https://mesosphere.atlassian.net/browse/DCOS-12449)
[DCOS-12480](https://mesosphere.atlassian.net/browse/DCOS-12480)
[DCOS-11754](https://mesosphere.atlassian.net/browse/DCOS-11754)
[DCOS-12971](https://mesosphere.atlassian.net/browse/DCOS-12971)
[DCOS-13018](https://mesosphere.atlassian.net/browse/DCOS-13018)
[DCOS-12740](https://mesosphere.atlassian.net/browse/DCOS-12740)
[DCOS-12741](https://mesosphere.atlassian.net/browse/DCOS-12741) …
=> Bump dcos-ui for 1.9

packages/dcos-ui/buildinfo.json
- Fixes scrollbar bug in Universe page
- Minor fixes on Jobs create form
[DCOS-11781](https://mesosphere.atlassian.net/browse/DCOS-11781)
[DCOS-11482](https://mesosphere.atlassian.net/browse/DCOS-11482)
[DCOS-11887](https://mesosphere.atlassian.net/browse/DCOS-11887)
[DCOS-9310](https://mesosphere.atlassian.net/browse/DCOS-9310)
[DCOS-11599](https://mesosphere.atlassian.net/browse/DCOS-11599)
=> Bump dcos-ui package for 1.8.8

test_util/test_upgrade_vpc.py
This PR adds a missing ticket reference to a comment. Followup from #1105.
- [DCOS-13426](https://mesosphere.atlassian.net/browse/DCOS-13426) Unable to resolve application DNS names during 1.8 to 1.9 upgrade
=> Reference ticket in DNS upgrade failure comment

packages/dcos-ui/buildinfo.json
* Allows revert of marathon configuration through the UI
- https://mesosphere.atlassian.net/browse/DCOS-13243
___ …
=> Bump dcos-ui 1.8.8

packages/metronome/buildinfo.json
Bumped metronome version 0.2
None
=> Bumped metronome version to 0.2

packages/marathon/buildinfo.json
Bugfix version: handle dependencies correctly.
=> Use Marathon 1.3.9

packages/dcos-ui/buildinfo.json
Fixes network type switching in service create form.
- https://mesosphere.atlassian.net/browse/DCOS-11559
- https://mesosphere.atlassian.net/browse/DCOS-13530
=> Bump dcos-ui package for 1.8

packages/dcos-integration-test/extra/test_applications.py, test_util/marathon.py
- tests for UCR container deployment
- tests http health check on UCR
[DCOS-9437](https://mesosphere.atlassian.net/browse/DCOS-9437)
...
- [x ] Included a test which will fail if code is reverted but test is not
- [ x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)
=> added ucr deployment with healthcheck

packages/dcos-integration-test/extra/test_mesos.py
Add mesos files API test to make sure sandbox files stdout/stderr are being populated.
- [DCOS-12875](https://mesosphere.atlassian.net/browse/DCOS-12875)
___
It is best to …
=> add mesos files api integration test

dcos_installer/config.py, gen/__init__.py, gen/calc.py, gen/internals.py, pkgpanda/__init__.py, pkgpanda/actions.py, pkgpanda/build/__init__.py, pkgpanda/util.py, release/__init__.py, test_util/installer_api_test.py
This PR contains fixes for small issues I discovered while working on #1066.
- [DCOS-10453](https://mesosphere.atlassian.net/browse/DCOS-10453) Add late binding config support to pkgpanda
=> Assorted tooling fixes

docs/admin-ports.md, gen/azure/cloud-config.yaml, gen/calc.py, gen/dcos-config.yaml, packages/3dt/build, packages/adminrouter/extra/dcos-adminrouter-agent.service, packages/adminrouter/extra/dcos-adminrouter.service, packages/cosmos/build, packages/dcos-history/extra/dcos-history.service, packages/dcos-oauth/extra/dcos-oauth.service, packages/dcos-signal/extra/dcos-signal.service, packages/erlang/build, packages/exhibitor/extra/dcos-exhibitor.service, packages/logrotate/extra/dcos-logrotate-agent.service, packages/logrotate/extra/dcos-logrotate-master.service, packages/marathon/build, packages/mesos-dns/build, packages/mesos-dns/buildinfo.json, packages/mesos-dns/extra/dcos-mesos-dns.service, packages/metronome/build, packages/minuteman/buildinfo.json, packages/navstar/build, packages/navstar/buildinfo.json, packages/pkgpanda-api/extra/dcos-pkgpanda-api.service, packages/rexray/extra/dcos-rexray.service, packages/spartan/extra/dcos-spartan.service, tests/test_installer_backend.py
1.8.8 train with:
#1200
#1197
#1195
#1194
#1193
#1174
___
=> 1.8.8 train-1

gen/dcos-config.yaml, packages/cosmos/build
Backport of https://github.com/dcos/dcos/pull/1134
https://dcosjira.atlassian.net/browse/DCOS-613
___
It is best to proactively ask for 2 reviews by @mentioning the candidate …
=> Cosmos loopback

gen/azure/cloud-config.yaml, packages/3dt/build, packages/adminrouter/extra/dcos-adminrouter-agent.service, packages/adminrouter/extra/dcos-adminrouter.service, packages/cosmos/build, packages/dcos-history/extra/dcos-history.service, packages/dcos-oauth/extra/dcos-oauth.service, packages/dcos-signal/extra/dcos-signal.service, packages/erlang/build, packages/exhibitor/extra/dcos-exhibitor.service, packages/logrotate/extra/dcos-logrotate-agent.service, packages/logrotate/extra/dcos-logrotate-master.service, packages/marathon/build, packages/mesos-dns/extra/dcos-mesos-dns.service, packages/metronome/build, packages/navstar/build, packages/pkgpanda-api/extra/dcos-pkgpanda-api.service, packages/rexray/extra/dcos-rexray.service, packages/spartan/extra/dcos-spartan.service
Backport of:
- relevant parts of https://github.com/dcos/dcos/pull/1170
- https://github.com/dcos/dcos/pull/1181
- [DCOS-625](https://dcosjira.atlassian.net/browse/DCOS-625) Explicit file descriptor limits for all DC/OS services
___ …
=> Fd limits 1.8.8

gen/dcos-config.yaml, packages/mesos-dns/build, packages/mesos-dns/buildinfo.json
Backport of https://github.com/dcos/dcos/pull/1188
=> Backport of mesos-dns fix (PR #1188)

packages/minuteman/buildinfo.json, packages/navstar/buildinfo.json
Updates navstar and minuteman which has a fix wherein lashup was timing out on start of marathon-lb 
- [DCOS-13430](https://dcosjira.atlassian.net/browse/DCOS-13430) Navstar crash after installing marathon-lb (DCOS 1.8.7).
___ …
=> upgrade navstar and minuteman

packages/dcos-ui/buildinfo.json
Removes 2s and 10s timeouts
- [DCOS-13692](https://mesosphere.atlassian.net/browse/DCOS-13692)
=> Bump dcos-ui for 1.8.8

dcos_installer/backend.py, dcos_installer/cli.py, dcos_installer/config_util.py, dcos_installer/test_backend.py, dcos_installer/test_cli.py, dcos_installer/upgrade.py, test_util/cluster.py, test_util/dcos_api_session.py, test_util/installer_api_test.py, test_util/test_upgrade_vpc.py
Introducing a new upgrade script using pkgpanda commands. More details at 
https://mesosphere.atlassian.net/browse/DCOS-11435
https://mesosphere.atlassian.net/browse/DCOS-11437
[DCOS-11435](https://mesosphere.atlassian.net/browse/DCOS-11435)
...
=> Generate node upgrade script

packages/dcos-integration-test/extra/test_networking.py, packages/navstar/buildinfo.json, packages/navstar/extra/dcos-navstar.service, test_util/marathon.py
Fixes a bug in minuteman routes that prevents VIPs from working in bridge mode.
- [DCOS-13228](https://mesosphere.atlassian.net/browse/DCOS-13228) TRACKING: dcosjira-13228, VIPs are not working in bridge mode
Added networking tests to cover every permunation of VIP
https://github.com/dcos/minuteman/compare/452b57b07d08def9a4586b6be046943785440529...fe299aa5c9e7956407643f2284c91fd2c52ac955
https://github.com/dcos/navstar/compare/4ef753e175a93adc597827aa28a836e43b8ccf3d...439b52afd04cd0614d52b9c80c18835fcf916cf2
https://circleci.com/gh/dcos/minuteman/424?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source= …
=> Update navstar to fixed ipvs

packages/dcos-ui/buildinfo.json
Bug fixes for 1.9
- [DCOS-12872](https://jira.mesosphere.com/browse/DCOS-12872)
- [DCOS-12416](https://jira.mesosphere.com/browse/DCOS-12416)
- [DCOS-13017](https://jira.mesosphere.com/browse/DCOS-13017)
- [DCOS-13340](https://jira.mesosphere.com/browse/DCOS-13340)
- [DCOS-11968](https://jira.mesosphere.com/browse/DCOS-11968)
- [DCOS-12608](https://jira.mesosphere.com/browse/DCOS-12608)
- [DCOS-13773](https://jira.mesosphere.com/browse/DCOS-13773)
- [DCOS-13362](https://jira.mesosphere.com/browse/DCOS-13362)
- [DCOS-12890](https://jira.mesosphere.com/browse/DCOS-12890)
- [DCOS-12589](https://jira.mesosphere.com/browse/DCOS-12589)
- [DCOS-13661](https://jira.mesosphere.com/browse/DCOS-13661)
- [DCOS-13579](https://jira.mesosphere.com/browse/DCOS-13579)
- …
=> Bump dcos-ui package

packages/erlang/build, packages/erlang/buildinfo.json, packages/navstar/buildinfo.json, packages/navstar/extra/dcos-navstar.service, packages/spartan/buildinfo.json
This patch fixes three issues:
1. Erlang crash whenever hostname was 64 characters long which disallowed spartan, navstar, minuteman from starting
2. Mesos_state parser error whenever network protocol or type was in capital. For instance, TCP/UDP or BRIDGE/HOST instead of tcp/udp or bridge/host
3. Minuteman issue in which backends were not removed when the tasks died if the backends were on overlay network 
- [DCOS-13478](https://jira.mesosphere.com/browse/DCOS-13478) Spartan crashes when calling 'set_hostname()' with long hostnames.
- [DCOS-12154](https://jira.mesosphere.com/browse/DCOS-12154) Minuteman: Failed to parse task
- [DCOS-13273](https://jira.mesosphere.com/browse/DCOS-13273) Failed to parse task error in navstar logs
- …
=> upgrade networking components

packages/dcos-integration-test/extra/test_ec2.py
The `test_move_external_volume_to_new_agent` test has been flaky for a long time. This is primarily due to volume actions (create, mount, attach, detach, destroy) taking anything from seconds to several minutes on EC2.
This test increases the timeouts to 10 minutes to reduce the number of failures due to infrastructure flakiness. Whether this reduces the number of failures to zero remains to be seen. 
- [DCOS-13562](https://jira.mesosphere.com/browse/DCOS-13562) Integration tests: test_move_external_volume_to_new_agent fails in strict mode	
___
=> dcos-integration-test: bump timeouts in test_move_external_volume_to_new_agent

packages/metronome/buildinfo.json
Bugfix Release
- https://github.com/dcos/metronome/issues/100
___ …
=> Bump metronome to 0.2.1

packages/dcos-ui/buildinfo.json
Bug fixes for 1.9
- [DCOS-13152](https://jira.mesosphere.com/browse/DCOS-13152)
- [DCOS-13974](https://jira.mesosphere.com/browse/DCOS-13974)
- [DCOS-397](https://jira.mesosphere.com/browse/DCOS-397)
- [DCOS-13910](https://jira.mesosphere.com/browse/DCOS-13910)
___
* …
=> Bump dcos-ui 1.9

packages/adminrouter/buildinfo.json
https://github.com/dcos/adminrouter/pull/52
https://jira.mesosphere.com/browse/DCOS-14109
=> Allow for passing X-Accel-Buffering header to upstream proxies in AR

gen/calc.py
* `curl`/`libcurl` doesn't work with `*.`
* Add `.thisdcos.directory` & `.dcos.directory` to `no_proxy` or Minuteman Named VIPs won't be accessible over `http(s)://` within the DC/OS cluster
* Add `.zk` to `no_proxy` to access, for example, `http://zk-1.zk:8121` within the DC/OS cluster.
- [DCOS_OSS-664](https://jira.mesosphere.com/browse/DCOS_OSS-664) no_proxy defaults must not contain "*." and should also contain "l4lb.thisdcos.directory"
___ …
=> Fix for DCOS_OSS-664

packages/navstar/buildinfo.json, packages/spartan/buildinfo.json
Updated networking components for fixes observed in soak_cluster in 1.9-rc1
- [DCOS-14149](https://jira.mesosphere.com/browse/DCOS-14149) Empty container_status in task protobuf causes crash in mesos_state parser
- [DCOS-14121](https://jira.mesosphere.com/browse/DCOS-14121) HTTP frameworks in soak cluster is causing navstar crashes
- [DCOS-14201](https://jira.mesosphere.com/browse/DCOS-14201) minuteman module minuteman_lb_mgr crashes
- [DCOS-14012](https://jira.mesosphere.com/browse/DCOS-14012) upgrade rebar3 to latest
https://github.com/dcos/mesos_state/pull/27
https://github.com/dcos/minuteman/pull/88 …
=>  upgrade networking components

dcos_installer/upgrade.py
Assorted fixes for the upgrade script. See commits.
* Exit with error status on Exhibitor migration failure
* Suppress Exhibitor migration script stdout
* Clearer and more accurate shell output
* Style tweaks
- [DCOS-14046](https://jira.mesosphere.com/browse/DCOS-14046) Upgrade Procedure for 1.9 Findings
=> Assorted upgrade script fixes

packages/dcos-ui/buildinfo.json
Bug fixes for 1.9
- [DCOS-13960](https://jira.mesosphere.com/browse/DCOS-13960])
- [DCOS-13474](https://jira.mesosphere.com/browse/DCOS-13474])
- [DCOS-12423](https://jira.mesosphere.com/browse/DCOS-12423])
- [DCOS-12713](https://jira.mesosphere.com/browse/DCOS-12713])
- [DCOS-13451](https://jira.mesosphere.com/browse/DCOS-13451])
- [DCOS-12416](https://jira.mesosphere.com/browse/DCOS-12416])
@MatApple & @jfurrow - could you guys please review?
=> Bump dcos-ui package for 1.9

cloud_images/CHANGELOG.md, cloud_images/centos7/install_prereqs.sh, gen/build_deploy/aws.py, packages/adminrouter/extra/systemd/dcos-adminrouter.service
This is a cherry-pick of:
#1277 
#1258
#1279
#1306
=> Bump CoreOS, CentOS, Docker

gen/dcos-config.yaml, packages/dcos-integration-test/extra/test_3dt.py
This change adds a few more files from master node to a diagnostics bundle.These files come in handy for support debugging various issues
Enterprise PR https://github.com/mesosphere/dcos-enterprise/pull/576
- [DCOS-13706](https://mesosphere.atlassian.net/browse/DCOS-13706) 
___ …
=> Added a few more files to diagnostics bundle for support

packages/adminrouter/build, packages/adminrouter/docker/Dockerfile
@adam-mesos 
This fixes small spelling/formatting mistakes you pointed out yesterday in:
https://github.com/dcos/dcos/pull/1303#pullrequestreview-24537206
https://github.com/mesosphere/dcos-enterprise/pull/645#pullrequestreview-24538813
plus backports some small quoting fix that was preset only in EE AR.
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/656
=> Spelling fixes for AdminRouter repository

packages/cosmos/buildinfo.json
Three improvements to cosmos:
1. Prevent the `/package/list` endpoint responding with status 400 when a deployed service's package is not present in its origin repository (https://github.com/dcos/cosmos/pull/563).
1. Add an optional command-line flag to configure the maximum acceptable HTTP response size from services that cosmos makes API calls to (https://github.com/dcos/cosmos/pull/569).
1. Log all HTTP requests cosmos makes to package repositories (https://github.com/dcos/cosmos/pull/573).
Respectively:
1. [DCOS-13213](https://jira.mesosphere.com/browse/DCOS-13213)
1. [DCOS-13595](https://jira.mesosphere.com/browse/DCOS-13595)
1. [DCOS-10270](https://jira.mesosphere.com/browse/DCOS-10270) …
=> Update cosmos to version 0.3.0

packages/dcos-log/buildinfo.json
Consolidate dcos-log auth middleware: remove cookie handling, do not partially validate JWT
- [DCOS-12011](https://jira.mesosphere.com/browse/DCOS-12011) 
A minor code refactor which does not have any impact on functionality.
___ …
=> bump dcos-log sha

dcos_installer/action_lib.py, dcos_installer/async_server.py, ssh/runner.py
ssh_port in DC/OS installer config was not connected to the SSH runner
https://jira.mesosphere.com/browse/DCOS_OSS-325
=> Connect config's ssh port to MultiRunner

owners.json
Folks in owners.json can issue commands to mergebot. We need to include the repo admins to owners.json too. Including adam in this change.
- NA
=> Add adam to owners.json

test_util/aws.py, test_util/test_aws_vpc.py
This allows a client of `test_util/test_aws_vpc.py` to specify the AMI from which cluster nodes are launched.
- [DCOS_OSS-668](https://jira.mesosphere.com/browse/DCOS_OSS-668) Parameterize AMI in AWS onprem test
=> Parameterize AMI used in AWS VPC integration tests

gen/build_deploy/util.py
=> Fix intended exception

packages/marathon/buildinfo.json
Upgrades Marathon to 1.4.2-snapshot2 (candidate) which has the correct version.
- [MARATHON-4570](https://jira.mesosphere.com/browse/MARATHON-4570) Don't destroy persistent volumes when killing unreachable tasks
- [MARATHON-4390](https://jira.mesosphere.com/browse/MARATHON-4390) Lazy event parsing
- Improve health checks to log less warnings.
- [MARATHON-1712](https://jira.mesosphere.com/browse/MARATHON-1712) Loosen SSL requirements for HTTPS health checks.
- [MARATHON-1408](https://jira.mesosphere.com/browse/MARATHON-1408) Fix serialization of maxSize for persistent volumes.
- [MARATHON-2311](https://jira.mesosphere.com/browse/MARATHON-2311) Publish a TASK_GONE mesos update when an unreachable instance's resources are seen.
- [MARATHON-1682](https://jira.mesosphere.com/browse/MARATHON-168 …
=> Upgrade marathon to 1.4.2-snapshot2

packages/metronome/buildinfo.json
Bugfix Release
- https://jira.mesosphere.com/browse/DCOS-14228
___ …
=> Updated metronome version to 0.2.2

packages/dcos-integration-test/extra/test_metrics.py
Fixes a race condition where container state has not yet propagated to the metrics service which queries agent state for container every two minutes. 
___
It is best to …
=> Metrics retry logic

packages/marathon/buildinfo.json
Upgrades Marathon to 1.4.2-snapshot2 (candidate) which has the correct version.
Changes from 1.4.1 to 1.4.2-snapshot3
- [MARATHON-4570](https://jira.mesosphere.com/browse/MARATHON-4570) Don't destroy persistent volumes when killing unreachable tasks
- [MARATHON-4390](https://jira.mesosphere.com/browse/MARATHON-4390) Lazy event parsing
- Improve health checks to log less warnings.
- [MARATHON-1712](https://jira.mesosphere.com/browse/MARATHON-1712) Loosen SSL requirements for HTTPS health checks.
- [MARATHON-1408](https://jira.mesosphere.com/browse/MARATHON-1408) Fix serialization of maxSize for persistent volumes.
- [MARATHON-2311](https://jira.mesosphere.com/browse/MARATHON-2311) Publish a TASK_GONE mesos update when an unreachable instance's resources are seen.
- …
=> Upgrade Marathon to 1.4.2-snapshot3

test_util/cluster.py, test_util/test_upgrade_vpc.py
Refactor the upgrade tests to clean up cluster.py. Add option for acs token
DCOS-14031
https://jira.mesosphere.com/browse/DCOS-14031
___ …
=> Add acs token to test upgrades

gen/azure/cloud-config.yaml, packages/dcos-integration-test/extra/test_service_discovery.py, test_util/marathon.py
This adds tests for the various DNS records generated by Navstar in the various container configurations.
- N/A
___ …
=> Add DNS Tests

packages/mesos-modules/buildinfo.json, packages/mesos/README.md, packages/mesos/buildinfo.json
Bumps dcos-mesos to the Apache Mesos 1.2.x branch to include such critical fixes as:
```
356cf67 Fixed ContainerLogger / IOSwitchboard FD leaks.
9c0bbf1 Removed redundant 'root' user set in containerizer::launch().
0f3a68d Fixed command task with container image 'root' user issue.
801cdfa Added ability to dynamically load '/dev/nvidia-uvm' in GPU isolator.
dc498b7 Ensured the cgroup memory+swap limit is no less than the memory limit.
12890ba Fixed flags logging in Docker executor.
d6b3440 Fixed crash with tasks that use very small resource values.
89d141c Docker environment gets passed on docker run command.
62a8551 Removed containerizer flag logging to prevent leak of sensitive data.
f62f570 Fixed environment overwrite warning to not leak possibly sensitive data.
```
- …
=> Bump Mesos to the 1.2.x branch and bump Mesos modules to include ContainerLogger changes.

packages/dcos-ui/buildinfo.json
Fixes following issues:
- Universal Container Runtime shows Experimental in UI (It's Preview)
- Can't launch service
- Framework resources are not being aggregated correctly
- [DCOS-14743](https://jira.mesosphere.com/browse/DCOS-14743])
- [DCOS-14733](https://jira.mesosphere.com/browse/DCOS-14733])
- [DCOS-14456](https://jira.mesosphere.com/browse/DCOS-14456])
- [DCOS-13209](https://jira.mesosphere.com/browse/DCOS-13209])
- [DCOS-14120](https://jira.mesosphere.com/browse/DCOS-14120])
- [DCOS-14707](https://jira.mesosphere.com/browse/DCOS-14707])
- [DCOS-14699](https://jira.mesosphere.com/browse/DCOS-14699])
- [DCOS-14527](https://jira.mesosphere.com/browse/DCOS-14527])
- [DCOS-13032](https://jira.mesosphere.com/browse/DCOS-13032])
Plugins
- …
=> Bump for dcos-ui package for 1.9

packages/navstar/buildinfo.json, packages/spartan/buildinfo.json
This commit fixes following issues.
1. navstar failure in 1k nodes cluster
2. corruption of crypto cluster id
3. Improves logging by including pid, module, function and line number in log message
4. minuteman udp support
- [DCOS_OSS-796](https://jira.mesosphere.com/browse/DCOS_OSS-796) navstar unhealthy in 1k node cluster.
- [DCOS_OSS-720](https://jira.mesosphere.com/browse/DCOS_OSS-720) Cryptographic Cluster ID is longer than ~50chars
- [DCOS_OSS-804](https://jira.mesosphere.com/browse/DCOS_OSS-804) Improve logging of networking component
- [DCOS_OSS-812](https://jira.mesosphere.com/browse/DCOS_OSS-812) minuteman crashes for non-tcp protocol
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the …
=> upgrade spartan and navstar to improve the logging

packages/marathon/buildinfo.json
Exactly the same as 1.4.2-snapshot5
N/A
___
=> Upgrade marathon to 1.4.2

packages/adminrouter/extra/src/README.md
This PR documents the authorizer code in Admin Router
- [DCOS-14584](https://jira.mesosphere.com/browse/DCOS-14584) Admin Router: Documentation for auth.lua and friends
This PR should be merged together with https://github.com/mesosphere/dcos-enterprise/pull/766
=> Admin Router: Auth[n|z] documentation

packages/dcos-launch/extra/launch/azure.py
The DCOS_DNS input variable should be master load balancer as was originally coded here, however, Azure currently needs an update for that load balancer address to actually route HTTP traffic to masters. In the meanwhile, this code is modified to route directly to the zero-th master
https://jira.mesosphere.com/browse/DCOS-14627
___
=> Patch dcos-launch pytest for azure

packages/dcos-integration-test/extra/util/delete_ec2_volume.py
The `test_ec2.test_move_external_volume_to_new_agent` waits for the volume to detach before deleting it. This has been observed to take several minutes, causing the cleanup step to timeout and the EBS volume to become orphaned.
This PR forces the volume to detach before attempting to delete it.
- [DCOS-6357](https://jira.mesosphere.com/browse/DCOS-6357) External volume integration test fails to clean up volume
___
=> Force detach volume after test

dcos_installer/upgrade.py
Trap ERR on the Upgrade Script and show more information and why the upgrade failed
- [DCOS_OSS-839](https://jira.dcos.io/browse/DCOS_OSS-839)
=> Trap ERR on Upgrade Script.

mergebot-config.json
* PR creators and Owners can ask mergebot add label to a PR.
- [DCOS-14379](https://jira.mesosphere.com/browse/DCOS-14379) - Delegate Issue label application via mergebot
=> Update mergebot config for labels.

dcos_installer/cli.py
Update genconf help strings.
- [DCOS_OSS-561](https://jira.dcos.io/browse/DCOS_OSS-561) Unhelpful help text for `--genconf` argument
- [DCOS_OSS-562](https://jira.mesosphere.com/browse/DCOS_OSS-562) Bad help text for `--install-prereqs`
**n/a**
~~If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:~~
- ~~[ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)~~
- ~~[ ] Test Results: [link to CI job test results for component]~~
- ~~[ ] Code Coverage (if available): …
=> more useful parameter help

packages/3dt/buildinfo.json
3dt refactor and vendor folder update.
[DCOS-14886](https://jira.mesosphere.com/browse/DCOS-14886)
existing integration tests should be enough to cover this refactor.
___
It is …
=> 3dt refactor

README.md
Updating docs to match what I had to do to get DCOS successfully built locally.
- [DCOS_OSS-884](https://jira.mesosphere.com/browse/DCOS_OSS-884) Update dcos/dcos setup instructions
**N/A**
~~If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:~~
- ~~[ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)~~
- ~~[ ] Test Results: [link to CI job test results for component]~~
- ~~[ ] Code Coverage (if available): [link to code coverage report]~~
=> updated build docs

docs/styleguides/python.md
Python Style Guide proposal for DCOS Code base.
Readable Version: https://github.com/orsenthil/dcos/blob/style_guide/docs/styleguides/python.md 
- [DCOS_OSS-886](https://jira.dcos.io/browse/DCOS_OSS-886) Create style guide documentation for community in dcos/dcos
- [DCOS-14924](https://jira.mesosphere.com/browse/DCOS-14924) Define and adopt a python style guideline for dcos/dcos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dcos/dcos/1439)
=> Proposal: Python Style Guide for DCOS

gen/dcos-config.yaml, packages/bootstrap/extra/dcos_internal_utils/cli.py, packages/dcos-integration-test/extra/test_networking.py, packages/navstar/buildinfo.json, packages/navstar/extra/dcos-navstar.service, packages/navstar/extra/setup_iptables.sh
Fixes two issues
1. merges the minuteman code to navstar as navstar_l4lb
2. fixes iptables which were mangled by docker 1.12+
- [DCOS_OSS-902](https://jira.mesosphere.com/browse/DCOS_OSS-902) move minuteman code to navstar
- [DCOS_OSS-980](https://jira.mesosphere.com/browse/DCOS_OSS-980) docker 1.12+ breaks virtual network
https://github.com/dcos/navstar/pull/64
___ …
=> merges minuteman code to navstar as navstar_l4lb

packages/dcos-launch/extra/README.md, packages/dcos-launch/extra/launch/sample_configs/README.md
This PR was accidentally closed and had trouble being reopened due to a force push.
https://github.com/dcos/dcos/pull/1455
=> Add dcos-launch user guide

test_util/aws.py
- no longer overrides inherited delete function with effectively identical function
- fetch_stack never assumes BareClusterStack; instead assumes generic stack and selectively picks BareClusterStack
https://jira.mesosphere.com/browse/DCOS-13299
=> Cleanup BareClusterStack

pkgpanda/docker/dcos-builder/Dockerfile
Update to base builder image to golang 1.8.1
- [DCOS_OSS-986](https://jira.mesosphere.com/browse/DCOS_OSS-986)
Current set of tests must be sufficient
___
It is best to …
=> dcos-builder: update base image to golang 1.8.1

gen/calc.py, gen/dcos-config.yaml, gen/tests/test_validation.py, gen/tests/utils.py, packages/spartan/buildinfo.json
Adds a blacklist to the ips that spartan will bind on. This can be used on masters to allow for something like dnsmasq to run without sacrificing other functionality.
Also adds a way to delegate zones to different resolvers.
- [DCOS-15214](https://jira.mesosphere.com/browse/DCOS-15214)
- [DCOS-15310](https://jira.mesosphere.com/browse/DCOS-15310)
___
All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-revi …
=> spartan: Add bind ip blacklist and forward zones

packages/mesos/README.md, packages/mesos/buildinfo.json, test_util/marathon.py, test_util/test_upgrade_vpc.py
This PR:
* updates the Mesos package to a branch based on latest Mesos master
* updates tests to accommodate Mesos changes
* updates the Mesos package README with new cherry-pick SHAs
___
* Developers responsible for code that interacts with or depends on the code being …
=> Bumped Mesos to latest master.

packages/cosmos/buildinfo.json
This updates cosmos to version 0.2.1, which backports the bugfix to the `/package/list` endpoint from this PR: https://github.com/dcos/cosmos/pull/563.
This should be merged at the same time as the corresponding downstream Enterprise PR: https://github.com/mesosphere/dcos-enterprise/pull/807
- [DCOS-15077](https://jira.mesosphere.com/browse/DCOS-15077) Backport handling the case when a service from a package is running but the package doesn't exist
___ …
=> Update cosmos to version 0.2.1, for 1.8.9

packages/dcos-metrics/buildinfo.json
This includes the fix for DCOS_OSS-925 (metrics endpoint
sometimes returns a `null` datapoints property).
cc @amitaekbote 
- [DCOS_OSS-<number>](https://jira.dcos.io/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.
- [DCOS-<number>](https://jira.mesosphere.com/browse/DCOS-<number>) Foo the Bar so it stops Bazzing.
___ …
=> Point to 1.9.1 branch of dcos-metrics.

pkgpanda/build/cli.py, pkgpanda/cli.py
Currently pkgpanda exceptions go to stdout. This resulted in upgrade script not printing errors. Changing print in pkgpanda to go to stderr in case of exceptions. 
https://jira.mesosphere.com/browse/DCOS-15302
___
* Developers responsible for code that interacts with or …
=> Print pkgpanda exceptions to stderr

packages/adminrouter/build, packages/adminrouter/buildinfo.json, packages/adminrouter/extra/adminrouter.sh, packages/adminrouter/extra/dcos-adminrouter-agent-reload.service, packages/adminrouter/extra/dcos-adminrouter-agent.service, packages/adminrouter/extra/dcos-adminrouter-reload.service, packages/adminrouter/extra/dcos-adminrouter.service, packages/dcos-history/extra/history/server.py, packages/minuteman/build, packages/minuteman/buildinfo.json, packages/navstar/buildinfo.json
Train 162 for 1.8.9 :steam_locomotive: 
Includes:
#1453 Bump networking components
#1532 Make AdminRouter route to history-service backend, conditionally
=> [1.8.9] Train 162

packages/minuteman/build, packages/minuteman/buildinfo.json, packages/navstar/buildinfo.json
This patch backports some of the mesos state parser fixes that many customers have reported.
- [DCOS_OSS-927](https://jira.mesosphere.com/browse/DCOS_OSS-927) Backport fix for mesos state parser to 1.8.x
https://github.com/dcos/minuteman/pull/104
https://github.com/dcos/minuteman/pull/109
https://github.com/dcos/navstar/pull/62
___
Reviewers …
=> Bump networking components for 1.8.9

README.md, packages/adminrouter/extra/src/README.md
Fixes some broken links in the Adminrouter README, and a small typo in the DC/OS README.
- [-] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: just a docs change.
___
=> Update readme links

packages/cosmos/buildinfo.json, packages/dcos-integration-test/extra/test_endpoints.py
* Changes package/install to store the configuration used to run a package.
* Adds support for v4 packages and v4 universe.
* Implements service/describe endpoint
* Fixes proxy bug
- [DCOS-15545](https://jira.mesosphere.com/browse/DCOS-15545) Despite `.mesos` being present in `no_proxy`, Cosmos makes requests to http://master.mesos:8082/repo through the proxy
___ …
=> Update Cosmos to latest version

gen/dcos-config.yaml, packages/dcos-ui/buildinfo.json, packages/marathon/buildinfo.json, packages/mesos/README.md, packages/mesos/buildinfo.json, packages/metronome/buildinfo.json
:steam_locomotive: Train 165 for DC/OS 1.8.9
#1479 Metronome 0.2.3 bump
#1482 UI bump
#1563 Marathon 1.3.11 bump
#1567 Mesos cherry-pick bump
Backported #1499 Mesos master/agent logrotation
=> [1.8.9] Train 165

packages/metronome/buildinfo.json
Security fix for Cross-Site Scripting Vulnerabilities
- [DCOS-14866](https://jira.mesosphere.com/browse/DCOS-14866) Cross-Site Scripting Vulnerabilities
=> [DCOS 1.8.9] Use metronome 0.2.3

packages/dcos-ui/buildinfo.json
* Fixes some packages not showing up in the Universe UI
* Manual VIP label overwritten in JSON
- [DCOS-11781](https://jira.mesosphere.com/browse/DCOS-11781])
- [DCOS-10426](https://jira.mesosphere.com/browse/DCOS-10426])
___ …
=> Bump dcos-ui for 1.8.9

packages/marathon/buildinfo.json
Bug fix release addressing recent performance issues.
- dfddf50 Use the latest stable Marathon UI build (1.1.7) (#5180)
See also: https://github.com/mesosphere/marathon/commits/releases/1.3
https://github.com/mesosphere/marathon/releases/v1.3.11
=> Marathon 1.3.11 in DC/OS 1.8.9

packages/marathon/buildinfo.json
https://github.com/mesosphere/marathon/releases/tag/v1.4.3
Bugfix release
Bugfix release
- [MARATHON-7267](https://jira.mesosphere.com/browse/MARATHON-7267) Enforce validation for pod container names
- [DCOS-14890] Fix default scheme for HTTP health checks in pods
- [DCOS-14303] Fix issue in which Marathon would fail to launch if hostname is not resolvable (but still specified from the command line)
___ …
=> Upgrade Marathon to 1.4.3

packages/adminrouter/extra/src/docs/api/nginx.agent.html, packages/adminrouter/extra/src/docs/api/nginx.agent.yaml, packages/adminrouter/extra/src/nginx.agent.conf
Adding dcos version endpoint to agent
Cluster check 
___ …
=> Admin Router: Adding version endpoint to agent

dcos_installer/exhibitor_migrate.py, dcos_installer/upgrade.py, gen/calc.py, gen/dcos-config.yaml, packages/dcos-integration-test/extra/api_session_fixture.py, packages/dcos-integration-test/extra/test_endpoints.py, packages/dcos-launch/buildinfo.json, packages/navstar/buildinfo.json, packages/navstar/extra/setup_iptables.sh, test_util/dcos_api_session.py
* #1431 - Bump networking components for 1.9.1
* #1559 - Authenticate requests to Exhibitor during upgrade
=> (1.9.1) train-166

packages/adminrouter/docker/requirements-tests.txt, packages/adminrouter/extra/src/lib/service.lua, packages/adminrouter/extra/src/pytest.ini, packages/adminrouter/extra/src/test-harness/modules/mocker/dns.py, packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/basehandler.py, packages/adminrouter/extra/src/test-harness/modules/mocker/endpoints/generic.py, packages/adminrouter/extra/src/test-harness/modules/runner/common.py, packages/adminrouter/extra/src/test-harness/modules/util.py, packages/adminrouter/extra/src/test-harness/tests/conftest.py, packages/adminrouter/extra/src/test-harness/tests/test_common.py
This PR:
* reduces the verbosity of logs produced by Admin Router
* fix resource leaks of the test harness
* fixes some deprecation warnings
* bumps pytest framework to 3.1
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/962
=> Admin Router: Logging tunning, fix test-harness resource leaks

packages/dcos-ui/buildinfo.json
- Can't delete CMD in UI or JSON editor
- Correct pod definition gives error
- Environment vars for Pods are broken
- Volumes size should say GiB not MiB
- Declined offers showing NaN for resource offer received
- Environment variable set to "null" if populating only the value
- Rename Remove/Destroy anywhere in the UI to “Delete”
- Zeppelin package is gone from Universe in UI
- Incorrect Resource Reporting
- Support host volume for Pods in DC/OS UI.
- Labels (certified, community) to the Universe View
- Declined offers debug information doesn't show until 5minutes
- Write integration tests for the Sidebar
- Provide names for service paths
- Automate "Create an app with HTTP health check (via UI)" Test
- Automate "Create a pod with multiple containers (via UI)" Test
- Automate "Create an …
=> bump(DCOS-UI): latest bits

packages/cosmos/buildinfo.json
Update the uninstall endpoint to correctly uninstall sdk services. Update the service/describe endpoint to leave userProvidedOptions and resolvedOptions empty.
- [DCOS_OSS-1112](https://jira.mesosphere.com/browse/DCOS_OSS-1112) Don't Reveal User Config.
- [DCOS-15235](https://jira.mesosphere.com/browse/DCOS-15235) Change uninstall endpoint to update app definition for sdk services
___ …
=> Update DC/OS to the latest cosmos

packages/cosmos/build, packages/cosmos/buildinfo.json, packages/dcos-ui/buildinfo.json, packages/marathon/buildinfo.json, packages/mesos/README.md, packages/mesos/buildinfo.json
https://github.com/dcos/dcos/pull/1570
https://github.com/dcos/dcos/pull/1581
https://github.com/dcos/dcos/pull/1582
https://github.com/dcos/dcos/pull/1584
https://github.com/dcos/dcos/pull/1594
=> 1.8.9 train 166

packages/dcos-ui/buildinfo.json
Fix incorrect rounding of resource allocation (dashboard).
- [DCOS-12054](https://jira.mesosphere.com/browse/DCOS-12054): Fix incorrect rounding of resource allocation
___
It is …
=> Bump DC/OS UI version (1.8.9)

packages/cosmos/buildinfo.json
This change for DC/OS 1.8.9 updates cosmos to [version 0.2.2](https://github.com/dcos/cosmos/releases/tag/v0.2.2), which backports https://github.com/dcos/cosmos/pull/625 to the 0.2.x release series.
Corresponding EE PR: https://github.com/mesosphere/dcos-enterprise/pull/952
- [DCOS-15545](https://jira.mesosphere.com/browse/DCOS-15545): the original bug
- [DCOS-15483](https://jira.mesosphere.com/browse/DCOS-15483): the JIRA for the backport
___ …
=> Bump cosmos to version 0.2.2, for 1.8.9

packages/cosmos/buildinfo.json, packages/dcos-installer-ui/buildinfo.json, packages/dcos-integration-test/extra/test_applications.py, packages/dcos-integration-test/extra/test_helpers.py, packages/dcos-ui/buildinfo.json, packages/exhibitor/extra/start_exhibitor.py
This train includes the following pull requests:
* #1347
* #1497 
* #1554 
* #1556 
And master cherry-pick:
https://github.com/dcos/dcos/commit/2f389a52313a5027e368d23a9160cc17e93844d4
Downstream PR number: 977
=> [1.9.1] Train 170

packages/dcos-installer-ui/buildinfo.json
Minor bug fixes
- [DCOS-12870](https://jira.mesosphere.com/browse/DCOS-12870])
- [DCOS-9939](https://jira.mesosphere.com/browse/DCOS-9939])
- [DCOS-14984](https://jira.mesosphere.com/browse/DCOS-14984])
___
* Developers responsible for code that interacts with or depends …
=> Bumps dcos-installer-ui package for 1.9 release

packages/dcos-ui/buildinfo.json
- Can't delete CMD in UI or JSON editor
- Correct pod definition gives error
- Environment vars for Pods are broken
- Volumes size should say GiB not MiB
- Zeppelin package is gone from Universe in UI
- Incorrect Resource Reporting
- Update help text and tooltips in create flow
- "EDIT" button in services UI doesn't do anything when clicked
- Fix incorrect rounding of resource allocation
- Implement a field for a load balanced port
- Move ports auto assign checkbox at the top level
- [DCOS-14894](https://jira.mesosphere.com/browse/DCOS-14894])
- [DCOS-14842](https://jira.mesosphere.com/browse/DCOS-14842])
- [DCOS-11781](https://jira.mesosphere.com/browse/DCOS-11781])
- [DCOS-14854](https://jira.mesosphere.com/browse/DCOS-14854])
- …
=> Bump dcos-ui for 1.9.1

packages/cosmos/buildinfo.json
This change for DC/OS 1.9.1 updates cosmos to [version 0.3.1](https://github.com/dcos/cosmos/releases/tag/v0.3.1), which backports https://github.com/dcos/cosmos/pull/625 to the 0.3.x release series.
- [DCOS-15545](https://jira.mesosphere.com/browse/DCOS-15545): the original bug
- [DCOS-15483](https://jira.mesosphere.com/browse/DCOS-15483): the JIRA for the backport
___ …
=> Bump cosmos to version 0.3.1, for 1.9.1

dcos_installer/upgrade.py, gen/calc.py, gen/dcos-config.yaml, gen/dcos-services.yaml, packages/dcos-integration-test/extra/test_misc.py, packages/dcos-metrics/buildinfo.json, packages/mesos-modules/buildinfo.json, packages/mesos/README.md, packages/mesos/buildinfo.json
* #1530 
* #1574 
* #1592 
* #1597 
* #1598
=> 1.9.1 train 171

gen/calc.py, gen/dcos-config.yaml, packages/mesos/README.md, packages/mesos/buildinfo.json
- introduce a new config.yaml option `gpus_are_scarce` with default values `true`
- bump mesos to include `--filter-gpu-resources` master flag.
- [DCOS_OSS-876](https://jira.mesosphere.com/browse/DCOS_OSS-876)
- [CORE-1107](https://jira.mesosphere.com/browse/CORE-1107)
The PR does not include any integration test, since we do not have an infrastructure for integration tests with GPUs. @klueska has performed manual tests to make sure this change works as expected.
___ …
=> add a new config.yaml option gpus_are_scarce

packages/dcos-signal/buildinfo.json, packages/marathon/buildinfo.json
:steam_locomotive: 172 for DC/OS 1.9.1
#1548 dcos-signal bugfix
#1585 Marathon 1.4.3
=> 1.9.1 train 172

packages/marathon/buildinfo.json
https://github.com/mesosphere/marathon/releases/tag/v1.4.3
Bugfix release
* [MARATHON-7267](https://jira.mesosphere.com/browse/MARATHON-7267) Enforce validation for pod container names
* [DCOS-14890] Fix default scheme for HTTP health checks in pods
* [DCOS-14303] Fix issue in which Marathon would fail to launch if hostname is not resolvable (but still specified from the command line)
___ …
=> bumping marathon to 1.4.3

packages/metronome/buildinfo.json
Security fix for Cross-Site Scripting Vulnerabilities
- [DCOS-14866](https://jira.mesosphere.com/browse/DCOS-14866) Cross-Site Scripting Vulnerabilities
___
It is best to …
=> [Master] Use metronome 0.2.3

gen/calc.py, gen/dcos-config.yaml
This PR adds the `--max_completed_tasks_per_framework` Mesos master flag to `config.yaml` so that it can be set by users at install time.
___ …
=> Added 'max_completed_tasks_per_framework' Mesos flag to 'config.yaml'.

gen/build_deploy/bash/Dockerfile.in, packages/adminrouter/docker/Dockerfile, packages/dcos-image-deps/buildinfo.json
This patch is required for EE patch that will allow installing DC/OS with custom CA certificate.
- [DCOS-14898](https://jira.mesosphere.com/browse/DCOS-14898) Custom CA Certificate implementation
=> Custom CA certificate implementation

packages/dcos-integration-test/extra/test_mesos.py, packages/marathon/buildinfo.json
:steam_locomotive: 173 for 1.9.1
#1616 mesos pid namespace test bug
#1638 Marathon 1.4.4
=> 1.9.1 train 173

packages/dcos-integration-test/extra/test_mesos.py
Previously, there was a race between the `app_task` starting and it
writing its output to the `ps_output_file`. We now wait up to 10 seconds
for this file to appear before giving up and throwing an exception.
- [DCOS_OSS-862](https://jira.mesosphere.com/browse/DCOS_OSS-862) Vagrant integration test test_mesos.test_if_ucr_app_runs_in_new_pid_namespace is flaky.
___
=> Fixed bug in 'test_mesos.test_if_ucr_app_runs_in_new_pid_namespace'.

packages/cosmos/build
We don't support cosmos using proxies with NTLM authentication at this time. This change will allow Cosmos to use a different authentication scheme, such as Basic, instead of NTLM.
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/1008
- [DCOS-15096](https://jira.mesosphere.com/browse/DCOS-15096) Unable to access Universe on a cluster configured with proxy using basic auth
___ …
=> Disable NTLM proxy auth for cosmos

gen/build_deploy/aws.py, packages/marathon/buildinfo.json
:steam_locomotive: 174 for DC/OS 1.9.1
#1659 govcloud
#1662 Marathon 1.4.5
=> 1.9.1 train 174

dcos_installer/upgrade.py
Run the node and cluster checks before and after upgrade
https://jira.mesosphere.com/browse/DCOS-15924
___ …
=> Upgrade checks

packages/marathon/buildinfo.json
* Introduces file based secrets.
* MARATHON-7090 Support passing a Docker config.json for app / pod being launched.
* MARATHON-7457
* MARATHON-7468
* MARATHON-7204
* MARATHON-7430
* MARATHON-7479
* DCOS-16151
* MARATHON-7458
* MARATHON-7414
=> updating to latest marathon 1.5

packages/cosmos/buildinfo.json
Various code and test refactorings that don't change the functionality of Cosmos. This release is mainly being made to bring cosmos up to date in Enterprise DC/OS. See the corresponding Enterprise PR for more details.
- [DCOS-15635](https://jira.mesosphere.com/browse/DCOS-15635) Get rid of `PackageRunner`
- [DCOS-11808](https://jira.mesosphere.com/browse/DCOS-11808) Allow extensible Error accross projects
- [DCOS-15844](https://jira.mesosphere.com/browse/DCOS-15844) Refactor error handling in service/update
___
**What is the …
=> Update to latest cosmos snapshot

packages/minuteman/buildinfo.json, packages/navstar/buildinfo.json
:steam_locomotive: 167 for 1.8.9
#1651 navstar and minuteman bumps for 1k node cluster testing
=> 1.8.9 train 167

packages/minuteman/buildinfo.json, packages/navstar/buildinfo.json
This patch fixes navstar crash in 1k node cluster
- [DCOS_OSS-796](https://jira.mesosphere.com/browse/DCOS_OSS-796) navstar unhealthy in 1k node cluster
https://github.com/dcos/navstar/pull/82
https://github.com/dcos/minuteman/pull/113
https://github.com/dcos/lashup/compare/f2a20fa1033724cf47724e6c9d701f4dcd4b4e01...e831653c7a8eb3cb44e8ebed08c3164e31849975
___ …
=> upgrade navstar and minuteman to support 1k node cluster

gen/calc.py, gen/tests/test_validation.py, gen/tests/utils.py, packages/dcos-image-deps/build, packages/dcos-image-deps/buildinfo.json, packages/mesos/buildinfo.json, pkgpanda/docker/dcos-builder/Dockerfile, setup.py
:steam_locomotive: 181 for 1.10/master
#1674 custom_checks config parameter
#1676 Go 1.8.3
#1673 latest Mesos master (pre-1.4)
=> Master train 181

packages/bootstrap/extra/dcos_internal_utils/cli.py, packages/dcos-diagnostics/extra/dcos-diagnostics-agent.service, packages/dcos-diagnostics/extra/dcos-diagnostics-master.service
Add checks to the bootstrap to create service accounts
Corresponding enterprise pr: 
https://github.com/mesosphere/dcos-enterprise/pull/1083
This pr is dependent on the enterprise pr and will need to be merged together
___ …
=> Add checks account to bootstrap

packages/cosmos/buildinfo.json
- [DCOS-15938](https://jira.dcos.io/browse/DCOS-15938) Re-implement SDK uninstall so that it doesn't block
- [DCOS-15995](https://jira.dcos.io/browse/DCOS-15995) Supported media type error for universe should include v4
- [DCOS-16321](https://jira.mesosphere.com/browse/DCOS-16321) Compress large Envelope values.
___ …
=> Bump Cosmos to Snapshot build 260

packages/dcos-diagnostics/buildinfo.json
This updates dcos-diagnostics to the latest version.
- [DCOS_OSS-1345](https://jira.mesosphere.com/browse/DCOS_OSS-1345) "dcos-diagnostics check --list" uses wrong key name for check command
=> Bump dcos-diagnostics

packages/adminrouter/extra/src/README.md, packages/adminrouter/extra/src/lib/cache.lua, packages/adminrouter/extra/src/test-harness/tests/test_cache.py
Just a rebase of community contribution from https://github.com/dcos/dcos/pull/1628
=> Admin Router: rebase of https://github.com/dcos/dcos/pull/1628

dcos_installer/upgrade.py
Fixes bug in the upgrade script
___
It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the …
=> Upgrade script bugs

mergebot-config.json
Turn ON pr-status-checks for dcos/dcos repo.
- [DCOS-16484 ](https://jira.mesosphere.com/browse/DCOS-16484 )Config option for PR Status Check
=> Turn ON pr-status-checks for dcos/dcos repo.

packages/dcos-ui/buildinfo.json
- [DCOS-16191](https://jira.mesosphere.com/browse/DCOS-16191): Skip non-string values in env var parsers
- [DCOS-16147](https://jira.mesosphere.com/browse/DCOS-16147): Default portDefinitions to an empty array
- [DCOS_OSS-1237](https://jira.mesosphere.com/browse/DCOS_OSS-1237), [DCOS_OSS-1236](https://jira.mesosphere.com/browse/DCOS_OSS-1236): Remove Size from ExternalVolumes with docker runtime
- [DCOS-14880](https://jira.mesosphere.com/browse/DCOS-14880]): Remove docker from container if needed
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / …
=> DCOS_OSS-1248: Update dcos ui package

packages/dcos-installer-ui/buildinfo.json
Minor bug fixes
- [DCOS-12870](https://jira.mesosphere.com/browse/DCOS-12870])
- [DCOS-9939](https://jira.mesosphere.com/browse/DCOS-9939])
- [DCOS-14984](https://jira.mesosphere.com/browse/DCOS-14984])
___ …
=> Bumps dcos-installer-ui package

packages/dcos-ui/buildinfo.json
* [DCOS-15838](https://jira.mesosphere.com/browse/DCOS-15838): Switch to DCOS_PACKAGE_NAME for a Framework package name
* [DCOS_OSS-1033](https://jira.mesosphere.com/browse/DCOS_OSS-1033): Adjust jobs handling
* [DCOS-16436](https://jira.mesosphere.com/browse/DCOS-16436): Update copy on Catalog page
* [DCOS_OSS-1051](https://jira.mesosphere.com/browse/DCOS_OSS-1051), [DCOS_OSS-1052](https://jira.mesosphere.com/browse/DCOS_OSS-1052), [DCOS-14556](https://jira.mesosphere.com/browse/DCOS-14556): Fix checkbox task behavior
* [DCOS-16493](https://jira.mesosphere.com/browse/DCOS-16493): Hard code navigator language
* [DCOS-15057](https://jira.mesosphere.com/browse/DCOS-15057): improve universe system tests
* …
=> DCOS_OSS-1246: Update DC/OS UI Package

owners.json
Adding more owners: @orlandohohmeier , @meichstedt , @MatApple 
They can how apply Ship-It labels when they do a bump and the status checks are green.
=> Include DCOS-UI/Marathon team members to owners.json file

packages/dcos-ui/buildinfo.json, packages/mesos/buildinfo.json
=> 1.9.2 train 191

packages/dcos-ui/buildinfo.json
- [DCOS-17262](https://jira.mesosphere.com/browse/DCOS-17262]): Cannot edit marathon app from UI form
- [DCOS-17241](https://jira.mesosphere.com/browse/DCOS-17241]) : Unable to select a task
- [DCOS_OSS-1350](https://jira.mesosphere.com/browse/DCOS_OSS-1350): Nodes Page error on checkbox
- [DCOS-17242](https://jira.mesosphere.com/browse/DCOS-17242): Adjust marathon errors parse util
___
All PRs …
=> Update DC/OS UI package

packages/dcos-diagnostics/buildinfo.json, packages/dcos-integration-test/extra/test_dcos_diagnostics.py
- bump dcos-diagnostics sha.
- update integration test to exclude `system` field validation.
- [DCOS_OSS-143](https://jira.mesosphere.com/browse/DCOS_OSS-1430) Remove `system` field from dcos-diagnostics health response.
- [DCOS_OSS-671](https://jira.mesosphere.com/browse/DCOS_OSS-671) Diagnostics bundle naming improvement. 
Current set of integration tests provides a good coverage. 
___ …
=> bump dcos-diagnostics sha

gen/calc.py, packages/cosmos/buildinfo.json
=> Master train 194

gen/calc.py
This patch enables linux capabilities support in DC/OS for Mesos/UCR containers.
This only enables the isolator. Since we don't set the
`--allowed_capabilities` flag on the Mesos agent, the agent should
behave the same as it is currently. However, this allows the framework
to optionally use this feature by setting ContainerInfo properly.
- [DCOS_OSS-1069](https://jira.mesosphere.com/browse/DCOS_OSS-1069) Support Linux Capabilities for UCR/Mesos containers.
___
All PRs …
=> Enable Linux Capabilities isolator in Mesos.

packages/cosmos/buildinfo.json
Changes to use the 0.4.0 release of cosmos.
___
It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is …
=> Update to cosmos 0.4.0

packages/dcos-ui/buildinfo.json
**FIXES 1.9.2 RELEASE BLOCKER [COPS-5](https://jira.mesosphere.com/browse/COPS-5)**
Update the DC/OS UI package to include the latest fixes and
improvements.
- [COPS-5](https://jira.mesosphere.com/browse/COPS-5): Do not set container if it is not necessary
- [DCOS-17304](https://jira.mesosphere.com/browse/DCOS-17304): Introduce `CODEOWNERS` file
- [DCOS-16515](https://jira.mesosphere.com/browse/DCOS-16515): Introduce Cobertura coverage reports
___ …
=> Bump DCOS-UI for 1.9.2 to fix blockers

flake8_dcos_lint/setup.py
* https://jira.mesosphere.com/browse/DCOS_OSS-1477
Pin Flake8 Version to 3.3.0
Corresponding backport PR to 1.9: #1776
=> Pin flake8 version to 3.3.0.

dcos_installer/test_backend.py, flake8_dcos_lint/setup.py, gen/calc.py
* Update version to 1.10.0-beta1
=> Update version to 1.10.0-beta1

packages/dcos-ui/buildinfo.json
- [DCOS-17242](https://jira.mesosphere.com/browse/DCOS-17242): Adjust MarathonErrorUtil to handle missing detail errors
- [DCOS-16705](https://jira.mesosphere.com/browse/DCOS-16705): Allow unknown values for container images
- [DCOS-15059](https://jira.mesosphere.com/browse/DCOS-15059): Write system integration for cluster dashboard
- [DCOS_OSS-1272](https://jira.mesosphere.com/browse/DCOS_OSS-1272): Retain port value if requirePorts is set to false
- [DCOS-17262](https://jira.mesosphere.com/browse/DCOS-17262): Add support for 0 vip port
- [DCOS_OSS-744](https://jira.mesosphere.com/browse/DCOS_OSS-744): Add clear "Edit Configuration" action to service config tab
- …
=> Latest DCOS-UI for 1.10

dcos_installer/test_backend.py, flake8_dcos_lint/setup.py, gen/calc.py
Set the DCOS version to 1.10-beta2
=> dcos version =  1.10-beta2

packages/adminrouter/extra/src/README.md
Documents `/service` endpoint
- DCOS_OSS-1014 Admin Router: Document /service endpoint behaviour and limitations
https://github.com/mesosphere/dcos-enterprise/pull/1248
=> Admin Router: /service endpoint documentation

packages/navstar/buildinfo.json
* Fix inconsistent state error in minuteman
- [DCOS_OSS-1472](https://jira.mesosphere.com/browse/DCOS_OSS-1472) Inconsistent state of minuteman
https://github.com/dcos/navstar/compare/c4e9ea6f18f8fa256139a0b66771f1349302ab52...193dea241d408d1f820bff8ecd2ba67800d6ec88
https://github.com/dcos/navstar/pull/85
https://github.com/dcos/navstar/pull/87
=> Bump navstar

flake8_dcos_lint/setup.py
=> Pin Flake8 to 3.3.0

packages/mesos-modules/buildinfo.json, packages/mesos/README.md, packages/mesos/buildinfo.json
This PR updates the `Mesos` and `mesos-modules` packages.
* [CORE-1067](https://jira.mesosphere.com/browse/CORE-1067) Filter results of /master/slaves and the v1 call GET_AGENTS.
* [DCOS-17194](https://jira.mesosphere.com/browse/DCOS-17194) Rename `.cni` config files to `.conf`
[dcos-mesos](https://github.com/mesosphere/mesos/compare/80928eaf1d66e2d06d4f301ac197c12d08eaa533...17979fea307b7c094c2bac8e5a3f25af33208a0c)
[dcos-mesos-modules](https://github.com/dcos/dcos-mesos-modules/compare/2a5a02f1de47dcbe44844f7358adf85ea630cf4a...4b2432429e5a283a4bdf26a023d2327089315eb4)
[Mesos …
=> Bumped the packages 'Mesos' and 'mesos-modules'

packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json
Bumped `mesos` and `mesos-modules` to the HEAD of their `master` branches.
Mesos highlights include: 
```
50a553d Made the capabilities isolator work with nested containers.
21a3405 Made the rlimits isolator work with nested containers.
ebfccf4 Introduced `--default_container_dns` agent flag.
e87569b Added full authz for non summarized fields of `/slaves` endpoint.
2fe2562 Enabled filtering of the 'GET_AGENTS' v1 API call.
0ed2f72 Added configuration option for LIFO fixed-size semaphore to Mesos.
d532518 Implemented blkio subsystem usage() for resource statistics.
b5efb91 Fixed the sandbox volume relative host path ownership.
63fd94c Fixed the sandbox_path volume source path ownership.
bb0e4f2 Added 'FRAMEWORK_REMOVED' event for master streaming api.
77486d7 Added 'FRAMEWORK_UPDATED' …
```
=> Bumped the packages 'Mesos' and 'mesos-modules'.

packages/exhibitor/extra/start_exhibitor.py
- [DCOS_OSS-1470](https://jira.dcos.io/browse/DCOS_OSS-1470) Exhibitor: use PatternLayoutEscaped logger layout for structured journal logger.
=> [DCOS_OSS-1470] Exhibitor: use PatternLayoutEscaped logger layout for structured journal logger

dcos_installer/test_backend.py, gen/calc.py
Bumps version from 1.9.2 to 1.9.3!
Tracked via https://jira.mesosphere.com/browse/DCOS_OSS-1530
=> Bump version to 1.9.3

packages/cosmos/buildinfo.json
Add metrics and documentation.
- [DCOS-17822](https://jira.mesosphere.com/browse/DCOS-17822) Release cosmos
- [DCOS-17823](https://jira.mesosphere.com/browse/DCOS-17823) Release cosmos enterprise
___
* Developers responsible for code that interacts with or depends on the …
=> Update cosmos version to 0.4.1

packages/dcos-ui/buildinfo.json
Release https://github.com/dcos/dcos-ui/releases/tag/v1.10.0-rc.5
- [DCOS-17939](https://jira.mesosphere.com/browse/DCOS-17939): Blacklist historySummary. #close
- [DCOS-17527](https://jira.mesosphere.com/browse/DCOS-17527): Update Certified and Community catagory headings. #close
- [DCOS-16599](https://jira.mesosphere.com/browse/DCOS-16599): Introduce hooks to lint commit message. #close
- [DCOS_OSS-1372](https://jira.mesosphere.com/browse/DCOS_OSS-1372): Marathon features list delimiter. #close
- [DCOS-17296](https://jira.mesosphere.com/browse/DCOS-17296): Delete group dialog incorrectly asks you to type a service name instead of a group name. #close
- [DCOS-16744](https://jira.mesosphere.com/browse/DCOS-16744): …
=> [next beta]: Bump UI for 1.10

packages/dcos-ui/buildinfo.json
- [DCOS-17705](https://jira.dcos.io/browse/DCOS-17705)   remove duplicated fetch parser
- [DCOS_OSS-1569](https://jira.dcos.io/browse/DCOS_OSS-1569) adjust SDK action handling
- [DCOS-17979](https://jira.dcos.io/browse/DCOS-17979) remove "open service" buttons for SDK services
- [DCOS-17982](https://jira.dcos.io/browse/DCOS-17982) remove suspend/resume for SDK service
___ …
=> chore(dcos-ui): update package to v1.10.0-rc.6

packages/dcos-integration-test/extra/test_networking.py
test_networking.test_vip test is flaky.
- [DCOS_OSS-1463](https://jira.mesosphere.com/browse/DCOS_OSS-1463) test_networking.test_vip test is flaky
___
It is best to proactively …
=> test_networking.test_vip test is flaky

packages/dcos-integration-test/extra/test_networking.py
test_networking.test_vip test is flaky.
* Add logging
* Fix checking of deployment status
* Set adequate timeout
- [DCOS_OSS-1463](https://jira.dcos.io/browse/DCOS_OSS-1463) test_networking.test_vip test is flaky
___
* Developers responsible for code that interacts with …
=> test_networking.test_vip test is flaky [2]

packages/marathon/buildinfo.json
* https://jira.mesosphere.com/browse/DCOS-18246 - This cherry-picks marathon-pr #1863
=> Cherry-pick Bump Marathon to 1.4.7.

dcos_installer/test_backend.py, gen/calc.py
=> Version Changes to 1.10.0-RC1.

packages/dcos-ui/buildinfo.json
- [DCOS_OSS-1582](https://jira.mesosphere.com/browse/DCOS_OSS-1609): Fix `unreachableStrategy` validation
___
* Developers responsible for code that interacts with or depends on the code being …
=> Update DC/OS UI package to v1.9.3

packages/mesos/buildinfo.json
This PR bumps the Mesos package to the latest HEAD of the 1.2.x branch, to bring in the recent backported bugfix.
- [MESOS-7926](https://issues.apache.org/jira/browse/MESOS-7926) - Abnormal termination of default executor can cause MesosContainerizer::destroy to fail.
- [MESOS-7934](https://issues.apache.org/jira/browse/MESOS-7934) - OOM due to LibeventSSLSocket send incorrectly returning 0 after shutdown.
- [MESOS-6743](https://issues.apache.org/jira/browse/MESOS-6743) - Docker executor hangs forever if docker stop fails.
___ …
=> Bumped Mesos package to Mesos 1.2.x head d95a031.

dcos_installer/test_backend.py, gen/calc.py
https://jira.mesosphere.com/browse/DCOS_OSS-1618
=> Bump version to 1.9.4

packages/dcos-ui/buildinfo.json
- [DCOS_OSS-1582](https://jira.mesosphere.com/browse/DCOS_OSS-1582): Fix `unreachableStrategy` validation
___ …
=> Update DC/OS UI package to 1.10.0-rc.8 (1.10)

packages/mesos/buildinfo.json
This PR bumps the Mesos package to the latest HEAD of the 1.4.x branch, to bring in the recent backported bugfix.
- [MESOS-7926](https://issues.apache.org/jira/browse/MESOS-7926) Abnormal termination of default executor can cause MesosContainerizer::destroy to fail.
- [MESOS-7934](https://issues.apache.org/jira/browse/MESOS-7934) OOM due to LibeventSSLSocket send incorrectly returning 0 after shutdown.
- [MESOS-7861](https://issues.apache.org/jira/browse/MESOS-7861) Include check output in the DefaultExecutor log.
Edit(JP):
- https://jira.mesosphere.com/browse/DCOS-18346
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / …
=> Bumped Mesos package to 1.4.x head 60b8d41.

packages/dcos-ui/buildinfo.json
- [DCOS_OSS-1582](https://jira.mesosphere.com/browse/DCOS_OSS-1582): Fix `unreachableStrategy` validation
___ …
=> Update DC/OS UI package to 1.10.0-rc.8

gen/build_deploy/aws.py, gen/build_deploy/azure.py, gen/build_deploy/bash.py, gen/calc.py, gen/dcos-config.yaml, gen/fault-domain-detect/aws.sh, gen/fault-domain-detect/azure.sh, packages/dcos-integration-test/extra/test_mesos.py, packages/mesos/build, packages/mesos/extra/dcos-mesos-master.service, packages/mesos/extra/dcos-mesos-slave-public.service, packages/mesos/extra/dcos-mesos-slave.service, packages/mesos/extra/start_mesos.sh, setup.py
Add detect fault domain option to DC/OS config.yaml
The optional parameter points to a file which emits the out for mesos flag `--domain`
[More info](https://mesos.apache.org/documentation/latest/configuration/)
Supported environment:
- aws
- azure
- on-prem
- [DCOS-17485](https://jira.mesosphere.com/browse/DCOS-17485)
___ …
=> add fault-domain option to config

packages/marathon/buildinfo.json
A few improvements to the constraint migration logic and better handling of exceptions when forwarding requests to a Marathon leader.
- [MARATHON-4802](https://jira.mesosphere.com/browse/MARATHON-4802) Constraint migration was not really implemented. This commit makes sure that it is fully implemented. During migration some constraints get sanitized. For instance, `["field", "UNIQUE", "value"]` gets transformed to `["field", "UNIQUE"]` because the `UNIQUE` constraint should not have any value. In addition to that the validation of `CLUSTER` is relaxed, because it doesn't require a value, and such a constraint did not pass the validation before.
- [#5487](https://github.com/mesosphere/marathon/pull/5487) Handle socket timeout exception when forwarding requests to a leader.
If you are …
=> Bump Marathon to v1.3.13

packages/mesos/buildinfo.json
Bumping Mesos to 1.4.0 which contain a critical libprocess bug fix ([MESOS-7921](https://issues.apache.org/jira/browse/MESOS-7921))
___ …
=> Bump Mesos to 1.4.0

dcos_installer/check.py, dcos_installer/test_check.py, packages/dcos-metrics/buildinfo.json, packages/dcos-ui/buildinfo.json
#1923 chore(dcos-ui): bump dcos-ui for 1.10.1
#1937 (1.10) Fix method name in installer
#1943 [1.10.1] Bump dcos-metrics
=> [1.10.1] Train 223

cloud_images/CHANGELOG.md, cloud_images/centos7/packer.json, gen/aws/templates/advanced/advanced-master.json, gen/aws/templates/advanced/advanced-priv-agent.json, gen/aws/templates/advanced/advanced-pub-agent.json, gen/aws/templates/advanced/zen.json, gen/aws/templates/cloudformation.json, gen/build_deploy/aws.py
Use m4.xlarge as default instance type for aws templates
- The descriptions/wording in the template had to be modified because we were hitting aws cloudformation template size limits. 
- The ami's are generated from:
- https://teamcity.mesosphere.io/viewLog.html?buildId=774490&tab=buildResultsDiv&buildTypeId=DcosIo_Dcos_BuildCloudBaseImages_AwsBuildAndPublishCentOS7baseImage
- https://teamcity.mesosphere.io/viewLog.html?buildId=774489&tab=buildResultsDiv&buildTypeId=DcosIo_Dcos_BuildCloudBaseImages_AwsBuildAndPublishCentOS7baseImagesForGovcloud
Lukas has tested these ami's. 
m4.xlarge doesnt work with only one test for data agility which is a low priority issue and does not block this pr - https://jira.mesosphere.com/browse/INFINITY-2428 
* CoreOS version unchanged at 1235.12.0 (just …
=> Testing m4 xlarge

packages/marathon/buildinfo.json
* [MARATHON-7697](https://jira.mesosphere.com/browse/MARATHON-7697) - CLUSTER constraint doesn't require a value.
* [MARATHON-7724](https://jira.mesosphere.com/browse/MARATHON-7724) - Better error handling around proxy leader failure.
* [MARATHON-7728](https://jira.mesosphere.com/browse/MARATHON-7728) - Always log exceptions when performing migration.
* [MARATHON-7696](https://jira.mesosphere.com/browse/MARATHON-7696) - Do a better job at maintaining task failure rate limiting values per RunSpec.
=> marathon 1.4.8 bump

packages/cosmos/buildinfo.json
- [DCOS_OSS-1650](https://jira.dcos.io/browse/DCOS_OSS-1650) Release Cosmos (Open & EE) :  Back ported https://github.com/dcos/cosmos/pull/681, https://github.com/dcos/cosmos/pull/686 and https://github.com/dcos/cosmos/pull/687.
___
All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews …
=> Release cosmos v0.4.2

cloud_images/CHANGELOG.md, cloud_images/centos7/packer.json, gen/aws/templates/advanced/advanced-master.json, gen/aws/templates/advanced/advanced-priv-agent.json, gen/aws/templates/advanced/advanced-pub-agent.json, gen/aws/templates/advanced/zen.json, gen/aws/templates/cloudformation.json, gen/build_deploy/aws.py
For AWS simple cloudformation templates this PR adds ability to choose instance type and defaults instance type to m4.xlarge 
___
It is best to proactively ask for 2 reviews by …
=> Use m4.xlarge as default instance type

packages/dcos-integration-test/extra/test_networking.py
- [DCOS_OSS-1039](https://jira.dcos.io/browse/DCOS_OSS-1039) Integration tests for `dcos-l4lb` CNI plugin.
This tests the interaction of the `dcos-l4lb` CNI plugin with `minuteman.
- [*] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
- [*] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
- [*] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs) …
=> Added a test for `dcos-l4lb` CNI plugins.

packages/dcos-metrics/buildinfo.json, packages/dcos-ui/buildinfo.json, packages/marathon/buildinfo.json
* Bump dcos-ui for 1.10.1 #1982
* Bump dcos-metrics #1981
* Bump to marathon 1.5.1 #1967
=> 1.10 train 231

packages/dcos-ui/buildinfo.json
Includes 2 blocker fixes listed below.
- [DCOS-18788](https://jira.mesosphere.com/browse/DCOS-18788): The JSON editor duplicates and fails to properly parse app definition
- [DCOS-18696](https://jira.mesosphere.com/browse/DCOS-18694): Pod Endpoints protocol JSON parser adds 0 to JSON
___
* Developers who understand the …
=> Bump dcos-ui for 1.10.1

gen/azure/cloud-config.yaml
Package has been renamed from `docker-engine` to `docker-ce`.
=> Update Ubuntu (Azure) Docker to `17.09.0`

gen/build_deploy/aws.py, gen/build_deploy/azure.py, gen/build_deploy/bash.py, gen/calc.py, gen/tests/test_validation.py
set `fault_domain_enabled` to `false` in all cases.
current tests coverage is sufficient for this change
___ …
=> disable fault domain

packages/mesos-modules/buildinfo.json, packages/metronome/buildinfo.json
Includes:
https://github.com/dcos/dcos/pull/1986
https://github.com/dcos/dcos/pull/2010
=> Train 1.10 232

packages/mesos-modules/buildinfo.json
Updated the `mesos-modules` package to point to the `dcos/dcos-mesos-modules` 1.10 branch for DC/OS 1.10
- [DCOS_OSS-1712](https://jira.dcos.io/browse/DCOS_OSS-1712) Ticket for tracking creation of 1.10 branch for `dcos-mesos-modules` branch. 
___
The SHA hasn't been changed but the ref is just pointing to a newly created branch so none of the above are applicable here. …
=> Moved `mesos-modules` to 1.10 branch.

packages/metronome/buildinfo.json
-[COPS-1814](https://jira.mesosphere.com/browse/COPS-1814) Fixes to cron-utils enables advanced cron expressions.
=> upgrade metronome to 2.4.0

gen/aws/templates/cloudformation.json
=> [master] Train 239

gen/aws/templates/cloudformation.json
Add second volume to the cloudformation template instances
https://jira.mesosphere.com/browse/DCOS_OSS-1702 
___ …
=> Adding xvdb

packages/marathon/buildinfo.json
- [MARATHON-7848](https://jira.mesosphere.com/browse/MARATHON-7848) Fixes regression in which underscores were no longer permitted in network names
=> bump of marathon 1.5.1.1

packages/metronome/buildinfo.json
* upgrade metronome to 2.4.0 #2009
=> 1.9 train 232

packages/dcos-ui/buildinfo.json
- [DCOS-15709](https://jira.mesosphere.com/browse/DCOS-15709): Introduce Connection Manager
- [DCOS-17721](https://jira.mesosphere.com/browse/DCOS-17721): Edit configuration settings
- [DCOS-18055](https://jira.mesosphere.com/browse/DCOS-18055): Improvements for deployment behavior in Catalog
- [DCOS-18144](https://jira.mesosphere.com/browse/DCOS-18144): SDK Connection Endpoints (Enterprise + OSS): Create actions for SDK Endpoints
- [DCOS-18199](https://jira.mesosphere.com/browse/DCOS-18199): implement new actions for package edit
- [DCOS-18200](https://jira.mesosphere.com/browse/DCOS-18200): add support to stores for package edit
- [DCOS-18357](https://jira.mesosphere.com/browse/DCOS-18357): Implement a separate …
=> Bump dcos-ui package to 1.11-rc.1

packages/marathon/buildinfo.json
- [MARATHON-7848](https://jira.dcos.io/browse/MARATHON-7848) Fixes regression in which underscores were no longer permitted in network names
=> bump Marathon to v1.5.1.2

packages/dcos-integration-test/extra/test_networking.py
It's a backport of test_vip fixes.
- [DCOS_OSS-1463](https://jira.mesosphere.com/browse/DCOS_OSS-1463) test_networking.test_vip test is flaky
___
It is best to proactively ask …
=> [1.10] test_networking.test_vip test is flaky

dcos_installer/test_backend.py, gen/calc.py
Update version to 1.11.0 
https://jira.mesosphere.com/browse/DCOS_OSS-1765
___
It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR …
=> Update version to 1.11

dcos_installer/action_lib.py, dcos_installer/test_backend.py, gen/calc.py, owners.json, packages/dcos-diagnostics/buildinfo.json
* Updating Owners.json #2052
* bump dcos-diagnostics #2066
* Enhance install-prereqs #2015
* Update version to 1.11 #1933
=> Master train 245

packages/adminrouter/extra/src/includes/server/master.conf, packages/adminrouter/extra/src/includes/server/open/master.conf, packages/adminrouter/extra/src/lib/auth/open.lua
This is a backport of https://github.com/dcos/dcos/commit/277a61651e74f06a5c80105421a6e7c7a9d398b3 (originally in https://github.com/mesosphere/dcos/pull/43) to the 1.10 branch.
This PR removes authz from `/metadata` endpoint. Please see linked Jira issues for the reasoning behind this PR and other details.
- [DCOS-14563](https://jira.mesosphere.com/browse/DCOS-14563) Admin Router: switch /metadata to "allow all authenticated users" instead of ACL lookup
___
All PRs …
=> [1.10] Admin Router: Remove authz from /metadata endpoint

dcos_installer/backend.py, gen/__init__.py, gen/calc.py, gen/dcos-config.yaml, gen/internals.py, gen/tests/test_config.py, gen/tests/test_internals.py, packages/dcos-integration-test/extra/test_helpers.py
This is a 1.10 backport of #2062.
- [DCOS_OSS-1795](https://jira.mesosphere.com/browse/DCOS_OSS-1795) Sensitive config values in diagnostics bundles
=> (1.10) Remove sensitive config values from diagnostics bundles and build output

dcos_installer/backend.py, gen/__init__.py, gen/calc.py, gen/dcos-config.yaml, gen/internals.py, gen/tests/test_config.py, gen/tests/test_internals.py, packages/dcos-integration-test/extra/test_helpers.py, packages/navstar/buildinfo.json
* (1.10) Remove sensitive config values from diagnostics bundles and build output #2086
* Bump navstar #2085
=> 1.10 train 253

gen/calc.py, gen/dcos-config.yaml, gen/tests/test_validation.py, packages/dcos-integration-test/extra/test_endpoints.py, packages/dcos-net/buildinfo.json, packages/dcos-net/extra/dcos-net-setup.py, packages/dcos-net/extra/dcos-net.service, packages/mesos-dns/buildinfo.json
Add IPv6 support
- [DCOS_OSS-1735](https://jira.dcos.io/browse/DCOS_OSS-1735) Add IPv6 support
___
It is best to proactively ask for 2 reviews by @mentioning the candidate …
=> Add ipv6 support

dcos_installer/backend.py, gen/__init__.py, gen/calc.py, gen/dcos-config.yaml, gen/internals.py, gen/test_config.py, gen/test_internals.py, packages/dcos-integration-test/extra/test_helpers.py
This is a 1.9 backport of #2062.
- [DCOS_OSS-1795](https://jira.mesosphere.com/browse/DCOS_OSS-1795) Sensitive config values in diagnostics bundles
=> (1.9) Remove sensitive config values from diagnostics bundles and build output

dcos_installer/backend.py, gen/__init__.py, gen/calc.py, gen/dcos-config.yaml, gen/internals.py, gen/test_config.py, gen/test_internals.py, packages/dcos-integration-test/extra/test_helpers.py, packages/openssl/build
* openssl: Disable TLS compression [1.9] #2079
* (1.9) Remove sensitive config values from diagnostics bundles and build output #2087
=> DCOS 1.9 - Train 254

README.md, packages/adminrouter/extra/src/Makefile.common, packages/dcos-integration-test/extra/util/run_integration_test.sh, test_util/run-all, tox.ini
* #2096 Rename py.test to pytest
=> Train 255 (master)

README.md
* Update README on how to run integration-tests.
* Remove the reference to non-existing file.
=> Update DCOS README for executing integration tests

gen/calc.py, gen/tests/test_config.py, packages/dcos-net/buildinfo.json
Old format:
```
dns_forward_zones:
- - "a.contoso.com"
- - - "1.1.1.1"
- 53
- - "2.2.2.2"
- 53
- - "b.contoso.com"
- - - "3.3.3.3"
- 53
- - "4.4.4.4"
- 53
```
New format:
```
dns_forward_zones:
a.contoso.com:
- 1.1.1.1:53
- 2.2.2.2
b.contoso.com:
- 3.3.3.3
- 4.4.4.4:53
```
- [DCOS-17712](https://jira.mesosphere.com/browse/DCOS-17712) Change dns_forward_zones format from nested lists to proper object/lists.
- [DCOS_OSS-1825](https://jira.mesosphere.com/browse/DCOS_OSS-1825) DC/OS L4lb should periodically check the correctness of the IPVS config
https://github.com/dcos/dcos-net/pull/8 …
=> Make dns forward zones sane

gen/calc.py
rename default fault domain script from `fault_domain_detect` to `fault-domain-detect` to match
detect ip naming convention.
[DCOS_OSS-1855](https://jira.mesosphere.com/browse/DCOS_OSS-1855)
current set of unit/integration test cover this change
___
* Developers …
=> set default fault domain script name to `fault-domain-detect`

packages/dcos-test-utils/buildinfo.json
This is train 260, comprised of the following pull request(s):
- #2109 (Bump dcos-test-utils)
=> Train 260 (master)

packages/dcos-test-utils/buildinfo.json
Fixes KeyError in wait_for_history_service_data check
diff: https://github.com/dcos/dcos-test-utils/pull/17/files
https://jira.mesosphere.com/browse/DCOS-19612
=> Bump dcos-test-utils

mergebot-config.json
* DCOS-19387 - Mergebot to support overriding status
=> Enable override-status

mergebot-config.json
This one has most of the PRs on the bump-ee
https://github.com/dcos/dcos/pull/2126 – **Enable override-status**
> DCOS-19387 - Mergebot to support overriding status
=> Train 264 (master)

packages/mesos/buildinfo.json
Bumped Mesos to latest 1.2.x (f8706e5).
* [DCOS_OSS-1897](https://jira.mesosphere.com/browse/DCOS_OSS-1897)
Tests covered by Mesos test suite.
___
It is best to proactively ask …
=> Bumped Mesos to latest 1.2.x (f8706e5).

dcos_installer/test_backend.py, gen/calc.py
https://jira.mesosphere.com/browse/RELEASE-188
=> Bump DC/OS version to 1.9.6

packages/java/buildinfo.json
Train 267
* #2131 bump java patch level
=> Train 267 (base 1.10)

packages/dcos-ui/buildinfo.json
Contains a large portion of 1.11 work.
- [DCOS-19104](https://jira.mesosphere.com/browse/DCOS-19104): Consistent Service Status on Dashboard
- [DCOS-19528](https://jira.mesosphere.com/browse/DCOS-19528): Replace Suspend state with Stop
- [DCOS-19345](https://jira.mesosphere.com/browse/DCOS-19345): Add linked clusters page and menu link
- [DCOS-19483](https://jira.mesosphere.com/browse/DCOS-19483): Add new IS constraint operator constant
- [DCOS-19372](https://jira.mesosphere.com/browse/DCOS-19372): Use new Icon for deploying state
- [DCOS-17968](https://jira.mesosphere.com/browse/DCOS-17968): Redesign service Status
- [DCOS-18268](https://jira.mesosphere.com/browse/DCOS-18268): Create and use …
=> Bump UI for latest 1.11 bits

packages/dcos-net/buildinfo.json
ipv6 overlay network doesn't work on soak111 cluster
**This PR also includes all dcos-net changes from https://github.com/dcos/dcos/pull/2108**
- [DCOS-19706](https://jira.mesosphere.com/browse/DCOS-19706) ipv6 overlay network doesn't work on soak111 cluster
- [DCOS_OSS-1909](https://jira.mesosphere.com/browse/DCOS_OSS-1909) Remove annoying crash reports
https://github.com/dcos/dcos-net/pull/19
https://github.com/dcos/dcos-net/pull/20
___ …
=> Bump dcos-net

packages/adminrouter/docker/requirements-tests.txt
* https://github.com/dcos/dcos/pull/2141 – **Admin Router: Pin pytest**
> https://jira.mesosphere.com/browse/DCOS_OSS-1910
=> Train 270 (1.9)

packages/cosmos/buildinfo.json, packages/dcos-test-utils/buildinfo.json
* #2049 Update cosmos to latest version
=> Train 269 base:master

packages/dcos-integration-test/extra/test_dcos_log.py
#2153 fix race condition in dcos-log integration test
=> Train 272 (base:master)

packages/dcos-ui/buildinfo.json
* [DCOS-19481](https://jira.mesosphere.com/browse/DCOS-19481) swap placement form fields
* [DCOS-19559](https://jira.mesosphere.com/browse/DCOS-19559) use placement constraints widget
* [DCOS-19657](https://jira.mesosphere.com/browse/DCOS-19657) add advanced type to constraints input
* [DCOS-19103](https://jira.mesosphere.com/browse/DCOS-19103) re-order breadcrumb and update style based on new design.
* [DCOS-18275](https://jira.mesosphere.com/browse/DCOS-18275) switch to Mesos Event Stream
* [DCOS-19557](https://jira.mesosphere.com/browse/DCOS-19557) extract placement constraints partial
* …
=> chore(dcos-ui): update package to 1.11.0-rc.3

packages/dcos-integration-test/extra/test_mesos.py, packages/dcos-net/buildinfo.json, packages/dcos-ui/buildinfo.json, packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json
This is train 273, comprised of the following pull requests:
- #2144 (chore(dcos-ui): update package to 1.11.0-rc.3 )
- #2142 (Bumped Mesos and mesos-modules.)
- #2092 (Add an integration test for blkio statistics.)
=> Train 273 (master)

packages/marathon/buildinfo.json
* Workload bursting
* Significant performance improvement to deployments
* Docker IPv6 Support (Apache Mesos 1.5 Required)
- [DCOS-19774](https://jira.mesosphere.com/browse/DCOS-19774) Bump Marathon for DC/OS 1.11 Beta2.
In addition there was a technical infrastructure update with a move to akka.http for controllers and a switch from joda time to java time.
- [MARATHON_EE-1713](https://jira.mesosphere.com/browse/MARATHON_EE-1713)
- [MARATHON_EE-1661](https://jira.mesosphere.com/browse/MARATHON_EE-1661)
- [MARATHON_EE-1770](https://jira.mesosphere.com/browse/MARATHON_EE-1770)
- [MARATHON_EE-1764](https://jira.mesosphere.com/browse/MARATHON_EE-1764)
- …
=> Marathon 1.6 Beta Release

packages/dcos-ui/buildinfo.json
- [DCOS-19820](https://jira.mesosphere.com/browse/DCOS-19820): add constraints validators to frameworks
- [DCOS-19784](https://jira.mesosphere.com/browse/DCOS-19784): only show framework edit if hook true
- [DCOS-19573](https://jira.mesosphere.com/browse/DCOS-19573): fix unique constraints
- [DCOS_OSS-1789](https://jira.mesosphere.com/browse/DCOS_OSS-1789): add download config button
- [DCOS_OSS-1789](https://jira.mesosphere.com/browse/DCOS_OSS-1789): framework config tab with cosmos
- [DCOS-19354](https://jira.mesosphere.com/browse/DCOS-19354): add IPv6 field to the healthchecks form section
- …
=> chore(dcos-ui): update package to 1.11.0-rc.4

packages/marathon/buildinfo.json
Bugfixes
- [MARATHON_EE-1701](https://jira.mesosphere.com/browse/MARATHON_EE-1701) Pods now respect hostname: UNIQUE constraint
- [MARATHON_EE-1768](https://jira.mesosphere.com/browse/MARATHON_EE-1768) Proper reading of secrets from volumes 
- [MARATHON_EE-1764](https://jira.mesosphere.com/browse/MARATHON_EE-1764) Speed up service port assignment
- [MARATHON_EE-1770](https://jira.mesosphere.com/browse/MARATHON_EE-1770) Speed up service port assignment 
=> marathon 1.5.3 bump

packages/marathon/buildinfo.json
Includes the following PR's:
#2166 : marathon 1.5.3 bump
=> Train 277 (1.10)

packages/marathon/buildinfo.json
- [MARATHON_EE-1779](https://jira.mesosphere.com/browse/MARATHON_EE-1779) Release Marathon 1.5.4
- [MARATHON_EE-1773](https://jira.mesosphere.com/browse/MARATHON_EE-1773) Enable `killGracePeriodSeconds` for Pods
=> marathon 1.5.4 bump

LICENSE, NOTICE, gen/build_deploy/bash.py, packages/adminrouter/extra/src/LICENSE, packages/dcos-image/build
Backport changes from https://github.com/dcos/dcos/pull/2128 to 1.10 branch
JIRA Ticket: https://jira.mesosphere.com/browse/COPS-2050
=> Backport - Include LICENSE, NOTICE file in dcos-image.

gen/dcos-config.yaml
This commit sets the newly added reconfiguration policy
for mesos-agent to `additive`, in order to allow agents
to add new domains without draining all tasks.
- [DCOS_OSS-1959](https://jira.mesosphere.com/browse/DCOS_OSS-1959)
- [MESOS-1739](https://issues.apache.org/jira/browse/MESOS-1739) Allow slave reconfiguration on restart
- [CORE-1244](https://jira.mesosphere.com/browse/CORE-1244) Allow agent domain re-configuration without losing tasks
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO …
=> Set new --reconfiguration_policy mesos flag.

gen/dcos-config.yaml
This is to avoid any potential deadlocks due to unavailable libprocess workers. The previous (default) value was 8.
- [DCOS_OSS-1943](https://jira.mesosphere.com/browse/DCOS_OSS-1943) Increase LIBPROCESS_NUM_WORKER_THREADS for Mesos master from 8 to 16.
___ …
=> Mesos: Increase min libprocess worker threads to 16. [1.11]

packages/dcos-ui/buildinfo.json
- [DCOS-19720](https://jira.mesosphere.com/browse/DCOS-19720): adjust hasHealthChecks condition
- [DCOS-19869](https://jira.mesosphere.com/browse/DCOS-19869): fix duplicate local string in region/ zone column
- [DCOS-19828](https://jira.mesosphere.com/browse/DCOS-19828): correct FRAMEWORK_REMOVED message format
- [DCOS-19747](https://jira.mesosphere.com/browse/DCOS-19747): add tooltip to serviceStatusIcon
- [DCOS-12802](https://jira.mesosphere.com/browse/DCOS-12802): introduce Jenkinsfile
- [DCOS-19771](https://jira.mesosphere.com/browse/DCOS-19771): avoid framework regex errors
If you are …
=> chore(dcos-ui): update package

gen/dcos-config.yaml, packages/dcos-ui/buildinfo.json
This is train 283. It contains the following pull requests:
- #2159 (Mesos: Increase min libprocess worker threads to 16. [1.11])
- #2196 (chore(dcos-ui): update package)
=> Train 283 (master)

dcos_installer/test_backend.py, gen/calc.py
* https://jira.mesosphere.com/browse/DCOS-19985 - Update version of DCOS to 1.11.0-sf2
=> DCOS Version 1.11.0-sf2

packages/cosmos/buildinfo.json
Migrate config updates to open DC/OS
- [DCOS-19855](https://jira.mesosphere.com/browse/DCOS-19855) Migrate Describe
- [DCOS-19858](https://jira.mesosphere.com/browse/DCOS-19858) Refactor Update
- [DCOS-19856](https://jira.mesosphere.com/browse/DCOS-19856) Migrate Update
- [DCOS-19857](https://jira.mesosphere.com/browse/DCOS-19857) Release DC/OS
___ …
=> Update cosmos buildinfo.json

gen/build_deploy/bash.py, gen/dcos-services.yaml, packages/cosmos/buildinfo.json, packages/dcos-integration-test/extra/test_networking.py, packages/mesos/buildinfo.json
:steam_locomotive: :2nd_place_medal: :8ball: :five: :train: (master)
#2168 Install to an existing install directory if it's empty
#2189 Bump Mesos
#2194 Bump cosmos
#2204 Skip the ip_per_container test when number of slaves <2
=> Train 285 (master)

gen/dcos-config.yaml
This is to avoid any potential deadlocks due to unavailable libprocess workers. The previous (default) value was 8.
- [DCOS_OSS-1943](https://jira.mesosphere.com/browse/DCOS_OSS-1943) Increase LIBPROCESS_WORKER_THREADS for Mesos master from 8 to 16.
___ …
=> Mesos: Increase min libprocess worker threads to 16. [1.9]

packages/navstar/buildinfo.json
Set dump_log_write_threshold to 10
- [DCOS-19893](https://jira.mesosphere.com/browse/DCOS-19893) Navstar Lashup Crash Loop
https://github.com/dcos/navstar/pull/95
___
* Developers who understand …
=> [1.9] Bump navstar

owners.json
This will be used with mergebot override feature.
https://jira.mesosphere.com/browse/DCOS-19647
=> Add JIRA ids to owners.json

gen/dcos-config.yaml, owners.json, packages/metronome/buildinfo.json, packages/navstar/buildinfo.json
* Mesos: Increase min libprocess worker threads to 16. [1.9]  #2161 
* [1.9] Bump navstar  #2174
* Add JIRA ids to owners.json  #2188 
* bump to metronome 0.3.1 on DCOS 1.9  #2201
=> DCOS 1.9 - Train 287

gen/calc.py, packages/dcos-checks/build, packages/dcos-checks/buildinfo.json, packages/dcos-checks/extra/dcos-checks-poststart.service, packages/dcos-checks/extra/dcos-checks-poststart.timer, packages/dcos-integration-test/extra/test_composition.py, packages/mesos/buildinfo.json
:steam_locomotive:  :2nd_place_medal: :8ball: :nine: :train: 
#2069 poststart check
#2205 Mesos bump
=> Train 289 (master)

gen/dcos-config.yaml
This is to avoid any potential deadlocks due to unavailable libprocess workers. The previous (default) value was 8.
- [DCOS_OSS-1943](https://jira.mesosphere.com/browse/DCOS_OSS-1943) Increase LIBPROCESS_WORKER_THREADS for Mesos master from 8 to 16.
___ …
=> Mesos: Increase min libprocess worker threads to 16. [1.10]

packages/navstar/buildinfo.json
Set dump_log_write_threshold to 10
- [DCOS-19893](https://jira.mesosphere.com/browse/DCOS-19893) Navstar Lashup Crash Loop
https://github.com/dcos/navstar/pull/96
___
* Developers who understand …
=> [1.10] Bump navstar

owners.json
This will be used with mergebot override feature.
Corresponding DC/OS tickets (obligatory)
https://jira.mesosphere.com/browse/DCOS-19647
=> [1.10 backport] Update owners with JIRA

gen/dcos-config.yaml, owners.json, packages/dcos-test-utils/buildinfo.json, packages/metronome/buildinfo.json, packages/navstar/buildinfo.json
* Mesos: Increase min libprocess worker threads to 16. #2162 
* [1.10] Bump navstar  #2175 
* [1.10 backport] Update owners with JIRA #2187
* bump metronome 0.3.1 #2191
*  1.10 backport - Update dcos-test-utils #2203
=> [dcos 1.10] - Train 286 

docs/admin-ports.md, gen/build_deploy/bash.py, packages/dcos-net/buildinfo.json, packages/erlang/buildinfo.json
Included PRs:
#2172 : Bump dcos-net
=> Train 290 (base: master)

dcos_installer/action_lib.py
Also, added a DC/OS specific network configuration when we detect
`networkd` is enabled.
- [DCOS_OSS-1790](https://jira.dcos.io/browse/DCOS_OSS-1790) Fixing overlay issues in newer versions of CoreOS.
___
* …
=> Fixed detection of CoreOS and overlay issues with `systemd-networkd`.

packages/dcos-integration-test/extra/test_dcos_log.py, packages/dcos-log/buildinfo.json
bump dcos-log sha
this PR fixes a bug which makes dcos-log service panic under certain circumstances   
- [DCOS_OSS-1995](https://jira.mesosphere.com/browse/DCOS_OSS-1995)
N/A
___ …
=> bump dcos log sha

dcos_installer/upgrade.py
This PR adds a new flag to the upgrade script `--verbose`. 
```
amita@amita-desktop:~/Testing/verbosity/genconf/serve/upgrade/d65e4416634b4acabeefc8d1f6731fb0$ bash dcos_node_upgrade.sh --verbose
Verbose mode on
This script must be run as root
amita@amita-desktop:~/Testing/verbosity/genconf/serve/upgrade/d65e4416634b4acabeefc8d1f6731fb0$ bash dcos_node_upgrade.sh --skip-checks
Skipping checks
This script must be run as root
amita@amita-desktop:~/Testing/verbosity/genconf/serve/upgrade/d65e4416634b4acabeefc8d1f6731fb0$ bash dcos_node_upgrade.sh 
This script must be run as root
amita@amita-desktop:~/Testing/verbosity/genconf/serve/upgrade/d65e4416634b4acabeefc8d1f6731fb0$ bash dcos_node_upgrade.sh --skip-checks --verbose
Skipping checks
Verbose mode on
This script must be run as root
``` …
=> Add debug mode to the upgrade script

dcos_installer/upgrade.py, packages/dcos-integration-test/extra/test_metrics.py, packages/dcos-metrics/buildinfo.json, packages/marathon/buildinfo.json
#2116 - Update Marathon (Persistent volumes, optimizations and more)
#2190 - Add debug mode to the upgrade script
#2206 - Bump dcos-metrics sha
* 2190 EE bump merged in previous train
* 2206 EE bump closed, was testing only
=> Train 294 (master)

packages/dcos-integration-test/extra/test_helpers.py, packages/dcos-integration-test/extra/test_networking.py, packages/dcos-integration-test/extra/util/python_test_server.py
Enable VIP DC/OS integration tests for IPv6
- [DCOS_OSS-1861](https://jira.mesosphere.com/browse/DCOS_OSS-1861) Enable VIP DC/OS integration tests for IPv6
___ …
=> Enable VIP DC/OS integration tests for IPv6

gen/fault-domain-detect/cloud.sh
fix minor issues in fault domain shell script
- [DCOS-19815](https://jira.mesosphere.com/browse/DCOS-19815)
N/A
current set of tests cover this change
___ …
=> fault domain script improvements

gen/calc.py, gen/dcos-config.yaml, packages/dcos-net/buildinfo.json
Disable ipv6 support for l4lb
- [DCOS_OSS-1993](https://jira.mesosphere.com/browse/DCOS_OSS-1993) ipv6 docker containers reboot agent nodes on aws
https://github.com/dcos/dcos-net/pull/28
___
* …
=> Disable ipv6 support for l4lb

packages/mesos/buildinfo.json
Bump Mesos to latest head to pick up bug fixes and CSI and Resource Provider related changes.
- [DCOS_OSS-1970](https://jira.mesosphere.com/browse/DCOS_OSS-1970) Bump mesos to pre-1.5.0 in preparation for beta3
=> Bump dcos-mesos to Mesos 63f116a.

gen/calc.py, gen/dcos-config.yaml, gen/fault-domain-detect/cloud.sh, packages/dcos-integration-test/extra/test_helpers.py, packages/dcos-integration-test/extra/test_metrics.py, packages/dcos-integration-test/extra/test_networking.py, packages/dcos-integration-test/extra/util/python_test_server.py, packages/dcos-metrics/buildinfo.json, packages/dcos-net/buildinfo.json, packages/mesos/buildinfo.json
:steam_locomotive: :two: :nine: :six: :train: :tada: 
#2230 fault domain script improvements
#2232 Disable ipv6 for l4lb
#2245 Bump dc/os metrics
#2242 Bump dcos-mesos
#2182 VIP integ tests for ipv6
=> Train 296 (master)

owners.json
Add urbanserj to owners.json
___
It is best to …
=> Add urbanserj to owners.json

packages/bootstrap/extra/dcos_internal_utils/exhibitor.py
DCOS_OSS-1919 has revealed that it is possible for Zookeeper to not to create zk.pid even though Exhibitor reports that all the ZK instances have joined the quorum.
This change does not solve the root cause of the problem, it just makes the bootstrap handle it more gracefully and it adds some extra logging so that debugging of the underlying issue will be easier next time.
See the Jira issue for more details. Tests will be made green after I get all the required thumbs up. Same goes for porting these changes to `master` and `1.9`.
- https://jira.mesosphere.com/browse/DCOS_OSS-1919 `Terminated Master node in 3 HA cluster, Failed to start.`
EE PR: https://github.com/mesosphere/dcos-enterprise/pull/1888
=> bootstrap: More robust handling of a zk.pid file while waiting for exhibitor

dcos_installer/test_backend.py, gen/calc.py
Update DCOS version to version 1.10.4
=> Update version to 1.10.4

packages/dcos-net/buildinfo.json, packages/dcos-net/extra/dcos-net-env
Please see the JIRA ticket.
- [DCOS-20076](https://jira.mesosphere.com/browse/DCOS-20076) Name Resolution Failure
https://github.com/dcos/dcos-net/pull/30
___ …
=> Temporary disable hostname verification for Erlang Distribution Protocol

packages/dcos-net/buildinfo.json, packages/dcos-net/extra/dcos-net-env, packages/metronome/buildinfo.json
#2259 Temporary disable hostname verification for Erlang Distribution Protocol
#2252 metronome 0.3.2 bump for dcos 1.11
=> Train 298 (master)

packages/dcos-net/buildinfo.json, packages/dcos-net/extra/dcos-net-env
Please see the JIRA ticket.
- [DCOS-20076](https://jira.mesosphere.com/browse/DCOS-20076) Name Resolution Failure
https://github.com/dcos/dcos-net/pull/30
___ …
=> [1.11.0-beta3] Disable hostname verification for Erlang Distribution Protocol

packages/dcos-log/buildinfo.json
bump dcos-log sha
this change fixes the dcos-log bug, where logs from custom completed frameworks were not available.
- [DCOS-20083](https://jira.mesosphere.com/browse/DCOS-20083)
N/A
current set of tests cover this
___ …
=> bump dcos-log

packages/bootstrap/extra/dcos_internal_utils/exhibitor.py
This is just a fix for a bug pointed out by @adam-mesos in https://github.com/dcos/dcos/pull/2212/files#r158573924
Please check the original PR's description for details.
=> bootstrap: Fix small logging bug

packages/bootstrap/extra/dcos_internal_utils/exhibitor.py
#2264 -bootstrap: Fix small logging bug
=> Train 301 (1.10)

packages/dcos-ui/buildinfo.json
This PR _back-ports_  the latest DC/OS UI fixes, improvements and features introduced with #2256 to 1.11.0 beta3 .
- [DCOS-20068](https://jira.mesosphere.com/browse/DCOS-20068): rename GraphQLTaskUtil to TaskMergeDataUtil
- [DCOS-18860](https://jira.mesosphere.com/browse/DCOS-18860): add region/zone DSL filters to nodes page
- [DCOS-19579](https://jira.mesosphere.com/browse/DCOS-19579): introduces the support for persistent volumes in multi container services.
- [DCOS-19139](https://jira.mesosphere.com/browse/DCOS-19139): add DSL filter in tasks table page
- [DCOS-19719](https://jira.mesosphere.com/browse/DCOS-19719): improve advanced constraints with minor UX/design changes
- …
=> DC/OS UI v1.11.0 rc.8+1.11.0 beta3

packages/mesos/README.md, packages/mesos/buildinfo.json
See branch `dcos-mesos-post-1.2.3` in `mesosphere/mesos/`.
This change bumps Mesos beyond 1.2.3, the last officially released patch version of 1.2.x. It includes a critical bugfix with stuck built-in executors.
- [DCOS_OSS-2024](https://jira.mesosphere.com/browse/DCOS_OSS-2024) Bump Mesos to post-1.2.3 in DC/OS 1.9.7.
- [MESOS-8297](https://issues.apache.org/jira/browse/MESOS-8297) Built-in driver-based executors ignore kill task if the task has not been launched.
___
**PLEASE FILL IN THE …
=> Bumped Mesos package to post-1.2.3 head 13a0782.

packages/bootstrap/extra/dcos_internal_utils/exhibitor.py, packages/mesos/README.md, packages/mesos/buildinfo.json
* #2227 more robust handling of zk pid
* #2251 bump mesos package
=> Train 299 [1.9]

dcos_installer/test_backend.py, gen/calc.py
=> Update version to 1.9.7

packages/dcos-net/buildinfo.json, packages/dcos-net/extra/dcos-net-env, packages/erlang/buildinfo.json
Enable TLS X509-path validation checks
- [DCOS-20087](https://jira.mesosphere.com/browse/DCOS-20087) Enable x509-path validation checks
- [DCOS-11320](https://jira.mesosphere.com/browse/DCOS-11320) Navstar fails to poll SSL client certificate requiring mesos master
- [DCOS-11321](https://jira.mesosphere.com/browse/DCOS-11321) Minuteman fails to poll SSL client certificate requiring mesos agent
- [DCOS-20112](https://jira.mesosphere.com/browse/DCOS-20112) Unable to build dcos-net locally …
=>  Enable TLS X509-path validation checks

packages/marathon/buildinfo.json
- Fix ephemeral volumes for pods
- Complete support for CSI persistent volume profiles
- Improvements to Marathon's CI
- App residency field deprecated
- Other fixes and improvements
- [MARATHON_EE-1786](https://jira.mesosphere.com/browse/MARATHON_EE-1786) — Persistent volumes for pods — move reservation info from tasks to instances
- [MARATHON_EE-1787](https://jira.mesosphere.com/browse/MARATHON_EE-1787) — Persistent volumes for pods — remove the polymorphism for tasks
- [MARATHON-8004](https://jira.mesosphere.com/browse/MARATHON-8004) — Pod ephemeral volumes are broken
- [MARATHON-7998](https://jira.mesosphere.com/browse/MARATHON-7998) — Config validation does NOT work
- [MARATHON-8000](https://jira.mesosphere.com/browse/MARATHON-8000) — Break exception propagates to the logs when the …
=> Bump Marathon

packages/marathon/buildinfo.json
Various fixes and optimizations.
- [DCOS-20098](https://jira.mesosphere.com/browse/DCOS-20098) - Release Marathon v1.4.11
- [MARATHON-7992](https://jira.mesosphere.com/browse/MARATHON-7992) - Validation errors on root group in large clusters can lead Marathon to crash.
- [MARATHON-7974](https://jira.mesosphere.com/browse/MARATHON-7974) - If a non-super-user was explicitly given access to some resource, such as GroupResources, they were denied. This has been resolved.
- [MARATHON-7962](https://jira.mesosphere.com/browse/MARATHON-7962) - Enable killGracePeriodSeconds for Pods.
- [MARATHON_EE-1770](https://jira.mesosphere.com/browse/MARATHON_EE-1770) - Optimized port assignments and performance enhancements.
- [MARATHON_EE-1764](https://jira.mesosphere.com/browse/MARATHON_EE-1764) - …
=> Update Marathon to v1.4.11

cloud_images/lib/el7/configure_dcos_system.sh, cloud_images/lib/el7/install_dcos_required_packages.sh, cloud_images/lib/el7/install_docker.sh
Trying stuff to fix https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=884142&_focus=709 `Caching enabled but no local cache of /var/cache/yum/x86_64/7/base/packages/libseccomp-2.3.1-3.el7.x86_64.rpm from base/7/x86_64`.
Update: Tried running `yum clean all` and `yum makecache` before the broken line https://github.com/dcos/dcos/blob/10e4045a0eafd4eaba8d4356d3a23c99853d0cef/cloud_images/lib/el7/install_docker.sh#L9 but the same error was still there. Removing the `-C` flag which tells yum to only use the system cache removed the error, and doesn't seem to have increased the build time. I noticed that the /etc/yum.conf had `keepcache=0` which means it wasn't storing anything anyway, so not sure how that worked before.
Here are successful …
=> fix cloud_images CI yum error

dcos_installer/test_backend.py, gen/calc.py
**Just in case, if we need to ship a 1.9.7-dev release**
=> Changing the Version to 1.9.7-dev

dcos_installer/action_lib.py
Also, added a DC/OS specific network configuration when we detect
`networkd` is enabled.
Please checkout the JIRA.
- [DCOS_OSS-2003](https://jira.mesosphere.com/browse/DCOS_OSS-2003)
- [DCOS_OSS-1790](https://jira.mesosphere.com/browse/DCOS_OSS-1790)
___ …
=> Fixed detection of CoreOS.

dcos_installer/action_lib.py, dcos_installer/test_backend.py, gen/calc.py, packages/dcos-oauth/buildinfo.json, packages/marathon/buildinfo.json
* This brings in changes from 1.9 branch (by doing a git merge).
* This also sets the version back to 1.9.7 ( https://github.com/dcos/dcos/commit/be51b54bbe9bac2a28b9a1d503ecff29e376142c)
=> Merge 1.9 changes to 1.9.7

packages/adminrouter/extra/src/lib/auth/common.lua, packages/adminrouter/extra/src/test-harness/tests/test_auth.py, packages/dcos-log/buildinfo.json, packages/dcos-test-utils/buildinfo.json
Includes:
#2299 bump dcos-log sha
#2287 bump dcos-test-utils
#2031 adminrouter: add alternative authentication header
=> Train 305 (master)

dcos_installer/action_lib.py, packages/adminrouter/extra/src/includes/http/common.conf, packages/adminrouter/extra/src/includes/server/agent.conf, packages/adminrouter/extra/src/nginx.agent.conf, packages/adminrouter/extra/src/test-harness/modules/generic_test_code/generalised_tests.py, packages/adminrouter/extra/src/test-harness/tests/open/test_generic.config.yml, packages/adminrouter/extra/src/test-harness/tests/test_agent.py, packages/adminrouter/extra/src/test-harness/tests/test_generic.config.yml, packages/dcos-oauth/buildinfo.json, packages/dcos-test-utils/buildinfo.json
#2265 Fixed detection of CoreOS.
#2281 Admin Router: Minimizing software version information reported by the AR [1.10]
#2288 Bump dcos-test-utils
#2291 dcos-oauth: bump for increased zk connection timeout 1.10
=> Train 306 (base:1.10)

gen/tests/test_adminrouter_tls_conf.py
Improves unit tests for TLS configuration parameters in `gen` package.
- [DCOS_OSS-2039](https://jira.mesosphere.com/browse/DCOS_OSS-2039) Address review comments from DCOS-19976
=> gen/tests: Improve TLS configuration parameters tests

packages/marathon/buildinfo.json
- It fixes a race condition in status updates handling in case of pods with two or more containers.
- Optimization of group validation.
- Fix ephemeral volumes for pods
- Complete support for CSI persistent volume profiles
- Improvements to Marathon's CI
- App residency field deprecated
- Other fixes and improvements
- [MARATHON_EE-1817](https://jira.mesosphere.com/browse/MARATHON_EE-1817) - Race condition when handling pod task status updates
- [MARATHON_EE-883](https://jira.mesosphere.com/browse/MARATHON_EE-883) - Investigate whether validation in Marathon is indeed a performance bottleneck.
- [MARATHON_EE-1786](https://jira.mesosphere.com/browse/MARATHON_EE-1786) — Persistent volumes for pods — …
=> Bump Marathon on 1.11 to Version 1.6.0-pre-250

gen/build_deploy/aws.py
Adding this flag allows not only the existing leader.mesos will be asserted but all of the dcos-\<components\> will be validated as well.
- [DCOS_OSS-2084](https://jira.mesosphere.com/browse/DCOS_OSS-2084) Adding dcos component check to cnf-signal service for oss.
Tested manually by stopping the dcos-mesos-master and confirmed that the proper error code was returned. When the ExecStartPre occurs, the error code will be parsed to ensure that the service runs properly.
~~If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please …
=> adding dcos-diag check for aws cf templates

packages/dcos-ui/buildinfo.json
We updated the UI with the latest fixes.
- [DCOS-20158](https://jira.mesosphere.com/browse/DCOS-20158) update `marked` package
___ …
=> Update DCOS-UI to 1.9.4

packages/cosmos/buildinfo.json
This PR doesn't change any of the code in Cosmos. It is simply a release build. The Cosmos currently in DC/OS is a SNAPSHOT build. SNAPSHOT builds are not reproducible.
- [DCOS_OSS-2091](https://jira.mesosphere.com/browse/DCOS_OSS-2091) Create a release version of Cosmos.
___ …
=> Bump Cosmos to a release version

packages/mesos/buildinfo.json
* https://issues.apache.org/jira/browse/MESOS-8460
* https://issues.apache.org/jira/browse/MESOS-8461
* https://issues.apache.org/jira/browse/MESOS-8344
- [DCOS_OSS-2092](https://jira.mesosphere.com/browse/DCOS_OSS-2092) Bump Mesos to latest 1.5.x prerelease.
___
=> Bumped Mesos to 1.5.0-rc1 (689760896).

dcos_installer/test_backend.py, gen/calc.py
Update the version to 1.11-rc1
=> Update version to 1.11-rc1

packages/dcos-integration-test/extra/test_composition.py, packages/dcos-signal/buildinfo.json
Bump dcos-signal sha
fix false positive component health report
[EE DC/OS PR](https://github.com/mesosphere/dcos-enterprise/pull/2015)
- [DCOS-20017](https://jira.mesosphere.com/browse/DCOS-20017)
- N/A
___
Reviewers …
=> Bump dcos-signal sha

packages/cosmos/buildinfo.json
Cosmos should send `force=true` flag during marathon app update. This needs to be merged in to `1.11`.
-  [DCOS-19500](https://jira.mesosphere.com/browse/DCOS-19500) cosmos/service/update fails if Marathon is deploying
- [DCOS_OSS-2102](https://jira.mesosphere.com/browse/DCOS_OSS-2102) Bump cosmos
___
**What is the review process and …
=> Bump cosmos version

packages/dcos-ui/buildinfo.json
This PR back-ports the DC/OS UI package update to include the latest bug fixes introduced with #2375.
- [DCOS-20343](https://jira.mesosphere.com/browse/DCOS-20343) Fix loading screen
- [DCOS-20485](https://jira.mesosphere.com/browse/DCOS-20485): Adjust implementation to address performance issues
___ …
=> chore(dcos-ui): update package to v1.11.0-rc.12

packages/dcos-ui/buildinfo.json
We updated the UI with the latest fixes.
- [DCOS-18784](https://jira.mesosphere.com/browse/DCOS-18784) Fix pod instance count
- [X ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
- [ X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)
___ …
=> chore(dcos-ui): update package to 1.10.4

dcos_installer/test_backend.py, gen/calc.py
=> Update Version to 1.11.0-rc2

dcos_installer/test_backend.py, gen/calc.py
Update version string of 1.10 branch to 1.10.5
=> updated version string to 1.10.5

packages/mesos/buildinfo.json
This change bumps Mesos beyond 1.4.1. It includes several critical and important bugfixes in Mesos.
- [DCOS_OSS-2128](https://jira.mesosphere.com/browse/DCOS_OSS-2128) Bump Mesos to post 1.4.1 in DC/OS 1.10.5.
- [MESOS-7504](https://issues.apache.org/jira/browse/MESOS-7504) Parent's mount namespace cannot be determined when launching a nested container.
- [MESOS-8356](https://issues.apache.org/jira/browse/MESOS-8356) Persistent volume ownership is set to root despite of sandbox owner (frameworkInfo.user) when docker executor is used.
- [MESOS-8480](https://issues.apache.org/jira/browse/MESOS-8480) Mesos returns high resource usage when killing a Docker task.
If …
=> Bumped Mesos package to 1.4.x head c8bfe87.

packages/metronome/buildinfo.json
- [METRONOME-190](https://jira.mesosphere.com/browse/METRONOME-190) Added authorized launch queue
- [METRONOME-194](https://jira.mesosphere.com/browse/METRONOME-194) Support FORBID Concurrency Policy
- [METRONOME-100](https://jira.mesosphere.com/browse/METRONOME-100) Metronome Restarts causes duplication of jobruns
- [METRONOME-191](https://jira.mesosphere.com/browse/METRONOME-191) Implement Start Deadline Timeout
=> bumping metronome to 0.4.0

dcos_installer/async_server.py
add error message and exit with code 1 if a user tries to run a web installer
- [DCOS-20726](https://jira.mesosphere.com/browse/DCOS-20726)
N/A
___ …
=> retire dcos web installer

dcos_installer/test_backend.py, gen/calc.py
Update version information to 1.11.0-rc3
=> Update DCOS Version to RC3.

README.md
When a status check fails, we should make it easy for a developer to be self-sufficient, by helping the developer in identifying the purpose of the test, and provide information on the maintainer for the test.
* https://jira.mesosphere.com/browse/DCOS-20357 - Describe Pull Request Status checks.
=> Pull Request Statuses Information for PR.

gen/azure/templates/acs.json, gen/fault-domain-detect/cloud.sh
This fixes the Azure Templates for it to successfully deploy
- [https://jira.mesosphere.com/browse/DCOS-20064](https://jira.mesosphere.com/browse/DCOS-20064) Verify azure and aws advanced templates work with the licensing parameter
@branden  @amitaekbote
=> ARM + Licensing Fix

gen/calc.py
As of DC/OS 1.11, IPv6 overlay network is optional. Hence, the
validation check shouldn't assert on the presence of IPv6 overlay.
This patch makes modifies the validation checks such that IPv6
overlay could be optional
- [DCOS-21095](https://jira.mesosphere.com/browse/DCOS-21095) Turn IPv6 Overlay Off in IPv4 Environment
___ …
=> Makes overlay IPv6 validation checks optional

owners.json
Prune owners. Remove @lingmann  and @adam-mesos  :-)
=> Prune Owners

gen/azure/templates/acs.json, gen/fault-domain-detect/cloud.sh
This fixes the Azure Templates for it to successfully deploy
- [https://jira.mesosphere.com/browse/DCOS-20064](https://jira.mesosphere.com/browse/DCOS-20064) Verify azure and aws advanced templates work with the licensing parameter
@branden  @amitaekbote
=> azure licensing fix

packages/marathon/buildinfo.json
* 1.5 migration buf fix
* AppDefiniton changes containing scaling to 0 instances are processes immediately now
* Region and Task related information is exposed via API
* v2/groups performance is greatly improved
* Updated mesos dependency to 1.5.0
* Important fixes
- [MARATHON-8015](https://jira.mesosphere.com/browse/MARATHON-8015) Validation error on applications configured with args on v1.5.0 persistence store migration.
- [MARATHON-8011](https://jira.mesosphere.com/browse/MARATHON-8011) 
Scaling to zero takes too much time in case of non-scaling related runspec changes.
- [MARATHON_EE-1849](https://jira.mesosphere.com/browse/MARATHON_EE-1849) Expose region and zone task info in API.
- …
=> Bump marathon to 1.6.322

dcos_installer/test_backend.py, gen/calc.py
Update the version string to 1.11.0 RC4
=> Up version to 1.11.0 RC4.

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Fixture that will download the diagnostics bundles if provided a directory via environment variable. Uses the `dcos_api_session` fixture because otherwise this would require installing and auth for the dcos CLI.
Change to TeamCity `dcos-launch test` template to get this to work:
- add environment variable `env.DIAGNOSTICS_DIRECTORY` which is set to `teamcityWorkingDir/diagnostics`
- add `teamcityWorkingDir/diagnostics` to artifacts paths
- add `env.DIAGNOSTICS_DIRECTORY` to `PYTEST_PASS_ENV` parameter
- add lines in 'run tests' build step to scp the diagnostics bundle back and then upload it as an artifact
Additionally, the 3 enterprise integration tests that inherit from the dcos-test-utils template need to have the `PYTEST_PASS_ENV` updated because they override the default from …
=> fixture for downloading diagnostics bundles

packages/dcos-ui/buildinfo.json
Update the DC/OS UI package to include the latest fixes, improvements and features.
- [DCOS-20247](https://jira.mesosphere.com/browse/DCOS-20247) Fix zone and region column
- [DCOS-20498](https://jira.mesosphere.com/browse/DCOS-20498) add broken link finding script
- [DCOS_OSS-2062](https://jira.mesosphere.com/browse/DCOS_OSS-2062) Change debug message from danger to warning
- [DCOS-20939](https://jira.mesosphere.com/browse/DCOS-20939) add version query
- [DCOS-19693](https://jira.mesosphere.com/browse/DCOS-19693) fix labels reducer to accept empty strings
- [DCOS-20948](https://jira.mesosphere.com/browse/DCOS-20948) keep unknown attributes
- [DCOS-20978](https://jira.mesosphere.com/browse/DCOS-20978) …
=> [master] chore(dcos-ui): update package

dcos_installer/test_backend.py, gen/calc.py
Update version string to 1.11.0
=> Update version string to 1.11.0-rc5

packages/dcos-cni/buildinfo.json
This is backport of #2492 
I have requested more information from @asridharan  on the late introduction of this feature. This may or may not be merged with 1.11.0 GA
=> bump dcos-cni

packages/mesos/README.md, packages/mesos/patches.json
A non-code update that makes it easier for tooling to find patches to apply on top of Apache Mesos.
=> Added patches.json that contains patch list for Mesos.

test_util/run-all
Upgrade dcos-vagrant so that it brings in this fix
* https://jira.mesosphere.com/browse/DCOS-21244
=> Update dcos-vagrant pinned version.

dcos_installer/test_backend.py, gen/calc.py
=> Update version string for 1.11.0-RC6

gen/__init__.py, gen/calc.py, gen/tests/test_gen.py, release/__init__.py
This adds a channel artifact containing the version string. Example: https://downloads.dcos.io/dcos/testing/pull/2488/version
- [DCOS_OSS-2146](https://jira.mesosphere.com/browse/DCOS_OSS-2146) Simplify getting the release version from a DC/OS build
___ …
=> Add version channel artifact

packages/dcos-ui/buildinfo.json
- [DCOS-20948](https://jira.mesosphere.com/browse/DCOS-20948): DC/OS UI removes CNI labels from network configuration
- [DCOS-21119](https://jira.mesosphere.com/browse/DCOS-21119): Jobs UI overwrites the id and the concurrency policy
___ …
=> chore(packages/dcos-ui): bump ui from 1.10.4 > 1.10.5

dcos_installer/test_backend.py, gen/calc.py
Setting the version string to 1.10.5-hotfix1
=> Set version to 1.10.5-hotfix1

gen/build_deploy/aws.py, gen/build_deploy/azure.py, gen/build_deploy/bash.py, gen/calc.py, gen/dcos-config.yaml, gen/ip-detect/aws6.sh, gen/ip-detect/azure6.sh, gen/ip-detect/vagrant6.sh, gen/tests/test_validate.py, gen/tests/utils.py, setup.py
Adds ip6-detect scripts for aws and azure. These scripts are similar to what we have for ipv4. 
In phase-1, these scripts would only be used by mesos-agent to be able to populate NetworkInfo for the containers that would be running on IPv6 in host mode.
- [DCOS_OSS-1044](https://jira.mesosphere.com/browse/DCOS_OSS-1044) Add an ip6-detect script to advertise IPv6 address on the host.
- [DCOS_OSS-1735](https://jira.mesosphere.com/browse/DCOS_OSS-1735) IPv6 for Docker Containers Only
___ …
=> Adds ip6-detect script

packages/cosmos/buildinfo.json
[DCOS-21374](https://jira.mesosphere.com/browse/DCOS-21374) Uninstaller shouldn't assume that the "env" field exists 
[DCOS_OSS-2087](https://jira.mesosphere.com/browse/DCOS_OSS-2087) Cosmos should uninstall the service and respond correctly in all cases.
[DCOS_OSS-2119](https://jira.mesosphere.com/browse/DCOS_OSS-2119) Delete raml and update release documentation
- [DCOS_OSS-2195](https://jira.mesosphere.com/browse/DCOS_OSS-2195) Release cosmos.
If you are changing components or …
=> Release cosmos v0.6.0-SNAPSHOT Build 334

gen/dcos-config.yaml
- update diagnostics bundle endpoints for mesos agent nodes
- remove diagnostics bundle endpoint for marathon
according to [conversation](https://mesosphere.slack.com/archives/C02CGA57K/p1512157577000089) with mesos core team, mesos agent endpoints `/slave/state` and `/slave/flags` has been renamed to `/state` and `/slave` accordantly. This PR does the renaming for diagnostics bundle.
According to this [improvement](https://jira.mesosphere.com/browse/MARATHON-7981)The marathon endpoint `/v2/eventSubscriptions` was renamed to `/v2/events`, however
according to [DCOS-20600](https://jira.mesosphere.com/browse/DCOS-20600) support team is not using logs from this endpoint and it can be removed from the bundle.
These changes already landed on EE DC/OS:
- [change mesos …
=> update diagnostics bundle endpoints

packages/marathon/buildinfo.json
- [MARATHON-8063](https://jira.mesosphere.com/browse/MARATHON-8063)
- [MARATHON-8086](https://jira.mesosphere.com/browse/MARATHON-8086)
- [MARATHON_EE-1791](https://jira.mesosphere.com/browse/MARATHON_EE-1791)
- [MARATHON-8045](https://jira.mesosphere.com/browse/MARATHON-8045)
- [MARATHON-8097](https://jira.mesosphere.com/browse/MARATHON-8097)
- [MARATHON-7751](https://jira.mesosphere.com/browse/MARATHON-7751)
=> Bump Marathon to 1.6.348-e45e6e08d.

gen/calc.py, gen/dcos-config.yaml, packages/dcos-net/extra/dcos-net-setup.py, packages/dcos-net/extra/dcos-net-watchdog.service, packages/dcos-net/extra/dcos-net.service
- [DCOS-21471](https://jira.mesosphere.com/browse/DCOS-21471) dcos-net not starting if IPv6 is disabled
___ …
=> [1.11.0-GA] dcos-net not starting if IPv6 is disabled

gen/calc.py, gen/dcos-config.yaml, packages/dcos-net/extra/dcos-net-setup.py, packages/dcos-net/extra/dcos-net-watchdog.service, packages/dcos-net/extra/dcos-net.service
dcos-net is not starting when IPv6 is disabled.
- [DCOS-21471](https://jira.mesosphere.com/browse/DCOS-21471) dcos-net not starting if IPv6 is disabled
___ …
=> [1.11] dcos-net not starting if IPv6 is disabled

packages/cosmos/buildinfo.json
[DCOS-21374](https://jira.mesosphere.com/browse/DCOS-21374) Uninstaller shouldn't assume that the "env" field exists 
- [DCOS_OSS-2195](https://jira.mesosphere.com/browse/DCOS_OSS-2195) Release cosmos.
___ …
=> Release cosmos v0.5.3

gen/calc.py, gen/dcos-config.yaml, packages/dcos-net/extra/dcos-net-setup.py, packages/dcos-net/extra/dcos-net-watchdog.service, packages/dcos-net/extra/dcos-net.service
dcos-net is not starting when IPv6 is disabled.
- [DCOS-21471](https://jira.mesosphere.com/browse/DCOS-21471) dcos-net not starting if IPv6 is disabled
___ …
=> dcos-net is not starting when IPv6 is disabled.

packages/dcos-ui/buildinfo.json
- [DCOS-21564](https://jira.mesosphere.com/browse/DCOS-21564): Revert "fix(createServiceModal): disabled review and run button"
- [DCOS-21361](https://jira.mesosphere.com/browse/DCOS-21361): fix(struct/Node): does not throw exception when resources are empty
- [DCOS-21362](https://jira.mesosphere.com/browse/DCOS-21362): chore(reactjs-components): update package to 0.20.3
- [DCOS-21359](https://jira.mesosphere.com/browse/DCOS-21359): fix(ServicesContainer): checks and updates modalProps if needed
- [DCOS_OSS-1341](https://jira.mesosphere.com/browse/DCOS_OSS-1341): feat(ServiceTree): stay in group view when service deleted …
=> chore(dcos-ui): update package to v1.11.0-rc.16

dcos_installer/test_backend.py, gen/calc.py
Update the version string to 1.11.0
=> update version to 1.11.0

dcos_installer/test_backend.py, gen/calc.py, packages/dcos-ui/buildinfo.json
* chore(dcos-ui): update package to v1.11.0-rc.16 #2574
* update version to 1.11.0 #2581
=> 1.11.0 Integration Train for UI Changes and Version Update.

dcos_installer/test_backend.py, gen/calc.py
Updating the version of dcos to 1.12-dev.
=> Updated version to 1.12-dev

packages/pytest/buildinfo.json
Upgrade the pytest pypi package version to `3.1.0` in `packages/pytest` (Was `3.0.3`). 
Initially, I tried upgrading to `3.4.2` but i learnt that `pytest` [stopped vendoring](https://docs.pytest.org/en/latest/changelog.html#id104) `pluggy` from `3.3.0` and I go [this error](https://teamcity.mesosphere.io/viewLog.html?buildId=994405&buildTypeId=DcOs_Open_Test_DcosDocker_DockerSmokeTests_SmokeTestDcosDockerPr&tab=buildLog&_focus=262). So If I were to upgrade to `3.4.2` the change won't be trivial. I also faced a different [error](https://teamcity.mesosphere.io/viewLog.html?buildId=994427&buildTypeId=DcOs_Open_Test_DcosDocker_DockerSmokeTests_SmokeTestDcosDockerPr&tab=buildLog&_focus=253) when I tried upgrading to …
=> Upgrade pytest to v3.1.0

packages/dcos-ui/buildinfo.json
* [DCOS-20158](https://jira.mesosphere.com/browse/DCOS-20158): update marked package
___
* Developers …
=> Update DCOS-UI to 1.8.11

gen/calc.py, tests/test_installer_backend.py
* Update version string to 1.8.11
=> Update version to 1.8.11

dcos_installer/test_backend.py, gen/calc.py
=> Update version to 1.9.8

packages/dcos-net/buildinfo.json
lashup_kv: fix a distributed deadlock, add backpressure, off heap message box
- [DCOS_OSS-2229](https://jira.mesosphere.com/browse/DCOS_OSS-2229) Investigate memory spikes during container churn in lashup
https://github.com/dcos/lashup/pull/39
___ …
=> [1.11] Bump dcos-net

packages/dcos-installer-ui/build, packages/dcos-installer-ui/buildinfo.json
Fix tests build and update gulp to 3.9.1.
- [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) dcos-installer-ui package failed to build
___ …
=> fix(dcos-installer-ui): fix tests build and update gulp

packages/marathon/buildinfo.json
=> marathon 1.5.7 bump

dcos_installer/upgrade.py
1.11 backport of https://github.com/dcos/dcos/pull/2270 
___ …
=> [1.11] Do not exit on error during bash loop for the upgrade script

dcos_installer/test_backend.py, gen/calc.py
Update 1.10 branch version to 1.10.6
=> Update version to 1.10.6

packages/dcos-checks/buildinfo.json
bump dcos-checks sha
- [DCOS_OSS-1878](https://jira.mesosphere.com/browse/DCOS_OSS-1878) Fix bug where `--detect-ip` parameter is ignored
- [DCOS-21703](https://jira.mesosphere.com/browse/DCOS-21703) Fix bug bash exit code not matching check status in case of Go err
N/A
___ …
=> bump dcos-checks sha

packages/mesos/buildinfo.json
This PR incorporates Mesos bug fixes and improvements.
- [MESOS-8488](https://issues.apache.org/jira/browse/MESOS-8488) Docker bug can cause unkillable tasks.
- [MESOS-8536](https://issues.apache.org/jira/browse/MESOS-8536) Pending offer operations on resource provider resources not properly accounted for in allocator.
- [MESOS-8550](https://issues.apache.org/jira/browse/MESOS-8550) Bug in `Master::detected()` leads to coredump in `MasterZooKeeperTest.MasterInfoAddress`.
- [MESOS-8574](https://issues.apache.org/jira/browse/MESOS-8574) Docker executor makes no progress when 'docker inspect' hangs.
- [MESOS-8575](https://issues.apache.org/jira/browse/MESOS-8575) Improve discard handling for 'Docker::stop' and 'Docker::pull'.
- …
=> Bumped Mesos SHA to the latest 1.5.x.

dcos_installer/test_backend.py, gen/calc.py
Update DC/OS version to 1.11.1
=> Update DC/OS version to 1.11.1

packages/dcos-ui/buildinfo.json
- [DCOS-21305](https://jira.mesosphere.com/browse/DCOS-21305): feat(Packages): respect minDcosReleaseVersion
- [DCOS-21440](https://jira.mesosphere.com/browse/DCOS-21440): fix(vips): keep VIP label
- [DCOS_OSS-2244](https://jira.mesosphere.com/browse/DCOS_OSS-2244): feat(task-details-tab): display task's ip addresses
- [DCOS-21190](https://jira.mesosphere.com/browse/DCOS-21190): fix(services-table): hide text if the service status is N/A
- [DCOS-19586](https://jira.mesosphere.com/browse/DCOS-19586): feat(podDetail): add volume views to podDetail
- [DCOS-21571](https://jira.mesosphere.com/browse/DCOS-21571): fix(moment): update …
=> Bump dcos-ui 1.11.1

pkgpanda/docker.windows/dcos-builder/Dockerfile
sourceforge.net SSL certs expired. Moving 2 tools to a git repo.
- [DCOS_OSS-2331](https://jira.mesosphere.com/browse/DCOS_OSS-2331) Windows pkgpanda docker container broken due to external tools SSL issue
___ …
=> fix windows docker file dependencies

packages/dcos-integration-test/extra/test_networking.py
Brings in changes from #2426
(Discussion is here: https://github.com/dcos/dcos/pull/2426#issuecomment-368958266)
=> Backport changes from #2426

packages/metronome/buildinfo.json
Metronome bump 0.5.0
- [DCOS_OSS-2338](https://jira.mesosphere.com/browse/DCOS_OSS-2338) Bump metronome to 0.5.0
=> metronome 0.5.0 bump

packages/metronome/buildinfo.json
Metronome bump 0.4.2 on DCOS 1.10.6
- [METRONOME-248](https://jira.mesosphere.com/browse/METRONOME-248)Metronome metrics breaking change
=> Metronome 0.4.2 with Secrets without breaking Metrics #2753

CHANGES.md
* Release Notes Proposal for DC/OS. https://jira.mesosphere.com/browse/QUALITY-1879 
This is our desired format for the change log. This gives guidelines on how to add change log entries and adds entries to already committed changes in 1.12. 
As new features are added, reviewers could request developers to add an entry to this file following the suggested format. 
Note - The format, style and the methodology is work in progress during early 1.12 timeframe.  We will evolve it as realize the improvements that can be made to this process.
=> Add Changelog Entries for 1.12 release.

pkgpanda/build/__init__.py, pkgpanda/build/tests/build_integration_test.py, pkgpanda/build/tests/resources/buildhash/hashcheck1/build, pkgpanda/build/tests/resources/buildhash/hashcheck1/buildinfo.json, pkgpanda/build/tests/resources/buildhash/hashcheck2/build, pkgpanda/build/tests/resources/buildhash/hashcheck2/buildinfo.json, pkgpanda/build/tests/resources/buildhash/hashcheck3/build, pkgpanda/build/tests/resources/buildhash/hashcheck3/buildinfo.json
This PR fixes a regression introduced in https://github.com/dcos/dcos/pull/2445 where the package build script contents are no longer considered as part of the package hash for purposes of reusing cached artifacts.
I ran the tests manually as they are not run by CI as of today:
```
[gustav@gpaul-dell dcos]$ tox -e py35-pkgpanda-build
GLOB sdist-make: /home/gustav/repos/dcos/dcos/setup.py
py35-pkgpanda-build inst-nodeps: /home/gustav/repos/dcos/dcos/.tox/dist/dcos_image-0.1.zip
py35-pkgpanda-build installed: adal==0.4.7,aiohttp==0.22.5,analytics-python==1.2.9,asn1crypto==0.24.0,attrs==17.4.0,azure-common==1.1.4,azure-mgmt-network==0.30.0rc4,azure-mgmt-nspkg==2.0.0,azure-mgmt-resource==0.30.0rc4,azure-nspkg==2.0.0,azure-s …
```
=> pkgpanda/build: hash build script contents

packages/cosmos/buildinfo.json
- Upgraded cosmos dependencies to latest versions
- Cosmos now extracts default options from config.json efficiently - by initializing optional json objects to be "null (non existent)" instead of empty. [DCOS_OSS-2223](https://jira.mesosphere.com/browse/DCOS_OSS-2223).
- [DCOS_OSS-2223](https://jira.mesosphere.com/browse/DCOS_OSS-2223) Cosmos should extract defaults from schema intelligently …
=> Bump cosmos to latest snapshot version

packages/dcos-net/buildinfo.json, packages/erlang/buildinfo.json
Upgrade OTP version.
- [DCOS_OSS-2378](https://jira.mesosphere.com/browse/DCOS_OSS-2378) Upgrade OTP version.
___ …
=> [1.11] Upgrade OTP version

pkgpanda/util.py
This is a 1.11 backport of #2685.
- [DCOS_OSS-2317](https://jira.mesosphere.com/browse/DCOS_OSS-2317) Pkgpanda lack of retries when downloading packages.
=> (1.11) Add retries for pkgpanda when downloading packages

packages/dcos-ui/buildinfo.json
* [DCOS-22215](http://jira.mesosphere.com/browse/DCOS-22215) **DSLInputField:** adjust change event handling ([c227b22](https://github.com/dcos/dcos-ui/commit/c227b22)) 
* [DCOS-21798](http://jira.mesosphere.com/browse/DCOS-21798) **editservicemodal:** render empty modal if the service is not loaded ([bd2d9e9](https://github.com/dcos/dcos-ui/commit/bd2d9e9)) 
* [DCOS-22128](http://jira.mesosphere.com/browse/DCOS-22128) **marathonUtil:** fix parsePod function ([d4373f5](https://github.com/dcos/dcos-ui/commit/d4373f5)) 
* [DCOS-22301](http://jira.mesosphere.com/browse/DCOS-22301) **MesosStateStore:** add linearBackoff retry to the …
=> chore(dcos-ui): bump DC/OS UI package to 1.11+v1.12.0

dcos_installer/test_backend.py, gen/calc.py
=> Update version to 1.11.2

packages/dcos-ui/buildinfo.json
* DCOS-19693: fix(labelsReducer): fix labels reducer to accept empty strings
* feat(babel): allow stage-3 syntax
* DCOS-21412: fix(PodStorageConfigSection): fix variable reference
* DCOS-19219: fix(PodStorageConfigSection): fix variable reference
* DCOS-21122: fix(ServiceForm): fixes focus/change/blur behavior
___ …
=> chore(dcos-ui): update dcos-ui to 1.10.6

packages/dcos-integration-test/extra/test_networking.py
As noted this in this comment - https://github.com/dcos/dcos/pull/2426#issuecomment-368958266 
this commit brings the changes from https://github.com/dcos/dcos/pull/2426
It could not be cherrypicked as the change spawned across 8 commits.
=> Backport test_networking changes

packages/dcos-ui/buildinfo.json
Fix npmshrinkwrap
[DCOS-19693](https://jira.mesosphere.com/browse/DCOS-19693): fix labels reducer to accept empty strings
___
* Developers responsible for code that interacts with or depends on the …
=> Bump dcos-ui 1.9.6 in 1.9 release

packages/dcos-history/extra/history/server_util.py
This is a 1.9 backport of #2829
- [DCOS_OSS-2422](https://jira.mesosphere.com/browse/DCOS_OSS-2422) test_history_service is failing on master
=> (1.9) Fix flask-compress import

owners.json
Remove non-mesosphere accounts from owners.
___ …
=> remove owners who no longer work at mesosphere

owners.json
This patch adds owners from the pool of Apache Mesos committers. Three people are in three different timezones and hence cover Apache Mesos ownership pretty well. 
- none.
- none
___
* Developers …
=> Add owners from the Mesos pool of committers.

gen/dcos-config.yaml, packages/dcos-history/extra/history/server_util.py, packages/dcos-net/extra/dcos-net-setup.py, packages/dcos-net/extra/dcos-net.service, packages/mesos/extra/start_mesos.sh
Add support for CoreOS 1688.4.0
- [DCOS_OSS-2417](https://jira.mesosphere.com/browse/DCOS_OSS-2417) Add support for CoreOS 1688.4.0
___
* …
=> Add support for CoreOS 1688.4.0

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/test_dcos_diagnostics.py
**This is a backport of @Margaret 's work from https://github.com/dcos/dcos/pull/2411**
This is tracked by https://jira.mesosphere.com/browse/DCOS-22384.
Description from that PR:
```
High-level description
Fixture that will download the diagnostics bundles if provided a directory via environment variable. Uses the dcos_api_session fixture because otherwise this would require installing and auth for the dcos CLI.
Change to TeamCity dcos-launch test template to get this to work:
add environment variable env.DIAGNOSTICS_DIRECTORY which is set to teamcityWorkingDir/diagnostics
add teamcityWorkingDir/diagnostics to artifacts paths
add env.DIAGNOSTICS_DIRECTORY to PYTEST_PASS_ENV parameter
add lines in 'run tests' build step to scp the diagnostics bundle back and then upload it as an artifact …
```
=> [1.11][DCOS-22384] Dump diagnostics bundles for TeamCity artifacts

CHANGES.md
This removes a changelog entry that was reversed with https://github.com/dcos/dcos/pull/2705.
N/A
=> Remove REX-Ray 0.11.2 upgrade from changelog

packages/metronome/buildinfo.json
Metronome bump 0.4.2 on DCOS 1.10.6
- [METRONOME-248](https://jira.mesosphere.com/browse/METRONOME-248)Metronome metrics breaking change
=> Metronome 0.4.2 bump on Master

packages/mesos/README.md, packages/mesos/build, packages/mesos/buildinfo.json, packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch, packages/mesos/extra/patches/0002-Mesos-UI-Change-paths-pailer-and-logs-to-work-with-a.patch, packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch, packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch, packages/mesos/extra/patches/0005-Included-nested-command-check-output-in-the-executor.patch, packages/mesos/extra/patches/0006-Made-the-log-output-handling-of-TCP-and-HTTP-checks-.patch, packages/mesos/extra/patches/0007-Raised-the-logging-level-of-some-check-and-health-ch.patch
This is similar to the changes made to the master branch via #2824.
There are no new patches. This PR just replaces the previous dcos-mesos branch with upstream Mesos SHA + a set of patches.
___ …
=> [1.10] Updated Mesos patches to extra/patches directory.

packages/dcos-ui/buildinfo.json
DCOS-34561: flatten the service tree to avoid extra lookups
DCOS-37420: adjust Framework struct to improve performance
DCOS-37422: adjust flagSDKTask to improve performance
DCOS-37423: improve performance of composite store nodes list getter
DCOS-35759: throttle mesos state fetching
DCOS-37421: Adjust GetSetBaseStore to stop dispatching events on every change
DCOS-35757: remove 2 seconds timeout
DCOS-22400,DCOS-22404: update login and user for privacy policy
___
All PRs …
=> Bump 1.10 to 1.10.7

CHANGES.md
This changelog is derived from the changes that are present in 1.10.7 branch
```
git log --left-right --graph --cherry-pick --oneline 1.10.7...1.10.6
```
And I included the changes that we are bringing in to 1.10.7
=> 1.10.7 Changelog

CHANGES.md, packages/dcos-ui/buildinfo.json
- [DCOS-22215](https://jira.mesosphere.com/browse/DCOS-22215) **DSLInputField:** adjust change event handling ([c227b22](https://github.com/dcos/dcos-ui/commit/c227b22))
- [DCOS-21798](https://jira.mesosphere.com/browse/DCOS-21798) **editservicemodal:** render empty modal if the service is not loaded ([bd2d9e9](https://github.com/dcos/dcos-ui/commit/bd2d9e9))
- [DCOS-22128](https://jira.mesosphere.com/browse/DCOS-22128) **marathonUtil:** fix parsePod function ([d4373f5](https://github.com/dcos/dcos-ui/commit/d4373f5))
- [DCOS-22301](https://jira.mesosphere.com/browse/DCOS-22301) **MesosStateStore:** add linearBackoff retry to the …
=> chore(dcos-ui): bump package to 1.11+1.13.0

setup.py
Pins urllib3 in setup.py to 1.22. 1.23 was released last night, but requests library requires 1.22.
1.11 backport: https://github.com/dcos/dcos/pull/2950
1.10 didn't have urllib3 in the setup and running tox on that again doesn't have the error https://teamcity.mesosphere.io/viewLog.html?buildId=1093391&buildTypeId=DcOs_Open_Build_Tox&tab=buildLog&_focus=234#_state=234
1.9 also doesn't need the backport https://teamcity.mesosphere.io/viewLog.html?buildId=1093420&tab=buildResultsDiv&buildTypeId=DcOs_Open_Build_Tox
- https://jira.mesosphere.com/browse/DCOS_OSS-3603
N/A …
=> pin urllib3 to 1.22 for compatibility with requests

setup.py
Backport of https://github.com/dcos/dcos/pull/2949
___ …
=> pin urllib3 to 1.22 to be compatible with requests

packages/cosmos/buildinfo.json
Increase client payload limit when cosmos is talking to marathon.
- [DCOS-34435](https://jira.mesosphere.com/browse/DCOS-34435) Cosmos is limited to loading a max payload of 5MB when talking to /v2/apps from Marathon. Increase this limit.
___ …
=> Bump cosmos to v0.5.4

packages/marathon/buildinfo.json
Marathon 1.6.496 bump
- [MARATHON-8149](https://jira.mesosphere.com/browse/MARATHON-8149) Fix links to DC/OS documentation.
- [MARATHON-8151](https://jira.mesosphere.com/browse/MARATHON-8151) Track mesos offer requests.
- [MARATHON-8148](https://jira.mesosphere.com/browse/MARATHON-8148) Pod failure reasons are not visible in the UI/API.
- [MARATHON-8172](https://jira.mesosphere.com/browse/MARATHON-8172) Limit max number of concurrently running deployments.
- [MARATHON-8174](https://jira.mesosphere.com/browse/MARATHON-8174) Upgrade to Jersey 2.27.
- [MARATHON-8200](https://jira.mesosphere.com/browse/MARATHON-8200) Default to application/json when Accept */* provided.
- …
=> bump marathon 1.6.496

CHANGES.md, packages/dcos-ui/buildinfo.json
- [See Changelog](https://github.com/dcos/dcos-ui/blob/1.11+v1.14.0/CHANGELOG.md)
___ …
=> [1.11] Bump DC/OS UI to 1.11+v1.14.0

owners.json
Remove non-mesosphere accounts from owners. 
/cc @asridharan 
___
* Developers responsible for code that interacts with or depends on the code …
=> Prune owners.json

packages/dcos-ui/buildinfo.json
- [DCOS-37558](https://jira.mesosphere.com/browse/DCOS-37558): Remove track.js calls
- [DCOS-22399](https://jira.mesosphere.com/browse/DCOS-22399), [DCOS-22403](https://jira.mesosphere.com/browse/DCOS-22403): Update privacy policy integration
___ …
=> chore(dcos-ui): update package to 1.9.7

CHANGES.md, gen/calc.py, gen/dcos-config.yaml, packages/dcos-integration-test/extra/util/delete_ec2_volume.py, packages/marathon/build, packages/marathon/extra/marathon.sh, packages/mesos/buildinfo.json, packages/rexray/build, packages/rexray/buildinfo.json, packages/rexray/extra/dcos-rexray.service
* Merge #2883
* Merge #2918
* Merge #2966
=> DC/OS Merge train for 1.11

packages/cosmos/buildinfo.json
Increase client payload limit when cosmos is talking to marathon.
- [DCOS-34435](https://jira.mesosphere.com/browse/DCOS-34435) Cosmos is limited to loading a max payload of 5MB when talking to /v2/apps from Marathon. Increase this limit.
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS …
=> Bump cosmos to v0.4.4

packages/dcos-ui/buildinfo.json
[DCOS-21266](https://jira.mesosphere.com/browse/DCOS-21266) Switching files in the UI does not work correctly
[DCOS-37516](https://jira.mesosphere.com/browse/DCOS-37516) Change flagSDKTask to mutate the task instead of copying
[DCOS-37472](https://jira.mesosphere.com/browse/DCOS-37472) [1.10] Change MesosStateStore to apply assignSchedulerTaskField once
[DCOS-37585](https://jira.mesosphere.com/browse/DCOS-37585) [1.10] Marathon Health Checks results not being shown
[DCOS-37464](https://jira.mesosphere.com/browse/DCOS-37464) Adjust DCOSStore to cache the serviceTree and taskLookupTable …
=> [1.10] Bump dcos-ui v1.10.8

owners.json
This is to update the dcos owners list. It adds dgoel and removes avinash
=> update owners list

CHANGES.md, gen/calc.py
Update checks timeouts
https://jira.mesosphere.com/browse/DCOS_OSS-2277
___
It is best to …
=> [1.11] Update checks timeout

gen/dcos-config.yaml
This patch adds few network related information to be collected as part of diagnostics bundle. 
- [DCOS_OSS-3613](https://jira.mesosphere.com/browse/DCOS_OSS-3613) Improve diagnostics bundle to include information that would help debugging network issues
___
All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/) …
=> Adds network information to be collected as part of diagnostic bundle

packages/dcos-integration-test/extra/conftest.py, packages/dcos-integration-test/extra/test_applications.py, packages/dcos-integration-test/extra/test_auth.py, packages/dcos-integration-test/extra/test_composition.py, packages/dcos-integration-test/extra/test_dcos_diagnostics.py, packages/dcos-integration-test/extra/test_endpoints.py, packages/dcos-integration-test/extra/test_helpers.py, packages/dcos-integration-test/extra/test_mesos.py, packages/dcos-integration-test/extra/test_metrics.py, packages/dcos-integration-test/extra/test_misc.py, packages/dcos-integration-test/extra/test_rexray.py, packages/dcos-integration-test/extra/test_units.py
This pull request adds Windows support for some of the current integration tests.
- [DCOS_OSS-2078](https://jira.mesosphere.com/browse/DCOS_OSS-2078) Integrate Hybrid DC/OS Cluster into CI/CD.
=> Add Windows support to integration tests 

gen/dcos-config.yaml
This patch adds few network related information to be collected as part of diagnostics bundle.
- [DCOS_OSS-3613](https://jira.mesosphere.com/browse/DCOS_OSS-3613) Improve diagnostics bundle to include information that would help debugging network issues
___ …
=> [Backport/1.10] Adds network information to be collected as part of diagnostic bundle

packages/mesos/buildinfo.json, packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch, packages/mesos/extra/patches/0002-Mesos-UI-Change-paths-pailer-and-logs-to-work-with-a.patch, packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch, packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch, packages/mesos/extra/patches/0005-Included-nested-command-check-output-in-the-executor.patch, packages/mesos/extra/patches/0006-Made-the-log-output-handling-of-TCP-and-HTTP-checks-.patch, packages/mesos/extra/patches/0007-Raised-the-logging-level-of-some-check-and-health-ch.patch, packages/mesos/extra/patches/0008-Improved-logging-for-offers-and-inverse-offers.patch
This is a routine bump to the latest Mesos and mesos-modules. It also includes an extra patch to improve the logging of offers in Mesos.
- [DCOS-39092](https://jira.mesosphere.com/browse/DCOS-39092) Bump Mesos for MESOS-8830.
- [DCOS-38662](https://jira.mesosphere.com/browse/DCOS-38662) Make Mesos optionally log offers sent to frameworks.
- [DCOS-38603](https://jira.mesosphere.com/browse/DCOS-38603) Improve Mesos allocator performance.
- [DCOS-38599](https://jira.mesosphere.com/browse/DCOS-38599) Backport fix for quota limit "chopping" leading to cpu-only and memory-only offers.
- [DCOS-27982](https://jira.mesosphere.com/browse/DCOS-27982) Backport quota fixes.
- …
=> [1.10] Bump Mesos to 1.4.x 5f6d4cd

CHANGES.md, packages/marathon/buildinfo.json
MARATHON-8311 Metrics for suppress operations.
MARATHON-8304 Activate HeartbeatMonitor before Marathon is connected to Mesos.
MARATHON-8310 Ignore MARATHON_APP_ env vars.
- [DCOS-39258](https://jira.mesosphere.com/browse/DCOS-39258) Release Marathon 1.5.11 for DC/OS 1.10.
___ …
=> Bump 1.10 to Marathon 1.5.11

gen/dcos-config.yaml
This patch adds few network related information to be collected as part of diagnostics bundle.
- [DCOS_OSS-3613](https://jira.mesosphere.com/browse/DCOS_OSS-3613) Improve diagnostics bundle to include information that would help debugging network issues
___ …
=> [Backport/1.11] Adds network information to be collected as part of diagnostic bundle

packages/dcos-ui/buildinfo.json
- [DCOS_OSS-3687](https://jira.mesosphere.com/browse/DCOS_OSS-3687): Support docker parameters
___
It is …
=> chore(dcos-ui): update package to 1.9.8

dcos_installer/test_backend.py, gen/calc.py
=> Update version to 1.10.8

packages/mesos/buildinfo.json
This is a Mesos bump to include [MESOS-8830](https://issues.apache.org/jira/browse/MESOS-8830).
=> [1.9] Bump Mesos to mesosphere/1.2.x 6e1adf7

dcos_installer/test_backend.py, gen/calc.py
=> update version to 1.9.10

packages/marathon/buildinfo.json
- [MARATHON-8317](https://jira.mesosphere.com/browse/MARATHON-8317) Marathon Bump of 1.6 on DCOS 1.11.
- [MARATHON-8259](https://jira.mesosphere.com/browse/MARATHON-8259) Deprecate /v2/events heavy event format.
- [PR-6288](https://github.com/mesosphere/marathon/pull/6288) Include gzipped data in metrics.
- [DCOS-38317](https://jira.mesosphere.com/browse/DCOS-38317) Reschedule resident task during a deployment with failing health.
- [MARATHON-8264](https://jira.mesosphere.com/browse/MARATHON-8264) Add bytesWritten counter to metrics.
- …
=> Marathon 1.6 Bump

dcos_installer/test_backend.py, gen/calc.py
=> Set DC/OS version to 1.11.4

CHANGES.md, packages/dcos-ui/buildinfo.json
Update DCOS-UI package v1.11+v1.15.0+3231764b
- Updated to [DC/OS UI 1.11+v1.15.0](https://github.com/dcos/dcos-ui/blob/1.11+v1.15.0/CHANGELOG.md)
___ …
=> Dcos ui/v1.11+v1.15.0+3231764b

owners.json
Adding gauripowale from the Testing team as a dcos owner.
=> Adding gauripowale as a dcos owner.

gen/calc.py, gen/dcos-config.yaml, owners.json, packages/adminrouter/extra/src/lib/cache.lua, packages/adminrouter/extra/src/test-harness/tests/test_cache.py, packages/mesos-modules/buildinfo.json, packages/mesos/build, packages/mesos/buildinfo.json, packages/mesos/extra/dcos-mesos-slave-public.service, packages/mesos/extra/dcos-mesos-slave.service, packages/mesos/extra/upgrade_cni.py
* Adds dataDir to ucr bridge cni configuration #3092
* Adding gauripowale as a dcos owner. #3014
* Bump Mesos to nightly master 9147283  #3124
* [1.12/master] Use ngx.timer.every() for the AR cache update #3064
=> 1.12 master train

packages/adminrouter/extra/src/includes/main/agent.conf, packages/adminrouter/extra/src/includes/main/common.conf, packages/adminrouter/extra/src/includes/main/master.conf, packages/adminrouter/extra/src/nginx.agent.conf, packages/adminrouter/extra/src/nginx.master.conf
Back-port of #2866
This PR increases the limit on the number of connections (worker_connections) to 10K for Admin Router.
https://jira.mesosphere.com/browse/SOAK-80
___ …
=> [1.10] Increased the limit on worker_connections to 10K for Agent AR

packages/adminrouter/extra/src/lib/cache.lua
This PR removes an extra comment for AR cache lua code to keep the docs readable.
https://jira.mesosphere.com/browse/DCOS-39104
___ …
=> Corrected comment to keep the docs readable

CHANGES.md, packages/dcos-ui/buildinfo.json
Updated to [DC/OS UI 1.10.9-rc.1](https://github.com/dcos/dcos-ui/releases/tag/v1.10.9-rc.1)
- [DCOS_OSS-3800](https://jira.mesosphere.com/browse/DCOS_OSS-3800) Support docker parameters 
- [DCOS-39282](https://jira.mesosphere.com/browse/DCOS-39282) Show allocated resources
- [DCOS-39661](https://jira.mesosphere.com/browse/DCOS-39661) Refactor ServiceDebugContainer: check instance type
___ …
=> Bump dcos-ui to 1.10.9-rc.1

CHANGES.md, gen/dcos-config.yaml, packages/dcos-integration-test/extra/test_mesos.py, packages/mesos/build
This pull request enables usage of the memory profiling support that was introduced with Mesos 1.6.
It consists of three commits:
- The first consists of preparatory cleanup work
- The second changes the Mesos build to use the jemalloc memory allocator by default, to improve general performance of the `mesos-master` and `mesos-agent` binaries.
- The third enables support for capturing memory profiles using a libprocess endpoint.
- [DCOS_OSS-2137](https://jira.mesosphere.com/browse/DCOS_OSS-2137) Enable Mesos memory profiling in DC/OS images. …
=> Enable Mesos jemalloc and memory profiling support in DC/OS

CHANGES.md, packages/dcos-ui/buildinfo.json
Updated to [DC/OS UI 1.11+v1.16.0](https://github.com/dcos/dcos-ui/blob/1.11+v1.16.0/CHANGELOG.md)
- [DCOS_OSS-3801](https://jira.mesosphere.com/browse/DCOS_OSS-3801) - Support docker parameters in Metronome
- [DCOS-39662](https://jira.mesosphere.com/browse/DCOS-39662) - Refactor ServiceDebugContainer
___ …
=> Bump ui to 1.11+v1.16.0

packages/mesos/windows.buildinfo.json
Windows build is currently broken because the commit hash for dcos-mesos no longer refers to a valid commit. This changes the commit hash to the same value as linux
- DCOS_OSS-3950 - CI for dcos/dcos build should be failing due to build break in windows
___
**What is the review process and when will …
=> Fix windows build of mesos package

CHANGES.md, packages/dcos-ui/buildinfo.json
Updated to DC/OS UI [1.11+v1.17.0](https://github.com/dcos/dcos-ui/blob/1.11%2Bv1.17.0/CHANGELOG.md)
- [DCOS-38595](https://jira.mesosphere.com/browse/DCOS-38595) Display Error with JSON when schema.properties is undefined
None
___ …
=> Bump ui to 1.11+v1.17.0

packages/dcos-metrics/build, packages/dcos-metrics/buildinfo.json
This brings the dcos-metrics build reference up to date with the latest state of dcos-metrics. It should help enable testing and development until the telegraf replacement PR lands. 
- [DCOS-39811](https://jira.mesosphere.com/browse/DCOS-39811) [Mixed Workload] Bring metrics fixes in 1.10 and 1.11 fixes to master
- [DCOS-22194](https://jira.mesosphere.com/browse/DCOS-22194) Fix dcos-metrics pkgpanda build
- [DCOS-21663](https://jira.mesosphere.com/browse/DCOS-21663) Overhaul docs for DC/OS Metrics
- [DCOS_OSS-2360](https://jira.mesosphere.com/browse/DCOS_OSS-2360) - Metric names can begin with numbers in dcos-metrics Prometheus endpoint
- …
=> Bump dcos-metrics

packages/marathon/buildinfo.json
- [DCOS_OSS-3980](https://jira.mesosphere.com/browse/DCOS_OSS-3980) Marathon 1.7.81 bump on DC/OS 1.12.
- [MARATHON-7568](https://jira.mesosphere.com/browse/MARATHON-7568) /v2/info leak some ZK credentials
- [DCOS-40232](https://jira.mesosphere.com/browse/DCOS-40232) Fix migration to 1.6
- [MARATHON-7390](https://jira.mesosphere.com/browse/MARATHON-7390) Marathon Unable to Connect to Zookeeper - No Retries
- [MARATHON-8084](https://jira.mesosphere.com/browse/MARATHON-8084) Properly forward HTTP requests from proxy
- [MARATHON-8183](https://jira.mesosphere.com/browse/MARATHON-8183) Fix log line …
=> bump marathon 1.7.81

CHANGES.md, packages/dcos-ui/buildinfo.json
Updated to DC/OS UI [1.11+v1.18.0](https://github.com/dcos/dcos-ui/blob/1.11%2Bv1.18.0/CHANGELOG.md)
- [DCOS-39877: DSL Filter in the tasks view only works with completed](https://jira.mesosphere.com/browse/DCOS-39877)
- [DCOS-40523: On config edit, strips env entries with empty values, breaking services](https://jira.mesosphere.com/browse/DCOS-40523)
___
**What is the review process and when will my …
=> DC/OS UI: 1.11+v1.18.0

CHANGES.md, packages/dcos-ui/buildinfo.json
- [DCOS-39720](https://jira.mesosphere.com/browse/DCOS-39720)
___
* …
=> chore(dcos-ui): bump DC/OS UI v1.19.0

dcos_installer/test_backend.py, gen/calc.py
Update DC/OS version for 1.11 branch to 1.11.5
=> Update DC/OS version to 1.11.5

CHANGES.md, dcos_installer/test_backend.py, gen/calc.py, packages/dcos-history/extra/history/server_util.py, packages/dcos-history/extra/test_history_service.py, packages/dcos-integration-test/extra/test_networking.py, packages/dcos-ui/buildinfo.json, packages/mesos/buildinfo.json
* Merge #3296
* Merge #3295
* Merge #3292
* Merge #3284
* Merge #3283
* Merge #3255
=> 1.11 train aug 20

packages/dcos-integration-test/extra/test_packaging.py
- [DCOS-18957](https://jira.mesosphere.com/browse/DCOS-18957) Adds a Marathon on Marathon (MoM) integration test.
=> mom integration test

packages/metronome/buildinfo.json
Migration fix https://jira.mesosphere.com/browse/DCOS-39324
- [DCOS-39324](https://jira.mesosphere.com/browse/DCOS-39324) Updating migration
- [DCOS-39324](https://jira.mesosphere.com/browse/DCOS-39324) Updating migration
=> Update to Metronome 0.4.4

packages/metronome/buildinfo.json
Migration fix https://jira.mesosphere.com/browse/DCOS-39324
- [DCOS-39324](https://jira.mesosphere.com/browse/DCOS-39324) Updating migration
- [DCOS-39324](https://jira.mesosphere.com/browse/DCOS-39324) Updating migration
=> Bump metronome to 0.4.4

CHANGES.md, packages/dcos-ui/buildinfo.json
New version of DC/OS UI with bug fixes
- [DCOS-40638](https://jira.mesosphere.com/browse/DCOS-40638) Firefox icon overflow fix
- [DCOS-40579](https://jira.mesosphere.com/browse/DCOS-40579) Avoid duplication of container names
___
* …
=> chore(dcos-ui): bump DC/OS UI 1.11+v1.20.0

CHANGES.md, packages/dcos-ui/buildinfo.json
Bug fix related to showing frameworks debug information
- [DCOS-22291](https://jira.mesosphere.com/browse/DCOS-22291) Marathon-LB Debug page no longer shows deployment problems	
___
* Developers …
=> chore(dcos-ui):  bump DC/OS UI 1.9+v1.9.11-rc1

gen/calc.py, gen/dcos-config.yaml
Adds a piece of config to enable intercom.io for the beta phase
[DCOS-40519](https://jira.mesosphere.com/browse/DCOS-40519) - Add a DC/OS UI Intercom plugin
___
It is best to …
=> feat: enable intercom ui plugin

packages/cosmos/buildinfo.json
This change support custom managers in cosmos for k8s team. See [DCOS-39579](https://jira.mesosphere.com/browse/DCOS-39579)
- PR addresses all tickets under [DCOS-39579](https://jira.mesosphere.com/browse/DCOS-39579): Route package/install, package/uninstall, service/update, service/describe requests to custom managers when needed …
=> Support custom managers in cosmos

mergebot-config.json
* DCOS-18174 - (Design) Associate Pull Requests against releases using Mergebot.
* DCOS-39388 - Update fixVersion and comment on JIRA when PR is merged using mergebot
This configuration will support mergebot updating the fixVersions when the PR is merged.
=> Mergebot config to support fixVersions

gen/dcos-config.yaml
Disable a watchdog for stuck processes.
- [DCOS-38600](https://jira.mesosphere.com/browse/DCOS-38600) Deadlock when SSL sockets are simultaneously sending/receiving data and buffers are full.
- [SOAK-112](https://jira.mesosphere.com/browse/SOAK-112) l4lb and autoip address not connectable - constantly failing tasks.
___ …
=> [1.11.5] Disable a watchdog for stuck processes

gen/dcos-config.yaml
Disable a watchdog for stuck processes.
- [DCOS-38600](https://jira.mesosphere.com/browse/DCOS-38600) Deadlock when SSL sockets are simultaneously sending/receiving data and buffers are full.
- [SOAK-112](https://jira.mesosphere.com/browse/SOAK-112) l4lb and autoip address not connectable - constantly failing tasks.
___ …
=> Disable a watchdog for stuck processes

CHANGES.md, packages/dcos-ui/buildinfo.json
- [DCOS-39896](https://jira.mesosphere.com/browse/DCOS-39896) Add Region Information to Services Struct
- [DCOS-39897](https://jira.mesosphere.com/browse/DCOS-39897) add regions table column
- [DCOS-40691](https://jira.mesosphere.com/browse/DCOS-40691) in services table, region column uses Tooltip component
___ …
=> chore(dcos-ui): bump DC/OS UI master+v2.18.0

CHANGES.md, packages/dcos-ui/buildinfo.json
Fixes the support to environment variables on services when the variable is empty
- [DCOS-40525](https://jira.mesosphere.com/browse/DCOS-40525) This fixes the environment variables reducer to support empty values.
- [ x ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
___
**PLEASE …
=> chore(dcos-ui): bump DC/OS UI 1.10+v1.10.9-rc2

packages/metronome/buildinfo.json
- [DCOS_OSS-4018](https://jira.mesosphere.com/browse/DCOS_OSS-4018) Metronome 0.5.3 bump on DCOS 1.12.
=> metronome 0.5.3 bump

CHANGES.md, docs/admin-ports.md, gen/build_deploy/bash.py, gen/calc.py, gen/dcos-config.yaml, packages/adminrouter/extra/src/README.md, packages/adminrouter/extra/src/docs/api/nginx.agent.yaml, packages/adminrouter/extra/src/docs/api/nginx.master.yaml, packages/adminrouter/extra/src/includes/http/agent.conf, packages/adminrouter/extra/src/includes/http/master.conf, packages/adminrouter/extra/src/test-harness/modules/mocker/common.py, packages/adminrouter/extra/src/test-harness/tests/test_generic.config.yml, packages/dcos-integration-test/extra/test_composition.py, packages/dcos-integration-test/extra/test_metrics.py, packages/dcos-metrics/build, packages/mesos-modules/buildinfo.json, packages/telegraf/build, packages/telegraf/buildinfo.json, packages/telegraf/extra/dcos-telegraf.service, packages/telegraf/extra/dcos-telegraf.socket, packages/telegraf/extra/start_telegraf.sh, packages/telegraf/extra/tools/migrate_containers_dir.sh
This PR adds plugins to telegraf which gather metrics from Mesos about containers and from tasks running on containers via Mesos. It also adds a plugin which tags metrics with dcos primitives - name service, executor and task name. Finally it adds configuration for a prometheus plugin to expose these metrics. 
Finally, it moves dcos-metrics' prometheus producer to a different port ahead of removing it entirely (this work will come in a separate plugin).
- [DCOS_OSS-3714](https://jira.mesosphere.com/browse/DCOS_OSS-3714) - Adopt Telegraf as the DC/OS metrics pipeline
- [DCOS_OSS-3716](https://jira.mesosphere.com/browse/DCOS_OSS-3716) - Write a Telegraf input plugin to get data for each container
- …
=> [WIP] Add plugins to Telegraf

packages/cosmos/buildinfo.json
- various bug fixes and enhancements for cosmos custom package managers to support multi-kubernetes
- fix regression in repository/add package/describe flow
[DCOS-4125](https://jira.mesosphere.com/browse/DCOS-41235)
[DCOS-41118](https://jira.mesosphere.com/browse/DCOS-41118) …
=> Fix various cosmos issues

packages/mesos-modules/buildinfo.json, packages/mesos/buildinfo.json, packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch, packages/mesos/extra/patches/0002-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch, packages/mesos/extra/patches/0003-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch, packages/mesos/extra/patches/0004-Revert-Removed-long-ago-deprecated-endpoints.patch
https://github.com/apache/mesos/compare/9127c792c5a20aee2f31a2e56854c2490a9ca608...6a98857cf429580b72cd97ddd749a074c3e4524d
https://github.com/dcos/dcos-mesos-modules/compare/26d11daee118055ab0975b0eaa0a25b6cf1a35c3...29561f11a12372752b77839be73418d1d75abe63
=> [master] Bump Mesos to nightly master 6a98857

CHANGES.md, packages/dcos-ui/buildinfo.json
Fixes a possible privacy issue with intercom.
- [DCOS-41283](https://jira.mesosphere.com/browse/DCOS-41283) Intercom: user is only identified by username
- [DCOS-41229](https://jira.mesosphere.com/browse/DCOS-41229) Jest Snapshots are outdated / tests fail
- [DCOS-40899](https://jira.mesosphere.com/browse/DCOS-40899) Make the Nodes dashboard chart green
- [DCOS-40780](https://jira.mesosphere.com/browse/DCOS-40780) Can't type in Networks Filter
- [DCOS-40685](https://jira.mesosphere.com/browse/DCOS-40685) When reviewing a service with a long VIP you can not copy it due to truncation
- [DCOS-37789](https://jira.mesosphere.com/browse/DCOS-37789) GPU says NaN in Jobs Config List page
- [DCOS-21187](https://jira.mesosphere.com/browse/DCOS-21187) The preinstall notes are not well formatted
If …
=> chore(dcos-ui): bump DC/OS UI dcos-ui/master+v2.19.4

packages/marathon/buildinfo.json
Improved marathon defaults, and optimised the user experience.
* [DCOS-39290](https://jira.mesosphere.com/browse/DCOS-39290) - Bump Marathon's max_instances_per_offer, task_launch_confirm_timeout, task_launch_timeout, and task_reservation_timeout
* [DCOS-37999](https://jira.mesosphere.com/browse/DCOS-37999) - Loosen constraint validation during migration
* [DCOS_OSS-4007](https://jira.mesosphere.com/browse/DCOS_OSS-4007) - dcos-launch missing docker dependency
* [MARATHON-8394](https://jira.mesosphere.com/browse/MARATHON-8394) - Benchmark Feature Branch
* [MARATHON-8326](https://jira.mesosphere.com/browse/MARATHON-8326) - Add "wipe=true" support for pod's instances endpoint, as it is implemented for app's tasks
* [MARATHON-8381](https://jira.mesosphere.com/browse/MARATHON-8381) - Use …
=> Bumping marathon to 1.7.111

CHANGES.md, dcos_installer/test_backend.py, gen/calc.py
Update version information to 1.12.0-beta1
=> Update version information to 1.12.0-beta1

packages/mesos/extra/make_disk_resources.py
This concerns agents and the file `/var/lib/dcos/mesos-resources`.
We previously used the free space on the agent's mounted volumes
when using `make_disk_resources.py` to create the Mesos resources
file.
We recently saw that the Mesos agent would not restart due to this
behavior for a specific case: a mount volume is used on an agent
by a framework, the agent is stopped and a new volume is mounted.
This is because, when adding an agent, we create again the Mesos
resources file and, if a mount volume is used, its free disk space
will have decreased. Mesos will then not accept to restart as it
cannot find the volume (due to the change of value).
To fix this, we now use a cache to know what was the original free
amount of disk space available on the mount volumes. When the Mesos
resources …
=> [1.11] Check cache when creating Mesos resources using make_disk_resources.py.

CHANGES.md, packages/dcos-ui/build, packages/dcos-ui/buildinfo.json
Updated to [1.11+v1.21.0](https://github.com/dcos/dcos-ui/releases/tag/1.11%2Bv1.21.0)
- [DCOS-41282](https://jira.mesosphere.com/browse/DCOS-41282)
- [DCOS-22310](https://jira.mesosphere.com/browse/DCOS-22310)
- [DCOS-40779](https://jira.mesosphere.com/browse/DCOS-40779)
- [DCOS-40495](https://jira.mesosphere.com/browse/DCOS-40495)
___
**What is the review process and when …
=> UI update to 1.11+v1.21.0

packages/mesos/extra/make_disk_resources.py
This concerns agents and the file `/var/lib/dcos/mesos-resources`.
We previously used the free space on the agent's mounted volumes
when using `make_disk_resources.py` to create the Mesos resources
file.
We recently saw that the Mesos agent would not restart due to this
behavior for a specific case: a mount volume is used on an agent
by a framework, the agent is stopped and a new volume is mounted.
This is because, when adding an agent, we create again the Mesos
resources file and, if a mount volume is used, its free disk space
will have decreased. Mesos will then not accept to restart as it
cannot find the volume (due to the change of value).
To fix this, we now use a cache to know what was the original free
amount of disk space available on the mount volumes. When the Mesos
resources …
=> [1.10] Check cache when creating Mesos resources using make_disk_resources.py.

packages/dcos-diagnostics/buildinfo.json
This changes add better error handling and updates the vendor folder packages:
* github.com/coreos/go-systemd
* github.com/godbus/dbus
Full list of changes https://github.com/dcos/dcos-diagnostics/compare/f0e7cc0eddce6672f45fbb930c0f967023a99fb1...1a532f890b7e05b604309e53b0b5d8f67d1f2940
Bacport:
* https://github.com/dcos/dcos/pull/2389
* https://github.com/dcos/dcos/pull/2390
- [DCOS_OSS-4064](https://jira.mesosphere.com/browse/DCOS_OSS-4064) Bump dcos-diagnostics in 1.10
=> [1.10] Bump dcos-diagnostics

packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch, packages/mesos/extra/patches/0002-Mesos-UI-Change-paths-pailer-and-logs-to-work-with-a.patch, packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch, packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch, packages/mesos/extra/patches/0005-Included-nested-command-check-output-in-the-executor.patch, packages/mesos/extra/patches/0006-Made-the-log-output-handling-of-TCP-and-HTTP-checks-.patch, packages/mesos/extra/patches/0007-Raised-the-logging-level-of-some-check-and-health-ch.patch, packages/mesos/extra/patches/0008-Improved-logging-for-offers-and-inverse-offers.patch, packages/mesos/extra/patches/0009-Logged-the-resources-in-DRF-sorter-CHECKs.patch, packages/mesos/extra/patches/0010-Added-verbose-logging-in-Sorter-Allocation.patch
This backports Mesos commit #f26ffcee0a, in order to improve logging for some checks in the allocator.
- [DCOS_OSS-4086](https://jira.mesosphere.com/browse/DCOS_OSS-4086) Backport Improved Allocator Error Messages for Mesos.
- [COPS-3780](https://jira.mesosphere.com/browse/COPS-3780) Mesos Master frequently goes unhealthy..
The changed code path should never be hit during normal usage.
As above, the changed code path should never be hit during normal usage.
___
**PLEASE FILL IN THE TEMPLATE …
=> [1.10] Backported detailed resource logging for some allocator errors in Mesos.

CHANGES.md, packages/exhibitor/buildinfo.json, packages/flask/buildinfo.json, packages/openssl/buildinfo.json
- Bump ZooKeeper
- Bump OpenSSL
- Editorial edits to CHANGES.md
- https://jira.mesosphere.com/browse/DCOS_OSS-4106
- https://jira.mesosphere.com/browse/DCOS_OSS-4107
- https://jira.mesosphere.com/browse/DCOS_OSS-4109
=> Bump ZooKeeper, OpenSSL (1.11)

packages/telegraf/extra/start_telegraf.sh
=> [1.12.0b1] Ensure that statsd socket is cleaned up before launching telegraf

gen/dcos-config.yaml, packages/dcos-net/buildinfo.json, packages/mesos-modules/buildinfo.json
This patch brings in two fixes:
1. The new docker version (18.x) has changed its iptables CHAIN name from `DOCKER-ISOLATION` to `DOCKER-ISOLATION-STAGE-1` and `DOCKER-ISOLATION-STAGE-2`. As DC/OS overlay modifies docker isolation rules, the change in CHAIN name has broken the DC/OS overlay. This patch bumps mesos-module which fixes the issue
2. The dcos-net watchdog has been modified to restart the stuck Erlang VM. This fix should work as a good workaround till we have the actual fix for the SSL deadlock issue from the Erlang community
- [DCOS-38600](https://jira.mesosphere.com/browse/DCOS-38600) Deadlock when SSL sockets are simultaneously sending/receiving data and buffers are full
- …
=> [Backport] [1.12-beta1] bump mesos-module to bring in fix for SOAK-118

owners.json
This feature improves productivity and velocity.
=> Grant more folks owners karma.

dcos_installer/test_backend.py, gen/calc.py
Update DC/OS Version to 1.11.6
* DCOS-41741 - DC/OS 1.11.6: Update DC/OS version string for OSS and EE
=> update version to 1.11.6.

packages/openssl/buildinfo.json
https://jira.mesosphere.com/browse/DCOS_OSS-4105
=> openssl: bump to 1.0.2p

CHANGES.md, packages/adminrouter/extra/src/includes/http/common.conf
See https://jira.mesosphere.com/browse/DCOS_OSS-4129
https://jira.mesosphere.com/browse/DCOS_OSS-4129
=> adminrouter: modify access_log format (DCOS_OSS-4129)

CHANGES.md, packages/adminrouter/extra/src/includes/http/common.conf, packages/dcos-integration-test/extra/test_dcos_diagnostics.py, packages/dcos-test-utils/buildinfo.json, packages/openssl/buildinfo.json
* Bump dcos-test-utils version #3421
*  Merge dependent tests into one big scenario #3438
* openssl: bump to 1.0.2p #3443
* adminrouter: modify access_log format (DCOS_OSS-4129) #3448
=> 1.12.0 beta2 train

mergebot-config.json
* DCOS-41731 - Mergebot override-status should apply mergebot-override label to the jira issue that tracks the override
=> Update override-status config with JIRA label.

dcos_installer/test_backend.py, gen/calc.py, mergebot-config.json
Update DC/OS version in 1.12 branch to 1.12.0-beta2
=> Update version to 1.12.0-beta2

packages/marathon/buildinfo.json
- [MARATHON-8428](https://jira.mesosphere.com/browse/MARATHON-8428) Populate PodStatus startedAt with instance timestamp.
- [MARATHON-8430](https://jira.mesosphere.com/browse/MARATHON-8430) HTTPS readiness checks do not check certificates.
___ …
=> Bump Marathon on 1.11

CHANGES.md, README.md, dcos_installer/test_backend.py, gen/calc.py, mergebot-config.json
`master` of dcos/dcos is now DC/OS version 1.13
=> Update DC/OS Version for master.

CHANGES.md, dcos_installer/test_backend.py, gen/calc.py
Set 1.11 version to 1.11.7-dev
=> Set 1.11 version to 1.11.7-dev

CHANGES.md, packages/dcos-ui/buildinfo.json
- [DCOS-41862](https://jira.mesosphere.com/browse/DCOS-41862)
- [DCOS-41700](https://jira.mesosphere.com/browse/DCOS-41700)
- [DCOS-41667](https://jira.mesosphere.com/browse/DCOS-41667)
- [DCOS-41661](https://jira.mesosphere.com/browse/DCOS-41661)
- [DCOS-41016](https://jira.mesosphere.com/browse/DCOS-41016)
- [DCOS-41501](https://jira.mesosphere.com/browse/DCOS-41501)
- [DCOS-40644](https://jira.mesosphere.com/browse/DCOS-40644)
- [DCOS_OSS-4033](https://jira.mesosphere.com/browse/DCOS_OSS-4033)
- [DCOS_OSS-526](https://jira.mesosphere.com/browse/DCOS_OSS-526)
- [DCOS-21464](https://jira.mesosphere.com/browse/DCOS-21464)
- …
=> chore: bump UI 1.11+v1.23.0

CHANGES.md, README.md, dcos_installer/test_backend.py, gen/calc.py, mergebot-config.json
Reverts dcos/dcos#3454
* https://jira.mesosphere.com/browse/DCOS-42313 - Version update to 1.13-dev breaks the Universe
=> Revert "Update DC/OS Version for master."

CHANGES.md, packages/dcos-ui/buildinfo.json
Bump UI to v1.22.0
- [DCOS-41862](https://jira.mesosphere.com/browse/DCOS-41862)
- [DCOS-41700](https://jira.mesosphere.com/browse/DCOS-41700)
- [DCOS-41667](https://jira.mesosphere.com/browse/DCOS-41667)
- [DCOS-41661](https://jira.mesosphere.com/browse/DCOS-41661)
- [DCOS-41016](https://jira.mesosphere.com/browse/DCOS-41016)
- [DCOS-41501](https://jira.mesosphere.com/browse/DCOS-41501)
- [DCOS-40644](https://jira.mesosphere.com/browse/DCOS-40644)
- [DCOS_OSS-4033](https://jira.mesosphere.com/browse/DCOS_OSS-4033)
- [DCOS_OSS-526](https://jira.mesosphere.com/browse/DCOS_OSS-526)
- [DCOS-21464](https://jira.mesosphere.com/browse/DCOS-21464)
- [DCOS-15289](https://jira.mesosphere.com/browse/DCOS-15289) …
=> Bump ui to v1.23.0

packages/dcos-integration-test/extra/test_helpers.py, packages/dcos-integration-test/extra/test_networking.py
Debugging apps with just a random hash is hard. This changed introduces
more context to each app name so that they are unique and human
readable.
Please see https://github.com/dcos/dcos/pull/3043.
- [DCOS_OSS-2115](https://jira.mesosphere.com/browse/DCOS_OSS-2115) test_vip failed with RetryError on MarathonApp.wait
___ …
=> Add more context to vip test app names

CHANGES.md
Fix the CHANGES.md for 1.11.7-dev
=> Fixed CHANGES.md for 1.11.7-dev.

CHANGES.md, packages/dcos-ui/buildinfo.json
- [DCOS-41016](https://jira.mesosphere.com/browse/DCOS-41016)
- [DCOS-41502](https://jira.mesosphere.com/browse/DCOS-41502)
- [DCOS-41396](https://jira.mesosphere.com/browse/DCOS-41396)
- [DCOS_OSS-4034](https://jira.mesosphere.com/browse/DCOS_OSS-4034)
- [DCOS_OSS-526](https://jira.mesosphere.com/browse/DCOS_OSS-526)
- [DCOS-21464](https://jira.mesosphere.com/browse/DCOS-21464)
- [DCOS-15289](https://jira.mesosphere.com/browse/DCOS-15289)
- [DCOS-40881](https://jira.mesosphere.com/browse/DCOS-40881) …
=> chore: bump dcos-ui v1.10+v1.10.9-rc3

packages/cosmos/buildinfo.json
release contains fixes for  blockers filed by MKE against cosmos for 1.12 GA
Description of release: https://github.com/dcos/cosmos/releases/tag/v0.6.1
merge all reported blockers from MKE soak test
Cosmos support for MKE operations 
ticket to track release DCOS-42340
Tickets for cosmos blockers: 
DCOS-41745
DCOS-42020
DCOS-41745
If you are changing components or packages in DC/OS …
=> release v0.6.1 cosmos to 1.12

packages/dcos-net/buildinfo.json, packages/erlang/build, packages/erlang/buildinfo.json
Bump dcos-net and upgrade OTP version.
- [DCOS_OSS-3655](https://jira.mesosphere.com/browse/DCOS_OSS-3655) Upgrade OTP version
https://github.com/dcos/dcos-net/compare/1753c7f42cf4577427740e9a23aedb433242b696...e78ab07e5d3f03239b23c24402b38e6ae917ff97
https://github.com/dcos/dcos-net/pull/78
https://github.com/dcos/dcos-net/pull/80
https://circleci.com/gh/dcos/dcos-net/650
https://codecov.io/github/dcos/dcos-net/commit/e78ab07e5d3f03239b23c24402b38e6ae917ff97 …
=> [1.12] Bump dcos-net

packages/cosmos/buildinfo.json
Description of releasew: https://github.com/dcos/cosmos/releases/tag/v0.6.1
merge all reported blockers from MKE soak test
Cosmos support for MKE operations 
ticket to track release DCOS-42340
Tickets for cosmos blockers: 
DCOS-41745
DCOS-42020
DCOS-41745
If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), …
=> release v0.6.1 cosmos

packages/mesos-dns/buildinfo.json
Mesos state.json endpoint has been deprecated in favor of state endpoint. This patch bumps mesos-dns to bring in those changes
- [DCOS_OSS-3941](https://jira.mesosphere.com/browse/DCOS_OSS-3941) mesos-dns is using deprecated mesos endpoint /master/state.json
___
All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-revie …
=> bump mesos-dns to bring in changes for mesos state endpoint

CHANGES.md, packages/dcos-ui/buildinfo.json
- [DCOS-42317](https://jira.mesosphere.com/browse/DCOS-42317)
- [DCOS-42395](https://jira.mesosphere.com/browse/DCOS-42395)
- [DCOS-21232](https://jira.mesosphere.com/browse/DCOS-21232)
- [DCOS-42349](https://jira.mesosphere.com/browse/DCOS-42349)
- [DCOS-42230](https://jira.mesosphere.com/browse/DCOS-42230)
- [DCOS_OSS-1961](https://jira.mesosphere.com/browse/DCOS_OSS-1961)
- [DCOS-41914](https://jira.mesosphere.com/browse/DCOS-41914)
- [DCOS-41922](https://jira.mesosphere.com/browse/DCOS-41922)
- [DCOS-42056](https://jira.mesosphere.com/browse/DCOS-42056)
- …
=> chore(dcos-ui): bump DC/OS UI v2.24.4

dcos_installer/test_backend.py, gen/calc.py
* DCOS-42839 - : Update DC/OS version string for OSS and EE
=> Update version to 1.12.0-rc1

CHANGES.md, packages/marathon/buildinfo.json
Bump Marathon dependency for 1.12.0 release. DCOS-42832
* DCOS-42671
* MARATHON-7941
* MARATHON-8372
* MARATHON-8438
* MARATHON-8420
* MARATHON-8442
* MARATHON-8437
* MARATHON-8436
* MARATHON-8430
* MARATHON-8433
* MARATHON-8434
* MARATHON-8432
* MARATHON-8398
=> Bump Marathon to 1.7.174

packages/metronome/buildinfo.json
Fixed a bug when Metronome did not handle exceptions during startup properly.
- [DCOS_OSS-4239](https://jira.mesosphere.com/browse/DCOS_OSS-4239) Handle exceptions during Metronome startup
- [DCOS_OSS-4261](https://jira.mesosphere.com/browse/DCOS_OSS-4261) Metronome crash looping during the initialization
=> Handle exceptions during Metronome startup

CHANGES.md, packages/dcos-ui/buildinfo.json
- [DCOS-43324](https://jira.mesosphere.com/browse/DCOS-43324) 
- [DCOS-43338](https://jira.mesosphere.com/browse/DCOS-43338)
- [DCOS-41626](https://jira.mesosphere.com/browse/DCOS-41626)
___ …
=> chore(dcos-ui): bump DC/OS UI v2.25.1

CHANGES.md, packages/dcos-metrics/build, packages/dcos-metrics/buildinfo.json, packages/marathon/build
Mergebot Train Pull Request.
This Integration PR consists of the following PRs.
#3531 - Marathon remove precheck on single node 1.11
#3606 - [1.11] Fix panic in metrics agent service when mesos is unavailable
=> 1.11 train 10/17

packages/metronome/buildinfo.json
Fixed a bug when Metronome did not handle exceptions during startup properly.
- [DCOS_OSS-4239](https://jira.mesosphere.com/browse/DCOS_OSS-4239) Handle exceptions during Metronome startup
- [DCOS_OSS-4261](https://jira.mesosphere.com/browse/DCOS_OSS-4261) Metronome crash looping during the initialization
=> Bump to the newest Metronome

build_teamcity_windows.ps1, prep_teamcity_windows.ps1
Adds Powershell equivalents for the Teamcity build scripts.
=> Build teamcity windows

packages/adminrouter/extra/src/README.md, packages/adminrouter/extra/src/lib/auth/common.lua, packages/adminrouter/extra/src/lib/auth/open.lua, packages/adminrouter/extra/src/lib/resty/README.md, packages/adminrouter/extra/src/lib/resty/evp.lua, packages/adminrouter/extra/src/lib/resty/hmac.lua, packages/adminrouter/extra/src/lib/resty/jwt-validators.lua, packages/adminrouter/extra/src/lib/resty/jwt.lua, packages/adminrouter/extra/src/test-harness/modules/runner/open.py, packages/adminrouter/extra/src/test-harness/tests/conftest.py, packages/adminrouter/extra/src/test-harness/tests/open/test_auth.py, packages/adminrouter/extra/src/test-harness/tests/open/test_master.py, packages/adminrouter/extra/src/test-harness/tests/test_auth.py, packages/adminrouter/extra/src/test-harness/tests/test_boot_envvars.py, packages/adminrouter/extra/systemd/dcos-adminrouter.service
- README updates
- lua-resty-jwt version bump
- AR authentication arch changes
- corresponding adjustment of the AR test harness
=> Alignment of authentication architectures: start to adjust Admin Router (iteration 1)

gen/dcos-config.yaml, packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Currently, we pull overlay endpoints to diagnostic bundle
* `:5050/overlay-master/state`
* `:5051/overlay-agent/overlay`
This PR will remove these endpoints when the overlay is [disabled](https://docs.mesosphere.com/1.12/installing/production/advanced-configuration/configuration-reference/#dcos-overlay-enable).
- [DCOS_OSS-4250](https://jira.mesosphere.com/browse/DCOS_OSS-4250) Avoid failure when overlay and related endpoints are not available
___ …
=> Do not pull overlay data when overlay is disable

CHANGES.md, packages/dcos-ui/buildinfo.json
- [DCOS-42348 [1.11] DC/OS UI fails to show sandbox logs on soak-112s.](https://jira.mesosphere.com/browse/DCOS-42348)
- [DCOS-42243 [1.11] Catalog filter is not ranked well](https://jira.mesosphere.com/browse/DCOS-42243)
- [DCOS-42035 Backport DCOS-20222](https://jira.mesosphere.com/browse/DCOS-42035)
- [DCOS-42365 [1.11] Pod instance shows incorrect memory total](https://jira.mesosphere.com/browse/DCOS-42365)
- [DCOS-41924 [1.11] Display the Framework form if able](https://jira.mesosphere.com/browse/DCOS-41924)
- [DCOS-42326 Backport DCOS_OSS-1961 to 1.11](https://jira.mesosphere.com/browse/DCOS-42326)
Other tickets related to …
=> chore(dcos-ui): bump package to 1.11+v1.24.0

dcos_installer/test_backend.py, gen/calc.py
Update DC/OS version to 1.12.0
=> Update version to 1.12.0

CHANGES.md, packages/dcos-ui/buildinfo.json
- [DCOS-42366](https://jira.mesosphere.com/browse/DCOS-42366) fix(PodInstancesTable): clarify resource totals on pod instances table
- [DCOS-42347](https://jira.mesosphere.com/browse/DCOS-42347) fix(MesosLog): show error when logs can not be loaded
- [DCOS-42035](https://jira.mesosphere.com/browse/DCOS-42035) feat(ServiceForm): add error for environment values without keys
- [DCOS-42054](https://jira.mesosphere.com/browse/DCOS-42054) fix(Services): environment labels show error
- [DCOS-41903](https://jira.mesosphere.com/browse/DCOS-41903) fix(NetworkingFormSection): enable service endpoints ucr
- …
=> Bump dcos-ui v1.10-1.10.9

gen/dcos-config.yaml, packages/dcos-integration-test/extra/test_dcos_diagnostics.py
Currently, we pull overlay endpoints to diagnostic bundle
* `:5050/overlay-master/state`
* `:5051/overlay-agent/overlay`
This PR will remove these endpoints when the overlay is [disabled](https://docs.mesosphere.com/1.12/installing/production/advanced-configuration/configuration-reference/#dcos-overlay-enable).
- [DCOS_OSS-4250](https://jira.mesosphere.com/browse/DCOS_OSS-4250) Avoid failure when overlay and related endpoints are not available
___ …
=> [1.12] Do not pull overlay data when overlay is disable

packages/dcos-diagnostics/buildinfo.json
* Update dcos-diagnostics to the latest version with small fixes and upgraded dependencies
- [DCOS_OSS-4322](https://jira.mesosphere.com/browse/DCOS_OSS-4322) 
=> [1.12] Update dcos-diagnostics

packages/erlang/build
Fix TLS handshake for RSA based end-entity certificate signed by EC based CA with TLS insufficient security alert.
- [DCOS-44367](https://bugs.erlang.org/browse/DCOS-44367) [ERL-763] TLS handshake fails for RSA based end-entity certificate signed by EC based CA with TLS insufficient security alert
- [ERL-763](https://bugs.erlang.org/browse/ERL-763) TLS handshake fails for RSA based end-entity certificate signed by EC based CA with TLS insufficient security alert
___
**PLEASE FILL IN THE …
=> Fix TLS handshake

CHANGES.md, docs/admin-ports.md, gen/dcos-config.yaml, mergebot-config.json, packages/dcos-integration-test/extra/test_metrics.py, packages/dcos-log/buildinfo.json, packages/docker-gc/extra/dcos-docker-gc.service, packages/erlang/build
Updating the fixVersions because Mergebot doesn't have the AI feature…  
#3748
Fix TLS handshake
#3718
Docker gc log fix  Ship It
#3710
Bump dcos-log  Ship It
#3644
Enable statsd plugin on telegraf  Ship It
#3636
=> Train master 11/08/2018

packages/erlang/build
Fix TLS handshake for RSA based end-entity certificate signed by EC based CA with TLS insufficient security alert.
- [DCOS-44367](https://bugs.erlang.org/browse/DCOS-44367) [ERL-763] TLS handshake fails for RSA based end-entity certificate signed by EC based CA with TLS insufficient security alert
- [ERL-763](https://bugs.erlang.org/browse/ERL-763) TLS handshake fails for RSA based end-entity certificate signed by EC based CA with TLS insufficient security alert
___
**PLEASE FILL IN THE …
=> [1.12] Fix TLS handshake

mergebot-config.json
=> Updating fixVersion data for Mergebot

mergebot-config.json, packages/erlang/build
Updating fixVersion data for Mergebot
#3750
[1.12] Fix TLS handshake
#3716
=> 1.12 train

packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch, packages/mesos/extra/patches/0002-Mesos-UI-Change-paths-pailer-and-logs-to-work-with-a.patch, packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch, packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch, packages/mesos/extra/patches/0005-Included-nested-command-check-output-in-the-executor.patch, packages/mesos/extra/patches/0006-Made-the-log-output-handling-of-TCP-and-HTTP-checks-.patch, packages/mesos/extra/patches/0007-Raised-the-logging-level-of-some-check-and-health-ch.patch, packages/mesos/extra/patches/0008-Improved-logging-for-offers-and-inverse-offers.patch, packages/mesos/extra/patches/0009-Logged-the-resources-in-DRF-sorter-CHECKs.patch, packages/mesos/extra/patches/0010-Added-verbose-logging-in-Sorter-Allocation.patch, packages/mesos/extra/patches/0011-Put-TerminateEvent-at-the-end-of-the-queue-in-the-Me.patch, packages/mesos/extra/patches/0012-Waited-for-TEARDOWN-to-be-sent-in-v1-Java-scheduler-.patch, packages/mesos/extra/patches/0013-Added-task-health-check-definitions-to-master-API-re.patch
This PR adds a patch on top of OSS Mesos which includes task health check definitions in Mesos master API outputs.
The related ticket for this PR exists in OSS Mesos JIRA:
- [MESOS-8780](https://issues.apache.org/jira/browse/MESOS-8780) Expose Check and HealthCheck information on Mesos HTTP endpoints.
___ …
=> [1.10] Added Mesos patch to include health checks in master API outputs.

packages/mesos/extra/patches/0001-Set-LIBPROCESS_IP-into-docker-container.patch, packages/mesos/extra/patches/0002-Mesos-UI-updated-the-URL-generation-to-make-it-work-.patch, packages/mesos/extra/patches/0003-Revert-Fixed-the-broken-metrics-information-of-maste.patch, packages/mesos/extra/patches/0004-Updated-mesos-containerizer-to-ignore-GPU-isolator-c.patch, packages/mesos/extra/patches/0005-Displayed-resource-provider-resources-in-GET_RESOURC.patch, packages/mesos/extra/patches/0006-Improved-logging-for-offers-and-inverse-offers.patch, packages/mesos/extra/patches/0007-Introduced-a-push-based-gauge-metric.patch, packages/mesos/extra/patches/0008-Added-a-test-for-PushGauge.patch, packages/mesos/extra/patches/0009-Renamed-Gauge-to-PullGauge-and-documented-difference.patch, packages/mesos/extra/patches/0010-Updated-mesos-source-for-Gauge-PullGauge-renaming.patch, packages/mesos/extra/patches/0011-Enabled-per-framework-metrics-in-the-master.patch, packages/mesos/extra/patches/0012-Added-per-framework-subscribed-metric-and-helpers.patch, packages/mesos/extra/patches/0013-Added-per-framework-metrics-for-scheduler-calls.patch, packages/mesos/extra/patches/0014-Added-per-framework-metrics-for-scheduler-events.patch, packages/mesos/extra/patches/0015-Added-per-framework-offer-metrics.patch, packages/mesos/extra/patches/0016-Added-per-framework-metrics-for-task-states.patch, packages/mesos/extra/patches/0017-Added-per-framework-metrics-for-offer-operations.patch, packages/mesos/extra/patches/0018-Enabled-per-framework-metrics-in-the-allocator.patch, packages/mesos/extra/patches/0019-Changed-the-capacity_-member-of-BoundedHashMap-to-no.patch, packages/mesos/extra/patches/0020-Tracked-completed-framework-metrics-in-the-allocator.patch, packages/mesos/extra/patches/0021-Added-per-framework-metrics-for-suppressed-roles.patch, packages/mesos/extra/patches/0022-Added-task-health-check-definitions-to-master-API-re.patch
This PR adds a patch on top of OSS Mesos which includes task health check definitions in Mesos master API outputs.
The related ticket for this PR exists in OSS Mesos JIRA:
- [MESOS-8780](https://issues.apache.org/jira/browse/MESOS-8780) Expose Check and HealthCheck information on Mesos HTTP endpoints.
___ …
=> [1.11] Added Mesos patch to include health checks in master API outputs.

packages/cosmos/buildinfo.json
[DCOS-44443](https://jira.mesosphere.com/browse/DCOS-44443) Remove the deprecated `DCOS_PACKAGE_METADATA` label.
- [DCOS-44443](https://jira.mesosphere.com/browse/DCOS-44443) Remove the deprecated `DCOS_PACKAGE_METADATA` label.
___ …
=> Bump cosmos to latest version

gen/dcos-config.yaml, packages/adminrouter/extra/src/README.md
Admin Router: adding clarifications of limitations to Readme
- [DCOS-42624](https://jira.mesosphere.com/browse/DCOS-42624) Master Admin Router responds 404 on /service/jenkinsX.
___ …
=> Admin Router: adding clarifications of limitations to Readme

README.md
This updates the README to use the latest DC/OS E2E interface.
- [DCOS_OSS-4478](https://jira.mesosphere.com/browse/DCOS_OSS-4478) DC/OS E2E - Run commands are confusing before the test environment is available
=> Update README example for running command to new DC/OS E2E CLI

CHANGES.md, packages/dcos-ui/buildinfo.json
DCOS-43779
DCOS-40871
DCOS-46676
DCOS-43897
DCOS-44017
DCOS_OSS-4245
DCOS-44456
DCOS-43383
DCOS-42974
DCOS-44138
DCOS-43375
DCOS-41415
DCOS-43373
DCOS-43340
DCOS-41578
DCOS-43461
DCOS-43349
DCOS-43087
DCOS_OSS-4270
DCOS_OSS-4273
DCOS_OSS-2358
DCOS-43041
DCOS-43050
DCOS-43055
DCOS-40640
___ …
=> bump ui version to 2.36.5
